SUMO - Simulation of Urban MObility: PCLoaderVisum Class Reference
PCLoaderVisum Class Reference
A reader of pois and polygons stored in VISUM-format.
#include <PCLoaderVisum.h>
Static Public Member Functions
static void loadIfSet (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois/polygons assumed to be stored using VISUM-format.
Static Protected Member Functions
static void load (const std::string &file, OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Parses pois/polys stored within the given file.
Detailed Description
A reader of pois and polygons stored in VISUM-format.
Definition at line 52 of file PCLoaderVisum.h.
Member Function Documentation
void PCLoaderVisum::load (const std::string & file, OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static, protected]
Parses pois/polys stored within the given file.
Parameters:
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions:
ProcessError if something fails
hmmmm - assume it's sorted...
Definition at line 86 of file PCLoaderVisum.cpp.
References PositionVector::clear(), PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, PCTypeMap::get(), NamedColumnsParser::get(), OptionsCont::getBool(), OptionsCont::getInt(), GeoConvHelper::getProcessing(), OptionsCont::getString(), PCTypeMap::has(), LineReader::hasMore(), PCTypeMap::TypeDef::id, PCPolyContainer::insert(), PCTypeMap::TypeDef::layer, StringTokenizer::next(), RGBColor::parseColor(), NamedColumnsParser::parseLine(), PCTypeMap::TypeDef::prefix, PositionVector::push_back(), LineReader::readLine(), LineReader::reinit(), NamedColumnsParser::reinit(), SUMOReal, toString(), WRITE_ERROR, WRITE_WARNING, and GeoConvHelper::x2cartesian().
Referenced by loadIfSet().
void PCLoaderVisum::loadIfSet (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static]
Loads pois/polygons assumed to be stored using VISUM-format.
If the option "visum-files" is set within the given options container, the files stored herein are parsed using "load", assuming this option contains file paths to files containing pois and polygons stored in VISUM ".net"-format.
Parameters:
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions:
ProcessError if something fails
Definition at line 66 of file PCLoaderVisum.cpp.
References FileHelpers::exists(), OptionsCont::getStringVector(), OptionsCont::isSet(), load(), PROGRESS_BEGIN_MESSAGE, and PROGRESS_DONE_MESSAGE.
Referenced by main().
The documentation for this class was generated from the following files:
PCLoaderVisum.h
PCLoaderVisum.cpp