SUMO - Simulation of Urban MObility: TraCIServerAPI_Route Class Reference
TraCIServerAPI_Route Class Reference
APIs for getting/setting route values via TraCI.
#include <TraCIServerAPI_Route.h>
Static Public Member Functions
static bool processGet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa6: Get Route Variable).
static bool processSet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc6: Change Route State).
Private Member Functions
TraCIServerAPI_Route & operator= (const TraCIServerAPI_Route &s)
invalidated assignment operator
TraCIServerAPI_Route (const TraCIServerAPI_Route &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting route values via TraCI.
Definition at line 46 of file TraCIServerAPI_Route.h.
Constructor & Destructor Documentation
TraCIServerAPI_Route::TraCIServerAPI_Route (const TraCIServerAPI_Route & s) [private]
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_Route& TraCIServerAPI_Route::operator= (const TraCIServerAPI_Route & s) [private]
invalidated assignment operator
bool TraCIServerAPI_Route::processGet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) [static]
Processes a get value command (Command 0xa6: Get Route Variable).
Parameters:
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 54 of file TraCIServerAPI_Route.cpp.
References MSRoute::begin(), CMD_GET_ROUTE_VARIABLE, MSRoute::dictionary(), MSRoute::end(), ID_COUNT, ID_LIST, MSRoute::insertIDs(), RESPONSE_GET_ROUTE_VARIABLE, RTYPE_ERR, RTYPE_OK, MSRoute::size(), TYPE_INTEGER, TYPE_STRINGLIST, VAR_EDGES, traci::TraCIServer::writeResponseWithLength(), and traci::TraCIServer::writeStatusCmd().
bool TraCIServerAPI_Route::processSet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) [static]
Processes a set value command (Command 0xc6: Change Route State).
Parameters:
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 107 of file TraCIServerAPI_Route.cpp.
References ADD, CMD_SET_ROUTE_VARIABLE, RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSEdge::dictionary(), RTYPE_ERR, RTYPE_OK, TYPE_STRINGLIST, and traci::TraCIServer::writeStatusCmd().
The documentation for this class was generated from the following files:
TraCIServerAPI_Route.h
TraCIServerAPI_Route.cpp