SUMO - Simulation of Urban MObility: MSBaseVehicle Class Reference
MSBaseVehicle Class Reference
The base class for microscopic and mesoscopic vehicles.
#include <MSBaseVehicle.h>
Public Member Functions
virtual void activateReminders (const MSMoveReminder::Notification reason)
"Activates" all current move reminder
virtual SUMOReal adaptMaxSpeed (SUMOReal referenceSpeed)=0
Adapt the vehicle's maximum speed depending on the reference speed.
double adaptMaxSpeed (double referenceSpeed)
Adapts the current maximum speed using the distribution given in the type.
virtual void addPerson (MSPerson *person)
Adds a person to this vehicle.
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::string & getID () const
Returns the name of the vehicle.
double getMaxSpeed () const
Returns the current maximum speed.
const MSVehicleType * getMyType () const
unsigned int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition).
virtual SUMOReal getPositionOnLane () const =0
Get the vehicle's position along the lane.
virtual double getPreDawdleAcceleration () const
Returns the vehicle's acceleration before dawdling.
const MSRoute & getRoute () const
Returns the current route.
virtual SUMOReal getSpeed () const =0
Returns the vehicle's current speed.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
bool hasValidRoute (std::string &msg) const
Validates the current route.
virtual bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated).
virtual bool isStopped () const
Returns whether the vehicle is at a stop.
MSBaseVehicle (SUMOVehicleParameter *pars, const MSRoute *route, const MSVehicleType *type)
Constructor.
void onDepart ()
Called when the vehicle is inserted into the network.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
virtual bool replaceRoute (const MSRoute *route, bool onInit=false)=0
Replaces the current route by the given one.
bool replaceRouteEdges (const MSEdgeVector &edges, bool onInit=false)
Replaces the current route by the given edges.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, bool withTaz=false)
Performs a rerouting using the given router.
const MSEdge * succEdge (unsigned int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
virtual ~MSBaseVehicle ()
Destructor.
Protected Member Functions
void calculateArrivalPos ()
(Re-)Calculates the arrival position from the vehicle parameters
Protected Attributes
double myArrivalPos
the position on the destination lane where the vehicle stops
MSRouteIterator myCurrEdge
Iterator to current route-edge.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
bool myHasIndividualMaxSpeed
is true if there has an individual speed been set
double myIndividualMaxSpeed
unsigned int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This Vehicle's parameter.
double myReferenceSpeed
the speed which served as reference when calculating the individual maxspeed
const MSRoute * myRoute
This Vehicle's route.
const MSVehicleType * myType
This Vehicle's type.
Move reminder structures
Definition of a move reminder container
typedef std::vector< std::pair
< MSMoveReminder *, double > > MoveReminderCont
MoveReminderCont myMoveReminders
Current lane's move reminder.
Detailed Description
The base class for microscopic and mesoscopic vehicles.
Definition at line 57 of file MSBaseVehicle.h.
Member Typedef Documentation
typedef std::vector<std::pair<MSMoveReminder*,double> > MSBaseVehicle::MoveReminderCont [protected]
Definition at line 234 of file MSBaseVehicle.h.
Constructor & Destructor Documentation
MSBaseVehicle::MSBaseVehicle (SUMOVehicleParameter * pars, const MSRoute * route, const MSVehicleType * type)
Constructor.
Definition at line 57 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSDevice_FEV::buildVehicleDevices(), MSDevice_HBEFA::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSDevice_Tripinfo::buildVehicleDevices(), MSDevice_Vehroutes::buildVehicleDevices(), calculateArrivalPos(), myDevices, myMoveReminders, and myRoute.
MSBaseVehicle::~MSBaseVehicle () [virtual]
Destructor.
Definition at line 85 of file MSBaseVehicle.cpp.
References myDevices, myParameter, myRoute, and MSRoute::release().
Member Function Documentation
void MSBaseVehicle::activateReminders (const MSMoveReminder::Notification reason) [virtual]
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters:
[in] reason The reason for changing the reminders' states
See also:
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented in MSVehicle.
Definition at line 279 of file MSBaseVehicle.cpp.
References myMoveReminders.
virtual SUMOReal SUMOVehicle::adaptMaxSpeed (SUMOReal referenceSpeed) [pure virtual, inherited]
Adapt the vehicle's maximum speed depending on the reference speed.
Parameters:
[in] the maximum speed on the edge
Returns:
The vehicle's new maximum speed
double MSBaseVehicle::adaptMaxSpeed (double referenceSpeed)
Adapts the current maximum speed using the distribution given in the type.
Returns:
The vehicle's new maximum speed
void MSBaseVehicle::addPerson (MSPerson * person) [virtual]
Adds a person to this vehicle.
The default implementation does nothing since persons are not supported by default
Parameters:
[in] person The person to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 230 of file MSBaseVehicle.cpp.
void MSBaseVehicle::addReminder (MSMoveReminder * rem)
Adds a MoveReminder dynamically.
Parameters:
[in] rem the reminder to add
See also:
MSMoveReminder
Definition at line 262 of file MSBaseVehicle.cpp.
References myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), and MSVehicle::enterLaneAtLaneChange().
void MSBaseVehicle::calculateArrivalPos () [protected]
(Re-)Calculates the arrival position from the vehicle parameters
Definition at line 291 of file MSBaseVehicle.cpp.
References ARRIVAL_POS_DEFAULT, ARRIVAL_POS_GIVEN, ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, MSEdge::getLanes(), MSRoute::getLastEdge(), MAX2(), MIN2(), myArrivalPos, myParameter, myRoute, RandHelper::rand(), and SUMOReal.
Referenced by MSBaseVehicle(), and MSVehicle::replaceRoute().
SUMOTime MSBaseVehicle::getDeparture () const [virtual]
Returns this vehicle's real departure time.
Returns:
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 218 of file MSBaseVehicle.cpp.
References myDeparture.
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const [inline, virtual]
Returns this vehicle's devices.
Returns:
This vehicle's devices
Implements SUMOVehicle.
Definition at line 164 of file MSBaseVehicle.h.
References myDevices.
Referenced by MSVehicle::moveChecked(), and MSVehicle::writeSyntheticData().
const MSEdge * MSBaseVehicle::getEdge () const [virtual]
Returns the edge the vehicle is currently at.
Returns:
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 152 of file MSBaseVehicle.cpp.
References myCurrEdge.
Referenced by MSVehicleTransfer::addVeh(), MSVehicleTransfer::checkInsertions(), and TraCIServerAPI_Vehicle::commandDistanceRequest().
const std::string & MSBaseVehicle::getID () const [virtual]
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 95 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and myParameter.
Referenced by MSVehicleTransfer::checkInsertions(), MSLane::detectCollisions(), MSVTypeProbe::execute(), MSLane::isInsertionSuccess(), MSCFModel_KraussOrig1::moveHelper(), TraCIServerAPI_Vehicle::processSet(), MSLane::removeVehicle(), replaceRouteEdges(), reroute(), MSLane::setCritical(), MSVehicle::writeSyntheticData(), and MSXMLRawOut::writeVehicle().
SUMOReal MSBaseVehicle::getMaxSpeed () const [virtual]
Returns the current maximum speed.
Returns:
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 119 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), myHasIndividualMaxSpeed, myIndividualMaxSpeed, and myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), GUIVehicle::getColorValue(), MSLane::insertVehicle(), and MSVehicle::moveChecked().
const MSVehicleType * MSBaseVehicle::getMyType () const
Definition at line 311 of file MSBaseVehicle.cpp.
References myType.
Referenced by MSVehicle::writeSyntheticData().
unsigned int MSBaseVehicle::getNumberReroutes () const [virtual]
Returns the number of new routes this vehicle got.
Returns:
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 224 of file MSBaseVehicle.cpp.
References myNumberReroutes.
Referenced by GUIVehicle::drawGLAdditional(), GUIVehicle::getColorValue(), and replaceRouteEdges().
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const [virtual]
Returns the vehicle's parameter (including departure definition).
Returns:
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 101 of file MSBaseVehicle.cpp.
References myParameter.
Referenced by MSPersonControl::boardAnyWaiting(), MSEdge::getDepartLane(), GUIVehicle::getParameterWindow(), MSLane::insertVehicle(), TraCIServerAPI_Vehicle::processGet(), and GUIVehicle::setFunctionalColor().
virtual SUMOReal SUMOVehicle::getPositionOnLane () const [pure virtual, inherited]
Get the vehicle's position along the lane.
Returns:
The position of the vehicle (in m from the lane's begin)
Implemented in MSVehicle.
Referenced by MSInstantInductLoop::notifyEnter(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), and MSE2Collector::by_vehicle_position_sorter::operator()().
SUMOReal MSBaseVehicle::getPreDawdleAcceleration () const [virtual]
Returns the vehicle's acceleration before dawdling.
This default implementation returns always 0.
Returns:
The acceleration before dawdling
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 205 of file MSBaseVehicle.cpp.
const MSRoute & MSBaseVehicle::getRoute () const [virtual]
Returns the current route.
Returns:
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 107 of file MSBaseVehicle.cpp.
References myRoute.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), MSVehicle::enterLaneAtLaneChange(), MSEdge::getDepartLane(), getMaxSpeedRegardingNextLanes(), MSLane::isInsertionSuccess(), TraCIServerAPI_Vehicle::processGet(), and GUIVehicle::setFunctionalColor().
virtual SUMOReal SUMOVehicle::getSpeed () const [pure virtual, inherited]
Returns the vehicle's current speed.
Returns:
The vehicle's speed
Implemented in MSVehicle.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSE3Collector::detectorUpdate(), MSE3Collector::enter(), MSE3Collector::leave(), MSDevice_Tripinfo::notifyEnter(), MSInstantInductLoop::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), and TraCIServerAPI_Vehicle::processSet().
const MSVehicleType & MSBaseVehicle::getVehicleType () const [virtual]
Returns the vehicle's type definition.
Returns:
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 113 of file MSBaseVehicle.cpp.
References myType.
Referenced by MSLaneChanger::change(), MSVehicleTransfer::checkInsertions(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), drawAction_drawBlinker(), drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), GUIVehicle::drawGL(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), MSVTypeProbe::execute(), MSLane::freeInsertion(), MSVehicle::gap2pred(), MSEdge::getDepartLane(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealThisLeader(), MSLane::incorporateVehicle(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MSLane::leftByLaneChange(), MSCFModel::leftVehicleVsafe(), MSLane::maxSpeedGapInsertion(), MSVehicle::moveChecked(), MSVehicle::overlap(), MSAbstractLaneChangeModel::predInteraction(), TraCIServerAPI_Vehicle::processGet(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), MSLane::removeVehicle(), MSLane::setCritical(), GUIVehicle::setFunctionalColor(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
bool MSBaseVehicle::hasValidRoute (std::string & msg) const
Validates the current route.
Parameters:
[out] msg Description why the route is not valid (if it is the case)
Returns:
Whether the vehicle's current route is valid
Definition at line 240 of file MSBaseVehicle.cpp.
References MSRoute::end(), MSVehicleType::getVehicleClass(), myCurrEdge, myRoute, and myType.
Referenced by TraCIServerAPI_Vehicle::processGet().
virtual bool MSBaseVehicle::isOnRoad () const [inline, virtual]
Returns the information whether the vehicle is on a road (is simulated).
Returns:
Whether the vehicle is simulated
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 114 of file MSBaseVehicle.h.
bool MSBaseVehicle::isStopped () const [virtual]
Returns whether the vehicle is at a stop.
Returns:
Whether it has stopped
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 234 of file MSBaseVehicle.cpp.
void MSBaseVehicle::onDepart () [virtual]
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 211 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSNet::getVehicleControl(), myDeparture, and MSVehicleControl::vehicleDeparted().
void MSBaseVehicle::removeReminder (MSMoveReminder * rem)
Removes a MoveReminder dynamically.
Parameters:
[in] rem the reminder to remove
See also:
MSMoveReminder
Definition at line 268 of file MSBaseVehicle.cpp.
References myMoveReminders.
virtual bool SUMOVehicle::replaceRoute (const MSRoute * route, bool onInit = false) [pure virtual, inherited]
Replaces the current route by the given one.
Implemented in MSVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), TraCIServerAPI_Vehicle::processSet(), and replaceRouteEdges().
bool MSBaseVehicle::replaceRouteEdges (const MSEdgeVector & edges, bool onInit = false) [virtual]
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters:
[in] edges The new list of edges to pass
[in] simTime The time at which the route was replaced
Returns:
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 179 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::dictionary(), MSRoute::getColor(), Named::getID(), getID(), getNumberReroutes(), MSRoute::getStops(), myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), and toString().
Referenced by TraCIServerAPI_Vehicle::processSet(), and reroute().
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, bool withTaz = false) [virtual]
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters:
[in] t The time for which the route is computed
[in] router The router to use
See also:
replaceRoute
Implements SUMOVehicle.
Definition at line 158 of file MSBaseVehicle.cpp.
References SUMOAbstractRouter< E, V >::compute(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, getID(), MSRoute::getLastEdge(), myCurrEdge, myParameter, myRoute, replaceRouteEdges(), SUMOVehicleParameter::toTaz, and WRITE_WARNING.
const MSEdge * MSBaseVehicle::succEdge (unsigned int nSuccs) const [virtual]
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters:
[in] nSuccs The number of edge to look forward
Returns:
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 142 of file MSBaseVehicle.cpp.
References myCurrEdge.
Referenced by MSVehicleTransfer::addVeh(), and MSVehicleTransfer::checkInsertions().
Field Documentation
double MSBaseVehicle::myArrivalPos [protected]
the position on the destination lane where the vehicle stops
Definition at line 243 of file MSBaseVehicle.h.
Referenced by calculateArrivalPos(), MSVehicle::ends(), and MSVehicle::getBestLanes().
MSRouteIterator MSBaseVehicle::myCurrEdge [protected]
Iterator to current route-edge.
Definition at line 221 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::ends(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::getBestLanes(), getEdge(), hasValidRoute(), MSVehicle::moveChecked(), MSVehicle::replaceRoute(), reroute(), succEdge(), and MSVehicle::willPass().
SUMOTime MSBaseVehicle::myDeparture [protected]
The real departure time.
Definition at line 241 of file MSBaseVehicle.h.
Referenced by getDeparture(), and onDepart().
std::vector<MSDevice*> MSBaseVehicle::myDevices [protected]
The devices this vehicle has.
Definition at line 239 of file MSBaseVehicle.h.
Referenced by MSVehicle::addPerson(), getDevices(), GUIVehicle::GUIVehicle(), MSBaseVehicle(), and ~MSBaseVehicle().
bool MSBaseVehicle::myHasIndividualMaxSpeed [protected]
is true if there has an individual speed been set
Definition at line 228 of file MSBaseVehicle.h.
Referenced by getMaxSpeed(), MSVehicle::setIndividualMaxSpeed(), and MSVehicle::unsetIndividualMaxSpeed().
double MSBaseVehicle::myIndividualMaxSpeed [protected]
An individual speed for an vehicle that is used (iff set) instead of the maximal speed of the vehicle class. NOTE: This is just a little workaround for allowing an external influence on the actual speed
Definition at line 226 of file MSBaseVehicle.h.
Referenced by getMaxSpeed(), and MSVehicle::setIndividualMaxSpeed().
MoveReminderCont MSBaseVehicle::myMoveReminders [protected]
Current lane's move reminder.
Definition at line 236 of file MSBaseVehicle.h.
Referenced by MSVehicle::activateReminders(), activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addPerson(), addReminder(), GUIVehicle::GUIVehicle(), MSVehicle::leaveLane(), MSBaseVehicle(), and removeReminder().
unsigned int MSBaseVehicle::myNumberReroutes [protected]
The number of reroutings.
Definition at line 246 of file MSBaseVehicle.h.
Referenced by getNumberReroutes(), and MSVehicle::replaceRoute().
const SUMOVehicleParameter* MSBaseVehicle::myParameter [protected]
This Vehicle's parameter.
Definition at line 215 of file MSBaseVehicle.h.
Referenced by calculateArrivalPos(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBestLanes(), getID(), getParameter(), MSVehicle::moveChecked(), reroute(), and ~MSBaseVehicle().
double MSBaseVehicle::myReferenceSpeed [protected]
the speed which served as reference when calculating the individual maxspeed
Definition at line 230 of file MSBaseVehicle.h.
const MSRoute* MSBaseVehicle::myRoute [protected]
This Vehicle's route.
Definition at line 217 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), calculateArrivalPos(), GUIVehicle::drawRoute(), MSVehicle::ends(), MSVehicle::getBestLanes(), getRoute(), hasValidRoute(), MSVehicle::moveChecked(), MSBaseVehicle(), MSVehicle::replaceRoute(), replaceRouteEdges(), reroute(), MSVehicle::willPass(), and ~MSBaseVehicle().
const MSVehicleType* MSBaseVehicle::myType [protected]
This Vehicle's type.
Definition at line 219 of file MSBaseVehicle.h.
Referenced by MSVehicle::getAngle(), MSVehicle::getBestLanes(), MSVehicle::getCarFollowModel(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHBEFA_CO2Emissions(), MSVehicle::getHBEFA_COEmissions(), MSVehicle::getHBEFA_FuelConsumption(), MSVehicle::getHBEFA_HCEmissions(), MSVehicle::getHBEFA_NOxEmissions(), MSVehicle::getHBEFA_PMxEmissions(), getMaxSpeed(), getMyType(), GUIVehicle::getParameterWindow(), getVehicleType(), hasValidRoute(), MSVehicle::replaceVehicleType(), and MSVehicle::~MSVehicle().
The documentation for this class was generated from the following files:
MSBaseVehicle.h
MSBaseVehicle.cpp