SUMO - Simulation of Urban MObility: MFXEventQue Class Reference
MFXEventQue Class Reference
#include <MFXEventQue.h>
Public Member Functions
void add (void *what)
bool empty ()
MFXEventQue ()
void pop ()
size_t size ()
void * top ()
~MFXEventQue ()
Private Attributes
std::list< void * > myEvents
MFXMutex myMutex
Detailed Description
Definition at line 37 of file MFXEventQue.h.
Constructor & Destructor Documentation
MFXEventQue::MFXEventQue () [inline]
Definition at line 39 of file MFXEventQue.h.
MFXEventQue::~MFXEventQue () [inline]
Definition at line 40 of file MFXEventQue.h.
Member Function Documentation
void MFXEventQue::add (void * what)
Definition at line 57 of file MFXEventQue.cpp.
References MFXMutex::lock(), myEvents, myMutex, and MFXMutex::unlock().
Referenced by GUIRunThread::makeStep(), GUIRunThread::retrieveMessage(), GUILoadThread::retrieveMessage(), and GUILoadThread::submitEndAndCleanup().
bool MFXEventQue::empty ()
Definition at line 74 of file MFXEventQue.cpp.
References MFXMutex::lock(), myMutex, size(), and MFXMutex::unlock().
Referenced by GUIApplicationWindow::eventOccured(), and GUIApplicationWindow::~GUIApplicationWindow().
void MFXEventQue::pop ()
Definition at line 49 of file MFXEventQue.cpp.
References MFXMutex::lock(), myEvents, myMutex, and MFXMutex::unlock().
Referenced by GUIApplicationWindow::eventOccured(), and GUIApplicationWindow::~GUIApplicationWindow().
size_t MFXEventQue::size ()
Definition at line 65 of file MFXEventQue.cpp.
References MFXMutex::lock(), myEvents, myMutex, and MFXMutex::unlock().
Referenced by empty(), and top().
void * MFXEventQue::top ()
Definition at line 39 of file MFXEventQue.cpp.
References MFXMutex::lock(), myEvents, myMutex, size(), and MFXMutex::unlock().
Referenced by GUIApplicationWindow::eventOccured(), and GUIApplicationWindow::~GUIApplicationWindow().
Field Documentation
std::list<void*> MFXEventQue::myEvents [private]
Definition at line 49 of file MFXEventQue.h.
Referenced by add(), pop(), size(), and top().
MFXMutex MFXEventQue::myMutex [private]
Definition at line 48 of file MFXEventQue.h.
Referenced by add(), empty(), pop(), size(), and top().
The documentation for this class was generated from the following files:
MFXEventQue.h
MFXEventQue.cpp