SUMO - Simulation of Urban MObility: RORDLoader_SUMOBase Class Reference
RORDLoader_SUMOBase Class Reference
The base class for SUMO-native route handlers.
#include <RORDLoader_SUMOBase.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endDocument ()
Called when the document has ended.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RORDLoader_SUMOBase (RONet &net, SUMOTime begin, SUMOTime end, const SUMOReal beta, const SUMOReal gawronA, const SUMOReal logitGamma, const int maxRouteNumber, const bool tryRepair, const bool withTaz, const bool keepRoutes, const bool skipRouteCalculation, const std::string &file="")
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
~RORDLoader_SUMOBase ()
Destructor.
inherited from ROAbstractRouteDefLoader
bool ended () const
Returns the information whether no routes are available from this loader anymore.
bool readRoutesAtLeastUntil (SUMOTime time, bool skipping)
Adds routes from the file until the given time is reached.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
inherited from ROAbstractRouteDefLoader
SUMOTime getLastReadTimeStep () const
Returns the time the current (last read) route starts at.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
bool closeVehicle ()
void startAlternative (const SUMOSAXAttributes &attrs)
Begins the parsing of the next route alternative in the file.
void startRoute (const SUMOSAXAttributes &attrs)
Begins the parsing of a route alternative of the opened route.
inherited from ROTypedXMLRoutesLoader
void beginNextRoute ()
Returns Initialises the reading of a further route.
bool nextRouteRead ()
inherited from GenericSAXHandler
void myCharacters (int element, const std::string &chars)
Called when characters occure.
virtual void myEndElement (int element)
Called when a closing tag occurs.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
bool myAltIsValid
Information whether the currently parsed alternatives set is valid.
SUMOTime myBegin
The time for which the first route shall be loaded.
const SUMOReal myBeta
gawron or logit beta - value
RGBColor * myColor
The color of the current route/vehicle.
SUMOReal myCost
The costs of the current alternative.
RORouteDef_Alternatives * myCurrentAlternatives
The currently parsed route alternatives.
SUMOTime myCurrentDepart
The currently read vehicle's depart.
bool myCurrentIsOk
Information whether the currently parsed item is valid.
RORouteDef_Complete * myCurrentRoute
The currently parsed route.
std::string myCurrentRouteName
The name of the currently parsed route.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
SUMOTime myEnd
The time for which the first route shall be loaded.
bool myEnded
Information whether the whole file has been parsed.
const SUMOReal myGawronA
gawron a - value
bool myHaveNextRoute
Information whether a further route has been read.
bool myHaveWarnedAboutDeprecatedRoute
bool myHaveWarnedAboutDeprecatedVType
const bool myKeepRoutes
Information whether all routes should be saved.
const SUMOReal myLogitGamma
logit gamma - value
int myMaxRouteNumber
The maximum route alternatives number.
RONet & myNet
The network to add routes to.
SAX2XMLReader * myParser
The parser used.
SUMOReal myProbability
The probability of the current alternative's usage.
const bool mySkipRouteCalculation
Information whether new routes should be calculated.
XMLPScanToken myToken
Information about the current position within the file.
bool myTryRepair
Information whether a read route shall be tried to be repaired.
SUMOVehicleParameter * myVehicleParameter
The parsed vehicle parameter.
const bool myWithTaz
Information whether zones (districts) are used as origins / destinations.
Private Member Functions
RORDLoader_SUMOBase & operator= (const RORDLoader_SUMOBase &src)
Invalidated assignment operator.
RORDLoader_SUMOBase (const RORDLoader_SUMOBase &src)
Invalidated copy constructor.
Detailed Description
The base class for SUMO-native route handlers.
As both the SUMO-routes and the SUMO-route alternatives handlers share a set of processing functions, we've joined these functions within a single class (this one).
Definition at line 64 of file RORDLoader_SUMOBase.h.
Constructor & Destructor Documentation
RORDLoader_SUMOBase::RORDLoader_SUMOBase (RONet & net, SUMOTime begin, SUMOTime end, const SUMOReal beta, const SUMOReal gawronA, const SUMOReal logitGamma, const int maxRouteNumber, const bool tryRepair, const bool withTaz, const bool keepRoutes, const bool skipRouteCalculation, const std::string & file = "")
Constructor.
Definition at line 55 of file RORDLoader_SUMOBase.cpp.
RORDLoader_SUMOBase::~RORDLoader_SUMOBase ()
Destructor.
Definition at line 70 of file RORDLoader_SUMOBase.cpp.
References myColor, myCurrentAlternatives, myCurrentRoute, and myVehicleParameter.
RORDLoader_SUMOBase::RORDLoader_SUMOBase (const RORDLoader_SUMOBase & src) [private]
Invalidated copy constructor.
Member Function Documentation
void RORDLoader_SUMOBase::beginNextRoute () [protected, virtual]
Returns Initialises the reading of a further route.
Todo:
recheck/refactor
See also:
ROTypedXMLRoutesLoader::beginNextRoute
Implements ROTypedXMLRoutesLoader.
Definition at line 351 of file RORDLoader_SUMOBase.cpp.
References myHaveNextRoute.
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
bool RORDLoader_SUMOBase::closeVehicle () [protected]
Definition at line 322 of file RORDLoader_SUMOBase.cpp.
References RONet::addVehicle(), SUMOVehicleParameter::depart, MsgHandler::getErrorInstance(), RONet::getRouteDef(), RONet::getVehicleTypeSecure(), SUMOVehicleParameter::id, ROAbstractRouteDefLoader::myBegin, myCurrentIsOk, ROAbstractRouteDefLoader::myEnd, ROAbstractRouteDefLoader::myNet, myVehicleParameter, SUMOVehicleParameter::routeid, SUMOVehicleParameter::vtypeid, and WRITE_ERROR.
Referenced by myEndElement().
void ROTypedXMLRoutesLoader::endDocument () [inherited]
Called when the document has ended.
Todo:
Recheck usage of route loaders; it is not very fine to have one that use a parser and other that do not
Definition at line 86 of file ROTypedXMLRoutesLoader.cpp.
References ROTypedXMLRoutesLoader::myEnded.
bool ROTypedXMLRoutesLoader::ended () const [inline, virtual, inherited]
Returns the information whether no routes are available from this loader anymore.
Returns:
Whether the whole input has been processed
Implements ROAbstractRouteDefLoader.
Definition at line 99 of file ROTypedXMLRoutesLoader.h.
References ROTypedXMLRoutesLoader::myEnded.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
SUMOTime RORDLoader_SUMOBase::getLastReadTimeStep () const [inline, virtual]
Returns the time the current (last read) route starts at.
Returns:
The least time step that was read by this reader
Implements ROAbstractRouteDefLoader.
Definition at line 86 of file RORDLoader_SUMOBase.h.
References myCurrentDepart.
void RORDLoader_SUMOBase::myCharacters (int element, const std::string & chars) [protected, virtual]
Called when characters occure.
Parameters:
[in] element ID of the last opened element
[in] chars The read characters (complete)
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myCharacters
Reimplemented from GenericSAXHandler.
Definition at line 207 of file RORDLoader_SUMOBase.cpp.
References RORouteDef_Alternatives::addLoadedAlternative(), SUMOVehicleParameter::fromTaz, RONet::getEdge(), Named::getID(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, myAltIsValid, myColor, myCost, myCurrentAlternatives, myCurrentIsOk, myCurrentRoute, myCurrentRouteName, ROAbstractRouteDefLoader::myNet, myProbability, myTryRepair, myVehicleParameter, myWithTaz, StringTokenizer::next(), SUMO_TAG_ROUTE, SUMOVehicleParameter::toTaz, VEHPARS_TAZ_SET, SUMOVehicleParameter::wasSet(), and WRITE_ERROR.
Referenced by startRoute().
void RORDLoader_SUMOBase::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 272 of file RORDLoader_SUMOBase.cpp.
References RONet::addRouteDef(), RONet::addVehicleType(), closeVehicle(), SUMOVehicleParserHelper::closeVTypeParsing(), myAltIsValid, myCurrentAlternatives, myCurrentIsOk, myCurrentRoute, myCurrentVType, myHaveNextRoute, ROAbstractRouteDefLoader::myNet, myVehicleParameter, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, and SUMO_TAG_VTYPE__DEPRECATED.
void RORDLoader_SUMOBase::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 80 of file RORDLoader_SUMOBase.cpp.
References SUMOVehicleParserHelper::beginVTypeParsing(), SUMOVehicleParameter::depart, myAltIsValid, myCurrentDepart, myCurrentIsOk, myCurrentVType, myHaveWarnedAboutDeprecatedVType, myVehicleParameter, SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVTypeEmbedded(), startAlternative(), startRoute(), SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE__DEPRECATED, toString(), and WRITE_WARNING.
bool RORDLoader_SUMOBase::nextRouteRead () [inline, protected, virtual]
Returns the information whether a route was read
Returns:
Whether a further route was read
See also:
ROTypedXMLRoutesLoader::nextRouteRead
Implements ROTypedXMLRoutesLoader.
Definition at line 145 of file RORDLoader_SUMOBase.h.
References myHaveNextRoute.
RORDLoader_SUMOBase& RORDLoader_SUMOBase::operator= (const RORDLoader_SUMOBase & src) [private]
Invalidated assignment operator.
bool ROTypedXMLRoutesLoader::readRoutesAtLeastUntil (SUMOTime time, bool skipping) [virtual, inherited]
Adds routes from the file until the given time is reached.
Parameters:
[in] time The time until which route definitions shall be loaded
[in] skipping Whether routes shall not be added
Returns:
Whether any errors occured
Exceptions:
ProcessError If a major error occured
See also:
ROAbstractRouteDefLoader::readRoutesAtLeastUntil
Implements ROAbstractRouteDefLoader.
Reimplemented in RORDGenerator_ODAmounts.
Definition at line 73 of file ROTypedXMLRoutesLoader.cpp.
References ROTypedXMLRoutesLoader::beginNextRoute(), ROTypedXMLRoutesLoader::ended(), ROAbstractRouteDefLoader::getLastReadTimeStep(), ROTypedXMLRoutesLoader::myParser, ROTypedXMLRoutesLoader::myToken, ROTypedXMLRoutesLoader::nextRouteRead(), and UNUSED_PARAMETER.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void RORDLoader_SUMOBase::startAlternative (const SUMOSAXAttributes & attrs) [protected]
Begins the parsing of the next route alternative in the file.
Definition at line 176 of file RORDLoader_SUMOBase.cpp.
References SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getStringReporting(), SUMOVehicleParameter::id, myBeta, myCurrentAlternatives, myCurrentIsOk, myGawronA, myKeepRoutes, myLogitGamma, myMaxRouteNumber, mySkipRouteCalculation, myVehicleParameter, SUMO_ATTR_ID, SUMO_ATTR_LAST, and WRITE_ERROR.
Referenced by myStartElement().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void RORDLoader_SUMOBase::startRoute (const SUMOSAXAttributes & attrs) [protected]
Begins the parsing of a route alternative of the opened route.
Definition at line 126 of file RORDLoader_SUMOBase.cpp.
References Named::getID(), SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myAltIsValid, myCharacters(), myColor, myCost, myCurrentAlternatives, myCurrentIsOk, myCurrentRouteName, myHaveWarnedAboutDeprecatedRoute, myProbability, myVehicleParameter, RGBColor::parseColorReporting(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_TAG_ROUTE, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
bool RORDLoader_SUMOBase::myAltIsValid [protected]
Information whether the currently parsed alternatives set is valid.
Definition at line 170 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), myEndElement(), myStartElement(), and startRoute().
SUMOTime ROAbstractRouteDefLoader::myBegin [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 109 of file ROAbstractRouteDefLoader.h.
Referenced by closeVehicle(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), RORDGenerator_ODAmounts::readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts::RORDGenerator_ODAmounts().
const SUMOReal RORDLoader_SUMOBase::myBeta [protected]
gawron or logit beta - value
Definition at line 185 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
RGBColor* RORDLoader_SUMOBase::myColor [protected]
The color of the current route/vehicle.
Definition at line 164 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), startRoute(), and ~RORDLoader_SUMOBase().
SUMOReal RORDLoader_SUMOBase::myCost [protected]
The costs of the current alternative.
Definition at line 179 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), and startRoute().
RORouteDef_Alternatives* RORDLoader_SUMOBase::myCurrentAlternatives [protected]
The currently parsed route alternatives.
Definition at line 176 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), myEndElement(), startAlternative(), startRoute(), and ~RORDLoader_SUMOBase().
SUMOTime RORDLoader_SUMOBase::myCurrentDepart [protected]
The currently read vehicle's depart.
Definition at line 215 of file RORDLoader_SUMOBase.h.
Referenced by getLastReadTimeStep(), and myStartElement().
bool RORDLoader_SUMOBase::myCurrentIsOk [protected]
Information whether the currently parsed item is valid.
Definition at line 167 of file RORDLoader_SUMOBase.h.
Referenced by closeVehicle(), myCharacters(), myEndElement(), myStartElement(), startAlternative(), and startRoute().
RORouteDef_Complete* RORDLoader_SUMOBase::myCurrentRoute [protected]
The currently parsed route.
Definition at line 209 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), myEndElement(), and ~RORDLoader_SUMOBase().
std::string RORDLoader_SUMOBase::myCurrentRouteName [protected]
The name of the currently parsed route.
Definition at line 212 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), and startRoute().
SUMOVTypeParameter* RORDLoader_SUMOBase::myCurrentVType [protected]
The currently parsed vehicle type.
Definition at line 218 of file RORDLoader_SUMOBase.h.
Referenced by myEndElement(), and myStartElement().
SUMOTime ROAbstractRouteDefLoader::myEnd [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 112 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), closeVehicle(), and RORDLoader_TripDefs::myEndElement().
bool ROTypedXMLRoutesLoader::myEnded [protected, inherited]
Information whether the whole file has been parsed.
Definition at line 141 of file ROTypedXMLRoutesLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), ROTypedXMLRoutesLoader::endDocument(), and ROTypedXMLRoutesLoader::ended().
const SUMOReal RORDLoader_SUMOBase::myGawronA [protected]
gawron a - value
Definition at line 188 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
bool RORDLoader_SUMOBase::myHaveNextRoute [protected]
Information whether a further route has been read.
Definition at line 173 of file RORDLoader_SUMOBase.h.
Referenced by beginNextRoute(), myEndElement(), and nextRouteRead().
bool RORDLoader_SUMOBase::myHaveWarnedAboutDeprecatedRoute [protected]
Definition at line 221 of file RORDLoader_SUMOBase.h.
Referenced by startRoute().
bool RORDLoader_SUMOBase::myHaveWarnedAboutDeprecatedVType [protected]
Definition at line 220 of file RORDLoader_SUMOBase.h.
Referenced by myStartElement().
const bool RORDLoader_SUMOBase::myKeepRoutes [protected]
Information whether all routes should be saved.
Definition at line 203 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
const SUMOReal RORDLoader_SUMOBase::myLogitGamma [protected]
logit gamma - value
Definition at line 191 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
int RORDLoader_SUMOBase::myMaxRouteNumber [protected]
The maximum route alternatives number.
Definition at line 194 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
RONet& ROAbstractRouteDefLoader::myNet [protected, inherited]
The network to add routes to.
Definition at line 106 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), closeVehicle(), RORDLoader_TripDefs::getEdge(), myCharacters(), RORDLoader_TripDefs::myEndElement(), myEndElement(), and RORDGenerator_ODAmounts::myEndFlowAmountDef().
SAX2XMLReader* ROTypedXMLRoutesLoader::myParser [protected, inherited]
The parser used.
Definition at line 135 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), and ROTypedXMLRoutesLoader::~ROTypedXMLRoutesLoader().
SUMOReal RORDLoader_SUMOBase::myProbability [protected]
The probability of the current alternative's usage.
Definition at line 182 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters(), and startRoute().
const bool RORDLoader_SUMOBase::mySkipRouteCalculation [protected]
Information whether new routes should be calculated.
Definition at line 206 of file RORDLoader_SUMOBase.h.
Referenced by startAlternative().
XMLPScanToken ROTypedXMLRoutesLoader::myToken [protected, inherited]
Information about the current position within the file.
Definition at line 138 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), and ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader().
bool RORDLoader_SUMOBase::myTryRepair [protected]
Information whether a read route shall be tried to be repaired.
Definition at line 197 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters().
SUMOVehicleParameter* RORDLoader_SUMOBase::myVehicleParameter [protected]
The parsed vehicle parameter.
Definition at line 161 of file RORDLoader_SUMOBase.h.
Referenced by closeVehicle(), myCharacters(), myEndElement(), myStartElement(), startAlternative(), startRoute(), and ~RORDLoader_SUMOBase().
const bool RORDLoader_SUMOBase::myWithTaz [protected]
Information whether zones (districts) are used as origins / destinations.
Definition at line 200 of file RORDLoader_SUMOBase.h.
Referenced by myCharacters().
The documentation for this class was generated from the following files:
RORDLoader_SUMOBase.h
RORDLoader_SUMOBase.cpp