SUMO - Simulation of Urban MObility: Point2D< coord_type > Class Template Reference
Point2D< coord_type > Class Template Reference
#include <points.h>
Public Member Functions
coord_type getX () const
coord_type getY () const
double magnitude () const
template<class point_type >
bool operator!= (const Point2D< point_type > &old) const
template<class point_type >
Point2D< coord_type > & operator+= (const Point2D< point_type > &old)
template<class point_type >
Point2D< coord_type > & operator-= (const Point2D< point_type > &old)
Point2D< coord_type > & operator= (const Point2D< coord_type > &old)
template<class point_type >
Point2D< coord_type > & operator= (const Point2D< point_type > &old)
template<class point_type >
bool operator== (const Point2D< point_type > &old) const
coord_type operator[] (int i) const
Point2D (const Point2D< coord_type > &old)
template<class point_type >
Point2D (const Point2D< point_type > &old)
Point2D (coord_type x0, coord_type y0)
Point2D ()
void rotate (double angle)
void set (coord_type nx, coord_type ny)
void setX (coord_type nx)
void setY (coord_type ny)
void swap ()
coord_type x () const
coord_type y () const
~Point2D ()
Protected Attributes
coord_type _x
coord_type _y
Detailed Description
template<class coord_type>
class Point2D< coord_type >
Definition at line 37 of file points.h.
Constructor & Destructor Documentation
template<class coord_type> Point2D< coord_type >::Point2D () [inline]
Definition at line 42 of file points.h.
template<class coord_type> Point2D< coord_type >::Point2D (coord_type x0, coord_type y0) [inline]
Definition at line 47 of file points.h.
template<class coord_type> template<class point_type > Point2D< coord_type >::Point2D (const Point2D< point_type > & old) [inline]
template<class coord_type> Point2D< coord_type >::Point2D (const Point2D< coord_type > & old) [inline]
template<class coord_type> Point2D< coord_type >::~Point2D () [inline]
Definition at line 90 of file points.h.
Member Function Documentation
template<class coord_type> coord_type Point2D< coord_type >::getX () const [inline]
Definition at line 94 of file points.h.
Referenced by EulerSpiral::compute_end_pt(), euc_distance(), operator*(), operator+(), operator-(), operator/(), and Point2D< double >::operator=().
template<class coord_type> coord_type Point2D< coord_type >::getY () const [inline]
Definition at line 95 of file points.h.
Referenced by EulerSpiral::compute_end_pt(), euc_distance(), operator*(), operator+(), operator-(), operator/(), and Point2D< double >::operator=().
template<class coord_type> double Point2D< coord_type >::magnitude () const [inline]
Definition at line 170 of file points.h.
template<class coord_type> template<class point_type > bool Point2D< coord_type >::operator!= (const Point2D< point_type > & old) const [inline]
Definition at line 123 of file points.h.
template<class coord_type> template<class point_type > Point2D<coord_type>& Point2D< coord_type >::operator+= (const Point2D< point_type > & old) [inline]
Definition at line 133 of file points.h.
template<class coord_type> template<class point_type > Point2D<coord_type>& Point2D< coord_type >::operator-= (const Point2D< point_type > & old) [inline]
Definition at line 142 of file points.h.
template<class coord_type> Point2D<coord_type>& Point2D< coord_type >::operator= (const Point2D< coord_type > & old) [inline]
Definition at line 83 of file points.h.
template<class coord_type> template<class point_type > Point2D<coord_type>& Point2D< coord_type >::operator= (const Point2D< point_type > & old) [inline]
Definition at line 61 of file points.h.
template<class coord_type> template<class point_type > bool Point2D< coord_type >::operator== (const Point2D< point_type > & old) const [inline]
Definition at line 114 of file points.h.
template<class coord_type> coord_type Point2D< coord_type >::operator[] (int i) const [inline]
Definition at line 103 of file points.h.
template<class coord_type> void Point2D< coord_type >::rotate (double angle) [inline]
NOTE: The angle is assumed to be in RADIANS.
Definition at line 153 of file points.h.
template<class coord_type> void Point2D< coord_type >::set (coord_type nx, coord_type ny) [inline]
Definition at line 101 of file points.h.
template<class coord_type> void Point2D< coord_type >::setX (coord_type nx) [inline]
Definition at line 99 of file points.h.
Referenced by EulerSpiral::compute_end_pt(), BiArc::compute_other_stuff(), EulerSpiral::get_fresnel_integral(), and Point2D< double >::set().
template<class coord_type> void Point2D< coord_type >::setY (coord_type ny) [inline]
Definition at line 100 of file points.h.
Referenced by EulerSpiral::compute_end_pt(), BiArc::compute_other_stuff(), EulerSpiral::get_fresnel_integral(), and Point2D< double >::set().
template<class coord_type> void Point2D< coord_type >::swap () [inline]
Definition at line 165 of file points.h.
Referenced by Point2D< double >::swap().
template<class coord_type> coord_type Point2D< coord_type >::x () const [inline]
Definition at line 96 of file points.h.
Referenced by BiArc::compute_biarc_params(), EulerSpiral::compute_es_params(), BiArc::compute_join_theta(), and BiArc::compute_other_stuff().
template<class coord_type> coord_type Point2D< coord_type >::y () const [inline]
Definition at line 97 of file points.h.
Referenced by BiArc::compute_biarc_params(), EulerSpiral::compute_es_params(), BiArc::compute_join_theta(), and BiArc::compute_other_stuff().
Field Documentation
template<class coord_type> coord_type Point2D< coord_type >::_x [protected]
Definition at line 40 of file points.h.
Referenced by Point2D< double >::getX(), Point2D< double >::magnitude(), Point2D< double >::operator!=(), Point2D< double >::operator+=(), Point2D< double >::operator-=(), Point2D< double >::operator=(), Point2D< double >::operator==(), Point2D< double >::operator[](), Point2D< double >::Point2D(), Point2D< double >::rotate(), Point2D< double >::setX(), Point2D< double >::swap(), and Point2D< double >::x().
template<class coord_type> coord_type Point2D< coord_type >::_y [protected]
Definition at line 40 of file points.h.
Referenced by Point2D< double >::getY(), Point2D< double >::magnitude(), Point2D< double >::operator!=(), Point2D< double >::operator+=(), Point2D< double >::operator-=(), Point2D< double >::operator=(), Point2D< double >::operator==(), Point2D< double >::operator[](), Point2D< double >::Point2D(), Point2D< double >::rotate(), Point2D< double >::setY(), Point2D< double >::swap(), and Point2D< double >::y().
The documentation for this class was generated from the following file:
points.h