SUMO - Simulation of Urban MObility: RODFRouteCont Class Reference
RODFRouteCont Class Reference
A container for DFROUTER-routes.
#include <RODFRouteCont.h>
Data Structures
class by_distance_sorter
A class for sorting route descriptions by their length.
class route_finder
A class for finding a same route (one that passes the same edges).
Public Member Functions
void addAllEndFollower ()
All routes are replaced by their versions extended by follower edges.
void addRouteDesc (RODFRouteDesc &desc)
Adds a route to the container.
std::vector< RODFRouteDesc > & get ()
Returns the container of stored routes.
void removeIllegal (const std::vector< std::vector< ROEdge * > > &illegals)
Removes "illegal" routes.
bool removeRouteDesc (RODFRouteDesc &desc)
Removes the given route description from the container.
RODFRouteCont ()
Constructor.
bool save (std::vector< std::string > &saved, const std::string &prependix, OutputDevice &out)
Saves routes.
void sortByDistance ()
Sorts routes by their distance (length).
~RODFRouteCont ()
Destructor.
Protected Member Functions
void setID (RODFRouteDesc &desc) const
Computes and sets the id of a route.
Protected Attributes
std::map< std::pair< ROEdge
*, ROEdge * >, int > myConnectionOccurences
Counts how many routes connecting the key-edges were already stored.
std::vector< RODFRouteDesc > myRoutes
Stored route descriptions.
Detailed Description
A container for DFROUTER-routes.
The route id is (re)set as soon as the route is added.
As sometimes several routes can be used between two edges and have to be identified, the number of routes connecting them is stored for each edge pair "myConnectionOccurences" and the route is named using this information,
See also:
addRouteDesc.
RODFRouteDesc
Definition at line 63 of file RODFRouteCont.h.
Constructor & Destructor Documentation
RODFRouteCont::RODFRouteCont ()
Constructor.
Definition at line 50 of file RODFRouteCont.cpp.
RODFRouteCont::~RODFRouteCont ()
Destructor.
Definition at line 53 of file RODFRouteCont.cpp.
Member Function Documentation
void RODFRouteCont::addAllEndFollower ()
All routes are replaced by their versions extended by follower edges.
Definition at line 138 of file RODFRouteCont.cpp.
References RODFRouteDesc::edges2Pass, ROEdge::getFollower(), ROEdge::getNoFollowing(), myRoutes, and setID().
Referenced by RODFNet::buildRoutes().
void RODFRouteCont::addRouteDesc (RODFRouteDesc & desc)
Adds a route to the container.
If the same route is already known, its "overallProb" is increased by the value stored in the given route.
An id for the route is generated if it is unset, yet. The id is computed and set via "setID".
Parameters:
[in] desc The route description to add
See also:
setID
Definition at line 58 of file RODFRouteCont.cpp.
References myRoutes, RODFRouteDesc::overallProb, and setID().
Referenced by RODFDetector::addRoute(), and RODFNet::computeRoutesFor().
std::vector<RODFRouteDesc>& RODFRouteCont::get () [inline]
Returns the container of stored routes.
Returns:
The stored routes
Definition at line 113 of file RODFRouteCont.h.
References myRoutes.
Referenced by RODFDetector::buildDestinationDistribution(), RODFNet::buildRoutes(), RODFDetector::computeSplitProbabilities(), RODFDetector::getRouteVector(), RODFDetector::hasRoutes(), and RODFDetector::writeEmitterDefinition().
void RODFRouteCont::removeIllegal (const std::vector< std::vector< ROEdge * > > & illegals)
Removes "illegal" routes.
"illegal" routes means edge combinations that shall not be passed.
Parameters:
[in] illegals List of edge combinations that shall not be passed
Todo:
Not used, yet
Definition at line 113 of file RODFRouteCont.cpp.
References RODFRouteDesc::edges2Pass, and myRoutes.
bool RODFRouteCont::removeRouteDesc (RODFRouteDesc & desc)
Removes the given route description from the container.
All routes are regarded as being same if they pass the same edges. This is done via the "route_finder".
Parameters:
[in] desc The route description to remove
Returns:
Whether the route was removed (a similar was found)
See also:
RODFRouteCont::route_finder
Definition at line 72 of file RODFRouteCont.cpp.
References myRoutes.
Referenced by RODFNet::computeRoutesFor().
bool RODFRouteCont::save (std::vector< std::string > & saved, const std::string & prependix, OutputDevice & out)
Saves routes.
Parameters:
[in,out] saved The list of ids of routes that shall not be saved (were saved before)
[in] prependix The prependix for route names
[out] out The device the routes shall written to
Returns:
Whether at least one route was saved
Exceptions:
IOError not yet implemented
Definition at line 82 of file RODFRouteCont.cpp.
References RODFRouteDesc::edges2Pass, myRoutes, and RODFRouteDesc::routename.
Referenced by RODFDetector::writeRoutes().
void RODFRouteCont::setID (RODFRouteDesc & desc) const [protected]
Computes and sets the id of a route.
The id is <FIRST_EDGE>_to_<LAST_EDGE>_<RUNNING> where <RUNNING> is the number of routes which connect <FIRST_EDGE> and <LAST_EDGE>.
Parameters:
[in] desc The route description to add
Definition at line 159 of file RODFRouteCont.cpp.
References RODFRouteDesc::edges2Pass, myConnectionOccurences, RODFRouteDesc::routename, and toString().
Referenced by addAllEndFollower(), and addRouteDesc().
void RODFRouteCont::sortByDistance ()
Sorts routes by their distance (length).
Done using by_distance_sorter.
See also:
RODFRouteCont::by_distance_sorter
Definition at line 107 of file RODFRouteCont.cpp.
References myRoutes.
Field Documentation
std::map<std::pair<ROEdge*, ROEdge*>, int> RODFRouteCont::myConnectionOccurences [mutable, protected]
Counts how many routes connecting the key-edges were already stored.
Definition at line 189 of file RODFRouteCont.h.
Referenced by setID().
std::vector<RODFRouteDesc> RODFRouteCont::myRoutes [protected]
Stored route descriptions.
Definition at line 186 of file RODFRouteCont.h.
Referenced by addAllEndFollower(), addRouteDesc(), get(), removeIllegal(), removeRouteDesc(), save(), and sortByDistance().
The documentation for this class was generated from the following files:
RODFRouteCont.h
RODFRouteCont.cpp