SUMO - Simulation of Urban MObility: SUMOVehicleParserHelper Class Reference
SUMOVehicleParserHelper Class Reference
Helper methods for parsing vehicle attributes.
#include <SUMOVehicleParserHelper.h>
Static Public Member Functions
static SUMOVTypeParameter * beginVTypeParsing (const SUMOSAXAttributes &attrs)
Starts to parse a vehicle type.
static void closeVTypeParsing (SUMOVTypeParameter &vtype)
Closes parsing of the vehicle type.
static SUMOEmissionClass parseEmissionClass (const SUMOSAXAttributes &attrs, const std::string &id)
Parses the vehicle emission class.
static SUMOVehicleParameter * parseFlowAttributes (const SUMOSAXAttributes &attrs)
Parses a flow's attributes.
static SUMOVehicleShape parseGuiShape (const SUMOSAXAttributes &attrs, const std::string &id)
Parses the vehicle class.
static SUMOVehicleParameter * parseVehicleAttributes (const SUMOSAXAttributes &attrs, bool skipID=false, bool skipDepart=false)
Parses a vehicle's attributes.
static SUMOVehicleClass parseVehicleClass (const SUMOSAXAttributes &attrs, const std::string &id)
Parses the vehicle class.
static void parseVTypeEmbedded (SUMOVTypeParameter &into, int element, const SUMOSAXAttributes &attrs, bool fromVType=false)
Parses an element embedded in vtype definition.
Private Types
typedef std::map< SumoXMLTag,
std::set< SumoXMLAttr > > CFAttrMap
Static Private Member Functions
static const CFAttrMap & getAllowedCFModelAttrs ()
static void parseCommonAttributes (const SUMOSAXAttributes &attrs, SUMOVehicleParameter *ret, std::string element)
Parses attributes common to vehicles and flows.
Static Private Attributes
static CFAttrMap allowedCFModelAttrs
static bool gHaveWarnedAboutDeprecatedArrivalLane = false
static bool gHaveWarnedAboutDeprecatedArrivalPos = false
static bool gHaveWarnedAboutDeprecatedArrivalSpeed = false
static bool gHaveWarnedAboutDeprecatedDepartLane = false
static bool gHaveWarnedAboutDeprecatedDepartPos = false
static bool gHaveWarnedAboutDeprecatedDepartSpeed = false
static bool gHaveWarnedAboutDeprecatedMaxSpeed = false
static bool gHaveWarnedAboutDeprecatedNumber = false
static bool gHaveWarnedAboutDeprecatedTazs = false
static bool gHaveWarnedAboutDeprecatedVClass = false
Detailed Description
Helper methods for parsing vehicle attributes.
This class supports helper methods for parsing a vehicle's attributes.
Definition at line 55 of file SUMOVehicleParserHelper.h.
Member Typedef Documentation
typedef std::map<SumoXMLTag, std::set<SumoXMLAttr> > SUMOVehicleParserHelper::CFAttrMap [private]
Definition at line 185 of file SUMOVehicleParserHelper.h.
Member Function Documentation
SUMOVTypeParameter * SUMOVehicleParserHelper::beginVTypeParsing (const SUMOSAXAttributes & attrs) [static]
Starts to parse a vehicle type.
Parameters:
[in] attr The SAX-attributes to get vehicle parameter from
Exceptions:
ProcessError If an attribute's value is invalid
See also:
SUMOVTypeParameter
Note:
: the caller is responsible for deleting the returned pointer
Definition at line 553 of file SUMOVehicleParserHelper.cpp.
References SUMOVTypeParameter::air_dens, SUMOVTypeParameter::aux_mask, SUMOVTypeParameter::capacity, SUMOVTypeParameter::celsius, SUMOVTypeParameter::cockpit_ligths_consumption, SUMOVTypeParameter::color, SUMOVTypeParameter::constant_losses, SUMOVTypeParameter::cooper_losses, SUMOVTypeParameter::defaultProbability, SUMOVTypeParameter::drag_coefficient, SUMOVTypeParameter::emissionClass, SUMOVTypeParameter::front_fog_ligths_consumption, SUMOVTypeParameter::frontal_area, SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), gHaveWarnedAboutDeprecatedMaxSpeed, gHaveWarnedAboutDeprecatedVClass, SUMOSAXAttributes::hasAttribute(), SUMOVTypeParameter::heatingAC_consumption, SUMOVTypeParameter::humidity, SUMOVTypeParameter::id, SUMOVTypeParameter::iron_losses, SUMOVTypeParameter::length, SUMOVTypeParameter::light_mask, SUMOVTypeParameter::mass, SUMOVTypeParameter::maxSpeed, SUMOVTypeParameter::minGap, SUMOVTypeParameter::motor_sys_effc, SUMOVTypeParameter::num_cells, RGBColor::parseColorReporting(), parseEmissionClass(), parseGuiShape(), parseVehicleClass(), parseVTypeEmbedded(), SUMOVTypeParameter::power_accs, SUMOVTypeParameter::radio_consumption, SUMOVTypeParameter::regen_ratio, SUMOVTypeParameter::rolling_res, SUMOVTypeParameter::setParameter, SUMOVTypeParameter::shape, SUMOVTypeParameter::speedDev, SUMOVTypeParameter::speedFactor, SUMO_ATTR_AIR_DENSITY, SUMO_ATTR_AUX_MASK, SUMO_ATTR_CAPACITY, SUMO_ATTR_COCKPIT_LIGHT, SUMO_ATTR_COLOR, SUMO_ATTR_CONSTANT_LOSSES, SUMO_ATTR_COOPER_LOSSES, SUMO_ATTR_DRAG_COEFFICIENT, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_ENV_HUM, SUMO_ATTR_ENV_TEMP, SUMO_ATTR_FOG_LIGHT, SUMO_ATTR_FRONTAL_AREA, SUMO_ATTR_GEAR_RATIO, SUMO_ATTR_GEAR_SYS_EFFC, SUMO_ATTR_GUIOFFSET, SUMO_ATTR_GUISHAPE, SUMO_ATTR_GUIWIDTH, SUMO_ATTR_HEAD_LIGHT, SUMO_ATTR_HEATING_AC, SUMO_ATTR_ID, SUMO_ATTR_IRON_LOSSES, SUMO_ATTR_LENGTH, SUMO_ATTR_LIGHT_MASK, SUMO_ATTR_MASS, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED__DEPRECATED, SUMO_ATTR_MINGAP, SUMO_ATTR_MOTOR_SYS_EFFC, SUMO_ATTR_NUM_CELLS, SUMO_ATTR_POWER_ACCS, SUMO_ATTR_PROB, SUMO_ATTR_RADIO, SUMO_ATTR_REGEN_RATIO, SUMO_ATTR_ROLLING_RES, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TIME_CHARGE, SUMO_ATTR_VCLASS, SUMO_ATTR_VCLASS__DEPRECATED, SUMO_ATTR_WINDAGE_LOSSES, SUMO_TAG_CF_KRAUSS, SUMOVTypeParameter::time_charge, toString(), SUMOVTypeParameter::vehicle_headligths_consumption, SUMOVTypeParameter::vehicleClass, VTYPEPARS_COLOR_SET, VTYPEPARS_EMISSIONCLASS_SET, VTYPEPARS_LENGTH_SET, VTYPEPARS_MAXSPEED_SET, VTYPEPARS_MINGAP_SET, VTYPEPARS_PROBABILITY_SET, VTYPEPARS_SHAPE_SET, VTYPEPARS_SPEEDDEVIATION_SET, VTYPEPARS_SPEEDFACTOR_SET, VTYPEPARS_VEHICLECLASS_SET, VTYPEPARS_WIDTH_SET, SUMOVTypeParameter::width, SUMOVTypeParameter::windage_losses, and WRITE_WARNING.
Referenced by RORDLoader_TripDefs::myStartElement(), RORDLoader_SUMOBase::myStartElement(), and MSRouteHandler::myStartElement().
static void SUMOVehicleParserHelper::closeVTypeParsing (SUMOVTypeParameter & vtype) [inline, static]
Closes parsing of the vehicle type.
Returns:
The resulting vehicle type parameter
See also:
SUMOVTypeParameter
Definition at line 114 of file SUMOVehicleParserHelper.h.
References UNUSED_PARAMETER.
Referenced by RORDLoader_TripDefs::myEndElement(), RORDLoader_SUMOBase::myEndElement(), and MSRouteHandler::myEndElement().
const SUMOVehicleParserHelper::CFAttrMap & SUMOVehicleParserHelper::getAllowedCFModelAttrs () [static, private]
Definition at line 797 of file SUMOVehicleParserHelper.cpp.
References allowedCFModelAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CF_IDM_DELTA, SUMO_ATTR_CF_IDM_STEPPING, SUMO_ATTR_CF_IDMM_ADAPT_FACTOR, SUMO_ATTR_CF_IDMM_ADAPT_TIME, SUMO_ATTR_CF_KERNER_PHI, SUMO_ATTR_CF_PWAGNER2009_APPROB, SUMO_ATTR_CF_PWAGNER2009_TAULAST, SUMO_ATTR_CF_WIEDEMANN_ESTIMATION, SUMO_ATTR_CF_WIEDEMANN_SECURITY, SUMO_ATTR_DECEL, SUMO_ATTR_K, SUMO_ATTR_SIGMA, SUMO_ATTR_TAU, SUMO_TAG_CF_BKERNER, SUMO_TAG_CF_IDM, SUMO_TAG_CF_IDMM, SUMO_TAG_CF_KRAUSS, SUMO_TAG_CF_KRAUSS_ORIG1, SUMO_TAG_CF_PWAGNER2009, and SUMO_TAG_CF_WIEDEMANN.
Referenced by parseVTypeEmbedded().
void SUMOVehicleParserHelper::parseCommonAttributes (const SUMOSAXAttributes & attrs, SUMOVehicleParameter * ret, std::string element) [static, private]
Parses attributes common to vehicles and flows.
Parses all attributes stored in "SUMOVehicleParameter".
See also:
SUMOVehicleParameter
Parameters:
[in] attr The SAX-attributes to get vehicle parameter from
[out] ret The parameter to parse into
[in] element The name of the element (vehicle or flow)
Exceptions:
ProcessError If an attribute's value is invalid
Definition at line 260 of file SUMOVehicleParserHelper.cpp.
References ARRIVAL_LANE_CURRENT, ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_CURRENT, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, DEPART_POS_BASE, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_MAX_SPEED_GAP, DEPART_POS_PWAG_GENERIC, DEPART_POS_PWAG_SIMPLE, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, SUMOVehicleParameter::fromTaz, SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), gHaveWarnedAboutDeprecatedArrivalLane, gHaveWarnedAboutDeprecatedArrivalPos, gHaveWarnedAboutDeprecatedArrivalSpeed, gHaveWarnedAboutDeprecatedDepartLane, gHaveWarnedAboutDeprecatedDepartPos, gHaveWarnedAboutDeprecatedDepartSpeed, gHaveWarnedAboutDeprecatedTazs, SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, RGBColor::parseColor(), SUMOVehicleParameter::routeid, SUMOVehicleParameter::setParameter, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALLANE__DEPRECATED, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS__DEPRECATED, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_ARRIVALSPEED__DEPRECATED, SUMO_ATTR_COLOR, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTLANE__DEPRECATED, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS__DEPRECATED, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DEPARTSPEED__DEPRECATED, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_FROM_TAZ__DEPRECATED, SUMO_ATTR_LINE, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TO_TAZ, SUMO_ATTR_TO_TAZ__DEPRECATED, SUMO_ATTR_TYPE, toString(), SUMOVehicleParameter::toTaz, VEHPARS_ARRIVALLANE_SET, VEHPARS_ARRIVALPOS_SET, VEHPARS_ARRIVALSPEED_SET, VEHPARS_COLOR_SET, VEHPARS_DEPARTLANE_SET, VEHPARS_DEPARTPOS_SET, VEHPARS_DEPARTSPEED_SET, VEHPARS_FORCE_REROUTE, VEHPARS_LINE_SET, VEHPARS_ROUTE_SET, VEHPARS_TAZ_SET, VEHPARS_VTYPE_SET, SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by parseFlowAttributes(), and parseVehicleAttributes().
SUMOEmissionClass SUMOVehicleParserHelper::parseEmissionClass (const SUMOSAXAttributes & attrs, const std::string & id) [static]
Parses the vehicle emission class.
When given, the vehicle emission class is parsed using getVehicleEmissionTypeID. Exceptions occuring within this process are catched and reported.
If no vehicle class is available in the attributes, the default class (SVE_UNKNOWN) is returned.
Parameters:
[in] attrs The attributes to read the class from
[in] id The id of the parsed element, for error message generation
Returns:
The parsed vehicle emission class
See also:
SUMOEmissionClass
Todo:
Recheck how errors are handled and what happens if they occure
Definition at line 875 of file SUMOVehicleParserHelper.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), getVehicleEmissionTypeID(), SUMO_ATTR_EMISSIONCLASS, SVE_UNKNOWN, and WRITE_ERROR.
Referenced by beginVTypeParsing().
SUMOVehicleParameter * SUMOVehicleParserHelper::parseFlowAttributes (const SUMOSAXAttributes & attrs) [static]
Parses a flow's attributes.
Parses all attributes stored in "SUMOVehicleParameter".
See also:
SUMOVehicleParameter
Parameters:
[in] attr The SAX-attributes to get vehicle parameter from
Returns:
The parsed attribute structure if no error occured, 0 otherwise
Exceptions:
ProcessError If an attribute's value is invalid
Note:
: the caller is responsible for deleting the returned pointer
Definition at line 66 of file SUMOVehicleParserHelper.cpp.
References SUMOVehicleParameter::depart, SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getName(), OptionsCont::getOptions(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), gHaveWarnedAboutDeprecatedNumber, SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, parseCommonAttributes(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::setParameter, string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NO__DEPRECATED, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_VEHSPERHOUR, SUMOReal, SUMOTime_MAX, TIME2STEPS, toString(), VEHPARS_PERIODFREQ_SET, and WRITE_WARNING.
Referenced by MSRouteHandler::myStartElement().
SUMOVehicleShape SUMOVehicleParserHelper::parseGuiShape (const SUMOSAXAttributes & attrs, const std::string & id) [static]
Parses the vehicle class.
When given, the vehicle class is parsed using getVehicleShapeID. Exceptions occuring within this process are catched and reported.
If no vehicle class is available in the attributes, the default class (SVS_UNKNOWN) is returned.
Parameters:
[in] attrs The attributes to read the class from
[in] id The id of the parsed element, for error message generation
Returns:
The parsed vehicle shape
See also:
SUMOVehicleShape
Todo:
Recheck how errors are handled and what happens if they occure
Definition at line 893 of file SUMOVehicleParserHelper.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), SUMO_ATTR_GUISHAPE, SumoVehicleShapeStrings, SVS_UNKNOWN, and WRITE_ERROR.
Referenced by beginVTypeParsing().
SUMOVehicleParameter * SUMOVehicleParserHelper::parseVehicleAttributes (const SUMOSAXAttributes & attrs, bool skipID = false, bool skipDepart = false) [static]
Parses a vehicle's attributes.
Parses all attributes stored in "SUMOVehicleParameter".
See also:
SUMOVehicleParameter
Parameters:
[in] attr The SAX-attributes to get vehicle parameter from
[in] skipID Whether parsing the id shall be skipped
[in] skipDepart Whether parsing the departure time shall be skipped
Returns:
The parsed attribute structure if no error occured, 0 otherwise
Exceptions:
ProcessError If an attribute's value is invalid
Note:
: the caller is responsible for deleting the returned pointer
Definition at line 196 of file SUMOVehicleParserHelper.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departProcedure, SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, parseCommonAttributes(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::setParameter, SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_ATTR_PERIOD, SUMO_ATTR_REPNUMBER, VEHPARS_PERIODFREQ_SET, VEHPARS_PERIODNUM_SET, and WRITE_WARNING.
Referenced by RORDLoader_TripDefs::myStartElement(), RORDLoader_SUMOBase::myStartElement(), MSRouteHandler::myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
SUMOVehicleClass SUMOVehicleParserHelper::parseVehicleClass (const SUMOSAXAttributes & attrs, const std::string & id) [static]
Parses the vehicle class.
When given, the vehicle class is parsed using getVehicleClassID. Exceptions occuring within this process are catched and reported.
If no vehicle class is available in the attributes, the default class (SVC_UNKNOWN) is returned.
Parameters:
[in] attrs The attributes to read the class from
[in] id The id of the parsed element, for error message generation
Returns:
The parsed vehicle class
See also:
SUMOVehicleClass
Todo:
Recheck how errors are handled and what happens if they occure
Definition at line 852 of file SUMOVehicleParserHelper.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), getVehicleClassID(), SUMOSAXAttributes::hasAttribute(), SUMO_ATTR_VCLASS, SUMO_ATTR_VCLASS__DEPRECATED, SVC_UNKNOWN, and WRITE_ERROR.
Referenced by beginVTypeParsing().
void SUMOVehicleParserHelper::parseVTypeEmbedded (SUMOVTypeParameter & into, int element, const SUMOSAXAttributes & attrs, bool fromVType = false) [static]
Parses an element embedded in vtype definition.
Parameters:
in,filled] into The structure to fill with parsed values
[in] element The id of the currently parsed XML-element
[in] attr The SAX-attributes to get vehicle parameter from
[in] fromVType Whether the attributes are a part of the vtype-definition
Exceptions:
ProcessError If an attribute's value is invalid
See also:
SUMOVTypeParameter
Definition at line 762 of file SUMOVehicleParserHelper.cpp.
References SUMOVTypeParameter::cfModel, SUMOVTypeParameter::cfParameter, getAllowedCFModelAttrs(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVTypeParameter::id, SUMOXMLDefinitions::Tags, toString(), and WRITE_WARNING.
Referenced by beginVTypeParsing(), RORDLoader_TripDefs::myStartElement(), RORDLoader_SUMOBase::myStartElement(), and MSRouteHandler::myStartElement().
Field Documentation
SUMOVehicleParserHelper::CFAttrMap SUMOVehicleParserHelper::allowedCFModelAttrs [static, private]
Definition at line 191 of file SUMOVehicleParserHelper.h.
Referenced by getAllowedCFModelAttrs().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedArrivalLane = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedArrivalPos = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedArrivalSpeed = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedDepartLane = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedDepartPos = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedDepartSpeed = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedMaxSpeed = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by beginVTypeParsing().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedNumber = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseFlowAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedTazs = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by parseCommonAttributes().
bool SUMOVehicleParserHelper::gHaveWarnedAboutDeprecatedVClass = false [static, private]
Definition at line 194 of file SUMOVehicleParserHelper.h.
Referenced by beginVTypeParsing().
The documentation for this class was generated from the following files:
SUMOVehicleParserHelper.h
SUMOVehicleParserHelper.cpp