SUMO - Simulation of Urban MObility: ToString.h File Reference
ToString.h File Reference
#include <config.h>
#include <sstream>
#include <string>
#include <iomanip>
#include <utils/xml/SUMOXMLDefinitions.h>
#include <utils/common/SUMOVehicleClass.h>
#include "StdDefs.h"
Functions
template<class T >
std::string toString (const T &t, std::streamsize accuracy=OUTPUT_ACCURACY)
template<>
std::string toString< LaneSpreadFunction > (const LaneSpreadFunction &lsf, std::streamsize accuracy)
template<>
std::string toString< LinkDirection > (const LinkDirection &linkDir, std::streamsize accuracy)
template<>
std::string toString< LinkState > (const LinkState &linkState, std::streamsize accuracy)
template<>
std::string toString< SUMOVehicleClass > (const SUMOVehicleClass &vClass, std::streamsize accuracy)
template<>
std::string toString< SumoXMLAttr > (const SumoXMLAttr &attr, std::streamsize accuracy)
template<>
std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc &edgeFunc, std::streamsize accuracy)
template<>
std::string toString< SumoXMLNodeType > (const SumoXMLNodeType &nodeType, std::streamsize accuracy)
template<>
std::string toString< SumoXMLTag > (const SumoXMLTag &tag, std::streamsize accuracy)
template<>
std::string toString< TrafficLightType > (const TrafficLightType &type, std::streamsize accuracy)
Detailed Description
Author:
Christian Roessel
Daniel Krajzewicz
Jakob Erdmann
Date:
Wed, 23 Sep 2002
Version:
Id
ToString.h 11671 2012-01-07 20:14:30Z behrisch
Definition in file ToString.h.
Function Documentation
template<class T > std::string toString (const T & t, std::streamsize accuracy = OUTPUT_ACCURACY) [inline]
Template for conversions from origin format to string representation (when supplied by c++/the stl)
Definition at line 50 of file ToString.h.
Referenced by NIImporter_SUMO::_loadNetwork(), ODMatrix::add(), MSDetectorControl::add(), NLHandler::addConnection(), NIImporter_SUMO::addConnection(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIXMLEdgesHandler::addEdge(), NIImporter_SUMO::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NIXMLEdgesHandler::addLane(), NIImporter_SUMO::addLane(), GUIEdgeControlBuilder::addLane(), NLJunctionControlBuilder::addLogicItem(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimTL::NIVissimTLSignal::addTo(), NBEdge::allowVehicleClass(), NLHandler::beginE3Detector(), NLHandler::beginEdgeParsing(), SUMOVehicleParserHelper::beginVTypeParsing(), NLBuilder::build(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), MSInsertionControl::checkFlows(), NGFrame::checkOptions(), NLDetectorBuilder::checkSampleInterval(), MSNet::closeSimulation(), NBOwnTLDef::collectLinks(), NBNetBuilder::compute(), ODMatrix::computeDeparts(), NBNode::computeInternalLaneShape(), RODFNet::computeTypes(), NIXMLEdgesHandler::deleteEdge(), NIXMLNodesHandler::deleteNode(), NBTrafficLightLogic::deletePhase(), GUISelectedStorage::deselect(), NBEdge::disallowVehicleClass(), GUITriggeredRerouter::drawGL(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), MSE3Collector::enter(), OptionsLoader::error(), OptionsLoader::fatalError(), NLDetectorBuilder::getEdgeChecking(), NLDetectorBuilder::getLaneChecking(), NBEdge::getLaneID(), NIVissimDistrictConnection::getMeanSpeed(), GeomHelper::getNormal90D_CW(), GUISUMOAbstractView::getObjectsInBoundary(), GUILaneWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), Line::getPositionAtDistance(), ROEdge::getStoredEffort(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), ROEdge::getTravelTime(), TraCIServerAPI_VehicleType::getVariable(), getVehicleClassNames(), getVehicleEmissionTypeName(), NBNodeCont::guessTLs(), GUICompleteSchemeStorage::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NIImporter_OpenStreetMap::insertEdge(), NIXMLEdgesHandler::insertNodeChecking(), NIImporter_OpenStreetMap::insertNodeChecking(), NIVissimConnectionCluster::joinBySameEdges(), NBNodeCont::joinTLS(), MSE3Collector::leave(), PCLoaderVisum::load(), PCLoaderArcView::load(), NLBuilder::load(), NILoader::load(), NIImporter_ArcView::load(), NIImporter_RobocupRescue::loadEdges(), GUISelectedStorage::loadIDs(), PCLoaderOSM::loadIfSet(), NIImporter_RobocupRescue::loadNodes(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), main(), MSCFModel_KraussOrig1::moveHelper(), MSRouteProbe::MSRouteProbe(), NIXMLEdgesHandler::myEndElement(), RORDLoader_TripDefs::myStartElement(), RORDLoader_SUMOBase::myStartElement(), RONetHandler::myStartElement(), ROJTRTurnDefLoader::myStartElement(), RODFDetectorHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), ODDistrictHandler::myStartElement(), NLHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::myStartElement(), GUISettingsHandler::myStartElement(), NIVissimAbstractEdge::NIVissimAbstractEdge(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIApplicationWindow::openNewView(), MSRouteHandler::openRoute(), OutputDevice::openTag(), MSRouteHandler::openVehicleTypeDistribution(), OutputDevice_Network::OutputDevice_Network(), NIImporter_VISUM::parse_AreaSubPartElement(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_Point(), NLTriggerBuilder::parseAndBuildBusStop(), SUMOVehicleParserHelper::parseCommonAttributes(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), RORDGenerator_ODAmounts::parseFlowAmountDef(), SUMOVehicleParserHelper::parseFlowAttributes(), GUISettingsHandler::parseTextSettings(), parseTimeLine(), SUMOVehicleParserHelper::parseVTypeEmbedded(), GUIVisualizationTextSettings::print(), NBNodeCont::printBuiltNodesStatistics(), TraCIServerAPI_Lane::processGet(), readO(), NBNodeCont::removeSelfLoops(), MSBaseVehicle::replaceRouteEdges(), PCPolyContainer::report(), NBRequest::reportWarnings(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), GUILaneWrapper::ROWdrawAction_drawLinkNo(), GUILaneWrapper::ROWdrawAction_drawTLSLinkNo(), RODFDetectorCon::save(), RONet::saveAndRemoveRoutesUntil(), GUISelectedStorage::select(), RODFRouteCont::setID(), MFXAddEditTypedTable::setItemFromControl(), MFXAddEditTypedTable::setItemFromControl_NoRelease(), GeoConvHelper::setLoaded(), NIXMLEdgesHandler::setNodes(), PositionVector::splitAt(), NBEdge::splitGeometry(), NBNode::stateCode(), GUISelectedStorage::toggleSelection(), NIXMLEdgesHandler::tryGetLaneSpread(), SAXWeightsHandler::tryParse(), GUISUMOAbstractView::updatePositionInformation(), NIXMLConnectionsHandler::validateLaneInfo(), OptionsLoader::warning(), SUMOVTypeParameter::write(), ODMatrix::write(), MSInstantInductLoop::write(), SUMOVehicleParameter::writeAs(), OutputDevice::writeAttr(), NWWriter_SUMO::writeConnection(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalEdge(), NWWriter_SUMO::writeInternalNodes(), NWWriter_SUMO::writeLane(), NBRequest::writeLaneResponse(), NWWriter_XML::writeNodes(), GUICompleteSchemeStorage::writeSettings(), ROLoader::writeStats(), NWWriter_SUMO::writeSUMOTime(), NWWriter_SUMO::writeTrafficLights(), MSRouteProbe::writeXMLOutput(), and GeoConvHelper::x2cartesian().
template<> std::string toString< LaneSpreadFunction > (const LaneSpreadFunction & lsf, std::streamsize accuracy) [inline]
template<> std::string toString< LinkDirection > (const LinkDirection & linkDir, std::streamsize accuracy) [inline]
template<> std::string toString< LinkState > (const LinkState & linkState, std::streamsize accuracy) [inline]
template<> std::string toString< SUMOVehicleClass > (const SUMOVehicleClass & vClass, std::streamsize accuracy) [inline]
template<> std::string toString< SumoXMLAttr > (const SumoXMLAttr & attr, std::streamsize accuracy) [inline]
template<> std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc & edgeFunc, std::streamsize accuracy) [inline]
template<> std::string toString< SumoXMLNodeType > (const SumoXMLNodeType & nodeType, std::streamsize accuracy) [inline]
template<> std::string toString< SumoXMLTag > (const SumoXMLTag & tag, std::streamsize accuracy) [inline]
template<> std::string toString< TrafficLightType > (const TrafficLightType & type, std::streamsize accuracy) [inline]