SUMO - Simulation of Urban MObility: NIVissimNodeDef_Poly Class Reference
NIVissimNodeDef_Poly Class Reference
#include <NIVissimNodeDef_Poly.h>
Public Member Functions
int buildNodeCluster ()
virtual SUMOReal getEdgePosition (int edgeid) const
NIVissimNodeDef_Poly (int id, const std::string &name, const PositionVector &poly)
virtual void searchAndSetConnections ()
void searchAndSetConnections (SUMOReal offset)
virtual ~NIVissimNodeDef_Poly ()
Static Public Member Functions
static void clearDict ()
static void dict_assignConnectionsToNodes ()
static NIVissimNodeDef * dictionary (int id)
static bool dictionary (int id, NIVissimNodeDef *o)
static bool dictionary (int id, const std::string &name, const NIVissimNodeParticipatingEdgeVector &edges)
static bool dictionary (int id, const std::string &name, const PositionVector &poly)
static size_t dictSize ()
static int getMaxID ()
Protected Attributes
NIVissimNodeParticipatingEdgeVector myEdges
int myID
std::string myName
Private Attributes
PositionVector myPoly
Detailed Description
Definition at line 40 of file NIVissimNodeDef_Poly.h.
Constructor & Destructor Documentation
NIVissimNodeDef_Poly::NIVissimNodeDef_Poly (int id, const std::string & name, const PositionVector & poly)
Definition at line 54 of file NIVissimNodeDef_Poly.cpp.
Referenced by dictionary().
NIVissimNodeDef_Poly::~NIVissimNodeDef_Poly () [virtual]
Definition at line 60 of file NIVissimNodeDef_Poly.cpp.
Member Function Documentation
int NIVissimNodeDef::buildNodeCluster () [inherited]
void NIVissimNodeDef::clearDict () [static, inherited]
Definition at line 132 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
void NIVissimNodeDef::dict_assignConnectionsToNodes () [static, inherited]
Definition at line 117 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
NIVissimNodeDef * NIVissimNodeDef::dictionary (int id) [static, inherited]
Definition at line 74 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
bool NIVissimNodeDef::dictionary (int id, NIVissimNodeDef * o) [static, inherited]
Definition at line 59 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict, and NIVissimNodeDef::myMaxID.
Referenced by dictionary(), NIVissimNodeDef_Edges::dictionary(), and NIVissimConnectionCluster::getPositionForEdge().
bool NIVissimNodeDef_Edges::dictionary (int id, const std::string & name, const NIVissimNodeParticipatingEdgeVector & edges) [static, inherited]
Definition at line 68 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeDef::dictionary(), and NIVissimNodeDef_Edges::NIVissimNodeDef_Edges().
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse(), and NIVissimNodeDef_Edges::searchAndSetConnections().
bool NIVissimNodeDef_Poly::dictionary (int id, const std::string & name, const PositionVector & poly) [static]
Definition at line 64 of file NIVissimNodeDef_Poly.cpp.
References NIVissimNodeDef::dictionary(), and NIVissimNodeDef_Poly().
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse(), and searchAndSetConnections().
size_t NIVissimNodeDef::dictSize () [static, inherited]
Definition at line 125 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
SUMOReal NIVissimNodeDef_Edges::getEdgePosition (int edgeid) const [virtual, inherited]
Implements NIVissimNodeDef.
Definition at line 113 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeParticipatingEdge::getFromPos(), NIVissimNodeParticipatingEdge::getID(), NIVissimNodeParticipatingEdge::getToPos(), NIVissimNodeDef_Edges::myEdges, and SUMOReal.
int NIVissimNodeDef::getMaxID () [static, inherited]
Definition at line 141 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myMaxID.
Referenced by NIImporter_Vissim::postLoadBuild().
void NIVissimNodeDef_Edges::searchAndSetConnections () [virtual, inherited]
Implements NIVissimNodeDef.
Definition at line 80 of file NIVissimNodeDef_Edges.cpp.
References Boundary::add(), NIVissimNodeDef_Edges::dictionary(), NIVissimConnection::getFromGeomPosition(), NIVissimNodeParticipatingEdge::getFromPos(), NIVissimNodeParticipatingEdge::getID(), NIVissimConnection::getToGeomPosition(), NIVissimNodeParticipatingEdge::getToPos(), NIVissimEdge::myConnectionClusters, NIVissimNodeDef_Edges::myEdges, NIVissimNodeDef::myID, and NIVissimConnection::setNodeCluster().
void NIVissimNodeDef_Poly::searchAndSetConnections (SUMOReal offset)
Definition at line 98 of file NIVissimNodeDef_Poly.cpp.
References dictionary(), PositionVector::getBoxBoundary(), NIVissimAbstractEdge::getWithin(), NIVissimEdge::myConnectionClusters, NIVissimNodeDef::myID, myPoly, and NIVissimConnection::setNodeCluster().
Field Documentation
NIVissimNodeParticipatingEdgeVector NIVissimNodeDef_Edges::myEdges [protected, inherited]
Definition at line 77 of file NIVissimNodeDef_Edges.h.
Referenced by NIVissimNodeDef_Edges::getEdgePosition(), NIVissimNodeDef_Edges::searchAndSetConnections(), and NIVissimNodeDef_Edges::~NIVissimNodeDef_Edges().
int NIVissimNodeDef::myID [protected, inherited]
Definition at line 58 of file NIVissimNodeDef.h.
Referenced by searchAndSetConnections(), and NIVissimNodeDef_Edges::searchAndSetConnections().
std::string NIVissimNodeDef::myName [protected, inherited]
Definition at line 59 of file NIVissimNodeDef.h.
PositionVector NIVissimNodeDef_Poly::myPoly [private]
Definition at line 52 of file NIVissimNodeDef_Poly.h.
Referenced by searchAndSetConnections().
The documentation for this class was generated from the following files:
NIVissimNodeDef_Poly.h
NIVissimNodeDef_Poly.cpp