SUMO - Simulation of Urban MObility: NIVissimSource Class Reference
NIVissimSource Class Reference
#include <NIVissimSource.h>
Public Member Functions
NIVissimSource (const std::string &id, const std::string &name, const std::string &edgeid, SUMOReal q, bool exact, int vehicle_combination, SUMOReal beg, SUMOReal end)
~NIVissimSource ()
Static Public Member Functions
static void clearDict ()
static NIVissimSource * dictionary (const std::string &id)
static bool dictionary (const std::string &id, NIVissimSource *o)
static bool dictionary (const std::string &id, const std::string &name, const std::string &edgeid, SUMOReal q, bool exact, int vehicle_combination, SUMOReal beg, SUMOReal end)
Private Types
typedef std::map< std::string,
NIVissimSource * > DictType
Private Attributes
std::string myEdgeID
bool myExact
std::string myID
std::string myName
SUMOReal myQ
SUMOReal myTimeBeg
SUMOReal myTimeEnd
int myVehicleCombination
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 43 of file NIVissimSource.h.
Member Typedef Documentation
typedef std::map<std::string, NIVissimSource*> NIVissimSource::DictType [private]
Definition at line 66 of file NIVissimSource.h.
Constructor & Destructor Documentation
NIVissimSource::NIVissimSource (const std::string & id, const std::string & name, const std::string & edgeid, SUMOReal q, bool exact, int vehicle_combination, SUMOReal beg, SUMOReal end)
Definition at line 42 of file NIVissimSource.cpp.
Referenced by dictionary().
NIVissimSource::~NIVissimSource ()
Definition at line 51 of file NIVissimSource.cpp.
Member Function Documentation
void NIVissimSource::clearDict () [static]
Definition at line 90 of file NIVissimSource.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
NIVissimSource * NIVissimSource::dictionary (const std::string & id) [static]
Definition at line 80 of file NIVissimSource.cpp.
References myDict.
bool NIVissimSource::dictionary (const std::string & id, NIVissimSource * o) [static]
Definition at line 69 of file NIVissimSource.cpp.
References myDict.
bool NIVissimSource::dictionary (const std::string & id, const std::string & name, const std::string & edgeid, SUMOReal q, bool exact, int vehicle_combination, SUMOReal beg, SUMOReal end) [static]
Definition at line 55 of file NIVissimSource.cpp.
References NIVissimSource().
Referenced by NIVissimSingleTypeParser_Zuflussdefinition::parse().
Field Documentation
NIVissimSource::DictType NIVissimSource::myDict [static, private]
Definition at line 67 of file NIVissimSource.h.
Referenced by clearDict(), and dictionary().
std::string NIVissimSource::myEdgeID [private]
Definition at line 58 of file NIVissimSource.h.
bool NIVissimSource::myExact [private]
Definition at line 60 of file NIVissimSource.h.
std::string NIVissimSource::myID [private]
Definition at line 56 of file NIVissimSource.h.
std::string NIVissimSource::myName [private]
Definition at line 57 of file NIVissimSource.h.
SUMOReal NIVissimSource::myQ [private]
Definition at line 59 of file NIVissimSource.h.
SUMOReal NIVissimSource::myTimeBeg [private]
Definition at line 62 of file NIVissimSource.h.
SUMOReal NIVissimSource::myTimeEnd [private]
Definition at line 63 of file NIVissimSource.h.
int NIVissimSource::myVehicleCombination [private]
Definition at line 61 of file NIVissimSource.h.
The documentation for this class was generated from the following files:
NIVissimSource.h
NIVissimSource.cpp