SUMO - Simulation of Urban MObility: GUIBusStop Class Reference
GUIBusStop Class Reference
A lane area vehicles can halt at (gui-version).
#include <GUIBusStop.h>
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
void enter (void *what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
SUMOReal getBeginLanePosition () const
Returns the begin position of this bus stop.
SUMOReal getEndLanePosition () const
Returns the end position of this bus stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this bus stop is located at.
SUMOReal getLastFreePos () const
Returns the last free position on this stop.
GUIBusStop (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, SUMOReal frompos, SUMOReal topos)
Constructor.
void leaveFrom (void *what)
Called if a vehicle leaves this stop.
void setID (const std::string &newID)
resets the id
~GUIBusStop ()
Destructor.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
inherited from GUIGlObject
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT).
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted).
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector
< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
Protected Attributes
SUMOReal myBegPos
The begin position this bus stop is located at.
SUMOReal myEndPos
The end position this bus stop is located at.
std::map< void *, std::pair
< SUMOReal, SUMOReal > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
MSLane & myLane
The lane this bus stop is located at.
SUMOReal myLastFreePos
The last free position at this stop (variable).
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
Static Protected Attributes
static std::vector
< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string,
GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Attributes
PositionVector myFGShape
The shape.
DoubleVector myFGShapeLengths
The lengths of the shape parts.
DoubleVector myFGShapeRotations
The rotations of the shape parts.
Position myFGSignPos
The position of the sign.
SUMOReal myFGSignRot
The rotation of the sign.
Detailed Description
A lane area vehicles can halt at (gui-version).
This gui-version of a bus-stop extends MSBusStop by methods for displaying and interaction.
See also:
MSBusStop
GUIGlObject_AbstractAdd
GUIGlObject
Definition at line 71 of file GUIBusStop.h.
Constructor & Destructor Documentation
GUIBusStop::GUIBusStop (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, SUMOReal frompos, SUMOReal topos)
Constructor.
Parameters:
[in] idStorage The gl-id storage for giving this object an gl-id
[in] id The id of the bus stop
[in] lines Names of the bus lines that halt on this bus stop
[in] lane The lane the bus stop is placed on
[in] begPos Begin position of the bus stop on the lane
[in] endPos End position of the bus stop on the lane
Definition at line 73 of file GUIBusStop.cpp.
References Position::distanceTo(), PositionVector::getLineCenter(), MSLane::getShape(), PositionVector::getSubpart(), PositionVector::length(), PositionVector::move2side(), myFGShape, myFGShapeLengths, myFGShapeRotations, myFGSignPos, myFGSignRot, PI, PositionVector::rotationDegreeAtLengthPosition(), PositionVector::size(), SUMOReal, Position::x(), and Position::y().
GUIBusStop::~GUIBusStop ()
Destructor.
Definition at line 100 of file GUIBusStop.cpp.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) [inherited]
Lets this object know a parameter window showing the object's values was opened.
Parameters:
[in] w The opened parameter window
Definition at line 191 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to center to the object.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 129 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 138 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) [protected, inherited]
Builds the header.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 119 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 170 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to (de)select the object.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to open the manipulator window.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 182 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUITriggeredRerouter::getPopUpMenu(), and GUILaneSpeedTrigger::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to open the parameter window.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 161 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIVehicle::getPopUpMenu(), GUINet::getPopUpMenu(), GUILaneWrapper::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUIDetectorWrapper::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () [static, inherited]
Clears the dictionary (the objects will not be deleted).
!! delete (*i).second;
Definition at line 65 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void MSBusStop::computeLastFreePos () [protected, inherited]
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 96 of file MSBusStop.cpp.
References MSBusStop::myEndPos, MSBusStop::myEndPositions, and MSBusStop::myLastFreePos.
Referenced by MSBusStop::enter(), MSBusStop::leaveFrom(), and MSBusStop::MSBusStop().
void GUIBusStop::drawGL (const GUIVisualizationSettings & s) const [virtual]
Draws the object.
Parameters:
[in] s The settings for the current view (may influence drawing)
See also:
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 124 of file GUIBusStop.cpp.
References GUIVisualizationSettings::addExaggeration, GUIVisualizationSettings::addName, GLHelper::drawBoxLines(), GLHelper::drawFilledCircle(), GUIGlObject::drawName(), GLHelper::drawText(), getCenteringBoundary(), GUIGlObject::getGlID(), GUIGlObject::getType(), MIN2(), myFGShape, myFGShapeLengths, myFGShapeRotations, myFGSignPos, myFGSignRot, MSBusStop::myLines, pfDrawString(), pfSetPosition(), pfSetScale(), GUIVisualizationSettings::scale, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const [inline, virtual, inherited]
Draws additional, user-triggered visualisations.
Parameters:
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle.
Definition at line 177 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const [inherited]
Definition at line 218 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIVehicle::drawGL(), GUIPointOfInterest::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), drawGL(), and GUI_E2_ZS_Collector::MyWrapper::drawGL().
void MSBusStop::enter (void * what, SUMOReal beg, SUMOReal end) [inherited]
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters:
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See also:
computeLastFreePos
Definition at line 75 of file MSBusStop.cpp.
References MSBusStop::computeLastFreePos(), and MSBusStop::myEndPositions.
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) [static, inherited]
Returns a named object.
Definition at line 76 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
SUMOReal MSBusStop::getBeginLanePosition () const [inherited]
Returns the begin position of this bus stop.
Returns:
The position the bus stop begins at
Definition at line 63 of file MSBusStop.cpp.
References MSBusStop::myBegPos.
Referenced by MSRouteHandler::addStop().
Boundary GUIBusStop::getCenteringBoundary () const [virtual]
Returns the boundary to which the view shall be centered in order to show the object.
Returns:
The boundary the object is within
See also:
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 172 of file GUIBusStop.cpp.
References PositionVector::getBoxBoundary(), Boundary::grow(), and myFGShape.
Referenced by drawGL().
SUMOReal MSBusStop::getEndLanePosition () const [inherited]
Returns the end position of this bus stop.
Returns:
The position the bus stop ends at
Definition at line 69 of file MSBusStop.cpp.
References MSBusStop::myEndPos.
Referenced by MSRouteHandler::addStop(), and MSNet::getBusStopID().
const std::string& GUIGlObject::getFullName () const [inline, inherited]
Returns the full name appearing in the tool tip.
Returns:
This object's typed id
Definition at line 102 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUITriggeredRerouter::openManipulator(), GUILaneSpeedTrigger::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const [inline, inherited]
Returns the numerical id of the object.
Returns:
This object's gl-id
Definition at line 110 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GUILaneWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIE3Collector::MyWrapper::drawGL(), drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GUIVehicle::drawGLAdditional(), GUILaneWrapper::getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUIVehicle::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUISUMOViewParent::isSelected(), GUIGlChildWindow::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUILaneWrapper::ROWdrawAction_drawLinkRules(), and GUIGlObject::~GUIGlObject().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () [static, inherited]
Returns the list of gl-ids of all additional objects.
Definition at line 92 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
const MSLane & MSBusStop::getLane () const [inherited]
Returns the lane this bus stop is located at.
Returns:
Reference to the lane the bus stop is located at
Definition at line 57 of file MSBusStop.cpp.
References MSBusStop::myLane.
Referenced by MSRouteHandler::addStop(), and MSNet::getBusStopID().
SUMOReal MSBusStop::getLastFreePos () const [inherited]
Returns the last free position on this stop.
Returns:
The last free position of this bus stop
Definition at line 82 of file MSBusStop.cpp.
References MSBusStop::myLastFreePos.
const std::string& GUIGlObject::getMicrosimID () const [inline, inherited]
Returns the id of the object as known to microsim.
Returns:
The id of the object
Definition at line 141 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () [static, inherited]
Returns the list of all additional objects.
Definition at line 86 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
GUIParameterTableWindow * GUIBusStop::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) [virtual]
Returns an own parameter window.
Bus stops have no parameter windows (yet).
Parameters:
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns:
The built parameter window (always 0 in this case)
See also:
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 117 of file GUIBusStop.cpp.
GUIGLObjectPopupMenu * GUIBusStop::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) [virtual]
Returns an own popup-menu.
Parameters:
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns:
The built popup-menu
See also:
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 104 of file GUIBusStop.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), and GUIGlObject::buildSelectionPopupEntry().
GUIGlObjectType GUIGlObject::getType () const [inline, inherited]
Returns the type of the object as coded in GUIGlObjectType.
Returns:
The type of the object
See also:
GUIGlObjectType
Definition at line 154 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), GUILaneWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIE3Collector::MyWrapper::drawGL(), drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GUIVehicle::drawGLAdditional(), GUILaneWrapper::getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOViewParent::isSelected(), GUIGlChildWindow::isSelected(), GUISelectedStorage::loadIDs(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideAllRoutes(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideBestLanes(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideCurrentRoute(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowAllRoutes(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowBestLanes(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowCurrentRoute(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUIVehicle::GUIVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), and GUISelectedStorage::toggleSelection().
void MSBusStop::leaveFrom (void * what) [inherited]
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters:
[in] what The vehicle that leaves the bus stop
See also:
computeLastFreePos
Definition at line 88 of file MSBusStop.cpp.
References MSBusStop::computeLastFreePos(), and MSBusStop::myEndPositions.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) [inherited]
Lets this object know a parameter window showing the object's values was closed.
Parameters:
[in] w The closed parameter window
Definition at line 197 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void GUIGlObject::setMicrosimID (const std::string & newID) [inherited]
Changes the microsimID of the object (happens in NETEDIT).
Definition at line 112 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) [protected, inherited]
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
SUMOReal MSBusStop::myBegPos [protected, inherited]
The begin position this bus stop is located at.
Definition at line 155 of file MSBusStop.h.
Referenced by MSBusStop::getBeginLanePosition().
SUMOReal MSBusStop::myEndPos [protected, inherited]
The end position this bus stop is located at.
Definition at line 158 of file MSBusStop.h.
Referenced by MSBusStop::computeLastFreePos(), and MSBusStop::getEndLanePosition().
std::map<void*, std::pair<SUMOReal, SUMOReal> > MSBusStop::myEndPositions [protected, inherited]
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 149 of file MSBusStop.h.
Referenced by MSBusStop::computeLastFreePos(), MSBusStop::enter(), and MSBusStop::leaveFrom().
PositionVector GUIBusStop::myFGShape [private]
The shape.
Definition at line 142 of file GUIBusStop.h.
Referenced by drawGL(), getCenteringBoundary(), and GUIBusStop().
DoubleVector GUIBusStop::myFGShapeLengths [private]
The lengths of the shape parts.
Definition at line 139 of file GUIBusStop.h.
Referenced by drawGL(), and GUIBusStop().
DoubleVector GUIBusStop::myFGShapeRotations [private]
The rotations of the shape parts.
Definition at line 136 of file GUIBusStop.h.
Referenced by drawGL(), and GUIBusStop().
Position GUIBusStop::myFGSignPos [private]
The position of the sign.
Definition at line 145 of file GUIBusStop.h.
Referenced by drawGL(), and GUIBusStop().
SUMOReal GUIBusStop::myFGSignRot [private]
The rotation of the sign.
Definition at line 148 of file GUIBusStop.h.
Referenced by drawGL(), and GUIBusStop().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane& MSBusStop::myLane [protected, inherited]
The lane this bus stop is located at.
Definition at line 152 of file MSBusStop.h.
Referenced by MSBusStop::getLane().
SUMOReal MSBusStop::myLastFreePos [protected, inherited]
The last free position at this stop (variable).
Definition at line 161 of file MSBusStop.h.
Referenced by MSBusStop::computeLastFreePos(), and MSBusStop::getLastFreePos().
std::vector<std::string> MSBusStop::myLines [protected, inherited]
The list of lines that are assigned to this stop.
Definition at line 146 of file MSBusStop.h.
Referenced by drawGL().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList [static, protected, inherited]
The list of all addtional objects currently loaded.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), and GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects [static, protected, inherited]
Map from names of loaded additional objects to the objects themselves.
Definition at line 72 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), and GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames [static, inherited]
associates object types with strings
Definition at line 94 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIBusStop.h
GUIBusStop.cpp