SUMO - Simulation of Urban MObility: NIVissimNodeParticipatingEdge Class Reference
NIVissimNodeParticipatingEdge Class Reference
#include <NIVissimNodeParticipatingEdge.h>
Public Member Functions
SUMOReal getFromPos () const
int getID () const
SUMOReal getToPos () const
NIVissimNodeParticipatingEdge (int edgeid, SUMOReal frompos, SUMOReal topos)
bool positionLiesWithin (SUMOReal pos) const
~NIVissimNodeParticipatingEdge ()
Private Attributes
int myEdgeID
SUMOReal myFromPos
SUMOReal myToPos
Detailed Description
Definition at line 44 of file NIVissimNodeParticipatingEdge.h.
Constructor & Destructor Documentation
NIVissimNodeParticipatingEdge::NIVissimNodeParticipatingEdge (int edgeid, SUMOReal frompos, SUMOReal topos)
Definition at line 42 of file NIVissimNodeParticipatingEdge.cpp.
NIVissimNodeParticipatingEdge::~NIVissimNodeParticipatingEdge ()
Definition at line 46 of file NIVissimNodeParticipatingEdge.cpp.
Member Function Documentation
SUMOReal NIVissimNodeParticipatingEdge::getFromPos () const
Definition at line 64 of file NIVissimNodeParticipatingEdge.cpp.
References myFromPos.
Referenced by NIVissimNodeDef_Edges::getEdgePosition(), and NIVissimNodeDef_Edges::searchAndSetConnections().
int NIVissimNodeParticipatingEdge::getID () const
Definition at line 50 of file NIVissimNodeParticipatingEdge.cpp.
References myEdgeID.
Referenced by NIVissimNodeDef_Edges::getEdgePosition(), NIVissimNodeDef_Edges::lying_within_match::operator()(), NIVissimNodeDef_Edges::id_matches::operator()(), and NIVissimNodeDef_Edges::searchAndSetConnections().
SUMOReal NIVissimNodeParticipatingEdge::getToPos () const
Definition at line 70 of file NIVissimNodeParticipatingEdge.cpp.
References myToPos.
Referenced by NIVissimNodeDef_Edges::getEdgePosition(), and NIVissimNodeDef_Edges::searchAndSetConnections().
bool NIVissimNodeParticipatingEdge::positionLiesWithin (SUMOReal pos) const
Definition at line 56 of file NIVissimNodeParticipatingEdge.cpp.
References myFromPos, and myToPos.
Referenced by NIVissimNodeDef_Edges::lying_within_match::operator()().
Field Documentation
int NIVissimNodeParticipatingEdge::myEdgeID [private]
Definition at line 54 of file NIVissimNodeParticipatingEdge.h.
Referenced by getID().
SUMOReal NIVissimNodeParticipatingEdge::myFromPos [private]
Definition at line 55 of file NIVissimNodeParticipatingEdge.h.
Referenced by getFromPos(), and positionLiesWithin().
SUMOReal NIVissimNodeParticipatingEdge::myToPos [private]
Definition at line 55 of file NIVissimNodeParticipatingEdge.h.
Referenced by getToPos(), and positionLiesWithin().
The documentation for this class was generated from the following files:
NIVissimNodeParticipatingEdge.h
NIVissimNodeParticipatingEdge.cpp