SUMO - Simulation of Urban MObility: TraCIServerAPI_TLS Class Reference
TraCIServerAPI_TLS Class Reference
APIs for getting/setting traffic light values via TraCI.
#include <TraCIServerAPI_TLS.h>
Static Public Member Functions
static bool processGet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa2: Get Traffic Lights Variable).
static bool processSet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc2: Change Traffic Lights State).
Private Member Functions
TraCIServerAPI_TLS & operator= (const TraCIServerAPI_TLS &s)
invalidated assignment operator
TraCIServerAPI_TLS (const TraCIServerAPI_TLS &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting traffic light values via TraCI.
Definition at line 46 of file TraCIServerAPI_TLS.h.
Constructor & Destructor Documentation
TraCIServerAPI_TLS::TraCIServerAPI_TLS (const TraCIServerAPI_TLS & s) [private]
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_TLS& TraCIServerAPI_TLS::operator= (const TraCIServerAPI_TLS & s) [private]
invalidated assignment operator
bool TraCIServerAPI_TLS::processGet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) [static]
Processes a get value command (Command 0xa2: Get Traffic Lights Variable).
Parameters:
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 53 of file TraCIServerAPI_TLS.cpp.
References CMD_GET_TL_VARIABLE, MSPhaseDefinition::duration, MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTLLogicControl::TLSLogicVariants::getAllLogics(), MSTLLogicControl::getAllTLIds(), MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), Named::getID(), MSNet::getInstance(), MSLink::getLane(), MSTrafficLightLogic::getLanes(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSTrafficLightLogic::getProgramID(), MSPhaseDefinition::getState(), MSNet::getTLSControl(), MSLink::getViaLane(), ID_COUNT, ID_LIST, MSTLLogicControl::knows(), MSPhaseDefinition::maxDuration, MSPhaseDefinition::minDuration, RESPONSE_GET_TL_VARIABLE, RTYPE_ERR, RTYPE_OK, TL_COMPLETE_DEFINITION_RYG, TL_CONTROLLED_JUNCTIONS, TL_CONTROLLED_LANES, TL_CONTROLLED_LINKS, TL_CURRENT_PHASE, TL_CURRENT_PROGRAM, TL_NEXT_SWITCH, TL_PHASE_DURATION, TL_RED_YELLOW_GREEN_STATE, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, traci::TraCIServer::writeResponseWithLength(), and traci::TraCIServer::writeStatusCmd().
bool TraCIServerAPI_TLS::processSet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) [static]
Processes a set value command (Command 0xc2: Change Traffic Lights State).
Parameters:
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 231 of file TraCIServerAPI_TLS.cpp.
References MSTLLogicControl::TLSLogicVariants::addLogic(), MSTrafficLightLogic::changeStepAndDuration(), CMD_SET_TL_VARIABLE, DELTA_T, MSPhaseDefinition::duration, MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions(), MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTLLogicControl::TLSLogicVariants::getLogic(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSNet::getTLSControl(), RTYPE_ERR, RTYPE_OK, MSTrafficLightLogic::setTrafficLightSignals(), MSTLLogicControl::TLSLogicVariants::switchTo(), TL_COMPLETE_PROGRAM_RYG, TL_PHASE_DURATION, TL_PHASE_INDEX, TL_PROGRAM, TL_RED_YELLOW_GREEN_STATE, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, and traci::TraCIServer::writeStatusCmd().
The documentation for this class was generated from the following files:
TraCIServerAPI_TLS.h
TraCIServerAPI_TLS.cpp