SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::NodesHandler Class Reference
NIImporter_DlrNavteq::NodesHandler Class Reference
Importer of nodes stored in unsplit elmar format.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
NodesHandler (NBNodeCont &nc, const std::string &file, std::map< std::string, PositionVector > &geoms)
Constructor.
bool report (const std::string &result)
Parsing method.
~NodesHandler ()
Destructor.
Protected Attributes
std::map< std::string,
PositionVector > & myGeoms
A container for parsed geometries.
NBNodeCont & myNodeCont
Private Member Functions
NodesHandler (const NodesHandler &)
Invalidated copy constructor.
NodesHandler & operator= (const NodesHandler &)
Invalidated assignment operator.
Detailed Description
Importer of nodes stored in unsplit elmar format.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain node definitions in DLRNavteq's unsplit format.
Definition at line 85 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
NIImporter_DlrNavteq::NodesHandler::NodesHandler (NBNodeCont & nc, const std::string & file, std::map< std::string, PositionVector > & geoms)
Constructor.
Parameters:
in,filled] nc The node control to insert loaded nodes into
[in] file The name of the parsed file
in,geoms] geoms Storage for read edge geometries
Definition at line 111 of file NIImporter_DlrNavteq.cpp.
References UNUSED_PARAMETER.
NIImporter_DlrNavteq::NodesHandler::~NodesHandler ()
Destructor.
Definition at line 119 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::NodesHandler::NodesHandler (const NodesHandler &) [private]
Invalidated copy constructor.
Member Function Documentation
NodesHandler& NIImporter_DlrNavteq::NodesHandler::operator= (const NodesHandler &) [private]
Invalidated assignment operator.
bool NIImporter_DlrNavteq::NodesHandler::report (const std::string & result) [virtual]
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores it into "myNodeCont". Additionally, edge geometries are parsed and stored into "myGeoms".
Parameters:
[in] result The read line
Returns:
Whether the parsing shall continue
Exceptions:
ProcessError if something fails
See also:
LineHandler::report
Implements LineHandler.
Definition at line 123 of file NIImporter_DlrNavteq.cpp.
References NBNodeCont::insert(), myGeoms, myNodeCont, PositionVector::push_back(), NBNodeCont::size(), and NILoader::transformCoordinates().
Field Documentation
std::map<std::string, PositionVector>& NIImporter_DlrNavteq::NodesHandler::myGeoms [protected]
A container for parsed geometries.
Definition at line 119 of file NIImporter_DlrNavteq.h.
Referenced by report().
NBNodeCont& NIImporter_DlrNavteq::NodesHandler::myNodeCont [protected]
Definition at line 116 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp