SUMO - Simulation of Urban MObility: ROJTREdgeBuilder Class Reference
ROJTREdgeBuilder Class Reference
Interface for building instances of jtrrouter-edges.
#include <ROJTREdgeBuilder.h>
Public Member Functions
ROJTREdgeBuilder ()
Constructor.
~ROJTREdgeBuilder ()
Destructor.
Methods inherited from ROAbstractEdgeBuilder
ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to)
Builds an edge with the given name.
Protected Member Functions
unsigned int getNextIndex ()
Returns the index of the edge to built.
Detailed Description
Interface for building instances of jtrrouter-edges.
This ROAbstractEdgeBuilder implementation builds edges for the jtrrouter (instances of ROJTREdge).
See also:
ROJTREdge
Definition at line 55 of file ROJTREdgeBuilder.h.
Constructor & Destructor Documentation
ROJTREdgeBuilder::ROJTREdgeBuilder ()
Constructor.
Definition at line 43 of file ROJTREdgeBuilder.cpp.
ROJTREdgeBuilder::~ROJTREdgeBuilder ()
Destructor.
Definition at line 46 of file ROJTREdgeBuilder.cpp.
Member Function Documentation
ROEdge * ROJTREdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to) [virtual]
Builds an edge with the given name.
This implementation builds a ROJTREdge.
Parameters:
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
Returns:
A proper instance of the named edge
See also:
ROJTREdge
Implements ROAbstractEdgeBuilder.
Definition at line 50 of file ROJTREdgeBuilder.cpp.
References ROAbstractEdgeBuilder::getNextIndex().
unsigned int ROAbstractEdgeBuilder::getNextIndex () [inline, protected, inherited]
Returns the index of the edge to built.
Returns:
Next valid edge index
Definition at line 88 of file ROAbstractEdgeBuilder.h.
References ROAbstractEdgeBuilder::myCurrentIndex.
Referenced by buildEdge(), RODUAEdgeBuilder::buildEdge(), and RODFEdgeBuilder::buildEdge().
The documentation for this class was generated from the following files:
ROJTREdgeBuilder.h
ROJTREdgeBuilder.cpp