SUMO - Simulation of Urban MObility: MSBusStop Class Reference
MSBusStop Class Reference
A lane area vehicles can halt at.
#include <MSBusStop.h>
Public Member Functions
void enter (void *what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
SUMOReal getBeginLanePosition () const
Returns the begin position of this bus stop.
SUMOReal getEndLanePosition () const
Returns the end position of this bus stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this bus stop is located at.
SUMOReal getLastFreePos () const
Returns the last free position on this stop.
void leaveFrom (void *what)
Called if a vehicle leaves this stop.
MSBusStop (const std::string &id, const std::vector< std::string > &lines, MSLane &lane, SUMOReal begPos, SUMOReal endPos)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MSBusStop ()
Destructor.
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
Protected Attributes
SUMOReal myBegPos
The begin position this bus stop is located at.
SUMOReal myEndPos
The end position this bus stop is located at.
std::map< void *, std::pair
< SUMOReal, SUMOReal > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
MSLane & myLane
The lane this bus stop is located at.
SUMOReal myLastFreePos
The last free position at this stop (variable).
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
Private Member Functions
MSBusStop (const MSBusStop &)
Invalidated copy constructor.
MSBusStop & operator= (const MSBusStop &)
Invalidated assignment operator.
Detailed Description
A lane area vehicles can halt at.
The bus stops tracks the last free space a vehicle may halt at by being informed about a vehicle's entering and depart. It keeps the information about entered vehicles' begin and end position within an internal container ("myEndPositions") and is so able to compute the last free space.
Please note that using the last free space disallows vehicles to enter a free space in between other vehicles.
Definition at line 60 of file MSBusStop.h.
Constructor & Destructor Documentation
MSBusStop::MSBusStop (const std::string & id, const std::vector< std::string > & lines, MSLane & lane, SUMOReal begPos, SUMOReal endPos)
Constructor.
Parameters:
[in] id The id of the bus stop
[in] net The net the bus stop belongs to
[in] lines Names of the bus lines that halt on this bus stop
[in] lane The lane the bus stop is placed on
[in] begPos Begin position of the bus stop on the lane
[in] endPos End position of the bus stop on the lane
Definition at line 43 of file MSBusStop.cpp.
References computeLastFreePos().
MSBusStop::~MSBusStop () [virtual]
Destructor.
Definition at line 53 of file MSBusStop.cpp.
MSBusStop::MSBusStop (const MSBusStop &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSBusStop::computeLastFreePos () [protected]
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 96 of file MSBusStop.cpp.
References myEndPos, myEndPositions, and myLastFreePos.
Referenced by enter(), leaveFrom(), and MSBusStop().
void MSBusStop::enter (void * what, SUMOReal beg, SUMOReal end)
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters:
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See also:
computeLastFreePos
Definition at line 75 of file MSBusStop.cpp.
References computeLastFreePos(), and myEndPositions.
SUMOReal MSBusStop::getBeginLanePosition () const
Returns the begin position of this bus stop.
Returns:
The position the bus stop begins at
Definition at line 63 of file MSBusStop.cpp.
References myBegPos.
Referenced by MSRouteHandler::addStop().
SUMOReal MSBusStop::getEndLanePosition () const
Returns the end position of this bus stop.
Returns:
The position the bus stop ends at
Definition at line 69 of file MSBusStop.cpp.
References myEndPos.
Referenced by MSRouteHandler::addStop(), and MSNet::getBusStopID().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane & MSBusStop::getLane () const
Returns the lane this bus stop is located at.
Returns:
Reference to the lane the bus stop is located at
Definition at line 57 of file MSBusStop.cpp.
References myLane.
Referenced by MSRouteHandler::addStop(), and MSNet::getBusStopID().
SUMOReal MSBusStop::getLastFreePos () const
Returns the last free position on this stop.
Returns:
The last free position of this bus stop
Definition at line 82 of file MSBusStop.cpp.
References myLastFreePos.
void MSBusStop::leaveFrom (void * what)
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters:
[in] what The vehicle that leaves the bus stop
See also:
computeLastFreePos
Definition at line 88 of file MSBusStop.cpp.
References computeLastFreePos(), and myEndPositions.
MSBusStop& MSBusStop::operator= (const MSBusStop &) [private]
Invalidated assignment operator.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
Field Documentation
SUMOReal MSBusStop::myBegPos [protected]
The begin position this bus stop is located at.
Definition at line 155 of file MSBusStop.h.
Referenced by getBeginLanePosition().
SUMOReal MSBusStop::myEndPos [protected]
The end position this bus stop is located at.
Definition at line 158 of file MSBusStop.h.
Referenced by computeLastFreePos(), and getEndLanePosition().
std::map<void*, std::pair<SUMOReal, SUMOReal> > MSBusStop::myEndPositions [protected]
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 149 of file MSBusStop.h.
Referenced by computeLastFreePos(), enter(), and leaveFrom().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane& MSBusStop::myLane [protected]
The lane this bus stop is located at.
Definition at line 152 of file MSBusStop.h.
Referenced by getLane().
SUMOReal MSBusStop::myLastFreePos [protected]
The last free position at this stop (variable).
Definition at line 161 of file MSBusStop.h.
Referenced by computeLastFreePos(), and getLastFreePos().
std::vector<std::string> MSBusStop::myLines [protected]
The list of lines that are assigned to this stop.
Definition at line 146 of file MSBusStop.h.
Referenced by GUIBusStop::drawGL().
The documentation for this class was generated from the following files:
MSBusStop.h
MSBusStop.cpp