SUMO - Simulation of Urban MObility: MSTLLogicControl::WAUTSwitchProcedure Class Reference
MSTLLogicControl::WAUTSwitchProcedure Class Reference
This is the abstract base class for switching from one tls program to another.
#include <MSTLLogicControl.h>
Public Member Functions
virtual bool trySwitch (SUMOTime step)=0
Determines whether a switch is possible.
WAUTSwitchProcedure (MSTLLogicControl &control, WAUT &waut, MSTrafficLightLogic *from, MSTrafficLightLogic *to, bool synchron)
Constructor.
virtual ~WAUTSwitchProcedure ()
Destructor.
Protected Member Functions
SUMOTime getDiffToStartOfPhase (MSTrafficLightLogic &logic, SUMOTime toTime)
Returns the difference between a given time and the start of the phase.
unsigned int getGSPValue (const MSTrafficLightLogic &logic) const
Returns the GSP-value.
bool isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic &logic)
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt").
void switchToPos (SUMOTime simStep, MSTrafficLightLogic &logic, SUMOTime toTime)
switches the given logic directly to the given position
Protected Attributes
MSTLLogicControl & myControl
The control the logic belongs to.
MSTrafficLightLogic * myFrom
The current program of the tls to switch.
bool mySwitchSynchron
Information whether to switch synchron (?).
MSTrafficLightLogic * myTo
The program to switch the tls to.
WAUT & myWAUT
The WAUT responsible for switching.
Private Member Functions
WAUTSwitchProcedure & operator= (const WAUTSwitchProcedure &)
Invalidated assignment operator.
WAUTSwitchProcedure (const WAUTSwitchProcedure &)
Invalidated copy constructor.
Detailed Description
This is the abstract base class for switching from one tls program to another.
Definition at line 504 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
MSTLLogicControl::WAUTSwitchProcedure::WAUTSwitchProcedure (MSTLLogicControl & control, WAUT & waut, MSTrafficLightLogic * from, MSTrafficLightLogic * to, bool synchron) [inline]
Constructor.
Parameters:
[in] control The responsible tls control
[in] waut The WAUT to switch
[in] from The original tls program
[in] to The destination tls program
[in] synchron Whether the switch shall be done in synchronuous mode
Definition at line 513 of file MSTLLogicControl.h.
virtual MSTLLogicControl::WAUTSwitchProcedure::~WAUTSwitchProcedure () [inline, virtual]
Destructor.
Definition at line 520 of file MSTLLogicControl.h.
MSTLLogicControl::WAUTSwitchProcedure::WAUTSwitchProcedure (const WAUTSwitchProcedure &) [private]
Invalidated copy constructor.
Member Function Documentation
SUMOTime MSTLLogicControl::WAUTSwitchProcedure::getDiffToStartOfPhase (MSTrafficLightLogic & logic, SUMOTime toTime) [protected]
Returns the difference between a given time and the start of the phase.
Parameters:
[in] logic The logic to consider
[in] toTime The time to ask for
Returns:
How much time elapsed between the last pahse start and the given time
Definition at line 241 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::getIndexFromOffset(), and MSTrafficLightLogic::getOffsetFromIndex().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and switchToPos().
unsigned int MSTLLogicControl::WAUTSwitchProcedure::getGSPValue (const MSTrafficLightLogic & logic) const [protected]
Returns the GSP-value.
The GSP must be given as a logic's parameter ("GSP").
Parameters:
[in] logic The logic to retrieve the GSP from
Returns:
The GSP value; 0 if not given.
See also:
MSTrafficLightLogic::getParameterValue
Definition at line 222 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::getParameterValue().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), isPosAtGSP(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
bool MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic & logic) [protected]
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt").
The GSP must be given as a logic's parameter ("GSP"). Not the simulation second, but the phase the GSP lies within is used. If the phase the GSP lies within is the same as the logic's current phase, the result is true.
Parameters:
[in] currentTime The current time step
[in] logic The logic for which this should be examined
Returns:
Whether the current step is the GSP
See also:
getGSPValue
Definition at line 232 of file MSTLLogicControl.cpp.
References MSPhaseDefinition::duration, MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getDefaultCycleTime(), getGSPValue(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), and TIME2STEPS.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
WAUTSwitchProcedure& MSTLLogicControl::WAUTSwitchProcedure::operator= (const WAUTSwitchProcedure &) [private]
Invalidated assignment operator.
void MSTLLogicControl::WAUTSwitchProcedure::switchToPos (SUMOTime simStep, MSTrafficLightLogic & logic, SUMOTime toTime) [protected]
switches the given logic directly to the given position
Parameters:
[in] simStep The current simulation time
[in] logic The logic to switch
[in] toTime The time offset within the logic's phases to switch to
Definition at line 250 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSPhaseDefinition::duration, getDiffToStartOfPhase(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getPhase(), and myControl.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
virtual bool MSTLLogicControl::WAUTSwitchProcedure::trySwitch (SUMOTime step) [pure virtual]
Determines whether a switch is possible.
Parameters:
[in] step The current simulation step
Returns:
If a switch shall be done, this method should return true.
Implemented in MSTLLogicControl::WAUTSwitchProcedure_JustSwitch, MSTLLogicControl::WAUTSwitchProcedure_GSP, and MSTLLogicControl::WAUTSwitchProcedure_Stretch.
Referenced by MSTLLogicControl::check2Switch().
Field Documentation
MSTLLogicControl& MSTLLogicControl::WAUTSwitchProcedure::myControl [protected]
The control the logic belongs to.
Definition at line 584 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and switchToPos().
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myFrom [protected]
The current program of the tls to switch.
Definition at line 572 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
bool MSTLLogicControl::WAUTSwitchProcedure::mySwitchSynchron [protected]
Information whether to switch synchron (?).
Definition at line 578 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myTo [protected]
The program to switch the tls to.
Definition at line 575 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch().
WAUT& MSTLLogicControl::WAUTSwitchProcedure::myWAUT [protected]
The WAUT responsible for switching.
Definition at line 581 of file MSTLLogicControl.h.
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp