SUMO - Simulation of Urban MObility: MSVehicleControl Class Reference
MSVehicleControl Class Reference
The class responsible for building and deletion of vehicles.
#include <MSVehicleControl.h>
Public Types
typedef std::map< std::string,
SUMOVehicle * >
::const_iterator constVehIt
Definition of the internal vehicles map iterator.
Public Member Functions
void abortWaiting ()
removes any vehicles that are still waiting
void addWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
SUMOVehicle * getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > &lines)
MSVehicleControl ()
Constructor.
void registerOneWaitingForPerson ()
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
void removeWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
void unregisterOneWaitingForPerson ()
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
virtual ~MSVehicleControl ()
Destructor.
Insertion, deletion and retrieval of vehicles
virtual bool addVehicle (const std::string &id, SUMOVehicle *v)
Tries to insert the vehicle into the internal vehicle container.
virtual void deleteVehicle (SUMOVehicle *v)
Deletes the vehicle.
SUMOVehicle * getVehicle (const std::string &id) const
Returns the vehicle with the given id.
constVehIt loadedVehBegin () const
Returns the begin of the internal vehicle map.
constVehIt loadedVehEnd () const
Returns the end of the internal vehicle map.
void scheduleVehicleRemoval (SUMOVehicle *veh)
Removes a vehicle after it has ended.
Insertion and retrieval of vehicle types
bool addVType (MSVehicleType *vehType)
Adds a vehicle type.
bool addVTypeDistribution (const std::string &id, RandomDistributor< MSVehicleType * > *vehTypeDistribution)
Adds a vehicle type distribution.
MSVehicleType * getVType (const std::string &id=DEFAULT_VTYPE_ID)
Returns the named vehicle type or a sample from the named distribution.
bool hasVTypeDistribution (const std::string &id) const
Asks for a vehicle type distribution.
void insertVTypeIDs (std::vector< std::string > &into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
Vehicle creation
virtual SUMOVehicle * buildVehicle (SUMOVehicleParameter *defs, const MSRoute *route, const MSVehicleType *type)
Builds a vehicle, increases the number of built vehicles.
Retrieval of vehicle statistics (always accessable)
int getActiveVehicleCount () const
Returns the number of build vehicles that have not been removed or need to wait for a passenger.
unsigned int getDepartedVehicleNo () const
Returns the number of inserted vehicles.
unsigned int getEndedVehicleNo () const
Returns the number of removed vehicles.
unsigned int getLoadedVehicleNo () const
Returns the number of build vehicles.
unsigned int getRunningVehicleNo () const
Returns the number of build and inserted, but not yet deleted vehicles.
bool isInQuota (const SUMOReal frac) const
Returns the information whether the currently vehicle number is still in the given range.
State I/O (mesosim only)
virtual void loadState (BinaryInputDevice &bis, const SUMOTime offset)
Saves the current state into the given stream.
virtual void saveState (std::ostream &os)
Loads the state of this control from the given stream.
Retrieval of vehicle statistics (availability depends on simulation settings)
void printMeanTravelTime (OutputDevice &od) const
Returns the mean travel time of vehicles The mean travel time of ended vehicles (-1 if no vehicle has ended, yet).
void printMeanWaitingTime (OutputDevice &od) const
Prints the mean waiting time of vehicles. The mean time vehicles had to wait for being inserted (-1 if no vehicle was inserted, yet).
Setting vehicle statistics
void vehicleDeparted (const SUMOVehicle &v)
Informs this control about a vehicle's departure.
Protected Attributes
Vehicle statistics (always accessable)
unsigned int myEndedVehNo
The number of removed vehicles.
unsigned int myLoadedVehNo
The number of build vehicles.
unsigned int myRunningVehNo
The number of vehicles within the network (build and inserted but not removed).
Vehicle statistics
SUMOReal myTotalDepartureDelay
The aggregated time vehicles had to wait for departure (in seconds).
SUMOReal myTotalTravelTime
The aggregated time vehicles needed to aacomplish their route (in seconds).
Private Member Functions
bool checkVType (const std::string &id)
Checks whether the vehicle type (distribution) may be added.
Vehicle container
typedef std::map< std::string,
SUMOVehicle * > VehicleDictType
Vehicle dictionary type.
VehicleDictType myVehicleDict
Dictionary of vehicles.
Vehicle type container
typedef std::map< std::string,
MSVehicleType * > VTypeDictType
Vehicle type dictionary type.
typedef std::map< std::string,
RandomDistributor
< MSVehicleType * > * > VTypeDistDictType
Vehicle type distribution dictionary type.
bool myDefaultVTypeMayBeDeleted
Whether no vehicle type was loaded.
VTypeDictType myVTypeDict
Dictionary of vehicle types.
VTypeDistDictType myVTypeDistDict
A distribution of vehicle types (probability->vehicle type).
std::map< const MSEdge *const,
std::vector< SUMOVehicle * > > myWaiting
the lists of waiting vehicles
unsigned int myWaitingForPerson
the number of vehicles contained in myWaiting which can only continue by being triggered
MSVehicleControl (const MSVehicleControl &s)
invalidated copy constructor
MSVehicleControl & operator= (const MSVehicleControl &s)
invalidated assignment operator
Detailed Description
The class responsible for building and deletion of vehicles.
This class is responsible for vehicle building and deletion. It stores vehicle types, vehicles and statistics about the last.
This class also realizes the tripinfos and the vehroutes - outputs, both generated when a vehicle is removed from the simulation, see scheduleVehicleRemoval.
Use this class for the pure microsim and GUIVehicleControl within the gui.
See also:
GUIVehicleControl
Definition at line 73 of file MSVehicleControl.h.
Member Typedef Documentation
typedef std::map<std::string, SUMOVehicle*>::const_iterator MSVehicleControl::constVehIt
Definition of the internal vehicles map iterator.
Definition at line 76 of file MSVehicleControl.h.
typedef std::map< std::string, SUMOVehicle* > MSVehicleControl::VehicleDictType [protected]
Vehicle dictionary type.
Definition at line 402 of file MSVehicleControl.h.
typedef std::map< std::string, MSVehicleType* > MSVehicleControl::VTypeDictType [protected]
Vehicle type dictionary type.
Definition at line 412 of file MSVehicleControl.h.
typedef std::map< std::string, RandomDistributor<MSVehicleType*>* > MSVehicleControl::VTypeDistDictType [protected]
Vehicle type distribution dictionary type.
Definition at line 417 of file MSVehicleControl.h.
Constructor & Destructor Documentation
MSVehicleControl::MSVehicleControl ()
Constructor.
Definition at line 52 of file MSVehicleControl.cpp.
References MSVehicleType::build(), DEFAULT_VTYPE_ID, and myVTypeDict.
MSVehicleControl::~MSVehicleControl () [virtual]
Destructor.
Definition at line 65 of file MSVehicleControl.cpp.
References myVehicleDict, myVTypeDict, and myVTypeDistDict.
MSVehicleControl::MSVehicleControl (const MSVehicleControl & s) [private]
invalidated copy constructor
Member Function Documentation
void MSVehicleControl::abortWaiting ()
removes any vehicles that are still waiting
Definition at line 299 of file MSVehicleControl.cpp.
References myVehicleDict, and WRITE_WARNING.
Referenced by MSNet::simulationState().
bool MSVehicleControl::addVehicle (const std::string & id, SUMOVehicle * v) [virtual]
Tries to insert the vehicle into the internal vehicle container.
Checks whether another vehicle with the same id exists; returns false if so. Otherwise, the vehicle is added to "myVehicleDict" and true is returned.
The vehicle control gets responsible for vehicle deletion.
Parameters:
[in] id The id of the vehicle
[in] v The vehicle
Returns:
Whether the vehicle could be inserted (no other vehicle with the same id was inserted before)
Reimplemented in GUIVehicleControl.
Definition at line 150 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by MSInsertionControl::checkFlows(), MSRouteHandler::closeVehicle(), and TraCIServerAPI_Vehicle::processSet().
bool MSVehicleControl::addVType (MSVehicleType * vehType)
Adds a vehicle type.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type is added to the internal vehicle type container "myVTypeDict".
This control get responsible for deletion of the added vehicle type.
Parameters:
[in] vehType The vehicle type to add
Returns:
Whether the vehicle type could be added
Definition at line 210 of file MSVehicleControl.cpp.
References checkVType(), MSVehicleType::getID(), and myVTypeDict.
bool MSVehicleControl::addVTypeDistribution (const std::string & id, RandomDistributor< MSVehicleType * > * vehTypeDistribution)
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters:
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns:
Whether the vehicle type could be added
Definition at line 220 of file MSVehicleControl.cpp.
References checkVType(), and myVTypeDistDict.
void MSVehicleControl::addWaiting (const MSEdge *const edge, SUMOVehicle * vehicle)
Definition at line 265 of file MSVehicleControl.cpp.
References myWaiting.
Referenced by MSRouteHandler::closeVehicle().
SUMOVehicle * MSVehicleControl::buildVehicle (SUMOVehicleParameter * defs, const MSRoute * route, const MSVehicleType * type) [virtual]
Builds a vehicle, increases the number of built vehicles.
Builds a MSVehicle instance using the given parameter. Increases the number of loaded vehicles ("myLoadedVehNo").
Parameters:
[in] id The id of the vehicle to build
[in] route The route of this vehicle
[in] departTime The departure time of this vehicle
[in] type The type of this vehicle
[in] repNo The number of repetitions
[in] repOffset The repetition offset
Returns:
The built vehicle (MSVehicle instance)
Reimplemented in GUIVehicleControl.
Definition at line 85 of file MSVehicleControl.cpp.
References MSNet::getInstance(), MSNet::informVehicleStateListener(), myLoadedVehNo, and MSNet::VEHICLE_STATE_BUILT.
Referenced by MSInsertionControl::checkFlows(), MSRouteHandler::closeVehicle(), and TraCIServerAPI_Vehicle::processSet().
bool MSVehicleControl::checkVType (const std::string & id) [private]
Checks whether the vehicle type (distribution) may be added.
Removed the vehicle from the internal dictionary
Parameters:
[in] id The id of the vehicle type (distribution) to add
Returns:
Whether the type (distribution) may be added
Definition at line 192 of file MSVehicleControl.cpp.
References DEFAULT_VTYPE_ID, myDefaultVTypeMayBeDeleted, myVTypeDict, and myVTypeDistDict.
Referenced by addVType(), and addVTypeDistribution().
void MSVehicleControl::deleteVehicle (SUMOVehicle * v) [virtual]
Deletes the vehicle.
Parameters:
[in] v The vehicle to delete
Todo:
Isn't this quite insecure?
Reimplemented in GUIVehicleControl.
Definition at line 172 of file MSVehicleControl.cpp.
References SUMOVehicle::getID(), myEndedVehNo, and myVehicleDict.
Referenced by MSRouteHandler::closeVehicle(), scheduleVehicleRemoval(), and MSInsertionControl::tryInsert().
int MSVehicleControl::getActiveVehicleCount () const [inline]
Returns the number of build vehicles that have not been removed or need to wait for a passenger.
Returns:
Number of active vehicles
Definition at line 241 of file MSVehicleControl.h.
References myEndedVehNo, myLoadedVehNo, and myWaitingForPerson.
Referenced by MSNet::simulationState().
unsigned int MSVehicleControl::getDepartedVehicleNo () const [inline]
Returns the number of inserted vehicles.
Returns:
The number of vehicles that have entered the simulation so far
Definition at line 221 of file MSVehicleControl.h.
References myEndedVehNo, and myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSNet::postSimStepOutput(), printMeanWaitingTime(), and MSNet::writeOutput().
unsigned int MSVehicleControl::getEndedVehicleNo () const [inline]
Returns the number of removed vehicles.
Returns:
The number of vehicles that have left the simulation
Definition at line 205 of file MSVehicleControl.h.
References myEndedVehNo.
Referenced by GUINet::getParameterWindow(), and MSNet::writeOutput().
unsigned int MSVehicleControl::getLoadedVehicleNo () const [inline]
Returns the number of build vehicles.
Returns:
The number of loaded (build) vehicles
Definition at line 197 of file MSVehicleControl.h.
References myLoadedVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and MSNet::writeOutput().
unsigned int MSVehicleControl::getRunningVehicleNo () const [inline]
Returns the number of build and inserted, but not yet deleted vehicles.
Returns:
The number simulated vehicles (including those in teleporter)
Definition at line 213 of file MSVehicleControl.h.
References myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSNet::postSimStepOutput(), GUINet::setSimDuration(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::writeOutput().
SUMOVehicle * MSVehicleControl::getVehicle (const std::string & id) const
Returns the vehicle with the given id.
If no vehicle with the given id is store din "myVehicleDict", 0 is returned.
Parameters:
[in] id The id of the vehicle to retrieve
Returns:
The vehicle with the given id, 0 if no such vehicle exists
Definition at line 162 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by MSInsertionControl::checkFlows(), MSRouteHandler::closeVehicle(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), and GUINet::vehicleExists().
MSVehicleType * MSVehicleControl::getVType (const std::string & id = DEFAULT_VTYPE_ID)
Returns the named vehicle type or a sample from the named distribution.
Parameters:
[in] id The id of the vehicle type to return. If left out, the default type is returned.
Returns:
The named vehicle type, or 0 if no such type exists
Definition at line 236 of file MSVehicleControl.cpp.
References DEFAULT_VTYPE_ID, myDefaultVTypeMayBeDeleted, myVTypeDict, and myVTypeDistDict.
Referenced by MSInsertionControl::checkFlows(), MSRouteHandler::closeVehicle(), MSRouteHandler::openVehicleTypeDistribution(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_VehicleType::processSet(), and TraCIServerAPI_Vehicle::processSet().
SUMOVehicle * MSVehicleControl::getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > & lines)
Definition at line 285 of file MSVehicleControl.cpp.
References SUMOVehicle::getParameter(), SUMOVehicleParameter::line, and myWaiting.
Referenced by MSPerson::MSPersonStage_Driving::proceed().
bool MSVehicleControl::hasVTypeDistribution (const std::string & id) const
Asks for a vehicle type distribution.
If vehicle type distribution with the id exists, true is returned, false otherwise.
Parameters:
[in] id The id of the distribution
Returns:
Whether the vehicle type distribution exists
Definition at line 230 of file MSVehicleControl.cpp.
References myVTypeDistDict.
Referenced by MSInsertionControl::add().
void MSVehicleControl::insertVTypeIDs (std::vector< std::string > & into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
Parameters:
[in] into The vector to fill with ids
Definition at line 253 of file MSVehicleControl.cpp.
References myVTypeDict, and myVTypeDistDict.
Referenced by TraCIServerAPI_VehicleType::processGet().
bool MSVehicleControl::isInQuota (const SUMOReal frac) const [inline]
Returns the information whether the currently vehicle number is still in the given range.
Returns:
True iff the vehicle number is acceptable
Definition at line 229 of file MSVehicleControl.h.
References MSGlobals::gFractions, and myLoadedVehNo.
Referenced by MSDevice_Routing::buildVehicleDevices(), MSDevice_HBEFA::buildVehicleDevices(), and MSRouteHandler::closeVehicle().
MSVehicleControl::constVehIt MSVehicleControl::loadedVehBegin () const
Returns the begin of the internal vehicle map.
Returns:
The begin of the internal vehicle map
Definition at line 180 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by MSVTypeProbe::execute(), and TraCIServerAPI_Vehicle::processGet().
MSVehicleControl::constVehIt MSVehicleControl::loadedVehEnd () const
Returns the end of the internal vehicle map.
Returns:
The end of the internal vehicle map
Definition at line 186 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by MSVTypeProbe::execute(), and TraCIServerAPI_Vehicle::processGet().
void MSVehicleControl::loadState (BinaryInputDevice & bis, const SUMOTime offset) [virtual]
Saves the current state into the given stream.
Todo:
Does not work for microsim
Definition at line 145 of file MSVehicleControl.cpp.
MSVehicleControl& MSVehicleControl::operator= (const MSVehicleControl & s) [private]
invalidated assignment operator
void MSVehicleControl::printMeanTravelTime (OutputDevice & od) const
Returns the mean travel time of vehicles The mean travel time of ended vehicles (-1 if no vehicle has ended, yet).
Todo:
Enable this for guisim?
Definition at line 122 of file MSVehicleControl.cpp.
References myEndedVehNo, myTotalTravelTime, and SUMOReal.
Referenced by MSNet::writeOutput().
void MSVehicleControl::printMeanWaitingTime (OutputDevice & od) const
Prints the mean waiting time of vehicles. The mean time vehicles had to wait for being inserted (-1 if no vehicle was inserted, yet).
Todo:
Enable this for guisim?
Definition at line 112 of file MSVehicleControl.cpp.
References getDepartedVehicleNo(), myTotalDepartureDelay, and SUMOReal.
Referenced by MSNet::writeOutput().
void MSVehicleControl::registerOneWaitingForPerson () [inline]
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 332 of file MSVehicleControl.h.
References myWaitingForPerson.
Referenced by MSRouteHandler::closeVehicle().
void MSVehicleControl::removeWaiting (const MSEdge *const edge, SUMOVehicle * vehicle)
Definition at line 274 of file MSVehicleControl.cpp.
References myWaiting.
Referenced by MSPerson::MSPersonStage_Driving::proceed().
void MSVehicleControl::saveState (std::ostream & os) [virtual]
Loads the state of this control from the given stream.
Todo:
Does not work for microsim
Definition at line 140 of file MSVehicleControl.cpp.
void MSVehicleControl::scheduleVehicleRemoval (SUMOVehicle * veh)
Removes a vehicle after it has ended.
Writes output to tripinfos and vehroutes if wished; decrements the number of running vehicles and increments the number of ended vehicles. Then deletes the vehicle using "deleteVehicle".
This method should be called for each vehicle that was inserted into the network and quits its ride.
Parameters:
[in] veh The vehicle to remove
Definition at line 96 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), deleteVehicle(), SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getDevices(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::informVehicleStateListener(), myRunningVehNo, myTotalTravelTime, STEPS2TIME, and MSNet::VEHICLE_STATE_ARRIVED.
Referenced by TraCIServerAPI_Vehicle::processSet(), and MSLane::setCritical().
void MSVehicleControl::unregisterOneWaitingForPerson () [inline]
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 338 of file MSVehicleControl.h.
References myWaitingForPerson.
Referenced by MSPerson::MSPersonStage_Driving::proceed().
void MSVehicleControl::vehicleDeparted (const SUMOVehicle & v)
Informs this control about a vehicle's departure.
If the mean waiting time shall be computed (f.e. for emissions-output), the absolut waiting time is increased by the waiting time of the given vehicle.
Parameters:
[in] v The inserted vehicle
Definition at line 132 of file MSVehicleControl.cpp.
References SUMOVehicleParameter::depart, SUMOVehicle::getDeparture(), MSNet::getInstance(), SUMOVehicle::getParameter(), MSNet::informVehicleStateListener(), myRunningVehNo, myTotalDepartureDelay, STEPFLOOR, STEPS2TIME, and MSNet::VEHICLE_STATE_DEPARTED.
Referenced by MSBaseVehicle::onDepart().
Field Documentation
bool MSVehicleControl::myDefaultVTypeMayBeDeleted [protected]
Whether no vehicle type was loaded.
Definition at line 422 of file MSVehicleControl.h.
Referenced by checkVType(), and getVType().
unsigned int MSVehicleControl::myEndedVehNo [protected]
The number of removed vehicles.
Definition at line 383 of file MSVehicleControl.h.
Referenced by deleteVehicle(), getActiveVehicleCount(), getDepartedVehicleNo(), getEndedVehicleNo(), and printMeanTravelTime().
unsigned int MSVehicleControl::myLoadedVehNo [protected]
The number of build vehicles.
Definition at line 377 of file MSVehicleControl.h.
Referenced by buildVehicle(), GUIVehicleControl::buildVehicle(), getActiveVehicleCount(), getLoadedVehicleNo(), and isInQuota().
unsigned int MSVehicleControl::myRunningVehNo [protected]
The number of vehicles within the network (build and inserted but not removed).
Definition at line 380 of file MSVehicleControl.h.
Referenced by getDepartedVehicleNo(), getRunningVehicleNo(), scheduleVehicleRemoval(), and vehicleDeparted().
SUMOReal MSVehicleControl::myTotalDepartureDelay [protected]
The aggregated time vehicles had to wait for departure (in seconds).
Definition at line 391 of file MSVehicleControl.h.
Referenced by printMeanWaitingTime(), and vehicleDeparted().
SUMOReal MSVehicleControl::myTotalTravelTime [protected]
The aggregated time vehicles needed to aacomplish their route (in seconds).
Definition at line 394 of file MSVehicleControl.h.
Referenced by printMeanTravelTime(), and scheduleVehicleRemoval().
VehicleDictType MSVehicleControl::myVehicleDict [protected]
Dictionary of vehicles.
Definition at line 404 of file MSVehicleControl.h.
Referenced by abortWaiting(), addVehicle(), deleteVehicle(), getVehicle(), GUIVehicleControl::insertVehicleIDs(), loadedVehBegin(), loadedVehEnd(), and ~MSVehicleControl().
VTypeDictType MSVehicleControl::myVTypeDict [protected]
Dictionary of vehicle types.
Definition at line 414 of file MSVehicleControl.h.
Referenced by addVType(), checkVType(), getVType(), insertVTypeIDs(), MSVehicleControl(), and ~MSVehicleControl().
VTypeDistDictType MSVehicleControl::myVTypeDistDict [protected]
A distribution of vehicle types (probability->vehicle type).
Definition at line 419 of file MSVehicleControl.h.
Referenced by addVTypeDistribution(), checkVType(), getVType(), hasVTypeDistribution(), insertVTypeIDs(), and ~MSVehicleControl().
std::map<const MSEdge* const, std::vector<SUMOVehicle*> > MSVehicleControl::myWaiting [protected]
the lists of waiting vehicles
Definition at line 425 of file MSVehicleControl.h.
Referenced by addWaiting(), getWaitingVehicle(), and removeWaiting().
unsigned int MSVehicleControl::myWaitingForPerson [protected]
the number of vehicles contained in myWaiting which can only continue by being triggered
Definition at line 428 of file MSVehicleControl.h.
Referenced by getActiveVehicleCount(), registerOneWaitingForPerson(), and unregisterOneWaitingForPerson().
The documentation for this class was generated from the following files:
MSVehicleControl.h
MSVehicleControl.cpp