SUMO - Simulation of Urban MObility: MSMeanData Class Reference
MSMeanData Class Reference
Data collector for edges/lanes.
#include <MSMeanData.h>
Data Structures
class MeanDataValues
Data structure for mean (aggregated) edge/lane values.
class MeanDataValueTracker
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
Public Member Functions
virtual void detectorUpdate (const SUMOTime step)
Updates the detector.
const std::string & getID () const
Returns the id.
void init ()
Adds the value collectors to all relevant edges.
MSMeanData (const std::string &id, const SUMOTime dumpBegin, const SUMOTime dumpEnd, const bool useLanes, const bool withEmpty, const bool withInternal, const bool trackVehicles, const SUMOReal minSamples, const SUMOReal maxTravelTime, const std::set< std::string > vTypes)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MSMeanData ()
Destructor.
Virtual methods to implement by derived classes
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
virtual void reset ()
Resets collected values.
Methods inherited from MSDetectorFileOutput.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "netstats" as root element.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
Protected Member Functions
virtual
MSMeanData::MeanDataValues * createValues (MSLane *const lane, const SUMOReal length, const bool doAdd) const =0
Create an instance of MeanDataValues.
void resetOnly (SUMOTime stopTime)
Resets network value in order to allow processing of the next interval.
void writeEdge (OutputDevice &dev, const std::vector< MeanDataValues * > &edgeValues, MSEdge *edge, SUMOTime startTime, SUMOTime stopTime)
Writes edge values into the given stream.
bool writePrefix (OutputDevice &dev, const MeanDataValues &values, const std::string prefix) const
Checks for emptiness and writes prefix into the given stream.
Protected Attributes
std::string myID
The name of the object.
const SUMOReal myMaxTravelTime
the maximum travel time to write
std::vector< std::vector
< MeanDataValues * > > myMeasures
Value collectors; sorted by edge, then by lane.
const SUMOReal myMinSamples
the minimum sample seconds
const std::set< std::string > myVehicleTypes
The vehicle types to look for (empty means all).
Private Member Functions
MSMeanData (const MSMeanData &)
Invalidated copy constructor.
MSMeanData & operator= (const MSMeanData &)
Invalidated assignment operator.
Private Attributes
const bool myAmEdgeBased
Information whether the output shall be edge-based (not lane-based).
const SUMOTime myDumpBegin
The first and the last time step to write information (-1 indicates always).
const bool myDumpEmpty
Whether empty lanes/edges shall be written.
const SUMOTime myDumpEnd
const bool myDumpInternal
Whether internal lanes/edges shall be written.
std::vector< MSEdge * > myEdges
The corresponding first edges.
std::list< std::pair< SUMOTime,
SUMOTime > > myPendingIntervals
The intervals for which output still has to be generated (only in the tracking case).
const bool myTrackVehicles
Whether vehicles are tracked.
Detailed Description
Data collector for edges/lanes.
This structure does not contain the data itself, it is stored within MeanDataValues-MoveReminder objects. This class is used to build the output, optionally, in the case of edge-based dump, aggregated over the edge's lanes.
Todo:
consider error-handling on write (using IOError)
Definition at line 67 of file MSMeanData.h.
Constructor & Destructor Documentation
MSMeanData::MSMeanData (const std::string & id, const SUMOTime dumpBegin, const SUMOTime dumpEnd, const bool useLanes, const bool withEmpty, const bool withInternal, const bool trackVehicles, const SUMOReal minSamples, const SUMOReal maxTravelTime, const std::set< std::string > vTypes)
Constructor.
Parameters:
[in] id The id of the detector
[in] dumpBegin Begin time of dump
[in] dumpEnd End time of dump
[in] useLanes Information whether lane-based or edge-based dump shall be generated
[in] withEmpty Information whether empty lanes/edges shall be written
[in] withInternal Information whether internal lanes/edges shall be written
[in] trackVehicles Information whether vehicles shall be tracked
[in] maxTravelTime the maximum travel time to use when calculating per vehicle output
[in] minSamples the minimum number of sample seconds before the values are valid
[in] vTypes the set of vehicle types to consider
Definition at line 240 of file MSMeanData.cpp.
MSMeanData::~MSMeanData () [virtual]
Destructor.
Definition at line 306 of file MSMeanData.cpp.
References myMeasures.
MSMeanData::MSMeanData (const MSMeanData &) [private]
Invalidated copy constructor.
Member Function Documentation
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () [inline, virtual, inherited]
Builds the graphical representation.
Meant to be overridden by grahical versions of the detectors
Returns:
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUI_E2_ZS_CollectorOverLanes, GUIE3Collector, GUIInductLoop, and GUIInstantInductLoop.
Definition at line 121 of file MSDetectorFileOutput.h.
virtual MSMeanData::MeanDataValues* MSMeanData::createValues (MSLane *const lane, const SUMOReal length, const bool doAdd) const [protected, pure virtual]
Create an instance of MeanDataValues.
Parameters:
[in] lane The lane to create for
[in] doAdd whether to add the values as reminder to the lane
Implemented in MSMeanData_Harmonoise, MSMeanData_HBEFA, and MSMeanData_Net.
Referenced by init(), MSMeanData::MeanDataValueTracker::MeanDataValueTracker(), MSMeanData::MeanDataValueTracker::reset(), and writeEdge().
void MSMeanData::detectorUpdate (const SUMOTime step) [virtual]
Updates the detector.
Reimplemented from MSDetectorFileOutput.
Reimplemented in MSMeanData_Harmonoise.
Definition at line 465 of file MSMeanData.cpp.
References DELTA_T, init(), and myDumpBegin.
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
void MSMeanData::init ()
Adds the value collectors to all relevant edges.
Definition at line 260 of file MSMeanData.cpp.
References createValues(), MSEdge::EDGEFUNCTION_INTERNAL, MSNet::getEdgeControl(), MSEdgeControl::getEdges(), MSNet::getInstance(), myAmEdgeBased, myDumpInternal, myEdges, myMeasures, myTrackVehicles, myVehicleTypes, and MSMeanData::MeanDataValues::reset().
Referenced by MSDetectorControl::add(), and detectorUpdate().
MSMeanData& MSMeanData::operator= (const MSMeanData &) [private]
Invalidated assignment operator.
virtual void MSDetectorFileOutput::reset () [inline, virtual, inherited]
Resets collected values.
Please note that this is only a "hack" for coupled-tls-outputs.
See also:
Command_SaveTLCoupledLaneDet
Todo:
Reckeck/refactor
Reimplemented in GUIInductLoop, MSE2Collector, MSE3Collector, and MSInductLoop.
Definition at line 106 of file MSDetectorFileOutput.h.
Referenced by Command_SaveTLCoupledLaneDet::execute().
void MSMeanData::resetOnly (SUMOTime stopTime) [protected]
Resets network value in order to allow processing of the next interval.
Goes through the lists of edges and starts "resetOnly" for each edge.
Parameters:
[in] edge The last time step that is reported
Reimplemented in MSMeanData_Net.
Definition at line 316 of file MSMeanData.cpp.
References myEdges, myMeasures, MSMeanData::MeanDataValues::reset(), and UNUSED_PARAMETER.
Referenced by writeXMLOutput().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSMeanData::writeEdge (OutputDevice & dev, const std::vector< MeanDataValues * > & edgeValues, MSEdge * edge, SUMOTime startTime, SUMOTime stopTime) [protected]
Writes edge values into the given stream.
microsim: It is checked whether the dump shall be generated edge- or lane-wise. In the first case, the lane-data are collected and aggregated and written directly. In the second case, "writeLane" is used to write each lane's state.
Parameters:
[in] dev The output device to write the data into
[in] edgeValues List of this edge's value collectors
[in] edge The edge to write the dump of
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 342 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::addTo(), OutputDevice::closeTag(), createValues(), Named::getID(), MSEdge::getID(), MSMoveReminder::getLane(), MSEdge::getLanes(), myAmEdgeBased, myDumpEmpty, myTrackVehicles, OutputDevice::openTag(), MSMeanData::MeanDataValues::reset(), SUMOReal, MSMeanData::MeanDataValues::write(), and writePrefix().
Referenced by writeXMLOutput().
bool MSMeanData::writePrefix (OutputDevice & dev, const MeanDataValues & values, const std::string prefix) const [protected]
Checks for emptiness and writes prefix into the given stream.
Parameters:
[in] dev The output device to write the data into
[in] values The values to check for emptiness
[in] prefix The xml prefix to write (mostly the lane / edge id)
Returns:
whether further output should be generated
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 409 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::getSamples(), OutputDevice::indent(), MSMeanData::MeanDataValues::isEmpty(), and myDumpEmpty.
Referenced by writeEdge().
void MSMeanData::writeXMLDetectorProlog (OutputDevice & dev) const [virtual]
Opens the XML-output using "netstats" as root element.
Parameters:
[in] dev The output device to write the root into
See also:
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 459 of file MSMeanData.cpp.
References OutputDevice::writeXMLHeader().
void MSMeanData::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [virtual]
Writes collected values into the given stream.
At first, it is checked whether the values for the current interval shall be written. If not, a reset is performed, only, using "resetOnly". Otherwise, both the list of single-lane edges and the list of multi-lane edges are gone through and each edge is written using "writeEdge".
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also:
MSDetectorFileOutput::writeXMLOutput
write
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 419 of file MSMeanData.cpp.
References OutputDevice::closeTag(), DELTA_T, MIN2(), myDumpBegin, myDumpEnd, myEdges, Named::myID, myMeasures, myPendingIntervals, myTrackVehicles, OutputDevice::openTag(), resetOnly(), time2string(), and writeEdge().
Field Documentation
const bool MSMeanData::myAmEdgeBased [private]
Information whether the output shall be edge-based (not lane-based).
Definition at line 425 of file MSMeanData.h.
Referenced by init(), and writeEdge().
const SUMOTime MSMeanData::myDumpBegin [private]
The first and the last time step to write information (-1 indicates always).
Definition at line 428 of file MSMeanData.h.
Referenced by detectorUpdate(), and writeXMLOutput().
const bool MSMeanData::myDumpEmpty [private]
Whether empty lanes/edges shall be written.
Definition at line 434 of file MSMeanData.h.
Referenced by writeEdge(), and writePrefix().
const SUMOTime MSMeanData::myDumpEnd [private]
Definition at line 428 of file MSMeanData.h.
Referenced by writeXMLOutput().
const bool MSMeanData::myDumpInternal [private]
Whether internal lanes/edges shall be written.
Definition at line 437 of file MSMeanData.h.
Referenced by init().
std::vector<MSEdge*> MSMeanData::myEdges [private]
The corresponding first edges.
Definition at line 431 of file MSMeanData.h.
Referenced by init(), resetOnly(), and writeXMLOutput().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const SUMOReal MSMeanData::myMaxTravelTime [protected]
the maximum travel time to write
Definition at line 415 of file MSMeanData.h.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::write().
std::vector<std::vector<MeanDataValues*> > MSMeanData::myMeasures [protected]
Value collectors; sorted by edge, then by lane.
Definition at line 421 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::detectorUpdate(), init(), resetOnly(), writeXMLOutput(), and ~MSMeanData().
const SUMOReal MSMeanData::myMinSamples [protected]
the minimum sample seconds
Definition at line 412 of file MSMeanData.h.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::write().
std::list< std::pair<SUMOTime, SUMOTime> > MSMeanData::myPendingIntervals [private]
The intervals for which output still has to be generated (only in the tracking case).
Definition at line 443 of file MSMeanData.h.
Referenced by writeXMLOutput().
const bool MSMeanData::myTrackVehicles [private]
Whether vehicles are tracked.
Definition at line 440 of file MSMeanData.h.
Referenced by init(), writeEdge(), and writeXMLOutput().
const std::set<std::string> MSMeanData::myVehicleTypes [protected]
The vehicle types to look for (empty means all).
Definition at line 418 of file MSMeanData.h.
Referenced by MSMeanData_Net::createValues(), MSMeanData_HBEFA::createValues(), MSMeanData_Harmonoise::createValues(), and init().
The documentation for this class was generated from the following files:
MSMeanData.h
MSMeanData.cpp