SUMO - Simulation of Urban MObility: GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel Class Reference
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel Class Reference
The canvas for the visualisation of phases.
#include <GUITLLogicPhasesTrackerWindow.h>
Public Member Functions
GUITLLogicPhasesTrackerPanel (FXComposite *c, GUIMainWindow &app, GUITLLogicPhasesTrackerWindow &parent)
Constructor.
~GUITLLogicPhasesTrackerPanel ()
Destructor.
Friends
class GUITLLogicPhasesTrackerWindow
needed to update
FOX-callbacks
{
GUIMainWindow * myApplication
The main application.
GUITLLogicPhasesTrackerWindow * myParent
}
long onConfigure (FXObject *, FXSelector, void *)
called on size change
long onPaint (FXObject *, FXSelector, void *)
called if the widget shall be repainted
GUITLLogicPhasesTrackerPanel ()
protected constructor for FOX
Detailed Description
The canvas for the visualisation of phases.
The drawing itself id done by the parent.
Definition at line 142 of file GUITLLogicPhasesTrackerWindow.h.
Constructor & Destructor Documentation
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::GUITLLogicPhasesTrackerPanel (FXComposite * c, GUIMainWindow & app, GUITLLogicPhasesTrackerWindow & parent)
Constructor.
Parameters:
[in] c The container for this panel
[in] app The main application window
[in] parent This panel's logial parent
Definition at line 78 of file GUITLLogicPhasesTrackerWindow.cpp.
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::~GUITLLogicPhasesTrackerPanel ()
Destructor.
Definition at line 85 of file GUITLLogicPhasesTrackerWindow.cpp.
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::GUITLLogicPhasesTrackerPanel () [inline, protected]
protected constructor for FOX
Definition at line 180 of file GUITLLogicPhasesTrackerWindow.h.
Member Function Documentation
long GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::onConfigure (FXObject * , FXSelector , void *)
called on size change
Definition at line 89 of file GUITLLogicPhasesTrackerWindow.cpp.
Referenced by GUITLLogicPhasesTrackerWindow::onConfigure().
long GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::onPaint (FXObject * , FXSelector , void *)
called if the widget shall be repainted
Definition at line 112 of file GUITLLogicPhasesTrackerWindow.cpp.
References GUITLLogicPhasesTrackerWindow::drawValues(), and myParent.
Referenced by GUITLLogicPhasesTrackerWindow::onPaint().
Friends And Related Function Documentation
friend class GUITLLogicPhasesTrackerWindow [friend]
needed to update
Definition at line 157 of file GUITLLogicPhasesTrackerWindow.h.
Field Documentation
GUIMainWindow* GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::myApplication [private]
The main application.
Definition at line 176 of file GUITLLogicPhasesTrackerWindow.h.
GUITLLogicPhasesTrackerWindow* GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::myParent [private]
}
The parent window
Definition at line 173 of file GUITLLogicPhasesTrackerWindow.h.
Referenced by onPaint().
The documentation for this class was generated from the following files:
GUITLLogicPhasesTrackerWindow.h
GUITLLogicPhasesTrackerWindow.cpp