SUMO - Simulation of Urban MObility: NWWriter_SUMO Class Reference
NWWriter_SUMO Class Reference
Exporter writing networks using the SUMO format.
#include <NWWriter_SUMO.h>
Public Types
enum ConnectionStyle { SUMONET, PLAIN, TLL }
Static Public Member Functions
static void writeConnection (OutputDevice &into, const NBEdge &from, const NBEdge::Connection &c, bool includeInternal, ConnectionStyle style=SUMONET)
Writes connections outgoing from the given edge (also used in NWWriter_XML).
static void writeLocation (OutputDevice &into)
writes the location element
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a SUMO-file.
static void writeProhibitions (OutputDevice &into, const NBConnectionProhibits &prohibitions)
writes the given prohibitions
static void writeTrafficLights (OutputDevice &into, const NBTrafficLightLogicCont &tllCont)
writes the traffic light logics to the given device
Methods for writing network parts
static void writeDistrict (OutputDevice &into, const NBDistrict &d)
Writes a district.
static void writeEdge (OutputDevice &into, const NBEdge &e, bool noNames)
Writes an edge (<edge ...).
static bool writeInternalConnections (OutputDevice &into, const NBNode &n)
Writes inner connections within the node.
static bool writeInternalEdges (OutputDevice &into, const NBNode &n)
Writes internal edges (<edge ... with id[0]==':') of the given node.
static bool writeInternalNodes (OutputDevice &into, const NBNode &n)
Writes internal junctions (<junction with id[0]==':' ...) of the given node.
static void writeJunction (OutputDevice &into, const NBNode &n)
Writes a junction (<junction ...).
static void writeLane (OutputDevice &into, const std::string &lID, const std::string &eID, const NBEdge::Lane &lane, SUMOReal length, unsigned int index)
Writes a lane (<lane ...) of an edge.
static void writeRoundabout (OutputDevice &into, const std::set< NBEdge * > &r)
Writes a roundabout.
static std::string prohibitionConnection (const NBConnection &c)
the attribute value for a prohibition
static void writeInternalConnection (OutputDevice &into, const std::string &from, const std::string &to, int toLane, const std::string &via)
Writes a single internal connection.
static void writeInternalEdge (OutputDevice &into, const std::string &id, SUMOReal vmax, const PositionVector &shape)
Writes a single internal edge.
static std::string writeSUMOTime (SUMOTime time)
writes a SUMOTime as int if possible, otherwise as a float
Detailed Description
Exporter writing networks using the SUMO format.
Definition at line 62 of file NWWriter_SUMO.h.
Member Enumeration Documentation
enum NWWriter_SUMO::ConnectionStyle
Enumerator:
SUMONET
PLAIN
TLL
Definition at line 65 of file NWWriter_SUMO.h.
Member Function Documentation
std::string NWWriter_SUMO::prohibitionConnection (const NBConnection & c) [static, private]
the attribute value for a prohibition
Definition at line 534 of file NWWriter_SUMO.cpp.
References NBConnection::getFrom(), Named::getID(), and NBConnection::getTo().
Referenced by writeProhibitions().
void NWWriter_SUMO::writeConnection (OutputDevice & into, const NBEdge & from, const NBEdge::Connection & c, bool includeInternal, ConnectionStyle style = SUMONET) [static]
Writes connections outgoing from the given edge (also used in NWWriter_XML).
Parameters:
[in] into The device to write the edge into
[in] from The edge to write connections for
[in] c The connection to write
[in] includeInternal Whether information about inner-lanes used to cross the intersection shall be written
[in] plain Whether only plain-xml output should be written (omit some attributes)
Definition at line 372 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBEdge::Connection::fromLane, NBNode::getDirection(), Named::getID(), NBEdge::getToNode(), NBEdge::Connection::id, LINKDIR_NODIR, LINKSTATE_TL_OFF_BLINKING, NBEdge::Connection::mayDefinitelyPass, OutputDevice::openTag(), PLAIN, NBNode::stateCode(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMO_TAG_CONNECTION, SUMONET, NBEdge::Connection::tlID, NBEdge::Connection::tlLinkNo, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), writeNetwork(), and NWWriter_XML::writeTrafficLights().
void NWWriter_SUMO::writeDistrict (OutputDevice & into, const NBDistrict & d) [static, protected]
Writes a district.
Parameters:
[in] into The device to write the edge into
[in] d The district
Definition at line 475 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), Named::getID(), NBDistrict::getShape(), NBDistrict::getSinkEdges(), NBDistrict::getSinkWeights(), NBDistrict::getSourceEdges(), NBDistrict::getSourceWeights(), OutputDevice::openTag(), PositionVector::size(), SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, and SUMO_TAG_TAZSOURCE.
Referenced by writeNetwork().
void NWWriter_SUMO::writeEdge (OutputDevice & into, const NBEdge & e, bool noNames) [static, protected]
Writes an edge (<edge ...).
Parameters:
[in] into The device to write the edge into
[in] e The edge to write
[in] noNames Whether names shall be ignored
See also:
writeLane()
Definition at line 204 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLanes(), NBEdge::getLaneSpreadFunction(), NBEdge::getLoadedLength(), NBEdge::getPriority(), NBEdge::getStreetName(), NBEdge::getToNode(), NBEdge::getTypeName(), NBEdge::hasDefaultGeometry(), NBEdge::hasLoadedLength(), NBEdge::isMacroscopicConnector(), LANESPREAD_RIGHT, OutputDevice::openTag(), SUMO_ATTR_FROM, SUMO_ATTR_FUNCTION, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_TAG_EDGE, SUMOReal, OutputDevice::writeAttr(), and writeLane().
Referenced by writeNetwork().
void NWWriter_SUMO::writeInternalConnection (OutputDevice & into, const std::string & from, const std::string & to, int toLane, const std::string & via) [static, private]
Writes a single internal connection.
Parameters:
[in] from The id of the from-edge
[in] to The id of the to-edge
[in] toLane The indexd of the to-lane
[in] via The (optional) via edge
Definition at line 435 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_STATE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMO_TAG_CONNECTION, and OutputDevice::writeAttr().
Referenced by writeInternalConnections().
bool NWWriter_SUMO::writeInternalConnections (OutputDevice & into, const NBNode & n) [static, protected]
Writes inner connections within the node.
Parameters:
[in] into The device to write the edge into
[in] n The node to write inner links for
Definition at line 410 of file NWWriter_SUMO.cpp.
References NBEdge::getConnections(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::Connection::haveVia, NBEdge::Connection::id, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, NBEdge::Connection::viaID, and writeInternalConnection().
Referenced by writeNetwork().
void NWWriter_SUMO::writeInternalEdge (OutputDevice & into, const std::string & id, SUMOReal vmax, const PositionVector & shape) [static, private]
Writes a single internal edge.
Parameters:
[in] into The device to write the edges into
[in] id The id of the edge
[in] vmax The maximum speed of the edge
[in] shape The shape of the edge
Definition at line 186 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), EDGEFUNC_INTERNAL, PositionVector::length(), MAX2(), OutputDevice::openTag(), POSITION_EPS, SUMO_ATTR_FUNCTION, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LENGTH, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_TAG_EDGE, SUMO_TAG_LANE, SUMOReal, toString(), and OutputDevice::writeAttr().
Referenced by writeInternalEdges().
bool NWWriter_SUMO::writeInternalEdges (OutputDevice & into, const NBNode & n) [static, protected]
Writes internal edges (<edge ... with id[0]==':') of the given node.
Parameters:
[in] into The device to write the edges into
[in] n The node to write the edges of
Returns:
Whether an internal edge was written
Definition at line 165 of file NWWriter_SUMO.cpp.
References NBNode::getIncomingEdges(), and writeInternalEdge().
Referenced by writeNetwork().
bool NWWriter_SUMO::writeInternalNodes (OutputDevice & into, const NBNode & n) [static, protected]
Writes internal junctions (<junction with id[0]==':' ...) of the given node.
Parameters:
[in] into The device to write the edge into
[in] n The junction/node to write internal nodes for
Definition at line 342 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBNode::getIncomingEdges(), NODETYPE_INTERNAL, OutputDevice::openTag(), SUMO_TAG_JUNCTION, toString(), and NWFrame::writePositionLong().
Referenced by writeNetwork().
void NWWriter_SUMO::writeJunction (OutputDevice & into, const NBNode & n) [static, protected]
Writes a junction (<junction ...).
Parameters:
[in] into The device to write the edge into
[in] n The junction/node to write
Definition at line 287 of file NWWriter_SUMO.cpp.
References OptionsCont::getBool(), Named::getID(), NBNode::getIncomingEdges(), OptionsCont::getOptions(), NBNode::getPosition(), NBNode::getShape(), NBNode::getType(), NODETYPE_DEAD_END, OutputDevice::openTag(), SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, OutputDevice::writeAttr(), NBNode::writeLogic(), and NWFrame::writePositionLong().
Referenced by writeNetwork().
void NWWriter_SUMO::writeLane (OutputDevice & into, const std::string & lID, const std::string & eID, const NBEdge::Lane & lane, SUMOReal length, unsigned int index) [static, protected]
Writes a lane (<lane ...) of an edge.
Parameters:
[in] into The device to write the edge into
[in] e The edge to write
[in] lID The ID of the lane
[in] eID The ID of the edge
[in] lane Lane definition
[in] length Lane's length
[in] index The index of the lane within the edge
Definition at line 245 of file NWWriter_SUMO.cpp.
References NBEdge::Lane::allowed, OutputDevice::closeTag(), PositionVector::getSubpart(), getVehicleClassNames(), PositionVector::length(), NBEdge::Lane::notAllowed, NBEdge::Lane::offset, OutputDevice::openTag(), NBEdge::Lane::preferred, NBEdge::Lane::shape, NBEdge::Lane::speed, SUMO_ATTR_LENGTH, SUMO_ATTR_SPEED, SUMO_TAG_LANE, toString(), NBEdge::UNSPECIFIED_WIDTH, NBEdge::Lane::width, WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by writeEdge().
void NWWriter_SUMO::writeLocation (OutputDevice & into) [static]
writes the location element
Definition at line 566 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), GEO_OUTPUT_ACCURACY, GeoConvHelper::getConvBoundary(), GeoConvHelper::getFinal(), GeoConvHelper::getOffsetBase(), GeoConvHelper::getOrigBoundary(), GeoConvHelper::getProjString(), OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, SUMO_ATTR_ORIG_PROJ, SUMO_TAG_LOCATION, GeoConvHelper::usingGeoProjection(), and OutputDevice::writeAttr().
Referenced by writeNetwork(), and NWWriter_XML::writeNodes().
void NWWriter_SUMO::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) [static]
Writes the network into a SUMO-file.
Parameters:
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 61 of file NWWriter_SUMO.cpp.
References NBDistrictCont::begin(), NBEdgeCont::begin(), NBNodeCont::begin(), OutputDevice::close(), SUMOSAXAttributes::ENCODING, NBDistrictCont::end(), NBEdgeCont::end(), NBNodeCont::end(), OptionsCont::getBool(), NBEdge::getConnections(), OutputDevice::getDevice(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NBNetBuilder::getRoundabouts(), OptionsCont::getString(), NBNetBuilder::getTLLogicCont(), OptionsCont::isSet(), NWFrame::MAJOR_VERSION, NBDistrictCont::size(), NBEdge::sortOutgoingConnectionsByIndex(), writeConnection(), writeDistrict(), writeEdge(), writeInternalConnections(), writeInternalEdges(), writeInternalNodes(), writeJunction(), writeLocation(), writeProhibitions(), writeRoundabout(), writeTrafficLights(), and OutputDevice::writeXMLHeader().
void NWWriter_SUMO::writeProhibitions (OutputDevice & into, const NBConnectionProhibits & prohibitions) [static]
writes the given prohibitions
Definition at line 518 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), prohibitionConnection(), SUMO_ATTR_PROHIBITED, SUMO_ATTR_PROHIBITOR, SUMO_TAG_PROHIBITION, and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), and writeNetwork().
void NWWriter_SUMO::writeRoundabout (OutputDevice & into, const std::set< NBEdge * > & r) [static, protected]
Writes a roundabout.
Parameters:
[in] into The device to write the edge into
[in] r The roundabout to write
Definition at line 452 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), and SUMO_TAG_ROUNDABOUT.
Referenced by writeNetwork().
std::string NWWriter_SUMO::writeSUMOTime (SUMOTime time) [static, private]
writes a SUMOTime as int if possible, otherwise as a float
Definition at line 507 of file NWWriter_SUMO.cpp.
References STEPS2TIME, SUMOReal, and toString().
Referenced by writeTrafficLights().
void NWWriter_SUMO::writeTrafficLights (OutputDevice & into, const NBTrafficLightLogicCont & tllCont) [static]
writes the traffic light logics to the given device
Definition at line 540 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBTrafficLightLogicCont::getComputed(), OutputDevice::openTag(), SUMO_ATTR_DURATION, SUMO_ATTR_ID, SUMO_ATTR_OFFSET, SUMO_ATTR_PROGRAMID, SUMO_ATTR_STATE, SUMO_ATTR_TYPE, SUMO_TAG_PHASE, SUMO_TAG_TLLOGIC, TLTYPE_STATIC, toString(), OutputDevice::writeAttr(), and writeSUMOTime().
Referenced by writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_SUMO.h
NWWriter_SUMO.cpp