SUMO - Simulation of Urban MObility: MSLane Class Reference
MSLane Class Reference
Representation of a lane in the micro simulation.
#include <MSLane.h>
Data Structures
class by_connections_to_sorter
class edge_finder
struct IncomingLaneInfo
class vehicle_position_sorter
Sorts vehicles by their position (descending).
struct VehPosition
Public Types
typedef std::deque< MSVehicle * > VehCont
Container for vehicles.
Public Member Functions
void addApproachingLane (MSLane *lane)
void addIncomingLane (MSLane *lane, MSLink *viaLink)
bool allowsVehicleClass (SUMOVehicleClass vclass) const
virtual bool appropriate (const MSVehicle *veh)
virtual GUILaneWrapper * buildLaneWrapper (unsigned int index)
virtual void detectCollisions (SUMOTime timestep)
Check if vehicles are too close.
bool empty () const
Returns true if there is not a single vehicle on the lane.
void enteredByLaneChange (MSVehicle *v)
MSEdge & getEdge () const
Returns the lane's edge.
virtual const MSVehicle * getFirstVehicle () const
std::pair< MSVehicle *const,
SUMOReal > getFollowerOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal leaderSpeed, SUMOReal backOffset, SUMOReal predMaxDecel) const
const std::string & getID () const
Returns the id.
const std::vector
< IncomingLaneInfo > & getIncomingLanes () const
virtual MSVehicle * getLastVehicle () const
returns the last vehicle
std::pair< MSVehicle *const,
SUMOReal > getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle &veh, const std::vector< MSLane * > &bestLaneConts) const
Returns the leader and the distance to him.
MSLane * getLeftLane () const
const MSLinkCont & getLinkCont () const
returns the container with all links !!!
MSLane * getLogicalPredecessorLane () const
MSLane * getRightLane () const
bool isApproachedFrom (MSEdge *const edge, MSLane *const lane)
bool isApproachedFrom (MSEdge *const edge)
bool isLinkEnd (MSLinkCont::iterator &i)
bool isLinkEnd (MSLinkCont::const_iterator &i) const
void leftByLaneChange (MSVehicle *v)
MSLane (const std::string &id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, unsigned int numericalID, const PositionVector &shape, SUMOReal width, const SUMOVehicleClasses &allowed, const SUMOVehicleClasses &disallowed, double slope=0)
Constructor.
virtual MSVehicle * removeVehicle (MSVehicle *remVehicle)
void setAllowedClasses (const SUMOVehicleClasses &classes)
void setID (const std::string &newID)
resets the id
void setLength (SUMOReal val)
void setMaxSpeed (SUMOReal val)
void setNotAllowedClasses (const SUMOVehicleClasses &classes)
virtual MSLinkCont::const_iterator succLinkSec (const SUMOVehicle &veh, unsigned int nRouteSuccs, const MSLane &succLinkSource, const std::vector< MSLane * > &conts) const
virtual ~MSLane ()
Destructor.
Additional initialisation
void addLink (MSLink *link)
Delayed initialization.
void initialize (MSLinkCont *succs)
Delayed initialization (deprecated).
interaction with MSMoveReminder
virtual void addMoveReminder (MSMoveReminder *rem)
Add a move-reminder to move-reminder container.
const std::vector
< MSMoveReminder * > & getMoveReminders () const
Return the list of this lane's move reminders.
double getMySlope () const
void setMySlope (double mySlope)
Vehicle insertion
void forceVehicleInsertion (MSVehicle *veh, SUMOReal pos)
Inserts the given vehicle at the given position.
bool freeInsertion (MSVehicle &veh, SUMOReal speed, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
bool insertVehicle (MSVehicle &v)
Tries to insert the given vehicle.
virtual bool isInsertionSuccess (MSVehicle *vehicle, SUMOReal speed, SUMOReal pos, bool recheckNextLanes, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle with the given state (speed and pos).
bool maxSpeedGapInsertion (MSVehicle &veh, SUMOReal mspeed)
bool pWagGenericInsertion (MSVehicle &veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
bool pWagSimpleInsertion (MSVehicle &veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
Atomar value getter
const SUMOVehicleClasses & getAllowedClasses () const
Returns vehicle classes explicitly allowed on this lane.
SUMOReal getLength () const
Returns the lane's length.
SUMOReal getMaxSpeed () const
Returns the lane's maximum speed.
const SUMOVehicleClasses & getNotAllowedClasses () const
Returns vehicle classes explicitly disallowed on this lane.
size_t getNumericalID () const
Returns this lane's numerical id.
const PositionVector & getShape () const
Returns this lane's shape.
SUMOReal getWidth () const
Returns the lane's width.
Current state retrieval
SUMOReal getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
SUMOReal getHBEFA_CO2Emissions () const
Returns the sum of last step CO2 emissions.
SUMOReal getHBEFA_COEmissions () const
Returns the sum of last step CO emissions.
SUMOReal getHBEFA_FuelConsumption () const
Returns the sum of last step fuel consumption.
SUMOReal getHBEFA_HCEmissions () const
Returns the sum of last step HC emissions.
SUMOReal getHBEFA_NOxEmissions () const
Returns the sum of last step NOx emissions.
SUMOReal getHBEFA_PMxEmissions () const
Returns the sum of last step PMx emissions.
SUMOReal getMeanSpeed () const
Returns the mean speed on this lane.
SUMOReal getOccupancy () const
Returns the occupancy of this lane during the last step.
SUMOReal getVehLenSum () const
Returns the sum of lengths of vehicles which were on the lane during the last step.
Handling vehicles lapping into lanes
std::pair< MSVehicle *, SUMOReal > getLastVehicleInformation () const
Returns the last vehicle which is still on the lane.
MSVehicle * getPartialOccupator () const
Returns the vehicle which laps into this lane.
SUMOReal getPartialOccupatorEnd () const
Returns the position of the in-lapping vehicle's end.
void resetPartialOccupation (MSVehicle *v)
Removes the information about a vehicle lapping into this lane.
SUMOReal setPartialOccupation (MSVehicle *v, SUMOReal leftVehicleLength)
Sets the information about a vehicle lapping into this lane.
Access to vehicles
unsigned int getVehicleNumber () const
Returns the number of vehicles on this lane.
virtual const std::deque
< MSVehicle * > & getVehiclesSecure () const
Returns the vehicles container; locks it for microsimulation.
virtual void releaseVehicles () const
Allows to use the container for microsimulation again.
Vehicle movement (longitudinal)
virtual bool integrateNewVehicle (SUMOTime t)
Insert buffered vehicle into the real lane.
virtual bool moveCritical (SUMOTime t)
virtual bool setCritical (SUMOTime t, std::vector< MSLane * > &into)
Static Public Member Functions
static void clear ()
static MSLane * dictionary (std::string id)
Returns the MSLane associated to the key id if exists Otherwise returns 0.
static bool dictionary (std::string id, MSLane *lane)
Inserts a MSLane into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
static size_t dictSize ()
static void insertIDs (std::vector< std::string > &into)
Data Fields
PositionVector myShape
The shape of the lane.
Protected Types
typedef std::map< std::string,
MSLane * > DictType
definition of the tatic dictionary type
Protected Member Functions
virtual void incorporateVehicle (MSVehicle *veh, SUMOReal pos, SUMOReal speed, const MSLane::VehCont::iterator &at, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Inserts the vehicle into this lane, and informs it about entering the network.
virtual void swapAfterLaneChange (SUMOTime t)
moves myTmpVehicles int myVehicles after a lane change procedure
Protected Attributes
SUMOVehicleClasses myAllowedClasses
The list of allowed vehicle classes.
std::map< MSEdge
*, std::vector< MSLane * > > myApproachingLanes
SUMOReal myBackDistance
MSEdge * myEdge
The lane's edge, for routing only.
std::string myID
The name of the object.
std::vector< IncomingLaneInfo > myIncomingLanes
MSVehicle * myInlappingVehicle
The vehicle which laps into this lane.
SUMOReal myInlappingVehicleEnd
End position of a vehicle which laps into this lane.
SUMOReal myLeftVehLength
Not yet seen vehicle lengths.
SUMOReal myLength
Lane length [m].
MSLinkCont myLinks
MSLane * myLogicalPredecessorLane
SUMOReal myMaxSpeed
Lane-wide speedlimit [m/s].
SUMOVehicleClasses myNotAllowedClasses
The list of disallowed vehicle classes.
size_t myNumericalID
Unique numerical ID (set on reading by netload).
VehCont myTmpVehicles
std::vector< MSVehicle * > myVehBuffer
SUMOReal myVehicleLengthSum
The current length of all vehicles on this lane.
VehCont myVehicles
The lane's vehicles. The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
SUMOReal myWidth
Lane width [m].
Static Protected Attributes
static DictType myDict
Static dictionary to associate string-ids with objects.
Private Member Functions
MSLane (const MSLane &)
invalidated copy constructor
MSLane & operator= (const MSLane &)
invalidated assignment operator
Private Attributes
std::vector< MSMoveReminder * > myMoveReminders
double mySlope
This lane's move reminder.
Friends
class GUILaneWrapper
class MSLaneChanger
needs access to myTmpVehicles (this maybe should be done via SUMOReal-buffering!!!)
class MSXMLRawOut
Detailed Description
Representation of a lane in the micro simulation.
Class which represents a single lane. Somekind of the main class of the simulation. Allows moving vehicles.
Definition at line 78 of file MSLane.h.
Member Typedef Documentation
typedef std::map< std::string, MSLane* > MSLane::DictType [protected]
definition of the tatic dictionary type
Definition at line 715 of file MSLane.h.
typedef std::deque< MSVehicle* > MSLane::VehCont
Container for vehicles.
Definition at line 453 of file MSLane.h.
Constructor & Destructor Documentation
MSLane::MSLane (const std::string & id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, unsigned int numericalID, const PositionVector & shape, SUMOReal width, const SUMOVehicleClasses & allowed, const SUMOVehicleClasses & disallowed, double slope = 0)
Constructor.
Parameters:
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] edge The edge this lane belongs to
[in] numericalID The numerical id of the lane
[in] shape The shape of the lane
[in] width The width of the lane
[in] allowed Vehicle classes that explicitly may drive on this lane
[in] disallowed Vehicle classes that are explicitly forbidden on this lane
See also:
SUMOVehicleClass
Definition at line 79 of file MSLane.cpp.
MSLane::~MSLane () [virtual]
Destructor.
Definition at line 92 of file MSLane.cpp.
References myLinks.
MSLane::MSLane (const MSLane &) [private]
invalidated copy constructor
Member Function Documentation
void MSLane::addApproachingLane (MSLane * lane)
Definition at line 1020 of file MSLane.cpp.
References getEdge(), and myApproachingLanes.
Referenced by NLHandler::addConnection(), and NLSucceedingLaneBuilder::addSuccLane().
void MSLane::addIncomingLane (MSLane * lane, MSLink * viaLink)
Definition at line 1010 of file MSLane.cpp.
References getLength(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, myIncomingLanes, and MSLane::IncomingLaneInfo::viaLink.
Referenced by NLHandler::addConnection(), and NLSucceedingLaneBuilder::addSuccLane().
void MSLane::addLink (MSLink * link)
Delayed initialization.
Not all lane-members are known at the time the lane is born, above all the pointers to other lanes, so we have to add them later.
Parameters:
[in] link An outgoing link
Definition at line 107 of file MSLane.cpp.
References myLinks.
Referenced by NLHandler::addConnection().
void MSLane::addMoveReminder (MSMoveReminder * rem) [virtual]
Add a move-reminder to move-reminder container.
The move reminder will not be deleted by the lane.
Parameters:
[in] rem The move reminder to add
Definition at line 114 of file MSLane.cpp.
References myMoveReminders, and myVehicles.
Referenced by MSMoveReminder::MSMoveReminder().
bool MSLane::allowsVehicleClass (SUMOVehicleClass vclass) const
Definition at line 989 of file MSLane.cpp.
References myAllowedClasses, myNotAllowedClasses, and SVC_UNKNOWN.
bool MSLane::appropriate (const MSVehicle * veh) [virtual]
Returns the information whether this lane may be used to continue the current route
Definition at line 822 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSVehicle::getBestLanesContinuation(), MSEdge::getPurpose(), myEdge, myLinks, and succLinkSec().
GUILaneWrapper * MSLane::buildLaneWrapper (unsigned int index) [virtual]
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 957 of file MSLane.cpp.
void MSLane::clear () [static]
Clears the dictionary
Definition at line 805 of file MSLane.cpp.
References myDict.
Referenced by MSNet::clearAll().
void MSLane::detectCollisions (SUMOTime timestep) [virtual]
Check if vehicles are too close.
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 681 of file MSLane.cpp.
References MSVehicleTransfer::addVeh(), Named::getID(), MSBaseVehicle::getID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), myVehicleLengthSum, myVehicles, SUMOReal, time2string(), and WRITE_WARNING.
MSLane * MSLane::dictionary (std::string id) [static]
Returns the MSLane associated to the key id if exists Otherwise returns 0.
Definition at line 794 of file MSLane.cpp.
References myDict.
bool MSLane::dictionary (std::string id, MSLane * lane) [static]
Inserts a MSLane into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Definition at line 782 of file MSLane.cpp.
References myDict.
Referenced by NLHandler::addConnection(), NLHandler::addLane(), NLHandler::addPOI(), MSVehicle::addStop(), MSRouteHandler::addStop(), NLSucceedingLaneBuilder::addSuccLane(), NLSucceedingLaneBuilder::closeSuccLane(), MSDevice_Tripinfo::generateOutput(), NLTriggerBuilder::getLane(), NLDetectorBuilder::getLaneChecking(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLHandler::parseLanes(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_Lane::processSet().
static size_t MSLane::dictSize () [inline, static]
Definition at line 446 of file MSLane.h.
References myDict.
bool MSLane::empty () const [inline]
Returns true if there is not a single vehicle on the lane.
Definition at line 413 of file MSLane.h.
References myVehBuffer, and myVehicles.
void MSLane::enteredByLaneChange (MSVehicle * v)
Definition at line 1201 of file MSLane.cpp.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), and myVehicleLengthSum.
void MSLane::forceVehicleInsertion (MSVehicle * veh, SUMOReal pos)
Inserts the given vehicle at the given position.
No checks are done, vehicle insertion using this method may generate collisions (possibly delayed).
Parameters:
[in] veh The vehicle to insert
[in] pos The position at which the vehicle shall be inserted
Definition at line 603 of file MSLane.cpp.
References MSVehicle::getSpeed(), incorporateVehicle(), and myVehicles.
Referenced by TraCIServerAPI_Vehicle::processSet().
bool MSLane::freeInsertion (MSVehicle & veh, SUMOReal speed, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
Parameters:
[in] veh The vehicle to insert
[in] speed The maximum insertion speed
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns:
Whether the vehicle could be inserted
Definition at line 271 of file MSLane.cpp.
References MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), getPartialOccupator(), getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), isInsertionSuccess(), MIN2(), myVehicles, POSITION_EPS, and SUMOReal.
Referenced by MSVehicleTransfer::checkInsertions(), and insertVehicle().
const SUMOVehicleClasses& MSLane::getAllowedClasses () const [inline]
Returns vehicle classes explicitly allowed on this lane.
Returns:
This lane's allowed vehicle classes
Definition at line 361 of file MSLane.h.
References myAllowedClasses.
Referenced by GUILaneWrapper::getColorValue(), and TraCIServerAPI_Lane::processGet().
MSEdge& MSLane::getEdge () const [inline]
Returns the lane's edge.
Returns:
This lane's edge
Definition at line 430 of file MSLane.h.
References myEdge.
Referenced by addApproachingLane(), MSVehicle::addStop(), NLDetectorBuilder::buildInductLoop(), MSEdge::closeBuilding(), GUILaneWrapper::drawGL(), MSVehicle::enterLaneAtMove(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), GUILaneWrapper::getColorValue(), GUILaneWrapper::getEdgeLaneNumber(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), getLogicalPredecessorLane(), MSVehicle::moveChecked(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSLane::edge_finder::operator()(), MSLCM_DK2004::patchSpeed(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Lane::processSet(), setCritical(), and MSVehicle::writeSyntheticData().
const MSVehicle * MSLane::getFirstVehicle () const [virtual]
Definition at line 867 of file MSLane.cpp.
References myVehicles.
Referenced by getFollowerOnConsecutive().
std::pair< MSVehicle *const, SUMOReal > MSLane::getFollowerOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal leaderSpeed, SUMOReal backOffset, SUMOReal predMaxDecel) const
Definition at line 1054 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), getFirstVehicle(), getIncomingLanes(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, MSCFModel::maxNextSpeed(), myIncomingLanes, SUMOReal, and MSLane::IncomingLaneInfo::viaLink.
Referenced by isInsertionSuccess().
SUMOReal MSLane::getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
Returns:
noise emissions of vehicles on this lane during the last step
Definition at line 1308 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), HelpersHarmonoise::sum(), and SUMOReal.
Referenced by GUILaneWrapper::getColorValue(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_CO2Emissions () const
Returns the sum of last step CO2 emissions.
Returns:
CO2 emissions of vehicles on this lane during the last step
Definition at line 1236 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_CO2Emissions(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_COEmissions () const
Returns the sum of last step CO emissions.
Returns:
CO emissions of vehicles on this lane during the last step
Definition at line 1248 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_COEmissions(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_FuelConsumption () const
Returns the sum of last step fuel consumption.
Returns:
fuel consumption of vehicles on this lane during the last step
Definition at line 1296 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_FuelConsumption(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_HCEmissions () const
Returns the sum of last step HC emissions.
Returns:
HC emissions of vehicles on this lane during the last step
Definition at line 1284 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_HCEmissions(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_NOxEmissions () const
Returns the sum of last step NOx emissions.
Returns:
NOx emissions of vehicles on this lane during the last step
Definition at line 1272 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_NOxEmissions(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getHBEFA_PMxEmissions () const
Returns the sum of last step PMx emissions.
Returns:
PMx emissions of vehicles on this lane during the last step
Definition at line 1260 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and SUMOReal.
Referenced by GUILaneWrapper::getNormedHBEFA_PMxEmissions(), and TraCIServerAPI_Lane::processGet().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const std::vector<IncomingLaneInfo>& MSLane::getIncomingLanes () const [inline]
Definition at line 518 of file MSLane.h.
References myIncomingLanes.
Referenced by MSVehicle::enterLaneAtLaneChange(), and getFollowerOnConsecutive().
MSVehicle * MSLane::getLastVehicle () const [virtual]
returns the last vehicle
Definition at line 858 of file MSLane.cpp.
References myVehicles.
Referenced by getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), and isInsertionSuccess().
std::pair< MSVehicle *, SUMOReal > MSLane::getLastVehicleInformation () const
Returns the last vehicle which is still on the lane.
The information about the last vehicle in this lane's que is returned. If there is no such vehicle, the information about the vehicle which laps into this lane is returned. If there is no such vehicle, the first returned member is 0.
Returns:
Information about the last vehicle and it's back position
Definition at line 631 of file MSLane.cpp.
References MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), myInlappingVehicle, myInlappingVehicleEnd, myVehicles, and SUMOReal.
std::pair< MSVehicle *const, SUMOReal > MSLane::getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle & veh, const std::vector< MSLane * > & bestLaneConts) const
Returns the leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the vehicle will pass it. If so, the subsequent lane is investigated. If a vehicle (leader) is found, it is returned, together with the length of the investigated lanes until this vehicle's end, including the already seen place (seen).
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Todo:
: There are some oddities:
what about crossing a link at red, or if a link is closed? Has a following vehicle to be regarded or not?
Parameters:
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The vehicle for which the information shall be computed
[in] bestLaneConts The lanes the vehicle will use in future
Returns:
Definition at line 1104 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), getLastVehicle(), getLength(), MSVehicleType::getLengthWithGap(), getMaxSpeed(), getPartialOccupator(), getPartialOccupatorEnd(), MSBaseVehicle::getVehicleType(), isLinkEnd(), LINKSTATE_TL_RED, succLinkSec(), and TIME2STEPS.
Referenced by MSCFModel_PWag2009::moveHelper(), pWagGenericInsertion(), and pWagSimpleInsertion().
MSLane * MSLane::getLeftLane () const
Definition at line 977 of file MSLane.cpp.
References MSEdge::leftLane(), and myEdge.
SUMOReal MSLane::getLength () const [inline]
Returns the lane's length.
Returns:
This lane's length
Definition at line 353 of file MSLane.h.
References myLength.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), NLHandler::addConnection(), addIncomingLane(), NLHandler::addPOI(), MSVehicle::addStop(), NLSucceedingLaneBuilder::addSuccLane(), MS_E2_ZS_CollectorOverLanes::buildCollector(), GUI_E2_ZS_CollectorOverLanes::buildCollector(), NLDetectorBuilder::buildInductLoop(), MS_E2_ZS_CollectorOverLanes::extendTo(), freeInsertion(), MSVehicle::getBestLanes(), TraCIDijkstraRouter< E >::getEffort(), TraCIServerAPI_Simulation::getLaneChecking(), getLeaderOnConsecutive(), getMaxSpeedRegardingNextLanes(), GUILaneWrapper::getNormedHBEFA_CO2Emissions(), GUILaneWrapper::getNormedHBEFA_COEmissions(), GUILaneWrapper::getNormedHBEFA_FuelConsumption(), GUILaneWrapper::getNormedHBEFA_HCEmissions(), GUILaneWrapper::getNormedHBEFA_NOxEmissions(), GUILaneWrapper::getNormedHBEFA_PMxEmissions(), GUILaneWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), MSVehicle::getSpaceTillLastStanding(), MSNet::EdgeWeightsProxi::getTravelTime(), MSActuatedTrafficLightLogic::init(), MS_E2_ZS_CollectorOverLanes::init(), insertVehicle(), isInsertionSuccess(), maxSpeedGapInsertion(), MSVehicle::moveChecked(), MSLink::opened(), NLTriggerBuilder::parseAndBuildBusStop(), TraCIServerAPI_Lane::processGet(), pWagGenericInsertion(), pWagSimpleInsertion(), MSVehicle::setBlinkerInformation(), setCritical(), MSLCM_DK2004::wantsChangeToLeft(), MSLCM_DK2004::wantsChangeToRight(), and MSVehicle::writeSyntheticData().
const MSLinkCont & MSLane::getLinkCont () const
returns the container with all links !!!
Definition at line 942 of file MSLane.cpp.
References myLinks.
Referenced by MSLinkContHelper::getConnectingLink(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), GUILaneWrapper::getLinkNumber(), MSRightOfWayJunction::postloadInit(), MSInternalJunction::postloadInit(), TraCIServerAPI_Lane::processGet(), GUILaneWrapper::ROWdrawAction_drawArrows(), GUILaneWrapper::ROWdrawAction_drawLane2LaneConnections(), GUILaneWrapper::ROWdrawAction_drawLinkRules(), and MSVehicle::setBlinkerInformation().
MSLane * MSLane::getLogicalPredecessorLane () const
Definition at line 1167 of file MSLane.cpp.
References getEdge(), MSEdge::getIncomingEdges(), myEdge, myIncomingLanes, and myLogicalPredecessorLane.
SUMOReal MSLane::getMaxSpeed () const [inline]
Returns the lane's maximum speed.
Returns:
This lane's maximum speed
Definition at line 345 of file MSLane.h.
References myMaxSpeed.
Referenced by MSVehicleTransfer::checkInsertions(), MSAbstractLaneChangeModel::congested(), MSCFModel_IDM::desiredSpeed(), GUILaneWrapper::getColorValue(), TraCIDijkstraRouter< E >::getEffort(), getLeaderOnConsecutive(), getMaxSpeedRegardingNextLanes(), GUILaneWrapper::getParameterWindow(), MSNet::EdgeWeightsProxi::getTravelTime(), GUILaneWrapper::GUILaneWrapper(), MSActuatedTrafficLightLogic::init(), insertVehicle(), MSCFModel::interactionGap(), isInsertionSuccess(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSVehicle::MSVehicle(), TraCIServerAPI_Lane::processGet(), MSVehicle::setBlinkerInformation(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
SUMOReal MSLane::getMeanSpeed () const
Returns the mean speed on this lane.
Returns:
The average speed of vehicles during the last step; default speed if no vehicle was on this lane
Definition at line 1220 of file MSLane.cpp.
References getVehiclesSecure(), myMaxSpeed, myVehicles, releaseVehicles(), and SUMOReal.
Referenced by TraCIServerAPI_Lane::processGet().
const std::vector< MSMoveReminder* >& MSLane::getMoveReminders () const [inline]
Return the list of this lane's move reminders.
Returns:
Previously added move reminder
Definition at line 165 of file MSLane.h.
References myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), and MSVehicle::enterLaneAtLaneChange().
double MSLane::getMySlope () const
Definition at line 123 of file MSLane.cpp.
References mySlope.
const SUMOVehicleClasses& MSLane::getNotAllowedClasses () const [inline]
Returns vehicle classes explicitly disallowed on this lane.
Returns:
This lane's disallowed vehicle classes
Definition at line 369 of file MSLane.h.
References myNotAllowedClasses.
Referenced by GUILaneWrapper::getColorValue(), and TraCIServerAPI_Lane::processGet().
size_t MSLane::getNumericalID () const [inline]
Returns this lane's numerical id.
Returns:
This lane's numerical id
Definition at line 329 of file MSLane.h.
References myNumericalID.
SUMOReal MSLane::getOccupancy () const
Returns the occupancy of this lane during the last step.
Returns:
The occupancy during the last step
Definition at line 1208 of file MSLane.cpp.
References myLength, and myVehicleLengthSum.
Referenced by GUILaneWrapper::getColorValue(), and TraCIServerAPI_Lane::processGet().
MSVehicle* MSLane::getPartialOccupator () const [inline]
Returns the vehicle which laps into this lane.
Returns:
The vehicle which laps into this lane, 0 if there is no such
Definition at line 267 of file MSLane.h.
References myInlappingVehicle.
Referenced by MSE2Collector::detectorUpdate(), freeInsertion(), getLeaderOnConsecutive(), MSLaneChanger::getRealLeader(), MSLaneChanger::getRealThisLeader(), isInsertionSuccess(), maxSpeedGapInsertion(), and MSE2Collector::by_vehicle_position_sorter::operator()().
SUMOReal MSLane::getPartialOccupatorEnd () const [inline]
Returns the position of the in-lapping vehicle's end.
Returns:
Information about how far the vehicle laps into this lane
Definition at line 275 of file MSLane.h.
References myInlappingVehicleEnd.
Referenced by MSE2Collector::detectorUpdate(), freeInsertion(), getLeaderOnConsecutive(), MSLaneChanger::getRealLeader(), MSLaneChanger::getRealThisLeader(), isInsertionSuccess(), and maxSpeedGapInsertion().
MSLane * MSLane::getRightLane () const
Definition at line 983 of file MSLane.cpp.
References myEdge, and MSEdge::rightLane().
const PositionVector& MSLane::getShape () const [inline]
Returns this lane's shape.
Returns:
This lane's shape
Definition at line 337 of file MSLane.h.
References myShape.
Referenced by NLHandler::addConnection(), NLHandler::addPOI(), NLSucceedingLaneBuilder::addSuccLane(), GUIE3Collector::MyWrapper::buildDefinition(), TraCIServerAPI_Simulation::commandPositionConversion(), GUIVehicle::drawGL(), MSVTypeProbe::execute(), MSVehicle::getAngle(), MSVehicle::getPosition(), GUIBusStop::GUIBusStop(), MSLane::by_connections_to_sorter::operator()(), TraCIServerAPI_Lane::processGet(), and GUILaneWrapper::ROWdrawAction_drawLane2LaneConnections().
unsigned int MSLane::getVehicleNumber () const [inline]
Returns the number of vehicles on this lane.
Returns:
The number of vehicles on this lane
Definition at line 299 of file MSLane.h.
References myVehicles.
Referenced by MSEdge::getFreeLane(), TraCIServerAPI_Lane::processGet(), and MSXMLRawOut::writeLane().
virtual const std::deque< MSVehicle* >& MSLane::getVehiclesSecure () const [inline, virtual]
Returns the vehicles container; locks it for microsimulation.
Please note that it is necessary to release the vehicles container afterwards using "releaseVehicles".
Returns:
The vehicles on this lane
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 310 of file MSLane.h.
References myVehicles.
Referenced by GUILaneWrapper::drawGL(), getHarmonoise_NoiseEmissions(), getHBEFA_CO2Emissions(), getHBEFA_COEmissions(), getHBEFA_FuelConsumption(), getHBEFA_HCEmissions(), getHBEFA_NOxEmissions(), getHBEFA_PMxEmissions(), getMeanSpeed(), MSVehicle::getSpaceTillLastStanding(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getVehLenSum () const
Returns the sum of lengths of vehicles which were on the lane during the last step.
Returns:
The sum of vehicle lengths of vehicles in the last step
Definition at line 1214 of file MSLane.cpp.
References myVehicleLengthSum.
SUMOReal MSLane::getWidth () const [inline]
Returns the lane's width.
Returns:
This lane's width
Definition at line 377 of file MSLane.h.
References myWidth.
Referenced by GUILaneWrapper::GUILaneWrapper(), TraCIServerAPI_Lane::processGet(), GUILaneWrapper::ROWdrawAction_drawLinkNo(), GUILaneWrapper::ROWdrawAction_drawLinkRules(), and GUILaneWrapper::ROWdrawAction_drawTLSLinkNo().
void MSLane::incorporateVehicle (MSVehicle * veh, SUMOReal pos, SUMOReal speed, const MSLane::VehCont::iterator & at, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) [protected, virtual]
Inserts the vehicle into this lane, and informs it about entering the network.
Calls the vehicles enterLaneAtInsertion function, updates statistics and modifies the active state as needed
Parameters:
[in] veh The vehicle to be incorporated
[in] pos The position of the vehicle
[in] speed The speed of the vehicle
[in] at
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 135 of file MSLane.cpp.
References MSVehicle::enterLaneAtInsertion(), MSNet::getEdgeControl(), MSNet::getInstance(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSEdgeControl::gotActive(), myVehicleLengthSum, and myVehicles.
Referenced by forceVehicleInsertion(), isInsertionSuccess(), maxSpeedGapInsertion(), pWagGenericInsertion(), and pWagSimpleInsertion().
void MSLane::initialize (MSLinkCont * succs)
Delayed initialization (deprecated).
Not all lane-members are known at the time the lane is born, above all the pointers to other lanes, so we have to initialize later.
Parameters:
[in] succs The list of (outgoing) links
Todo:
Why are succs not const?
Definition at line 100 of file MSLane.cpp.
References myLinks.
Referenced by NLSucceedingLaneBuilder::closeSuccLane().
void MSLane::insertIDs (std::vector< std::string > & into) [static]
Definition at line 814 of file MSLane.cpp.
References myDict.
Referenced by TraCIServerAPI_Lane::processGet().
bool MSLane::insertVehicle (MSVehicle & v)
Tries to insert the given vehicle.
The insertion position and speed are determined in dependence to the vehicle's departure definition, first.
Then, the vehicle is tried to be inserted into the lane using these values by a call to "isInsertionSuccess". The result of "isInsertionSuccess" is returned.
Parameters:
[in] v The vehicle to insert
Returns:
Whether the vehicle could be inserted
See also:
isInsertionSuccess
MSVehicle::getDepartureDefinition
MSVehicle::DepartArrivalDefinition
Definition at line 338 of file MSLane.cpp.
References DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_MAX_SPEED_GAP, DEPART_POS_PWAG_GENERIC, DEPART_POS_PWAG_SIMPLE, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_SPEED_DEFAULT, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, freeInsertion(), getLength(), MSVehicleType::getLengthWithGap(), getMaxSpeed(), MSBaseVehicle::getMaxSpeed(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), isInsertionSuccess(), maxSpeedGapInsertion(), MIN2(), myLength, POSITION_EPS, pWagGenericInsertion(), pWagSimpleInsertion(), RandHelper::rand(), and SUMOReal.
Referenced by MSEdge::insertVehicle().
bool MSLane::integrateNewVehicle (SUMOTime t) [virtual]
Insert buffered vehicle into the real lane.
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 832 of file MSLane.cpp.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), myVehBuffer, myVehicleLengthSum, and myVehicles.
bool MSLane::isApproachedFrom (MSEdge *const edge, MSLane *const lane)
Definition at line 1036 of file MSLane.cpp.
References myApproachingLanes.
bool MSLane::isApproachedFrom (MSEdge *const edge)
Definition at line 1030 of file MSLane.cpp.
References myApproachingLanes.
bool MSLane::isInsertionSuccess (MSVehicle * vehicle, SUMOReal speed, SUMOReal pos, bool recheckNextLanes, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) [virtual]
Tries to insert the given vehicle with the given state (speed and pos).
Checks whether the vehicle can be inserted at the given position with the given speed so that no collisions with leader/follower occur and the speed does not cause unexpected behaviour on consecutive lanes. Returns false if the vehicle can not be inserted.
If the insertion can take place, incorporateVehicleis called and true is returned.
Parameters:
[in] vehicle The vehicle to insert
[in] speed The speed with which it shall be inserted
[in] pos The position at which it shall be inserted
[in] recheckNextLanes Forces patching the speed for not being too fast on next lanes
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns:
Whether the vehicle could be inserted
See also:
MSVehicle::enterLaneAtInsertion
Definition at line 408 of file MSLane.cpp.
References MSRoute::begin(), MSCFModel::brakeGap(), MSCFModel::followSpeed(), MSCFModel::freeSpeed(), MSVehicle::gap(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), getFollowerOnConsecutive(), MSBaseVehicle::getID(), MSNet::getInstance(), getLastVehicle(), getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), getMaxSpeed(), getPartialOccupator(), getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), incorporateVehicle(), isLinkEnd(), LINKSTATE_TL_RED, MIN2(), myLength, myVehicles, SPEED2DIST, succLinkSec(), SUMOReal, TIME2STEPS, and WRITE_ERROR.
Referenced by MSVehicleTransfer::checkInsertions(), freeInsertion(), insertVehicle(), and maxSpeedGapInsertion().
bool MSLane::isLinkEnd (MSLinkCont::iterator & i)
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 852 of file MSLane.cpp.
References myLinks.
bool MSLane::isLinkEnd (MSLinkCont::const_iterator & i) const
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 846 of file MSLane.cpp.
References myLinks.
Referenced by getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), and isInsertionSuccess().
void MSLane::leftByLaneChange (MSVehicle * v)
Definition at line 1195 of file MSLane.cpp.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), and myVehicleLengthSum.
bool MSLane::maxSpeedGapInsertion (MSVehicle & veh, SUMOReal mspeed)
Definition at line 230 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getHeadwayTime(), getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), getPartialOccupator(), getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), incorporateVehicle(), isInsertionSuccess(), MIN2(), myLength, myVehicles, and SUMOReal.
Referenced by insertVehicle().
bool MSLane::moveCritical (SUMOTime t) [virtual]
Reimplemented in GUIInternalLane, GUILane, and MSInternalLane.
Definition at line 648 of file MSLane.cpp.
References MSVehicleTransfer::addVeh(), Named::getID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), myLeftVehLength, myLength, myVehicleLengthSum, myVehicles, time2string(), and WRITE_WARNING.
MSLane& MSLane::operator= (const MSLane &) [private]
invalidated assignment operator
bool MSLane::pWagGenericInsertion (MSVehicle & veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
Definition at line 152 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSCFModel::followSpeed(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), getLeaderOnConsecutive(), getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), incorporateVehicle(), myVehicles, and SUMOReal.
Referenced by insertVehicle().
bool MSLane::pWagSimpleInsertion (MSVehicle & veh, SUMOReal speed, SUMOReal maxPos, SUMOReal minPos)
Definition at line 198 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSCFModel::getHeadwayTime(), getLeaderOnConsecutive(), getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), incorporateVehicle(), myVehicles, and SUMOReal.
Referenced by insertVehicle().
virtual void MSLane::releaseVehicles () const [inline, virtual]
Allows to use the container for microsimulation again.
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 317 of file MSLane.h.
Referenced by GUILaneWrapper::drawGL(), getHarmonoise_NoiseEmissions(), getHBEFA_CO2Emissions(), getHBEFA_COEmissions(), getHBEFA_FuelConsumption(), getHBEFA_HCEmissions(), getHBEFA_NOxEmissions(), getHBEFA_PMxEmissions(), getMeanSpeed(), MSVehicle::getSpaceTillLastStanding(), and TraCIServerAPI_Lane::processGet().
MSVehicle * MSLane::removeVehicle (MSVehicle * remVehicle) [virtual]
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 963 of file MSLane.cpp.
References MSBaseVehicle::getID(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::leaveLane(), myVehicleLengthSum, myVehicles, and MSMoveReminder::NOTIFICATION_ARRIVED.
void MSLane::resetPartialOccupation (MSVehicle * v)
Removes the information about a vehicle lapping into this lane.
Parameters:
[in] v The vehicle which laps into this lane
Definition at line 622 of file MSLane.cpp.
References myInlappingVehicle, and myInlappingVehicleEnd.
Referenced by MSVehicle::moveChecked().
void MSLane::setAllowedClasses (const SUMOVehicleClasses & classes) [inline]
Definition at line 497 of file MSLane.h.
References myAllowedClasses.
Referenced by TraCIServerAPI_Lane::processSet().
bool MSLane::setCritical (SUMOTime t, std::vector< MSLane * > & into) [virtual]
Moves the critical vehicles This step is done after the responds have been set
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 727 of file MSLane.cpp.
References MSVehicleTransfer::addVeh(), MSVehicle::ends(), getEdge(), Named::getID(), MSBaseVehicle::getID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), MSVehicle::getLane(), getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSGlobals::gTimeToGridlock, MSVehicle::isParking(), MSEdge::isVaporizing(), MSVehicle::leaveLane(), MSVehicle::moveChecked(), myVehBuffer, myVehicleLengthSum, myVehicles, MSMoveReminder::NOTIFICATION_ARRIVED, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_VAPORIZED, MSVehicle::onRemovalFromNet(), MSVehicleControl::scheduleVehicleRemoval(), SPEED2DIST, SUMOReal, time2string(), MSVehicle::workOnMoveReminders(), and WRITE_WARNING.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSLane::setLength (SUMOReal val) [inline]
Definition at line 422 of file MSLane.h.
References myLength.
Referenced by TraCIServerAPI_Lane::processSet().
void MSLane::setMaxSpeed (SUMOReal val) [inline]
Definition at line 418 of file MSLane.h.
References myMaxSpeed.
Referenced by TraCIServerAPI_Lane::processSet().
void MSLane::setMySlope (double mySlope)
Definition at line 128 of file MSLane.cpp.
Referenced by NLHandler::addLane().
void MSLane::setNotAllowedClasses (const SUMOVehicleClasses & classes) [inline]
Definition at line 502 of file MSLane.h.
References myNotAllowedClasses.
Referenced by TraCIServerAPI_Lane::processSet().
SUMOReal MSLane::setPartialOccupation (MSVehicle * v, SUMOReal leftVehicleLength)
Sets the information about a vehicle lapping into this lane.
The given left length of vehicle which laps into this lane is used to determine the vehicle's end position in regard to this lane's length. This information is set into myInlappingVehicleState; additionally, the vehicle pointer is stored in myInlappingVehicle; Returns this lane's length for subtracting it from the left vehicle length.
Parameters:
[in] v The vehicle which laps into this lane
[in] leftVehicleLength The distance the vehicle laps into this lane
Returns:
This lane's length
Definition at line 610 of file MSLane.cpp.
References myInlappingVehicle, myInlappingVehicleEnd, and myLength.
MSLinkCont::const_iterator MSLane::succLinkSec (const SUMOVehicle & veh, unsigned int nRouteSuccs, const MSLane & succLinkSource, const std::vector< MSLane * > & conts) const [virtual]
Same as succLink, but does not throw any assertions when the succeeding link could not be found; Returns the myLinks.end() instead; Further, the number of edges to look forward may be given
Definition at line 876 of file MSLane.cpp.
References MSEdge::allowedLanes(), MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), myLinks, and SUMOVehicle::succEdge().
Referenced by appropriate(), getLeaderOnConsecutive(), MSLaneChanger::getRealThisLeader(), isInsertionSuccess(), and MSVehicle::setBlinkerInformation().
void MSLane::swapAfterLaneChange (SUMOTime t) [protected, virtual]
moves myTmpVehicles int myVehicles after a lane change procedure
Reimplemented in GUIInternalLane, and GUILane.
Definition at line 948 of file MSLane.cpp.
References myTmpVehicles, and myVehicles.
Friends And Related Function Documentation
friend class GUILaneWrapper [friend]
Definition at line 83 of file MSLane.h.
Referenced by GUILane::buildLaneWrapper(), and GUIInternalLane::buildLaneWrapper().
friend class MSLaneChanger [friend]
needs access to myTmpVehicles (this maybe should be done via SUMOReal-buffering!!!)
Definition at line 81 of file MSLane.h.
friend class MSXMLRawOut [friend]
Definition at line 85 of file MSLane.h.
Field Documentation
SUMOVehicleClasses MSLane::myAllowedClasses [protected]
The list of allowed vehicle classes.
Definition at line 684 of file MSLane.h.
Referenced by allowsVehicleClass(), getAllowedClasses(), and setAllowedClasses().
std::map<MSEdge*, std::vector<MSLane*> > MSLane::myApproachingLanes [protected]
Definition at line 710 of file MSLane.h.
Referenced by addApproachingLane(), and isApproachedFrom().
SUMOReal MSLane::myBackDistance [protected]
Definition at line 675 of file MSLane.h.
MSLane::DictType MSLane::myDict [static, protected]
Static dictionary to associate string-ids with objects.
Definition at line 718 of file MSLane.h.
Referenced by clear(), dictionary(), dictSize(), and insertIDs().
MSEdge* MSLane::myEdge [protected]
The lane's edge, for routing only.
Definition at line 665 of file MSLane.h.
Referenced by appropriate(), getEdge(), getLeftLane(), getLogicalPredecessorLane(), and getRightLane().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::vector<IncomingLaneInfo> MSLane::myIncomingLanes [protected]
Definition at line 689 of file MSLane.h.
Referenced by addIncomingLane(), getFollowerOnConsecutive(), getIncomingLanes(), and getLogicalPredecessorLane().
MSVehicle* MSLane::myInlappingVehicle [protected]
The vehicle which laps into this lane.
Definition at line 700 of file MSLane.h.
Referenced by getLastVehicleInformation(), getPartialOccupator(), resetPartialOccupation(), and setPartialOccupation().
SUMOReal MSLane::myInlappingVehicleEnd [protected]
End position of a vehicle which laps into this lane.
Definition at line 697 of file MSLane.h.
Referenced by getLastVehicleInformation(), getPartialOccupatorEnd(), resetPartialOccupation(), and setPartialOccupation().
SUMOReal MSLane::myLeftVehLength [protected]
Not yet seen vehicle lengths.
Definition at line 704 of file MSLane.h.
Referenced by moveCritical().
SUMOReal MSLane::myLength [protected]
Lane length [m].
Definition at line 659 of file MSLane.h.
Referenced by getLength(), getOccupancy(), insertVehicle(), isInsertionSuccess(), maxSpeedGapInsertion(), moveCritical(), setLength(), and setPartialOccupation().
MSLinkCont MSLane::myLinks [protected]
The lane's Links to it's succeeding lanes and the default right-of-way rule, i.e. blocked or not blocked.
Definition at line 708 of file MSLane.h.
Referenced by addLink(), appropriate(), getLinkCont(), initialize(), isLinkEnd(), succLinkSec(), and ~MSLane().
MSLane* MSLane::myLogicalPredecessorLane [mutable, protected]
Definition at line 690 of file MSLane.h.
Referenced by getLogicalPredecessorLane().
SUMOReal MSLane::myMaxSpeed [protected]
Lane-wide speedlimit [m/s].
Definition at line 668 of file MSLane.h.
Referenced by getMaxSpeed(), getMeanSpeed(), and setMaxSpeed().
std::vector< MSMoveReminder* > MSLane::myMoveReminders [private]
Definition at line 725 of file MSLane.h.
Referenced by addMoveReminder(), and getMoveReminders().
SUMOVehicleClasses MSLane::myNotAllowedClasses [protected]
The list of disallowed vehicle classes.
Definition at line 687 of file MSLane.h.
Referenced by allowsVehicleClass(), getNotAllowedClasses(), and setNotAllowedClasses().
size_t MSLane::myNumericalID [protected]
Unique numerical ID (set on reading by netload).
Definition at line 647 of file MSLane.h.
Referenced by getNumericalID().
PositionVector MSLane::myShape
The shape of the lane.
Definition at line 486 of file MSLane.h.
Referenced by GUILane::buildLaneWrapper(), GUIInternalLane::buildLaneWrapper(), and getShape().
double MSLane::mySlope [private]
This lane's move reminder.
Definition at line 724 of file MSLane.h.
Referenced by getMySlope().
VehCont MSLane::myTmpVehicles [protected]
Container for lane-changing vehicles. After completion of lane-change- process, the two containers will be swapped.
Definition at line 672 of file MSLane.h.
Referenced by swapAfterLaneChange().
std::vector<MSVehicle*> MSLane::myVehBuffer [protected]
Vehicle-buffer for vehicle that was put onto this lane by a junction. The buffer is necessary, because of competing push- and pop-operations on myVehicles during Junction::moveFirst()
Definition at line 681 of file MSLane.h.
Referenced by empty(), integrateNewVehicle(), setCritical(), and MSXMLRawOut::writeLane().
SUMOReal MSLane::myVehicleLengthSum [protected]
The current length of all vehicles on this lane.
Definition at line 694 of file MSLane.h.
Referenced by detectCollisions(), enteredByLaneChange(), getOccupancy(), getVehLenSum(), incorporateVehicle(), integrateNewVehicle(), leftByLaneChange(), moveCritical(), removeVehicle(), and setCritical().
VehCont MSLane::myVehicles [protected]
The lane's vehicles. The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
Definition at line 656 of file MSLane.h.
Referenced by addMoveReminder(), detectCollisions(), empty(), GUILaneWrapper::firstWaitingTime(), forceVehicleInsertion(), freeInsertion(), getFirstVehicle(), getLastVehicle(), getLastVehicleInformation(), getMeanSpeed(), getVehicleNumber(), getVehiclesSecure(), GUILane::getVehiclesSecure(), GUIInternalLane::getVehiclesSecure(), incorporateVehicle(), integrateNewVehicle(), isInsertionSuccess(), maxSpeedGapInsertion(), moveCritical(), MSInternalLane::moveCritical(), pWagGenericInsertion(), pWagSimpleInsertion(), removeVehicle(), setCritical(), swapAfterLaneChange(), and MSXMLRawOut::writeLane().
SUMOReal MSLane::myWidth [protected]
Lane width [m].
Definition at line 662 of file MSLane.h.
Referenced by getWidth().
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp