SUMO - Simulation of Urban MObility: EulerSpiral Class Reference
EulerSpiral Class Reference
#include <euler.h>
Public Member Functions
Point2D< double > compute_end_pt (double k0, double gamma, double L, bool bNormalized=false)
Point2D< double > compute_end_pt (double arclength, bool bNormalized=false)
double compute_error (double k0, double L)
void compute_es_params ()
Point2D< double > compute_es_point (EulerSpiralParams &es_params, double arclength, bool bNormalized=false)
void computeSpiral (std::vector< Point2D< double > > &spiral, double ds=0, int NPts=0)
EulerSpiral (Point2D< double > start_pt, double start_angle, double k0, double gamma, double L)
EulerSpiral (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle)
EulerSpiral ()
Point2D< double > get_fresnel_integral (double value)
void set_end_params (Point2D< double > end_pt, double end_angle)
void set_params (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle)
void set_start_params (Point2D< double > start_pt, double start_angle)
Data Fields
EulerSpiralParams params
std::vector< Point2D< double > > pts
Private Attributes
BiArc _bi_arc_estimate
Detailed Description
Definition at line 139 of file euler.h.
Constructor & Destructor Documentation
EulerSpiral::EulerSpiral () [inline]
Definition at line 148 of file euler.h.
EulerSpiral::EulerSpiral (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle) [inline]
Definition at line 151 of file euler.h.
References angle0To2Pi(), compute_es_params(), EulerSpiralParams::end_angle, EulerSpiralParams::end_pt, params, EulerSpiralParams::start_angle, and EulerSpiralParams::start_pt.
EulerSpiral::EulerSpiral (Point2D< double > start_pt, double start_angle, double k0, double gamma, double L) [inline]
Definition at line 164 of file euler.h.
References angle0To2Pi(), compute_end_pt(), compute_es_params(), EulerSpiralParams::end_angle, EulerSpiralParams::end_pt, params, EulerSpiralParams::start_angle, and EulerSpiralParams::start_pt.
Member Function Documentation
Point2D< double > EulerSpiral::compute_end_pt (double k0, double gamma, double L, bool bNormalized = false)
Definition at line 298 of file euler.cpp.
References CCW(), eGamma, eK, get_fresnel_integral(), Point2D< coord_type >::getX(), Point2D< coord_type >::getY(), M_PI, params, EulerSpiralParams::psi, Point2D< coord_type >::setX(), Point2D< coord_type >::setY(), EulerSpiralParams::start_angle, and EulerSpiralParams::start_pt.
Point2D< double > EulerSpiral::compute_end_pt (double arclength, bool bNormalized = false)
Definition at line 293 of file euler.cpp.
References EulerSpiralParams::gamma, EulerSpiralParams::K0, and params.
Referenced by compute_error(), compute_es_point(), computeSpiral(), and EulerSpiral().
double EulerSpiral::compute_error (double k0, double L) [inline]
Definition at line 356 of file euler.cpp.
References compute_end_pt(), euc_distance(), params, and EulerSpiralParams::turningAngle.
Referenced by compute_es_params().
void EulerSpiral::compute_es_params ()
Definition at line 186 of file euler.cpp.
References _bi_arc_estimate, angle0To2Pi(), BiArc::compute_biarc_params(), compute_error(), eError, EulerSpiralParams::end_angle, EulerSpiralParams::end_pt, EulerSpiralParams::error, euc_distance(), EulerSpiralParams::gamma, EulerSpiralParams::K0, BiArcParams::K1, EulerSpiralParams::K2, BiArcParams::K2, EulerSpiralParams::L, BiArcParams::L(), BiArcParams::L1, BiArcParams::L2, MAX_NUM_ITERATIONS, MIN2(), BiArc::params, params, EulerSpiralParams::psi, BiArc::set_end_params(), BiArc::set_start_params(), EulerSpiralParams::start_angle, EulerSpiralParams::start_pt, EulerSpiralParams::turningAngle, Point2D< coord_type >::x(), and Point2D< coord_type >::y().
Referenced by EulerSpiral().
Point2D< double > EulerSpiral::compute_es_point (EulerSpiralParams & es_params, double arclength, bool bNormalized = false)
Definition at line 287 of file euler.cpp.
References compute_end_pt(), EulerSpiralParams::gamma, EulerSpiralParams::K0, and params.
void EulerSpiral::computeSpiral (std::vector< Point2D< double > > & spiral, double ds = 0, int NPts = 0)
Definition at line 262 of file euler.cpp.
References compute_end_pt(), EulerSpiralParams::end_pt, EulerSpiralParams::L, params, and EulerSpiralParams::start_pt.
Referenced by NIImporter_OpenDrive::geomFromSpiral().
Point2D< double > EulerSpiral::get_fresnel_integral (double value)
Definition at line 380 of file euler.cpp.
References EPS, FPMIN, M_PI, MAXIT, Point2D< coord_type >::setX(), Point2D< coord_type >::setY(), sign, and XMIN.
Referenced by compute_end_pt().
void EulerSpiral::set_end_params (Point2D< double > end_pt, double end_angle) [inline]
Definition at line 181 of file euler.h.
References angle0To2Pi(), EulerSpiralParams::end_angle, EulerSpiralParams::end_pt, and params.
void EulerSpiral::set_params (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle) [inline]
Definition at line 187 of file euler.h.
References angle0To2Pi(), EulerSpiralParams::end_angle, EulerSpiralParams::end_pt, params, EulerSpiralParams::start_angle, and EulerSpiralParams::start_pt.
void EulerSpiral::set_start_params (Point2D< double > start_pt, double start_angle) [inline]
Definition at line 175 of file euler.h.
References angle0To2Pi(), params, EulerSpiralParams::start_angle, and EulerSpiralParams::start_pt.
Field Documentation
BiArc EulerSpiral::_bi_arc_estimate [private]
Definition at line 142 of file euler.h.
Referenced by compute_es_params().
EulerSpiralParams EulerSpiral::params
Definition at line 145 of file euler.h.
Referenced by compute_end_pt(), compute_error(), compute_es_params(), compute_es_point(), computeSpiral(), EulerSpiral(), set_end_params(), set_params(), and set_start_params().
std::vector<Point2D<double> > EulerSpiral::pts
Definition at line 146 of file euler.h.
The documentation for this class was generated from the following files:
euler.h
euler.cpp