SUMO - Simulation of Urban MObility: MSPerson::MSPersonStage_Waiting Class Reference
MSPerson::MSPersonStage_Waiting Class Reference
#include <MSPerson.h>
Public Member Functions
const MSEdge & getDestination () const
returns the destination edge
virtual bool isWaitingFor (const std::string &line) const
Whether the person waits for a vehicle of the line specified.
MSPersonStage_Waiting (const MSEdge &destination, SUMOTime duration, SUMOTime until)
constructor
virtual void proceed (MSNet *net, MSPerson *person, SUMOTime now, const MSEdge &previousEdge)
proceeds to the next step
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
~MSPersonStage_Waiting ()
destructor
Protected Attributes
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach (either by walking or driving)
Private Member Functions
MSPersonStage_Waiting (const MSPersonStage_Waiting &)
Invalidated copy constructor.
MSPersonStage_Waiting & operator= (const MSPersonStage_Waiting &)
Invalidated assignment operator.
Private Attributes
SUMOTime myWaitingDuration
the time the person is waiting
SUMOTime myWaitingUntil
the time until the person is waiting
Detailed Description
A "real" stage performing a waiting over the specified time
Definition at line 194 of file MSPerson.h.
Constructor & Destructor Documentation
MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting (const MSEdge & destination, SUMOTime duration, SUMOTime until)
constructor
Definition at line 168 of file MSPerson.cpp.
MSPerson::MSPersonStage_Waiting::~MSPersonStage_Waiting ()
destructor
Definition at line 173 of file MSPerson.cpp.
MSPerson::MSPersonStage_Waiting::MSPersonStage_Waiting (const MSPersonStage_Waiting &) [private]
Invalidated copy constructor.
Member Function Documentation
const MSEdge & MSPerson::MSPersonStage::getDestination () const [inherited]
returns the destination edge
Definition at line 64 of file MSPerson.cpp.
References MSPerson::MSPersonStage::myDestination.
bool MSPerson::MSPersonStage::isWaitingFor (const std::string & line) const [virtual, inherited]
Whether the person waits for a vehicle of the line specified.
Reimplemented in MSPerson::MSPersonStage_Driving.
Definition at line 84 of file MSPerson.cpp.
MSPersonStage_Waiting& MSPerson::MSPersonStage_Waiting::operator= (const MSPersonStage_Waiting &) [private]
Invalidated assignment operator.
void MSPerson::MSPersonStage_Waiting::proceed (MSNet * net, MSPerson * person, SUMOTime now, const MSEdge & previousEdge) [virtual]
proceeds to the next step
Implements MSPerson::MSPersonStage.
Definition at line 177 of file MSPerson.cpp.
References MSNet::getPersonControl(), MAX3(), myWaitingDuration, myWaitingUntil, and MSPersonControl::setArrival().
void MSPerson::MSPersonStage::setArrived (SUMOTime now) [inherited]
logs end of the step
Definition at line 78 of file MSPerson.cpp.
References MSPerson::MSPersonStage::myArrived.
void MSPerson::MSPersonStage::setDeparted (SUMOTime now) [inherited]
logs end of the step
Definition at line 70 of file MSPerson.cpp.
References MSPerson::MSPersonStage::myDeparted.
void MSPerson::MSPersonStage_Waiting::tripInfoOutput (OutputDevice & os) const [virtual]
Called on writing tripinfo output.
Parameters:
[in] os The stream to write the information into
Exceptions:
IOError not yet implemented
Implements MSPerson::MSPersonStage.
Definition at line 186 of file MSPerson.cpp.
References MSPerson::MSPersonStage::myArrived, OutputDevice::openTag(), and time2string().
Field Documentation
SUMOTime MSPerson::MSPersonStage::myArrived [protected, inherited]
the time at which this stage ended
Definition at line 105 of file MSPerson.h.
Referenced by MSPerson::MSPersonStage::setArrived(), tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), and MSPerson::MSPersonStage_Walking::tripInfoOutput().
SUMOTime MSPerson::MSPersonStage::myDeparted [protected, inherited]
the time at which this stage started
Definition at line 102 of file MSPerson.h.
Referenced by MSPerson::MSPersonStage::setDeparted(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
const MSEdge& MSPerson::MSPersonStage::myDestination [protected, inherited]
the next edge to reach (either by walking or driving)
Definition at line 99 of file MSPerson.h.
Referenced by MSPerson::MSPersonStage::getDestination().
SUMOTime MSPerson::MSPersonStage_Waiting::myWaitingDuration [private]
the time the person is waiting
Definition at line 214 of file MSPerson.h.
Referenced by proceed().
SUMOTime MSPerson::MSPersonStage_Waiting::myWaitingUntil [private]
the time until the person is waiting
Definition at line 217 of file MSPerson.h.
Referenced by proceed().
The documentation for this class was generated from the following files:
MSPerson.h
MSPerson.cpp