SUMO - Simulation of Urban MObility: GUIInductLoop Class Reference
GUIInductLoop Class Reference
The gui-version of the MSInductLoop.
#include <GUIInductLoop.h>
Data Structures
class MyWrapper
A MSInductLoop-visualiser.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Returns this detector's visualisation-wrapper.
std::vector< VehicleData > collectVehiclesOnDet (SUMOTime t) const
Returns vehicle data for vehicles that have been on the detector starting at the given time.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getPosition () const
Returns the position of the detector on the lane.
GUIInductLoop (const std::string &id, MSLane *const lane, SUMOReal position, bool splitByType)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void reset ()
Resets all generated values to allow computation of next interval.
void setID (const std::string &newID)
resets the id
~GUIInductLoop ()
Destructor.
Virtual methods to implement by derived classes
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values).
Methods returning current values
SUMOReal getCurrentLength () const
Returns the length of the vehicle on the detector.
SUMOReal getCurrentOccupancy () const
Returns the current occupancy.
unsigned int getCurrentPassedNumber () const
Returns the number of vehicles that have passed the detector.
SUMOReal getCurrentSpeed () const
Returns the speed of the vehicle on the detector.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the ids of vehicles that have passed the detector.
SUMOReal getTimestepsSinceLastDetection () const
Returns the time since the last vehicle left the detector.
Methods inherited from MSMoveReminder
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Returns whether the detector may has to be concerned during the vehicle's further movement.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Dismisses the vehicle if it is on the detector due to a lane change.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
Methods inherited from MSDetectorFileOutput.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
Data Fields
MFXMutex myLock
Mutex preventing parallel read/write access to internal MSInductLoop state.
Protected Types
typedef std::deque< VehicleData > VehicleDataCont
Type of myVehicleDataCont.
typedef std::map< SUMOVehicle
*, SUMOReal > VehicleMap
Type of myVehiclesOnDet.
Protected Member Functions
void writeTypedXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime, const std::string &type, const VehicleDataCont &vdc, const VehicleMap &vm)
Methods that add and remove vehicles from internal container
void enterDetectorByMove (SUMOVehicle &veh, SUMOReal entryTimestep)
Introduces a vehicle to the detector's map myVehiclesOnDet.
void leaveDetectorByLaneChange (SUMOVehicle &veh)
Removes a vehicle from the detector's map myVehiclesOnDet.
void leaveDetectorByMove (SUMOVehicle &veh, SUMOReal leaveTimestep)
Processes a vehicle that leaves the detector.
Static Protected Member Functions
Function for summing up values
static SUMOReal lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::lengthM.
static SUMOReal speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::speedM.
Protected Attributes
unsigned myDismissedVehicleNumber
The number of dismissed vehicles.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myLastLeaveTime
Leave-time of the last vehicle detected [s].
SUMOReal myLastOccupancy
Occupancy by the last vehicle detected.
VehicleDataCont myLastVehicleDataCont
Data of vehicles that have completely passed the detector in the last time interval.
const SUMOReal myPosition
Detector's position on lane [m].
bool mySplitByType
Whether additional information split by vehicle classes shall be generated.
VehicleDataCont myVehicleDataCont
Data of vehicles that have completely passed the detector.
VehicleMap myVehiclesOnDet
Data for vehicles that have entered the detector (vehicle -> enter time).
Detailed Description
The gui-version of the MSInductLoop.
Allows the building of a wrapper (also declared herein) which draws the detector on the gl-canvas. Uses a mutex to avoid parallel read/write operations. The mutex is only set within methods that change MSInductLoop-internal state and within "collectVehiclesOnDet". All other reading operations should be performed via the simulation loop only.
Definition at line 61 of file GUIInductLoop.h.
Member Typedef Documentation
typedef std::deque< VehicleData > MSInductLoop::VehicleDataCont [protected, inherited]
Type of myVehicleDataCont.
Definition at line 356 of file MSInductLoop.h.
typedef std::map< SUMOVehicle*, SUMOReal > MSInductLoop::VehicleMap [protected, inherited]
Type of myVehiclesOnDet.
Definition at line 366 of file MSInductLoop.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
GUIInductLoop::GUIInductLoop (const std::string & id, MSLane *const lane, SUMOReal position, bool splitByType)
Constructor.
Parameters:
[in] id Unique id
[in] lane Lane where detector woks on
[in] position Position of the detector within the lane
[in] splitByType Whether additional information split by vehicle classes shall be generated
Definition at line 63 of file GUIInductLoop.cpp.
GUIInductLoop::~GUIInductLoop ()
Destructor.
Definition at line 68 of file GUIInductLoop.cpp.
Member Function Documentation
GUIDetectorWrapper * GUIInductLoop::buildDetectorGUIRepresentation () [virtual]
Returns this detector's visualisation-wrapper.
Returns:
The wrapper representing the detector
Reimplemented from MSDetectorFileOutput.
Definition at line 72 of file GUIInductLoop.cpp.
References MSMoveReminder::getLane(), and MSInductLoop::myPosition.
std::vector< MSInductLoop::VehicleData > GUIInductLoop::collectVehiclesOnDet (SUMOTime t) const [virtual]
Returns vehicle data for vehicles that have been on the detector starting at the given time.
This method uses a mutex to prevent parallel read/write access to the vehicle buffer
Parameters:
[in] t The time from which vehicles shall be counted
Returns:
The list of vehicles
See also:
MSInductLoop::collectVehiclesOnDet()
Reimplemented from MSInductLoop.
Definition at line 108 of file GUIInductLoop.cpp.
References MFXMutex::lock(), myLock, and MFXMutex::unlock().
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) [inline, virtual, inherited]
Updates the detector (computes values).
Parameters:
[in] step The current time step
Reimplemented in MSE2Collector, MSE3Collector, MSMeanData, and MSMeanData_Harmonoise.
Definition at line 113 of file MSDetectorFileOutput.h.
void GUIInductLoop::enterDetectorByMove (SUMOVehicle & veh, SUMOReal entryTimestep) [protected, virtual]
Introduces a vehicle to the detector's map myVehiclesOnDet.
Locks the internal mutex before calling MSInductLoop::enterDetectorByMove()
See also:
MSInductLoop::enterDetectorByMove()
Parameters:
veh The entering vehicle.
entryTimestep Timestep (not necessary integer) of entrance.
See also:
MSInductLoop::enterDetectorByMove()
Reimplemented from MSInductLoop.
Definition at line 86 of file GUIInductLoop.cpp.
References MFXMutex::lock(), myLock, and MFXMutex::unlock().
SUMOReal MSInductLoop::getCurrentLength () const [inherited]
Returns the length of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's length.
Returns:
The length [m] of the vehicle if one is on the detector, -1 otherwise
Definition at line 144 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), MSInductLoop::lengthSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentOccupancy () const [inherited]
Returns the current occupancy.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, its occupancy value is returned. If no vehicle has passed, 0 is returned.
Returns:
This detector's current occupancy
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 153 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getCurrentTimeStep(), MSNet::getInstance(), MAX2(), MIN2(), STEPS2TIME, SUMOReal, and TS.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
unsigned int MSInductLoop::getCurrentPassedNumber () const [inherited]
Returns the number of vehicles that have passed the detector.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, 1 is returned. If no vehicle has passed, 0 is returned.
Returns:
The number of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 170 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, and MSNet::getInstance().
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentSpeed () const [inherited]
Returns the speed of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's current speed.
Returns:
The speed [m/s] of the vehicle if one is on the detector, -1 otherwise
Definition at line 135 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), MSInductLoop::speedSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
std::vector< std::string > MSInductLoop::getCurrentVehicleIDs () const [inherited]
Returns the ids of vehicles that have passed the detector.
Returns:
The ids of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 177 of file MSInductLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, and MSNet::getInstance().
Referenced by TraCIServerAPI_InductionLoop::processGet().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
SUMOReal MSInductLoop::getPosition () const [inline, inherited]
Returns the position of the detector on the lane.
Returns:
The detector's position in meters
Definition at line 99 of file MSInductLoop.h.
References MSInductLoop::myPosition.
Referenced by TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getTimestepsSinceLastDetection () const [inherited]
Returns the time since the last vehicle left the detector.
Returns:
Timesteps from last leaving (detection) of the detector
Definition at line 188 of file MSInductLoop.cpp.
References MSNet::getInstance(), MSInductLoop::myLastLeaveTime, MSInductLoop::myVehiclesOnDet, and STEPS2TIME.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), and TraCIServerAPI_InductionLoop::processGet().
void GUIInductLoop::leaveDetectorByLaneChange (SUMOVehicle & veh) [protected, virtual]
Removes a vehicle from the detector's map myVehiclesOnDet.
Locks the internal mutex before calling MSInductLoop::leaveDetectorByLaneChange()
See also:
MSInductLoop::leaveDetectorByLaneChange()
Parameters:
veh The leaving vehicle.
Reimplemented from MSInductLoop.
Definition at line 100 of file GUIInductLoop.cpp.
References MFXMutex::lock(), myLock, and MFXMutex::unlock().
void GUIInductLoop::leaveDetectorByMove (SUMOVehicle & veh, SUMOReal leaveTimestep) [protected, virtual]
Processes a vehicle that leaves the detector.
Locks the internal mutex before calling MSInductLoop::leaveDetectorByMove()
See also:
MSInductLoop::leaveDetectorByMove()
Parameters:
veh The leaving vehicle.
leaveTimestep Timestep (not necessary integer) of leaving.
See also:
MSInductLoop::leaveDetectorByMove()
Reimplemented from MSInductLoop.
Definition at line 93 of file GUIInductLoop.cpp.
References MFXMutex::lock(), myLock, and MFXMutex::unlock().
static SUMOReal MSInductLoop::lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) [inline, static, protected, inherited]
Adds up VehicleData::lengthM.
Definition at line 332 of file MSInductLoop.h.
References MSInductLoop::VehicleData::lengthM.
Referenced by MSInductLoop::getCurrentLength(), and MSInductLoop::writeTypedXMLOutput().
bool MSInductLoop::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) [virtual, inherited]
Returns whether the detector may has to be concerned during the vehicle's further movement.
If the detector is in front of the vehicle, true is returned. If the vehicle's front has passed the detector, false, because the vehicle is no longer relevant for the detector.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
True if vehicle is on or in front of the detector.
See also:
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 124 of file MSInductLoop.cpp.
References MSVehicleType::getLengthWithGap(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), and MSInductLoop::myPosition.
bool MSInductLoop::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) [virtual, inherited]
Dismisses the vehicle if it is on the detector due to a lane change.
If the vehicle is on the detector, it will be dismissed by incrementing myDismissedVehicleNumber and removing this vehicle's entering time from myVehiclesOnDet.
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also:
leaveDetectorByLaneChange
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 113 of file MSInductLoop.cpp.
References MSInductLoop::leaveDetectorByLaneChange(), and MSMoveReminder::NOTIFICATION_JUNCTION.
bool MSInductLoop::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [virtual, inherited]
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
As soon a vehicle enters the detector, its entry time is computed and stored in myVehiclesOnDet via enterDetectorByMove. If it passes the detector, the according leaving time is computed and stored, too, using leaveDetectorByMove.
Parameters:
[in] veh Vehicle that asks this remider.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns:
True if vehicle hasn't passed the detector completely.
See also:
MSMoveReminder
MSMoveReminder::notifyMove
enterDetectorByMove
leaveDetectorByMove
Reimplemented from MSMoveReminder.
Definition at line 84 of file MSInductLoop.cpp.
References MSInductLoop::enterDetectorByMove(), MSNet::getInstance(), MSVehicleType::getLengthWithGap(), SUMOVehicle::getVehicleType(), MSInductLoop::leaveDetectorByMove(), MSInductLoop::myPosition, STEPS2TIME, and SUMOReal.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
void GUIInductLoop::reset () [virtual]
Resets all generated values to allow computation of next interval.
Locks the internal mutex before calling MSInductLoop::reset()
See also:
MSInductLoop::reset()
Reimplemented from MSInductLoop.
Definition at line 78 of file GUIInductLoop.cpp.
References MFXMutex::lock(), myLock, and MFXMutex::unlock().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
static SUMOReal MSInductLoop::speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) [inline, static, protected, inherited]
Adds up VehicleData::speedM.
Definition at line 327 of file MSInductLoop.h.
References MSInductLoop::VehicleData::speedM.
Referenced by MSInductLoop::getCurrentSpeed(), and MSInductLoop::writeTypedXMLOutput().
void MSInductLoop::writeTypedXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime, const std::string & type, const VehicleDataCont & vdc, const VehicleMap & vm) [protected, inherited]
Definition at line 237 of file MSInductLoop.cpp.
References StringUtils::escapeXML(), Named::getID(), MSInductLoop::lengthSum(), MAX2(), MIN2(), MSInductLoop::myDismissedVehicleNumber, MSInductLoop::speedSum(), STEPS2TIME, SUMOReal, and time2string().
Referenced by MSInductLoop::writeXMLOutput().
void MSInductLoop::writeXMLDetectorProlog (OutputDevice & dev) const [virtual, inherited]
Opens the XML-output using "detector" as root element.
Parameters:
[in] dev The output device to write the root into
See also:
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 198 of file MSInductLoop.cpp.
References OutputDevice::writeXMLHeader().
void MSInductLoop::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [virtual, inherited]
Writes collected values into the given stream.
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also:
MSDetectorFileOutput::writeXMLOutput
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 204 of file MSInductLoop.cpp.
References MSInductLoop::mySplitByType, MSInductLoop::myVehicleDataCont, MSInductLoop::myVehiclesOnDet, MSInductLoop::reset(), and MSInductLoop::writeTypedXMLOutput().
Field Documentation
unsigned MSInductLoop::myDismissedVehicleNumber [protected, inherited]
The number of dismissed vehicles.
Definition at line 352 of file MSInductLoop.h.
Referenced by MSInductLoop::leaveDetectorByLaneChange(), MSInductLoop::reset(), and MSInductLoop::writeTypedXMLOutput().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSInductLoop::myLastLeaveTime [protected, inherited]
Leave-time of the last vehicle detected [s].
Definition at line 346 of file MSInductLoop.h.
Referenced by MSInductLoop::getTimestepsSinceLastDetection(), MSInductLoop::leaveDetectorByMove(), and MSInductLoop::MSInductLoop().
SUMOReal MSInductLoop::myLastOccupancy [protected, inherited]
Occupancy by the last vehicle detected.
Definition at line 349 of file MSInductLoop.h.
Referenced by MSInductLoop::leaveDetectorByMove().
VehicleDataCont MSInductLoop::myLastVehicleDataCont [protected, inherited]
Data of vehicles that have completely passed the detector in the last time interval.
Definition at line 362 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), and MSInductLoop::reset().
MFXMutex GUIInductLoop::myLock [mutable]
Mutex preventing parallel read/write access to internal MSInductLoop state.
Definition at line 217 of file GUIInductLoop.h.
Referenced by collectVehiclesOnDet(), enterDetectorByMove(), leaveDetectorByLaneChange(), leaveDetectorByMove(), and reset().
const SUMOReal MSInductLoop::myPosition [protected, inherited]
Detector's position on lane [m].
Definition at line 340 of file MSInductLoop.h.
Referenced by buildDetectorGUIRepresentation(), MSInductLoop::getPosition(), MSInductLoop::MSInductLoop(), MSInductLoop::notifyEnter(), and MSInductLoop::notifyMove().
bool MSInductLoop::mySplitByType [protected, inherited]
Whether additional information split by vehicle classes shall be generated.
Definition at line 343 of file MSInductLoop.h.
Referenced by MSInductLoop::writeXMLOutput().
VehicleDataCont MSInductLoop::myVehicleDataCont [protected, inherited]
Data of vehicles that have completely passed the detector.
Definition at line 359 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSInductLoop::leaveDetectorByMove(), MSInductLoop::reset(), and MSInductLoop::writeXMLOutput().
VehicleMap MSInductLoop::myVehiclesOnDet [protected, inherited]
Data for vehicles that have entered the detector (vehicle -> enter time).
Definition at line 369 of file MSInductLoop.h.
Referenced by MSInductLoop::collectVehiclesOnDet(), MSInductLoop::enterDetectorByMove(), MSInductLoop::getTimestepsSinceLastDetection(), MSInductLoop::leaveDetectorByLaneChange(), MSInductLoop::leaveDetectorByMove(), and MSInductLoop::writeXMLOutput().
The documentation for this class was generated from the following files:
GUIInductLoop.h
GUIInductLoop.cpp