SUMO - Simulation of Urban MObility: AGFrame Class Reference
AGFrame Class Reference
Sets and checks options for ActivityGen.
#include <AGFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont singleton for being valid for usage within ActivityGen.
static void fillOptions ()
Inserts options used by ActivityGen into the OptionsCont singleton.
Detailed Description
Sets and checks options for ActivityGen.
Definition at line 44 of file AGFrame.h.
Member Function Documentation
bool AGFrame::checkOptions () [static]
Checks set options from the OptionsCont singleton for being valid for usage within ActivityGen.
Returns:
Whether all needed options are set
Todo:
Not implemented yet
Definition at line 109 of file AGFrame.cpp.
void AGFrame::fillOptions () [static]
Inserts options used by ActivityGen into the OptionsCont singleton.
Definition at line 51 of file AGFrame.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addCopyrightNotice(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), OptionsCont::getOptions(), RandHelper::insertRandOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), and VERSION_STRING.
Referenced by main().
The documentation for this class was generated from the following files:
AGFrame.h
AGFrame.cpp