SUMO - Simulation of Urban MObility: NBJunctionTypesMatrix Class Reference
NBJunctionTypesMatrix Class Reference
#include <NBJunctionTypesMatrix.h>
Data Structures
class range_finder
Public Member Functions
SumoXMLNodeType getType (SUMOReal speed1, SUMOReal speed2) const
NBJunctionTypesMatrix ()
~NBJunctionTypesMatrix ()
Private Types
typedef std::map< char,
SumoXMLNodeType > CharToVal
typedef std::vector< std::pair
< SUMOReal, SUMOReal > > RangeCont
typedef std::vector< std::string > StringCont
Private Member Functions
char getNameAt (size_t pos1, size_t pos2) const
Private Attributes
CharToVal myMap
RangeCont myRanges
StringCont myValues
Detailed Description
A class that stores the relationship between incoming edges and the junction type resulting from their types.
Definition at line 49 of file NBJunctionTypesMatrix.h.
Member Typedef Documentation
typedef std::map<char, SumoXMLNodeType> NBJunctionTypesMatrix::CharToVal [private]
a map of chars to ints
Definition at line 92 of file NBJunctionTypesMatrix.h.
typedef std::vector<std::pair<SUMOReal, SUMOReal> > NBJunctionTypesMatrix::RangeCont [private]
a container type for edge priority ranges
Definition at line 86 of file NBJunctionTypesMatrix.h.
typedef std::vector<std::string> NBJunctionTypesMatrix::StringCont [private]
A container type for the resulting junction types (cross matrix)
Definition at line 89 of file NBJunctionTypesMatrix.h.
Constructor & Destructor Documentation
NBJunctionTypesMatrix::NBJunctionTypesMatrix ()
constructor
Definition at line 49 of file NBJunctionTypesMatrix.cpp.
References myMap, myRanges, myValues, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY_JUNCTION, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, and SUMOReal.
NBJunctionTypesMatrix::~NBJunctionTypesMatrix ()
destructor
Definition at line 72 of file NBJunctionTypesMatrix.cpp.
Member Function Documentation
char NBJunctionTypesMatrix::getNameAt (size_t pos1, size_t pos2) const [private]
returns the one-char name of the junction type between the two given ranges
Definition at line 85 of file NBJunctionTypesMatrix.cpp.
References myValues.
Referenced by getType().
SumoXMLNodeType NBJunctionTypesMatrix::getType (SUMOReal speed1, SUMOReal speed2) const
returns the type of the junction on the crossing of edges of the given types
Definition at line 76 of file NBJunctionTypesMatrix.cpp.
References getNameAt(), myMap, and myRanges.
Referenced by NBTypeCont::getJunctionType().
Field Documentation
CharToVal NBJunctionTypesMatrix::myMap [private]
a map of chars to their NBNode-representation
Definition at line 106 of file NBJunctionTypesMatrix.h.
Referenced by getType(), and NBJunctionTypesMatrix().
RangeCont NBJunctionTypesMatrix::myRanges [private]
a container for edge priority ranges
Definition at line 95 of file NBJunctionTypesMatrix.h.
Referenced by getType(), and NBJunctionTypesMatrix().
StringCont NBJunctionTypesMatrix::myValues [private]
A container for the resulting junction types (cross matrix) The informations are stored as chars: 't': Traffic Light Junction 'r': Right-before-Left Junction 'p': Priority Junction 'x': no Junction
Definition at line 103 of file NBJunctionTypesMatrix.h.
Referenced by getNameAt(), and NBJunctionTypesMatrix().
The documentation for this class was generated from the following files:
NBJunctionTypesMatrix.h
NBJunctionTypesMatrix.cpp