SUMO - Simulation of Urban MObility: MSJunctionLogic Class Reference
MSJunctionLogic Class Reference
#include <MSJunctionLogic.h>
Public Member Functions
virtual const
MSLogicJunction::LinkFoes & getFoesFor (unsigned int linkIndex) const
Returns the foes of the given link.
virtual const std::bitset< 64 > & getInternalFoesFor (unsigned int linkIndex) const
virtual bool getIsCont (unsigned int linkIndex) const
unsigned int getLogicSize () const
virtual bool isCrossing () const
unsigned int nLinks ()
Returns the logic's number of links.
virtual ~MSJunctionLogic ()
Destructor.
Protected Member Functions
MSJunctionLogic (unsigned int nLinks)
Constructor.
Protected Attributes
unsigned int myNLinks
The logic's number of links.
Static Protected Attributes
static MSLogicJunction::LinkFoes myDummyFoes
A dummy foe container.
Private Member Functions
MSJunctionLogic (const MSJunctionLogic &)
Copy constructor.
MSJunctionLogic ()
Default constructor.
MSJunctionLogic & operator= (const MSJunctionLogic &)
Assignment operator.
Detailed Description
Definition at line 46 of file MSJunctionLogic.h.
Constructor & Destructor Documentation
MSJunctionLogic::~MSJunctionLogic () [virtual]
Destructor.
Definition at line 59 of file MSJunctionLogic.cpp.
MSJunctionLogic::MSJunctionLogic (unsigned int nLinks) [protected]
Constructor.
Definition at line 55 of file MSJunctionLogic.cpp.
MSJunctionLogic::MSJunctionLogic () [private]
Default constructor.
MSJunctionLogic::MSJunctionLogic (const MSJunctionLogic &) [private]
Copy constructor.
Member Function Documentation
virtual const MSLogicJunction::LinkFoes& MSJunctionLogic::getFoesFor (unsigned int linkIndex) const [inline, virtual]
Returns the foes of the given link.
Reimplemented in MSBitSetLogic< N >.
Definition at line 55 of file MSJunctionLogic.h.
References myDummyFoes, and UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
virtual const std::bitset<64>& MSJunctionLogic::getInternalFoesFor (unsigned int linkIndex) const [inline, virtual]
Reimplemented in MSBitSetLogic< N >.
Definition at line 60 of file MSJunctionLogic.h.
References myDummyFoes, and UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
virtual bool MSJunctionLogic::getIsCont (unsigned int linkIndex) const [inline, virtual]
Reimplemented in MSBitSetLogic< N >.
Definition at line 64 of file MSJunctionLogic.h.
References UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
unsigned int MSJunctionLogic::getLogicSize () const [inline]
Definition at line 70 of file MSJunctionLogic.h.
References myNLinks.
Referenced by MSRightOfWayJunction::postloadInit().
virtual bool MSJunctionLogic::isCrossing () const [inline, virtual]
Reimplemented in MSBitSetLogic< N >.
Definition at line 74 of file MSJunctionLogic.h.
Referenced by MSRightOfWayJunction::postloadInit().
unsigned int MSJunctionLogic::nLinks ()
Returns the logic's number of links.
Definition at line 50 of file MSJunctionLogic.cpp.
References myNLinks.
MSJunctionLogic& MSJunctionLogic::operator= (const MSJunctionLogic &) [private]
Assignment operator.
Field Documentation
MSLogicJunction::LinkFoes MSJunctionLogic::myDummyFoes [static, protected]
A dummy foe container.
Definition at line 89 of file MSJunctionLogic.h.
Referenced by getFoesFor(), and getInternalFoesFor().
unsigned int MSJunctionLogic::myNLinks [protected]
The logic's number of links.
Definition at line 86 of file MSJunctionLogic.h.
Referenced by getLogicSize(), and nLinks().
The documentation for this class was generated from the following files:
MSJunctionLogic.h
MSJunctionLogic.cpp