SUMO - Simulation of Urban MObility: MSVehicleType Class Reference
MSVehicleType Class Reference
The car-following model and parameter.
#include <MSVehicleType.h>
Public Member Functions
bool amVehicleSpecific () const
Returns whether this type belongs to a single vehicle only (was modified).
MSVehicleType (const std::string &id, double lengthWithGap, double minGap, double maxSpeed, double prob, double speedFactor, double speedDev, SUMOVehicleClass vclass, SUMOEmissionClass emissionClass, double guiWidth, SUMOVehicleShape shape, const std::string &lcModel, const RGBColor &c, double m, double r_res, double air_r, double frotal, double drag_c, double gear_r, double gear_s_e, double reg_rat, double motor_s_e, double coop_l, double iron_l, double windage_l, double constant_l, double power_a, double num_c, double capac, double time, double temp, double hum, std::string aux_m, std::string ligth_m, double vehicle_ligths, double fron_ligth, double cockpit_lights, double radio, double heating)
MSVehicleType (const std::string &id, double lengthWithGap, double minGap, double maxSpeed, double prob, double speedFactor, double speedDev, SUMOVehicleClass vclass, SUMOEmissionClass emissionClass, double guiWidth, SUMOVehicleShape shape, const std::string &lcModel, const RGBColor &c)
Constructor.
void saveState (std::ostream &os)
virtual ~MSVehicleType ()
Destructor.
Atomar getter for simulation
MSCFModel & getCarFollowModel ()
Returns the vehicle type's car following model definition (non-const version).
const MSCFModel & getCarFollowModel () const
Returns the vehicle type's car following model definition (const version).
const RGBColor & getColor () const
Returns this type's color.
double getDefaultProbability () const
Get the default probability of this vehicle type.
SUMOEmissionClass getEmissionClass () const
Get this vehicle type's emission class.
const std::string & getID () const
Returns the name of the vehicle type.
double getLength () const
Get vehicle's length [m].
double getLengthWithGap () const
Get vehicle's length including the minimum gap [m].
double getMaxSpeed () const
Get vehicle's maximum speed [m/s].
double getMaxSpeedWithDeviation (double referenceSpeed) const
Get vehicle's maximum speed [m/s] drawn from a normal distribution.
double getMinGap () const
Get the free space in front of vehicles of this class.
double getSpeedDeviation () const
Returns this type's speed deviation.
double getSpeedFactor () const
Returns this type's speed factor.
SUMOVehicleClass getVehicleClass () const
Get this vehicle type's vehicle class.
double hasSpeedDeviation () const
Get vehicle's maximum speed [m/s].
Atomar getter for visualization
SUMOVehicleShape getGuiShape () const
Get this vehicle type's shape.
double getGuiWidth () const
Get the width which vehicles of this class shall have when being drawn.
Setter methods
void setColor (const RGBColor &color)
Set a new value for this type's color.
void setDefaultProbability (const double &prob)
Set a new value for this type's default probability.
void setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
void setLength (const double &length)
Set a new value for this type's length.
void setMaxSpeed (const double &maxSpeed)
Set a new value for this type's maximum speed.
void setMinGap (const double &minGap)
Set a new value for this type's minimum gap.
void setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
void setSpeedDeviation (const double &dev)
Set a new value for this type's speed deviation.
void setSpeedFactor (const double &factor)
Set a new value for this type's speed factor.
void setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
void setWidth (const double &width)
Set a new value for this type's width.
Private Member Functions
MSVehicleType (const MSVehicleType &)
Invalidated copy constructor.
MSVehicleType & operator= (const MSVehicleType &)
Invalidated assignment operator.
Private Attributes
double air_dens
std::string aux_mask
double capacity
double celsius
double cockpit_ligths_consumption
double constant_losses
double cooper_losses
double drag_coefficient
double front_fog_ligths_consumption
double frontal_area
double Gear_ratio
double Gear_sys_effc
double heatingAC_consumption
double humidity
double internal_resis
double iron_losses
std::string light_mask
double mass
double motor_sys_effc
MSCFModel * myCarFollowModel
ID of the car following model.
RGBColor myColor
The color.
double myDefaultProbability
The probability when being added to a distribution without an explicit probability.
SUMOEmissionClass myEmissionClass
The emission class of such vehicles.
std::string myID
Unique ID.
std::string myLaneChangeModel
ID of the lane change model.
double myLength
Vehicles' length [m].
double myMaxSpeed
Vehicles' maximum speed [m/s].
double myMinGap
This class' free space in front of the vehicle itself.
const MSVehicleType * myOriginalType
The original type.
double mySpeedDev
The standard deviation for speed variations.
double mySpeedFactor
The factor by which the maximum speed may deviate from the allowed max speed on the street.
SUMOVehicleClass myVehicleClass
The vehicles' class.
double num_cells
double power_accs
double radio_consumption
double regen_ratio
double rolling_res
double time_charge
double vehicle_headligths_consumption
double windage_losses
Values for drawing this class' vehicles
This class' width
SUMOVehicleShape myShape
This class' shape.
double myWidth
Static methods for building vehicle types
double getAirDens () const
std::string getAuxMask () const
double getCapacity () const
double getCelsius () const
double getCockpitLigthsConsumption () const
double getConstantLosses () const
double getCooperLosses () const
double getDragCoefficient () const
double getFrontalArea () const
double getFrontFogLigthsConsumption () const
double getGearRatio () const
double getGearSysEffc () const
double getHeatingAcConsumption () const
double getHumidity () const
double getInternalResis () const
double getIronLosses () const
std::string getLightMask () const
double getMass () const
double getMotorSysEffc () const
double getNumCells () const
double getPowerAccs () const
double getRadioConsumption () const
double getRegenRatio () const
double getRollingRes () const
double getTimeCharge () const
double getVehicleHeadligthsConsumption () const
double getWindageLosses () const
void setAirDens (double air_dens)
void setAuxMask (std::string aux_mask)
void setCapacity (double capacity)
void setCelsius (double celsius)
void setCockpitLigthsConsumption (double cockpit_ligths_consumption)
void setConstantLosses (double constant_losses)
void setCooperLosses (double cooper_losses)
void setDragCoefficient (double drag_coefficient)
void setFrontalArea (double frontal_area)
void setFrontFogLigthsConsumption (double front_fog_ligths_consumption)
void setGearRatio (double Gear_ratio)
void setGearSysEffc (double Gear_sys_effc)
void setHeatingAcConsumption (double heatingAC_consumption)
void setHumidity (double humidity)
void setInternalResis (double internal_resis)
void setIronLosses (double iron_losses)
void setLightMask (std::string light_mask)
void setMass (double mass)
void setMotorSysEffc (double motor_sys_effc)
void setNumCells (double num_cells)
void setPowerAccs (double power_accs)
void setRadioConsumption (double radio_consumption)
void setRegenRatio (double regen_ratio)
void setRollingRes (double rolling_res)
void setTimeCharge (double time_charge)
void setVehicleHeadligthsConsumption (double vehicle_headligths_consumption)
void setWindageLosses (double windage_losses)
static MSVehicleType * build (const std::string &id, const MSVehicleType *from)
Duplicates the microsim vehicle type giving it a the given id.
static MSVehicleType * build (SUMOVTypeParameter &from)
Builds the microsim vehicle type described by the given parameter.
static double get (const SUMOVTypeParameter::CFParams &from, SumoXMLAttr attr, double defaultValue)
Returns the named value from the map, or the default if it is ot contained there.
Detailed Description
The car-following model and parameter.
MSVehicleType stores the parameter of a single vehicle type and methods that use these for computing the vehicle's car-following behavior
It is assumed that within the simulation many vehicles are using the same vehicle type, quite common is using only one vehicle type for all vehicles.
You can think of it like of having a vehicle type for each VW Golf or Ford Mustang in your simulation while the car instances just refer to it.
Definition at line 70 of file MSVehicleType.h.
Constructor & Destructor Documentation
MSVehicleType::MSVehicleType (const std::string & id, double lengthWithGap, double minGap, double maxSpeed, double prob, double speedFactor, double speedDev, SUMOVehicleClass vclass, SUMOEmissionClass emissionClass, double guiWidth, SUMOVehicleShape shape, const std::string & lcModel, const RGBColor & c)
Constructor.
Parameters:
[in] id The vehicle type's id
[in] length The length of vehicles that of this type
[in] minGap The free space in front of the vehicles of this class
[in] maxSpeed The maximum velocity vehicles of this type may drive with
[in] prob The probability of this vehicle type
[in] speedFactor The speed factor to scale maximum speed with
[in] speedDev The speed deviation
[in] vclass The class vehicles of this type belong to
[in] emissionClass The emission class vehicles of this type belong to
[in] guiWidth The width of the vehicles when being drawn
[in] shape How vehicles of this class shall be drawn
[in] lcModel Name of the lane-change model to use
[in] c Color of this vehicle type
Referenced by build().
MSVehicleType::MSVehicleType (const std::string & id, double lengthWithGap, double minGap, double maxSpeed, double prob, double speedFactor, double speedDev, SUMOVehicleClass vclass, SUMOEmissionClass emissionClass, double guiWidth, SUMOVehicleShape shape, const std::string & lcModel, const RGBColor & c, double m, double r_res, double air_r, double frotal, double drag_c, double gear_r, double gear_s_e, double reg_rat, double motor_s_e, double coop_l, double iron_l, double windage_l, double constant_l, double power_a, double num_c, double capac, double time, double temp, double hum, std::string aux_m, std::string ligth_m, double vehicle_ligths, double fron_ligth, double cockpit_lights, double radio, double heating)
MSVehicleType::~MSVehicleType () [virtual]
Destructor.
Definition at line 104 of file MSVehicleType.cpp.
References myCarFollowModel.
MSVehicleType::MSVehicleType (const MSVehicleType &) [private]
Invalidated copy constructor.
Member Function Documentation
bool MSVehicleType::amVehicleSpecific () const [inline]
Returns whether this type belongs to a single vehicle only (was modified).
Returns:
Whether this vehicle type is based on a differen one, and belongs to one vehicle only
Definition at line 416 of file MSVehicleType.h.
References myOriginalType.
Referenced by MSVehicle::replaceVehicleType(), and MSVehicle::~MSVehicle().
MSVehicleType * MSVehicleType::build (const std::string & id, const MSVehicleType * from) [static]
Duplicates the microsim vehicle type giving it a the given id.
Parameters:
[in] id The new id of the type
[in] from The vehicle type
Returns:
The built vehicle type
Definition at line 298 of file MSVehicleType.cpp.
References MSCFModel::duplicate(), MSVehicleType(), myCarFollowModel, myColor, myDefaultProbability, myEmissionClass, myLaneChangeModel, myLength, myMaxSpeed, myMinGap, myOriginalType, myShape, mySpeedDev, mySpeedFactor, myVehicleClass, and myWidth.
MSVehicleType * MSVehicleType::build (SUMOVTypeParameter & from) [static]
Builds the microsim vehicle type described by the given parameter.
Parameters:
[in] from The vehicle type description
Returns:
The built vehicle type
Exceptions:
ProcessError on false values (not et used)
Definition at line 219 of file MSVehicleType.cpp.
References SUMOVTypeParameter::air_dens, SUMOVTypeParameter::aux_mask, SUMOVTypeParameter::capacity, SUMOVTypeParameter::celsius, SUMOVTypeParameter::cfModel, SUMOVTypeParameter::cfParameter, SUMOVTypeParameter::cockpit_ligths_consumption, SUMOVTypeParameter::color, SUMOVTypeParameter::constant_losses, SUMOVTypeParameter::cooper_losses, DEFAULT_VEH_ACCEL, DEFAULT_VEH_DECEL, DEFAULT_VEH_SIGMA, DEFAULT_VEH_TAU, SUMOVTypeParameter::defaultProbability, SUMOVTypeParameter::drag_coefficient, SUMOVTypeParameter::emissionClass, SUMOVTypeParameter::front_fog_ligths_consumption, SUMOVTypeParameter::frontal_area, SUMOVTypeParameter::Gear_ratio, SUMOVTypeParameter::Gear_sys_effc, SUMOVTypeParameter::heatingAC_consumption, SUMOVTypeParameter::humidity, SUMOVTypeParameter::id, SUMOVTypeParameter::iron_losses, SUMOVTypeParameter::lcModel, SUMOVTypeParameter::length, SUMOVTypeParameter::light_mask, SUMOVTypeParameter::mass, SUMOVTypeParameter::maxSpeed, SUMOVTypeParameter::minGap, SUMOVTypeParameter::motor_sys_effc, MSVehicleType(), myCarFollowModel, SUMOVTypeParameter::num_cells, SUMOVTypeParameter::power_accs, SUMOVTypeParameter::radio_consumption, SUMOVTypeParameter::regen_ratio, SUMOVTypeParameter::rolling_res, SUMOVTypeParameter::shape, SUMOVTypeParameter::speedDev, SUMOVTypeParameter::speedFactor, SUMO_ATTR_ACCEL, SUMO_ATTR_CF_IDM_DELTA, SUMO_ATTR_CF_IDM_STEPPING, SUMO_ATTR_CF_IDMM_ADAPT_FACTOR, SUMO_ATTR_CF_IDMM_ADAPT_TIME, SUMO_ATTR_CF_KERNER_PHI, SUMO_ATTR_CF_PWAGNER2009_APPROB, SUMO_ATTR_CF_PWAGNER2009_TAULAST, SUMO_ATTR_CF_WIEDEMANN_ESTIMATION, SUMO_ATTR_CF_WIEDEMANN_SECURITY, SUMO_ATTR_DECEL, SUMO_ATTR_K, SUMO_ATTR_SIGMA, SUMO_ATTR_TAU, SUMO_TAG_CF_BKERNER, SUMO_TAG_CF_IDM, SUMO_TAG_CF_IDMM, SUMO_TAG_CF_KRAUSS, SUMO_TAG_CF_KRAUSS_ORIG1, SUMO_TAG_CF_PWAGNER2009, SUMO_TAG_CF_WIEDEMANN, SUMOVTypeParameter::time_charge, SUMOVTypeParameter::vehicle_headligths_consumption, SUMOVTypeParameter::vehicleClass, SUMOVTypeParameter::width, and SUMOVTypeParameter::windage_losses.
Referenced by TraCIServerAPI_Vehicle::getSingularType(), MSVehicleControl::MSVehicleControl(), and MSRouteHandler::myEndElement().
static double MSVehicleType::get (const SUMOVTypeParameter::CFParams & from, SumoXMLAttr attr, double defaultValue) [static]
Returns the named value from the map, or the default if it is ot contained there.
Parameters:
[in] from The map to retrieve values from
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns:
The named value from the map or the default if it does not exist there
double MSVehicleType::getAirDens () const
Definition at line 310 of file MSVehicleType.cpp.
References air_dens.
Referenced by MSDevice_FEV::computeMaxSpeed().
std::string MSVehicleType::getAuxMask () const
Definition at line 446 of file MSVehicleType.cpp.
References aux_mask.
Referenced by MSDevice_FEV::computeElectricAuxiliaries(), and MSVehicle::writeSyntheticData().
double MSVehicleType::getCapacity () const
Definition at line 314 of file MSVehicleType.cpp.
References capacity.
Referenced by MSDevice_FEV::computeMaxSpeed(), and MSVehicle::writeSyntheticData().
MSCFModel& MSVehicleType::getCarFollowModel () [inline]
Returns the vehicle type's car following model definition (non-const version).
Returns:
The vehicle type's car following model definition
Definition at line 147 of file MSVehicleType.h.
References myCarFollowModel.
const MSCFModel& MSVehicleType::getCarFollowModel () const [inline]
Returns the vehicle type's car following model definition (const version).
Returns:
The vehicle type's car following model definition
Definition at line 140 of file MSVehicleType.h.
References myCarFollowModel.
Referenced by MSVehicle::getCarFollowModel(), TraCIServerAPI_VehicleType::getVariable(), MSVehicle::moveChecked(), MSVehicle::MSVehicle(), and TraCIServerAPI_VehicleType::setVariable().
double MSVehicleType::getCelsius () const
Definition at line 450 of file MSVehicleType.cpp.
References celsius.
Referenced by MSVehicle::writeSyntheticData().
double MSVehicleType::getCockpitLigthsConsumption () const
Definition at line 486 of file MSVehicleType.cpp.
References cockpit_ligths_consumption.
Referenced by MSDevice_FEV::computeElectricAuxiliaries().
const RGBColor& MSVehicleType::getColor () const [inline]
Returns this type's color.
Returns:
The color of this type
Definition at line 205 of file MSVehicleType.h.
References myColor.
Referenced by TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getConstantLosses () const
Definition at line 318 of file MSVehicleType.cpp.
References constant_losses.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getCooperLosses () const
Definition at line 322 of file MSVehicleType.cpp.
References cooper_losses.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getDefaultProbability () const [inline]
Get the default probability of this vehicle type.
Returns:
The probability to use this type
Definition at line 182 of file MSVehicleType.h.
References myDefaultProbability.
Referenced by MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
double MSVehicleType::getDragCoefficient () const
Definition at line 326 of file MSVehicleType.cpp.
References drag_coefficient.
Referenced by MSDevice_FEV::computeMaxSpeed().
SUMOEmissionClass MSVehicleType::getEmissionClass () const [inline]
Get this vehicle type's emission class.
Returns:
The emission class of this vehicle type
See also:
SUMOEmissionClass
Definition at line 198 of file MSVehicleType.h.
References myEmissionClass.
Referenced by MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHBEFA_CO2Emissions(), MSVehicle::getHBEFA_COEmissions(), MSVehicle::getHBEFA_FuelConsumption(), MSVehicle::getHBEFA_HCEmissions(), MSVehicle::getHBEFA_NOxEmissions(), MSVehicle::getHBEFA_PMxEmissions(), TraCIServerAPI_VehicleType::getVariable(), MSDevice_HBEFA::notifyMove(), MSMeanData_HBEFA::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), and TraCIServerAPI_Vehicle::processGet().
double MSVehicleType::getFrontalArea () const
Definition at line 330 of file MSVehicleType.cpp.
References frontal_area.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getFrontFogLigthsConsumption () const
Definition at line 491 of file MSVehicleType.cpp.
References front_fog_ligths_consumption.
Referenced by MSDevice_FEV::computeElectricAuxiliaries().
double MSVehicleType::getGearRatio () const
Definition at line 334 of file MSVehicleType.cpp.
References Gear_ratio.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getGearSysEffc () const
Definition at line 338 of file MSVehicleType.cpp.
References Gear_sys_effc.
Referenced by MSDevice_FEV::computeMaxSpeed().
SUMOVehicleShape MSVehicleType::getGuiShape () const [inline]
Get this vehicle type's shape.
Returns:
The shape of this vehicle type
See also:
SUMOVehicleShape
Definition at line 253 of file MSVehicleType.h.
References myShape.
Referenced by drawAction_drawVehicleAsPoly(), and TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getGuiWidth () const [inline]
Get the width which vehicles of this class shall have when being drawn.
Returns:
The width of this type's vehicles
Definition at line 245 of file MSVehicleType.h.
References myWidth.
Referenced by drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), and TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getHeatingAcConsumption () const
Definition at line 496 of file MSVehicleType.cpp.
References heatingAC_consumption.
Referenced by MSDevice_FEV::computeElectricAuxiliaries().
double MSVehicleType::getHumidity () const
Definition at line 454 of file MSVehicleType.cpp.
References humidity.
Referenced by MSVehicle::writeSyntheticData().
const std::string& MSVehicleType::getID () const [inline]
Returns the name of the vehicle type.
Returns:
This type's id
Definition at line 112 of file MSVehicleType.h.
References myID.
Referenced by MSVehicleControl::addVType(), MSInductLoop::collectVehiclesOnDet(), MSVTypeProbe::execute(), MSDevice_Vehroutes::generateOutput(), MSDevice_Tripinfo::generateOutput(), GUIVehicle::getParameterWindow(), TraCIServerAPI_Vehicle::getSingularType(), MSInductLoop::leaveDetectorByMove(), MSVehicle::MSVehicle(), MSRouteHandler::myEndElement(), TraCIServerAPI_Vehicle::processGet(), MSMeanData::MeanDataValues::vehicleApplies(), and MSInstantInductLoop::write().
double MSVehicleType::getInternalResis () const
Definition at line 342 of file MSVehicleType.cpp.
References internal_resis.
double MSVehicleType::getIronLosses () const
Definition at line 346 of file MSVehicleType.cpp.
References iron_losses.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getLength () const [inline]
Get vehicle's length [m].
Returns:
The length vehicles of this type have in m
Definition at line 119 of file MSVehicleType.h.
References myLength.
Referenced by MSCFModel_Wiedemann::_v(), drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), TraCIServerAPI_VehicleType::getVariable(), and MSInstantInductLoop::write().
double MSVehicleType::getLengthWithGap () const [inline]
Get vehicle's length including the minimum gap [m].
Returns:
The length vehicles of this type have (including the minimum gap in m
Definition at line 126 of file MSVehicleType.h.
References myLength, and myMinGap.
Referenced by MSLaneChanger::change(), MSInductLoop::collectVehiclesOnDet(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), drawAction_drawBlinker(), drawAction_drawVehicleBrakeLight(), GUIVehicle::drawGL(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), MSLane::freeInsertion(), MSVehicle::gap2pred(), MSVehicle::getAngle(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealThisLeader(), MSLane::incorporateVehicle(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MSInductLoop::leaveDetectorByMove(), MSLane::leftByLaneChange(), MSCFModel::leftVehicleVsafe(), MSLane::maxSpeedGapInsertion(), MSVehicle::moveChecked(), MSInstantInductLoop::notifyEnter(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSInstantInductLoop::notifyMove(), MSInductLoop::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSVehicle::overlap(), MSAbstractLaneChangeModel::predInteraction(), MSLane::pWagGenericInsertion(), MSLane::pWagSimpleInsertion(), MSLane::removeVehicle(), MSLink::setApproaching(), MSLane::setCritical(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
std::string MSVehicleType::getLightMask () const
Definition at line 458 of file MSVehicleType.cpp.
References light_mask.
Referenced by MSDevice_FEV::computeElectricAuxiliaries(), and MSVehicle::writeSyntheticData().
double MSVehicleType::getMass () const
Definition at line 350 of file MSVehicleType.cpp.
References mass.
Referenced by MSDevice_FEV::computeMaxSpeed(), and MSVehicle::writeSyntheticData().
double MSVehicleType::getMaxSpeed () const [inline]
Get vehicle's maximum speed [m/s].
Returns:
The maximum speed (in m/s) of vehicles of this class
Definition at line 154 of file MSVehicleType.h.
References myMaxSpeed.
Referenced by MSCFModel_IDM::desiredSpeed(), MSBaseVehicle::getMaxSpeed(), TraCIServerAPI_VehicleType::getVariable(), MSCFModel::maxNextSpeed(), MSVehicle::MSVehicle(), saveState(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
double MSVehicleType::getMaxSpeedWithDeviation (double referenceSpeed) const [inline]
Get vehicle's maximum speed [m/s] drawn from a normal distribution.
The speed is calculated relative to the reference speed (which is usually the maximum allowed speed on a lane or edge).
Returns:
The maximum speed (in m/s) of vehicles of this class
Definition at line 171 of file MSVehicleType.h.
References MAX3(), MIN3(), myMaxSpeed, mySpeedDev, mySpeedFactor, RandHelper::randNorm(), and SUMOReal.
double MSVehicleType::getMinGap () const [inline]
Get the free space in front of vehicles of this class.
Returns:
The place before the vehicle
Definition at line 133 of file MSVehicleType.h.
References myMinGap.
Referenced by MSCFModel_IDM::_v(), drawAction_drawBlinker(), drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), and TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getMotorSysEffc () const
Definition at line 354 of file MSVehicleType.cpp.
References motor_sys_effc.
double MSVehicleType::getNumCells () const
Definition at line 358 of file MSVehicleType.cpp.
References num_cells.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getPowerAccs () const
Definition at line 362 of file MSVehicleType.cpp.
References power_accs.
double MSVehicleType::getRadioConsumption () const
Definition at line 501 of file MSVehicleType.cpp.
References radio_consumption.
Referenced by MSDevice_FEV::computeElectricAuxiliaries().
double MSVehicleType::getRegenRatio () const
Definition at line 366 of file MSVehicleType.cpp.
References regen_ratio.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getRollingRes () const
Definition at line 370 of file MSVehicleType.cpp.
References rolling_res.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::getSpeedDeviation () const [inline]
Returns this type's speed deviation.
Returns:
The speed deviation of this type double rolling_res; double air_dens; double frontal_area; double drag_coefficient; double Gear_ratio; double Gear_sys_effc; double regen_ratio; double motor_sys_effc; double cooper_losses; double iron_losses; double windage_losses; double constant_losses; double power_accs; double internal_resis; double num_cells; double capacity;
Definition at line 235 of file MSVehicleType.h.
References mySpeedDev.
Referenced by TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getSpeedFactor () const [inline]
Returns this type's speed factor.
Returns:
The speed factor of this type
Definition at line 212 of file MSVehicleType.h.
References mySpeedFactor.
Referenced by TraCIServerAPI_VehicleType::getVariable().
double MSVehicleType::getTimeCharge () const
Definition at line 478 of file MSVehicleType.cpp.
References time_charge.
SUMOVehicleClass MSVehicleType::getVehicleClass () const [inline]
Get this vehicle type's vehicle class.
Returns:
The class of this vehicle type
See also:
SUMOVehicleClass
Definition at line 190 of file MSVehicleType.h.
References myVehicleClass.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicle::getBestLanes(), MSEdge::getDepartLane(), TraCIServerAPI_VehicleType::getVariable(), MSBaseVehicle::hasValidRoute(), MSEdge::prohibits(), and MSLane::succLinkSec().
double MSVehicleType::getVehicleHeadligthsConsumption () const
Definition at line 506 of file MSVehicleType.cpp.
References vehicle_headligths_consumption.
Referenced by MSDevice_FEV::computeElectricAuxiliaries().
double MSVehicleType::getWindageLosses () const
Definition at line 374 of file MSVehicleType.cpp.
References windage_losses.
Referenced by MSDevice_FEV::computeMaxSpeed().
double MSVehicleType::hasSpeedDeviation () const [inline]
Get vehicle's maximum speed [m/s].
Returns:
The maximum speed (in m/s) of vehicles of this class
Definition at line 161 of file MSVehicleType.h.
References mySpeedDev, and mySpeedFactor.
MSVehicleType& MSVehicleType::operator= (const MSVehicleType &) [private]
Invalidated assignment operator.
void MSVehicleType::saveState (std::ostream & os)
Saves the states of a vehicle
Definition at line 108 of file MSVehicleType.cpp.
References RGBColor::blue(), getMaxSpeed(), MSCFModel::getModelID(), RGBColor::green(), myCarFollowModel, myColor, myDefaultProbability, myEmissionClass, myID, myLaneChangeModel, myLength, myMinGap, myShape, mySpeedDev, mySpeedFactor, myVehicleClass, myWidth, RGBColor::red(), FileHelpers::writeFloat(), FileHelpers::writeInt(), and FileHelpers::writeString().
void MSVehicleType::setAirDens (double air_dens)
Definition at line 378 of file MSVehicleType.cpp.
void MSVehicleType::setAuxMask (std::string aux_mask)
Definition at line 462 of file MSVehicleType.cpp.
void MSVehicleType::setCapacity (double capacity)
Definition at line 382 of file MSVehicleType.cpp.
void MSVehicleType::setCelsius (double celsius)
Definition at line 466 of file MSVehicleType.cpp.
void MSVehicleType::setCockpitLigthsConsumption (double cockpit_ligths_consumption)
Definition at line 511 of file MSVehicleType.cpp.
void MSVehicleType::setColor (const RGBColor & color)
Set a new value for this type's color.
Parameters:
[in] color The new color of this type
Definition at line 191 of file MSVehicleType.cpp.
References myColor.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setConstantLosses (double constant_losses)
Definition at line 386 of file MSVehicleType.cpp.
void MSVehicleType::setCooperLosses (double cooper_losses)
Definition at line 390 of file MSVehicleType.cpp.
void MSVehicleType::setDefaultProbability (const double & prob)
Set a new value for this type's default probability.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] prob The new default probability of this type
void MSVehicleType::setDragCoefficient (double drag_coefficient)
Definition at line 394 of file MSVehicleType.cpp.
void MSVehicleType::setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
Parameters:
[in] eclass The new emission class of this type
Definition at line 187 of file MSVehicleType.cpp.
References myEmissionClass.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setFrontalArea (double frontal_area)
Definition at line 398 of file MSVehicleType.cpp.
void MSVehicleType::setFrontFogLigthsConsumption (double front_fog_ligths_consumption)
Definition at line 516 of file MSVehicleType.cpp.
void MSVehicleType::setGearRatio (double Gear_ratio)
Definition at line 402 of file MSVehicleType.cpp.
void MSVehicleType::setGearSysEffc (double Gear_sys_effc)
Definition at line 406 of file MSVehicleType.cpp.
void MSVehicleType::setHeatingAcConsumption (double heatingAC_consumption)
Definition at line 521 of file MSVehicleType.cpp.
void MSVehicleType::setHumidity (double humidity)
Definition at line 470 of file MSVehicleType.cpp.
void MSVehicleType::setInternalResis (double internal_resis)
Definition at line 410 of file MSVehicleType.cpp.
void MSVehicleType::setIronLosses (double iron_losses)
Definition at line 414 of file MSVehicleType.cpp.
void MSVehicleType::setLength (const double & length)
Set a new value for this type's length.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] length The new length of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setLightMask (std::string light_mask)
Definition at line 474 of file MSVehicleType.cpp.
void MSVehicleType::setMass (double mass)
Definition at line 418 of file MSVehicleType.cpp.
void MSVehicleType::setMaxSpeed (const double & maxSpeed)
Set a new value for this type's maximum speed.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] maxSpeed The new maximum speed of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMinGap (const double & minGap)
Set a new value for this type's minimum gap.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] offset The new minimum gap of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMotorSysEffc (double motor_sys_effc)
Definition at line 422 of file MSVehicleType.cpp.
void MSVehicleType::setNumCells (double num_cells)
Definition at line 426 of file MSVehicleType.cpp.
void MSVehicleType::setPowerAccs (double power_accs)
Definition at line 430 of file MSVehicleType.cpp.
void MSVehicleType::setRadioConsumption (double radio_consumption)
Definition at line 526 of file MSVehicleType.cpp.
void MSVehicleType::setRegenRatio (double regen_ratio)
Definition at line 434 of file MSVehicleType.cpp.
void MSVehicleType::setRollingRes (double rolling_res)
Definition at line 438 of file MSVehicleType.cpp.
void MSVehicleType::setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
Parameters:
[in] shape The new shape of this type
Definition at line 204 of file MSVehicleType.cpp.
References myShape.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedDeviation (const double & dev)
Set a new value for this type's speed deviation.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] dev The new speed deviation of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedFactor (const double & factor)
Set a new value for this type's speed factor.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] factor The new speed factor of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setTimeCharge (double time_charge)
Definition at line 482 of file MSVehicleType.cpp.
void MSVehicleType::setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
Parameters:
[in] vclass The new vehicle class of this type
Definition at line 156 of file MSVehicleType.cpp.
References myVehicleClass.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setVehicleHeadligthsConsumption (double vehicle_headligths_consumption)
Definition at line 531 of file MSVehicleType.cpp.
void MSVehicleType::setWidth (const double & width)
Set a new value for this type's width.
If the given value<0 then the one from the original type will be used.
Parameters:
[in] width The new width of this type
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setWindageLosses (double windage_losses)
Definition at line 442 of file MSVehicleType.cpp.
Field Documentation
double MSVehicleType::air_dens [private]
Definition at line 459 of file MSVehicleType.h.
Referenced by getAirDens().
std::string MSVehicleType::aux_mask [private]
Definition at line 482 of file MSVehicleType.h.
Referenced by getAuxMask().
double MSVehicleType::capacity [private]
Definition at line 473 of file MSVehicleType.h.
Referenced by getCapacity().
double MSVehicleType::celsius [private]
Definition at line 474 of file MSVehicleType.h.
Referenced by getCelsius().
double MSVehicleType::cockpit_ligths_consumption [private]
Definition at line 478 of file MSVehicleType.h.
Referenced by getCockpitLigthsConsumption().
double MSVehicleType::constant_losses [private]
Definition at line 469 of file MSVehicleType.h.
Referenced by getConstantLosses().
double MSVehicleType::cooper_losses [private]
Definition at line 466 of file MSVehicleType.h.
Referenced by getCooperLosses().
double MSVehicleType::drag_coefficient [private]
Definition at line 461 of file MSVehicleType.h.
Referenced by getDragCoefficient().
double MSVehicleType::front_fog_ligths_consumption [private]
Definition at line 479 of file MSVehicleType.h.
Referenced by getFrontFogLigthsConsumption().
double MSVehicleType::frontal_area [private]
Definition at line 460 of file MSVehicleType.h.
Referenced by getFrontalArea().
double MSVehicleType::Gear_ratio [private]
Definition at line 462 of file MSVehicleType.h.
Referenced by getGearRatio().
double MSVehicleType::Gear_sys_effc [private]
Definition at line 463 of file MSVehicleType.h.
Referenced by getGearSysEffc().
double MSVehicleType::heatingAC_consumption [private]
Definition at line 481 of file MSVehicleType.h.
Referenced by getHeatingAcConsumption().
double MSVehicleType::humidity [private]
Definition at line 476 of file MSVehicleType.h.
Referenced by getHumidity().
double MSVehicleType::internal_resis [private]
Definition at line 471 of file MSVehicleType.h.
Referenced by getInternalResis().
double MSVehicleType::iron_losses [private]
Definition at line 467 of file MSVehicleType.h.
Referenced by getIronLosses().
std::string MSVehicleType::light_mask [private]
Definition at line 483 of file MSVehicleType.h.
Referenced by getLightMask().
double MSVehicleType::mass [private]
Definition at line 457 of file MSVehicleType.h.
Referenced by getMass().
double MSVehicleType::motor_sys_effc [private]
Definition at line 465 of file MSVehicleType.h.
Referenced by getMotorSysEffc().
MSCFModel* MSVehicleType::myCarFollowModel [private]
ID of the car following model.
Definition at line 436 of file MSVehicleType.h.
Referenced by build(), getCarFollowModel(), saveState(), and ~MSVehicleType().
RGBColor MSVehicleType::myColor [private]
The color.
Definition at line 442 of file MSVehicleType.h.
Referenced by build(), getColor(), saveState(), and setColor().
double MSVehicleType::myDefaultProbability [private]
The probability when being added to a distribution without an explicit probability.
Definition at line 430 of file MSVehicleType.h.
Referenced by build(), getDefaultProbability(), and saveState().
SUMOEmissionClass MSVehicleType::myEmissionClass [private]
The emission class of such vehicles.
Definition at line 440 of file MSVehicleType.h.
Referenced by build(), getEmissionClass(), saveState(), and setEmissionClass().
std::string MSVehicleType::myID [private]
Unique ID.
Definition at line 422 of file MSVehicleType.h.
Referenced by getID(), and saveState().
std::string MSVehicleType::myLaneChangeModel [private]
ID of the lane change model.
Definition at line 438 of file MSVehicleType.h.
Referenced by build(), and saveState().
double MSVehicleType::myLength [private]
Vehicles' length [m].
Definition at line 424 of file MSVehicleType.h.
Referenced by build(), getLength(), getLengthWithGap(), and saveState().
double MSVehicleType::myMaxSpeed [private]
Vehicles' maximum speed [m/s].
Definition at line 428 of file MSVehicleType.h.
Referenced by build(), getMaxSpeed(), and getMaxSpeedWithDeviation().
double MSVehicleType::myMinGap [private]
This class' free space in front of the vehicle itself.
Definition at line 426 of file MSVehicleType.h.
Referenced by build(), getLengthWithGap(), getMinGap(), and saveState().
const MSVehicleType* MSVehicleType::myOriginalType [private]
The original type.
Definition at line 455 of file MSVehicleType.h.
Referenced by amVehicleSpecific(), and build().
SUMOVehicleShape MSVehicleType::myShape [private]
This class' shape.
Definition at line 451 of file MSVehicleType.h.
Referenced by build(), getGuiShape(), saveState(), and setShape().
double MSVehicleType::mySpeedDev [private]
The standard deviation for speed variations.
Definition at line 434 of file MSVehicleType.h.
Referenced by build(), getMaxSpeedWithDeviation(), getSpeedDeviation(), hasSpeedDeviation(), and saveState().
double MSVehicleType::mySpeedFactor [private]
The factor by which the maximum speed may deviate from the allowed max speed on the street.
Definition at line 432 of file MSVehicleType.h.
Referenced by build(), getMaxSpeedWithDeviation(), getSpeedFactor(), hasSpeedDeviation(), and saveState().
SUMOVehicleClass MSVehicleType::myVehicleClass [private]
The vehicles' class.
Definition at line 444 of file MSVehicleType.h.
Referenced by build(), getVehicleClass(), saveState(), and setVClass().
double MSVehicleType::myWidth [private]
Definition at line 448 of file MSVehicleType.h.
Referenced by build(), getGuiWidth(), and saveState().
double MSVehicleType::num_cells [private]
Definition at line 472 of file MSVehicleType.h.
Referenced by getNumCells().
double MSVehicleType::power_accs [private]
Definition at line 470 of file MSVehicleType.h.
Referenced by getPowerAccs().
double MSVehicleType::radio_consumption [private]
Definition at line 480 of file MSVehicleType.h.
Referenced by getRadioConsumption().
double MSVehicleType::regen_ratio [private]
Definition at line 464 of file MSVehicleType.h.
Referenced by getRegenRatio().
double MSVehicleType::rolling_res [private]
Definition at line 458 of file MSVehicleType.h.
Referenced by getRollingRes().
double MSVehicleType::time_charge [private]
Definition at line 475 of file MSVehicleType.h.
Referenced by getTimeCharge().
double MSVehicleType::vehicle_headligths_consumption [private]
Definition at line 477 of file MSVehicleType.h.
Referenced by getVehicleHeadligthsConsumption().
double MSVehicleType::windage_losses [private]
Definition at line 468 of file MSVehicleType.h.
Referenced by getWindageLosses().
The documentation for this class was generated from the following files:
MSVehicleType.h
MSVehicleType.cpp