SUMO - Simulation of Urban MObility: ROAbstractEdgeBuilder Class Reference
ROAbstractEdgeBuilder Class Reference
Interface for building instances of router-edges.
#include <ROAbstractEdgeBuilder.h>
Public Member Functions
ROAbstractEdgeBuilder ()
Constructor.
virtual ~ROAbstractEdgeBuilder ()
Destructor.
Methods to be implemented
virtual ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to)=0
Builds an edge with the given name.
Protected Member Functions
unsigned int getNextIndex ()
Returns the index of the edge to built.
Private Member Functions
ROAbstractEdgeBuilder & operator= (const ROAbstractEdgeBuilder &src)
Invalidated assignment operator.
ROAbstractEdgeBuilder (const ROAbstractEdgeBuilder &src)
Invalidated copy constructor.
Private Attributes
unsigned int myCurrentIndex
The next edge's index.
Detailed Description
Interface for building instances of router-edges.
As the different routing algorithms may need certain types of edges, edges are build via a factory object derived from this class.
The only method to be implemented is "buildEdge" which builds an edge of the needed ROEdge-subtype.
The built edges are numbered in the order they are built, the current number (index) is stored in "myCurrentIndex" and the next to use may be obtained via "getNextIndex".
Definition at line 60 of file ROAbstractEdgeBuilder.h.
Constructor & Destructor Documentation
ROAbstractEdgeBuilder::ROAbstractEdgeBuilder () [inline]
Constructor.
Definition at line 63 of file ROAbstractEdgeBuilder.h.
virtual ROAbstractEdgeBuilder::~ROAbstractEdgeBuilder () [inline, virtual]
Destructor.
Definition at line 67 of file ROAbstractEdgeBuilder.h.
ROAbstractEdgeBuilder::ROAbstractEdgeBuilder (const ROAbstractEdgeBuilder & src) [private]
Invalidated copy constructor.
Member Function Documentation
virtual ROEdge* ROAbstractEdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to) [pure virtual]
Builds an edge with the given name.
Parameters:
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
Returns:
A proper instance of the named edge
Implemented in RODFEdgeBuilder, RODUAEdgeBuilder, and ROJTREdgeBuilder.
Referenced by RONetHandler::parseDistrict(), and RONetHandler::parseEdge().
unsigned int ROAbstractEdgeBuilder::getNextIndex () [inline, protected]
Returns the index of the edge to built.
Returns:
Next valid edge index
Definition at line 88 of file ROAbstractEdgeBuilder.h.
References myCurrentIndex.
Referenced by ROJTREdgeBuilder::buildEdge(), RODUAEdgeBuilder::buildEdge(), and RODFEdgeBuilder::buildEdge().
ROAbstractEdgeBuilder& ROAbstractEdgeBuilder::operator= (const ROAbstractEdgeBuilder & src) [private]
Invalidated assignment operator.
Field Documentation
unsigned int ROAbstractEdgeBuilder::myCurrentIndex [private]
The next edge's index.
Definition at line 95 of file ROAbstractEdgeBuilder.h.
Referenced by getNextIndex().
The documentation for this class was generated from the following file:
ROAbstractEdgeBuilder.h