SUMO - Simulation of Urban MObility: DijkstraRouterTT_Direct< E, V, PF > Class Template Reference
DijkstraRouterTT_Direct< E, V, PF > Class Template Reference
#include <DijkstraRouterTT.h>
Public Types
typedef SUMOReal(E::* Operation)(const V *const, SUMOReal) const
Type of the function that is used to retrieve the edge effort.
Public Member Functions
void buildPathFrom (EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual void compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum afford at the given time The definition of the afford depends on the wished routing scheme.
DijkstraRouterTT_Direct (size_t noE, bool unbuildIsWarningOnly, Operation operation)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
Protected Attributes
EdgeInfoByTTComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Private Attributes
Operation myOperation
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterTT_Direct< E, V, PF >
Definition at line 246 of file DijkstraRouterTT.h.
Member Typedef Documentation
template<class E , class V , class PF > typedef SUMOReal(E::* DijkstraRouterTT_Direct< E, V, PF >::Operation)(const V *const, SUMOReal) const
Type of the function that is used to retrieve the edge effort.
Definition at line 249 of file DijkstraRouterTT.h.
Constructor & Destructor Documentation
template<class E , class V , class PF > DijkstraRouterTT_Direct< E, V, PF >::DijkstraRouterTT_Direct (size_t noE, bool unbuildIsWarningOnly, Operation operation) [inline]
Definition at line 251 of file DijkstraRouterTT.h.
Member Function Documentation
template<class E , class V , class PF > void DijkstraRouterTTBase< E, V, PF >::buildPathFrom (EdgeInfo * rbegin, std::vector< const E * > & edges) [inline, inherited]
Builds the path from marked edges.
Definition at line 196 of file DijkstraRouterTT.h.
References DijkstraRouterTTBase< E, V, PF >::EdgeInfo::edge, and DijkstraRouterTTBase< E, V, PF >::EdgeInfo::prev.
Referenced by DijkstraRouterTTBase< E, V, PF >::compute().
template<class E , class V , class PF > virtual void DijkstraRouterTTBase< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) [inline, virtual, inherited]
Builds the route between the given edges using the minimum afford at the given time The definition of the afford depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 125 of file DijkstraRouterTT.h.
References DijkstraRouterTTBase< E, V, PF >::buildPathFrom(), DijkstraRouterTTBase< E, V, PF >::EdgeInfo::edge, DijkstraRouterTTBase< E, V, PF >::getEffort(), MsgHandler::inform(), max, DijkstraRouterTTBase< E, V, PF >::myComparator, DijkstraRouterTTBase< E, V, PF >::myEdgeInfos, DijkstraRouterTTBase< E, V, PF >::myErrorMsgHandler, DijkstraRouterTTBase< E, V, PF >::myFrontierList, DijkstraRouterTTBase< E, V, PF >::EdgeInfo::prev, STEPS2TIME, SUMOReal, DijkstraRouterTTBase< E, V, PF >::EdgeInfo::traveltime, and DijkstraRouterTTBase< E, V, PF >::EdgeInfo::visited.
Referenced by MSTriggeredRerouter::notifyEnter(), and TraCIServerAPI_Vehicle::processSet().
template<class E , class V , class PF > SUMOReal DijkstraRouterTT_Direct< E, V, PF >::getEffort (const E *const e, const V *const v, SUMOReal t) const [inline, virtual]
Implements DijkstraRouterTTBase< E, V, PF >.
Definition at line 254 of file DijkstraRouterTT.h.
References DijkstraRouterTT_Direct< E, V, PF >::myOperation.
template<class E , class V , class PF > SUMOReal DijkstraRouterTTBase< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const [inline, virtual, inherited]
Implements SUMOAbstractRouter< E, V >.
Definition at line 182 of file DijkstraRouterTT.h.
References DijkstraRouterTTBase< E, V, PF >::getEffort(), STEPS2TIME, and SUMOReal.
Field Documentation
template<class E , class V , class PF > EdgeInfoByTTComparator DijkstraRouterTTBase< E, V, PF >::myComparator [protected, inherited]
Definition at line 212 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< E, V, PF >::compute().
template<class E , class V , class PF > std::vector<EdgeInfo> DijkstraRouterTTBase< E, V, PF >::myEdgeInfos [protected, inherited]
The container of edge information.
Definition at line 207 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< E, V, PF >::compute(), and DijkstraRouterTTBase< E, V, PF >::DijkstraRouterTTBase().
template<class E , class V , class PF > MsgHandler* const DijkstraRouterTTBase< E, V, PF >::myErrorMsgHandler [protected, inherited]
the handler for routing errors
Definition at line 215 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< E, V, PF >::compute().
template<class E , class V , class PF > std::vector<EdgeInfo*> DijkstraRouterTTBase< E, V, PF >::myFrontierList [protected, inherited]
A container for reusage of the min edge heap.
Definition at line 210 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTTBase< E, V, PF >::compute().
template<class E , class V , class PF > Operation DijkstraRouterTT_Direct< E, V, PF >::myOperation [private]
Definition at line 259 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT_Direct< E, V, PF >::getEffort().
The documentation for this class was generated from the following file:
DijkstraRouterTT.h