SUMO - Simulation of Urban MObility: NBTrafficLightDefinition Class Reference
NBTrafficLightDefinition Class Reference
The base class for traffic light logic definitions.
#include <NBTrafficLightDefinition.h>
Public Types
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of edges not controlled by the tls.
NBTrafficLightLogic * compute (const NBEdgeCont &ec, OptionsCont &oc)
Computes the traffic light logic.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
const std::vector< NBNode * > & getControlledNodes () const
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first).
const std::string & getProgramID () const
Returns the ProgramID.
bool isLeftMover (const NBEdge *const from, const NBEdge *const to) const
returns the information whether the given link is a left-mover
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
NBTrafficLightDefinition (const std::string &id, const std::string &programID)
Constructor.
NBTrafficLightDefinition (const std::string &id, NBNode *junction, const std::string &programID)
Constructor.
NBTrafficLightDefinition (const std::string &id, const std::vector< NBNode * > &junctions, const std::string &programID)
Constructor.
virtual void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)=0
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
virtual void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)=0
Replaces a removed edge/lane.
void setID (const std::string &newID)
resets the id
virtual void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void setProgramID (const std::string &programID)
virtual void setTLControllingInformation (const NBEdgeCont &ec) const =0
Informs edges about being controlled by a tls.
virtual ~NBTrafficLightDefinition ()
Destructor.
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
Static Public Attributes
static const std::string DefaultProgramID = "0"
Protected Member Functions
virtual bool amInvalid () const
void collectEdges ()
Build the list of participating edges.
virtual void collectLinks ()=0
Collects the links participating in this traffic light
Exceptions:
ProcessError If a link could not be found.
unsigned int computeBrakingTime (SUMOReal minDecel) const
Computes the time vehicles may need to brake.
virtual NBTrafficLightLogic * myCompute (const NBEdgeCont &ec, unsigned int brakingTime)=0
Computes the traffic light logic finally in dependence to the type.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
std::string mySubID
The tls program's subid.
Detailed Description
The base class for traffic light logic definitions.
A base class is necessary, as we have two cases: a) the logic is given by the imported network, or b) the logic is not given and we have to compute it by ourselves. In the first case, NBLoadedTLDef should be used, in the second NBOwnTLDef.
See also:
NBLoadedTLDef
NBOwnTLDef
Definition at line 72 of file NBTrafficLightDefinition.h.
Member Enumeration Documentation
enum NBTrafficLightDefinition::TLColor
An enumeration of possible tl-signal states.
Enumerator:
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused).
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 81 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, const std::vector< NBNode * > & junctions, const std::string & programID)
Constructor.
Parameters:
[in] id The id of the tls
[in] junctions List of junctions controlled by this tls
Definition at line 59 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, NBNode * junction, const std::string & programID)
Constructor.
Parameters:
[in] id The id of the tls
[in] junction The (single) junction controlled by this tls
Definition at line 81 of file NBTrafficLightDefinition.cpp.
References addNode(), and NBNode::addTrafficLight().
NBTrafficLightDefinition::NBTrafficLightDefinition (const std::string & id, const std::string & programID)
Constructor.
Parameters:
[in] id The id of the tls
Definition at line 90 of file NBTrafficLightDefinition.cpp.
NBTrafficLightDefinition::~NBTrafficLightDefinition () [virtual]
Destructor.
Definition at line 94 of file NBTrafficLightDefinition.cpp.
Member Function Documentation
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges)
Adds the given ids into the list of edges not controlled by the tls.
Parameters:
[in] edges The list of edge ids to add the inner edges to
Definition at line 345 of file NBTrafficLightDefinition.cpp.
References myControlledInnerEdges.
void NBTrafficLightDefinition::addNode (NBNode * node) [virtual]
Adds a node to the traffic light logic.
Parameters:
[in] node A further node that shall be controlled by the tls
Definition at line 325 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and myControlledNodes.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedTLDef::addToSignalGroup(), and NBTrafficLightDefinition().
bool NBTrafficLightDefinition::amInvalid () const [protected, virtual]
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 121 of file NBTrafficLightDefinition.cpp.
References myControlledLinks.
Referenced by compute().
void NBTrafficLightDefinition::collectEdges () [protected]
Build the list of participating edges.
Definition at line 142 of file NBTrafficLightDefinition.cpp.
References Named::getID(), myControlledInnerEdges, myControlledNodes, myEdgesWithin, and myIncomingEdges.
Referenced by setParticipantsInformation(), and NBOwnTLDef::setParticipantsInformation().
virtual void NBTrafficLightDefinition::collectLinks () [protected, pure virtual]
Collects the links participating in this traffic light
Exceptions:
ProcessError If a link could not be found.
Implemented in NBLoadedSUMOTLDef, NBLoadedTLDef, and NBOwnTLDef.
Referenced by setParticipantsInformation().
NBTrafficLightLogic * NBTrafficLightDefinition::compute (const NBEdgeCont & ec, OptionsCont & oc)
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters:
[in] ec The edge container in order to retrieve edge information
[in] oc The options container holding options needed during the building
Returns:
The built logic (may be 0)
Definition at line 98 of file NBTrafficLightDefinition.cpp.
References amInvalid(), computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), OptionsCont::isSet(), myCompute(), myControlledNodes, and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic().
unsigned int NBTrafficLightDefinition::computeBrakingTime (SUMOReal minDecel) const [protected]
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 127 of file NBTrafficLightDefinition.cpp.
References NBContHelper::maxSpeed(), myIncomingEdges, and SUMOReal.
Referenced by compute().
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
Parameters:
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns:
Whether both stream are foes (cross)
Definition at line 302 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
Referenced by NBOwnTLDef::computeUnblockedWeightedStreamNumber().
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters:
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 225 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), and myControlledNodes.
Referenced by mustBrake(), and NBOwnTLDef::myCompute().
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const [inline]
returns the controlled links (depends on previous call to collectLinks)
Definition at line 274 of file NBTrafficLightDefinition.h.
References myControlledLinks.
Referenced by NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::vector<NBNode*>& NBTrafficLightDefinition::getControlledNodes () const [inline]
Definition at line 280 of file NBTrafficLightDefinition.h.
References myControlledNodes.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), collectEdges(), NBOwnTLDef::collectLinks(), compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const
Returns the list of incoming edges (must be build first).
Returns:
The edges which are incoming into the tls
Definition at line 351 of file NBTrafficLightDefinition.cpp.
References myIncomingEdges.
Referenced by NBOwnTLDef::myCompute().
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const [inline]
Returns the list of controlled nodes.
Returns:
Controlled nodes
Definition at line 154 of file NBTrafficLightDefinition.h.
References myControlledNodes.
const std::string& NBTrafficLightDefinition::getProgramID () const [inline]
Returns the ProgramID.
Returns:
The ID of the program (subID)
Definition at line 288 of file NBTrafficLightDefinition.h.
References mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIImporter_SUMO::myEndElement(), and NBLoadedSUMOTLDef::removeConnection().
bool NBTrafficLightDefinition::isLeftMover (const NBEdge *const from, const NBEdge *const to) const
returns the information whether the given link is a left-mover
Parameters:
[in] from The connection's start edge
[in] to The connection's end edge
Returns:
Whether the connection is a left-mover
Definition at line 173 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
Referenced by NBOwnTLDef::myCompute().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
Parameters:
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 203 of file NBTrafficLightDefinition.cpp.
References forbids().
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
Parameters:
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 215 of file NBTrafficLightDefinition.cpp.
References forbids(), NBConnection::getFrom(), and NBConnection::getTo().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters:
[in] from The connection's start edge
[in] to The connection's end edge
Returns:
Whether the described connection must brake (has higher priorised foes)
Definition at line 189 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
Referenced by NBLoadedTLDef::mustBrake().
virtual NBTrafficLightLogic* NBTrafficLightDefinition::myCompute (const NBEdgeCont & ec, unsigned int brakingTime) [protected, pure virtual]
Computes the traffic light logic finally in dependence to the type.
Parameters:
[in] ec The edge container
[in] brakingTime Duration a vehicle needs for braking in front of the tls
Returns:
The computed logic
Implemented in NBLoadedSUMOTLDef, NBLoadedTLDef, and NBOwnTLDef.
Referenced by compute().
virtual void NBTrafficLightDefinition::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) [pure virtual]
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters:
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
Implemented in NBLoadedSUMOTLDef, NBLoadedTLDef, and NBOwnTLDef.
void NBTrafficLightDefinition::removeNode (NBNode * node) [virtual]
Removes the given node from the list of controlled nodes.
Parameters:
[in] node The node that shall not be controlled by the tls any more
Definition at line 335 of file NBTrafficLightDefinition.cpp.
References myControlledNodes.
Referenced by NBNode::removeTrafficLight().
virtual void NBTrafficLightDefinition::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) [pure virtual]
Replaces a removed edge/lane.
Parameters:
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
Implemented in NBLoadedSUMOTLDef, NBLoadedTLDef, and NBOwnTLDef.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void NBTrafficLightDefinition::setParticipantsInformation () [virtual]
Builds the list of participating nodes/edges/links.
Reimplemented in NBOwnTLDef.
Definition at line 134 of file NBTrafficLightDefinition.cpp.
References collectEdges(), and collectLinks().
void NBTrafficLightDefinition::setProgramID (const std::string & programID) [inline]
Definition at line 293 of file NBTrafficLightDefinition.h.
References mySubID.
Referenced by NBTrafficLightLogicCont::insert().
virtual void NBTrafficLightDefinition::setTLControllingInformation (const NBEdgeCont & ec) const [pure virtual]
Informs edges about being controlled by a tls.
Parameters:
[in] ec The container of edges
Implemented in NBLoadedSUMOTLDef, NBLoadedTLDef, and NBOwnTLDef.
Field Documentation
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" [static]
Definition at line 75 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges [protected]
Set of inner edges that shall be controlled, though.
Definition at line 345 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), addControlledInnerEdges(), and collectEdges().
NBConnectionVector NBTrafficLightDefinition::myControlledLinks [protected]
The list of controlled links.
Definition at line 342 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), amInvalid(), NBLoadedSUMOTLDef::amInvalid(), NBOwnTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), getControlledLinks(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBLoadedSUMOTLDef::removeConnection(), NBOwnTLDef::setTLControllingInformation(), and NBLoadedSUMOTLDef::setTLControllingInformation().
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes [protected]
The container with participating nodes.
Definition at line 333 of file NBTrafficLightDefinition.h.
Referenced by addNode(), NBLoadedSUMOTLDef::amInvalid(), collectEdges(), NBLoadedTLDef::collectNodes(), compute(), foes(), forbids(), getControlledNodes(), getNodes(), isLeftMover(), mustBrake(), NBTrafficLightDefinition(), and removeNode().
EdgeVector NBTrafficLightDefinition::myEdgesWithin [protected]
The list of edges within the area controlled by the tls.
Definition at line 339 of file NBTrafficLightDefinition.h.
Referenced by collectEdges().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
EdgeVector NBTrafficLightDefinition::myIncomingEdges [protected]
The list of incoming edges.
Definition at line 336 of file NBTrafficLightDefinition.h.
Referenced by collectEdges(), NBOwnTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), computeBrakingTime(), and getIncomingEdges().
std::string NBTrafficLightDefinition::mySubID [protected]
The tls program's subid.
Definition at line 348 of file NBTrafficLightDefinition.h.
Referenced by getProgramID(), and setProgramID().
The documentation for this class was generated from the following files:
NBTrafficLightDefinition.h
NBTrafficLightDefinition.cpp