SUMO - Simulation of Urban MObility: NBContHelper::edge_by_junction_angle_sorter Class Reference
NBContHelper::edge_by_junction_angle_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
edge_by_junction_angle_sorter (NBNode *n)
constructor
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
Private Member Functions
SUMOReal getConvAngle (NBEdge *e) const
Converts the angle of the edge if it is an incoming edge.
Private Attributes
NBNode * myNode
the edge to compute the relative angle of
Detailed Description
edge_by_angle_sorter Class to sort edges by their angle
Definition at line 79 of file NBContHelper.h.
Constructor & Destructor Documentation
NBContHelper::edge_by_junction_angle_sorter::edge_by_junction_angle_sorter (NBNode * n) [inline, explicit]
constructor
Definition at line 82 of file NBContHelper.h.
Member Function Documentation
SUMOReal NBContHelper::edge_by_junction_angle_sorter::getConvAngle (NBEdge * e) const [private]
Converts the angle of the edge if it is an incoming edge.
Definition at line 116 of file NBContHelper.cpp.
References NBEdge::getFromNode(), NBEdge::getNormedAngle(), myNode, and SUMOReal.
Referenced by operator()().
int NBContHelper::edge_by_junction_angle_sorter::operator() (NBEdge * e1, NBEdge * e2) const
comparing operation
Definition at line 109 of file NBContHelper.cpp.
References getConvAngle().
Field Documentation
NBNode* NBContHelper::edge_by_junction_angle_sorter::myNode [private]
the edge to compute the relative angle of
Definition at line 93 of file NBContHelper.h.
Referenced by getConvAngle().
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp