SUMO - Simulation of Urban MObility: AGAdult Class Reference
AGAdult Class Reference
An adult person who can have a job.
#include <AGAdult.h>
Public Member Functions
AGAdult (int age)
Initialises the base class and the own attributes.
virtual bool decide (SUMOReal probability) const
Lets the person make a decision.
virtual int getAge () const
Provides the age of the person.
const AGWorkPosition & getWorkPosition () const throw (std::runtime_error)
Provides the work position of the adult.
bool isWorking () const
States whether this person occupies a work position at present.
void lostWorkPosition ()
Called when the adult has lost her job.
void print () const
Puts out a summary of the attributes.
void resignFromWorkPosition ()
Called when the adult should resign her job.
void tryToWork (SUMOReal employmentRate, std::vector< AGWorkPosition > *wps)
Tries to get a new work position.
Protected Attributes
int age
Static Private Member Functions
static AGWorkPosition * randomFreeWorkPosition (std::vector< AGWorkPosition > *wps)
Randomly selects a free work position from the list.
Private Attributes
AGWorkPosition * work
Detailed Description
An adult person who can have a job.
AGAdult extends AGPerson by various methods to handle work life.
Definition at line 57 of file AGAdult.h.
Constructor & Destructor Documentation
AGAdult::AGAdult (int age)
Initialises the base class and the own attributes.
Parameters:
[in] the age of the AGPerson
Definition at line 58 of file AGAdult.cpp.
Member Function Documentation
bool AGPerson::decide (SUMOReal probability) const [virtual, inherited]
Lets the person make a decision.
The higher the degree of belief is, the more likely this method returns true.
Parameters:
[in] degreeOfBelief how strong the person beliefs the proposition
Returns:
whether the person agrees with the proposition
Definition at line 72 of file AGPerson.cpp.
References RandHelper::rand().
Referenced by tryToWork().
int AGPerson::getAge () const [virtual, inherited]
Provides the age of the person.
Returns:
the age in years
Definition at line 65 of file AGPerson.cpp.
References AGPerson::age.
const AGWorkPosition & AGAdult::getWorkPosition () const throw (std::runtime_error)
Provides the work position of the adult.
You should test before, whether the adult has a job. If you call this method and the adult has no job, then a runtime exception is thrown.
Returns:
the work position
Exceptions:
runtime_error the adult has no work position
Definition at line 116 of file AGAdult.cpp.
References work.
bool AGAdult::isWorking () const
States whether this person occupies a work position at present.
Returns:
true if she has a work position
Definition at line 93 of file AGAdult.cpp.
References work.
void AGAdult::lostWorkPosition ()
Called when the adult has lost her job.
This method is called from AGWorkPosition, whenever the adult lost her job, be it because it got fired or because its resignation has been accepted.
Definition at line 100 of file AGAdult.cpp.
References work.
Referenced by AGWorkPosition::let().
void AGAdult::print () const [virtual]
Puts out a summary of the attributes.
Reimplemented from AGPerson.
Definition at line 64 of file AGAdult.cpp.
References AGPerson::age, and work.
AGWorkPosition * AGAdult::randomFreeWorkPosition (std::vector< AGWorkPosition > * wps) [static, private]
Randomly selects a free work position from the list.
Parameters:
[in] the list of work positions (free or not)
Returns:
the chosen free work position
Definition at line 45 of file AGAdult.cpp.
References RandHelper::rand().
Referenced by tryToWork().
void AGAdult::resignFromWorkPosition ()
Called when the adult should resign her job.
This method asks the WorkPosition to quit the job. The WorkPosition in turn calls AGAdult::lostWorkPosition.
Definition at line 107 of file AGAdult.cpp.
References AGWorkPosition::let(), and work.
void AGAdult::tryToWork (SUMOReal employmentRate, std::vector< AGWorkPosition > * wps)
Tries to get a new work position.
Depending on the employment rate, this adult randomly gets unemployed or employed. If it gets employed, it randomly chooses one of the free work positions and occupies it.
The new state (employed or unemployed) is chosen independently from the previous state. If the adult was employed, her previous job is given up.
Parameters:
[in] employmentRate (1 - unemploymentRate)
[in] wps the list of work positions (open or not) in the city
Definition at line 71 of file AGAdult.cpp.
References AGPerson::decide(), AGWorkPosition::let(), randomFreeWorkPosition(), AGWorkPosition::take(), and work.
Field Documentation
int AGPerson::age [protected, inherited]
Definition at line 72 of file AGPerson.h.
Referenced by AGChild::alocateASchool(), AGPerson::getAge(), AGPerson::print(), AGChild::print(), and print().
AGWorkPosition* AGAdult::work [private]
The work position of this adult.
A pointer to the work position or 0 if the adult is unemployed at present.
Definition at line 119 of file AGAdult.h.
Referenced by getWorkPosition(), isWorking(), lostWorkPosition(), print(), resignFromWorkPosition(), and tryToWork().
The documentation for this class was generated from the following files:
AGAdult.h
AGAdult.cpp