SUMO - Simulation of Urban MObility: GUI_E2_ZS_Collector Class Reference
GUI_E2_ZS_Collector Class Reference
The gui-version of the MS_E2_ZS_Collector.
#include <GUI_E2_ZS_Collector.h>
Data Structures
class MyWrapper
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Returns the wrapper for this detector.
void detectorUpdate (const SUMOTime step)
Computes the detector values in each time step.
SUMOReal getEndPos () const
Returns the end position of the detector.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getStartPos () const
Returns the begin position of the detector.
virtual DetectorUsage getUsageType () const
Returns the detector's usage type.
GUI_E2_ZS_Collector (const std::string &id, DetectorUsage usage, MSLane *const lane, SUMOReal startPos, SUMOReal detLength, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void reset ()
Resets all values.
void setID (const std::string &newID)
resets the id
~GUI_E2_ZS_Collector ()
Destructor.
Methods returning current values
SUMOReal getCurrentJamLengthInMeters () const
Returns the length of all jams in meters.
unsigned getCurrentJamLengthInVehicles () const
Returns the length of all jams in vehicles.
unsigned getCurrentJamNumber () const
Returns the current number of jams.
SUMOReal getCurrentMaxJamLengthInMeters () const
Returns the length in meters of the currently largest jam.
unsigned getCurrentMaxJamLengthInVehicles () const
Returns the length in vehicles of the currently largest jam.
SUMOReal getCurrentMeanLength () const
Returns the mean vehicle length of vehicles currently on the detector.
SUMOReal getCurrentMeanSpeed () const
Returns the mean vehicle speed of vehicles currently on the detector.
SUMOReal getCurrentOccupancy () const
Returns the curent detector occupancy.
unsigned getCurrentStartedHalts () const
Returns the length of all jams in meters.
unsigned getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
Methods inherited from MSMoveReminder
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Adds the vehicle to known vehicles if not beyond the dector.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Removes a known vehicle due to its lane-change.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Adds/removes vehicles from the list of vehicles to regard.
Methods inherited from MSDetectorFileOutput.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
Protected Attributes
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Detailed Description
The gui-version of the MS_E2_ZS_Collector.
Allows the building of a wrapper (also declared herein) which draws the detector on the gl-canvas. Beside this, the method "amVisible" is overridden to signalise that this detector is not used for simulation- -internal reasons, but is placed over the simulation by the user.
Definition at line 63 of file GUI_E2_ZS_Collector.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
GUI_E2_ZS_Collector::GUI_E2_ZS_Collector (const std::string & id, DetectorUsage usage, MSLane *const lane, SUMOReal startPos, SUMOReal detLength, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
Parameters:
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lane The lane to place the detector at
[in] startPos Begin position of the detector
[in] detLength Length of the detector
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
Todo:
The lane should not be given as a pointer
Definition at line 62 of file GUI_E2_ZS_Collector.cpp.
GUI_E2_ZS_Collector::~GUI_E2_ZS_Collector ()
Destructor.
Definition at line 71 of file GUI_E2_ZS_Collector.cpp.
Member Function Documentation
GUIDetectorWrapper * GUI_E2_ZS_Collector::buildDetectorGUIRepresentation () [virtual]
Returns the wrapper for this detector.
Returns:
The wrapper representing the detector
See also:
MyWrapper
Reimplemented from MSDetectorFileOutput.
Definition at line 75 of file GUI_E2_ZS_Collector.cpp.
Referenced by GUI_E2_ZS_CollectorOverLanes::MyWrapper::MyWrapper().
void MSE2Collector::detectorUpdate (const SUMOTime step) [virtual, inherited]
Computes the detector values in each time step.
This method should be called at the end of a simulation step, when all vehicles have moved. The current values are computed and summed up with the previous.
Parameters:
[in] currentTime The current simulation time
Reimplemented from MSDetectorFileOutput.
Definition at line 154 of file MSE2Collector.cpp.
References DELTA_T, MSE2Collector::JamInfo::firstStandingVehicle, MSVehicle::getLane(), MSMoveReminder::getLane(), MSVehicleType::getLengthWithGap(), MSLane::getPartialOccupator(), MSLane::getPartialOccupatorEnd(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSE2Collector::JamInfo::lastStandingVehicle, MAX2(), MSE2Collector::myCurrentJamLengthInMeters, MSE2Collector::myCurrentJamLengthInVehicles, MSE2Collector::myCurrentJamNo, MSE2Collector::myCurrentMaxJamLengthInMeters, MSE2Collector::myCurrentMaxJamLengthInVehicles, MSE2Collector::myCurrentMeanLength, MSE2Collector::myCurrentMeanSpeed, MSE2Collector::myCurrentOccupancy, MSE2Collector::myCurrentStartedHalts, MSE2Collector::myEndPos, MSE2Collector::myHaltingVehicleDurations, MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myJamDistanceThreshold, MSE2Collector::myJamHaltingSpeedThreshold, MSE2Collector::myJamHaltingTimeThreshold, MSE2Collector::myJamLengthInMetersSum, MSE2Collector::myJamLengthInVehiclesSum, MSE2Collector::myKnownVehicles, MSMoveReminder::myLane, MSE2Collector::myMaxJamInMeters, MSE2Collector::myMaxJamInVehicles, MSE2Collector::myMaxOccupancy, MSE2Collector::myMaxVehicleNumber, MSE2Collector::myMeanMaxJamInMeters, MSE2Collector::myMeanMaxJamInVehicles, MSE2Collector::myMeanVehicleNumber, MSE2Collector::myOccupancySum, MSE2Collector::myPastIntervalStandingDurations, MSE2Collector::myPastStandingDurations, MSE2Collector::mySpeedSum, MSE2Collector::myStartedHalts, MSE2Collector::myStartPos, MSE2Collector::myTimeSamples, MSE2Collector::myVehicleSamples, and SUMOReal.
SUMOReal MSE2Collector::getCurrentJamLengthInMeters () const [inherited]
Returns the length of all jams in meters.
Definition at line 443 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentJamLengthInMeters.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
unsigned MSE2Collector::getCurrentJamLengthInVehicles () const [inherited]
Returns the length of all jams in vehicles.
Definition at line 437 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentJamLengthInVehicles.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
unsigned MSE2Collector::getCurrentJamNumber () const [inherited]
Returns the current number of jams.
Definition at line 419 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentJamNo.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMaxJamLengthInMeters () const [inherited]
Returns the length in meters of the currently largest jam.
Definition at line 431 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentMaxJamLengthInMeters.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
unsigned MSE2Collector::getCurrentMaxJamLengthInVehicles () const [inherited]
Returns the length in vehicles of the currently largest jam.
Definition at line 425 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentMaxJamLengthInVehicles.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMeanLength () const [inherited]
Returns the mean vehicle length of vehicles currently on the detector.
Definition at line 413 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentMeanLength.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMeanSpeed () const [inherited]
Returns the mean vehicle speed of vehicles currently on the detector.
Definition at line 407 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentMeanSpeed.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentOccupancy () const [inherited]
Returns the curent detector occupancy.
Definition at line 401 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentOccupancy, and SUMOReal.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
unsigned MSE2Collector::getCurrentStartedHalts () const [inherited]
Returns the length of all jams in meters.
Definition at line 449 of file MSE2Collector.cpp.
References MSE2Collector::myCurrentStartedHalts.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
unsigned MSE2Collector::getCurrentVehicleNumber () const [inherited]
Returns the number of vehicles currently on the detector.
Definition at line 395 of file MSE2Collector.cpp.
References MSE2Collector::myKnownVehicles.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getEndPos () const [inline, inherited]
Returns the end position of the detector.
Returns:
The detector's end position
Definition at line 214 of file MSE2Collector.h.
References MSE2Collector::myEndPos.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), and GUI_E2_ZS_Collector::MyWrapper::MyWrapper().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
SUMOReal MSE2Collector::getStartPos () const [inline, inherited]
Returns the begin position of the detector.
Returns:
The detector's begin position
Definition at line 205 of file MSE2Collector.h.
References MSE2Collector::myStartPos.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), and GUI_E2_ZS_Collector::MyWrapper::MyWrapper().
virtual DetectorUsage MSE2Collector::getUsageType () const [inline, virtual, inherited]
Returns the detector's usage type.
See also:
DetectorUsage
Returns:
How the detector is used.
Definition at line 106 of file MSE2Collector.h.
References MSE2Collector::myUsage.
Referenced by GUI_E2_ZS_Collector::MyWrapper::drawGL().
bool MSE2Collector::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) [virtual, inherited]
Adds the vehicle to known vehicles if not beyond the dector.
If the vehicles is within the detector are, it is added to the list of known vehicles. The method returns true as long as the vehicle is not beyond the detector.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
False, if vehicle passed the detector entirely, else true.
See also:
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 113 of file MSE2Collector.cpp.
References MSVehicleType::getLengthWithGap(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), MSE2Collector::myEndPos, MSE2Collector::myKnownVehicles, and MSE2Collector::myStartPos.
bool MSE2Collector::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) [virtual, inherited]
Removes a known vehicle due to its lane-change.
If the reported vehicle is known, it is removed from the list of vehicles to regard (myKnownVehicles).
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also:
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 100 of file MSE2Collector.cpp.
References MSVehicleType::getLengthWithGap(), SUMOVehicle::getVehicleType(), MSE2Collector::myEndPos, MSE2Collector::myKnownVehicles, MSE2Collector::myStartPos, and MSMoveReminder::NOTIFICATION_JUNCTION.
bool MSE2Collector::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [virtual, inherited]
Adds/removes vehicles from the list of vehicles to regard.
As soon as the reported vehicle enters the detector area (position>myStartPos) it is added to the list of vehicles to regard (myKnownVehicles). It is removed from this list if it leaves the detector (position<lengt>myEndPos). The method returns true as long as the vehicle is not beyond the detector.
Parameters:
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep.
[in] newSpeed Unused here.
Returns:
False, if vehicle passed the detector entierly, else true.
See also:
MSMoveReminder
MSMoveReminder::notifyMove
Reimplemented from MSMoveReminder.
Definition at line 77 of file MSE2Collector.cpp.
References MSVehicleType::getLengthWithGap(), SUMOVehicle::getVehicleType(), MSE2Collector::myEndPos, MSE2Collector::myKnownVehicles, and MSE2Collector::myStartPos.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
void MSE2Collector::reset () [virtual, inherited]
Resets all values.
This method is called on initialisation and as soon as the values were written. Values for the next interval may be collected, then. The list of known vehicles stays untouched.
Reimplemented from MSDetectorFileOutput.
Definition at line 129 of file MSE2Collector.cpp.
References MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myJamLengthInMetersSum, MSE2Collector::myJamLengthInVehiclesSum, MSE2Collector::myMaxJamInMeters, MSE2Collector::myMaxJamInVehicles, MSE2Collector::myMaxOccupancy, MSE2Collector::myMaxVehicleNumber, MSE2Collector::myMeanMaxJamInMeters, MSE2Collector::myMeanMaxJamInVehicles, MSE2Collector::myMeanVehicleNumber, MSE2Collector::myOccupancySum, MSE2Collector::myPastIntervalStandingDurations, MSE2Collector::myPastStandingDurations, MSE2Collector::mySpeedSum, MSE2Collector::myStartedHalts, MSE2Collector::myTimeSamples, and MSE2Collector::myVehicleSamples.
Referenced by MSE2Collector::MSE2Collector(), and MSE2Collector::writeXMLOutput().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSE2Collector::writeXMLDetectorProlog (OutputDevice & dev) const [virtual, inherited]
Opens the XML-output using "detector" as root element.
Parameters:
[in] dev The output device to write the root into
See also:
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 389 of file MSE2Collector.cpp.
References OutputDevice::writeXMLHeader().
void MSE2Collector::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [virtual, inherited]
Writes collected values into the given stream.
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also:
MSDetectorFileOutput::writeXMLOutput
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 325 of file MSE2Collector.cpp.
References Named::getID(), MAX2(), MSE2Collector::myHaltingVehicleDurations, MSE2Collector::myIntervalHaltingVehicleDurations, MSE2Collector::myJamLengthInMetersSum, MSE2Collector::myJamLengthInVehiclesSum, MSE2Collector::myMaxJamInMeters, MSE2Collector::myMaxJamInVehicles, MSE2Collector::myMaxOccupancy, MSE2Collector::myMaxVehicleNumber, MSE2Collector::myMeanMaxJamInMeters, MSE2Collector::myMeanMaxJamInVehicles, MSE2Collector::myMeanVehicleNumber, MSE2Collector::myOccupancySum, MSE2Collector::myPastIntervalStandingDurations, MSE2Collector::myPastStandingDurations, MSE2Collector::mySpeedSum, MSE2Collector::myStartedHalts, MSE2Collector::myTimeSamples, MSE2Collector::myVehicleSamples, MSE2Collector::reset(), STEPS2TIME, SUMOReal, and time2string().
Field Documentation
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
The documentation for this class was generated from the following files:
GUI_E2_ZS_Collector.h
GUI_E2_ZS_Collector.cpp