SUMO - Simulation of Urban MObility: MSCFModel_Krauss Class Reference
MSCFModel_Krauss Class Reference
Krauss car-following model, with acceleration decrease and faster start.
#include <MSCFModel_Krauss.h>
Public Member Functions
MSCFModel * duplicate (const MSVehicleType *vtype) const
Duplicates the car-following model.
MSCFModel_Krauss (const MSVehicleType *vtype, SUMOReal accel, SUMOReal decel, SUMOReal dawdle, SUMOReal headwayTime)
Constructor.
~MSCFModel_Krauss ()
Destructor.
Currently fixed methods
SUMOReal brakeGap (SUMOReal speed) const
Returns the distance the vehicle needs to halt including driver's reaction time.
SUMOReal getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const
Returns the minimum gap to reserve if the leader is braking at maximum.
SUMOReal getSpeedAfterMaxDecel (SUMOReal v) const
Returns the velocity after maximum deceleration.
void leftVehicleVsafe (const MSVehicle *const ego, const MSVehicle *const neigh, SUMOReal &vSafe) const
Incorporates the influence of the vehicle on the left lane.
SUMOReal maxNextSpeed (SUMOReal speed) const
Returns the maximum speed given the current speed.
Methods to override by model implementation
virtual VehicleVariables * createVehicleVariables () const
Returns model specific values which are stored inside a vehicle and must be used with casting.
virtual SUMOReal freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed) const
Computes the vehicle's safe speed without a leader.
virtual SUMOReal interactionGap (const MSVehicle *const veh, SUMOReal vL) const
Returns the maximum gap at which an interaction between both vehicles occurs.
virtual void saveState (std::ostream &os)
Saves the model's definition into the state.
Implementations of the MSCFModel interface
SUMOReal followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Computes the vehicle's safe speed (no dawdling).
int getModelID () const
Returns the model's name.
SUMOReal stopSpeed (const MSVehicle *const veh, SUMOReal gap2pred) const
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling).
Virtual methods with default implementation
virtual SUMOReal getHeadwayTime () const
Get the driver's reaction time [s].
virtual SUMOReal getMaxAccel () const
Get the vehicle type's maximum acceleration [m/s^2].
virtual SUMOReal getMaxDecel () const
Get the vehicle type's maximum deceleration [m/s^2].
Implementations of the MSCFModel interface
SUMOReal getImperfection () const
Get the driver's imperfection.
SUMOReal moveHelper (MSVehicle *const veh, SUMOReal vPos) const
Applies interaction with stops and lane changing model influences.
Setter methods
void setHeadwayTime (SUMOReal headwayTime)
Sets a new value for driver reaction time [s].
void setImperfection (SUMOReal imperfection)
Sets a new value for driver imperfection.
void setMaxDecel (SUMOReal decel)
Sets a new value for maximum deceleration [m/s^2].
Setter methods
virtual void setMaxAccel (SUMOReal accel)
Sets a new value for maximum acceleration [m/s^2].
Protected Attributes
SUMOReal myAccel
The vehicle's maximum acceleration [m/s^2].
SUMOReal myDawdle
The vehicle's dawdle-parameter. 0 for no dawdling, 1 for max.
SUMOReal myDecel
The vehicle's maximum deceleration [m/s^2].
SUMOReal myHeadwayTime
The driver's desired time headway (aka reaction time tau) [s].
SUMOReal myTauDecel
The precomputed value for myDecel*myTau.
const MSVehicleType * myType
The type to which this model definition belongs to.
Private Member Functions
SUMOReal _vsafe (SUMOReal gap, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Returns the "safe" velocity.
SUMOReal dawdle (SUMOReal speed) const
Applies driver imperfection (dawdling / sigma).
Detailed Description
Krauss car-following model, with acceleration decrease and faster start.
See also:
MSCFModel
Definition at line 46 of file MSCFModel_Krauss.h.
Constructor & Destructor Documentation
MSCFModel_Krauss::MSCFModel_Krauss (const MSVehicleType * vtype, SUMOReal accel, SUMOReal decel, SUMOReal dawdle, SUMOReal headwayTime)
Constructor.
Parameters:
[in] accel The maximum acceleration
[in] decel The maximum deceleration
[in] dawdle The driver imperfection
[in] headwayTime The driver's reaction time
Definition at line 45 of file MSCFModel_Krauss.cpp.
Referenced by duplicate().
MSCFModel_Krauss::~MSCFModel_Krauss ()
Destructor.
Definition at line 51 of file MSCFModel_Krauss.cpp.
Member Function Documentation
SUMOReal MSCFModel_Krauss::_vsafe (SUMOReal gap, SUMOReal predSpeed, SUMOReal predMaxDecel) const [private]
Returns the "safe" velocity.
Parameters:
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The LEADER's speed
Returns:
the safe velocity
Returns the SK-vsafe.
Definition at line 85 of file MSCFModel_Krauss.cpp.
References ACCEL2SPEED, MSCFModel::myDecel, MSCFModel_KraussOrig1::myTauDecel, SPEED2DIST, and SUMOReal.
Referenced by followSpeed(), and stopSpeed().
SUMOReal MSCFModel::brakeGap (SUMOReal speed) const [inherited]
Returns the distance the vehicle needs to halt including driver's reaction time.
Parameters:
[in] speed The vehicle's current speed
Returns:
The distance needed to halt
Definition at line 104 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxDecel(), MSCFModel::myHeadwayTime, SPEED2DIST, and SUMOReal.
Referenced by MSVehicle::addStop(), MSLane::getLeaderOnConsecutive(), getMaxSpeedRegardingNextLanes(), MSLaneChanger::getRealLeader(), MSCFModel::getSecureGap(), MSLane::isInsertionSuccess(), MSLane::pWagGenericInsertion(), and MSLane::pWagSimpleInsertion().
virtual VehicleVariables* MSCFModel::createVehicleVariables () const [inline, virtual, inherited]
Returns model specific values which are stored inside a vehicle and must be used with casting.
Reimplemented in MSCFModel_IDM, MSCFModel_PWag2009, and MSCFModel_Wiedemann.
Definition at line 157 of file MSCFModel.h.
Referenced by MSVehicle::MSVehicle().
SUMOReal MSCFModel_Krauss::dawdle (SUMOReal speed) const [private, virtual]
Applies driver imperfection (dawdling / sigma).
Parameters:
[in] speed The speed with no dawdling
Returns:
The speed after dawdling
Reimplemented from MSCFModel_KraussOrig1.
Definition at line 67 of file MSCFModel_Krauss.cpp.
References ACCEL2SPEED, MAX2(), MSCFModel::myAccel, MSCFModel_KraussOrig1::myDawdle, RandHelper::rand(), and SUMOReal.
MSCFModel * MSCFModel_Krauss::duplicate (const MSVehicleType * vtype) const [virtual]
Duplicates the car-following model.
Parameters:
[in] vtype The vehicle type this model belongs to (1:1)
Returns:
A duplicate of this car-following model
Reimplemented from MSCFModel_KraussOrig1.
Definition at line 103 of file MSCFModel_Krauss.cpp.
References MSCFModel_Krauss(), MSCFModel::myAccel, MSCFModel_KraussOrig1::myDawdle, MSCFModel::myDecel, and MSCFModel::myHeadwayTime.
SUMOReal MSCFModel_Krauss::followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const [virtual]
Computes the vehicle's safe speed (no dawdling).
Parameters:
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns:
EGO's safe speed
See also:
MSCFModel::ffeV
Reimplemented from MSCFModel_KraussOrig1.
Definition at line 55 of file MSCFModel_Krauss.cpp.
References _vsafe(), MSCFModel::getSpeedAfterMaxDecel(), MAX2(), MSCFModel::maxNextSpeed(), and MIN2().
virtual SUMOReal MSCFModel::freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed) const [inline, virtual, inherited]
Computes the vehicle's safe speed without a leader.
Returns the velocity of the vehicle in dependence to the length of the free street and the target velocity at the end of the free range.
Parameters:
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] seen The look ahead distance
[in] maxSpeed The maximum allowed speed
Returns:
EGO's safe speed
Definition at line 96 of file MSCFModel.h.
References MSCFModel::followSpeed().
Referenced by getMaxSpeedRegardingNextLanes(), and MSLane::isInsertionSuccess().
virtual SUMOReal MSCFModel::getHeadwayTime () const [inline, virtual, inherited]
Get the driver's reaction time [s].
Returns:
The reaction time of this class' drivers in s
Definition at line 193 of file MSCFModel.h.
References MSCFModel::myHeadwayTime.
Referenced by TraCIServerAPI_VehicleType::getVariable(), MSLane::maxSpeedGapInsertion(), and MSLane::pWagSimpleInsertion().
SUMOReal MSCFModel_KraussOrig1::getImperfection () const [inline, virtual, inherited]
Get the driver's imperfection.
Returns:
The imperfection of drivers of this class
Reimplemented from MSCFModel.
Definition at line 105 of file MSCFModel_KraussOrig1.h.
References MSCFModel_KraussOrig1::myDawdle.
virtual SUMOReal MSCFModel::getMaxAccel () const [inline, virtual, inherited]
Get the vehicle type's maximum acceleration [m/s^2].
Returns:
The maximum acceleration (in m/s^2) of vehicles of this class
Definition at line 169 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and MSCFModel::maxNextSpeed().
virtual SUMOReal MSCFModel::getMaxDecel () const [inline, virtual, inherited]
Get the vehicle type's maximum deceleration [m/s^2].
Returns:
The maximum deceleration (in m/s^2) of vehicles of this class
Definition at line 177 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by MSCFModel::brakeGap(), MSLaneChanger::change2left(), MSLaneChanger::change2right(), MSLane::freeInsertion(), TraCIServerAPI_VehicleType::getVariable(), MSLCM_DK2004::informBlocker(), MSLane::isInsertionSuccess(), MSCFModel::leftVehicleVsafe(), MSLane::maxSpeedGapInsertion(), MSVehicle::moveChecked(), MSLane::pWagGenericInsertion(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
int MSCFModel_Krauss::getModelID () const [inline, virtual]
Returns the model's name.
Returns:
The model's name
See also:
MSCFModel::getModelName
Reimplemented from MSCFModel_KraussOrig1.
Definition at line 89 of file MSCFModel_Krauss.h.
References SUMO_TAG_CF_KRAUSS.
SUMOReal MSCFModel::getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const [inline, inherited]
Returns the minimum gap to reserve if the leader is braking at maximum.
Parameters:
[in] speed EGO's speed
[in] leaderSpeed LEADER's speed
[in] leaderMaxDecel LEADER's max. deceleration rate
Definition at line 239 of file MSCFModel.h.
References ACCEL2SPEED, MSCFModel::brakeGap(), MAX2(), SPEED2DIST, and SUMOReal.
Referenced by MSLaneChanger::change2left(), MSLaneChanger::change2right(), MSLane::freeInsertion(), MSLCM_DK2004::informBlocker(), and MSLane::isInsertionSuccess().
SUMOReal MSCFModel::getSpeedAfterMaxDecel (SUMOReal v) const [inline, inherited]
Returns the velocity after maximum deceleration.
Parameters:
[in] v The velocity
Returns:
The velocity after maximum deceleration
Definition at line 250 of file MSCFModel.h.
References ACCEL2SPEED, MAX2(), MSCFModel::myDecel, and SUMOReal.
Referenced by followSpeed(), MSCFModel_Wiedemann::stopSpeed(), and stopSpeed().
SUMOReal MSCFModel::interactionGap (const MSVehicle *const veh, SUMOReal vL) const [virtual, inherited]
Returns the maximum gap at which an interaction between both vehicles occurs.
"interaction" means that the LEADER influences EGO's speed.
Parameters:
[in] veh The EGO vehicle
[in] vL LEADER's speed
Returns:
The interaction gap
Todo:
evaluate signature
Reimplemented in MSCFModel_IDM, and MSCFModel_Wiedemann.
Definition at line 71 of file MSCFModel.cpp.
References MSVehicle::getLane(), MSLane::getMaxSpeed(), MSVehicle::getSpeed(), MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, SPEED2DIST, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::predInteraction().
void MSCFModel::leftVehicleVsafe (const MSVehicle *const ego, const MSVehicle *const neigh, SUMOReal & vSafe) const [inherited]
Incorporates the influence of the vehicle on the left lane.
In Germany, vehicles on the right lane must not pass a vehicle on the lane left to the if the allowed velocity>60km/h
Parameters:
[in] ego The ego vehicle
[in] neigh The neighbor vehicle on the left lane
[in,out] vSafe Current vSafe; may be adapted due to the left neighbor
Definition at line 86 of file MSCFModel.cpp.
References MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), MIN2(), and SUMOReal.
SUMOReal MSCFModel::maxNextSpeed (SUMOReal speed) const [inherited]
Returns the maximum speed given the current speed.
The implementation of this method must take into account the time step duration.
Justification: Due to air brake or other influences, the vehicle's next maximum speed may depend on the vehicle's current speed (given).
Parameters:
[in] speed The vehicle's current speed
Returns:
The maximum possible speed for the next step
Definition at line 98 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxAccel(), MSVehicleType::getMaxSpeed(), MIN2(), MSCFModel::myType, and SUMOReal.
Referenced by MSCFModel_KraussOrig1::followSpeed(), followSpeed(), MSCFModel_Kerner::followSpeed(), MSLane::getFollowerOnConsecutive(), MSCFModel::interactionGap(), MSVehicle::moveChecked(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2004::patchSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), stopSpeed(), and MSCFModel_Kerner::stopSpeed().
SUMOReal MSCFModel_KraussOrig1::moveHelper (MSVehicle *const veh, SUMOReal vPos) const [virtual, inherited]
Applies interaction with stops and lane changing model influences.
Parameters:
[in] veh The ego vehicle
[in] vPos The possible velocity
Returns:
The velocity after applying interactions with stops and lane change model influences
Reimplemented from MSCFModel.
Definition at line 55 of file MSCFModel_KraussOrig1.cpp.
References ACCEL2SPEED, MSCFModel_KraussOrig1::dawdle(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getMaxSpeed(), MSVehicle::getSpeed(), MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MIN3(), MSCFModel::myDecel, MSAbstractLaneChangeModel::patchSpeed(), MSVehicle::processNextStop(), MSVehicle::setPreDawdleAcceleration(), SPEED2ACCEL, SUMOReal, toString(), and WRITE_WARNING.
void MSCFModel::saveState (std::ostream & os) [virtual, inherited]
Saves the model's definition into the state.
Parameters:
[in] os The output to write the definition into
Definition at line 113 of file MSCFModel.cpp.
void MSCFModel_KraussOrig1::setHeadwayTime (SUMOReal headwayTime) [inline, virtual, inherited]
Sets a new value for driver reaction time [s].
Parameters:
[in] headwayTime The new driver reaction time (in s)
Reimplemented from MSCFModel.
Definition at line 134 of file MSCFModel_KraussOrig1.h.
References MSCFModel::myDecel, MSCFModel::myHeadwayTime, and MSCFModel_KraussOrig1::myTauDecel.
void MSCFModel_KraussOrig1::setImperfection (SUMOReal imperfection) [inline, virtual, inherited]
Sets a new value for driver imperfection.
Parameters:
[in] accel The new driver imperfection
Reimplemented from MSCFModel.
Definition at line 126 of file MSCFModel_KraussOrig1.h.
References MSCFModel_KraussOrig1::myDawdle.
virtual void MSCFModel::setMaxAccel (SUMOReal accel) [inline, virtual, inherited]
Sets a new value for maximum acceleration [m/s^2].
Parameters:
[in] accel The new acceleration in m/s^2
Definition at line 262 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCIServerAPI_VehicleType::setVariable().
void MSCFModel_KraussOrig1::setMaxDecel (SUMOReal decel) [inline, virtual, inherited]
Sets a new value for maximum deceleration [m/s^2].
Parameters:
[in] accel The new deceleration in m/s^2
Reimplemented from MSCFModel.
Definition at line 117 of file MSCFModel_KraussOrig1.h.
References MSCFModel::myDecel, MSCFModel::myHeadwayTime, and MSCFModel_KraussOrig1::myTauDecel.
SUMOReal MSCFModel_Krauss::stopSpeed (const MSVehicle *const veh, SUMOReal gap2pred) const [virtual]
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling).
Parameters:
[in] veh The vehicle (EGO)
[in] gap2pred The (netto) distance to the the obstacle
Returns:
EGO's safe speed for approaching a non-moving obstacle
See also:
MSCFModel::ffeS
Todo:
generic Interface, models can call for the values they need
Reimplemented from MSCFModel_KraussOrig1.
Definition at line 61 of file MSCFModel_Krauss.cpp.
References _vsafe(), MSVehicle::getSpeed(), MSCFModel::getSpeedAfterMaxDecel(), MAX2(), MSCFModel::maxNextSpeed(), and MIN2().
Field Documentation
SUMOReal MSCFModel::myAccel [protected, inherited]
The vehicle's maximum acceleration [m/s^2].
Definition at line 297 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_Kerner::_v(), MSCFModel_IDM::_v(), MSCFModel_PWag2009::dawdle(), MSCFModel_KraussOrig1::dawdle(), dawdle(), MSCFModel_Wiedemann::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_KraussOrig1::duplicate(), duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Wiedemann::fullspeed(), MSCFModel::getMaxAccel(), MSCFModel_IDM::interactionGap(), and MSCFModel::setMaxAccel().
SUMOReal MSCFModel_KraussOrig1::myDawdle [protected, inherited]
The vehicle's dawdle-parameter. 0 for no dawdling, 1 for max.
Definition at line 164 of file MSCFModel_KraussOrig1.h.
Referenced by MSCFModel_KraussOrig1::dawdle(), dawdle(), MSCFModel_KraussOrig1::duplicate(), duplicate(), MSCFModel_KraussOrig1::getImperfection(), and MSCFModel_KraussOrig1::setImperfection().
SUMOReal MSCFModel::myDecel [protected, inherited]
The vehicle's maximum deceleration [m/s^2].
Definition at line 300 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_PWag2009::_v(), MSCFModel_Kerner::_v(), MSCFModel_KraussOrig1::_vsafe(), _vsafe(), MSCFModel_Wiedemann::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_KraussOrig1::duplicate(), duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Wiedemann::emergency(), MSCFModel::getMaxDecel(), MSCFModel::getSpeedAfterMaxDecel(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel_KraussOrig1::setMaxDecel(), and MSCFModel::setMaxDecel().
SUMOReal MSCFModel::myHeadwayTime [protected, inherited]
The driver's desired time headway (aka reaction time tau) [s].
Definition at line 303 of file MSCFModel.h.
Referenced by MSCFModel_IDM::_v(), MSCFModel::brakeGap(), MSCFModel_PWag2009::duplicate(), MSCFModel_KraussOrig1::duplicate(), duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel::getHeadwayTime(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel_PWag2009::moveHelper(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel::setHeadwayTime(), and MSCFModel_KraussOrig1::setMaxDecel().
SUMOReal MSCFModel_KraussOrig1::myTauDecel [protected, inherited]
The precomputed value for myDecel*myTau.
Definition at line 167 of file MSCFModel_KraussOrig1.h.
Referenced by MSCFModel_KraussOrig1::_vsafe(), _vsafe(), MSCFModel_KraussOrig1::setHeadwayTime(), and MSCFModel_KraussOrig1::setMaxDecel().
const MSVehicleType* MSCFModel::myType [protected, inherited]
The type to which this model definition belongs to.
Definition at line 294 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_IDM::desiredSpeed(), and MSCFModel::maxNextSpeed().
The documentation for this class was generated from the following files:
MSCFModel_Krauss.h
MSCFModel_Krauss.cpp