SUMO - Simulation of Urban MObility: NIVisumTL::SignalGroup Class Reference
NIVisumTL::SignalGroup Class Reference
#include <NIVisumTL.h>
Public Member Functions
NBConnectionVector * GetConnections ()
SUMOTime GetEndTime ()
std::string GetName ()
PhaseMap * GetPhases ()
SUMOTime GetStartTime ()
void SetEndTime (SUMOTime EndTime)
void SetStartTime (SUMOTime StartTime)
SignalGroup (const std::string &Name, SUMOTime StartTime, SUMOTime EndTime)
~SignalGroup ()
Private Attributes
NBConnectionVector myConnections
std::string myName
PhaseMap myPhases
Detailed Description
Definition at line 83 of file NIVisumTL.h.
Constructor & Destructor Documentation
NIVisumTL::SignalGroup::SignalGroup (const std::string & Name, SUMOTime StartTime, SUMOTime EndTime)
Definition at line 98 of file NIVisumTL.cpp.
NIVisumTL::SignalGroup::~SignalGroup ()
Definition at line 103 of file NIVisumTL.cpp.
Member Function Documentation
NBConnectionVector * NIVisumTL::SignalGroup::GetConnections ()
Definition at line 111 of file NIVisumTL.cpp.
References myConnections.
Referenced by NIVisumTL::build(), and NIImporter_VISUM::parse_TurnsToSignalGroups().
SUMOTime NIVisumTL::TimePeriod::GetEndTime () [inherited]
Definition at line 64 of file NIVisumTL.cpp.
References NIVisumTL::TimePeriod::myEndTime.
Referenced by NIVisumTL::build().
std::string NIVisumTL::SignalGroup::GetName ()
Definition at line 105 of file NIVisumTL.cpp.
References myName.
NIVisumTL::PhaseMap * NIVisumTL::SignalGroup::GetPhases ()
Definition at line 117 of file NIVisumTL.cpp.
References myPhases.
Referenced by NIVisumTL::build(), and NIImporter_VISUM::parse_SignalGroupsToPhases().
SUMOTime NIVisumTL::TimePeriod::GetStartTime () [inherited]
Definition at line 69 of file NIVisumTL.cpp.
References NIVisumTL::TimePeriod::myStartTime.
Referenced by NIVisumTL::build().
void NIVisumTL::TimePeriod::SetEndTime (SUMOTime EndTime) [inherited]
Definition at line 74 of file NIVisumTL.cpp.
References NIVisumTL::TimePeriod::myEndTime.
void NIVisumTL::TimePeriod::SetStartTime (SUMOTime StartTime) [inherited]
Definition at line 79 of file NIVisumTL.cpp.
References NIVisumTL::TimePeriod::myStartTime.
Field Documentation
NBConnectionVector NIVisumTL::SignalGroup::myConnections [private]
Definition at line 90 of file NIVisumTL.h.
Referenced by GetConnections().
std::string NIVisumTL::SignalGroup::myName [private]
Definition at line 92 of file NIVisumTL.h.
Referenced by GetName().
PhaseMap NIVisumTL::SignalGroup::myPhases [private]
Definition at line 91 of file NIVisumTL.h.
Referenced by GetPhases().
The documentation for this class was generated from the following files:
NIVisumTL.h
NIVisumTL.cpp