SUMO - Simulation of Urban MObility: ROLoader Class Reference
ROLoader Class Reference
The data loader.
#include <ROLoader.h>
Data Structures
class EdgeFloatTimeLineRetriever_EdgeTravelTime
Obtains edge travel times from a weights handler and stores them within the edges.
class EdgeFloatTimeLineRetriever_EdgeWeight
Obtains edge weights from a weights handler and stores them within the edges.
Public Member Functions
virtual void loadNet (RONet &toFill, ROAbstractEdgeBuilder &eb)
Loads the network.
bool loadWeights (RONet &net, const std::string &optionName, const std::string &measure, bool useLanes)
Loads the net weights.
bool makeSingleStep (SUMOTime end, RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
unsigned int openRoutes (RONet &net)
Builds and opens all route loaders Route loaders are derived from ROAbstractRouteDefLoader.
virtual void processAllRoutes (SUMOTime start, SUMOTime end, RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Loads all routes at once This is done for all previously build route loaders.
virtual void processRoutesStepWise (SUMOTime start, SUMOTime end, RONet &net, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Loads routes stepwise This is done for all previously build route loaders.
ROLoader (OptionsCont &oc, bool emptyDestinationsAllowed)
Constructor.
virtual ~ROLoader ()
Destructor.
Protected Types
typedef std::vector
< ROAbstractRouteDefLoader * > RouteLoaderCont
Definition of route loader list.
Protected Member Functions
ROAbstractRouteDefLoader * buildNamedHandler (const std::string &optionName, const std::string &file, RONet &net)
void destroyHandlers ()
Deletes all handlers and clears their container ("myHandler").
SUMOTime getMinTimeStep () const
Returns the first time step known by the built handlers.
bool openTypedRoutes (const std::string &optionName, RONet &net)
Opens route handler of the given type.
void writeStats (SUMOTime time, SUMOTime start, int absNo)
Protected Attributes
bool myEmptyDestinationsAllowed
Information whether empty destinations are allowed.
RouteLoaderCont myHandler
List of route loaders.
OptionsCont & myOptions
Options to use.
Private Member Functions
ROLoader & operator= (const ROLoader &src)
Invalidated assignment operator.
ROLoader (const ROLoader &src)
Invalidated copy constructor.
Detailed Description
The data loader.
Loads the network and route descriptions using further classes.
Is capable to either load all routes in one step or go through them step wise.
Definition at line 65 of file ROLoader.h.
Member Typedef Documentation
typedef std::vector<ROAbstractRouteDefLoader*> ROLoader::RouteLoaderCont [protected]
Definition of route loader list.
Definition at line 220 of file ROLoader.h.
Constructor & Destructor Documentation
ROLoader::ROLoader (OptionsCont & oc, bool emptyDestinationsAllowed)
Constructor.
Parameters:
[in] oc The options to use
[in] emptyDestinationsAllowed Whether tripdefs may be given without destinations
Todo:
Recheck usage of emptyDestinationsAllowed
Definition at line 104 of file ROLoader.cpp.
ROLoader::~ROLoader () [virtual]
Destructor.
Definition at line 108 of file ROLoader.cpp.
References destroyHandlers().
ROLoader::ROLoader (const ROLoader & src) [private]
Invalidated copy constructor.
Member Function Documentation
ROAbstractRouteDefLoader * ROLoader::buildNamedHandler (const std::string & optionName, const std::string & file, RONet & net) [protected]
Definition at line 301 of file ROLoader.cpp.
References OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getString(), myEmptyDestinationsAllowed, myOptions, string2time(), and SUMOReal.
Referenced by openTypedRoutes().
void ROLoader::destroyHandlers () [protected]
Deletes all handlers and clears their container ("myHandler").
Definition at line 388 of file ROLoader.cpp.
References myHandler.
Referenced by openRoutes(), and ~ROLoader().
SUMOTime ROLoader::getMinTimeStep () const [protected]
Returns the first time step known by the built handlers.
The handlers are responsible for not adding route definitions prior to "begin"-Option's value. These priori departures must also not be reported by them whaen asking via "getLastReadTimeStep".
Returns:
The first time step of loaded routes
See also:
ROAbstractRouteDefLoader::getLastReadTimeStep
Definition at line 230 of file ROLoader.cpp.
References myHandler.
Referenced by openRoutes(), and processRoutesStepWise().
void ROLoader::loadNet (RONet & toFill, ROAbstractEdgeBuilder & eb) [virtual]
Loads the network.
Definition at line 114 of file ROLoader.cpp.
References FileHelpers::exists(), OptionsCont::getString(), OptionsCont::isSet(), myOptions, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, XMLSubSys::runParser(), and GenericSAXHandler::setFileName().
Referenced by initNet(), and main().
bool ROLoader::loadWeights (RONet & net, const std::string & optionName, const std::string & measure, bool useLanes)
Loads the net weights.
Definition at line 333 of file ROLoader.cpp.
References RONet::getEdgeMap(), OptionsCont::getStringVector(), OptionsCont::isUsableFileList(), myOptions, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, XMLSubSys::runParser(), and WRITE_MESSAGE.
Referenced by initNet().
bool ROLoader::makeSingleStep (SUMOTime end, RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router)
Definition at line 209 of file ROLoader.cpp.
References MsgHandler::getErrorInstance(), myHandler, myOptions, RONet::saveAndRemoveRoutesUntil(), and MsgHandler::wasInformed().
Referenced by processRoutesStepWise().
unsigned int ROLoader::openRoutes (RONet & net)
Builds and opens all route loaders Route loaders are derived from ROAbstractRouteDefLoader.
Definition at line 149 of file ROLoader.cpp.
References destroyHandlers(), OptionsCont::getBool(), getMinTimeStep(), OptionsCont::getString(), myHandler, myOptions, openTypedRoutes(), string2time(), time2string(), and WRITE_MESSAGE.
Referenced by computeRoutes().
bool ROLoader::openTypedRoutes (const std::string & optionName, RONet & net) [protected]
Opens route handler of the given type.
Checks whether the given option name is known, returns true if not (this means that everything's ok, though the according handler is not built).
Checks then whether the given option name is set and his value is one or a set of valid (existing) files. This is done via a call to "OptionsCont::isUsableFileList" (which generates a proper error message).
If the given files are valid, the proper instance(s) is built using "buildNamedHandler" and if this could be done, it is added to the list of route handlers to use ("myHandler")
Returns whether the wished handler(s) could be built.
Parameters:
[in] optionName The name of the option that refers to which handler and which files shall be used
[in] net The net to assign to the built handlers
Returns:
Whether the wished handler(s) could be built
Definition at line 265 of file ROLoader.cpp.
References buildNamedHandler(), OptionsCont::exists(), OptionsCont::getStringVector(), OptionsCont::isSet(), OptionsCont::isUsableFileList(), myHandler, myOptions, and WRITE_ERROR.
Referenced by openRoutes().
ROLoader& ROLoader::operator= (const ROLoader & src) [private]
Invalidated assignment operator.
void ROLoader::processAllRoutes (SUMOTime start, SUMOTime end, RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router) [virtual]
Loads all routes at once This is done for all previously build route loaders.
Definition at line 245 of file ROLoader.cpp.
References myHandler, myOptions, RONet::saveAndRemoveRoutesUntil(), SUMOTime_MAX, and writeStats().
Referenced by computeRoutes().
void ROLoader::processRoutesStepWise (SUMOTime start, SUMOTime end, RONet & net, SUMOAbstractRouter< ROEdge, ROVehicle > & router) [virtual]
Loads routes stepwise This is done for all previously build route loaders.
Definition at line 181 of file ROLoader.cpp.
References DELTA_T, RONet::furtherStored(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), getMinTimeStep(), makeSingleStep(), myHandler, myOptions, time2string(), MsgHandler::wasInformed(), WRITE_MESSAGE, and writeStats().
Referenced by computeRoutes().
void ROLoader::writeStats (SUMOTime time, SUMOTime start, int absNo) [protected]
Definition at line 376 of file ROLoader.cpp.
References OptionsCont::getBool(), MsgHandler::getMessageInstance(), myOptions, OUTPUT_ACCURACY, MsgHandler::progressMsg(), SUMOReal, time2string(), and toString().
Referenced by processAllRoutes(), and processRoutesStepWise().
Field Documentation
bool ROLoader::myEmptyDestinationsAllowed [protected]
Information whether empty destinations are allowed.
Definition at line 226 of file ROLoader.h.
Referenced by buildNamedHandler().
RouteLoaderCont ROLoader::myHandler [protected]
List of route loaders.
Definition at line 223 of file ROLoader.h.
Referenced by destroyHandlers(), getMinTimeStep(), makeSingleStep(), openRoutes(), openTypedRoutes(), processAllRoutes(), and processRoutesStepWise().
OptionsCont& ROLoader::myOptions [protected]
Options to use.
Definition at line 217 of file ROLoader.h.
Referenced by buildNamedHandler(), loadNet(), loadWeights(), makeSingleStep(), openRoutes(), openTypedRoutes(), processAllRoutes(), processRoutesStepWise(), and writeStats().
The documentation for this class was generated from the following files:
ROLoader.h
ROLoader.cpp