SUMO - Simulation of Urban MObility: SUMOVehicleClass.h File Reference
SUMOVehicleClass.h File Reference
#include <config.h>
#include <string>
#include <set>
#include <utils/common/UtilExceptions.h>
#include <utils/common/StringBijection.h>
#include <utils/xml/SUMOXMLDefinitions.h>
Typedefs
typedef std::set
< SUMOVehicleClass > SUMOVehicleClasses
Enumerations
enum SUMOEmissionClass {
SVE_UNKNOWN = -1, SVE_HDV_3_1 = 0, SVE_HDV_3_2, SVE_HDV_3_3,
SVE_HDV_6_1, SVE_HDV_6_2, SVE_HDV_6_3, SVE_HDV_6_4,
SVE_HDV_6_5, SVE_HDV_6_6, SVE_HDV_12_1, SVE_HDV_12_2,
SVE_HDV_12_3, SVE_HDV_12_4, SVE_HDV_12_5, SVE_HDV_12_6,
SVE_HDV_12_7, SVE_HDV_12_8, SVE_HDV_12_9, SVE_HDV_12_10,
SVE_HDV_12_11, SVE_HDV_12_12, SVE_P_LDV_7_1, SVE_P_LDV_7_2,
SVE_P_LDV_7_3, SVE_P_LDV_7_4, SVE_P_LDV_7_5, SVE_P_LDV_7_6,
SVE_P_LDV_7_7, SVE_P_LDV_14_1, SVE_P_LDV_14_2, SVE_P_LDV_14_3,
SVE_P_LDV_14_4, SVE_P_LDV_14_5, SVE_P_LDV_14_6, SVE_P_LDV_14_7,
SVE_P_LDV_14_8, SVE_P_LDV_14_9, SVE_P_LDV_14_10, SVE_P_LDV_14_11,
SVE_P_LDV_14_12, SVE_P_LDV_14_13, SVE_P_LDV_14_14, SVE_ZERO_EMISSIONS,
SVE_HDV_A0_3_1, SVE_HDV_A0_3_2, SVE_HDV_A0_3_3, SVE_HDV_A0_6_1,
SVE_HDV_A0_6_2, SVE_HDV_A0_6_3, SVE_HDV_A0_6_4, SVE_HDV_A0_6_5,
SVE_HDV_A0_6_6, SVE_HDV_A0_12_1, SVE_HDV_A0_12_2, SVE_HDV_A0_12_3,
SVE_HDV_A0_12_4, SVE_HDV_A0_12_5, SVE_HDV_A0_12_6, SVE_HDV_A0_12_7,
SVE_HDV_A0_12_8, SVE_HDV_A0_12_9, SVE_HDV_A0_12_10, SVE_HDV_A0_12_11,
SVE_HDV_A0_12_12, SVE_P_LDV_A0_7_1, SVE_P_LDV_A0_7_2, SVE_P_LDV_A0_7_3,
SVE_P_LDV_A0_7_4, SVE_P_LDV_A0_7_5, SVE_P_LDV_A0_7_6, SVE_P_LDV_A0_7_7,
SVE_P_LDV_A0_14_1, SVE_P_LDV_A0_14_2, SVE_P_LDV_A0_14_3, SVE_P_LDV_A0_14_4,
SVE_P_LDV_A0_14_5, SVE_P_LDV_A0_14_6, SVE_P_LDV_A0_14_7, SVE_P_LDV_A0_14_8,
SVE_P_LDV_A0_14_9, SVE_P_LDV_A0_14_10, SVE_P_LDV_A0_14_11, SVE_P_LDV_A0_14_12,
SVE_P_LDV_A0_14_13, SVE_P_LDV_A0_14_14
}
Definition of vehicle emission classes.
enum SUMOVehicleClass {
SVC_UNKNOWN = 0, SVC_PRIVATE = 1, SVC_PUBLIC_TRANSPORT = 2, SVC_PUBLIC_EMERGENCY = 4,
SVC_PUBLIC_AUTHORITY = 8, SVC_PUBLIC_ARMY = 16, SVC_VIP = 32, SVC_IGNORING = 64,
SVC_PASSENGER = 256, SVC_HOV = 512, SVC_TAXI = 1024, SVC_BUS = 2048,
SVC_DELIVERY = 4096, SVC_TRANSPORT = 8192, SVC_LIGHTRAIL = 16384, SVC_CITYRAIL = 32768,
SVC_RAIL_SLOW = 65536, SVC_RAIL_FAST = 131072, SVC_MOTORCYCLE = 262144, SVC_BICYCLE = 524288,
SVC_PEDESTRIAN = 1048576
}
Definition of vehicle classes to differ between different lane usage and authority types.
enum SUMOVehicleShape {
SVS_UNKNOWN, SVS_PEDESTRIAN, SVS_BICYCLE, SVS_MOTORCYCLE,
SVS_PASSENGER, SVS_PASSENGER_SEDAN, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_WAGON,
SVS_PASSENGER_VAN, SVS_DELIVERY, SVS_TRANSPORT, SVS_TRANSPORT_SEMITRAILER,
SVS_TRANSPORT_1TRAILER, SVS_BUS, SVS_BUS_CITY, SVS_BUS_CITY_FLEXIBLE,
SVS_BUS_OVERLAND, SVS_BUS_TROLLEY, SVS_RAIL, SVS_RAIL_LIGHT,
SVS_RAIL_CITY, SVS_RAIL_SLOW, SVS_RAIL_FAST, SVS_RAIL_CARGO,
SVS_E_VEHICLE, SVS_ANT
}
Definition of vehicle classes to differ between different appearences.
Functions
int getVehicleClassCompoundID (const std::string &name)
Returns the OR'ed id of the compound class given by its name.
std::string getVehicleClassCompoundName (int id)
SUMOVehicleClass getVehicleClassID (const std::string &name)
Returns the class id of the abstract class given by its name.
std::string getVehicleClassNames (const SUMOVehicleClasses &ids)
Returns the ids of the given classes, divided using a ' '.
SUMOEmissionClass getVehicleEmissionTypeID (const std::string &name)
Returns the class id of the emission class given by its name.
std::string getVehicleEmissionTypeName (SUMOEmissionClass id)
Returns the class name of the emission class given by its id.
SUMOVehicleShape getVehicleShapeID (const std::string &name)
Returns the class id of the shape class given by its name.
std::string getVehicleShapeName (SUMOVehicleShape id)
Returns the class name of the shape class given by its id.
void parseVehicleClasses (const std::vector< std::string > &classesS, SUMOVehicleClasses &classes)
Parses the given vector of class names into their enum-representation.
void parseVehicleClasses (const std::string &allowedS, const std::string &disallowedS, SUMOVehicleClasses &allowed, SUMOVehicleClasses &disallowed)
Parses the given definition of allowed/disallowed vehicle classes into the given containers.
void parseVehicleClasses (const std::string &classNames, SUMOVehicleClasses &container)
Parses the given definition of allowed/disallowed vehicle classes into the given containers.
Variables
const SUMOReal DEFAULT_VEH_ACCEL
const SUMOVehicleClass DEFAULT_VEH_CLASS
const SUMOReal DEFAULT_VEH_DECEL
const SumoXMLTag DEFAULT_VEH_FOLLOW_MODEL
const SUMOReal DEFAULT_VEH_GUIWIDTH
const std::string DEFAULT_VEH_LANE_CHANGE_MODEL
const SUMOReal DEFAULT_VEH_LENGTH
const SUMOReal DEFAULT_VEH_MAXSPEED
const SUMOReal DEFAULT_VEH_MINGAP
const SUMOReal DEFAULT_VEH_PROB
const SUMOVehicleShape DEFAULT_VEH_SHAPE
const SUMOReal DEFAULT_VEH_SIGMA
const SUMOReal DEFAULT_VEH_SPEEDDEV
const SUMOReal DEFAULT_VEH_SPEEDFACTOR
const SUMOReal DEFAULT_VEH_TAU
const std::string DEFAULT_VTYPE_ID
StringBijection< SUMOVehicleClass > SumoVehicleClassStrings
StringBijection< SUMOVehicleShape > SumoVehicleShapeStrings
Detailed Description
Author:
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Walter Bamberger
Date:
2006-01-24
Version:
Id
SUMOVehicleClass.h 11671 2012-01-07 20:14:30Z behrisch
Definition in file SUMOVehicleClass.h.
Typedef Documentation
typedef std::set<SUMOVehicleClass> SUMOVehicleClasses
Definition at line 294 of file SUMOVehicleClass.h.
Enumeration Type Documentation
enum SUMOEmissionClass
Definition of vehicle emission classes.
The order is important - HBEFA computation helper use it.
See also:
HelpersHBEFA
Enumerator:
SVE_UNKNOWN
SVE_HDV_3_1
SVE_HDV_3_2
SVE_HDV_3_3
SVE_HDV_6_1
SVE_HDV_6_2
SVE_HDV_6_3
SVE_HDV_6_4
SVE_HDV_6_5
SVE_HDV_6_6
SVE_HDV_12_1
SVE_HDV_12_2
SVE_HDV_12_3
SVE_HDV_12_4
SVE_HDV_12_5
SVE_HDV_12_6
SVE_HDV_12_7
SVE_HDV_12_8
SVE_HDV_12_9
SVE_HDV_12_10
SVE_HDV_12_11
SVE_HDV_12_12
SVE_P_LDV_7_1
SVE_P_LDV_7_2
SVE_P_LDV_7_3
SVE_P_LDV_7_4
SVE_P_LDV_7_5
SVE_P_LDV_7_6
SVE_P_LDV_7_7
SVE_P_LDV_14_1
SVE_P_LDV_14_2
SVE_P_LDV_14_3
SVE_P_LDV_14_4
SVE_P_LDV_14_5
SVE_P_LDV_14_6
SVE_P_LDV_14_7
SVE_P_LDV_14_8
SVE_P_LDV_14_9
SVE_P_LDV_14_10
SVE_P_LDV_14_11
SVE_P_LDV_14_12
SVE_P_LDV_14_13
SVE_P_LDV_14_14
SVE_ZERO_EMISSIONS
SVE_HDV_A0_3_1
SVE_HDV_A0_3_2
SVE_HDV_A0_3_3
SVE_HDV_A0_6_1
SVE_HDV_A0_6_2
SVE_HDV_A0_6_3
SVE_HDV_A0_6_4
SVE_HDV_A0_6_5
SVE_HDV_A0_6_6
SVE_HDV_A0_12_1
SVE_HDV_A0_12_2
SVE_HDV_A0_12_3
SVE_HDV_A0_12_4
SVE_HDV_A0_12_5
SVE_HDV_A0_12_6
SVE_HDV_A0_12_7
SVE_HDV_A0_12_8
SVE_HDV_A0_12_9
SVE_HDV_A0_12_10
SVE_HDV_A0_12_11
SVE_HDV_A0_12_12
SVE_P_LDV_A0_7_1
SVE_P_LDV_A0_7_2
SVE_P_LDV_A0_7_3
SVE_P_LDV_A0_7_4
SVE_P_LDV_A0_7_5
SVE_P_LDV_A0_7_6
SVE_P_LDV_A0_7_7
SVE_P_LDV_A0_14_1
SVE_P_LDV_A0_14_2
SVE_P_LDV_A0_14_3
SVE_P_LDV_A0_14_4
SVE_P_LDV_A0_14_5
SVE_P_LDV_A0_14_6
SVE_P_LDV_A0_14_7
SVE_P_LDV_A0_14_8
SVE_P_LDV_A0_14_9
SVE_P_LDV_A0_14_10
SVE_P_LDV_A0_14_11
SVE_P_LDV_A0_14_12
SVE_P_LDV_A0_14_13
SVE_P_LDV_A0_14_14
Definition at line 193 of file SUMOVehicleClass.h.
enum SUMOVehicleClass
Definition of vehicle classes to differ between different lane usage and authority types.
Bits:
0-7: vehicle ownership
8-23: vehicle size
From NavTeq:
[0] All
[1] Passenger cars
[2] High Occupancy Vehicle
[3] Emergency Vehicle
[4] Taxi
[5] Public Bus
[6] Delivery Truck
[7] Transport Truck
[8] Bicycle
[9] Pedestrian
Enumerator:
SVC_UNKNOWN
SVC_PRIVATE
private vehicles
SVC_PUBLIC_TRANSPORT
public transport vehicles
SVC_PUBLIC_EMERGENCY
public emergency vehicles
SVC_PUBLIC_AUTHORITY
authorities vehicles
SVC_PUBLIC_ARMY
army vehicles
SVC_VIP
vip vehicles
SVC_IGNORING
vehicles ignoring classes
SVC_PASSENGER
vehicle is a passenger car (a "normal" car)
SVC_HOV
vehicle is a HOV
SVC_TAXI
vehicle is a taxi
SVC_BUS
vehicle is a bus
SVC_DELIVERY
vehicle is a small delivery vehicle
SVC_TRANSPORT
vehicle is a large transport vehicle
SVC_LIGHTRAIL
vehicle is a light rail
SVC_CITYRAIL
vehicle is a city rail
SVC_RAIL_SLOW
vehicle is a slow moving transport rail
SVC_RAIL_FAST
vehicle is a fast moving rail
SVC_MOTORCYCLE
vehicle is a motorcycle
SVC_BICYCLE
vehicle is a bicycle
SVC_PEDESTRIAN
is a pedestrian
Definition at line 126 of file SUMOVehicleClass.h.
enum SUMOVehicleShape
Definition of vehicle classes to differ between different appearences.
Enumerator:
SVS_UNKNOWN
not defined
SVS_PEDESTRIAN
render as a pedestrian
SVS_BICYCLE
render as a bicycle
SVS_MOTORCYCLE
render as a motorcycle
SVS_PASSENGER
render as a passenger vehicle
SVS_PASSENGER_SEDAN
render as a sedan passenger vehicle ("Stufenheck")
SVS_PASSENGER_HATCHBACK
render as a hatchback passenger vehicle ("Fliessheck")
SVS_PASSENGER_WAGON
render as a wagon passenger vehicle ("Combi")
SVS_PASSENGER_VAN
render as a van
SVS_DELIVERY
render as a delivery vehicle
SVS_TRANSPORT
render as a transport vehicle
SVS_TRANSPORT_SEMITRAILER
render as a semi-trailer transport vehicle ("Sattelschlepper")
SVS_TRANSPORT_1TRAILER
render as a transport vehicle with one trailer
SVS_BUS
render as a bus
SVS_BUS_CITY
render as a city bus
SVS_BUS_CITY_FLEXIBLE
render as a flexible city bus
SVS_BUS_OVERLAND
render as a overland bus
SVS_BUS_TROLLEY
render as a trolley bus
SVS_RAIL
render as a rail
SVS_RAIL_LIGHT
render as a light rail
SVS_RAIL_CITY
render as a city rail
SVS_RAIL_SLOW
render as a slow (passenger) train
SVS_RAIL_FAST
render as a fast (passenger) train
SVS_RAIL_CARGO
render as a cargo train
SVS_E_VEHICLE
render as a (futuristic) e-vehicle
SVS_ANT
render as a giant ant
Definition at line 49 of file SUMOVehicleClass.h.
Function Documentation
int getVehicleClassCompoundID (const std::string & name)
Returns the OR'ed id of the compound class given by its name.
Parameters:
[in] name The name of the abstract vehicle class
Returns:
The OR'ed combination of base enum values
Definition at line 160 of file SUMOVehicleClass.cpp.
References SumoVehicleClassStrings, and SVC_UNKNOWN.
std::string getVehicleClassCompoundName (int id)
Definition at line 119 of file SUMOVehicleClass.cpp.
References SumoVehicleClassStrings.
SUMOVehicleClass getVehicleClassID (const std::string & name)
Returns the class id of the abstract class given by its name.
Parameters:
[in] name The name of the abstract vehicle class
Returns:
The internal representation of this class. Name must not be a compound name
Definition at line 151 of file SUMOVehicleClass.cpp.
References SumoVehicleClassStrings.
Referenced by NIXMLEdgesHandler::addLane(), NBEdgeCont::applyOptions(), SUMOVehicleParserHelper::parseVehicleClass(), parseVehicleClasses(), and TraCIServerAPI_VehicleType::setVariable().
std::string getVehicleClassNames (const SUMOVehicleClasses & ids)
Returns the ids of the given classes, divided using a ' '.
Parameters:
[in] ids The ids to encode
Returns:
The string representation of these classes
Definition at line 136 of file SUMOVehicleClass.cpp.
References toString().
Referenced by NIXMLEdgesHandler::addEdge(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_SUMO::writeLane().
SUMOEmissionClass getVehicleEmissionTypeID (const std::string & name)
Returns the class id of the emission class given by its name.
Parameters:
[in] name The name of the emission class
Returns:
The internal representation of this class
Definition at line 220 of file SUMOVehicleClass.cpp.
References TplConvert< E >::_2int(), SVE_HDV_12_1, SVE_HDV_3_1, SVE_HDV_6_1, SVE_HDV_A0_12_1, SVE_HDV_A0_3_1, SVE_HDV_A0_6_1, SVE_P_LDV_14_1, SVE_P_LDV_7_1, SVE_P_LDV_A0_14_1, SVE_P_LDV_A0_7_1, SVE_UNKNOWN, and SVE_ZERO_EMISSIONS.
Referenced by SUMOVehicleParserHelper::parseEmissionClass(), and TraCIServerAPI_VehicleType::setVariable().
std::string getVehicleEmissionTypeName (SUMOEmissionClass id)
Returns the class name of the emission class given by its id.
Parameters:
[in] id The id of the emission class
Returns:
The string representation of this class
Definition at line 254 of file SUMOVehicleClass.cpp.
References SVE_ZERO_EMISSIONS, and toString().
Referenced by TraCIServerAPI_VehicleType::getVariable(), and SUMOVTypeParameter::write().
SUMOVehicleShape getVehicleShapeID (const std::string & name)
Returns the class id of the shape class given by its name.
Parameters:
[in] name The name of the shape class
Returns:
The internal representation of this class
Definition at line 203 of file SUMOVehicleClass.cpp.
References SumoVehicleShapeStrings.
Referenced by TraCIServerAPI_VehicleType::setVariable().
std::string getVehicleShapeName (SUMOVehicleShape id)
Returns the class name of the shape class given by its id.
Parameters:
[in] id The id of the shape class
Returns:
The string representation of this class
Definition at line 213 of file SUMOVehicleClass.cpp.
References SumoVehicleShapeStrings.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and SUMOVTypeParameter::write().
void parseVehicleClasses (const std::vector< std::string > & classesS, SUMOVehicleClasses & classes)
Parses the given vector of class names into their enum-representation.
Parameters:
[in] classesS The names vector to parse
[out] classes The parsed classes
Definition at line 194 of file SUMOVehicleClass.cpp.
References getVehicleClassID().
void parseVehicleClasses (const std::string & allowedS, const std::string & disallowedS, SUMOVehicleClasses & allowed, SUMOVehicleClasses & disallowed)
Parses the given definition of allowed/disallowed vehicle classes into the given containers.
Parameters:
[in] allowedS Definition which classes are allowed
[in] disallowedS Definition which classes are not allowed
[out] allowed The set of allowed vehicle classes to fill
[out] disallowed The set of disallowed vehicle classes to fill
Definition at line 184 of file SUMOVehicleClass.cpp.
References parseVehicleClasses().
void parseVehicleClasses (const std::string & classNames, SUMOVehicleClasses & container)
Parses the given definition of allowed/disallowed vehicle classes into the given containers.
Parameters:
[in] classNames Space separated class names
[out] container The set of vehicle classes to fill
Definition at line 173 of file SUMOVehicleClass.cpp.
References getVehicleClassID(), StringTokenizer::hasNext(), and StringTokenizer::next().
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addEdge(), NLHandler::addLane(), NIXMLTypesHandler::myStartElement(), RONetHandler::parseLane(), parseVehicleClasses(), TraCIServerAPI_Lane::processSet(), and TraCIServerAPI_Edge::processSet().
Variable Documentation
const SUMOReal DEFAULT_VEH_ACCEL
Referenced by MSVehicleType::build().
const SUMOVehicleClass DEFAULT_VEH_CLASS
Referenced by ROEdge::prohibits().
const SUMOReal DEFAULT_VEH_DECEL
Referenced by MSVehicleType::build().
const SumoXMLTag DEFAULT_VEH_FOLLOW_MODEL
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_GUIWIDTH
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const std::string DEFAULT_VEH_LANE_CHANGE_MODEL
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_LENGTH
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_MAXSPEED
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_MINGAP
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_PROB
Referenced by MSRouteHandler::openRoute(), and SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOVehicleShape DEFAULT_VEH_SHAPE
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_SIGMA
Referenced by MSVehicleType::build().
const SUMOReal DEFAULT_VEH_SPEEDDEV
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_SPEEDFACTOR
Referenced by SUMOVTypeParameter::SUMOVTypeParameter().
const SUMOReal DEFAULT_VEH_TAU
Referenced by MSVehicleType::build().
const std::string DEFAULT_VTYPE_ID
Referenced by MSVehicleControl::checkVType(), MSDevice_Vehroutes::generateOutput(), MSVehicleControl::getVType(), MSVehicleControl::MSVehicleControl(), SUMOVehicleParameter::SUMOVehicleParameter(), and SUMOVTypeParameter::SUMOVTypeParameter().
StringBijection<SUMOVehicleClass> SumoVehicleClassStrings
Referenced by getVehicleClassCompoundID(), getVehicleClassCompoundName(), and getVehicleClassID().
StringBijection<SUMOVehicleShape> SumoVehicleShapeStrings
Referenced by getVehicleShapeID(), getVehicleShapeName(), and SUMOVehicleParserHelper::parseGuiShape().