SUMO - Simulation of Urban MObility: GUILaneWrapper Class Reference
GUILaneWrapper Class Reference
A MSLane extended for visualisation purposes.
#include <GUILaneWrapper.h>
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawMarkings (const GUIVisualizationSettings &s) const
draw lane borders and white markings
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
SUMOReal firstWaitingTime () const
bool forLane (const MSLane &lane) const
Returns true if the given lane id the lane this wrapper wraps the geometry of.
SUMOReal getEdgeLaneNumber () const
SUMOReal getHalfWidth () const
const MSLane & getLane () const
Returns the represented lane.
unsigned int getLinkNumber () const
Returns the number of links.
const PositionVector & getShape () const
const DoubleVector & getShapeLengths () const
const DoubleVector & getShapeRotations () const
GUILaneWrapper (MSLane &lane, const PositionVector &shape, unsigned int index)
Constructor.
virtual ~GUILaneWrapper ()
Destructor.
Parameter table window I/O
void addParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was opened.
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
inherited from GUIGlObject
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Atomar getter methods
const std::string & getFullName () const
Returns the full name appearing in the tool tip.
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
void setMicrosimID (const std::string &newID)
Changes the microsimID of the object (happens in NETEDIT).
Current state retrieval
SUMOReal getNormedHBEFA_CO2Emissions () const
Returns the sum of last step CO2 emissions normed by the lane's length.
SUMOReal getNormedHBEFA_COEmissions () const
Returns the sum of last step CO emissions normed by the lane's length.
SUMOReal getNormedHBEFA_FuelConsumption () const
Returns the sum of last step fuel comsumption normed by the lane's length.
SUMOReal getNormedHBEFA_HCEmissions () const
Returns the sum of last step HC emissions normed by the lane's length.
SUMOReal getNormedHBEFA_NOxEmissions () const
Returns the sum of last step NOx emissions normed by the lane's length.
SUMOReal getNormedHBEFA_PMxEmissions () const
Returns the sum of last step PMx emissions normed by the lane's length.
Static Public Member Functions
static SUMOReal getOverallMaxSpeed ()
Returns the fastest known lane speed.
Static Public Attributes
static StringBijection
< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
helper methods for building popup-menus
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
Protected Attributes
SUMOReal myHalfLaneWidth
Half of lane width, for speed-up.
unsigned int myIndex
The lane index.
MSLane & myLane
The assigned lane.
SUMOReal myQuarterLaneWidth
Quarter of lane width, for speed-up.
const PositionVector & myShape
The shape of the lane.
DoubleVector myShapeLengths
The lengths of the shape parts.
DoubleVector myShapeRotations
The rotations of the shape parts.
SUMOReal myVisLength
Static Protected Attributes
static SUMOReal myAllMaxSpeed = 0
The maximum velocity over all lanes.
Private Member Functions
SUMOReal getColorValue (size_t activeScheme) const
gets the color value according to the current scheme index
GUILaneWrapper (const GUILaneWrapper &)
Invalidated copy constructor.
GUILaneWrapper & operator= (const GUILaneWrapper &)
Invalidated assignment operator.
void ROWdrawAction_drawArrows () const
void ROWdrawAction_drawLane2LaneConnections () const
void ROWdrawAction_drawLinkNo () const
helper methods
void ROWdrawAction_drawLinkRules (const GUINet &net) const
void ROWdrawAction_drawTLSLinkNo (const GUINet &net) const
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
Detailed Description
A MSLane extended for visualisation purposes.
The extensions consist of information about the position of the lane and it's direction. Further, a mechanism to avoid concurrent visualisation and simulation what may cause problems when vehicles disappear is implemented using a mutex.
Definition at line 64 of file GUILaneWrapper.h.
Constructor & Destructor Documentation
GUILaneWrapper::GUILaneWrapper (MSLane & lane, const PositionVector & shape, unsigned int index)
Constructor.
Parameters:
[in] lane The lane to be represented
[in] shape The shape of the lane (!!! this is a member of the lane - no need to give it additionally)
Definition at line 82 of file GUILaneWrapper.cpp.
References Position::distanceTo(), MSLane::getMaxSpeed(), MSLane::getWidth(), myAllMaxSpeed, myHalfLaneWidth, myLane, myQuarterLaneWidth, myShape, myShapeLengths, myShapeRotations, myVisLength, PI, PositionVector::size(), SUMOReal, Position::x(), and Position::y().
GUILaneWrapper::~GUILaneWrapper () [virtual]
Destructor.
Definition at line 113 of file GUILaneWrapper.cpp.
GUILaneWrapper::GUILaneWrapper (const GUILaneWrapper &) [private]
Invalidated copy constructor.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) [inherited]
Lets this object know a parameter window showing the object's values was opened.
Parameters:
[in] w The opened parameter window
Definition at line 191 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to center to the object.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 129 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and GUIBusStop::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 138 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and GUIBusStop::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) [protected, inherited]
Builds the header.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 119 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and GUIBusStop::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 170 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and GUIBusStop::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to (de)select the object.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 148 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIVehicle::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIDetectorWrapper::getPopUpMenu(), and GUIBusStop::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to open the manipulator window.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 182 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUITriggeredRerouter::getPopUpMenu(), and GUILaneSpeedTrigger::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) [protected, inherited]
Builds an entry which allows to open the parameter window.
Parameters:
in,filled] ret The popup menu to add the entry to
[in] addSeparator Whether a separator shall be added, too
Definition at line 161 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIVehicle::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUIEdge::getPopUpMenu(), and GUIDetectorWrapper::getPopUpMenu().
void GUILaneWrapper::drawGL (const GUIVisualizationSettings & s) const [virtual]
Draws the object.
Parameters:
[in] s The settings for the current view (may influence drawing)
See also:
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 397 of file GUILaneWrapper.cpp.
References GLHelper::drawBoxLines(), GLHelper::drawLine(), GUIVisualizationSettings::drawLinkJunctionIndex, GUIVisualizationSettings::drawLinkTLIndex, drawMarkings(), MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), GUIGlObject::getGlID(), MSNet::getInstance(), getLane(), MSEdge::getPurpose(), GUIGlObject::getType(), MSLane::getVehiclesSecure(), GLO_JUNCTION, GUIVisualizationSettings::minVehicleSize, myHalfLaneWidth, myLane, myQuarterLaneWidth, myShape, myShapeLengths, myShapeRotations, MSLane::releaseVehicles(), ROWdrawAction_drawArrows(), ROWdrawAction_drawLane2LaneConnections(), ROWdrawAction_drawLinkNo(), ROWdrawAction_drawLinkRules(), ROWdrawAction_drawTLSLinkNo(), GUIVisualizationSettings::scale, setColor(), GUIVisualizationSettings::showLane2Lane, and GUIVisualizationSettings::showLinkDecals.
virtual void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const [inline, virtual, inherited]
Draws additional, user-triggered visualisations.
Parameters:
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIVehicle.
Definition at line 177 of file GUIGlObject.h.
References UNUSED_PARAMETER.
void GUILaneWrapper::drawMarkings (const GUIVisualizationSettings & s) const
draw lane borders and white markings
Definition at line 470 of file GUILaneWrapper.cpp.
References GLHelper::drawBoxLines(), getHalfWidth(), getShape(), getShapeLengths(), getShapeRotations(), GLO_EDGE, myIndex, myShapeLengths, myShapeRotations, setColor(), PositionVector::size(), SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const [inherited]
Definition at line 218 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIVehicle::drawGL(), GUIPointOfInterest::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIEdge::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIBusStop::drawGL(), and GUI_E2_ZS_Collector::MyWrapper::drawGL().
SUMOReal GUILaneWrapper::firstWaitingTime () const
Definition at line 578 of file GUILaneWrapper.cpp.
References myLane, and MSLane::myVehicles.
Referenced by getColorValue().
bool GUILaneWrapper::forLane (const MSLane & lane) const
Returns true if the given lane id the lane this wrapper wraps the geometry of.
Definition at line 123 of file GUILaneWrapper.cpp.
References myLane.
Referenced by GUIEdge::lane_wrapper_finder::operator()().
Boundary GUILaneWrapper::getCenteringBoundary () const [virtual]
Returns the boundary to which the view shall be centered in order to show the object.
Returns:
The boundary the object is within
See also:
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 542 of file GUILaneWrapper.cpp.
References Boundary::add(), Boundary::grow(), and myShape.
SUMOReal GUILaneWrapper::getColorValue (size_t activeScheme) const [private]
gets the color value according to the current scheme index
Definition at line 635 of file GUILaneWrapper.cpp.
References firstWaitingTime(), MSLane::getAllowedClasses(), MSLane::getEdge(), getEdgeLaneNumber(), GUIGlObject::getGlID(), MSLane::getHarmonoise_NoiseEmissions(), MSNet::getInstance(), getLane(), MSLane::getMaxSpeed(), getNormedHBEFA_CO2Emissions(), getNormedHBEFA_COEmissions(), getNormedHBEFA_FuelConsumption(), getNormedHBEFA_HCEmissions(), getNormedHBEFA_NOxEmissions(), getNormedHBEFA_PMxEmissions(), MSLane::getNotAllowedClasses(), MSLane::getOccupancy(), GUIGlObject::getType(), MSNet::getWeightsStorage(), gSelected, GUISelectedStorage::isSelected(), MSEdgeWeightsStorage::knowsTravelTime(), MSEdgeWeightsStorage::retrieveExistingTravelTime(), SUMOReal, and SVC_PASSENGER.
Referenced by setColor().
SUMOReal GUILaneWrapper::getEdgeLaneNumber () const
Definition at line 586 of file GUILaneWrapper.cpp.
References MSLane::getEdge(), MSEdge::getLanes(), myLane, and SUMOReal.
Referenced by getColorValue().
const std::string& GUIGlObject::getFullName () const [inline, inherited]
Returns the full name appearing in the tool tip.
Returns:
This object's typed id
Definition at line 102 of file GUIGlObject.h.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUITriggeredRerouter::openManipulator(), GUILaneSpeedTrigger::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const [inline, inherited]
Returns the numerical id of the object.
Returns:
This object's gl-id
Definition at line 110 of file GUIGlObject.h.
References GUIGlObject::myGlID.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIBusStop::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GUIVehicle::drawGLAdditional(), getColorValue(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUIVehicle::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GUISUMOViewParent::isSelected(), GUIGlChildWindow::isSelected(), GUISelectedStorage::loadIDs(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), ROWdrawAction_drawLinkRules(), and GUIGlObject::~GUIGlObject().
SUMOReal GUILaneWrapper::getHalfWidth () const [inline]
Definition at line 149 of file GUILaneWrapper.h.
References myHalfLaneWidth.
Referenced by drawMarkings().
const MSLane& GUILaneWrapper::getLane () const [inline]
Returns the represented lane.
Returns:
The lane represented by this wrapper
Definition at line 123 of file GUILaneWrapper.h.
References myLane.
Referenced by drawGL(), getColorValue(), ROWdrawAction_drawArrows(), ROWdrawAction_drawLane2LaneConnections(), ROWdrawAction_drawLinkNo(), ROWdrawAction_drawLinkRules(), and ROWdrawAction_drawTLSLinkNo().
unsigned int GUILaneWrapper::getLinkNumber () const
Returns the number of links.
Definition at line 560 of file GUILaneWrapper.cpp.
References MSLane::getLinkCont(), and myLane.
Referenced by ROWdrawAction_drawArrows(), ROWdrawAction_drawLane2LaneConnections(), ROWdrawAction_drawLinkNo(), ROWdrawAction_drawLinkRules(), and ROWdrawAction_drawTLSLinkNo().
const std::string& GUIGlObject::getMicrosimID () const [inline, inherited]
Returns the id of the object as known to microsim.
Returns:
The id of the object
Definition at line 141 of file GUIGlObject.h.
References GUIGlObject::myMicrosimID.
Referenced by GUIGlObject::createFullName(), GUIGlObject::drawName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), and GUIGLObjectPopupMenu::onCmdCopyName().
SUMOReal GUILaneWrapper::getNormedHBEFA_CO2Emissions () const
Returns the sum of last step CO2 emissions normed by the lane's length.
Returns:
CO2 emissions of vehicles on this lane during the last step, normed by the lane length
Definition at line 593 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_CO2Emissions(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getNormedHBEFA_COEmissions () const
Returns the sum of last step CO emissions normed by the lane's length.
Returns:
CO emissions of vehicles on this lane during the last step, normed by the lane length
Definition at line 599 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_COEmissions(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getNormedHBEFA_FuelConsumption () const
Returns the sum of last step fuel comsumption normed by the lane's length.
Returns:
Fuel comsumption of vehicles on this lane during the last step, normed by the lane length
Definition at line 623 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_FuelConsumption(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getNormedHBEFA_HCEmissions () const
Returns the sum of last step HC emissions normed by the lane's length.
Returns:
HC emissions of vehicles on this lane during the last step, normed by the lane length
Definition at line 617 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_HCEmissions(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getNormedHBEFA_NOxEmissions () const
Returns the sum of last step NOx emissions normed by the lane's length.
Returns:
NOx emissions of vehicles on this lane during the last step, normed by the lane length
Definition at line 611 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_NOxEmissions(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getNormedHBEFA_PMxEmissions () const
Returns the sum of last step PMx emissions normed by the lane's length.
Returns:
PMx emissions of vehicles on this lane during the last step, normed by the lane length
Definition at line 605 of file GUILaneWrapper.cpp.
References MSLane::getHBEFA_PMxEmissions(), MSLane::getLength(), and myLane.
Referenced by getColorValue().
SUMOReal GUILaneWrapper::getOverallMaxSpeed () [static]
Returns the fastest known lane speed.
Definition at line 117 of file GUILaneWrapper.cpp.
References myAllMaxSpeed.
GUIParameterTableWindow * GUILaneWrapper::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) [virtual]
Returns an own parameter window.
Parameters:
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns:
The built parameter window
See also:
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 528 of file GUILaneWrapper.cpp.
References GUIParameterTableWindow::closeBuilding(), MSLane::getLength(), MSLane::getMaxSpeed(), GUIParameterTableWindow::mkItem(), and myLane.
GUIGLObjectPopupMenu * GUILaneWrapper::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) [virtual]
Returns an own popup-menu.
Parameters:
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns:
The built popup-menu
See also:
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 509 of file GUILaneWrapper.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUISUMOAbstractView::getPositionInformation(), myShape, PositionVector::nearest_position_on_line_to_point(), SUMOReal, and toString().
const PositionVector & GUILaneWrapper::getShape () const
Definition at line 554 of file GUILaneWrapper.cpp.
References myShape.
Referenced by GUIVehicle::draw(), GUITriggeredRerouter::drawGL(), GUIEdge::drawGL(), drawMarkings(), GUITriggeredRerouter::GUITriggeredRerouter(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), ROWdrawAction_drawArrows(), ROWdrawAction_drawLane2LaneConnections(), ROWdrawAction_drawLinkNo(), ROWdrawAction_drawLinkRules(), and ROWdrawAction_drawTLSLinkNo().
const DoubleVector & GUILaneWrapper::getShapeLengths () const
Definition at line 572 of file GUILaneWrapper.cpp.
References myShapeLengths.
Referenced by GUIVehicle::draw(), and drawMarkings().
const DoubleVector & GUILaneWrapper::getShapeRotations () const
Definition at line 566 of file GUILaneWrapper.cpp.
References myShapeRotations.
Referenced by GUIVehicle::draw(), and drawMarkings().
GUIGlObjectType GUIGlObject::getType () const [inline, inherited]
Returns the type of the object as coded in GUIGlObjectType.
Returns:
The type of the object
See also:
GUIGlObjectType
Definition at line 154 of file GUIGlObject.h.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), drawGL(), GUILaneSpeedTrigger::drawGL(), GUIJunctionWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIBusStop::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GUIVehicle::drawGLAdditional(), getColorValue(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOViewParent::isSelected(), GUIGlChildWindow::isSelected(), GUISelectedStorage::loadIDs(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideAllRoutes(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideBestLanes(), GUIVehicle::GUIVehiclePopupMenu::onCmdHideCurrentRoute(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowAllRoutes(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowBestLanes(), GUIVehicle::GUIVehiclePopupMenu::onCmdShowCurrentRoute(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack(), GUIVehicle::GUIVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), and GUISelectedStorage::toggleSelection().
GUILaneWrapper& GUILaneWrapper::operator= (const GUILaneWrapper &) [private]
Invalidated assignment operator.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) [inherited]
Lets this object know a parameter window showing the object's values was closed.
Parameters:
[in] w The closed parameter window
Definition at line 197 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUILaneWrapper::ROWdrawAction_drawArrows () const [private]
Definition at line 286 of file GUILaneWrapper.cpp.
References GLHelper::drawBoxLine(), GLHelper::drawTriangleAtEnd(), PositionVector::getEnd(), getLane(), MSLane::getLinkCont(), getLinkNumber(), getShape(), LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, LINKSTATE_TL_OFF_NOSIGNAL, PI, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
void GUILaneWrapper::ROWdrawAction_drawLane2LaneConnections () const [private]
Definition at line 345 of file GUILaneWrapper.cpp.
References GLHelper::drawTriangleAtEnd(), getLane(), MSLane::getLinkCont(), getLinkNumber(), MSLane::getShape(), getShape(), LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_TL_RED, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
void GUILaneWrapper::ROWdrawAction_drawLinkNo () const [private]
helper methods
Definition at line 130 of file GUILaneWrapper.cpp.
References GLHelper::drawText(), PositionVector::getEnd(), getLane(), getLinkNumber(), getShape(), MSLane::getWidth(), myLane, PI, SUMOReal, toString(), Position::x(), and Position::y().
Referenced by drawGL().
void GUILaneWrapper::ROWdrawAction_drawLinkRules (const GUINet & net) const [private]
Definition at line 188 of file GUILaneWrapper.cpp.
References PositionVector::getEnd(), GUIGlObject::getGlID(), getLane(), MSLane::getLinkCont(), getLinkNumber(), GUINet::getLinkTLID(), getShape(), MSLink::getState(), MSLane::getWidth(), LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_TL_RED, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, myHalfLaneWidth, myLane, PI, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
void GUILaneWrapper::ROWdrawAction_drawTLSLinkNo (const GUINet & net) const [private]
Definition at line 157 of file GUILaneWrapper.cpp.
References GLHelper::drawText(), PositionVector::getEnd(), getLane(), getLinkNumber(), GUINet::getLinkTLIndex(), getShape(), MSLane::getWidth(), myLane, PI, SUMOReal, toString(), Position::x(), and Position::y().
Referenced by drawGL().
void GUILaneWrapper::setColor (const GUIVisualizationSettings & s) const [private]
sets the color according to the currente settings
Definition at line 629 of file GUILaneWrapper.cpp.
References GUIColorer::getActive(), GUIColorScheme::getColor(), getColorValue(), GUIColorer::getScheme(), and GUIVisualizationSettings::laneColorer.
Referenced by drawGL(), and drawMarkings().
void GUIGlObject::setMicrosimID (const std::string & newID) [inherited]
Changes the microsimID of the object (happens in NETEDIT).
Definition at line 112 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
void GUIGlObject::setPrefix (const std::string & prefix) [protected, inherited]
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
SUMOReal GUILaneWrapper::myAllMaxSpeed = 0 [static, protected]
The maximum velocity over all lanes.
Definition at line 221 of file GUILaneWrapper.h.
Referenced by getOverallMaxSpeed(), and GUILaneWrapper().
SUMOReal GUILaneWrapper::myHalfLaneWidth [protected]
Half of lane width, for speed-up.
Definition at line 215 of file GUILaneWrapper.h.
Referenced by drawGL(), getHalfWidth(), GUILaneWrapper(), and ROWdrawAction_drawLinkRules().
unsigned int GUILaneWrapper::myIndex [protected]
The lane index.
Definition at line 224 of file GUILaneWrapper.h.
Referenced by drawMarkings().
MSLane& GUILaneWrapper::myLane [protected]
The assigned lane.
Definition at line 203 of file GUILaneWrapper.h.
Referenced by drawGL(), firstWaitingTime(), forLane(), getEdgeLaneNumber(), getLane(), getLinkNumber(), getNormedHBEFA_CO2Emissions(), getNormedHBEFA_COEmissions(), getNormedHBEFA_FuelConsumption(), getNormedHBEFA_HCEmissions(), getNormedHBEFA_NOxEmissions(), getNormedHBEFA_PMxEmissions(), getParameterWindow(), GUILaneWrapper(), ROWdrawAction_drawLinkNo(), ROWdrawAction_drawLinkRules(), and ROWdrawAction_drawTLSLinkNo().
SUMOReal GUILaneWrapper::myQuarterLaneWidth [protected]
Quarter of lane width, for speed-up.
Definition at line 218 of file GUILaneWrapper.h.
Referenced by drawGL(), and GUILaneWrapper().
const PositionVector& GUILaneWrapper::myShape [protected]
The shape of the lane.
Definition at line 206 of file GUILaneWrapper.h.
Referenced by drawGL(), getCenteringBoundary(), getPopUpMenu(), getShape(), and GUILaneWrapper().
DoubleVector GUILaneWrapper::myShapeLengths [protected]
The lengths of the shape parts.
Definition at line 212 of file GUILaneWrapper.h.
Referenced by drawGL(), drawMarkings(), getShapeLengths(), and GUILaneWrapper().
DoubleVector GUILaneWrapper::myShapeRotations [protected]
The rotations of the shape parts.
Definition at line 209 of file GUILaneWrapper.h.
Referenced by drawGL(), drawMarkings(), getShapeRotations(), and GUILaneWrapper().
SUMOReal GUILaneWrapper::myVisLength [protected]
the visualisation length; As sources and sinks may be shorter/longer as their visualisation length, a second length information is necessary
Definition at line 200 of file GUILaneWrapper.h.
Referenced by GUILaneWrapper().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames [static, inherited]
associates object types with strings
Definition at line 94 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUILaneWrapper.h
GUILaneWrapper.cpp