SUMO - Simulation of Urban MObility: gl2ps.c File Reference
gl2ps.c File Reference
#include "gl2ps.h"
#include <stdio.h>
#include <stdlib.h>
#include <GL/gl.h>
#include <math.h>
#include <string.h>
#include <sys/types.h>
#include <stdarg.h>
#include <time.h>
#include <float.h>
Data Structures
struct _GL2PSbsptree
struct _GL2PSbsptree2d
struct _GL2PSimagemap
struct GL2PSbackend
struct GL2PScompress
struct GL2PScontext
struct GL2PSimage
struct GL2PSlist
struct GL2PSpdfgroup
struct GL2PSprimitive
struct GL2PSstring
struct GL2PStriangle
struct GL2PSvertex
Defines
#define GL2PS_BEGIN_BLEND_TOKEN 9
#define GL2PS_BEGIN_BOUNDARY_TOKEN 3
#define GL2PS_BEGIN_OFFSET_TOKEN 1
#define GL2PS_BEGIN_STIPPLE_TOKEN 5
#define GL2PS_COINCIDENT 1
#define GL2PS_DRAW_PIXELS_TOKEN 14
#define GL2PS_DST_BLEND_TOKEN 12
#define GL2PS_END_BLEND_TOKEN 10
#define GL2PS_END_BOUNDARY_TOKEN 4
#define GL2PS_END_OFFSET_TOKEN 2
#define GL2PS_END_STIPPLE_TOKEN 6
#define GL2PS_EPSILON 5.0e-3F
#define GL2PS_IMAGEMAP 7
#define GL2PS_IMAGEMAP_TOKEN 13
#define GL2PS_IMAGEMAP_VISIBLE 9
#define GL2PS_IMAGEMAP_WRITTEN 8
#define GL2PS_IN_BACK_OF 3
#define GL2PS_IN_FRONT_OF 2
#define GL2PS_LINE 3
#define GL2PS_LINE_WIDTH_TOKEN 8
#define GL2PS_NO_TYPE -1
#define GL2PS_PIXMAP 6
#define GL2PS_POINT 2
#define GL2PS_POINT_BACK 2
#define GL2PS_POINT_COINCIDENT 0
#define GL2PS_POINT_INFRONT 1
#define GL2PS_POINT_SIZE_TOKEN 7
#define GL2PS_QUADRANGLE 4
#define GL2PS_SPANNING 4
#define GL2PS_SPECIAL 10
#define GL2PS_SRC_BLEND_TOKEN 11
#define GL2PS_TEXT 1
#define GL2PS_TEXT_TOKEN 15
#define GL2PS_TRIANGLE 5
#define GL2PS_ZERO(arg) (fabs(arg) < 1.e-20)
#define GL2PS_ZOFFSET 5.0e-2F
#define GL2PS_ZOFFSET_LARGE 20.0F
#define GL2PS_ZSCALE 1000.0F
#define M_PI 3.1415926535897932384626433832795
Typedefs
typedef struct _GL2PSbsptree GL2PSbsptree
typedef struct _GL2PSbsptree2d GL2PSbsptree2d
typedef struct _GL2PSimagemap GL2PSimagemap
typedef GLfloat GL2PSplane [4]
typedef GLfloat GL2PSxyz [3]
Enumerations
enum GL2PS_TRIANGLE_PROPERTY {
T_UNDEFINED = -1, T_CONST_COLOR = 1, T_VAR_COLOR = 1<<1, T_ALPHA_1 = 1<<2,
T_ALPHA_LESS_1 = 1<<3, T_VAR_ALPHA = 1<<4
}
Functions
static void gl2psAdaptVertexForBlending (GL2PSvertex *v)
static void gl2psAddBoundaryInList (GL2PSprimitive *prim, GL2PSlist *list)
static GLint gl2psAddInBspImageTree (GL2PSprimitive *prim, GL2PSbsptree2d **tree)
static void gl2psAddIndex (GLshort *index0, GLshort *index1, GLshort *nb, GLshort i, GLshort j)
static void gl2psAddInImageTree (void *data)
static void gl2psAddPlanesInBspTreeImage (GL2PSprimitive *prim, GL2PSbsptree2d **tree)
static void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex *verts, GLint offset, GLushort pattern, GLint factor, GLfloat width, char boundary)
static void gl2psAddPrimitiveInList (GL2PSprimitive *prim, GL2PSlist *list)
static GLint gl2psAddText (GLint type, const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle)
static void gl2psAssignTriangleProperties (GL2PStriangle *t)
GL2PSDLL_API GLint gl2psBeginPage (const char *title, const char *producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba *colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE *stream, const char *filename)
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
static void gl2psBuildBspTree (GL2PSbsptree *tree, GL2PSlist *primitives)
static void gl2psBuildPolygonBoundary (GL2PSbsptree *tree)
static GLint gl2psCheckPoint (GL2PSxyz point, GL2PSplane plane)
static GLint gl2psCheckPrimitive (GL2PSprimitive *prim, GL2PSplane plane)
static int gl2psClosePDFDataStream (void)
static int gl2psCompareDepth (const void *a, const void *b)
static GLfloat gl2psComparePointPlane (GL2PSxyz point, GL2PSplane plane)
static void gl2psComputeTightBoundingBox (void *data)
static GL2PSimage * gl2psCopyPixmap (GL2PSimage *im)
static GL2PSprimitive * gl2psCopyPrimitive (GL2PSprimitive *p)
static GL2PSstring * gl2psCopyText (GL2PSstring *t)
static void gl2psCreateSplitPrimitive (GL2PSprimitive *parent, GL2PSplane plane, GL2PSprimitive *child, GLshort numverts, GLshort *index0, GLshort *index1)
static GL2PSprimitive * gl2psCreateSplitPrimitive2D (GL2PSprimitive *parent, GLshort numverts, GL2PSvertex *vertx)
static void gl2psCutEdge (GL2PSvertex *a, GL2PSvertex *b, GL2PSplane plane, GL2PSvertex *c)
GL2PSDLL_API GLint gl2psDisable (GLint mode)
static void gl2psDivideQuad (GL2PSprimitive *quad, GL2PSprimitive **t1, GL2PSprimitive **t2)
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char *imagemap)
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void *pixels)
GL2PSDLL_API GLint gl2psEnable (GLint mode)
GL2PSDLL_API GLint gl2psEndPage (void)
static void gl2psEndPostScriptLine (void)
static void gl2psEndSVGLine (void)
GL2PSDLL_API GLint gl2psEndViewport (void)
static void gl2psFillTriangleFromPrimitive (GL2PStriangle *t, GL2PSprimitive *p, GLboolean assignprops)
static GLint gl2psFindRoot (GL2PSlist *primitives, GL2PSprimitive **root)
static void gl2psFree (void *ptr)
static void gl2psFreeBspImageTree (GL2PSbsptree2d **tree)
static void gl2psFreeBspTree (GL2PSbsptree **tree)
static void gl2psFreeImagemap (GL2PSimagemap *list)
static void gl2psFreePixmap (GL2PSimage *im)
static void gl2psFreePrimitive (void *data)
static void gl2psFreeText (GL2PSstring *text)
GL2PSDLL_API const char * gl2psGetFileExtension (GLint format)
GL2PSDLL_API const char * gl2psGetFormatDescription (GLint format)
static GLshort gl2psGetIndex (GLshort i, GLshort num)
static void gl2psGetNormal (GLfloat *a, GLfloat *b, GLfloat *c)
GL2PSDLL_API GLint gl2psGetOptions (GLint *options)
static void gl2psGetPlane (GL2PSprimitive *prim, GL2PSplane plane)
static GLint gl2psGetPlaneFromPoints (GL2PSxyz a, GL2PSxyz b, GL2PSplane plane)
static GLfloat gl2psGetRGB (GL2PSimage *im, GLuint x, GLuint y, GLfloat *red, GLfloat *green, GLfloat *blue)
static GLint gl2psGetVertex (GL2PSvertex *v, GLfloat *p)
static GLboolean gl2psGreater (GLfloat f1, GLfloat f2)
static void gl2psInitTriangle (GL2PStriangle *t)
static GLboolean gl2psLess (GLfloat f1, GLfloat f2)
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
static void gl2psListAction (GL2PSlist *list, void(*action)(void *data))
static void gl2psListActionInverse (GL2PSlist *list, void(*action)(void *data))
static void gl2psListAdd (GL2PSlist *list, void *data)
static GL2PSlist * gl2psListCreate (GLint n, GLint incr, GLint size)
static void gl2psListDelete (GL2PSlist *list)
static int gl2psListNbr (GL2PSlist *list)
static void * gl2psListPointer (GL2PSlist *list, GLint index)
static void gl2psListRealloc (GL2PSlist *list, GLint n)
static void gl2psListReset (GL2PSlist *list)
static void gl2psListSort (GL2PSlist *list, int(*fcmp)(const void *a, const void *b))
static void * gl2psMalloc (size_t size)
static void gl2psMsg (GLint level, const char *fmt,...)
static GLfloat gl2psNorm (GLfloat *a)
static int gl2psOpenPDFDataStream (void)
static int gl2psOpenPDFDataStreamWritePreface (void)
static void gl2psParseFeedbackBuffer (GLint used)
static void gl2psParseStipplePattern (GLushort pattern, GLint factor, int *nb, int array[10])
static void gl2psPDFgroupListDelete (void)
static void gl2psPDFgroupListInit (void)
static int gl2psPDFgroupListWriteFontResources (void)
static int gl2psPDFgroupListWriteGStateResources (void)
static void gl2psPDFgroupListWriteMainStream (void)
static int gl2psPDFgroupListWriteObjects (int entryoffs)
static int gl2psPDFgroupListWriteShaderResources (void)
static int gl2psPDFgroupListWriteVariableResources (void)
static int gl2psPDFgroupListWriteXObjectResources (void)
static void gl2psPDFgroupObjectInit (GL2PSpdfgroup *gro)
static void gl2psPDFRectHull (GLfloat *xmin, GLfloat *xmax, GLfloat *ymin, GLfloat *ymax, GL2PStriangle *triangles, int cnt)
static void gl2psPDFstacksInit (void)
static const char * gl2psPGFTextAlignment (int align)
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
static int gl2psPrintf (const char *fmt,...)
static void gl2psPrintGzipFooter (void)
static void gl2psPrintGzipHeader (void)
static void gl2psPrintPDFBeginViewport (GLint viewport[4])
static int gl2psPrintPDFCatalog (void)
static int gl2psPrintPDFCompressorType (void)
static int gl2psPrintPDFDataStreamLength (int val)
static GLint gl2psPrintPDFEndViewport (void)
static int gl2psPrintPDFFillColor (GL2PSrgba rgba)
static void gl2psPrintPDFFinalPrimitive (void)
static void gl2psPrintPDFFooter (void)
static int gl2psPrintPDFGSObject (void)
static void gl2psPrintPDFHeader (void)
static int gl2psPrintPDFInfo (void)
static int gl2psPrintPDFLineWidth (GLfloat lw)
static int gl2psPrintPDFOpenPage (void)
static int gl2psPrintPDFPages (void)
static int gl2psPrintPDFPixmap (int obj, int childobj, GL2PSimage *im, int gray)
static int gl2psPrintPDFPixmapStreamData (GL2PSimage *im, int(*action)(unsigned long data, int size), int gray)
static void gl2psPrintPDFPrimitive (void *data)
static int gl2psPrintPDFShader (int obj, GL2PStriangle *triangles, int size, int gray)
static int gl2psPrintPDFShaderExtGS (int obj, int childobj)
static int gl2psPrintPDFShaderMask (int obj, int childobj)
static int gl2psPrintPDFShaderSimpleExtGS (int obj, GLfloat alpha)
static int gl2psPrintPDFShaderStreamData (GL2PStriangle *triangle, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin, int(*action)(unsigned long data, int size), int gray)
static int gl2psPrintPDFShaderStreamDataAlpha (GL2PSvertex *vertex, int(*action)(unsigned long data, int size), int sigbyte)
static int gl2psPrintPDFShaderStreamDataCoord (GL2PSvertex *vertex, int(*action)(unsigned long data, int size), GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin)
static int gl2psPrintPDFShaderStreamDataRGB (GL2PSvertex *vertex, int(*action)(unsigned long data, int size))
static int gl2psPrintPDFStrokeColor (GL2PSrgba rgba)
static int gl2psPrintPDFText (int obj, GL2PSstring *s, int fontnumber)
static void gl2psPrintPGFBeginViewport (GLint viewport[4])
static void gl2psPrintPGFColor (GL2PSrgba rgba)
static void gl2psPrintPGFDash (GLushort pattern, GLint factor)
static GLint gl2psPrintPGFEndViewport (void)
static void gl2psPrintPGFFinalPrimitive (void)
static void gl2psPrintPGFFooter (void)
static void gl2psPrintPGFHeader (void)
static void gl2psPrintPGFPrimitive (void *data)
static void gl2psPrintPostScriptBeginViewport (GLint viewport[4])
static void gl2psPrintPostScriptColor (GL2PSrgba rgba)
static int gl2psPrintPostScriptDash (GLushort pattern, GLint factor, const char *str)
static GLint gl2psPrintPostScriptEndViewport (void)
static void gl2psPrintPostScriptFinalPrimitive (void)
static void gl2psPrintPostScriptFooter (void)
static void gl2psPrintPostScriptHeader (void)
static void gl2psPrintPostScriptImagemap (GLfloat x, GLfloat y, GLsizei width, GLsizei height, const unsigned char *imagemap)
static void gl2psPrintPostScriptPixmap (GLfloat x, GLfloat y, GL2PSimage *im)
static void gl2psPrintPostScriptPrimitive (void *data)
static GLint gl2psPrintPrimitives (void)
static void gl2psPrintSVGBeginViewport (GLint viewport[4])
static void gl2psPrintSVGDash (GLushort pattern, GLint factor)
static GLint gl2psPrintSVGEndViewport (void)
static void gl2psPrintSVGFinalPrimitive (void)
static void gl2psPrintSVGFooter (void)
static void gl2psPrintSVGHeader (void)
static void gl2psPrintSVGPixmap (GLfloat x, GLfloat y, GL2PSimage *pixmap)
static void gl2psPrintSVGPrimitive (void *data)
static void gl2psPrintSVGSmoothTriangle (GL2PSxyz xyz[3], GL2PSrgba rgba[3])
static void gl2psPrintTeXBeginViewport (GLint viewport[4])
static GLint gl2psPrintTeXEndViewport (void)
static void gl2psPrintTeXFinalPrimitive (void)
static void gl2psPrintTeXFooter (void)
static void gl2psPrintTeXHeader (void)
static void gl2psPrintTeXPrimitive (void *data)
static GLfloat gl2psPsca (GLfloat *a, GLfloat *b)
static void gl2psPutPDFImage (GL2PSimage *image, int cnt, GLfloat x, GLfloat y)
static void gl2psPutPDFText (GL2PSstring *text, int cnt, GLfloat x, GLfloat y)
static void gl2psPvec (GLfloat *a, GLfloat *b, GLfloat *c)
static void * gl2psRealloc (void *ptr, size_t size)
static void gl2psRescaleAndOffset (void)
static void gl2psResetPostScriptColor (void)
static GLboolean gl2psSameColor (GL2PSrgba rgba1, GL2PSrgba rgba2)
static GLboolean gl2psSameColorThreshold (int n, GL2PSrgba rgba[], GL2PSrgba threshold)
static GLboolean gl2psSamePosition (GL2PSxyz p1, GL2PSxyz p2)
static void gl2psSetLastColor (GL2PSrgba rgba)
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
static void gl2psSortOutTrianglePDFgroup (GL2PSpdfgroup *gro)
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char *str)
static GLint gl2psSplitPrimitive (GL2PSprimitive *prim, GL2PSplane plane, GL2PSprimitive **front, GL2PSprimitive **back)
static void gl2psSplitPrimitive2D (GL2PSprimitive *prim, GL2PSplane plane, GL2PSprimitive **front, GL2PSprimitive **back)
static GLboolean gl2psSupportedBlendMode (GLenum sfactor, GLenum dfactor)
static void gl2psSVGGetColorString (GL2PSrgba rgba, char str[32])
static void gl2psSVGGetCoordsAndColors (int n, GL2PSvertex *verts, GL2PSxyz *xyz, GL2PSrgba *rgba)
static GLint gl2psTestSplitPrimitive (GL2PSprimitive *prim, GL2PSplane plane)
GL2PSDLL_API GLint gl2psText (const char *str, const char *fontname, GLshort fontsize)
GL2PSDLL_API GLint gl2psTextOpt (const char *str, const char *fontname, GLshort fontsize, GLint alignment, GLfloat angle)
static void gl2psTraverseBspTree (GL2PSbsptree *tree, GL2PSxyz eye, GLfloat epsilon, GLboolean(*compare)(GLfloat f1, GLfloat f2), void(*action)(void *data), int inverse)
static int gl2psTrianglesFirst (const void *a, const void *b)
static GLboolean gl2psVertsSameColor (const GL2PSprimitive *prim)
static int gl2psWriteBigEndian (unsigned long data, int bytes)
static void gl2psWriteByte (unsigned char byte)
Variables
static GL2PScontext * gl2ps = NULL
static GL2PSbackend * gl2psbackends []
static GL2PSbackend gl2psEPS
static GL2PSbackend gl2psPDF
static GL2PSbackend gl2psPGF
static GL2PSbackend gl2psPS
static GL2PSbackend gl2psSVG
static GL2PSbackend gl2psTEX
Define Documentation
#define GL2PS_BEGIN_BLEND_TOKEN 9
Definition at line 110 of file gl2ps.c.
Referenced by gl2psEnable(), and gl2psParseFeedbackBuffer().
#define GL2PS_BEGIN_BOUNDARY_TOKEN 3
Definition at line 104 of file gl2ps.c.
Referenced by gl2psEnable(), and gl2psParseFeedbackBuffer().
#define GL2PS_BEGIN_OFFSET_TOKEN 1
Definition at line 102 of file gl2ps.c.
Referenced by gl2psEnable(), and gl2psParseFeedbackBuffer().
#define GL2PS_BEGIN_STIPPLE_TOKEN 5
Definition at line 106 of file gl2ps.c.
Referenced by gl2psEnable(), and gl2psParseFeedbackBuffer().
#define GL2PS_COINCIDENT 1
Definition at line 89 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psBuildBspTree(), gl2psCheckPrimitive(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
#define GL2PS_DRAW_PIXELS_TOKEN 14
Definition at line 115 of file gl2ps.c.
Referenced by gl2psDrawPixels(), and gl2psParseFeedbackBuffer().
#define GL2PS_DST_BLEND_TOKEN 12
Definition at line 113 of file gl2ps.c.
Referenced by gl2psBlendFunc(), and gl2psParseFeedbackBuffer().
#define GL2PS_END_BLEND_TOKEN 10
Definition at line 111 of file gl2ps.c.
Referenced by gl2psDisable(), and gl2psParseFeedbackBuffer().
#define GL2PS_END_BOUNDARY_TOKEN 4
Definition at line 105 of file gl2ps.c.
Referenced by gl2psDisable(), and gl2psParseFeedbackBuffer().
#define GL2PS_END_OFFSET_TOKEN 2
Definition at line 103 of file gl2ps.c.
Referenced by gl2psDisable(), and gl2psParseFeedbackBuffer().
#define GL2PS_END_STIPPLE_TOKEN 6
Definition at line 107 of file gl2ps.c.
Referenced by gl2psDisable(), and gl2psParseFeedbackBuffer().
#define GL2PS_EPSILON 5.0e-3F
Definition at line 67 of file gl2ps.c.
Referenced by gl2psCheckPoint(), gl2psPrintPrimitives(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
#define GL2PS_IMAGEMAP 7
Definition at line 82 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psAddInImageTree(), gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psGetPlane(), gl2psParseFeedbackBuffer(), and gl2psPrintPostScriptPrimitive().
#define GL2PS_IMAGEMAP_TOKEN 13
Definition at line 114 of file gl2ps.c.
Referenced by gl2psDrawImageMap(), and gl2psParseFeedbackBuffer().
#define GL2PS_IMAGEMAP_VISIBLE 9
Definition at line 84 of file gl2ps.c.
Referenced by gl2psAddInImageTree().
#define GL2PS_IMAGEMAP_WRITTEN 8
Definition at line 83 of file gl2ps.c.
Referenced by gl2psPrintPostScriptPrimitive().
#define GL2PS_IN_BACK_OF 3
Definition at line 91 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psBuildBspTree(), gl2psCheckPrimitive(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
#define GL2PS_IN_FRONT_OF 2
Definition at line 90 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psBuildBspTree(), gl2psCheckPrimitive(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
#define GL2PS_LINE 3
Definition at line 78 of file gl2ps.c.
Referenced by gl2psAddBoundaryInList(), gl2psAddInBspImageTree(), gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psGetPlane(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psRescaleAndOffset().
#define GL2PS_LINE_WIDTH_TOKEN 8
Definition at line 109 of file gl2ps.c.
Referenced by gl2psLineWidth(), and gl2psParseFeedbackBuffer().
#define GL2PS_NO_TYPE -1
Definition at line 75 of file gl2ps.c.
Referenced by gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), and gl2psPDFgroupListInit().
#define GL2PS_PIXMAP 6
Definition at line 81 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psCopyPrimitive(), gl2psDrawPixels(), gl2psFreePrimitive(), gl2psGetPlane(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive().
#define GL2PS_POINT 2
Definition at line 77 of file gl2ps.c.
Referenced by gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psGetPlane(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psSplitPrimitive().
#define GL2PS_POINT_BACK 2
Definition at line 98 of file gl2ps.c.
Referenced by gl2psAddPlanesInBspTreeImage(), gl2psCheckPoint(), gl2psCheckPrimitive(), and gl2psSplitPrimitive2D().
#define GL2PS_POINT_COINCIDENT 0
Definition at line 96 of file gl2ps.c.
Referenced by gl2psAddPlanesInBspTreeImage(), and gl2psCheckPoint().
#define GL2PS_POINT_INFRONT 1
Definition at line 97 of file gl2ps.c.
Referenced by gl2psAddPlanesInBspTreeImage(), gl2psCheckPoint(), gl2psCheckPrimitive(), and gl2psSplitPrimitive2D().
#define GL2PS_POINT_SIZE_TOKEN 7
Definition at line 108 of file gl2ps.c.
Referenced by gl2psParseFeedbackBuffer(), and gl2psPointSize().
#define GL2PS_QUADRANGLE 4
Definition at line 79 of file gl2ps.c.
Referenced by gl2psAddPrimitiveInList(), gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psGetPlane(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive().
#define GL2PS_SPANNING 4
Definition at line 92 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psBuildBspTree(), gl2psCheckPrimitive(), and gl2psSplitPrimitive().
#define GL2PS_SPECIAL 10
Definition at line 85 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psCopyPrimitive(), gl2psFreePrimitive(), gl2psGetPlane(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psSpecial().
#define GL2PS_SRC_BLEND_TOKEN 11
Definition at line 112 of file gl2ps.c.
Referenced by gl2psBlendFunc(), and gl2psParseFeedbackBuffer().
#define GL2PS_TEXT 1
Definition at line 76 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psCopyPrimitive(), gl2psFreePrimitive(), gl2psGetPlane(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), gl2psText(), and gl2psTextOpt().
#define GL2PS_TEXT_TOKEN 15
Definition at line 116 of file gl2ps.c.
Referenced by gl2psAddText(), and gl2psParseFeedbackBuffer().
#define GL2PS_TRIANGLE 5
Definition at line 80 of file gl2ps.c.
Referenced by gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psDivideQuad(), gl2psGetPlane(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psRescaleAndOffset(), and gl2psSortOutTrianglePDFgroup().
#define GL2PS_ZERO (arg) (fabs(arg) < 1.e-20)
Definition at line 71 of file gl2ps.c.
Referenced by gl2psAssignTriangleProperties(), gl2psCutEdge(), gl2psGetNormal(), gl2psGetPlane(), gl2psGetPlaneFromPoints(), gl2psPrintPDFFillColor(), gl2psPrintPDFLineWidth(), gl2psPrintPDFShaderStreamDataCoord(), gl2psPrintPDFStrokeColor(), gl2psRescaleAndOffset(), gl2psSameColor(), and gl2psSamePosition().
#define GL2PS_ZOFFSET 5.0e-2F
Definition at line 69 of file gl2ps.c.
Referenced by gl2psRescaleAndOffset().
#define GL2PS_ZOFFSET_LARGE 20.0F
Definition at line 70 of file gl2ps.c.
Referenced by gl2psRescaleAndOffset().
#define GL2PS_ZSCALE 1000.0F
Definition at line 68 of file gl2ps.c.
Referenced by gl2psPrintPrimitives(), and gl2psRescaleAndOffset().
#define M_PI 3.1415926535897932384626433832795
Definition at line 54 of file gl2ps.c.
Referenced by angle0To2Pi(), CCW(), BiArc::compute_arclength(), BiArc::compute_biarc_params(), EulerSpiral::compute_end_pt(), BiArc::compute_join_theta(), BiArc::compute_other_stuff(), EulerSpiralLookupTable::gamma(), EulerSpiral::get_fresnel_integral(), gl2psPutPDFText(), EulerSpiralLookupTable::k0(), EulerSpiralLookupTable::k1(), and EulerSpiralLookupTable::L().
Typedef Documentation
typedef struct _GL2PSbsptree GL2PSbsptree
Definition at line 142 of file gl2ps.c.
typedef struct _GL2PSbsptree2d GL2PSbsptree2d
Definition at line 130 of file gl2ps.c.
typedef struct _GL2PSimagemap GL2PSimagemap
Definition at line 179 of file gl2ps.c.
typedef GLfloat GL2PSplane[4]
Definition at line 128 of file gl2ps.c.
typedef GLfloat GL2PSxyz[3]
Definition at line 127 of file gl2ps.c.
Enumeration Type Documentation
enum GL2PS_TRIANGLE_PROPERTY
Enumerator:
T_UNDEFINED
T_CONST_COLOR
T_VAR_COLOR
T_ALPHA_1
T_ALPHA_LESS_1
T_VAR_ALPHA
Definition at line 118 of file gl2ps.c.
Function Documentation
static void gl2psAdaptVertexForBlending (GL2PSvertex * v) [static]
Definition at line 931 of file gl2ps.c.
References GL2PScontext::blendfunc, GL2PScontext::blending, GL2PS_NO_BLENDING, GL2PScontext::options, and GL2PSvertex::rgba.
Referenced by gl2psParseFeedbackBuffer().
static void gl2psAddBoundaryInList (GL2PSprimitive * prim, GL2PSlist * list) [static]
Definition at line 2065 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::factor, GL2PS_LINE, gl2psGetIndex(), gl2psListAdd(), gl2psMalloc(), gl2psNorm(), GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSvertex::rgba, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSprimitive::width, and GL2PSvertex::xyz.
Referenced by gl2psBuildPolygonBoundary().
static GLint gl2psAddInBspImageTree (GL2PSprimitive * prim, GL2PSbsptree2d ** tree) [static]
Definition at line 1989 of file gl2ps.c.
References GL2PS_COINCIDENT, GL2PS_IMAGEMAP, GL2PS_IN_BACK_OF, GL2PS_IN_FRONT_OF, GL2PS_LINE, GL2PS_PIXMAP, GL2PS_SPANNING, GL2PS_SPECIAL, GL2PS_TEXT, gl2psAddPlanesInBspTreeImage(), gl2psCheckPrimitive(), gl2psFree(), gl2psSplitPrimitive2D(), GL2PScontext::primitivetoadd, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PScontext::zerosurfacearea.
Referenced by gl2psAddInImageTree().
static void gl2psAddIndex (GLshort * index0, GLshort * index1, GLshort * nb, GLshort i, GLshort j) [static]
Definition at line 1238 of file gl2ps.c.
Referenced by gl2psSplitPrimitive().
static void gl2psAddInImageTree (void * data) [static]
Definition at line 2048 of file gl2ps.c.
References GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSimage::format, GL2PS_IMAGEMAP, GL2PS_IMAGEMAP_VISIBLE, gl2psAddInBspImageTree(), GL2PSprimitive::image, GL2PScontext::imagetree, GL2PScontext::primitivetoadd, and GL2PSprimitive::type.
Referenced by gl2psPrintPrimitives().
static void gl2psAddPlanesInBspTreeImage (GL2PSprimitive * prim, GL2PSbsptree2d ** tree) [static]
Definition at line 1754 of file gl2ps.c.
References _GL2PSbsptree2d::back, _GL2PSbsptree2d::front, GL2PS_POINT_BACK, GL2PS_POINT_COINCIDENT, GL2PS_POINT_INFRONT, gl2psCheckPoint(), gl2psFree(), gl2psGetPlaneFromPoints(), gl2psMalloc(), GL2PSprimitive::numverts, _GL2PSbsptree2d::plane, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psAddInBspImageTree().
static void gl2psAddPolyPrimitive (GLshort type, GLshort numverts, GL2PSvertex * verts, GLint offset, GLushort pattern, GLint factor, GLfloat width, char boundary) [static]
Definition at line 2153 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::factor, gl2psListAdd(), gl2psMalloc(), GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PScontext::primitives, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psParseFeedbackBuffer().
static void gl2psAddPrimitiveInList (GL2PSprimitive * prim, GL2PSlist * list) [static]
Definition at line 1484 of file gl2ps.c.
References GL2PS_QUADRANGLE, gl2psDivideQuad(), gl2psFreePrimitive(), gl2psListAdd(), and GL2PSprimitive::type.
Referenced by gl2psBuildBspTree().
static GLint gl2psAddText (GLint type, const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle) [static]
Definition at line 850 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PScontext::auxprimitives, GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSstring::fontname, GL2PSstring::fontsize, GL2PS_NO_TEXT, GL2PS_SUCCESS, GL2PS_TEXT_TOKEN, GL2PS_UNINITIALIZED, gl2psListAdd(), gl2psMalloc(), GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PScontext::options, GL2PSprimitive::pattern, GL2PSvertex::rgba, GL2PSstring::str, GL2PSprimitive::text, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSprimitive::width, and GL2PSvertex::xyz.
Referenced by gl2psSpecial(), gl2psText(), and gl2psTextOpt().
static void gl2psAssignTriangleProperties (GL2PStriangle * t) [static]
Definition at line 955 of file gl2ps.c.
References GL2PS_ZERO, GL2PStriangle::prop, GL2PSvertex::rgba, T_ALPHA_1, T_ALPHA_LESS_1, T_VAR_ALPHA, T_VAR_COLOR, and GL2PStriangle::vertex.
Referenced by gl2psFillTriangleFromPrimitive().
GL2PSDLL_API GLint gl2psBeginPage (const char * title, const char * producer, GLint viewport[4], GLint format, GLint sort, GLint options, GLint colormode, GLint colorsize, GL2PSrgba * colormap, GLint nr, GLint ng, GLint nb, GLint buffersize, FILE * stream, const char * filename)
Definition at line 5610 of file gl2ps.c.
References GL2PScontext::auxprimitives, GL2PScontext::bgcolor, GL2PScontext::blendfunc, GL2PScontext::blending, GL2PScontext::buffersize, GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PScontext::compress, GL2PScontext::feedback, GL2PScontext::filename, GL2PScontext::format, GL2PS_BSP_SORT, GL2PS_ERROR, GL2PS_NO_SORT, GL2PS_SIMPLE_SORT, GL2PS_SUCCESS, GL2PS_SVG, GL2PS_USE_CURRENT_VIEWPORT, gl2psFree(), gl2psListCreate(), gl2psMalloc(), gl2psMsg(), GL2PScontext::header, GL2PScontext::imagemap_head, GL2PScontext::imagemap_tail, GL2PScontext::imagetree, GL2PScontext::lastfactor, GL2PScontext::lastlinewidth, GL2PScontext::lastpattern, GL2PScontext::lastrgba, GL2PScontext::lastvertex, GL2PScontext::maxbestroot, GL2PScontext::options, GL2PScontext::pdfgrouplist, GL2PScontext::pdfprimlist, GL2PScontext::primitives, GL2PScontext::primitivetoadd, GL2PScontext::producer, GL2PSvertex::rgba, GL2PScontext::sort, GL2PScontext::stream, GL2PScontext::threshold, GL2PScontext::title, GL2PScontext::viewport, GL2PScontext::xreflist, GL2PSvertex::xyz, and GL2PScontext::zerosurfacearea.
Referenced by GUISUMOAbstractView::makeSnapshot().
GL2PSDLL_API GLint gl2psBeginViewport (GLint viewport[4])
Definition at line 5804 of file gl2ps.c.
References GL2PSbackend::beginViewport, GL2PScontext::format, GL2PS_SUCCESS, and GL2PS_UNINITIALIZED.
GL2PSDLL_API GLint gl2psBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 6032 of file gl2ps.c.
References GL2PS_DST_BLEND_TOKEN, GL2PS_SRC_BLEND_TOKEN, GL2PS_SUCCESS, GL2PS_UNINITIALIZED, GL2PS_WARNING, and gl2psSupportedBlendMode().
static void gl2psBuildBspTree (GL2PSbsptree * tree, GL2PSlist * primitives) [static]
Definition at line 1526 of file gl2ps.c.
References _GL2PSbsptree::back, _GL2PSbsptree::front, GL2PS_COINCIDENT, GL2PS_IN_BACK_OF, GL2PS_IN_FRONT_OF, GL2PS_SPANNING, gl2psAddPrimitiveInList(), gl2psFindRoot(), gl2psFreePrimitive(), gl2psGetPlane(), gl2psListCreate(), gl2psListDelete(), gl2psListNbr(), gl2psListPointer(), gl2psListSort(), gl2psMalloc(), gl2psSplitPrimitive(), gl2psTrianglesFirst(), _GL2PSbsptree::plane, and _GL2PSbsptree::primitives.
Referenced by gl2psPrintPrimitives().
static void gl2psBuildPolygonBoundary (GL2PSbsptree * tree) [static]
Definition at line 2133 of file gl2ps.c.
References _GL2PSbsptree::back, GL2PSprimitive::boundary, _GL2PSbsptree::front, gl2psAddBoundaryInList(), gl2psListNbr(), gl2psListPointer(), and _GL2PSbsptree::primitives.
Referenced by gl2psPrintPrimitives().
static GLint gl2psCheckPoint (GL2PSxyz point, GL2PSplane plane) [static]
Definition at line 1744 of file gl2ps.c.
References GL2PS_EPSILON, GL2PS_POINT_BACK, GL2PS_POINT_COINCIDENT, GL2PS_POINT_INFRONT, and gl2psComparePointPlane().
Referenced by gl2psAddPlanesInBspTreeImage(), gl2psCheckPrimitive(), and gl2psSplitPrimitive2D().
static GLint gl2psCheckPrimitive (GL2PSprimitive * prim, GL2PSplane plane) [static]
Definition at line 1858 of file gl2ps.c.
References GL2PS_COINCIDENT, GL2PS_IN_BACK_OF, GL2PS_IN_FRONT_OF, GL2PS_POINT_BACK, GL2PS_POINT_INFRONT, GL2PS_SPANNING, gl2psCheckPoint(), GL2PSprimitive::numverts, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psAddInBspImageTree().
static int gl2psClosePDFDataStream (void) [static]
Definition at line 4071 of file gl2ps.c.
References GL2PScontext::compress, GL2PS_COMPRESS, GL2PS_ERROR, gl2psMsg(), GL2PScontext::options, GL2PScontext::stream, and GL2PScontext::streamlength.
Referenced by gl2psPrintPDFFooter().
static int gl2psCompareDepth (const void * a, const void * b) [static]
Definition at line 1372 of file gl2ps.c.
References GL2PSprimitive::numverts, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psPrintPrimitives().
static GLfloat gl2psComparePointPlane (GL2PSxyz point, GL2PSplane plane) [static]
Definition at line 1061 of file gl2ps.c.
Referenced by gl2psCheckPoint(), gl2psCutEdge(), gl2psSplitPrimitive(), gl2psTestSplitPrimitive(), and gl2psTraverseBspTree().
static void gl2psComputeTightBoundingBox (void * data) [static]
Definition at line 5511 of file gl2ps.c.
References GL2PSprimitive::numverts, GL2PSprimitive::verts, GL2PScontext::viewport, and GL2PSvertex::xyz.
Referenced by gl2psPrintPrimitives().
static GL2PSimage* gl2psCopyPixmap (GL2PSimage * im) [static]
Definition at line 747 of file gl2ps.c.
References GL2PSimage::format, gl2psMalloc(), GL2PSimage::height, GL2PSimage::pixels, GL2PSimage::type, GL2PSimage::width, GL2PSimage::zoom_x, and GL2PSimage::zoom_y.
Referenced by gl2psCopyPrimitive().
static GL2PSprimitive* gl2psCopyPrimitive (GL2PSprimitive * p) [static]
Definition at line 1009 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PS_ERROR, GL2PS_PIXMAP, GL2PS_SPECIAL, GL2PS_TEXT, gl2psCopyPixmap(), gl2psCopyText(), gl2psMalloc(), gl2psMsg(), GL2PSprimitive::image, GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSprimitive::text, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psPrintPDFPrimitive().
static GL2PSstring* gl2psCopyText (GL2PSstring * t) [static]
Definition at line 895 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PSstring::fontname, GL2PSstring::fontsize, gl2psMalloc(), and GL2PSstring::str.
Referenced by gl2psCopyPrimitive().
static void gl2psCreateSplitPrimitive (GL2PSprimitive * parent, GL2PSplane plane, GL2PSprimitive * child, GLshort numverts, GLshort * index0, GLshort * index1) [static]
Definition at line 1194 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PS_IMAGEMAP, GL2PS_LINE, GL2PS_NO_TYPE, GL2PS_POINT, GL2PS_QUADRANGLE, GL2PS_TRIANGLE, GL2PS_WARNING, gl2psCutEdge(), gl2psMalloc(), gl2psMsg(), GL2PSprimitive::image, GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psSplitPrimitive().
static GL2PSprimitive* gl2psCreateSplitPrimitive2D (GL2PSprimitive * parent, GLshort numverts, GL2PSvertex * vertx) [static]
Definition at line 1873 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PS_IMAGEMAP, GL2PS_LINE, GL2PS_NO_TYPE, GL2PS_POINT, GL2PS_QUADRANGLE, GL2PS_TRIANGLE, gl2psMalloc(), GL2PSprimitive::image, GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psSplitPrimitive2D().
static void gl2psCutEdge (GL2PSvertex * a, GL2PSvertex * b, GL2PSplane plane, GL2PSvertex * c) [static]
Definition at line 1169 of file gl2ps.c.
References GL2PS_ZERO, gl2psComparePointPlane(), gl2psPsca(), GL2PSvertex::rgba, and GL2PSvertex::xyz.
Referenced by gl2psCreateSplitPrimitive(), and gl2psSplitPrimitive2D().
GL2PSDLL_API GLint gl2psDisable (GLint mode)
Definition at line 5987 of file gl2ps.c.
References GL2PS_BLEND, GL2PS_END_BLEND_TOKEN, GL2PS_END_BOUNDARY_TOKEN, GL2PS_END_OFFSET_TOKEN, GL2PS_END_STIPPLE_TOKEN, GL2PS_LINE_STIPPLE, GL2PS_POLYGON_BOUNDARY, GL2PS_POLYGON_OFFSET_FILL, GL2PS_SUCCESS, GL2PS_UNINITIALIZED, GL2PS_WARNING, and gl2psMsg().
static void gl2psDivideQuad (GL2PSprimitive * quad, GL2PSprimitive ** t1, GL2PSprimitive ** t2) [static]
Definition at line 1348 of file gl2ps.c.
References GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::factor, GL2PS_TRIANGLE, gl2psMalloc(), GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psAddPrimitiveInList().
GL2PSDLL_API GLint gl2psDrawImageMap (GLsizei width, GLsizei height, const GLfloat position[3], const unsigned char * imagemap)
Definition at line 5929 of file gl2ps.c.
References GL2PS_ERROR, GL2PS_IMAGEMAP_TOKEN, GL2PS_SUCCESS, and GL2PS_UNINITIALIZED.
GL2PSDLL_API GLint gl2psDrawPixels (GLsizei width, GLsizei height, GLint xorig, GLint yorig, GLenum format, GLenum type, const void * pixels)
Definition at line 5843 of file gl2ps.c.
References GL2PScontext::auxprimitives, GL2PScontext::blending, GL2PSprimitive::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSimage::format, GL2PS_DRAW_PIXELS_TOKEN, GL2PS_ERROR, GL2PS_NO_BLENDING, GL2PS_NO_PIXMAP, GL2PS_PIXMAP, GL2PS_SUCCESS, GL2PS_UNINITIALIZED, gl2psListAdd(), gl2psMalloc(), gl2psMsg(), GL2PSimage::height, GL2PSprimitive::image, GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PScontext::options, GL2PSprimitive::pattern, GL2PSimage::pixels, GL2PSvertex::rgba, GL2PSimage::type, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSimage::width, GL2PSprimitive::width, GL2PSvertex::xyz, GL2PSimage::zoom_x, and GL2PSimage::zoom_y.
GL2PSDLL_API GLint gl2psEnable (GLint mode)
Definition at line 5954 of file gl2ps.c.
References GL2PS_BEGIN_BLEND_TOKEN, GL2PS_BEGIN_BOUNDARY_TOKEN, GL2PS_BEGIN_OFFSET_TOKEN, GL2PS_BEGIN_STIPPLE_TOKEN, GL2PS_BLEND, GL2PS_LINE_STIPPLE, GL2PS_POLYGON_BOUNDARY, GL2PS_POLYGON_OFFSET_FILL, GL2PS_SUCCESS, GL2PS_UNINITIALIZED, GL2PS_WARNING, gl2psMsg(), and GL2PScontext::offset.
GL2PSDLL_API GLint gl2psEndPage (void)
Definition at line 5777 of file gl2ps.c.
References GL2PScontext::auxprimitives, GL2PScontext::colormap, GL2PScontext::feedback, GL2PScontext::filename, GL2PScontext::format, GL2PS_OVERFLOW, GL2PS_UNINITIALIZED, gl2psFree(), gl2psFreeImagemap(), gl2psListDelete(), gl2psPrintPrimitives(), GL2PScontext::imagemap_head, GL2PScontext::primitives, GL2PSbackend::printFooter, GL2PScontext::producer, GL2PScontext::stream, and GL2PScontext::title.
Referenced by GUISUMOAbstractView::makeSnapshot().
static void gl2psEndPostScriptLine (void) [static]
Definition at line 2895 of file gl2ps.c.
References gl2psPrintf(), GL2PScontext::lastvertex, GL2PSvertex::rgba, and GL2PSvertex::xyz.
Referenced by gl2psPrintPostScriptFinalPrimitive(), and gl2psPrintPostScriptPrimitive().
static void gl2psEndSVGLine (void) [static]
Definition at line 4998 of file gl2ps.c.
References gl2psPrintf(), GL2PScontext::lastvertex, GL2PSvertex::rgba, GL2PScontext::viewport, and GL2PSvertex::xyz.
Referenced by gl2psPrintSVGFinalPrimitive(), and gl2psPrintSVGPrimitive().
GL2PSDLL_API GLint gl2psEndViewport (void)
Definition at line 5813 of file gl2ps.c.
References GL2PSbackend::endViewport, GL2PScontext::format, GL2PS_UNINITIALIZED, and GL2PScontext::lastlinewidth.
static void gl2psFillTriangleFromPrimitive (GL2PStriangle * t, GL2PSprimitive * p, GLboolean assignprops) [static]
Definition at line 988 of file gl2ps.c.
References gl2psAssignTriangleProperties(), GL2PStriangle::vertex, and GL2PSprimitive::verts.
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), and gl2psSortOutTrianglePDFgroup().
static GLint gl2psFindRoot (GL2PSlist * primitives, GL2PSprimitive ** root) [static]
Definition at line 1412 of file gl2ps.c.
References GL2PS_BEST_ROOT, GL2PS_ERROR, gl2psGetPlane(), gl2psListNbr(), gl2psListPointer(), gl2psMsg(), gl2psTestSplitPrimitive(), GL2PScontext::maxbestroot, and GL2PScontext::options.
Referenced by gl2psBuildBspTree().
static void gl2psFree (void * ptr) [static]
Definition at line 324 of file gl2ps.c.
Referenced by gl2psAddInBspImageTree(), gl2psAddPlanesInBspTreeImage(), gl2psBeginPage(), gl2psEndPage(), gl2psFreeBspImageTree(), gl2psFreeBspTree(), gl2psFreeImagemap(), gl2psFreePixmap(), gl2psFreePrimitive(), gl2psFreeText(), gl2psListDelete(), gl2psPDFgroupListWriteObjects(), gl2psPrintGzipFooter(), gl2psPrintPDFFooter(), and gl2psSplitPrimitive2D().
static void gl2psFreeBspImageTree (GL2PSbsptree2d ** tree) [static]
Definition at line 1734 of file gl2ps.c.
References gl2psFree().
Referenced by gl2psPrintPrimitives().
static void gl2psFreeBspTree (GL2PSbsptree ** tree) [static]
Definition at line 1500 of file gl2ps.c.
References gl2psFree(), gl2psFreePrimitive(), gl2psListAction(), and gl2psListDelete().
Referenced by gl2psPrintPrimitives().
static void gl2psFreeImagemap (GL2PSimagemap * list) [static]
Definition at line 1457 of file gl2ps.c.
References gl2psFree(), _GL2PSimagemap::image, _GL2PSimagemap::next, and GL2PSimage::pixels.
Referenced by gl2psEndPage().
static void gl2psFreePixmap (GL2PSimage * im) [static]
Definition at line 775 of file gl2ps.c.
References gl2psFree(), and GL2PSimage::pixels.
Referenced by gl2psFreePrimitive().
static void gl2psFreePrimitive (void * data) [static]
Definition at line 1469 of file gl2ps.c.
References GL2PSprimitive::data, GL2PS_PIXMAP, GL2PS_SPECIAL, GL2PS_TEXT, gl2psFree(), gl2psFreePixmap(), gl2psFreeText(), GL2PSprimitive::image, GL2PSprimitive::text, GL2PSprimitive::type, and GL2PSprimitive::verts.
Referenced by gl2psAddPrimitiveInList(), gl2psBuildBspTree(), gl2psFreeBspTree(), gl2psPrintPDFFooter(), and gl2psPrintPrimitives().
static void gl2psFreeText (GL2PSstring * text) [static]
Definition at line 909 of file gl2ps.c.
References GL2PSstring::fontname, gl2psFree(), and GL2PSstring::str.
Referenced by gl2psFreePrimitive().
GL2PSDLL_API const char* gl2psGetFileExtension (GLint format)
Definition at line 6068 of file gl2ps.c.
References GL2PSbackend::file_extension.
GL2PSDLL_API const char* gl2psGetFormatDescription (GLint format)
Definition at line 6076 of file gl2ps.c.
References GL2PSbackend::description.
static GLshort gl2psGetIndex (GLshort i, GLshort num) [static]
Definition at line 1252 of file gl2ps.c.
Referenced by gl2psAddBoundaryInList(), gl2psSplitPrimitive(), and gl2psTestSplitPrimitive().
static void gl2psGetNormal (GLfloat * a, GLfloat * b, GLfloat * c) [static]
Definition at line 1086 of file gl2ps.c.
References GL2PS_ZERO, gl2psNorm(), and gl2psPvec().
Referenced by gl2psGetPlane().
GL2PSDLL_API GLint gl2psGetOptions (GLint * options)
Definition at line 6056 of file gl2ps.c.
References GL2PS_SUCCESS, GL2PS_UNINITIALIZED, and GL2PScontext::options.
static void gl2psGetPlane (GL2PSprimitive * prim, GL2PSplane plane) [static]
Definition at line 1105 of file gl2ps.c.
References GL2PS_ERROR, GL2PS_IMAGEMAP, GL2PS_LINE, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_QUADRANGLE, GL2PS_SPECIAL, GL2PS_TEXT, GL2PS_TRIANGLE, GL2PS_ZERO, gl2psGetNormal(), gl2psMsg(), GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psBuildBspTree(), and gl2psFindRoot().
static GLint gl2psGetPlaneFromPoints (GL2PSxyz a, GL2PSxyz b, GL2PSplane plane) [static]
Definition at line 1712 of file gl2ps.c.
References GL2PS_ZERO.
Referenced by gl2psAddPlanesInBspTreeImage().
static GLfloat gl2psGetRGB (GL2PSimage * im, GLuint x, GLuint y, GLfloat * red, GLfloat * green, GLfloat * blue) [static]
Definition at line 719 of file gl2ps.c.
References GL2PSimage::format, GL2PSimage::height, GL2PSimage::pixels, and GL2PSimage::width.
Referenced by gl2psPrintPDFPixmapStreamData(), and gl2psPrintPostScriptPixmap().
static GLint gl2psGetVertex (GL2PSvertex * v, GLfloat * p) [static]
Definition at line 2178 of file gl2ps.c.
References GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PSvertex::rgba, and GL2PSvertex::xyz.
Referenced by gl2psParseFeedbackBuffer().
static GLboolean gl2psGreater (GLfloat f1, GLfloat f2) [static]
Definition at line 1514 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
static void gl2psInitTriangle (GL2PStriangle * t) [static]
Definition at line 998 of file gl2ps.c.
References GL2PStriangle::prop, T_UNDEFINED, and GL2PStriangle::vertex.
Referenced by gl2psPDFgroupListInit().
static GLboolean gl2psLess (GLfloat f1, GLfloat f2) [static]
Definition at line 1520 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
GL2PSDLL_API GLint gl2psLineWidth (GLfloat value)
Definition at line 6022 of file gl2ps.c.
References GL2PS_LINE_WIDTH_TOKEN, GL2PS_SUCCESS, and GL2PS_UNINITIALIZED.
static void gl2psListAction (GL2PSlist * list, void(*)(void *data) action) [static]
Definition at line 599 of file gl2ps.c.
References gl2psListNbr(), and gl2psListPointer().
Referenced by gl2psFreeBspTree(), gl2psPrintPDFFooter(), gl2psPrintPrimitives(), and gl2psTraverseBspTree().
static void gl2psListActionInverse (GL2PSlist * list, void(*)(void *data) action) [static]
Definition at line 608 of file gl2ps.c.
References gl2psListNbr(), and gl2psListPointer().
Referenced by gl2psPrintPrimitives(), and gl2psTraverseBspTree().
static void gl2psListAdd (GL2PSlist * list, void * data) [static]
Definition at line 560 of file gl2ps.c.
References GL2PSlist::array, GL2PS_ERROR, gl2psListRealloc(), gl2psMsg(), GL2PSlist::n, and GL2PSlist::size.
Referenced by gl2psAddBoundaryInList(), gl2psAddPolyPrimitive(), gl2psAddPrimitiveInList(), gl2psAddText(), gl2psDrawPixels(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), and gl2psPrintPDFPrimitive().
static GL2PSlist* gl2psListCreate (GLint n, GLint incr, GLint size) [static]
Definition at line 531 of file gl2ps.c.
References GL2PSlist::array, gl2psListRealloc(), gl2psMalloc(), GL2PSlist::incr, GL2PSlist::n, GL2PSlist::nmax, and GL2PSlist::size.
Referenced by gl2psBeginPage(), gl2psBuildBspTree(), gl2psPDFgroupListInit(), gl2psPrintPDFHeader(), gl2psPrintPrimitives(), and gl2psPrintSVGPixmap().
static void gl2psListDelete (GL2PSlist * list) [static]
Definition at line 553 of file gl2ps.c.
References GL2PSlist::array, and gl2psFree().
Referenced by gl2psBuildBspTree(), gl2psEndPage(), gl2psFreeBspTree(), gl2psPDFgroupListDelete(), gl2psPrintPDFFooter(), and gl2psPrintSVGPixmap().
static int gl2psListNbr (GL2PSlist * list) [static]
Definition at line 571 of file gl2ps.c.
References GL2PSlist::n.
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), gl2psFindRoot(), gl2psListAction(), gl2psListActionInverse(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPrimitives(), gl2psPrintSVGPixmap(), gl2psRescaleAndOffset(), and gl2psSortOutTrianglePDFgroup().
static void* gl2psListPointer (GL2PSlist * list, GLint index) [static]
Definition at line 578 of file gl2ps.c.
References GL2PSlist::array, GL2PS_ERROR, gl2psMsg(), GL2PSlist::n, and GL2PSlist::size.
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), gl2psFindRoot(), gl2psListAction(), gl2psListActionInverse(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteXObjectResources(), gl2psRescaleAndOffset(), and gl2psSortOutTrianglePDFgroup().
static void gl2psListRealloc (GL2PSlist * list, GLint n) [static]
Definition at line 511 of file gl2ps.c.
References GL2PSlist::array, GL2PS_ERROR, gl2psMalloc(), gl2psMsg(), gl2psRealloc(), GL2PSlist::incr, GL2PSlist::nmax, and GL2PSlist::size.
Referenced by gl2psListAdd(), and gl2psListCreate().
static void gl2psListReset (GL2PSlist * list) [static]
Definition at line 547 of file gl2ps.c.
References GL2PSlist::n.
Referenced by gl2psParseFeedbackBuffer(), and gl2psPrintPrimitives().
static void gl2psListSort (GL2PSlist * list, int(*)(const void *a, const void *b) fcmp) [static]
Definition at line 591 of file gl2ps.c.
References GL2PSlist::array, GL2PSlist::n, and GL2PSlist::size.
Referenced by gl2psBuildBspTree(), and gl2psPrintPrimitives().
static void* gl2psMalloc (size_t size) [static]
Definition at line 298 of file gl2ps.c.
References GL2PS_ERROR, and gl2psMsg().
Referenced by gl2psAddBoundaryInList(), gl2psAddPlanesInBspTreeImage(), gl2psAddPolyPrimitive(), gl2psAddText(), gl2psBeginPage(), gl2psBuildBspTree(), gl2psCopyPixmap(), gl2psCopyPrimitive(), gl2psCopyText(), gl2psCreateSplitPrimitive(), gl2psCreateSplitPrimitive2D(), gl2psDivideQuad(), gl2psDrawPixels(), gl2psListCreate(), gl2psListRealloc(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListWriteObjects(), gl2psPrintPDFHeader(), gl2psPrintPrimitives(), and gl2psSplitPrimitive().
static void gl2psMsg (GLint level, const char * fmt, ...) [static]
Definition at line 280 of file gl2ps.c.
References GL2PS_ERROR, GL2PS_INFO, GL2PS_SILENT, GL2PS_WARNING, and GL2PScontext::options.
Referenced by gl2psBeginPage(), gl2psClosePDFDataStream(), gl2psCopyPrimitive(), gl2psCreateSplitPrimitive(), gl2psDisable(), gl2psDrawPixels(), gl2psEnable(), gl2psFindRoot(), gl2psGetPlane(), gl2psListAdd(), gl2psListPointer(), gl2psListRealloc(), gl2psMalloc(), gl2psParseFeedbackBuffer(), gl2psPrintGzipFooter(), gl2psPrintPostScriptPrimitive(), gl2psPrintPrimitives(), gl2psPrintSVGPixmap(), gl2psPrintSVGPrimitive(), and gl2psRealloc().
static GLfloat gl2psNorm (GLfloat * a) [static]
Definition at line 1081 of file gl2ps.c.
Referenced by gl2psAddBoundaryInList(), and gl2psGetNormal().
static int gl2psOpenPDFDataStream (void) [static]
Definition at line 3990 of file gl2ps.c.
References gl2psPrintPDFCompressorType(), and GL2PScontext::stream.
Referenced by gl2psPrintPDFHeader().
static int gl2psOpenPDFDataStreamWritePreface (void) [static]
Definition at line 4007 of file gl2ps.c.
References GL2PScontext::bgcolor, GL2PS_DRAW_BACKGROUND, gl2psPrintf(), gl2psPrintPDFFillColor(), GL2PScontext::options, and GL2PScontext::viewport.
Referenced by gl2psPrintPDFHeader().
static void gl2psParseFeedbackBuffer (GLint used) [static]
Definition at line 2203 of file gl2ps.c.
References GL2PScontext::auxprimitives, GL2PScontext::blendfunc, GL2PScontext::blending, GL2PSprimitive::boundary, GL2PScontext::boundary, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PScontext::feedback, flag, GL2PSimage::format, GL2PS_BEGIN_BLEND_TOKEN, GL2PS_BEGIN_BOUNDARY_TOKEN, GL2PS_BEGIN_OFFSET_TOKEN, GL2PS_BEGIN_STIPPLE_TOKEN, GL2PS_DRAW_PIXELS_TOKEN, GL2PS_DST_BLEND_TOKEN, GL2PS_END_BLEND_TOKEN, GL2PS_END_BOUNDARY_TOKEN, GL2PS_END_OFFSET_TOKEN, GL2PS_END_STIPPLE_TOKEN, GL2PS_ERROR, GL2PS_IMAGEMAP, GL2PS_IMAGEMAP_TOKEN, GL2PS_LINE, GL2PS_LINE_WIDTH_TOKEN, GL2PS_POINT, GL2PS_POINT_SIZE_TOKEN, GL2PS_SRC_BLEND_TOKEN, GL2PS_TEXT_TOKEN, GL2PS_TRIANGLE, GL2PS_WARNING, gl2psAdaptVertexForBlending(), gl2psAddPolyPrimitive(), gl2psGetVertex(), gl2psListAdd(), gl2psListNbr(), gl2psListPointer(), gl2psListReset(), gl2psMalloc(), gl2psMsg(), GL2PSimage::height, GL2PSprimitive::image, _GL2PSimagemap::image, GL2PScontext::imagemap_head, GL2PScontext::imagemap_tail, _GL2PSimagemap::next, GL2PSprimitive::numverts, GL2PSprimitive::offset, GL2PSprimitive::pattern, GL2PSimage::pixels, GL2PScontext::primitives, GL2PSvertex::rgba, GL2PSimage::type, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSimage::width, GL2PSprimitive::width, GL2PSvertex::xyz, GL2PSimage::zoom_x, and GL2PSimage::zoom_y.
Referenced by gl2psPrintPrimitives().
static void gl2psParseStipplePattern (GLushort pattern, GLint factor, int * nb, int array[10]) [static]
Definition at line 2907 of file gl2ps.c.
Referenced by gl2psPrintPGFDash(), gl2psPrintPostScriptDash(), and gl2psPrintSVGDash().
static void gl2psPDFgroupListDelete (void) [static]
Definition at line 3905 of file gl2ps.c.
References gl2psListDelete(), gl2psListNbr(), gl2psListPointer(), GL2PScontext::pdfgrouplist, and GL2PSpdfgroup::ptrlist.
Referenced by gl2psPrintPDFFooter().
static void gl2psPDFgroupListInit (void) [static]
Definition at line 3468 of file gl2ps.c.
References GL2PSprimitive::factor, GL2PScontext::font_stack, GL2PSpdfgroup::fontno, GL2PS_LINE, GL2PS_NO_TYPE, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_TEXT, GL2PS_TRIANGLE, gl2psFillTriangleFromPrimitive(), gl2psInitTriangle(), gl2psListAdd(), gl2psListCreate(), gl2psListNbr(), gl2psListPointer(), gl2psPDFgroupObjectInit(), gl2psSameColor(), GL2PScontext::im_stack, GL2PSpdfgroup::imno, GL2PSprimitive::pattern, GL2PScontext::pdfgrouplist, GL2PScontext::pdfprimlist, GL2PStriangle::prop, GL2PSpdfgroup::ptrlist, GL2PSvertex::rgba, T_ALPHA_1, T_CONST_COLOR, GL2PSprimitive::type, GL2PStriangle::vertex, GL2PSprimitive::verts, and GL2PSprimitive::width.
Referenced by gl2psPrintPDFFooter().
static int gl2psPDFgroupListWriteFontResources (void) [static]
Definition at line 3885 of file gl2ps.c.
References GL2PSpdfgroup::fontno, GL2PSpdfgroup::fontobjno, gl2psListNbr(), gl2psListPointer(), GL2PScontext::objects_stack, GL2PScontext::pdfgrouplist, and GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteVariableResources().
static int gl2psPDFgroupListWriteGStateResources (void) [static]
Definition at line 3806 of file gl2ps.c.
References gl2psListNbr(), gl2psListPointer(), GL2PSpdfgroup::gsno, GL2PSpdfgroup::gsobjno, GL2PScontext::pdfgrouplist, and GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteVariableResources().
static void gl2psPDFgroupListWriteMainStream (void) [static]
Definition at line 3618 of file gl2ps.c.
References GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSpdfgroup::fontno, GL2PS_LINE, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_TEXT, GL2PS_TRIANGLE, gl2psFillTriangleFromPrimitive(), gl2psListNbr(), gl2psListPointer(), gl2psPrintf(), gl2psPrintPDFFillColor(), gl2psPrintPDFLineWidth(), gl2psPrintPDFStrokeColor(), gl2psPrintPostScriptDash(), gl2psPutPDFImage(), gl2psPutPDFText(), gl2psSamePosition(), gl2psSortOutTrianglePDFgroup(), GL2PSpdfgroup::gsno, GL2PSprimitive::image, GL2PSpdfgroup::imno, GL2PSprimitive::pattern, GL2PScontext::pdfgrouplist, GL2PStriangle::prop, GL2PSpdfgroup::ptrlist, GL2PSvertex::rgba, GL2PSpdfgroup::shno, GL2PScontext::streamlength, T_ALPHA_1, T_ALPHA_LESS_1, T_CONST_COLOR, T_VAR_ALPHA, T_VAR_COLOR, GL2PSprimitive::text, GL2PSpdfgroup::trgroupno, GL2PSprimitive::type, GL2PStriangle::vertex, GL2PSprimitive::verts, GL2PSprimitive::width, and GL2PSvertex::xyz.
Referenced by gl2psPrintPDFFooter().
static int gl2psPDFgroupListWriteObjects (int entryoffs) [static]
Definition at line 4622 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSprimitive::data, GL2PSpdfgroup::fontno, GL2PSpdfgroup::fontobjno, GL2PSimage::format, GL2PS_LINE, GL2PS_PDF, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_SPECIAL, GL2PS_TEXT, GL2PS_TRIANGLE, gl2psFillTriangleFromPrimitive(), gl2psFree(), gl2psListNbr(), gl2psListPointer(), gl2psMalloc(), gl2psPrintPDFPixmap(), gl2psPrintPDFShader(), gl2psPrintPDFShaderExtGS(), gl2psPrintPDFShaderMask(), gl2psPrintPDFShaderSimpleExtGS(), gl2psPrintPDFText(), GL2PSpdfgroup::gsobjno, GL2PSprimitive::image, GL2PSpdfgroup::imobjno, GL2PSpdfgroup::maskshno, GL2PSpdfgroup::maskshobjno, GL2PScontext::pdfgrouplist, GL2PSpdfgroup::ptrlist, GL2PSvertex::rgba, GL2PSpdfgroup::shobjno, GL2PSstring::str, GL2PScontext::stream, T_ALPHA_LESS_1, T_VAR_ALPHA, T_VAR_COLOR, GL2PSprimitive::text, GL2PSpdfgroup::trgroupobjno, GL2PSprimitive::type, GL2PStriangle::vertex, and GL2PScontext::xreflist.
Referenced by gl2psPrintPDFFooter().
static int gl2psPDFgroupListWriteShaderResources (void) [static]
Definition at line 3827 of file gl2ps.c.
References gl2psListNbr(), gl2psListPointer(), GL2PSpdfgroup::maskshno, GL2PSpdfgroup::maskshobjno, GL2PScontext::pdfgrouplist, GL2PSpdfgroup::shno, GL2PSpdfgroup::shobjno, and GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteVariableResources().
static int gl2psPDFgroupListWriteVariableResources (void) [static]
Definition at line 4135 of file gl2ps.c.
References gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupListWriteXObjectResources(), and GL2PScontext::stream.
Referenced by gl2psPrintPDFFooter().
static int gl2psPDFgroupListWriteXObjectResources (void) [static]
Definition at line 3849 of file gl2ps.c.
References GL2PSprimitive::data, GL2PSimage::format, GL2PS_PIXMAP, GL2PS_TRIANGLE, gl2psListNbr(), gl2psListPointer(), GL2PSprimitive::image, GL2PSpdfgroup::imno, GL2PSpdfgroup::imobjno, GL2PScontext::objects_stack, GL2PScontext::pdfgrouplist, GL2PSpdfgroup::ptrlist, GL2PScontext::stream, GL2PSpdfgroup::trgroupno, GL2PSpdfgroup::trgroupobjno, and GL2PSprimitive::type.
Referenced by gl2psPDFgroupListWriteVariableResources().
static void gl2psPDFgroupObjectInit (GL2PSpdfgroup * gro) [static]
Definition at line 3455 of file gl2ps.c.
References GL2PSpdfgroup::fontno, GL2PSpdfgroup::fontobjno, GL2PSpdfgroup::gsno, GL2PSpdfgroup::gsobjno, GL2PSpdfgroup::imno, GL2PSpdfgroup::imobjno, GL2PSpdfgroup::maskshno, GL2PSpdfgroup::maskshobjno, GL2PSpdfgroup::ptrlist, GL2PSpdfgroup::shno, GL2PSpdfgroup::shobjno, GL2PSpdfgroup::trgroupno, and GL2PSpdfgroup::trgroupobjno.
Referenced by gl2psPDFgroupListInit().
static void gl2psPDFRectHull (GLfloat * xmin, GLfloat * xmax, GLfloat * ymin, GLfloat * ymax, GL2PStriangle * triangles, int cnt) [static]
Definition at line 4303 of file gl2ps.c.
References GL2PStriangle::vertex, and GL2PSvertex::xyz.
Referenced by gl2psPrintPDFShader().
static void gl2psPDFstacksInit (void) [static]
Definition at line 3444 of file gl2ps.c.
References GL2PScontext::extgs_stack, GL2PScontext::font_stack, GL2PScontext::im_stack, GL2PScontext::mshader_stack, GL2PScontext::objects_stack, GL2PScontext::shader_stack, and GL2PScontext::trgroupobjects_stack.
Referenced by gl2psPrintPDFHeader().
static const char* gl2psPGFTextAlignment (int align) [static]
Definition at line 5332 of file gl2ps.c.
References GL2PS_TEXT_B, GL2PS_TEXT_BL, GL2PS_TEXT_BR, GL2PS_TEXT_C, GL2PS_TEXT_CL, GL2PS_TEXT_CR, GL2PS_TEXT_T, GL2PS_TEXT_TL, and GL2PS_TEXT_TR.
Referenced by gl2psPrintPGFPrimitive().
GL2PSDLL_API GLint gl2psPointSize (GLfloat value)
Definition at line 6012 of file gl2ps.c.
References GL2PS_POINT_SIZE_TOKEN, GL2PS_SUCCESS, and GL2PS_UNINITIALIZED.
static int gl2psPrintf (const char * fmt, ...) [static]
Definition at line 423 of file gl2ps.c.
References GL2PScontext::compress, GL2PS_COMPRESS, GL2PScontext::options, and GL2PScontext::stream.
Referenced by gl2psEndPostScriptLine(), gl2psEndSVGLine(), gl2psOpenPDFDataStreamWritePreface(), gl2psPDFgroupListWriteMainStream(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFEndViewport(), gl2psPrintPDFFillColor(), gl2psPrintPDFLineWidth(), gl2psPrintPDFStrokeColor(), gl2psPrintPostScriptBeginViewport(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptDash(), gl2psPrintPostScriptEndViewport(), gl2psPrintPostScriptFooter(), gl2psPrintPostScriptHeader(), gl2psPrintPostScriptImagemap(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGBeginViewport(), gl2psPrintSVGDash(), gl2psPrintSVGEndViewport(), gl2psPrintSVGFooter(), gl2psPrintSVGHeader(), gl2psPrintSVGPixmap(), gl2psPrintSVGPrimitive(), gl2psPrintSVGSmoothTriangle(), gl2psPutPDFImage(), gl2psPutPDFText(), and gl2psWriteByte().
static void gl2psPrintGzipFooter (void) [static]
Definition at line 469 of file gl2ps.c.
References GL2PScontext::compress, GL2PS_COMPRESS, GL2PS_ERROR, gl2psFree(), gl2psMsg(), GL2PScontext::options, and GL2PScontext::stream.
Referenced by gl2psPrintPostScriptFooter(), and gl2psPrintSVGFooter().
static void gl2psPrintGzipHeader (void) [static]
Definition at line 451 of file gl2ps.c.
References GL2PS_COMPRESS, GL2PScontext::options, and GL2PScontext::stream.
Referenced by gl2psPrintPostScriptHeader(), and gl2psPrintSVGHeader().
static void gl2psPrintPDFBeginViewport (GLint viewport[4]) [static]
Definition at line 4763 of file gl2ps.c.
References GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PS_DRAW_BACKGROUND, gl2psPrintf(), gl2psPrintPDFFillColor(), gl2psPrintPDFHeader(), GL2PScontext::header, GL2PScontext::options, and GL2PScontext::streamlength.
static int gl2psPrintPDFCatalog (void) [static]
Definition at line 3965 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPrintPDFHeader().
static int gl2psPrintPDFCompressorType (void) [static]
Definition at line 3354 of file gl2ps.c.
References GL2PS_COMPRESS, GL2PScontext::options, and GL2PScontext::stream.
Referenced by gl2psOpenPDFDataStream(), gl2psPrintPDFPixmap(), and gl2psPrintPDFShader().
static int gl2psPrintPDFDataStreamLength (int val) [static]
Definition at line 4096 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPrintPDFFooter().
static GLint gl2psPrintPDFEndViewport (void) [static]
Definition at line 4806 of file gl2ps.c.
References gl2psPrintf(), gl2psPrintPrimitives(), and GL2PScontext::streamlength.
static int gl2psPrintPDFFillColor (GL2PSrgba rgba) [static]
Definition at line 3381 of file gl2ps.c.
References GL2PS_ZERO, and gl2psPrintf().
Referenced by gl2psOpenPDFDataStreamWritePreface(), gl2psPDFgroupListWriteMainStream(), and gl2psPrintPDFBeginViewport().
static void gl2psPrintPDFFinalPrimitive (void) [static]
Definition at line 4815 of file gl2ps.c.
static void gl2psPrintPDFFooter (void) [static]
Definition at line 4698 of file gl2ps.c.
References GL2PScontext::compress, GL2PS_COMPRESS, gl2psClosePDFDataStream(), gl2psFree(), gl2psFreePrimitive(), gl2psListAction(), gl2psListDelete(), gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteVariableResources(), gl2psPrintPDFDataStreamLength(), gl2psPrintPDFGSObject(), gl2psPrintPDFOpenPage(), gl2psRealloc(), GL2PScontext::objects_stack, GL2PScontext::options, GL2PScontext::pdfprimlist, GL2PScontext::stream, GL2PScontext::streamlength, and GL2PScontext::xreflist.
static int gl2psPrintPDFGSObject (void) [static]
Definition at line 4161 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPrintPDFFooter().
static void gl2psPrintPDFHeader (void) [static]
Definition at line 4025 of file gl2ps.c.
References GL2PS_COMPRESS, gl2psListCreate(), gl2psMalloc(), gl2psOpenPDFDataStream(), gl2psOpenPDFDataStreamWritePreface(), gl2psPDFstacksInit(), gl2psPrintPDFCatalog(), gl2psPrintPDFInfo(), gl2psPrintPDFPages(), GL2PScontext::objects_stack, GL2PScontext::options, GL2PScontext::pdfprimlist, GL2PScontext::stream, GL2PScontext::streamlength, and GL2PScontext::xreflist.
Referenced by gl2psPrintPDFBeginViewport().
static int gl2psPrintPDFInfo (void) [static]
Definition at line 3924 of file gl2ps.c.
References GL2PS_COPYRIGHT, GL2PS_EXTRA_VERSION, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_PATCH_VERSION, GL2PScontext::producer, GL2PScontext::stream, and GL2PScontext::title.
Referenced by gl2psPrintPDFHeader().
static int gl2psPrintPDFLineWidth (GLfloat lw) [static]
Definition at line 3397 of file gl2ps.c.
References GL2PS_ZERO, and gl2psPrintf().
Referenced by gl2psPDFgroupListWriteMainStream().
static int gl2psPrintPDFOpenPage (void) [static]
Definition at line 4106 of file gl2ps.c.
References GL2PS_LANDSCAPE, GL2PScontext::options, GL2PScontext::stream, and GL2PScontext::viewport.
Referenced by gl2psPrintPDFFooter().
static int gl2psPrintPDFPages (void) [static]
Definition at line 3976 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPrintPDFHeader().
static int gl2psPrintPDFPixmap (int obj, int childobj, GL2PSimage * im, int gray) [static]
Definition at line 4535 of file gl2ps.c.
References GL2PScontext::compress, GL2PSimage::format, GL2PS_COMPRESS, gl2psPrintPDFCompressorType(), gl2psPrintPDFPixmapStreamData(), gl2psWriteBigEndian(), GL2PSimage::height, GL2PScontext::options, GL2PScontext::stream, and GL2PSimage::width.
Referenced by gl2psPDFgroupListWriteObjects().
static int gl2psPrintPDFPixmapStreamData (GL2PSimage * im, int(*)(unsigned long data, int size) action, int gray) [static]
Definition at line 4496 of file gl2ps.c.
References GL2PSimage::format, gl2psGetRGB(), GL2PSimage::height, and GL2PSimage::width.
Referenced by gl2psPrintPDFPixmap().
static void gl2psPrintPDFPrimitive (void * data) [static]
Definition at line 4058 of file gl2ps.c.
References GL2PSprimitive::culled, GL2PS_OCCLUSION_CULL, gl2psCopyPrimitive(), gl2psListAdd(), GL2PScontext::options, and GL2PScontext::pdfprimlist.
static int gl2psPrintPDFShader (int obj, GL2PStriangle * triangles, int size, int gray) [static]
Definition at line 4333 of file gl2ps.c.
References GL2PScontext::compress, GL2PS_COMPRESS, gl2psPDFRectHull(), gl2psPrintPDFCompressorType(), gl2psPrintPDFShaderStreamData(), gl2psWriteBigEndian(), GL2PScontext::options, and GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteObjects().
static int gl2psPrintPDFShaderExtGS (int obj, int childobj) [static]
Definition at line 4459 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteObjects().
static int gl2psPrintPDFShaderMask (int obj, int childobj) [static]
Definition at line 4420 of file gl2ps.c.
References GL2PScontext::stream, and GL2PScontext::viewport.
Referenced by gl2psPDFgroupListWriteObjects().
static int gl2psPrintPDFShaderSimpleExtGS (int obj, GLfloat alpha) [static]
Definition at line 4480 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteObjects().
static int gl2psPrintPDFShaderStreamData (GL2PStriangle * triangle, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin, int(*)(unsigned long data, int size) action, int gray) [static]
Definition at line 4276 of file gl2ps.c.
References gl2psPrintPDFShaderStreamDataAlpha(), gl2psPrintPDFShaderStreamDataCoord(), gl2psPrintPDFShaderStreamDataRGB(), and GL2PStriangle::vertex.
Referenced by gl2psPrintPDFShader().
static int gl2psPrintPDFShaderStreamDataAlpha (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action, int sigbyte) [static]
Definition at line 4251 of file gl2ps.c.
References GL2PSvertex::rgba.
Referenced by gl2psPrintPDFShaderStreamData().
static int gl2psPrintPDFShaderStreamDataCoord (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action, GLfloat dx, GLfloat dy, GLfloat xmin, GLfloat ymin) [static]
Definition at line 4181 of file gl2ps.c.
References GL2PS_ZERO, and GL2PSvertex::xyz.
Referenced by gl2psPrintPDFShaderStreamData().
static int gl2psPrintPDFShaderStreamDataRGB (GL2PSvertex * vertex, int(*)(unsigned long data, int size) action) [static]
Definition at line 4227 of file gl2ps.c.
References GL2PSvertex::rgba.
Referenced by gl2psPrintPDFShaderStreamData().
static int gl2psPrintPDFStrokeColor (GL2PSrgba rgba) [static]
Definition at line 3364 of file gl2ps.c.
References GL2PS_ZERO, gl2psPrintf(), and gl2psSetLastColor().
Referenced by gl2psPDFgroupListWriteMainStream().
static int gl2psPrintPDFText (int obj, GL2PSstring * s, int fontnumber) [static]
Definition at line 4602 of file gl2ps.c.
References GL2PSstring::fontname, and GL2PScontext::stream.
Referenced by gl2psPDFgroupListWriteObjects().
static void gl2psPrintPGFBeginViewport (GLint viewport[4]) [static]
Definition at line 5428 of file gl2ps.c.
References GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PS_DRAW_BACKGROUND, gl2psPrintPGFColor(), gl2psPrintPGFHeader(), GL2PScontext::header, GL2PScontext::options, and GL2PScontext::stream.
static void gl2psPrintPGFColor (GL2PSrgba rgba) [static]
Definition at line 5275 of file gl2ps.c.
References gl2psSameColor(), gl2psSetLastColor(), GL2PScontext::lastrgba, and GL2PScontext::stream.
Referenced by gl2psPrintPGFBeginViewport(), gl2psPrintPGFHeader(), and gl2psPrintPGFPrimitive().
static void gl2psPrintPGFDash (GLushort pattern, GLint factor) [static]
Definition at line 5310 of file gl2ps.c.
References gl2psParseStipplePattern(), GL2PScontext::lastfactor, GL2PScontext::lastpattern, and GL2PScontext::stream.
Referenced by gl2psPrintPGFPrimitive().
static GLint gl2psPrintPGFEndViewport (void) [static]
Definition at line 5468 of file gl2ps.c.
References gl2psPrintPrimitives(), and GL2PScontext::stream.
static void gl2psPrintPGFFinalPrimitive (void) [static]
Definition at line 5476 of file gl2ps.c.
static void gl2psPrintPGFFooter (void) [static]
Definition at line 5423 of file gl2ps.c.
References GL2PScontext::stream.
static void gl2psPrintPGFHeader (void) [static]
Definition at line 5283 of file gl2ps.c.
References GL2PScontext::bgcolor, GL2PS_COPYRIGHT, GL2PS_DRAW_BACKGROUND, GL2PS_EXTRA_VERSION, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_PATCH_VERSION, gl2psPrintPGFColor(), GL2PScontext::options, GL2PScontext::producer, GL2PScontext::stream, GL2PScontext::title, and GL2PScontext::viewport.
Referenced by gl2psPrintPGFBeginViewport().
static void gl2psPrintPGFPrimitive (void * data) [static]
Definition at line 5348 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSstring::fontsize, GL2PS_LINE, GL2PS_PGF, GL2PS_POINT, GL2PS_SPECIAL, GL2PS_TEXT, GL2PS_TRIANGLE, gl2psPGFTextAlignment(), gl2psPrintPGFColor(), gl2psPrintPGFDash(), GL2PScontext::lastlinewidth, GL2PSprimitive::pattern, GL2PSvertex::rgba, GL2PSstring::str, GL2PScontext::stream, GL2PSprimitive::text, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSprimitive::width, and GL2PSvertex::xyz.
static void gl2psPrintPostScriptBeginViewport (GLint viewport[4]) [static]
Definition at line 3120 of file gl2ps.c.
References GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PS_DRAW_BACKGROUND, gl2psPrintf(), gl2psPrintPostScriptHeader(), GL2PScontext::header, and GL2PScontext::options.
static void gl2psPrintPostScriptColor (GL2PSrgba rgba) [static]
Definition at line 2882 of file gl2ps.c.
References gl2psPrintf(), gl2psSameColor(), gl2psSetLastColor(), and GL2PScontext::lastrgba.
Referenced by gl2psPrintPostScriptPrimitive().
static int gl2psPrintPostScriptDash (GLushort pattern, GLint factor, const char * str) [static]
Definition at line 2941 of file gl2ps.c.
References gl2psParseStipplePattern(), gl2psPrintf(), GL2PScontext::lastfactor, and GL2PScontext::lastpattern.
Referenced by gl2psPDFgroupListWriteMainStream(), and gl2psPrintPostScriptPrimitive().
static GLint gl2psPrintPostScriptEndViewport (void) [static]
Definition at line 3160 of file gl2ps.c.
References gl2psPrintf(), and gl2psPrintPrimitives().
static void gl2psPrintPostScriptFinalPrimitive (void) [static]
Definition at line 3169 of file gl2ps.c.
References gl2psEndPostScriptLine().
static void gl2psPrintPostScriptFooter (void) [static]
Definition at line 3107 of file gl2ps.c.
References gl2psPrintf(), and gl2psPrintGzipFooter().
static void gl2psPrintPostScriptHeader (void) [static]
Definition at line 2643 of file gl2ps.c.
References GL2PScontext::bgcolor, GL2PScontext::format, GL2PS_COPYRIGHT, GL2PS_DRAW_BACKGROUND, GL2PS_EXTRA_VERSION, GL2PS_LANDSCAPE, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_NO_PS3_SHADING, GL2PS_PATCH_VERSION, GL2PS_PS, gl2psPrintf(), gl2psPrintGzipHeader(), GL2PScontext::options, GL2PScontext::producer, GL2PScontext::threshold, GL2PScontext::title, and GL2PScontext::viewport.
Referenced by gl2psPrintPostScriptBeginViewport().
static void gl2psPrintPostScriptImagemap (GLfloat x, GLfloat y, GLsizei width, GLsizei height, const unsigned char * imagemap) [static]
Definition at line 2623 of file gl2ps.c.
References gl2psPrintf(), and gl2psWriteByte().
Referenced by gl2psPrintPostScriptPrimitive().
static void gl2psPrintPostScriptPixmap (GLfloat x, GLfloat y, GL2PSimage * im) [static]
Definition at line 2422 of file gl2ps.c.
References gl2psGetRGB(), gl2psPrintf(), gl2psWriteByte(), GL2PSimage::height, GL2PSimage::width, GL2PSimage::zoom_x, and GL2PSimage::zoom_y.
Referenced by gl2psPrintPostScriptPrimitive().
static void gl2psPrintPostScriptPrimitive (void * data) [static]
Definition at line 2968 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSstring::fontname, GL2PSstring::fontsize, GL2PS_EPS, GL2PS_IMAGEMAP, GL2PS_IMAGEMAP_WRITTEN, GL2PS_LINE, GL2PS_OCCLUSION_CULL, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_PS, GL2PS_QUADRANGLE, GL2PS_SPECIAL, GL2PS_TEXT, GL2PS_TEXT_B, GL2PS_TEXT_BL, GL2PS_TEXT_BR, GL2PS_TEXT_C, GL2PS_TEXT_CL, GL2PS_TEXT_CR, GL2PS_TEXT_T, GL2PS_TEXT_TL, GL2PS_TEXT_TR, GL2PS_TRIANGLE, GL2PS_WARNING, gl2psEndPostScriptLine(), gl2psMsg(), gl2psPrintf(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptDash(), gl2psPrintPostScriptImagemap(), gl2psPrintPostScriptPixmap(), gl2psResetPostScriptColor(), gl2psSameColor(), gl2psSamePosition(), gl2psVertsSameColor(), GL2PSimage::height, GL2PSprimitive::image, GL2PScontext::lastfactor, GL2PScontext::lastlinewidth, GL2PScontext::lastpattern, GL2PScontext::lastrgba, GL2PScontext::lastvertex, GL2PScontext::options, GL2PSprimitive::pattern, GL2PSimage::pixels, GL2PSvertex::rgba, GL2PSstring::str, GL2PSprimitive::text, GL2PSimage::type, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSimage::width, GL2PSprimitive::width, and GL2PSvertex::xyz.
static GLint gl2psPrintPrimitives (void) [static]
Definition at line 5530 of file gl2ps.c.
References GL2PScontext::boundary, GL2PScontext::format, GL2PS_BSP_SORT, GL2PS_EPSILON, GL2PS_INFO, GL2PS_NO_FEEDBACK, GL2PS_NO_SORT, GL2PS_OCCLUSION_CULL, GL2PS_OVERFLOW, GL2PS_SIMPLE_SORT, GL2PS_SUCCESS, GL2PS_TIGHT_BOUNDING_BOX, GL2PS_ZSCALE, gl2psAddInImageTree(), gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), gl2psCompareDepth(), gl2psComputeTightBoundingBox(), gl2psFreeBspImageTree(), gl2psFreeBspTree(), gl2psFreePrimitive(), gl2psGreater(), gl2psLess(), gl2psListAction(), gl2psListActionInverse(), gl2psListCreate(), gl2psListNbr(), gl2psListReset(), gl2psListSort(), gl2psMalloc(), gl2psMsg(), gl2psParseFeedbackBuffer(), gl2psRescaleAndOffset(), gl2psTraverseBspTree(), GL2PScontext::header, GL2PScontext::imagetree, GL2PScontext::options, GL2PScontext::primitives, GL2PSbackend::printFinalPrimitive, GL2PSbackend::printHeader, GL2PSbackend::printPrimitive, GL2PScontext::sort, and GL2PScontext::viewport.
Referenced by gl2psEndPage(), gl2psPrintPDFEndViewport(), gl2psPrintPGFEndViewport(), gl2psPrintPostScriptEndViewport(), gl2psPrintSVGEndViewport(), and gl2psPrintTeXEndViewport().
static void gl2psPrintSVGBeginViewport (GLint viewport[4]) [static]
Definition at line 5198 of file gl2ps.c.
References GL2PScontext::colormap, GL2PScontext::colormode, GL2PScontext::colorsize, GL2PS_DRAW_BACKGROUND, gl2psPrintf(), gl2psPrintSVGHeader(), gl2psSVGGetColorString(), GL2PScontext::header, GL2PScontext::options, and GL2PScontext::viewport.
static void gl2psPrintSVGDash (GLushort pattern, GLint factor) [static]
Definition at line 4983 of file gl2ps.c.
References gl2psParseStipplePattern(), and gl2psPrintf().
Referenced by gl2psPrintSVGPrimitive().
static GLint gl2psPrintSVGEndViewport (void) [static]
Definition at line 5241 of file gl2ps.c.
References gl2psPrintf(), and gl2psPrintPrimitives().
static void gl2psPrintSVGFinalPrimitive (void) [static]
Definition at line 5250 of file gl2ps.c.
References gl2psEndSVGLine().
static void gl2psPrintSVGFooter (void) [static]
Definition at line 5190 of file gl2ps.c.
References gl2psPrintf(), and gl2psPrintGzipFooter().
static void gl2psPrintSVGHeader (void) [static]
Definition at line 4863 of file gl2ps.c.
References GL2PScontext::bgcolor, GL2PS_COPYRIGHT, GL2PS_DRAW_BACKGROUND, GL2PS_EXTRA_VERSION, GL2PS_LANDSCAPE, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_PATCH_VERSION, gl2psPrintf(), gl2psPrintGzipHeader(), gl2psSVGGetColorString(), GL2PScontext::options, GL2PScontext::producer, GL2PScontext::title, and GL2PScontext::viewport.
Referenced by gl2psPrintSVGBeginViewport().
static void gl2psPrintSVGPixmap (GLfloat x, GLfloat y, GL2PSimage * pixmap) [static]
Definition at line 5011 of file gl2ps.c.
References GL2PS_WARNING, gl2psListCreate(), gl2psListDelete(), gl2psListNbr(), gl2psMsg(), gl2psPrintf(), GL2PSimage::height, and GL2PSimage::width.
Referenced by gl2psPrintSVGPrimitive().
static void gl2psPrintSVGPrimitive (void * data) [static]
Definition at line 5043 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PSprimitive::culled, GL2PSprimitive::data, GL2PSprimitive::factor, GL2PSstring::fontname, GL2PSstring::fontsize, GL2PS_LINE, GL2PS_OCCLUSION_CULL, GL2PS_PIXMAP, GL2PS_POINT, GL2PS_QUADRANGLE, GL2PS_SPECIAL, GL2PS_SVG, GL2PS_TEXT, GL2PS_TEXT_B, GL2PS_TEXT_BL, GL2PS_TEXT_BR, GL2PS_TEXT_C, GL2PS_TEXT_CL, GL2PS_TEXT_CR, GL2PS_TEXT_T, GL2PS_TEXT_TL, GL2PS_TEXT_TR, GL2PS_TRIANGLE, GL2PS_WARNING, gl2psEndSVGLine(), gl2psMsg(), gl2psPrintf(), gl2psPrintSVGDash(), gl2psPrintSVGPixmap(), gl2psPrintSVGSmoothTriangle(), gl2psSameColor(), gl2psSamePosition(), gl2psSetLastColor(), gl2psSVGGetColorString(), gl2psSVGGetCoordsAndColors(), GL2PSprimitive::image, GL2PScontext::lastfactor, GL2PScontext::lastlinewidth, GL2PScontext::lastpattern, GL2PScontext::lastrgba, GL2PScontext::lastvertex, GL2PSprimitive::numverts, GL2PScontext::options, GL2PSprimitive::pattern, GL2PSvertex::rgba, GL2PSstring::str, GL2PSprimitive::text, GL2PSprimitive::type, GL2PSprimitive::verts, GL2PSprimitive::width, and GL2PSvertex::xyz.
static void gl2psPrintSVGSmoothTriangle (GL2PSxyz xyz[3], GL2PSrgba rgba[3]) [static]
Definition at line 4916 of file gl2ps.c.
References gl2psPrintf(), gl2psSameColorThreshold(), gl2psSVGGetColorString(), and GL2PScontext::threshold.
Referenced by gl2psPrintSVGPrimitive().
static void gl2psPrintTeXBeginViewport (GLint viewport[4]) [static]
Definition at line 3315 of file gl2ps.c.
References gl2psPrintTeXHeader(), and GL2PScontext::header.
static GLint gl2psPrintTeXEndViewport (void) [static]
Definition at line 3326 of file gl2ps.c.
References gl2psPrintPrimitives().
static void gl2psPrintTeXFinalPrimitive (void) [static]
Definition at line 3331 of file gl2ps.c.
static void gl2psPrintTeXFooter (void) [static]
Definition at line 3309 of file gl2ps.c.
References GL2PS_LANDSCAPE, GL2PScontext::options, and GL2PScontext::stream.
static void gl2psPrintTeXHeader (void) [static]
Definition at line 3205 of file gl2ps.c.
References GL2PScontext::filename, GL2PS_COPYRIGHT, GL2PS_EXTRA_VERSION, GL2PS_LANDSCAPE, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_PATCH_VERSION, GL2PScontext::options, GL2PScontext::producer, GL2PScontext::stream, GL2PScontext::title, and GL2PScontext::viewport.
Referenced by gl2psPrintTeXBeginViewport().
static void gl2psPrintTeXPrimitive (void * data) [static]
Definition at line 3246 of file gl2ps.c.
References GL2PSstring::alignment, GL2PSstring::angle, GL2PSprimitive::data, GL2PSstring::fontsize, GL2PS_SPECIAL, GL2PS_TEX, GL2PS_TEXT, GL2PS_TEXT_B, GL2PS_TEXT_BL, GL2PS_TEXT_BR, GL2PS_TEXT_C, GL2PS_TEXT_CL, GL2PS_TEXT_CR, GL2PS_TEXT_T, GL2PS_TEXT_TL, GL2PS_TEXT_TR, GL2PSvertex::rgba, GL2PSstring::str, GL2PScontext::stream, GL2PSprimitive::text, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSvertex::xyz.
static GLfloat gl2psPsca (GLfloat * a, GLfloat * b) [static]
Definition at line 1069 of file gl2ps.c.
Referenced by gl2psCutEdge().
static void gl2psPutPDFImage (GL2PSimage * image, int cnt, GLfloat x, GLfloat y) [static]
Definition at line 3434 of file gl2ps.c.
References gl2psPrintf(), GL2PSimage::height, GL2PScontext::streamlength, and GL2PSimage::width.
Referenced by gl2psPDFgroupListWriteMainStream().
static void gl2psPutPDFText (GL2PSstring * text, int cnt, GLfloat x, GLfloat y) [static]
Definition at line 3407 of file gl2ps.c.
References GL2PSstring::angle, GL2PSstring::fontsize, gl2psPrintf(), M_PI, GL2PSstring::str, and GL2PScontext::streamlength.
Referenced by gl2psPDFgroupListWriteMainStream().
static void gl2psPvec (GLfloat * a, GLfloat * b, GLfloat * c) [static]
Definition at line 1074 of file gl2ps.c.
Referenced by gl2psGetNormal().
static void* gl2psRealloc (void * ptr, size_t size) [static]
Definition at line 311 of file gl2ps.c.
References GL2PS_ERROR, and gl2psMsg().
Referenced by gl2psListRealloc(), gl2psPrintPDFFooter(), and gl2psSplitPrimitive2D().
static void gl2psRescaleAndOffset (void) [static]
Definition at line 1625 of file gl2ps.c.
References GL2PS_LINE, GL2PS_SIMPLE_LINE_OFFSET, GL2PS_SIMPLE_SORT, GL2PS_TRIANGLE, GL2PS_ZERO, GL2PS_ZOFFSET, GL2PS_ZOFFSET_LARGE, GL2PS_ZSCALE, gl2psListNbr(), gl2psListPointer(), GL2PSprimitive::numverts, GL2PScontext::offset, GL2PSprimitive::offset, GL2PScontext::options, GL2PScontext::primitives, GL2PScontext::sort, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psPrintPrimitives().
static void gl2psResetPostScriptColor (void) [static]
Definition at line 2890 of file gl2ps.c.
References GL2PScontext::lastrgba.
Referenced by gl2psPrintPostScriptPrimitive().
static GLboolean gl2psSameColor (GL2PSrgba rgba1, GL2PSrgba rgba2) [static]
Definition at line 673 of file gl2ps.c.
References GL2PS_ZERO.
Referenced by gl2psPDFgroupListInit(), gl2psPrintPGFColor(), gl2psPrintPostScriptColor(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psVertsSameColor().
static GLboolean gl2psSameColorThreshold (int n, GL2PSrgba rgba[], GL2PSrgba threshold) [static]
Definition at line 694 of file gl2ps.c.
Referenced by gl2psPrintSVGSmoothTriangle().
static GLboolean gl2psSamePosition (GL2PSxyz p1, GL2PSxyz p2) [static]
Definition at line 1046 of file gl2ps.c.
References GL2PS_ZERO.
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive().
static void gl2psSetLastColor (GL2PSrgba rgba) [static]
Definition at line 711 of file gl2ps.c.
References GL2PScontext::lastrgba.
Referenced by gl2psPrintPDFStrokeColor(), gl2psPrintPGFColor(), gl2psPrintPostScriptColor(), and gl2psPrintSVGPrimitive().
GL2PSDLL_API GLint gl2psSetOptions (GLint options)
Definition at line 6047 of file gl2ps.c.
References GL2PS_SUCCESS, GL2PS_UNINITIALIZED, and GL2PScontext::options.
static void gl2psSortOutTrianglePDFgroup (GL2PSpdfgroup * gro) [static]
Definition at line 3564 of file gl2ps.c.
References GL2PScontext::extgs_stack, GL2PS_TRIANGLE, gl2psFillTriangleFromPrimitive(), gl2psListNbr(), gl2psListPointer(), GL2PSpdfgroup::gsno, GL2PSpdfgroup::gsobjno, GL2PSpdfgroup::maskshno, GL2PSpdfgroup::maskshobjno, GL2PScontext::mshader_stack, GL2PScontext::objects_stack, GL2PStriangle::prop, GL2PSpdfgroup::ptrlist, GL2PScontext::shader_stack, GL2PSpdfgroup::shno, GL2PSpdfgroup::shobjno, T_ALPHA_1, T_ALPHA_LESS_1, T_CONST_COLOR, T_VAR_ALPHA, T_VAR_COLOR, GL2PSpdfgroup::trgroupno, GL2PScontext::trgroupobjects_stack, GL2PSpdfgroup::trgroupobjno, and GL2PSprimitive::type.
Referenced by gl2psPDFgroupListWriteMainStream().
GL2PSDLL_API GLint gl2psSpecial (GLint format, const char * str)
Definition at line 5838 of file gl2ps.c.
References GL2PS_SPECIAL, and gl2psAddText().
static GLint gl2psSplitPrimitive (GL2PSprimitive * prim, GL2PSplane plane, GL2PSprimitive ** front, GL2PSprimitive ** back) [static]
Definition at line 1288 of file gl2ps.c.
References GL2PS_COINCIDENT, GL2PS_EPSILON, GL2PS_IN_BACK_OF, GL2PS_IN_FRONT_OF, GL2PS_POINT, GL2PS_SPANNING, gl2psAddIndex(), gl2psComparePointPlane(), gl2psCreateSplitPrimitive(), gl2psGetIndex(), gl2psMalloc(), GL2PSprimitive::numverts, GL2PSprimitive::type, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psBuildBspTree().
static void gl2psSplitPrimitive2D (GL2PSprimitive * prim, GL2PSplane plane, GL2PSprimitive ** front, GL2PSprimitive ** back) [static]
Definition at line 1907 of file gl2ps.c.
References flag, GL2PS_POINT_BACK, GL2PS_POINT_INFRONT, gl2psCheckPoint(), gl2psCreateSplitPrimitive2D(), gl2psCutEdge(), gl2psFree(), gl2psRealloc(), GL2PSprimitive::numverts, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psAddInBspImageTree().
static GLboolean gl2psSupportedBlendMode (GLenum sfactor, GLenum dfactor) [static]
Definition at line 920 of file gl2ps.c.
Referenced by gl2psBlendFunc().
static void gl2psSVGGetColorString (GL2PSrgba rgba, char str[32]) [static]
Definition at line 4852 of file gl2ps.c.
Referenced by gl2psPrintSVGBeginViewport(), gl2psPrintSVGHeader(), gl2psPrintSVGPrimitive(), and gl2psPrintSVGSmoothTriangle().
static void gl2psSVGGetCoordsAndColors (int n, GL2PSvertex * verts, GL2PSxyz * xyz, GL2PSrgba * rgba) [static]
Definition at line 4838 of file gl2ps.c.
References GL2PScontext::viewport, and GL2PSvertex::xyz.
Referenced by gl2psPrintSVGPrimitive().
static GLint gl2psTestSplitPrimitive (GL2PSprimitive * prim, GL2PSplane plane) [static]
Definition at line 1257 of file gl2ps.c.
References GL2PS_COINCIDENT, GL2PS_EPSILON, GL2PS_IN_BACK_OF, GL2PS_IN_FRONT_OF, gl2psComparePointPlane(), gl2psGetIndex(), GL2PSprimitive::numverts, GL2PSprimitive::verts, and GL2PSvertex::xyz.
Referenced by gl2psFindRoot().
GL2PSDLL_API GLint gl2psText (const char * str, const char * fontname, GLshort fontsize)
Definition at line 5833 of file gl2ps.c.
References GL2PS_TEXT, GL2PS_TEXT_BL, and gl2psAddText().
GL2PSDLL_API GLint gl2psTextOpt (const char * str, const char * fontname, GLshort fontsize, GLint alignment, GLfloat angle)
Definition at line 5827 of file gl2ps.c.
References GL2PS_TEXT, and gl2psAddText().
static void gl2psTraverseBspTree (GL2PSbsptree * tree, GL2PSxyz eye, GLfloat epsilon, GLboolean(*)(GLfloat f1, GLfloat f2) compare, void(*)(void *data) action, int inverse) [static]
Definition at line 1589 of file gl2ps.c.
References _GL2PSbsptree::back, _GL2PSbsptree::front, gl2psComparePointPlane(), gl2psListAction(), gl2psListActionInverse(), _GL2PSbsptree::plane, and _GL2PSbsptree::primitives.
Referenced by gl2psPrintPrimitives().
static int gl2psTrianglesFirst (const void * a, const void * b) [static]
Definition at line 1403 of file gl2ps.c.
References GL2PSprimitive::type.
Referenced by gl2psBuildBspTree().
static GLboolean gl2psVertsSameColor (const GL2PSprimitive * prim) [static]
Definition at line 682 of file gl2ps.c.
References gl2psSameColor(), GL2PSprimitive::numverts, GL2PSvertex::rgba, and GL2PSprimitive::verts.
Referenced by gl2psPrintPostScriptPrimitive().
static int gl2psWriteBigEndian (unsigned long data, int bytes) [static]
Definition at line 330 of file gl2ps.c.
References GL2PScontext::stream.
Referenced by gl2psPrintPDFPixmap(), and gl2psPrintPDFShader().
static void gl2psWriteByte (unsigned char byte) [static]
Definition at line 2415 of file gl2ps.c.
References gl2psPrintf().
Referenced by gl2psPrintPostScriptImagemap(), and gl2psPrintPostScriptPixmap().
Variable Documentation
GL2PScontext* gl2ps = NULL [static]
Definition at line 268 of file gl2ps.c.
GL2PSbackend* gl2psbackends[] [static]
Initial value:
 {
  &gl2psPS,
  &gl2psEPS,
  &gl2psTEX,
  &gl2psPDF,
  &gl2psSVG,
  &gl2psPGF
}
Definition at line 5502 of file gl2ps.c.
GL2PSbackend gl2psEPS [static]
Initial value:
 {
  gl2psPrintPostScriptHeader,
  gl2psPrintPostScriptFooter,
  gl2psPrintPostScriptBeginViewport,
  gl2psPrintPostScriptEndViewport,
  gl2psPrintPostScriptPrimitive,
  gl2psPrintPostScriptFinalPrimitive,
  "eps",
  "Encapsulated Postscript"
}
Definition at line 3188 of file gl2ps.c.
GL2PSbackend gl2psPDF [static]
Initial value:
 {
  gl2psPrintPDFHeader,
  gl2psPrintPDFFooter,
  gl2psPrintPDFBeginViewport,
  gl2psPrintPDFEndViewport,
  gl2psPrintPDFPrimitive,
  gl2psPrintPDFFinalPrimitive,
  "pdf",
  "Portable Document Format"
}
Definition at line 4821 of file gl2ps.c.
GL2PSbackend gl2psPGF [static]
Initial value:
 {
  gl2psPrintPGFHeader,
  gl2psPrintPGFFooter,
  gl2psPrintPGFBeginViewport,
  gl2psPrintPGFEndViewport,
  gl2psPrintPGFPrimitive,
  gl2psPrintPGFFinalPrimitive,
  "tex",
  "PGF Latex Graphics"
}
Definition at line 5482 of file gl2ps.c.
GL2PSbackend gl2psPS [static]
Initial value:
 {
  gl2psPrintPostScriptHeader,
  gl2psPrintPostScriptFooter,
  gl2psPrintPostScriptBeginViewport,
  gl2psPrintPostScriptEndViewport,
  gl2psPrintPostScriptPrimitive,
  gl2psPrintPostScriptFinalPrimitive,
  "ps",
  "Postscript"
}
Definition at line 3177 of file gl2ps.c.
GL2PSbackend gl2psSVG [static]
Initial value:
 {
  gl2psPrintSVGHeader,
  gl2psPrintSVGFooter,
  gl2psPrintSVGBeginViewport,
  gl2psPrintSVGEndViewport,
  gl2psPrintSVGPrimitive,
  gl2psPrintSVGFinalPrimitive,
  "svg",
  "Scalable Vector Graphics"
}
Definition at line 5258 of file gl2ps.c.
GL2PSbackend gl2psTEX [static]
Initial value:
 {
  gl2psPrintTeXHeader,
  gl2psPrintTeXFooter,
  gl2psPrintTeXBeginViewport,
  gl2psPrintTeXEndViewport,
  gl2psPrintTeXPrimitive,
  gl2psPrintTeXFinalPrimitive,
  "tex",
  "LaTeX text"
}
Definition at line 3337 of file gl2ps.c.