SUMO - Simulation of Urban MObility: MSRouteHandler Class Reference
MSRouteHandler Class Reference
Parser and container for routes during their loading.
#include <MSRouteHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getLastDepart () const
Returns the last loaded depart time.
MSRouteHandler (const std::string &file, bool addVehiclesDirectly)
standard constructor
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~MSRouteHandler ()
standard destructor
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Protected Member Functions
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute ()
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
inherited from GenericSAXHandler
virtual void myEndElement (int element)
Called when a closing tag occurs.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
MSPerson::MSPersonPlan * myActivePlan
The plan of the current person.
MSEdgeVector myActiveRoute
The current route.
RGBColor myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The id of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector
< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
RandomDistributor< const
MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route).
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor
< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type).
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
bool myHaveWarnedAboutDeprecatedBusStop
bool myHaveWarnedAboutDeprecatedFriendlyPos
bool myHaveWarnedAboutDeprecatedRefID
bool myHaveWarnedAboutDeprecatedVType
bool myHaveWarnedAboutDeprecatedVTypeDistribution
bool myHaveWarnedAboutDeprecatedVTypes
SUMOTime myLastDepart
The insertion time of the vehicle read last.
SUMOReal myScale
The scaling factor (especially for inc-dua).
SUMOVehicleParameter * myVehicleParameter
Private Member Functions
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
MSRouteHandler (const MSRouteHandler &s)
Invalidated copy constructor.
MSRouteHandler & operator= (const MSRouteHandler &s)
Invalidated assignment operator.
Detailed Description
Parser and container for routes during their loading.
MSRouteHandler is the container for routes while they are build until their transferring to the MSNet::RouteDict The result of the operations are single MSNet::Route-instances
Definition at line 60 of file MSRouteHandler.h.
Constructor & Destructor Documentation
MSRouteHandler::MSRouteHandler (const std::string & file, bool addVehiclesDirectly)
standard constructor
Definition at line 67 of file MSRouteHandler.cpp.
References OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getOptions(), OptionsCont::isSet(), myActiveRoute, myScale, and SUMOReal.
MSRouteHandler::~MSRouteHandler () [virtual]
standard destructor
Definition at line 95 of file MSRouteHandler.cpp.
MSRouteHandler::MSRouteHandler (const MSRouteHandler & s) [private]
Invalidated copy constructor.
Member Function Documentation
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) [protected]
Processing of a stop.
Definition at line 665 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, checkStopPos(), MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSBusStop::getBeginLanePosition(), MSNet::getBusStop(), MSBusStop::getEndLanePosition(), Named::getID(), MSNet::getInstance(), SUMOSAXAttributes::getIntReporting(), MSBusStop::getLane(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myActivePlan, myActiveRouteID, myActiveRouteStops, myHaveWarnedAboutDeprecatedBusStop, myHaveWarnedAboutDeprecatedFriendlyPos, myVehicleParameter, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, SUMOVehicleParameter::stops, SUMO_ATTR_BUS_STOP, SUMO_ATTR_BUS_STOP__DEPRECATED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_INDEX, SUMO_ATTR_LANE, SUMO_ATTR_PARKING, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, toString(), SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
bool MSRouteHandler::checkLastDepart () [private]
Checks whether the route file is sorted by departure time if needed.
Definition at line 106 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, myAddVehiclesDirectly, myLastDepart, myVehicleParameter, and WRITE_WARNING.
Referenced by closeFlow(), closePerson(), and closeVehicle().
bool MSRouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
Definition at line 627 of file MSRouteHandler.cpp.
Referenced by addStop().
void MSRouteHandler::closeFlow () [protected]
Ends the processing of a flow.
Definition at line 591 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), checkLastDepart(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, myActiveRouteID, myVehicleParameter, SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by myEndElement().
void MSRouteHandler::closePerson () [protected]
Ends the processing of a person.
Definition at line 575 of file MSRouteHandler.cpp.
References checkLastDepart(), SUMOVehicleParameter::depart, MSNet::getInstance(), MSNet::getPersonControl(), SUMOVehicleParameter::id, myActivePlan, myVehicleParameter, and MSPersonControl::setArrival().
Referenced by myEndElement().
void MSRouteHandler::closeRoute () [protected]
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Definition at line 401 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::dictionary(), MSNet::getInstance(), SUMOVehicleParameter::id, myActiveRoute, myActiveRouteColor, myActiveRouteID, myActiveRouteProbability, myActiveRouteRefID, myActiveRouteStops, myCurrentRouteDistribution, myVehicleParameter, and SUMOVehicleParameter::repetitionNumber.
Referenced by myEndElement(), and myStartElement().
void MSRouteHandler::closeRouteDistribution () [protected]
closes (ends) the building of a distribution
Definition at line 477 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), myCurrentRouteDistribution, myCurrentRouteDistributionID, and WRITE_ERROR.
Referenced by myEndElement().
void MSRouteHandler::closeVehicle () [protected]
Ends the processing of a vehicle.
Definition at line 492 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addWaiting(), MSRoute::begin(), MSVehicleControl::buildVehicle(), checkLastDepart(), MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSVehicleControl::isInQuota(), myActiveRouteID, myScale, myVehicleParameter, MSVehicleControl::registerOneWaitingForPerson(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by myEndElement(), and myStartElement().
void MSRouteHandler::closeVehicleTypeDistribution () [protected]
closes (ends) the building of a distribution
Definition at line 281 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), myCurrentVTypeDistribution, myCurrentVTypeDistributionID, and WRITE_ERROR.
Referenced by myEndElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
SUMOTime MSRouteHandler::getLastDepart () const
Returns the last loaded depart time.
Definition at line 100 of file MSRouteHandler.cpp.
References myLastDepart.
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void MSRouteHandler::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Reimplemented in NLHandler.
Definition at line 341 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSVehicleType::build(), closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), SUMOVehicleParserHelper::closeVTypeParsing(), MSVehicleType::getDefaultProbability(), MSVehicleType::getID(), MSNet::getInstance(), myCurrentVType, myCurrentVTypeDistribution, myVehicleParameter, SUMOVehicleParameter::repetitionNumber, SUMO_TAG_FLOW, SUMO_TAG_PERSON, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE__DEPRECATED, SUMO_TAG_VTYPE_DISTRIBUTION, and SUMO_TAG_VTYPE_DISTRIBUTION__DEPRECATED.
void MSRouteHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Reimplemented in NLHandler.
Definition at line 119 of file MSRouteHandler.cpp.
References addStop(), SUMOVehicleParserHelper::beginVTypeParsing(), closeRoute(), closeVehicle(), SUMOVehicleParameter::depart, MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSEdge::getFollower(), MSEdge::getNoFollowing(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myActivePlan, myActiveRoute, myActiveRouteID, myCurrentVType, myHaveWarnedAboutDeprecatedVType, myHaveWarnedAboutDeprecatedVTypeDistribution, myVehicleParameter, openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), MSEdge::parseEdgesList(), SUMOVehicleParserHelper::parseFlowAttributes(), SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVTypeEmbedded(), SUMOVehicleParameter::setParameter, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_LINES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_TAG_FLOW, SUMO_TAG_PERSON, SUMO_TAG_RIDE, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_STOP, SUMO_TAG_TRIP, SUMO_TAG_TRIP__DEPRECATED, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE__DEPRECATED, SUMO_TAG_VTYPE_DISTRIBUTION, SUMO_TAG_VTYPE_DISTRIBUTION__DEPRECATED, SUMO_TAG_WALK, SUMOReal, toString(), VEHPARS_FORCE_REROUTE, VEHPARS_TAZ_SET, SUMOVehicleParameter::wasSet(), WRITE_ERROR, and WRITE_WARNING.
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) [protected]
opens a route for reading
Definition at line 296 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), RGBColor::getDefaultColor(), SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myActiveRoute, myActiveRouteColor, myActiveRouteID, myActiveRouteProbability, myActiveRouteRefID, myCurrentRouteDistribution, myCurrentRouteDistributionID, myHaveWarnedAboutDeprecatedRefID, myVehicleParameter, RGBColor::parseColorReporting(), MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMO_ATTR_REFID__DEPRECATED, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) [protected]
opens a route distribution for reading
Definition at line 447 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::dictionary(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, myCurrentRouteDistribution, myCurrentRouteDistributionID, myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, and SUMO_ATTR_ROUTES.
Referenced by myStartElement().
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) [protected]
opens a type distribution for reading
Definition at line 252 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), SUMOSAXAttributes::getStringReporting(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), myCurrentVTypeDistribution, myCurrentVTypeDistributionID, myHaveWarnedAboutDeprecatedVTypes, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_VTYPES, SUMO_ATTR_VTYPES__DEPRECATED, toString(), and WRITE_WARNING.
Referenced by myStartElement().
MSRouteHandler& MSRouteHandler::operator= (const MSRouteHandler & s) [private]
Invalidated assignment operator.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
MSPerson::MSPersonPlan* MSRouteHandler::myActivePlan [protected]
The plan of the current person.
Definition at line 160 of file MSRouteHandler.h.
Referenced by addStop(), closePerson(), and myStartElement().
MSEdgeVector MSRouteHandler::myActiveRoute [protected]
The current route.
Definition at line 142 of file MSRouteHandler.h.
Referenced by closeRoute(), MSRouteHandler(), myStartElement(), and openRoute().
RGBColor MSRouteHandler::myActiveRouteColor [protected]
The currently parsed route's color.
Definition at line 154 of file MSRouteHandler.h.
Referenced by closeRoute(), and openRoute().
std::string MSRouteHandler::myActiveRouteID [protected]
The id of the current route.
Definition at line 145 of file MSRouteHandler.h.
Referenced by addStop(), closeFlow(), closeRoute(), closeVehicle(), myStartElement(), and openRoute().
SUMOReal MSRouteHandler::myActiveRouteProbability [protected]
The id of the current route.
Definition at line 151 of file MSRouteHandler.h.
Referenced by closeRoute(), and openRoute().
std::string MSRouteHandler::myActiveRouteRefID [protected]
The id of the route the current route references to.
Definition at line 148 of file MSRouteHandler.h.
Referenced by closeRoute(), and openRoute().
std::vector<SUMOVehicleParameter::Stop> MSRouteHandler::myActiveRouteStops [protected]
List of the stops on the parsed route.
Definition at line 157 of file MSRouteHandler.h.
Referenced by addStop(), and closeRoute().
bool MSRouteHandler::myAddVehiclesDirectly [protected]
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 163 of file MSRouteHandler.h.
Referenced by checkLastDepart().
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution [protected]
The currently parsed distribution of routes (probability->route).
Definition at line 172 of file MSRouteHandler.h.
Referenced by closeRoute(), closeRouteDistribution(), openRoute(), and openRouteDistribution().
std::string MSRouteHandler::myCurrentRouteDistributionID [protected]
The id of the currently parsed route distribution.
Definition at line 175 of file MSRouteHandler.h.
Referenced by closeRouteDistribution(), openRoute(), and openRouteDistribution().
SUMOVTypeParameter* MSRouteHandler::myCurrentVType [protected]
The currently parsed vehicle type.
Definition at line 181 of file MSRouteHandler.h.
Referenced by myEndElement(), and myStartElement().
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution [protected]
The currently parsed distribution of vehicle types (probability->vehicle type).
Definition at line 166 of file MSRouteHandler.h.
Referenced by closeVehicleTypeDistribution(), myEndElement(), and openVehicleTypeDistribution().
std::string MSRouteHandler::myCurrentVTypeDistributionID [protected]
The id of the currently parsed vehicle type distribution.
Definition at line 169 of file MSRouteHandler.h.
Referenced by closeVehicleTypeDistribution(), and openVehicleTypeDistribution().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedBusStop [protected]
Definition at line 183 of file MSRouteHandler.h.
Referenced by addStop().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos [protected]
Definition at line 183 of file MSRouteHandler.h.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NLHandler::addInstantE1Detector(), and addStop().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedRefID [protected]
Definition at line 185 of file MSRouteHandler.h.
Referenced by openRoute().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedVType [protected]
Definition at line 184 of file MSRouteHandler.h.
Referenced by myStartElement().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedVTypeDistribution [protected]
Definition at line 184 of file MSRouteHandler.h.
Referenced by myStartElement().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedVTypes [protected]
Reimplemented in NLHandler.
Definition at line 185 of file MSRouteHandler.h.
Referenced by openVehicleTypeDistribution().
SUMOTime MSRouteHandler::myLastDepart [protected]
The insertion time of the vehicle read last.
Definition at line 139 of file MSRouteHandler.h.
Referenced by checkLastDepart(), and getLastDepart().
SUMOReal MSRouteHandler::myScale [protected]
The scaling factor (especially for inc-dua).
Definition at line 178 of file MSRouteHandler.h.
Referenced by closeVehicle(), and MSRouteHandler().
SUMOVehicleParameter* MSRouteHandler::myVehicleParameter [protected]
Definition at line 136 of file MSRouteHandler.h.
Referenced by addStop(), checkLastDepart(), closeFlow(), closePerson(), closeRoute(), closeVehicle(), myEndElement(), myStartElement(), openRoute(), and openRouteDistribution().
The documentation for this class was generated from the following files:
MSRouteHandler.h
MSRouteHandler.cpp