SUMO - Simulation of Urban MObility: NIVissimEdge::connection_position_sorter Class Reference
NIVissimEdge::connection_position_sorter Class Reference
Public Member Functions
connection_position_sorter (int edgeid)
constructor
int operator() (int c1id, int c2id) const
comparing operation
Private Attributes
int myEdgeID
The id of the edge.
Detailed Description
Sorts connections the edge participates in by their position along the given edge
Definition at line 225 of file NIVissimEdge.h.
Constructor & Destructor Documentation
NIVissimEdge::connection_position_sorter::connection_position_sorter (int edgeid) [explicit]
constructor
Definition at line 74 of file NIVissimEdge.cpp.
Member Function Documentation
int NIVissimEdge::connection_position_sorter::operator() (int c1id, int c2id) const
comparing operation
Definition at line 79 of file NIVissimEdge.cpp.
References NIVissimEdge::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getFromPosition(), NIVissimConnection::getToPosition(), myEdgeID, and SUMOReal.
Field Documentation
int NIVissimEdge::connection_position_sorter::myEdgeID [private]
The id of the edge.
Definition at line 235 of file NIVissimEdge.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
NIVissimEdge.h
NIVissimEdge.cpp