SUMO - Simulation of Urban MObility: MSTriggeredRerouter Class Reference
MSTriggeredRerouter Class Reference
Reroutes vehicles passing an edge.
#include <MSTriggeredRerouter.h>
Data Structures
struct RerouteInterval
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const RerouteInterval & getCurrentReroute (SUMOTime time) const
Returns the rerouting definition valid for the given time and vehicle.
const RerouteInterval & getCurrentReroute (SUMOTime time, SUMOVehicle &veh) const
Returns the rerouting definition valid for the given time and vehicle.
const std::string & getFileName () const
returns the current file name
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getProbability () const
Returns the rerouting probability.
SUMOReal getUserProbability () const
Returns the rerouting probability given by the user.
bool hasCurrentReroute (SUMOTime time) const
Returns whether a rerouting definition is valid for the given time.
bool hasCurrentReroute (SUMOTime time, SUMOVehicle &veh) const
Returns whether a rerouting definition is valid for the given time and vehicle.
bool inUserMode () const
Returns whether the user is setting the rerouting probability.
MSTriggeredRerouter (const std::string &id, const std::vector< MSEdge * > &edges, SUMOReal prob, const std::string &file, bool off)
Constructor.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Tries to reroute the vehicle.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void setID (const std::string &newID)
resets the id
void setUserMode (bool val)
Sets whether the process is currently steered by the user.
void setUserUsageProbability (SUMOReal prob)
Sets the probability with which a vehicle is rerouted given by the user.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~MSTriggeredRerouter ()
Destructor.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Interface methods, to be derived by subclasses
virtual bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, Notification reason)
Called if the vehicle leaves the reminder's lane.
virtual bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myEndElement (int element)
Called when a closing tag occurs.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
bool myAmInUserMode
Information whether the current rerouting probability is the user-given.
std::string myID
The name of the object.
std::vector< RerouteInterval > myIntervals
List of rerouting definition intervals.
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myProbability
The probability and the user-given probability.
SUMOReal myUserProbability
members used during loading
std::vector< MSEdge * > myCurrentClosed
List of closed edges.
RandomDistributor< MSEdge * > myCurrentEdgeProb
new destinations with probabilities
SUMOTime myCurrentIntervalBegin
The first and the last time steps of the interval.
SUMOTime myCurrentIntervalEnd
RandomDistributor< const
MSRoute * > myCurrentRouteProb
new routes with probabilities
Static Protected Attributes
static bool myHaveWarnedAboutDeprecatedClosingReroute = false
static bool myHaveWarnedAboutDeprecatedDestProbReroute = false
static bool myHaveWarnedAboutDeprecatedRouteReroute = false
Private Member Functions
MSTriggeredRerouter (const MSTriggeredRerouter &)
Invalidated copy constructor.
MSTriggeredRerouter & operator= (const MSTriggeredRerouter &)
Invalidated assignment operator.
Detailed Description
Reroutes vehicles passing an edge.
A rerouter can be positioned on a list of edges and gives vehicles which arrive one of these edges a new route.
The new route may be either chosen from a set of routes where each is chosen with a certain probability, or newly computed, either by keeping the old destination or by choosing a new one from a set of existing ones.
Definition at line 66 of file MSTriggeredRerouter.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSTriggeredRerouter::MSTriggeredRerouter (const std::string & id, const std::vector< MSEdge * > & edges, SUMOReal prob, const std::string & file, bool off)
Constructor.
Parameters:
[in] id The id of the rerouter
[in] edges The edges the rerouter is placed at
[in] prob The probability the rerouter reoutes vehicles with
[in] file The file to read the reroute definitions from
Definition at line 71 of file MSTriggeredRerouter.cpp.
References XMLSubSys::runParser(), setUserMode(), and setUserUsageProbability().
MSTriggeredRerouter::~MSTriggeredRerouter () [virtual]
Destructor.
Definition at line 101 of file MSTriggeredRerouter.cpp.
MSTriggeredRerouter::MSTriggeredRerouter (const MSTriggeredRerouter &) [private]
Invalidated copy constructor.
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const MSTriggeredRerouter::RerouteInterval & MSTriggeredRerouter::getCurrentReroute (SUMOTime time) const
Returns the rerouting definition valid for the given time and vehicle.
Definition at line 258 of file MSTriggeredRerouter.cpp.
References myIntervals.
const MSTriggeredRerouter::RerouteInterval & MSTriggeredRerouter::getCurrentReroute (SUMOTime time, SUMOVehicle & veh) const
Returns the rerouting definition valid for the given time and vehicle.
Definition at line 242 of file MSTriggeredRerouter.cpp.
References MSRoute::containsAnyOf(), SUMOVehicle::getRoute(), and myIntervals.
Referenced by GUITriggeredRerouter::drawGL(), and notifyEnter().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
SUMOReal MSTriggeredRerouter::getProbability () const
Returns the rerouting probability.
Definition at line 335 of file MSTriggeredRerouter.cpp.
References myAmInUserMode, myProbability, and myUserProbability.
Referenced by GUITriggeredRerouter::drawGL().
SUMOReal MSTriggeredRerouter::getUserProbability () const
Returns the rerouting probability given by the user.
Definition at line 341 of file MSTriggeredRerouter.cpp.
References myUserProbability.
bool MSTriggeredRerouter::hasCurrentReroute (SUMOTime time) const
Returns whether a rerouting definition is valid for the given time.
Definition at line 227 of file MSTriggeredRerouter.cpp.
References myIntervals.
bool MSTriggeredRerouter::hasCurrentReroute (SUMOTime time, SUMOVehicle & veh) const
Returns whether a rerouting definition is valid for the given time and vehicle.
Definition at line 211 of file MSTriggeredRerouter.cpp.
References MSRoute::containsAnyOf(), SUMOVehicle::getRoute(), and myIntervals.
Referenced by GUITriggeredRerouter::drawGL(), and notifyEnter().
bool MSTriggeredRerouter::inUserMode () const
Returns whether the user is setting the rerouting probability.
Definition at line 329 of file MSTriggeredRerouter.cpp.
References myAmInUserMode.
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void MSTriggeredRerouter::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 191 of file MSTriggeredRerouter.cpp.
References MSTriggeredRerouter::RerouteInterval::begin, RandomDistributor< T >::clear(), MSTriggeredRerouter::RerouteInterval::closed, MSTriggeredRerouter::RerouteInterval::edgeProbs, MSTriggeredRerouter::RerouteInterval::end, myCurrentClosed, myCurrentEdgeProb, myCurrentIntervalBegin, myCurrentIntervalEnd, myCurrentRouteProb, myIntervals, MSTriggeredRerouter::RerouteInterval::routeProbs, and SUMO_TAG_INTERVAL.
void MSTriggeredRerouter::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 106 of file MSTriggeredRerouter.cpp.
References RandomDistributor< T >::add(), MSRoute::dictionary(), MSEdge::dictionary(), Named::getID(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringSecure(), myCurrentClosed, myCurrentEdgeProb, myCurrentIntervalBegin, myCurrentIntervalEnd, myCurrentRouteProb, myHaveWarnedAboutDeprecatedClosingReroute, myHaveWarnedAboutDeprecatedDestProbReroute, myHaveWarnedAboutDeprecatedRouteReroute, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CLOSING_REROUTE__DEPRECATED, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DEST_PROB_REROUTE__DEPRECATED, SUMO_TAG_INTERVAL, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTE_PROB_REROUTE__DEPRECATED, SUMOReal, toString(), and WRITE_WARNING.
bool MSTriggeredRerouter::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) [virtual]
Tries to reroute the vehicle.
It will not try to reroute if it is a lane change because there should be another rerouter on the lane the vehicle is coming from. Returns false - the vehicle will not be rerouted again.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
always false (the vehicle will not be rerouted again)
See also:
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 272 of file MSTriggeredRerouter.cpp.
References MSTriggeredRerouter::RerouteInterval::closed, DijkstraRouterTTBase< E, V, PF >::compute(), MSEdge::dictSize(), MSTriggeredRerouter::RerouteInterval::edgeProbs, RandomDistributor< T >::get(), getCurrentReroute(), MSNet::getCurrentTimeStep(), SUMOVehicle::getEdge(), MSNet::getInstance(), MSRoute::getLastEdge(), RandomDistributor< T >::getOverallProb(), SUMOVehicle::getRoute(), MSNet::EdgeWeightsProxi::getTravelTime(), hasCurrentReroute(), myAmInUserMode, myProbability, myUserProbability, MSMoveReminder::NOTIFICATION_LANE_CHANGE, RandHelper::rand(), SUMOVehicle::replaceRoute(), MSTriggeredRerouter::RerouteInterval::routeProbs, and SUMOReal.
virtual bool MSMoveReminder::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, Notification reason) [inline, virtual, inherited]
Called if the vehicle leaves the reminder's lane.
Informs if vehicle leaves reminder lane (due to lane change, removal from the network, or leaving to the next lane). The default is to do nothing.
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also:
Notification
Returns:
True if the reminder wants to receive further info.
Reimplemented in MSDevice_Person, MSDevice_Tripinfo, MSDevice_Vehroutes, MSE2Collector, MSE3Collector::MSE3EntryReminder, MSInductLoop, MSInstantInductLoop, MSMeanData::MeanDataValues, MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 173 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual bool MSMoveReminder::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [inline, virtual, inherited]
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns:
True if vehicle hasn't passed the reminder completely.
Reimplemented in MSDevice_HBEFA, MSDevice_Person, MSDevice_Tripinfo, MSE2Collector, MSE3Collector::MSE3EntryReminder, MSE3Collector::MSE3LeaveReminder, MSInductLoop, MSInstantInductLoop, and MSMeanData::MeanDataValues.
Definition at line 148 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
MSTriggeredRerouter& MSTriggeredRerouter::operator= (const MSTriggeredRerouter &) [private]
Invalidated assignment operator.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSTriggeredRerouter::setUserMode (bool val)
Sets whether the process is currently steered by the user.
Definition at line 317 of file MSTriggeredRerouter.cpp.
References myAmInUserMode.
Referenced by MSTriggeredRerouter(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef().
void MSTriggeredRerouter::setUserUsageProbability (SUMOReal prob)
Sets the probability with which a vehicle is rerouted given by the user.
Definition at line 323 of file MSTriggeredRerouter.cpp.
References myUserProbability.
Referenced by MSTriggeredRerouter(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
bool MSTriggeredRerouter::myAmInUserMode [protected]
Information whether the current rerouting probability is the user-given.
Definition at line 178 of file MSTriggeredRerouter.h.
Referenced by GUITriggeredRerouter::drawGL(), getProbability(), inUserMode(), notifyEnter(), and setUserMode().
std::vector<MSEdge*> MSTriggeredRerouter::myCurrentClosed [protected]
List of closed edges.
Definition at line 186 of file MSTriggeredRerouter.h.
Referenced by myEndElement(), and myStartElement().
RandomDistributor<MSEdge*> MSTriggeredRerouter::myCurrentEdgeProb [protected]
new destinations with probabilities
Definition at line 188 of file MSTriggeredRerouter.h.
Referenced by myEndElement(), and myStartElement().
SUMOTime MSTriggeredRerouter::myCurrentIntervalBegin [protected]
The first and the last time steps of the interval.
Definition at line 184 of file MSTriggeredRerouter.h.
Referenced by myEndElement(), and myStartElement().
SUMOTime MSTriggeredRerouter::myCurrentIntervalEnd [protected]
Definition at line 184 of file MSTriggeredRerouter.h.
Referenced by myEndElement(), and myStartElement().
RandomDistributor<const MSRoute*> MSTriggeredRerouter::myCurrentRouteProb [protected]
new routes with probabilities
Definition at line 190 of file MSTriggeredRerouter.h.
Referenced by myEndElement(), and myStartElement().
bool MSTriggeredRerouter::myHaveWarnedAboutDeprecatedClosingReroute = false [static, protected]
Definition at line 193 of file MSTriggeredRerouter.h.
Referenced by myStartElement().
bool MSTriggeredRerouter::myHaveWarnedAboutDeprecatedDestProbReroute = false [static, protected]
Definition at line 193 of file MSTriggeredRerouter.h.
Referenced by myStartElement().
bool MSTriggeredRerouter::myHaveWarnedAboutDeprecatedRouteReroute = false [static, protected]
Definition at line 193 of file MSTriggeredRerouter.h.
Referenced by myStartElement().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::vector<RerouteInterval> MSTriggeredRerouter::myIntervals [protected]
List of rerouting definition intervals.
Definition at line 172 of file MSTriggeredRerouter.h.
Referenced by getCurrentReroute(), hasCurrentReroute(), and myEndElement().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSTriggeredRerouter::myProbability [protected]
The probability and the user-given probability.
Definition at line 175 of file MSTriggeredRerouter.h.
Referenced by GUITriggeredRerouter::drawGL(), getProbability(), and notifyEnter().
SUMOReal MSTriggeredRerouter::myUserProbability [protected]
Definition at line 175 of file MSTriggeredRerouter.h.
Referenced by GUITriggeredRerouter::drawGL(), getProbability(), getUserProbability(), notifyEnter(), and setUserUsageProbability().
The documentation for this class was generated from the following files:
MSTriggeredRerouter.h
MSTriggeredRerouter.cpp