SUMO - Simulation of Urban MObility: ROJTREdge Class Reference
ROJTREdge Class Reference
An edge the jtr-router may route through.
#include <ROJTREdge.h>
Public Types
enum EdgeType { ET_NORMAL, ET_DISTRICT, ET_SOURCE, ET_SINK }
Possible types of edges.
Public Member Functions
void addFollower (ROEdge *s)
Adds information about a connected edge.
void addFollowerProbability (ROJTREdge *follower, SUMOTime begTime, SUMOTime endTime, SUMOReal probability)
adds the information about the percentage of using a certain follower
ROJTREdge * chooseNext (const ROVehicle *const veh, SUMOTime time) const
Returns the next edge to use.
ROJTREdge (const std::string &id, RONode *from, RONode *to, unsigned int index)
Constructor.
void setTurnDefaults (const std::vector< SUMOReal > &defs)
Sets the turning definition defaults.
~ROJTREdge ()
Destructor.
Methods for getting/setting travel time and cost information
void addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a weight value.
void addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a travel time value.
SUMOReal getCO2Effort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getCOEffort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getEffort (const ROVehicle *const veh, SUMOReal time) const
Returns the effort for this edge.
ROEdge * getFollower (unsigned int pos) const
Returns the edge at the given position from the list of reachable edges.
SUMOReal getFuelEffort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getHCEffort (const ROVehicle *const veh, SUMOReal time) const
unsigned int getNoFollowing () const
Returns the number of edges this edge is connected to.
SUMOReal getNoiseEffort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getNOxEffort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getPMxEffort (const ROVehicle *const veh, SUMOReal time) const
SUMOReal getTravelTime (const ROVehicle *const veh, SUMOReal time) const
Returns the travel time for this edge.
Set-up methods
virtual void addLane (ROLane *lane)
Adds a lane to the edge while loading.
void buildTimeLines (const std::string &measure)
Builds the internal representation of the travel time/effort.
void setType (EdgeType type)
Sets the type of te edge.
Getter methods
bool allFollowersProhibit (const ROVehicle *const vehicle) const
Returns whether this edge succeding edges prohibit the given vehicle to pass them.
RONode * getFromNode () const
Returns the node this edge starts at.
const std::string & getID () const
Returns the id of the edge.
unsigned int getLaneNo () const
Returns the number of lanes this edge has.
SUMOReal getLength () const
Returns the length of the edge.
unsigned int getNumericalID () const
Returns the index (numeric id) of the edge.
SUMOReal getSpeed () const
Returns the speed allowed on this edge.
RONode * getToNode () const
Returns the node this edge ends at.
EdgeType getType () const
Returns the type of the edge.
bool isConnectedTo (const ROEdge *const e) const
returns the information whether this edge is directly connected to the given
bool prohibits (const ROVehicle *const vehicle) const
Returns whether this edge prohibits the given vehicle to pass it.
Static Public Member Functions
static ROEdge * dictionary (size_t index)
Returns the ROEdge at the index.
Protected Member Functions
bool getStoredEffort (SUMOReal time, SUMOReal &ret) const
Retrieves the stored effort.
Protected Attributes
SUMOVehicleClasses myAllowedClasses
The list of allowed vehicle classes.
ValueTimeLine< SUMOReal > myEfforts
Container storing passing time varying over time for the edge.
std::vector< ROEdge * > myFollowingEdges
List of edges that may be approached from this edge.
RONode * myFromNode
The nodes this edge is connecting.
std::string myID
The id of the edge.
unsigned int myIndex
The index (numeric id) of the edge.
bool myInterpolate
Information whether to interpolate at interval boundaries.
std::vector< ROLane * > myLanes
This edge's lanes.
SUMOReal myLength
The length of the edge.
SUMOVehicleClasses myNotAllowedClasses
The list of disallowed vehicle classes.
SUMOReal mySpeed
The maximum speed allowed on this edge.
RONode * myToNode
ValueTimeLine< SUMOReal > myTravelTimes
Container storing passing time varying over time for the edge.
EdgeType myType
The type of the edge.
bool myUseBoundariesOnOverrideE
Whether overriding weight boundaries shall be reported.
bool myUseBoundariesOnOverrideTT
Whether overriding weight boundaries shall be reported.
bool myUsingETimeLine
Information whether the time line shall be used instead of the length value.
bool myUsingTTTimeLine
Information whether the time line shall be used instead of the length value.
Static Protected Attributes
static std::vector< ROEdge * > myEdges
static bool myHaveEWarned = false
Information whether the edge has reported missing weights.
static bool myHaveTTWarned = false
Information whether the edge has reported missing weights.
Private Types
typedef std::map< ROJTREdge
*, ValueTimeLine< SUMOReal > * > FollowerUsageCont
Definition of a map that stores the probabilities of using a certain follower over time.
Private Member Functions
ROJTREdge & operator= (const ROJTREdge &src)
invalidated assignment operator
ROJTREdge (const ROJTREdge &src)
invalidated copy constructor
Private Attributes
FollowerUsageCont myFollowingDefs
Storage for the probabilities of using a certain follower over time.
std::vector< SUMOReal > myParsedTurnings
The defaults for turnings.
Detailed Description
An edge the jtr-router may route through.
A router edge extended by the definition about the probability a vehicle chooses a certain following edge over time.
Definition at line 57 of file ROJTREdge.h.
Member Typedef Documentation
typedef std::map<ROJTREdge*, ValueTimeLine<SUMOReal>*> ROJTREdge::FollowerUsageCont [private]
Definition of a map that stores the probabilities of using a certain follower over time.
Definition at line 113 of file ROJTREdge.h.
Member Enumeration Documentation
enum ROEdge::EdgeType [inherited]
Possible types of edges.
Enumerator:
ET_NORMAL
A normal edge.
ET_DISTRICT
An edge representing a whole district.
ET_SOURCE
An edge where vehicles are inserted at (no vehicle may come from back).
ET_SINK
An edge where vehicles disappear (no vehicle may leave this edge).
Definition at line 70 of file ROEdge.h.
Constructor & Destructor Documentation
ROJTREdge::ROJTREdge (const std::string & id, RONode * from, RONode * to, unsigned int index)
Constructor.
Parameters:
[in] id The id of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] index The numeric id of the edge
Definition at line 48 of file ROJTREdge.cpp.
ROJTREdge::~ROJTREdge ()
Destructor.
Definition at line 52 of file ROJTREdge.cpp.
References myFollowingDefs.
ROJTREdge::ROJTREdge (const ROJTREdge & src) [private]
invalidated copy constructor
Member Function Documentation
void ROEdge::addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd) [inherited]
Adds a weight value.
Parameters:
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 118 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myEfforts, and ROEdge::myUsingETimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight().
void ROJTREdge::addFollower (ROEdge * s) [virtual]
Adds information about a connected edge.
Makes this edge know the given following edge. Calls ROEdge::addFollower.
Additionally it generates the entry for the given following edge in myFollowingDefs.
Parameters:
[in] s The following edge
See also:
ROEdge::addFollower
Reimplemented from ROEdge.
Definition at line 60 of file ROJTREdge.cpp.
References myFollowingDefs.
void ROJTREdge::addFollowerProbability (ROJTREdge * follower, SUMOTime begTime, SUMOTime endTime, SUMOReal probability)
adds the information about the percentage of using a certain follower
Parameters:
[in] follower The following edge
[in] begTime Time begin for which this probability is valid
[in] endTime Time end for which this probability is valid
[in] probability The probability to use the given follower
Definition at line 70 of file ROJTREdge.cpp.
References ROEdge::getID(), myFollowingDefs, and WRITE_ERROR.
Referenced by ROJTRTurnDefLoader::addToEdge().
void ROEdge::addLane (ROLane * lane) [virtual, inherited]
Adds a lane to the edge while loading.
The lane's length is adapted. Additionally, the information about allowed/disallowed vehicle classes is patched using the information stored in the lane.
Parameters:
[in] lane The lane to add
Todo:
What about vehicle-type aware connections?
Definition at line 84 of file ROEdge.cpp.
References ROLane::getAllowedClasses(), ROLane::getLength(), ROLane::getNotAllowedClasses(), ROLane::getSpeed(), ROEdge::myAllowedClasses, ROEdge::myLanes, ROEdge::myLength, ROEdge::myNotAllowedClasses, ROEdge::mySpeed, and SUMOReal.
Referenced by RONetHandler::parseLane().
void ROEdge::addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd) [inherited]
Adds a travel time value.
Parameters:
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 125 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myTravelTimes, and ROEdge::myUsingTTTimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight().
bool ROEdge::allFollowersProhibit (const ROVehicle *const vehicle) const [inherited]
Returns whether this edge succeding edges prohibit the given vehicle to pass them.
Parameters:
[in] vehicle The vehicle for which the information has to be returned
Returns:
Whether the vehicle may continue its route on any of the following edges
Definition at line 372 of file ROEdge.cpp.
References ROEdge::myFollowingEdges.
Referenced by chooseNext().
void ROEdge::buildTimeLines (const std::string & measure) [inherited]
Builds the internal representation of the travel time/effort.
Should be called after weights / travel times have been loaded.
In the case "weight-attribute" is one of "CO", "CO2", "HC", "NOx", "PMx", or "fuel" the proper value (departs/s) is computed and multiplied with the travel time.
Parameters:
[in] measure The name of the measure to use.
Definition at line 341 of file ROEdge.cpp.
References HelpersHBEFA::computeCO(), HelpersHBEFA::computeCO2(), HelpersHBEFA::computeFuel(), HelpersHBEFA::computeHC(), HelpersHBEFA::computeNOx(), HelpersHBEFA::computePMx(), ValueTimeLine< T >::fillGaps(), ROEdge::myEfforts, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUseBoundariesOnOverrideE, ROEdge::myUseBoundariesOnOverrideTT, ROEdge::myUsingETimeLine, ROEdge::myUsingTTTimeLine, SUMOReal, and SVE_UNKNOWN.
ROJTREdge * ROJTREdge::chooseNext (const ROVehicle *const veh, SUMOTime time) const
Returns the next edge to use.
Parameters:
[in] veh The vehicle to choose the next edge for
[in] time The time at which the next edge shall be entered
Returns:
The chosen edge
Definition at line 82 of file ROJTREdge.cpp.
References RandomDistributor< T >::add(), ROEdge::allFollowersProhibit(), RandomDistributor< T >::get(), RandomDistributor< T >::getOverallProb(), myFollowingDefs, ROEdge::myFollowingEdges, myParsedTurnings, and ROEdge::prohibits().
Referenced by ROJTRRouter::compute().
ROEdge * ROEdge::dictionary (size_t index) [static, inherited]
Returns the ROEdge at the index.
Definition at line 383 of file ROEdge.cpp.
References ROEdge::myEdges.
SUMOReal ROEdge::getCO2Effort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 180 of file ROEdge.cpp.
References HelpersHBEFA::computeCO2(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
SUMOReal ROEdge::getCOEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 164 of file ROEdge.cpp.
References HelpersHBEFA::computeCO(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
SUMOReal ROEdge::getEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Returns the effort for this edge.
Parameters:
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned [s]
Returns:
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 132 of file ROEdge.cpp.
References ROEdge::getStoredEffort(), ROEdge::myLength, ROEdge::mySpeed, SUMOReal, and UNUSED_PARAMETER.
ROEdge* ROEdge::getFollower (unsigned int pos) const [inline, inherited]
Returns the edge at the given position from the list of reachable edges.
Parameters:
[in] pos The position of the list within the list of following
Returns:
The following edge, stored at position pos
Definition at line 272 of file ROEdge.h.
References ROEdge::myFollowingEdges.
Referenced by RODFRouteCont::addAllEndFollower(), and RODFNet::buildApproachList().
RONode* ROEdge::getFromNode () const [inline, inherited]
Returns the node this edge starts at.
Returns:
The node this edge starts at
Definition at line 198 of file ROEdge.h.
References ROEdge::myFromNode.
Referenced by RODFNet::buildApproachList(), and AGPosition::compute2dPosition().
SUMOReal ROEdge::getFuelEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 244 of file ROEdge.cpp.
References HelpersHBEFA::computeFuel(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
SUMOReal ROEdge::getHCEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 212 of file ROEdge.cpp.
References HelpersHBEFA::computeHC(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
const std::string& ROEdge::getID () const [inline, inherited]
Returns the id of the edge.
Returns:
This edge's id
Definition at line 150 of file ROEdge.h.
References ROEdge::myID.
Referenced by RONet::addEdge(), addFollowerProbability(), RODFNet::buildApproachList(), RODFNet::buildEdgeFlowMap(), ROJTRRouter::compute(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), AGStreet::getName(), and AGStreet::print().
unsigned int ROEdge::getLaneNo () const [inline, inherited]
Returns the number of lanes this edge has.
Returns:
This edge's number of lanes
Definition at line 190 of file ROEdge.h.
References ROEdge::myLanes.
Referenced by RODFDetectorHandler::myStartElement().
SUMOReal ROEdge::getLength () const [inline, inherited]
Returns the length of the edge.
Returns:
This edge's length
Definition at line 167 of file ROEdge.h.
References ROEdge::myLength.
Referenced by AGStreet::AGStreet(), RODFNet::buildRoutes(), RODFNet::getAbsPos(), AGStreet::getLength(), and AGStreet::print().
unsigned int ROEdge::getNoFollowing () const [inherited]
Returns the number of edges this edge is connected to.
If this edge's type is set to "sink", 0 is returned, otherwise the number of edges stored in "myFollowingEdges".
Returns:
The number of edges following this edge
Definition at line 301 of file ROEdge.cpp.
References ROEdge::ET_SINK, ROEdge::getType(), and ROEdge::myFollowingEdges.
Referenced by RODFRouteCont::addAllEndFollower(), and RODFNet::buildApproachList().
SUMOReal ROEdge::getNoiseEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 260 of file ROEdge.cpp.
References HelpersHarmonoise::computeNoise(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
SUMOReal ROEdge::getNOxEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 228 of file ROEdge.cpp.
References HelpersHBEFA::computeNOx(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
unsigned int ROEdge::getNumericalID () const [inline, inherited]
Returns the index (numeric id) of the edge.
Returns:
This edge's numerical id
Definition at line 174 of file ROEdge.h.
References ROEdge::myIndex.
SUMOReal ROEdge::getPMxEffort (const ROVehicle *const veh, SUMOReal time) const [inherited]
Definition at line 196 of file ROEdge.cpp.
References HelpersHBEFA::computePMx(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), ROEdge::getTravelTime(), ROVehicle::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMOReal, and SVE_UNKNOWN.
Referenced by computeRoutes().
SUMOReal ROEdge::getSpeed () const [inline, inherited]
Returns the speed allowed on this edge.
Returns:
The speed allowed on this edge
Definition at line 182 of file ROEdge.h.
References ROEdge::mySpeed.
Referenced by RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), RODFNet::computeRoutesFor(), RODFNet::isDestination(), RODFNet::isFalseSource(), and RODFNet::isSource().
bool ROEdge::getStoredEffort (SUMOReal time, SUMOReal & ret) const [protected, inherited]
Retrieves the stored effort.
Parameters:
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned
Returns:
Whether the effort is given
Definition at line 276 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getSplitTime(), ValueTimeLine< T >::getValue(), ROEdge::myEfforts, ROEdge::myHaveEWarned, ROEdge::myID, ROEdge::myInterpolate, ROEdge::myTravelTimes, ROEdge::myUsingETimeLine, SUMOReal, toString(), and WRITE_WARNING.
Referenced by ROEdge::getCO2Effort(), ROEdge::getCOEffort(), ROEdge::getEffort(), ROEdge::getFuelEffort(), ROEdge::getHCEffort(), ROEdge::getNoiseEffort(), ROEdge::getNOxEffort(), and ROEdge::getPMxEffort().
RONode* ROEdge::getToNode () const [inline, inherited]
Returns the node this edge ends at.
Returns:
The node this edge ends at
Definition at line 206 of file ROEdge.h.
References ROEdge::myToNode.
Referenced by RODFNet::buildApproachList(), and AGPosition::compute2dPosition().
SUMOReal ROEdge::getTravelTime (const ROVehicle *const veh, SUMOReal time) const [inherited]
Returns the travel time for this edge.
Parameters:
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Returns:
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 143 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getSplitTime(), ValueTimeLine< T >::getValue(), ROEdge::myHaveTTWarned, ROEdge::myID, ROEdge::myInterpolate, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUsingTTTimeLine, SUMOReal, toString(), and WRITE_WARNING.
Referenced by ROJTRRouter::compute(), computeRoutes(), ROEdge::getCO2Effort(), ROEdge::getCOEffort(), ROEdge::getFuelEffort(), ROEdge::getHCEffort(), ROEdge::getNOxEffort(), and ROEdge::getPMxEffort().
EdgeType ROEdge::getType () const [inline, inherited]
Returns the type of the edge.
Returns:
This edge's type
See also:
EdgeType
Definition at line 159 of file ROEdge.h.
References ROEdge::myType.
Referenced by RONet::checkSourceAndDestinations(), ROJTRRouter::compute(), and ROEdge::getNoFollowing().
bool ROEdge::isConnectedTo (const ROEdge *const e) const [inline, inherited]
returns the information whether this edge is directly connected to the given
Parameters:
[in] e The edge which may be connected
Returns:
Whether the given edge is a direct successor to this one
Definition at line 216 of file ROEdge.h.
References ROEdge::myFollowingEdges.
ROJTREdge& ROJTREdge::operator= (const ROJTREdge & src) [private]
invalidated assignment operator
bool ROEdge::prohibits (const ROVehicle *const vehicle) const [inherited]
Returns whether this edge prohibits the given vehicle to pass it.
Parameters:
[in] vehicle The vehicle for which the information has to be returned
Returns:
Whether the vehicle must not enter this edge
Definition at line 316 of file ROEdge.cpp.
References DEFAULT_VEH_CLASS, ROVehicle::getType(), ROEdge::myAllowedClasses, ROEdge::myNotAllowedClasses, SVC_UNKNOWN, and SUMOVTypeParameter::vehicleClass.
Referenced by chooseNext(), and ROJTRRouter::compute().
void ROJTREdge::setTurnDefaults (const std::vector< SUMOReal > & defs)
Sets the turning definition defaults.
Parameters:
[in] def The turning percentage defaults
Definition at line 117 of file ROJTREdge.cpp.
References ROEdge::myFollowingEdges, myParsedTurnings, and SUMOReal.
void ROEdge::setType (ROEdge::EdgeType type) [inherited]
Sets the type of te edge.
Parameters:
[in] type The new type for the edge
Definition at line 310 of file ROEdge.cpp.
References ROEdge::myType.
Referenced by loadJTRDefinitions(), ROJTRTurnDefLoader::myCharacters(), ROJTRTurnDefLoader::myStartElement(), RONetHandler::parseDistrict(), and RONetHandler::parseEdge().
Field Documentation
SUMOVehicleClasses ROEdge::myAllowedClasses [protected, inherited]
The list of allowed vehicle classes.
Definition at line 367 of file ROEdge.h.
Referenced by ROEdge::addLane(), and ROEdge::prohibits().
std::vector< ROEdge * > ROEdge::myEdges [static, protected, inherited]
Definition at line 375 of file ROEdge.h.
Referenced by ROEdge::dictionary(), and ROEdge::ROEdge().
ValueTimeLine<SUMOReal> ROEdge::myEfforts [mutable, protected, inherited]
Container storing passing time varying over time for the edge.
Definition at line 345 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
FollowerUsageCont ROJTREdge::myFollowingDefs [private]
Storage for the probabilities of using a certain follower over time.
Definition at line 116 of file ROJTREdge.h.
Referenced by addFollower(), addFollowerProbability(), chooseNext(), and ~ROJTREdge().
std::vector<ROEdge*> ROEdge::myFollowingEdges [protected, inherited]
List of edges that may be approached from this edge.
Definition at line 358 of file ROEdge.h.
Referenced by ROEdge::addFollower(), ROEdge::allFollowersProhibit(), chooseNext(), ROEdge::getFollower(), ROEdge::getNoFollowing(), ROEdge::isConnectedTo(), and setTurnDefaults().
RONode* ROEdge::myFromNode [protected, inherited]
The nodes this edge is connecting.
Definition at line 373 of file ROEdge.h.
Referenced by ROEdge::getFromNode().
bool ROEdge::myHaveEWarned = false [static, protected, inherited]
Information whether the edge has reported missing weights.
Definition at line 351 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort().
bool ROEdge::myHaveTTWarned = false [static, protected, inherited]
Information whether the edge has reported missing weights.
Definition at line 342 of file ROEdge.h.
Referenced by ROEdge::getTravelTime().
std::string ROEdge::myID [protected, inherited]
The id of the edge.
Definition at line 323 of file ROEdge.h.
Referenced by ROEdge::getID(), ROEdge::getStoredEffort(), and ROEdge::getTravelTime().
unsigned int ROEdge::myIndex [protected, inherited]
The index (numeric id) of the edge.
Definition at line 329 of file ROEdge.h.
Referenced by ROEdge::getNumericalID().
bool ROEdge::myInterpolate [protected, inherited]
Information whether to interpolate at interval boundaries.
Definition at line 354 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort(), and ROEdge::getTravelTime().
std::vector<ROLane*> ROEdge::myLanes [protected, inherited]
This edge's lanes.
Definition at line 364 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::getLaneNo(), and ROEdge::~ROEdge().
SUMOReal ROEdge::myLength [protected, inherited]
The length of the edge.
Definition at line 332 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getEffort(), ROEdge::getLength(), and ROEdge::getTravelTime().
SUMOVehicleClasses ROEdge::myNotAllowedClasses [protected, inherited]
The list of disallowed vehicle classes.
Definition at line 370 of file ROEdge.h.
Referenced by ROEdge::addLane(), and ROEdge::prohibits().
std::vector<SUMOReal> ROJTREdge::myParsedTurnings [private]
The defaults for turnings.
Definition at line 119 of file ROJTREdge.h.
Referenced by chooseNext(), and setTurnDefaults().
SUMOReal ROEdge::mySpeed [protected, inherited]
The maximum speed allowed on this edge.
Definition at line 326 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getCO2Effort(), ROEdge::getCOEffort(), ROEdge::getEffort(), ROEdge::getFuelEffort(), ROEdge::getHCEffort(), ROEdge::getNoiseEffort(), ROEdge::getNOxEffort(), ROEdge::getPMxEffort(), ROEdge::getSpeed(), and ROEdge::getTravelTime().
RONode * ROEdge::myToNode [protected, inherited]
Definition at line 373 of file ROEdge.h.
Referenced by ROEdge::getToNode().
ValueTimeLine<SUMOReal> ROEdge::myTravelTimes [mutable, protected, inherited]
Container storing passing time varying over time for the edge.
Definition at line 336 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), ROEdge::getStoredEffort(), and ROEdge::getTravelTime().
EdgeType ROEdge::myType [protected, inherited]
The type of the edge.
Definition at line 361 of file ROEdge.h.
Referenced by ROEdge::getType(), and ROEdge::setType().
bool ROEdge::myUseBoundariesOnOverrideE [protected, inherited]
Whether overriding weight boundaries shall be reported.
Definition at line 349 of file ROEdge.h.
Referenced by ROEdge::buildTimeLines().
bool ROEdge::myUseBoundariesOnOverrideTT [protected, inherited]
Whether overriding weight boundaries shall be reported.
Definition at line 340 of file ROEdge.h.
Referenced by ROEdge::buildTimeLines().
bool ROEdge::myUsingETimeLine [protected, inherited]
Information whether the time line shall be used instead of the length value.
Definition at line 347 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
bool ROEdge::myUsingTTTimeLine [protected, inherited]
Information whether the time line shall be used instead of the length value.
Definition at line 338 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), and ROEdge::getTravelTime().
The documentation for this class was generated from the following files:
ROJTREdge.h
ROJTREdge.cpp