SUMO - Simulation of Urban MObility: ODDistrictHandler Class Reference
ODDistrictHandler Class Reference
An XML-Handler for districts.
#include <ODDistrictHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
ODDistrictHandler (ODDistrictCont &cont, const std::string &file)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
~ODDistrictHandler ()
Destructor.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myEndElement (int element)
Called when a closing tag occurs.
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called when an opening-tag occurs.
Private Member Functions
void addSink (const SUMOSAXAttributes &attrs)
Adds a read sink to the current district.
void addSource (const SUMOSAXAttributes &attrs)
Adds a read source to the current district.
void closeDistrict ()
Closes the processing of the current district.
ODDistrictHandler (const ODDistrictHandler &s)
invalidated copy constructor
void openDistrict (const SUMOSAXAttributes &attrs)
Begins the parsing of a district.
ODDistrictHandler & operator= (const ODDistrictHandler &s)
invalidated assignment operator
std::pair< std::string, SUMOReal > parseConnection (const SUMOSAXAttributes &attrs)
Returns the id and weight for a sink/source.
Private Attributes
ODDistrictCont & myContainer
The container to add read districts to.
ODDistrict * myCurrentDistrict
The currently parsed district.
bool myHaveWarnedAboutDeprecatedDistrict
bool myHaveWarnedAboutDeprecatedDSink
bool myHaveWarnedAboutDeprecatedDSource
Detailed Description
An XML-Handler for districts.
This SUMOSAXHandler parses districts and their sinks and sources from and stores them into a the district container given at initialisation.
Definition at line 57 of file ODDistrictHandler.h.
Constructor & Destructor Documentation
ODDistrictHandler::ODDistrictHandler (ODDistrictCont & cont, const std::string & file)
Constructor.
Saves the given district containe in order to fill it.
Parameters:
[in] cont The container of districts to fill
[in] file The file that will be processed
Definition at line 53 of file ODDistrictHandler.cpp.
ODDistrictHandler::~ODDistrictHandler ()
Destructor.
Definition at line 59 of file ODDistrictHandler.cpp.
ODDistrictHandler::ODDistrictHandler (const ODDistrictHandler & s) [private]
invalidated copy constructor
Member Function Documentation
void ODDistrictHandler::addSink (const SUMOSAXAttributes & attrs) [private]
Adds a read sink to the current district.
Tries to get the id and the weight of the currently parsed sink from the attributes using getValues. If the retrieval could be done without errors (weight>=0), the so retrieved weighted sink is added to myCurrentDistrict using addSink. (getValues checks whether myCurrentDistrict is valid)
Parameters:
[in] attrs Attributes of the currently opened element
Todo:
Checking whether myCurrentDistrict is valid through getValues is not quite nice
Definition at line 127 of file ODDistrictHandler.cpp.
References ODDistrict::addSink(), myCurrentDistrict, and parseConnection().
Referenced by myStartElement().
void ODDistrictHandler::addSource (const SUMOSAXAttributes & attrs) [private]
Adds a read source to the current district.
Tries to get the id and the weight of the currently parsed source from the attributes using getValues. If the retrieval could be done without errors (weight>=0), the so retrieved weighted source is added to myCurrentDistrict using addSource. (getValues checks whether myCurrentDistrict is valid)
Parameters:
[in] attrs Attributes of the currently opened element
Todo:
Checking whether myCurrentDistrict is valid through getValues is not quite nice
Definition at line 118 of file ODDistrictHandler.cpp.
References ODDistrict::addSource(), myCurrentDistrict, and parseConnection().
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void ODDistrictHandler::closeDistrict () [private]
Closes the processing of the current district.
Adds myCurrentDistrict to myContainer.
Definition at line 163 of file ODDistrictHandler.cpp.
References NamedObjectCont< T >::add(), Named::getID(), myContainer, and myCurrentDistrict.
Referenced by myEndElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void ODDistrictHandler::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Processes district elements via closeDistrict.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If an error within the parsed file occurs
Reimplemented from GenericSAXHandler.
Definition at line 97 of file ODDistrictHandler.cpp.
References closeDistrict(), SUMO_TAG_DISTRICT__DEPRECATED, and SUMO_TAG_TAZ.
void ODDistrictHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called when an opening-tag occurs.
Processes district elements via openDistrict, their sinks (via addSink) and sources (via addSource).
Parameters:
[in] element The enum of the currently opened element
[in] attrs Attributes of the currently opened element
Exceptions:
ProcessError If an error within the parsed file occurs
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 63 of file ODDistrictHandler.cpp.
References addSink(), addSource(), myHaveWarnedAboutDeprecatedDistrict, myHaveWarnedAboutDeprecatedDSink, myHaveWarnedAboutDeprecatedDSource, openDistrict(), SUMO_TAG_DISTRICT__DEPRECATED, SUMO_TAG_DSINK__DEPRECATED, SUMO_TAG_DSOURCE__DEPRECATED, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, toString(), and WRITE_WARNING.
void ODDistrictHandler::openDistrict (const SUMOSAXAttributes & attrs) [private]
Begins the parsing of a district.
Tries to retrieve the id of a district, adds a message to the error handler if this fails. Otherwise builds a new district with this id at myCurrentDistrict.
Parameters:
[in] attrs Attributes of the currently opened element
Definition at line 105 of file ODDistrictHandler.cpp.
References SUMOSAXAttributes::getStringReporting(), myCurrentDistrict, and SUMO_ATTR_ID.
Referenced by myStartElement().
ODDistrictHandler& ODDistrictHandler::operator= (const ODDistrictHandler & s) [private]
invalidated assignment operator
std::pair< std::string, SUMOReal > ODDistrictHandler::parseConnection (const SUMOSAXAttributes & attrs) [private]
Returns the id and weight for a sink/source.
Checks whether myCurrentDistrict (the currently processed district) is !=0; in this case, both the id and the weight are parsed. If one of them is missing or the weight is not numerical, an error is generated and reported to MsgHandler. The "type"-parameter is used in order to inform the user whether a source or a sink was processed. In the case of an error, the returned weight is -1.
If no error occurs, the correct id and weight are returned.
Parameters:
[in] attrs Attributes of the currently opened element
[in] type The type of the currntly processed connection (sink/source)
Returns:
The id and the weight of a connection
Definition at line 137 of file ODDistrictHandler.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), myCurrentDistrict, SUMO_ATTR_ID, SUMO_ATTR_WEIGHT, SUMOReal, and WRITE_ERROR.
Referenced by addSink(), and addSource().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
ODDistrictCont& ODDistrictHandler::myContainer [private]
The container to add read districts to.
Definition at line 167 of file ODDistrictHandler.h.
Referenced by closeDistrict().
ODDistrict* ODDistrictHandler::myCurrentDistrict [private]
The currently parsed district.
Definition at line 170 of file ODDistrictHandler.h.
Referenced by addSink(), addSource(), closeDistrict(), openDistrict(), and parseConnection().
bool ODDistrictHandler::myHaveWarnedAboutDeprecatedDistrict [private]
Definition at line 172 of file ODDistrictHandler.h.
Referenced by myStartElement().
bool ODDistrictHandler::myHaveWarnedAboutDeprecatedDSink [private]
Definition at line 172 of file ODDistrictHandler.h.
Referenced by myStartElement().
bool ODDistrictHandler::myHaveWarnedAboutDeprecatedDSource [private]
Definition at line 172 of file ODDistrictHandler.h.
Referenced by myStartElement().
The documentation for this class was generated from the following files:
ODDistrictHandler.h
ODDistrictHandler.cpp