SUMO - Simulation of Urban MObility: RORDGenerator_ODAmounts::FlowDef Class Reference
RORDGenerator_ODAmounts::FlowDef Class Reference
#include <RORDGenerator_ODAmounts.h>
Public Member Functions
void addRoutes (RONet &net, SUMOTime time)
Adds routes to start within the given time into the given net.
void addSingleRoute (RONet &net, SUMOTime time)
Adds a single route to start within the given time into the given net.
bool applicableForTime (SUMOTime time) const
Returns the information whether this flow includes the given time.
FlowDef (ROVehicle *vehicle, SUMOVTypeParameter *type, RORouteDef *route, SUMOTime intBegin, SUMOTime intEnd, unsigned int vehicles2insert, bool randomize)
Constructor.
SUMOTime getIntervalEnd () const
Returns the end of the period this FlowDef describes.
~FlowDef ()
Destructor.
Private Attributes
std::vector< SUMOTime > myDepartures
The list of generated departure times in the case randomized departures are used.
unsigned int myInserted
The number of vehicles already inserted.
SUMOTime myIntervalBegin
The begin of the described interval.
SUMOTime myIntervalEnd
The end of the described interval.
bool myRandom
Information whether randomized departures are used.
RORouteDef * myRoute
(description of) the route to use
ROVehicle * myVehicle
(description of) the vehicle to insert
unsigned int myVehicle2InsertNumber
The number of vehicles to insert within the described interval.
SUMOVTypeParameter * myVehicleType
(description of) the vehicle type to use
Detailed Description
The definition of a flow.
Definition at line 120 of file RORDGenerator_ODAmounts.h.
Constructor & Destructor Documentation
RORDGenerator_ODAmounts::FlowDef::FlowDef (ROVehicle * vehicle, SUMOVTypeParameter * type, RORouteDef * route, SUMOTime intBegin, SUMOTime intEnd, unsigned int vehicles2insert, bool randomize)
Constructor.
Definition at line 63 of file RORDGenerator_ODAmounts.cpp.
References DELTA_T, myDepartures, myIntervalBegin, myIntervalEnd, myRandom, myVehicle2InsertNumber, and RandHelper::rand().
RORDGenerator_ODAmounts::FlowDef::~FlowDef ()
Destructor.
Definition at line 87 of file RORDGenerator_ODAmounts.cpp.
References myVehicle.
Member Function Documentation
void RORDGenerator_ODAmounts::FlowDef::addRoutes (RONet & net, SUMOTime time)
Adds routes to start within the given time into the given net.
Definition at line 99 of file RORDGenerator_ODAmounts.cpp.
References addSingleRoute(), DELTA_T, myDepartures, myInserted, myIntervalBegin, myIntervalEnd, myRandom, myVehicle2InsertNumber, and SUMOReal.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep().
void RORDGenerator_ODAmounts::FlowDef::addSingleRoute (RONet & net, SUMOTime time)
Adds a single route to start within the given time into the given net.
Definition at line 121 of file RORDGenerator_ODAmounts.cpp.
References RONet::addRouteDef(), RONet::addVehicle(), ROVehicle::copy(), RORouteDef::copy(), ROVehicle::getID(), myInserted, myRoute, and myVehicle.
Referenced by addRoutes().
bool RORDGenerator_ODAmounts::FlowDef::applicableForTime (SUMOTime time) const
Returns the information whether this flow includes the given time.
Definition at line 93 of file RORDGenerator_ODAmounts.cpp.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep().
SUMOTime RORDGenerator_ODAmounts::FlowDef::getIntervalEnd () const
Returns the end of the period this FlowDef describes.
Definition at line 132 of file RORDGenerator_ODAmounts.cpp.
References myIntervalEnd.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep().
Field Documentation
std::vector<SUMOTime> RORDGenerator_ODAmounts::FlowDef::myDepartures [private]
The list of generated departure times in the case randomized departures are used.
Definition at line 165 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), and FlowDef().
unsigned int RORDGenerator_ODAmounts::FlowDef::myInserted [private]
The number of vehicles already inserted.
Definition at line 162 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), and addSingleRoute().
SUMOTime RORDGenerator_ODAmounts::FlowDef::myIntervalBegin [private]
The begin of the described interval.
Definition at line 153 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), and FlowDef().
SUMOTime RORDGenerator_ODAmounts::FlowDef::myIntervalEnd [private]
The end of the described interval.
Definition at line 156 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), FlowDef(), and getIntervalEnd().
bool RORDGenerator_ODAmounts::FlowDef::myRandom [private]
Information whether randomized departures are used.
Definition at line 168 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), and FlowDef().
RORouteDef* RORDGenerator_ODAmounts::FlowDef::myRoute [private]
(description of) the route to use
Definition at line 150 of file RORDGenerator_ODAmounts.h.
Referenced by addSingleRoute().
ROVehicle* RORDGenerator_ODAmounts::FlowDef::myVehicle [private]
(description of) the vehicle to insert
Definition at line 144 of file RORDGenerator_ODAmounts.h.
Referenced by addSingleRoute(), and ~FlowDef().
unsigned int RORDGenerator_ODAmounts::FlowDef::myVehicle2InsertNumber [private]
The number of vehicles to insert within the described interval.
Definition at line 159 of file RORDGenerator_ODAmounts.h.
Referenced by addRoutes(), and FlowDef().
SUMOVTypeParameter* RORDGenerator_ODAmounts::FlowDef::myVehicleType [private]
(description of) the vehicle type to use
Definition at line 147 of file RORDGenerator_ODAmounts.h.
The documentation for this class was generated from the following files:
RORDGenerator_ODAmounts.h
RORDGenerator_ODAmounts.cpp