SUMO - Simulation of Urban MObility: VehicleToTrack Class Reference
VehicleToTrack Class Reference
#include <VehicleToTrack.h>
Public Member Functions
std::string getAsConsumption () const
std::string getBehaviour () const
std::string getCoefDrag () const
std::string getCoefRollingResistance () const
std::string getConstantLoss () const
std::string getCooperLossCoef () const
std::string getFinalPoint () const
std::string getFrontalArea () const
std::string getGearRatio () const
std::string getGearSystemEff () const
std::string getHeatingConsumption () const
std::string getIdentifier () const
std::string getInitialBattery () const
std::string getInitialPoint () const
std::string getIronLossCoef () const
std::string getLights () const
std::string getMass () const
std::string getMaxPower () const
std::string getMotorEff () const
std::string getNominalCapacity () const
std::string getNumberCells () const
std::string getOverlioad () const
std::string getPeukertCoeff () const
std::string getRadioConsumption () const
std::string getRegenRatio () const
std::string getTimeCharge () const
std::string getVehicleType () const
std::string getWidescreenCons () const
std::string getWindageLossCoef () const
void setAsConsumption (std::string asConsumption)
void setBehaviour (std::string behaviour)
void setCoefDrag (std::string coefDrag)
void setCoefRollingResistance (std::string coefRollingResistance)
void setConstantLoss (std::string constantLoss)
void setCooperLossCoef (std::string cooperLossCoef)
void setFinalPoint (std::string finalPoint)
void setFrontalArea (std::string frontalArea)
void setGearRatio (std::string gearRatio)
void setGearSystemEff (std::string gearSystemEff)
void setHeatingConsumption (std::string heatingConsumption)
void setIdentifier (std::string identifier)
void setInitialBattery (std::string initialBattery)
void setInitialPoint (std::string initialPoint)
void setIronLossCoef (std::string ironLossCoef)
void setLights (std::string lights)
void setMass (std::string mass)
void setMaxPower (std::string maxPower)
void setMotorEff (std::string motorEff)
void setNominalCapacity (std::string nominalCapacity)
void setNumberCells (std::string numberCells)
void setOverlioad (std::string overlioad)
void setPeukertCoeff (std::string peukertCoeff)
void setRadioConsumption (std::string radioConsumption)
void setRegenRatio (std::string regenRatio)
void setTimeCharge (std::string timeCharge)
void setVehicleType (std::string vehicleType)
void setWidescreenCons (std::string widescreenCons)
void setWindageLossCoef (std::string windageLossCoef)
void toString (const VehicleToTrack &vehicle)
VehicleToTrack ()
virtual ~VehicleToTrack ()
Private Attributes
std::string as_consumption
std::string behaviour
std::string coef_drag
std::string coef_rolling_resistance
std::string constant_loss
std::string cooper_loss_coef
std::string finalPoint
std::string frontal_area
std::string gear_ratio
std::string gear_system_eff
std::string heating_consumption
std::string identifier
std::string initialBattery
std::string initialPoint
std::string iron_loss_coef
std::string lights
std::string mass
std::string max_power
std::string motor_eff
std::string nominal_capacity
std::string number_cells
std::string overlioad
std::string peukert_coeff
std::string radio_consumption
std::string regen_ratio
std::string time_charge
std::string vehicleType
std::string widescreen_cons
std::string windage_loss_coef
Friends
std::ostream & operator<< (std::ostream &out, const VehicleToTrack &vehicle)
Detailed Description
Definition at line 19 of file VehicleToTrack.h.
Constructor & Destructor Documentation
VehicleToTrack::VehicleToTrack ()
Definition at line 17 of file VehicleToTrack.cpp.
VehicleToTrack::~VehicleToTrack () [virtual]
Definition at line 22 of file VehicleToTrack.cpp.
Member Function Documentation
std::string VehicleToTrack::getAsConsumption () const
Definition at line 49 of file VehicleToTrack.cpp.
References as_consumption.
std::string VehicleToTrack::getBehaviour () const [inline]
Definition at line 24 of file VehicleToTrack.h.
References behaviour.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getCoefDrag () const
Definition at line 57 of file VehicleToTrack.cpp.
References coef_drag.
std::string VehicleToTrack::getCoefRollingResistance () const
Definition at line 65 of file VehicleToTrack.cpp.
References coef_rolling_resistance.
std::string VehicleToTrack::getConstantLoss () const
Definition at line 73 of file VehicleToTrack.cpp.
References constant_loss.
std::string VehicleToTrack::getCooperLossCoef () const
Definition at line 81 of file VehicleToTrack.cpp.
References cooper_loss_coef.
std::string VehicleToTrack::getFinalPoint () const [inline]
Definition at line 34 of file VehicleToTrack.h.
References finalPoint.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getFrontalArea () const
Definition at line 89 of file VehicleToTrack.cpp.
References frontal_area.
std::string VehicleToTrack::getGearRatio () const
Definition at line 97 of file VehicleToTrack.cpp.
References gear_ratio.
std::string VehicleToTrack::getGearSystemEff () const
Definition at line 105 of file VehicleToTrack.cpp.
References gear_system_eff.
std::string VehicleToTrack::getHeatingConsumption () const
Definition at line 113 of file VehicleToTrack.cpp.
References heating_consumption.
std::string VehicleToTrack::getIdentifier () const [inline]
Definition at line 44 of file VehicleToTrack.h.
References identifier.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getInitialBattery () const [inline]
Definition at line 54 of file VehicleToTrack.h.
References initialBattery.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getInitialPoint () const [inline]
Definition at line 64 of file VehicleToTrack.h.
References initialPoint.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getIronLossCoef () const
Definition at line 121 of file VehicleToTrack.cpp.
References iron_loss_coef.
std::string VehicleToTrack::getLights () const
Definition at line 129 of file VehicleToTrack.cpp.
References lights.
std::string VehicleToTrack::getMass () const
Definition at line 137 of file VehicleToTrack.cpp.
References mass.
std::string VehicleToTrack::getMaxPower () const
Definition at line 145 of file VehicleToTrack.cpp.
References max_power.
std::string VehicleToTrack::getMotorEff () const
Definition at line 153 of file VehicleToTrack.cpp.
References motor_eff.
std::string VehicleToTrack::getNominalCapacity () const
Definition at line 161 of file VehicleToTrack.cpp.
References nominal_capacity.
std::string VehicleToTrack::getNumberCells () const
Definition at line 169 of file VehicleToTrack.cpp.
References number_cells.
std::string VehicleToTrack::getOverlioad () const [inline]
Definition at line 74 of file VehicleToTrack.h.
References overlioad.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getPeukertCoeff () const
Definition at line 177 of file VehicleToTrack.cpp.
References peukert_coeff.
std::string VehicleToTrack::getRadioConsumption () const
Definition at line 185 of file VehicleToTrack.cpp.
References radio_consumption.
std::string VehicleToTrack::getRegenRatio () const
Definition at line 193 of file VehicleToTrack.cpp.
References regen_ratio.
std::string VehicleToTrack::getTimeCharge () const
Definition at line 201 of file VehicleToTrack.cpp.
References time_charge.
std::string VehicleToTrack::getVehicleType () const [inline]
Definition at line 84 of file VehicleToTrack.h.
References vehicleType.
Referenced by operator<<(), and toString().
std::string VehicleToTrack::getWidescreenCons () const
Definition at line 209 of file VehicleToTrack.cpp.
References widescreen_cons.
std::string VehicleToTrack::getWindageLossCoef () const
Definition at line 217 of file VehicleToTrack.cpp.
References windage_loss_coef.
void VehicleToTrack::setAsConsumption (std::string asConsumption)
Definition at line 53 of file VehicleToTrack.cpp.
References as_consumption.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setBehaviour (std::string behaviour) [inline]
Definition at line 29 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setCoefDrag (std::string coefDrag)
Definition at line 61 of file VehicleToTrack.cpp.
References coef_drag.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setCoefRollingResistance (std::string coefRollingResistance)
Definition at line 69 of file VehicleToTrack.cpp.
References coef_rolling_resistance.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setConstantLoss (std::string constantLoss)
Definition at line 77 of file VehicleToTrack.cpp.
References constant_loss.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setCooperLossCoef (std::string cooperLossCoef)
Definition at line 85 of file VehicleToTrack.cpp.
References cooper_loss_coef.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setFinalPoint (std::string finalPoint) [inline]
Definition at line 39 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setFrontalArea (std::string frontalArea)
Definition at line 93 of file VehicleToTrack.cpp.
References frontal_area.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setGearRatio (std::string gearRatio)
Definition at line 101 of file VehicleToTrack.cpp.
References gear_ratio.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setGearSystemEff (std::string gearSystemEff)
Definition at line 109 of file VehicleToTrack.cpp.
References gear_system_eff.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setHeatingConsumption (std::string heatingConsumption)
Definition at line 117 of file VehicleToTrack.cpp.
References heating_consumption.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setIdentifier (std::string identifier) [inline]
Definition at line 49 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute(), and MyHandler2::startElement().
void VehicleToTrack::setInitialBattery (std::string initialBattery) [inline]
Definition at line 59 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setInitialPoint (std::string initialPoint) [inline]
Definition at line 69 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setIronLossCoef (std::string ironLossCoef)
Definition at line 125 of file VehicleToTrack.cpp.
References iron_loss_coef.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setLights (std::string lights)
Definition at line 133 of file VehicleToTrack.cpp.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setMass (std::string mass)
Definition at line 141 of file VehicleToTrack.cpp.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setMaxPower (std::string maxPower)
Definition at line 149 of file VehicleToTrack.cpp.
References max_power.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setMotorEff (std::string motorEff)
Definition at line 157 of file VehicleToTrack.cpp.
References motor_eff.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setNominalCapacity (std::string nominalCapacity)
Definition at line 165 of file VehicleToTrack.cpp.
References nominal_capacity.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setNumberCells (std::string numberCells)
Definition at line 173 of file VehicleToTrack.cpp.
References number_cells.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setOverlioad (std::string overlioad) [inline]
Definition at line 79 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setPeukertCoeff (std::string peukertCoeff)
Definition at line 181 of file VehicleToTrack.cpp.
References peukert_coeff.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setRadioConsumption (std::string radioConsumption)
Definition at line 189 of file VehicleToTrack.cpp.
References radio_consumption.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setRegenRatio (std::string regenRatio)
Definition at line 197 of file VehicleToTrack.cpp.
References regen_ratio.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setTimeCharge (std::string timeCharge)
Definition at line 205 of file VehicleToTrack.cpp.
References time_charge.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setVehicleType (std::string vehicleType) [inline]
Definition at line 89 of file VehicleToTrack.h.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setWidescreenCons (std::string widescreenCons)
Definition at line 213 of file VehicleToTrack.cpp.
References widescreen_cons.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::setWindageLossCoef (std::string windageLossCoef)
Definition at line 221 of file VehicleToTrack.cpp.
References windage_loss_coef.
Referenced by MyHandler2::processAttribute().
void VehicleToTrack::toString (const VehicleToTrack & vehicle)
Definition at line 26 of file VehicleToTrack.cpp.
References getBehaviour(), getFinalPoint(), getIdentifier(), getInitialBattery(), getInitialPoint(), getOverlioad(), and getVehicleType().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const VehicleToTrack & vehicle) [friend]
Definition at line 37 of file VehicleToTrack.cpp.
Field Documentation
std::string VehicleToTrack::as_consumption [private]
Definition at line 214 of file VehicleToTrack.h.
Referenced by getAsConsumption(), and setAsConsumption().
std::string VehicleToTrack::behaviour [private]
Definition at line 190 of file VehicleToTrack.h.
Referenced by getBehaviour().
std::string VehicleToTrack::coef_drag [private]
Definition at line 196 of file VehicleToTrack.h.
Referenced by getCoefDrag(), and setCoefDrag().
std::string VehicleToTrack::coef_rolling_resistance [private]
Definition at line 194 of file VehicleToTrack.h.
Referenced by getCoefRollingResistance(), and setCoefRollingResistance().
std::string VehicleToTrack::constant_loss [private]
Definition at line 205 of file VehicleToTrack.h.
Referenced by getConstantLoss(), and setConstantLoss().
std::string VehicleToTrack::cooper_loss_coef [private]
Definition at line 202 of file VehicleToTrack.h.
Referenced by getCooperLossCoef(), and setCooperLossCoef().
std::string VehicleToTrack::finalPoint [private]
Definition at line 188 of file VehicleToTrack.h.
Referenced by getFinalPoint().
std::string VehicleToTrack::frontal_area [private]
Definition at line 195 of file VehicleToTrack.h.
Referenced by getFrontalArea(), and setFrontalArea().
std::string VehicleToTrack::gear_ratio [private]
Definition at line 198 of file VehicleToTrack.h.
Referenced by getGearRatio(), and setGearRatio().
std::string VehicleToTrack::gear_system_eff [private]
Definition at line 199 of file VehicleToTrack.h.
Referenced by getGearSystemEff(), and setGearSystemEff().
std::string VehicleToTrack::heating_consumption [private]
Definition at line 206 of file VehicleToTrack.h.
Referenced by getHeatingConsumption(), and setHeatingConsumption().
std::string VehicleToTrack::identifier [private]
Definition at line 185 of file VehicleToTrack.h.
Referenced by getIdentifier().
std::string VehicleToTrack::initialBattery [private]
Definition at line 186 of file VehicleToTrack.h.
Referenced by getInitialBattery().
std::string VehicleToTrack::initialPoint [private]
Definition at line 187 of file VehicleToTrack.h.
Referenced by getInitialPoint().
std::string VehicleToTrack::iron_loss_coef [private]
Definition at line 203 of file VehicleToTrack.h.
Referenced by getIronLossCoef(), and setIronLossCoef().
std::string VehicleToTrack::lights [private]
Definition at line 208 of file VehicleToTrack.h.
Referenced by getLights().
std::string VehicleToTrack::mass [private]
Definition at line 193 of file VehicleToTrack.h.
Referenced by getMass().
std::string VehicleToTrack::max_power [private]
Definition at line 215 of file VehicleToTrack.h.
Referenced by getMaxPower(), and setMaxPower().
std::string VehicleToTrack::motor_eff [private]
Definition at line 197 of file VehicleToTrack.h.
Referenced by getMotorEff(), and setMotorEff().
std::string VehicleToTrack::nominal_capacity [private]
Definition at line 211 of file VehicleToTrack.h.
Referenced by getNominalCapacity(), and setNominalCapacity().
std::string VehicleToTrack::number_cells [private]
Definition at line 209 of file VehicleToTrack.h.
Referenced by getNumberCells(), and setNumberCells().
std::string VehicleToTrack::overlioad [private]
Definition at line 191 of file VehicleToTrack.h.
Referenced by getOverlioad().
std::string VehicleToTrack::peukert_coeff [private]
Definition at line 210 of file VehicleToTrack.h.
Referenced by getPeukertCoeff(), and setPeukertCoeff().
std::string VehicleToTrack::radio_consumption [private]
Definition at line 207 of file VehicleToTrack.h.
Referenced by getRadioConsumption(), and setRadioConsumption().
std::string VehicleToTrack::regen_ratio [private]
Definition at line 200 of file VehicleToTrack.h.
Referenced by getRegenRatio(), and setRegenRatio().
std::string VehicleToTrack::time_charge [private]
Definition at line 212 of file VehicleToTrack.h.
Referenced by getTimeCharge(), and setTimeCharge().
std::string VehicleToTrack::vehicleType [private]
Definition at line 189 of file VehicleToTrack.h.
Referenced by getVehicleType().
std::string VehicleToTrack::widescreen_cons [private]
Definition at line 213 of file VehicleToTrack.h.
Referenced by getWidescreenCons(), and setWidescreenCons().
std::string VehicleToTrack::windage_loss_coef [private]
Definition at line 204 of file VehicleToTrack.h.
Referenced by getWindageLossCoef(), and setWindageLossCoef().
The documentation for this class was generated from the following files:
VehicleToTrack.h
VehicleToTrack.cpp