SUMO - Simulation of Urban MObility: PCLoaderDlrNavteq Class Reference
PCLoaderDlrNavteq Class Reference
A reader of pois and polygons stored in DLR-Navteq (Elmar)-format.
#include <PCLoaderDlrNavteq.h>
Static Public Member Functions
static void loadIfSet (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois/polygons assumed to be stored as according DLR-Navteq (Elmar)-files.
Static Protected Member Functions
static void loadPOIFile (const std::string &file, OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads DLR-Navteq (Elmar)-pois from the given file.
static void loadPOIFiles (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois assumed to be stored as according DLR-Navteq (Elmar)-files.
static void loadPolyFile (const std::string &file, OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads DLR-Navteq (Elmar)-polygons from the given file.
static void loadPolyFiles (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads polygons assumed to be stored as according DLR-Navteq (Elmar)-files.
Detailed Description
A reader of pois and polygons stored in DLR-Navteq (Elmar)-format.
Reads pois stored in "pointcollection.txt" and polygons stored in "...polygons.txt"/"...water_polygons.txt", applies the given projection and network offset and stores the so build pois/polys into the given map.
Definition at line 57 of file PCLoaderDlrNavteq.h.
Member Function Documentation
void PCLoaderDlrNavteq::loadIfSet (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static]
Loads pois/polygons assumed to be stored as according DLR-Navteq (Elmar)-files.
If the option "elmar-poi-files" is set within the given options container, the files stored herein are parsed using "loadPOIFiles", assuming this option contains file paths to files containing pois stored in DLR-Navteq "pointcollection.txt"-format.
If the option "elmar-poly-files" is set within the given options container, the files stored herein are parsed using "loadPolyFiles", assuming this option contains file paths to files containing polygons stored in DLR-Navteq "...polygons.txt"/"...water_polygons.txt"-format.
Parameters:
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions:
ProcessError if something fails
Definition at line 67 of file PCLoaderDlrNavteq.cpp.
References OptionsCont::isSet(), loadPOIFiles(), and loadPolyFiles().
Referenced by main().
void PCLoaderDlrNavteq::loadPOIFile (const std::string & file, OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static, protected]
Loads DLR-Navteq (Elmar)-pois from the given file.
Parameters:
[in] file The name of the file to parse
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys to
[in] tm The type map to use for setting values of loaded polys
Exceptions:
ProcessError if something fails
Definition at line 109 of file PCLoaderDlrNavteq.cpp.
References PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, PCTypeMap::get(), OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), GeoConvHelper::getProcessing(), OptionsCont::getString(), PCTypeMap::has(), LineReader::hasMore(), PCTypeMap::TypeDef::id, PCPolyContainer::insert(), PCTypeMap::TypeDef::layer, RGBColor::parseColor(), PCTypeMap::TypeDef::prefix, StringUtils::prune(), LineReader::readLine(), toString(), and WRITE_ERROR.
Referenced by loadPOIFiles().
void PCLoaderDlrNavteq::loadPOIFiles (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static, protected]
Loads pois assumed to be stored as according DLR-Navteq (Elmar)-files.
Goes through the list of files given in "elmar-poi-files". Calls "loadPOIFile" using each of these as the first parameter.
Parameters:
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded pois to
[in] tm The type map to use for setting values of loaded pois
Exceptions:
ProcessError if something fails
Definition at line 79 of file PCLoaderDlrNavteq.cpp.
References FileHelpers::exists(), OptionsCont::getStringVector(), loadPOIFile(), PROGRESS_BEGIN_MESSAGE, and PROGRESS_DONE_MESSAGE.
Referenced by loadIfSet().
void PCLoaderDlrNavteq::loadPolyFile (const std::string & file, OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static, protected]
Loads DLR-Navteq (Elmar)-polygons from the given file.
Parameters:
[in] file The name of the file to parse
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys to
[in] tm The type map to use for setting values of loaded polys
Exceptions:
ProcessError if something fails
Definition at line 188 of file PCLoaderDlrNavteq.cpp.
References PCTypeMap::TypeDef::allowFill, PositionVector::clear(), PCTypeMap::TypeDef::color, PCPolyContainer::containsPolygon(), StringUtils::convertUmlaute(), PCTypeMap::TypeDef::discard, PCTypeMap::get(), PositionVector::getBegin(), OptionsCont::getBool(), PositionVector::getEnd(), PCPolyContainer::getEnumIDFor(), OptionsCont::getInt(), GeoConvHelper::getProcessing(), OptionsCont::getString(), StringTokenizer::getVector(), PCTypeMap::has(), LineReader::hasMore(), PCTypeMap::TypeDef::id, PCPolyContainer::insert(), PCTypeMap::TypeDef::layer, RGBColor::parseColor(), PCTypeMap::TypeDef::prefix, StringUtils::prune(), PositionVector::push_back(), LineReader::readLine(), PositionVector::size(), SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by loadPolyFiles().
void PCLoaderDlrNavteq::loadPolyFiles (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) [static, protected]
Loads polygons assumed to be stored as according DLR-Navteq (Elmar)-files.
Goes through the list of files given in "elmar-poly-files". Calls "loadPolyFile" using each of these as the first parameter.
Parameters:
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys to
[in] tm The type map to use for setting values of loaded polys
Exceptions:
ProcessError if something fails
Definition at line 94 of file PCLoaderDlrNavteq.cpp.
References FileHelpers::exists(), OptionsCont::getStringVector(), loadPolyFile(), PROGRESS_BEGIN_MESSAGE, and PROGRESS_DONE_MESSAGE.
Referenced by loadIfSet().
The documentation for this class was generated from the following files:
PCLoaderDlrNavteq.h
PCLoaderDlrNavteq.cpp