SUMO - Simulation of Urban MObility: TraCIServerAPI_InductionLoop Class Reference
TraCIServerAPI_InductionLoop Class Reference
APIs for getting/setting induction loop values via TraCI.
#include <TraCIServerAPI_InductionLoop.h>
Static Public Member Functions
static bool processGet (traci::TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa0: Get Induction Loop Variable).
Private Member Functions
TraCIServerAPI_InductionLoop & operator= (const TraCIServerAPI_InductionLoop &s)
invalidated assignment operator
TraCIServerAPI_InductionLoop (const TraCIServerAPI_InductionLoop &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting induction loop values via TraCI.
Definition at line 46 of file TraCIServerAPI_InductionLoop.h.
Constructor & Destructor Documentation
TraCIServerAPI_InductionLoop::TraCIServerAPI_InductionLoop (const TraCIServerAPI_InductionLoop & s) [private]
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_InductionLoop& TraCIServerAPI_InductionLoop::operator= (const TraCIServerAPI_InductionLoop & s) [private]
invalidated assignment operator
bool TraCIServerAPI_InductionLoop::processGet (traci::TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) [static]
Processes a get value command (Command 0xa0: Get Induction Loop Variable).
Parameters:
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 53 of file TraCIServerAPI_InductionLoop.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, MSInductLoop::collectVehiclesOnDet(), DELTA_T, MSInductLoop::VehicleData::entryTimeM, NamedObjectCont< T >::get(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSInductLoop::getCurrentSpeed(), MSInductLoop::getCurrentVehicleIDs(), MSNet::getDetectorControl(), Named::getID(), MSNet::getInstance(), MSMoveReminder::getLane(), MSInductLoop::getPosition(), MSInductLoop::getTimestepsSinceLastDetection(), MSDetectorControl::getTypedDetectors(), ID_COUNT, ID_LIST, MSInductLoop::VehicleData::idM, NamedObjectCont< T >::insertIDs(), LAST_STEP_LENGTH, LAST_STEP_MEAN_SPEED, LAST_STEP_OCCUPANCY, LAST_STEP_TIME_SINCE_DETECTION, LAST_STEP_VEHICLE_DATA, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, MSInductLoop::VehicleData::leaveTimeM, MSInductLoop::VehicleData::lengthM, RESPONSE_GET_INDUCTIONLOOP_VARIABLE, RTYPE_ERR, RTYPE_OK, SUMO_TAG_INDUCTION_LOOP, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, MSInductLoop::VehicleData::typeIDM, VAR_LANE_ID, VAR_POSITION, traci::TraCIServer::writeResponseWithLength(), and traci::TraCIServer::writeStatusCmd().
The documentation for this class was generated from the following files:
TraCIServerAPI_InductionLoop.h
TraCIServerAPI_InductionLoop.cpp