SUMO - Simulation of Urban MObility: Helper_ConvexHull.cpp File Reference
Helper_ConvexHull.cpp File Reference
#include <config.h>
#include "Helper_ConvexHull.h"
#include "Position.h"
#include "PositionVector.h"
#include <vector>
#include <utils/common/UtilExceptions.h>
#include <iostream>
Functions
PositionVector simpleHull_2D (const PositionVector &V)
Detailed Description
Author:
unknown_author
Daniel Krajzewicz
Michael Behrisch
Date:
2004-11-23
Version:
Id
Helper_ConvexHull.cpp 11671 2012-01-07 20:14:30Z behrisch
Definition in file Helper_ConvexHull.cpp.
Function Documentation
PositionVector simpleHull_2D (const PositionVector & V)
Definition at line 52 of file Helper_ConvexHull.cpp.
References isLeft(), PositionVector::push_back_noDoublePos(), and PositionVector::size().
Referenced by PositionVector::convexHull().