SUMO - Simulation of Urban MObility: GUILoadThread Class Reference
GUILoadThread Class Reference
#include <GUILoadThread.h>
Public Types
enum { ID_THREAD_EVENT }
Public Member Functions
const std::string & getFileName () const
GUILoadThread (MFXInterThreadEventClient *mw, MFXEventQue &eq, FXEX::FXThreadEvent &ev)
constructor
void load (const std::string &file, bool isNet)
begins the loading of the given file
long onThreadEvent (FXObject *, FXSelector, void *)
long onThreadSignal (FXObject *, FXSelector, void *)
void retrieveMessage (const MsgHandler::MsgType type, const std::string &msg)
Retrieves messages from the loading module.
FXint run ()
void signal (FXuint seltype)
void signal ()
virtual ~GUILoadThread ()
destructor
Static Public Member Functions
static void sleep (long ms)
Protected Member Functions
virtual bool initOptions ()
void submitEndAndCleanup (GUINet *net, SUMOTime simStartTime, SUMOTime simEndTime)
Closes the loading process.
Protected Attributes
OutputDevice * myErrorRetriever
The instances of message retriever encapsulations Needed to be deleted from the handler later on.
MFXEventQue & myEventQue
FXEX::FXThreadEvent & myEventThrow
std::string myFile
the path to load the simulation from
bool myLoadNet
Information whether only the network shall be loaded.
OutputDevice * myMessageRetriever
MFXInterThreadEventClient * myParent
the parent window to inform about the loading
OutputDevice * myWarningRetriever
Detailed Description
Definition at line 55 of file GUILoadThread.h.
Member Enumeration Documentation
anonymous enum [inherited]
Enumerator:
ID_THREAD_EVENT
Definition at line 31 of file FXSingleEventThread.h.
Constructor & Destructor Documentation
GUILoadThread::GUILoadThread (MFXInterThreadEventClient * mw, MFXEventQue & eq, FXEX::FXThreadEvent & ev)
constructor
Definition at line 75 of file GUILoadThread.cpp.
References MsgHandler::addRetriever(), MsgHandler::getErrorInstance(), MsgHandler::MT_ERROR, MsgHandler::MT_MESSAGE, MsgHandler::MT_WARNING, myErrorRetriever, myMessageRetriever, myWarningRetriever, and retrieveMessage().
GUILoadThread::~GUILoadThread () [virtual]
destructor
Definition at line 86 of file GUILoadThread.cpp.
References myErrorRetriever, myMessageRetriever, and myWarningRetriever.
Member Function Documentation
const std::string & GUILoadThread::getFileName () const
Definition at line 243 of file GUILoadThread.cpp.
References myFile.
bool GUILoadThread::initOptions () [protected, virtual]
Definition at line 200 of file GUILoadThread.cpp.
References OptionsCont::clear(), fillOptions(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), MsgHandler::inform(), myFile, myLoadNet, OptionsCont::set(), and WRITE_ERROR.
Referenced by run().
void GUILoadThread::load (const std::string & file, bool isNet)
begins the loading of the given file
Definition at line 227 of file GUILoadThread.cpp.
References myFile, and myLoadNet.
Referenced by GUIApplicationWindow::load().
long FXSingleEventThread::onThreadEvent (FXObject * , FXSelector , void *) [inherited]
Definition at line 108 of file FXSingleEventThread.cpp.
References MFXInterThreadEventClient::eventOccured(), and FXSingleEventThread::myClient.
long FXSingleEventThread::onThreadSignal (FXObject * , FXSelector , void *) [inherited]
Definition at line 94 of file FXSingleEventThread.cpp.
References PIPE_READ.
void GUILoadThread::retrieveMessage (const MsgHandler::MsgType type, const std::string & msg)
Retrieves messages from the loading module.
Definition at line 235 of file GUILoadThread.cpp.
References MFXEventQue::add(), myEventQue, myEventThrow, and FXEX::FXThreadEvent::signal().
Referenced by GUILoadThread().
FXint GUILoadThread::run () [virtual]
starts the thread the thread ends after the net has been loaded
Reimplemented from FXSingleEventThread.
Definition at line 94 of file GUILoadThread.cpp.
References MsgHandler::addRetriever(), NLBuilder::build(), MSFrame::checkOptions(), MsgHandler::clear(), MSNet::clearAll(), MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::getWarningInstance(), MsgHandler::inform(), GUINet::initGUIStructures(), initOptions(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), myErrorRetriever, myMessageRetriever, myWarningRetriever, MsgHandler::report2cerr(), MsgHandler::report2cout(), NLTriggerBuilder::setHandler(), MSFrame::setMSGlobals(), string2time(), submitEndAndCleanup(), and WRITE_ERROR.
void FXSingleEventThread::signal (FXuint seltype) [inherited]
Definition at line 83 of file FXSingleEventThread.cpp.
References FXSingleEventThread::event, PIPE_WRITE, and UNUSED_PARAMETER.
void FXSingleEventThread::signal () [inherited]
Definition at line 72 of file FXSingleEventThread.cpp.
References FXSingleEventThread::event, and PIPE_WRITE.
void FXSingleEventThread::sleep (long ms) [static, inherited]
Definition at line 122 of file FXSingleEventThread.cpp.
Referenced by GUISUMOAbstractView::makeSnapshot(), and GUIRunThread::run().
void GUILoadThread::submitEndAndCleanup (GUINet * net, SUMOTime simStartTime, SUMOTime simEndTime) [protected]
Closes the loading process.
This method is called both on success and failure. All message callbacks to this instance are removed and the parent application is informed about the loading
Definition at line 184 of file GUILoadThread.cpp.
References MFXEventQue::add(), MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), OptionsCont::getOptions(), MsgHandler::getWarningInstance(), myErrorRetriever, myEventQue, myEventThrow, myFile, myMessageRetriever, myWarningRetriever, MsgHandler::removeRetriever(), and FXEX::FXThreadEvent::signal().
Referenced by run().
Field Documentation
OutputDevice* GUILoadThread::myErrorRetriever [protected]
The instances of message retriever encapsulations Needed to be deleted from the handler later on.
Definition at line 96 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
MFXEventQue& GUILoadThread::myEventQue [protected]
Definition at line 98 of file GUILoadThread.h.
Referenced by retrieveMessage(), and submitEndAndCleanup().
FXEX::FXThreadEvent& GUILoadThread::myEventThrow [protected]
Definition at line 100 of file GUILoadThread.h.
Referenced by retrieveMessage(), and submitEndAndCleanup().
std::string GUILoadThread::myFile [protected]
the path to load the simulation from
Definition at line 92 of file GUILoadThread.h.
Referenced by getFileName(), initOptions(), load(), and submitEndAndCleanup().
bool GUILoadThread::myLoadNet [protected]
Information whether only the network shall be loaded.
Definition at line 103 of file GUILoadThread.h.
Referenced by initOptions(), and load().
OutputDevice * GUILoadThread::myMessageRetriever [protected]
Definition at line 96 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
MFXInterThreadEventClient* GUILoadThread::myParent [protected]
the parent window to inform about the loading
Definition at line 89 of file GUILoadThread.h.
OutputDevice * GUILoadThread::myWarningRetriever [protected]
Definition at line 96 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
The documentation for this class was generated from the following files:
GUILoadThread.h
GUILoadThread.cpp