SUMO - Simulation of Urban MObility: GUIVehicle::GUIVehiclePopupMenu Class Reference
GUIVehicle::GUIVehiclePopupMenu Class Reference
#include <GUIVehicle.h>
Public Member Functions
GUISUMOAbstractView * getParentView ()
return the real owner of this popup
GUIVehiclePopupMenu (GUIMainWindow &app, GUISUMOAbstractView &parent, GUIGlObject &o, std::map< GUISUMOAbstractView *, int > &additionalVisualizations)
Constructor.
long onCmdAddSelected (FXObject *, FXSelector, void *)
Called if the object shall be added to the list of selected objects.
long onCmdCenter (FXObject *, FXSelector, void *)
Called if the assigned objects shall be centered.
long onCmdCopyCursorGeoPosition (FXObject *, FXSelector, void *)
Called if the cursor geo-position shall be copied to clipboard.
long onCmdCopyCursorPosition (FXObject *, FXSelector, void *)
Called if the cursor position shall be copied to clipboard.
long onCmdCopyName (FXObject *, FXSelector, void *)
Called if the name shall be copied to clipboard.
long onCmdCopyTypedName (FXObject *, FXSelector, void *)
Called if the typed name shall be copied to clipboard.
long onCmdHideAllRoutes (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be hidden.
long onCmdHideBestLanes (FXObject *, FXSelector, void *)
Called if the vehicle's best lanes shall be hidden.
long onCmdHideCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the vehicle shall be hidden.
long onCmdRemoveSelected (FXObject *, FXSelector, void *)
Called if the object shall be removed from the list of selected objects.
long onCmdShowAllRoutes (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be shown.
long onCmdShowBestLanes (FXObject *, FXSelector, void *)
Called if the vehicle's best lanes shall be shown.
long onCmdShowCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the vehicle shall be shown.
long onCmdShowPars (FXObject *, FXSelector, void *)
Called if the parameter of this object shall be shown.
long onCmdStartTrack (FXObject *, FXSelector, void *)
Called if the vehicle shall be tracked.
long onCmdStopTrack (FXObject *, FXSelector, void *)
Called if the current shall not be tracked any longer.
~GUIVehiclePopupMenu ()
Destructor.
Protected Member Functions
GUIVehiclePopupMenu ()
default constructor needed by FOX
Protected Attributes
std::map< GUISUMOAbstractView
*, int > dummy
Needed for parameterless instantiation.
GUIMainWindow * myApplication
The main application.
Position myNetworkPosition
The position within the network the cursor was above when instanting the popup.
GUIGlObject * myObject
The object that belongs to this popup-menu.
GUISUMOAbstractView * myParent
The parent window.
std::map< GUISUMOAbstractView
*, int > & myVehiclesAdditionalVisualizations
Information which additional visualisations are enabled (per view).
Detailed Description
A popup-menu for vehicles. In comparison to the normal popup-menu, this one also allows to trigger further visualisations and to track the vehicle.
Definition at line 187 of file GUIVehicle.h.
Constructor & Destructor Documentation
GUIVehicle::GUIVehiclePopupMenu::GUIVehiclePopupMenu (GUIMainWindow & app, GUISUMOAbstractView & parent, GUIGlObject & o, std::map< GUISUMOAbstractView *, int > & additionalVisualizations)
Constructor.
Parameters:
[in] app The main window for instantiation of other windows
[in] parent The parent view for changing it
[in] o The object of interest
[in,out] additionalVisualizations Information which additional visualisations are enabled (per view)
Definition at line 134 of file GUIVehicle.cpp.
GUIVehicle::GUIVehiclePopupMenu::~GUIVehiclePopupMenu ()
Destructor.
Definition at line 141 of file GUIVehicle.cpp.
GUIVehicle::GUIVehiclePopupMenu::GUIVehiclePopupMenu () [inline, protected]
default constructor needed by FOX
Definition at line 227 of file GUIVehicle.h.
Member Function Documentation
GUISUMOAbstractView* GUIGLObjectPopupMenu::getParentView () [inline, inherited]
return the real owner of this popup
Definition at line 99 of file GUIGLObjectPopupMenu.h.
References GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdAddSelected (FXObject * , FXSelector , void *) [inherited]
Called if the object shall be added to the list of selected objects.
Definition at line 130 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISelectedStorage::select().
long GUIGLObjectPopupMenu::onCmdCenter (FXObject * , FXSelector , void *) [inherited]
Called if the assigned objects shall be centered.
Definition at line 83 of file GUIGLObjectPopupMenu.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition (FXObject * , FXSelector , void *) [inherited]
Called if the cursor geo-position shall be copied to clipboard.
Definition at line 112 of file GUIGLObjectPopupMenu.cpp.
References GeoConvHelper::cartesian2geo(), GUIUserIO::copyToClipboard(), GEO_OUTPUT_ACCURACY, GeoConvHelper::getFinal(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, toString(), Position::x(), and Position::y().
long GUIGLObjectPopupMenu::onCmdCopyCursorPosition (FXObject * , FXSelector , void *) [inherited]
Called if the cursor position shall be copied to clipboard.
Definition at line 105 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, and toString().
long GUIGLObjectPopupMenu::onCmdCopyName (FXObject * , FXSelector , void *) [inherited]
Called if the name shall be copied to clipboard.
Definition at line 91 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getMicrosimID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIGLObjectPopupMenu::onCmdCopyTypedName (FXObject * , FXSelector , void *) [inherited]
Called if the typed name shall be copied to clipboard.
Definition at line 98 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getFullName(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIVehicle::GUIVehiclePopupMenu::onCmdHideAllRoutes (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be hidden.
Definition at line 155 of file GUIVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIVehicle::removeActiveAddVisualisation(), and GUIVehicle::VO_SHOW_ALL_ROUTES.
long GUIVehicle::GUIVehiclePopupMenu::onCmdHideBestLanes (FXObject * , FXSelector , void *)
Called if the vehicle's best lanes shall be hidden.
Definition at line 190 of file GUIVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIVehicle::removeActiveAddVisualisation(), and GUIVehicle::VO_SHOW_BEST_LANES.
long GUIVehicle::GUIVehiclePopupMenu::onCmdHideCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the vehicle shall be hidden.
Definition at line 183 of file GUIVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIVehicle::removeActiveAddVisualisation(), and GUIVehicle::VO_SHOW_ROUTE.
long GUIGLObjectPopupMenu::onCmdRemoveSelected (FXObject * , FXSelector , void *) [inherited]
Called if the object shall be removed from the list of selected objects.
Definition at line 138 of file GUIGLObjectPopupMenu.cpp.
References GUISelectedStorage::deselect(), GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIVehicle::GUIVehiclePopupMenu::onCmdShowAllRoutes (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be shown.
Definition at line 145 of file GUIVehicle.cpp.
References GUIVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIVehicle::VO_SHOW_ALL_ROUTES.
long GUIVehicle::GUIVehiclePopupMenu::onCmdShowBestLanes (FXObject * , FXSelector , void *)
Called if the vehicle's best lanes shall be shown.
Definition at line 173 of file GUIVehicle.cpp.
References GUIVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIVehicle::VO_SHOW_BEST_LANES.
long GUIVehicle::GUIVehiclePopupMenu::onCmdShowCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the vehicle shall be shown.
Definition at line 163 of file GUIVehicle.cpp.
References GUIVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIVehicle::VO_SHOW_ROUTE.
long GUIGLObjectPopupMenu::onCmdShowPars (FXObject * , FXSelector , void *) [inherited]
Called if the parameter of this object shall be shown.
Definition at line 123 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
long GUIVehicle::GUIVehiclePopupMenu::onCmdStartTrack (FXObject * , FXSelector , void *)
Called if the vehicle shall be tracked.
Definition at line 198 of file GUIVehicle.cpp.
References GUIVehicle::addActiveAddVisualisation(), GUIGlObject::getGlID(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUISUMOAbstractView::startTrack(), and GUIVehicle::VO_TRACKED.
long GUIVehicle::GUIVehiclePopupMenu::onCmdStopTrack (FXObject * , FXSelector , void *)
Called if the current shall not be tracked any longer.
Definition at line 208 of file GUIVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIVehicle::removeActiveAddVisualisation(), GUISUMOAbstractView::stopTrack(), and GUIVehicle::VO_TRACKED.
Field Documentation
std::map<GUISUMOAbstractView*, int> GUIVehicle::GUIVehiclePopupMenu::dummy [protected]
Needed for parameterless instantiation.
Definition at line 223 of file GUIVehicle.h.
GUIMainWindow* GUIGLObjectPopupMenu::myApplication [protected, inherited]
The main application.
Definition at line 111 of file GUIGLObjectPopupMenu.h.
Referenced by GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), and GUIGLObjectPopupMenu::onCmdShowPars().
Position GUIGLObjectPopupMenu::myNetworkPosition [protected, inherited]
The position within the network the cursor was above when instanting the popup.
Definition at line 114 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), and GUIGLObjectPopupMenu::onCmdCopyCursorPosition().
GUIGlObject* GUIGLObjectPopupMenu::myObject [protected, inherited]
The object that belongs to this popup-menu.
Definition at line 108 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdAddSelected(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), onCmdHideAllRoutes(), onCmdHideBestLanes(), onCmdHideCurrentRoute(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), onCmdShowAllRoutes(), onCmdShowBestLanes(), onCmdShowCurrentRoute(), GUIGLObjectPopupMenu::onCmdShowPars(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), onCmdStartTrack(), onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), and GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic().
GUISUMOAbstractView* GUIGLObjectPopupMenu::myParent [protected, inherited]
The parent window.
Definition at line 105 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::getParentView(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), onCmdHideAllRoutes(), onCmdHideBestLanes(), onCmdHideCurrentRoute(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), onCmdShowAllRoutes(), onCmdShowBestLanes(), onCmdShowCurrentRoute(), GUIGLObjectPopupMenu::onCmdShowPars(), onCmdStartTrack(), and onCmdStopTrack().
std::map<GUISUMOAbstractView*, int>& GUIVehicle::GUIVehiclePopupMenu::myVehiclesAdditionalVisualizations [protected]
Information which additional visualisations are enabled (per view).
Definition at line 221 of file GUIVehicle.h.
The documentation for this class was generated from the following files:
GUIVehicle.h
GUIVehicle.cpp