SUMO - Simulation of Urban MObility: StdDefs.h File Reference
StdDefs.h File Reference
#include <config.h>
Defines
#define UNUSED_PARAMETER(x) ((void)(x))
Functions
template<typename T >
T ISNAN (T a)
template<typename T >
T MAX2 (T a, T b)
template<typename T >
T MAX3 (T a, T b, T c)
template<typename T >
T MAX4 (T a, T b, T c, T d)
template<typename T >
T MIN2 (T a, T b)
template<typename T >
T MIN3 (T a, T b, T c)
template<typename T >
T MIN4 (T a, T b, T c, T d)
Variables
const SUMOReal SUMO_const_halfLaneAndOffset = (SUMOReal)(3.2 / 2. + .1)
const SUMOReal SUMO_const_halfLaneWidth = (SUMOReal) 1.6
const SUMOReal SUMO_const_laneOffset = (SUMOReal) .1
const SUMOReal SUMO_const_laneWidth = (SUMOReal) 3.2
const SUMOReal SUMO_const_laneWidthAndOffset = (SUMOReal) 3.3
const SUMOReal SUMO_const_quarterLaneWidth = (SUMOReal) 0.8
Detailed Description
Author:
Daniel Krajzewicz
Laura Bieker
Michael Behrisch
Date:
Fri, 29.04.2005
Version:
Id
StdDefs.h 11671 2012-01-07 20:14:30Z behrisch
Definition in file StdDefs.h.
Define Documentation
#define UNUSED_PARAMETER (x) ((void)(x))
Definition at line 36 of file StdDefs.h.
Referenced by RODFDetector::buildDestinationDistribution(), MSOffTrafficLightLogic::changeStepAndDuration(), SUMOVehicleParserHelper::closeVTypeParsing(), combineCallback(), TraCIDijkstraRouter< E >::compute(), NBNodeShapeComputer::compute(), NIVissimDisturbance::dictionary(), GUIPolygon::drawGL(), GUIGlObject::drawGLAdditional(), NIImporter_DlrNavteq::EdgesHandler::EdgesHandler(), AGBusLine::generateBuses(), NIImporter_OpenDrive::geomFromArc(), NIImporter_OpenDrive::geomFromLine(), NIImporter_OpenDrive::geomFromPoly(), NIImporter_OpenDrive::geomFromSpiral(), RODFDetectorCon::getAggFlowFor(), RORDLoader_TripDefs::getEdge(), ROEdge::getEffort(), MSInternalJunction::getFoeInternalLanes(), MSInternalJunction::getFoeLinks(), MSJunctionLogic::getFoesFor(), MSJunctionLogic::getInternalFoesFor(), MSJunctionLogic::getIsCont(), GUIEdge::getParameterWindow(), MSCFModel_Wiedemann::interactionGap(), PCNetProjectionLoader::myCharacters(), NIImporter_SUMO::myCharacters(), NIImporter_OpenDrive::myCharacters(), NBLoadedSUMOTLDef::myCompute(), NIImporter_ArcView::NIImporter_ArcView(), NIImporter_Vissim::NIImporter_Vissim(), NIImporter_DlrNavteq::NodesHandler::NodesHandler(), MSMoveReminder::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSMoveReminder::notifyLeave(), MSMoveReminder::notifyMove(), MSMoveReminder::notifyMoveInternal(), RGBColor::parseColorReporting(), MSLaneSpeedTrigger::processCommand(), ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::readRoutesAtLeastUntil(), TraCIDijkstraRouter< E >::recomputeCosts(), NBNodeCont::removeIsolatedRoads(), NBEdge::replaceInConnections(), MSMeanData::resetOnly(), MSCFModel::setImperfection(), FXEX::FXThreadEvent::signal(), FXSingleEventThread::signal(), NIImporter_DlrNavteq::TrafficlightsHandler::TrafficlightsHandler(), NIXMLEdgesHandler::tryGetPosition(), MSOffTrafficLightLogic::trySwitch(), NBRequest::writeAreFoes(), NBRequest::writeResponse(), and RORoute::writeXMLDefinition().
Function Documentation
template<typename T > T ISNAN (T a) [inline]
Definition at line 95 of file StdDefs.h.
Referenced by RORouteDef_Alternatives::addAlternative().
template<typename T > T MAX2 (T a, T b) [inline]
Definition at line 60 of file StdDefs.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_PWag2009::_v(), MSCFModel_Kerner::_v(), MSCFModel_IDM::_v(), ShapeContainer::add(), RORouteDef_Alternatives::addAlternative(), IDSupplier::avoid(), RODFNet::buildEdgeFlowMap(), MSBaseVehicle::calculateArrivalPos(), RGBColor::changedBrightness(), NBNodeShapeComputer::compute(), HelpersHBEFA::compute(), Bresenham::compute(), NBNode::computeInternalLaneShape(), MSCFModel_PWag2009::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_Krauss::dawdle(), MSE2Collector::detectorUpdate(), drawAction_drawVehicleBlinker(), GUIVehicle::drawBestLanes(), MSCFModel_Krauss::followSpeed(), Distribution_Points::getAreaPerc(), MSInductLoop::getCurrentOccupancy(), MSDevice_Routing::getEffort(), GeomHelper::getMaxAngleDiff(), NIImporter_OpenDrive::OpenDriveEdge::getMaxLaneNumber(), ShapeContainer::getPOICont(), ShapeContainer::getPolygonCont(), MSLaneChanger::getRealThisLeader(), MSCFModel::getSecureGap(), MSCFModel::getSpeedAfterMaxDecel(), GUIJunctionWrapper::GUIJunctionWrapper(), MSLCM_DK2004::informBlocker(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), NBEdgeCont::joinSameNodeConnectingEdges(), MSCFModel::leftVehicleVsafe(), MAX3(), MAX4(), MSVehicle::moveChecked(), MSCFModel_PWag2009::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSPerson::MSPersonStage_Walking::MSPersonStage_Walking(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), MSLCM_DK2004::patchSpeed(), MSPerson::MSPersonStage_Walking::proceed(), TraCIServerAPI_Vehicle::processSet(), NBEdgeCont::retrievePossiblySplitted(), MSCFModel_Wiedemann::stopSpeed(), MSCFModel_Krauss::stopSpeed(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), AGFreeTime::typeFromHomeNight(), MSLCM_DK2004::wantsChangeToLeft(), MSLCM_DK2004::wantsChangeToRight(), ODMatrix::write(), NWWriter_SUMO::writeInternalEdge(), RODFDetector::writeSingleSpeedTrigger(), MSInductLoop::writeTypedXMLOutput(), and MSE2Collector::writeXMLOutput().
template<typename T > T MAX3 (T a, T b, T c) [inline]
Definition at line 74 of file StdDefs.h.
References MAX2().
Referenced by MSVehicleType::getMaxSpeedWithDeviation(), and MSPerson::MSPersonStage_Waiting::proceed().
template<typename T > T MAX4 (T a, T b, T c, T d) [inline]
Definition at line 88 of file StdDefs.h.
References MAX2().
template<typename T > T MIN2 (T a, T b) [inline]
Definition at line 54 of file StdDefs.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_Kerner::_v(), ShapeContainer::add(), RORouteDef_Alternatives::addAlternative(), NBEdge::buildInnerEdges(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), MSBaseVehicle::calculateArrivalPos(), RGBColor::changedBrightness(), MSVehicleTransfer::checkInsertions(), Bresenham::compute(), EulerSpiral::compute_es_params(), NBNodeShapeComputer::computeContinuationNodeShape(), NBNode::computeInternalLaneShape(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSCFModel_IDM::desiredSpeed(), PositionVector::distance(), GUIBusStop::drawGL(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_Kerner::followSpeed(), MSLane::freeInsertion(), MSCFModel_Wiedemann::fullspeed(), Distribution_Points::getAreaPerc(), ROEdge::getCO2Effort(), ROEdge::getCOEffort(), MSInductLoop::getCurrentOccupancy(), ROEdge::getFuelEffort(), ROEdge::getHCEffort(), getMaxSpeedRegardingNextLanes(), GeomHelper::getMinAngleDiff(), ROEdge::getNoiseEffort(), ROEdge::getNOxEffort(), ROEdge::getPMxEffort(), ShapeContainer::getPOICont(), ShapeContainer::getPolygonCont(), MSLaneChanger::getRealFollower(), MSLane::insertVehicle(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSCFModel::leftVehicleVsafe(), MSCFModel::maxNextSpeed(), MSLane::maxSpeedGapInsertion(), MIN3(), MIN4(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), MSLCM_DK2004::patchSpeed(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Lane::processGet(), MSCFModel_Wiedemann::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Kerner::stopSpeed(), AGFreeTime::typeFromHomeNight(), MSLCM_DK2004::wantsChangeToLeft(), MSLCM_DK2004::wantsChangeToRight(), MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSInductLoop::writeTypedXMLOutput(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
template<typename T > T MIN3 (T a, T b, T c) [inline]
Definition at line 67 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), MSVehicleType::getMaxSpeedWithDeviation(), MSVehicle::moveChecked(), MSCFModel_KraussOrig1::moveHelper(), and MSCFModel::moveHelper().
template<typename T > T MIN4 (T a, T b, T c, T d) [inline]
Definition at line 81 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), and GLHelper::drawBoxLines().
Variable Documentation
const SUMOReal SUMO_const_halfLaneAndOffset = (SUMOReal)(3.2 / 2. + .1)
Definition at line 46 of file StdDefs.h.
Referenced by NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), NBEdge::getMaxLaneOffsetPositionAt(), NBEdge::getMinLaneOffsetPositionAt(), NBNodeShapeComputer::replaceFirstChecking(), and NBNodeShapeComputer::replaceLastChecking().
const SUMOReal SUMO_const_halfLaneWidth = (SUMOReal) 1.6
Definition at line 42 of file StdDefs.h.
Referenced by NBNodeShapeComputer::computeContinuationNodeShape(), NBNodeShapeComputer::computeNodeShapeByCrosses(), and NBNodeShapeComputer::joinSameDirectionEdges().
const SUMOReal SUMO_const_laneOffset = (SUMOReal) .1
Definition at line 44 of file StdDefs.h.
Referenced by GUILaneWrapper::drawMarkings(), and NBEdge::width().
const SUMOReal SUMO_const_laneWidth = (SUMOReal) 3.2
Definition at line 41 of file StdDefs.h.
Referenced by NLHandler::addLane(), GUIViewTraffic::doPaintGL(), GUISUMOAbstractView::makeSnapshot(), NBNodeShapeComputer::replaceFirstChecking(), NBNodeShapeComputer::replaceLastChecking(), NBEdge::width(), and NWWriter_OpenDrive::writeNetwork().
const SUMOReal SUMO_const_laneWidthAndOffset = (SUMOReal) 3.3
Definition at line 45 of file StdDefs.h.
Referenced by NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), NBEdge::computeLaneShape(), NBEdge::getMaxLaneOffset(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::reconstructEdgeShape(), NBNodeShapeComputer::replaceFirstChecking(), and NBNodeShapeComputer::replaceLastChecking().
const SUMOReal SUMO_const_quarterLaneWidth = (SUMOReal) 0.8
Definition at line 43 of file StdDefs.h.