SUMO - Simulation of Urban MObility: testclient::TraCITestClient Class Reference
testclient::TraCITestClient Class Reference
#include <TraCITestClient.h>
Public Member Functions
bool close ()
void commandClose ()
void commandDistanceRequest (testclient::Position3D pos1, testclient::PositionRoadMap pos2, int flag)
void commandDistanceRequest (testclient::Position pos1, testclient::PositionRoadMap pos2, int flag)
void commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::Position3D pos2, int flag)
void commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::Position pos2, int flag)
void commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::PositionRoadMap pos2, int flag)
void commandDistanceRequest (testclient::Position3D pos1, testclient::Position pos2, int flag)
void commandDistanceRequest (testclient::Position pos1, testclient::Position3D pos2, int flag)
void commandDistanceRequest (testclient::Position3D pos1, testclient::Position3D pos2, int flag)
void commandDistanceRequest (testclient::Position pos1, testclient::Position pos2, int flag)
void commandGetVariable (int domID, int varID, const std::string &objID)
void commandGetVariablePlus (int domID, int varID, const std::string &objID, std::ifstream &defFile)
void commandPositionConversion (testclient::PositionRoadMap pos, int posId)
void commandPositionConversion (testclient::Position3D pos, int posId)
void commandPositionConversion (testclient::Position pos, int posId)
void commandSetValue (int domID, int varID, const std::string &objID, std::ifstream &defFile)
void commandSimulationStep2 (SUMOTime time)
void commandSubscribeVariable (int domID, const std::string &objID, int beginTime, int endTime, int varNo, std::ifstream &defFile)
bool connect (int port, std::string host="localhost")
bool run (std::string fileName, int port, std::string host="localhost")
TraCITestClient (std::string outputFileName="testclient_result.out")
~TraCITestClient ()
Private Member Functions
void commandDistanceRequest (testclient::Position *pos1_2D, testclient::Position3D *pos1_3D, testclient::PositionRoadMap *pos1_Road, testclient::Position *pos2_2D, testclient::Position3D *pos2_3D, testclient::PositionRoadMap *pos2_Road, int flag)
void commandPositionConversion (testclient::Position *pos2D, testclient::Position3D *pos3D, testclient::PositionRoadMap *posRoad, int posId)
void errorMsg (std::stringstream &msg)
bool readAndReportTypeDependent (tcpip::Storage &inMsg, int valueDataType)
bool reportResultState (tcpip::Storage &inMsg, int command, bool ignoreCommandId=false)
int setValueTypeDependant (tcpip::Storage &into, std::ifstream &defFile, std::stringstream &msg)
Parses the next value type / value pair from the stream and inserts it into the storage.
bool validateDistanceRequest (tcpip::Storage &inMsg)
bool validatePositionConversion (tcpip::Storage &inMsg)
bool validateSimulationStep2 (tcpip::Storage &inMsg)
bool validateSubscription (tcpip::Storage &inMsg)
void writeResult ()
Private Attributes
std::stringstream answerLog
std::string outputFileName
tcpip::Socket * socket
Detailed Description
Definition at line 78 of file TraCITestClient.h.
Constructor & Destructor Documentation
TraCITestClient::TraCITestClient (std::string outputFileName = "testclient_result.out")
Definition at line 64 of file TraCITestClient.cpp.
References answerLog.
TraCITestClient::~TraCITestClient ()
Definition at line 74 of file TraCITestClient.cpp.
References socket, and writeResult().
Member Function Documentation
bool TraCITestClient::close ()
Definition at line 124 of file TraCITestClient.cpp.
References socket.
Referenced by run().
void TraCITestClient::commandClose ()
Definition at line 1025 of file TraCITestClient.cpp.
References answerLog, CMD_CLOSE, errorMsg(), reportResultState(), and socket.
Referenced by run().
void TraCITestClient::commandDistanceRequest (testclient::Position * pos1_2D, testclient::Position3D * pos1_3D, testclient::PositionRoadMap * pos1_Road, testclient::Position * pos2_2D, testclient::Position3D * pos2_3D, testclient::PositionRoadMap * pos2_Road, int flag) [private]
Definition at line 549 of file TraCITestClient.cpp.
References answerLog, CMD_DISTANCEREQUEST, errorMsg(), testclient::PositionRoadMap::laneId, testclient::PositionRoadMap::pos, POSITION_2D, POSITION_3D, POSITION_ROADMAP, reportResultState(), testclient::PositionRoadMap::roadId, socket, validateDistanceRequest(), testclient::Position3D::x, testclient::Position::x, testclient::Position3D::y, testclient::Position::y, and testclient::Position3D::z.
void TraCITestClient::commandDistanceRequest (testclient::Position3D pos1, testclient::PositionRoadMap pos2, int flag)
Definition at line 542 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::Position pos1, testclient::PositionRoadMap pos2, int flag)
Definition at line 536 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::Position3D pos2, int flag)
Definition at line 524 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::Position pos2, int flag)
Definition at line 518 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::PositionRoadMap pos1, testclient::PositionRoadMap pos2, int flag)
Definition at line 530 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::Position3D pos1, testclient::Position pos2, int flag)
Definition at line 512 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::Position pos1, testclient::Position3D pos2, int flag)
Definition at line 500 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::Position3D pos1, testclient::Position3D pos2, int flag)
Definition at line 506 of file TraCITestClient.cpp.
References commandDistanceRequest().
void TraCITestClient::commandDistanceRequest (testclient::Position pos1, testclient::Position pos2, int flag)
Definition at line 494 of file TraCITestClient.cpp.
Referenced by commandDistanceRequest(), and run().
void TraCITestClient::commandGetVariable (int domID, int varID, const std::string & objID)
Definition at line 659 of file TraCITestClient.cpp.
References answerLog, errorMsg(), readAndReportTypeDependent(), reportResultState(), and socket.
Referenced by run().
void TraCITestClient::commandGetVariablePlus (int domID, int varID, const std::string & objID, std::ifstream & defFile)
Definition at line 727 of file TraCITestClient.cpp.
References answerLog, errorMsg(), readAndReportTypeDependent(), reportResultState(), setValueTypeDependant(), and socket.
Referenced by run().
void TraCITestClient::commandPositionConversion (testclient::Position * pos2D, testclient::Position3D * pos3D, testclient::PositionRoadMap * posRoad, int posId) [private]
Definition at line 413 of file TraCITestClient.cpp.
References answerLog, CMD_POSITIONCONVERSION, errorMsg(), testclient::PositionRoadMap::laneId, testclient::PositionRoadMap::pos, POSITION_2D, POSITION_3D, POSITION_ROADMAP, reportResultState(), testclient::PositionRoadMap::roadId, socket, validatePositionConversion(), testclient::Position3D::x, testclient::Position::x, testclient::Position3D::y, testclient::Position::y, and testclient::Position3D::z.
void TraCITestClient::commandPositionConversion (testclient::PositionRoadMap pos, int posId)
Definition at line 407 of file TraCITestClient.cpp.
References commandPositionConversion().
void TraCITestClient::commandPositionConversion (testclient::Position3D pos, int posId)
Definition at line 401 of file TraCITestClient.cpp.
References commandPositionConversion().
void TraCITestClient::commandPositionConversion (testclient::Position pos, int posId)
Definition at line 395 of file TraCITestClient.cpp.
Referenced by commandPositionConversion(), and run().
void TraCITestClient::commandSetValue (int domID, int varID, const std::string & objID, std::ifstream & defFile)
Definition at line 973 of file TraCITestClient.cpp.
References answerLog, errorMsg(), reportResultState(), setValueTypeDependant(), and socket.
Referenced by run().
void TraCITestClient::commandSimulationStep2 (SUMOTime time)
Definition at line 352 of file TraCITestClient.cpp.
References answerLog, CMD_SIMSTEP2, errorMsg(), reportResultState(), socket, and validateSimulationStep2().
Referenced by run().
void TraCITestClient::commandSubscribeVariable (int domID, const std::string & objID, int beginTime, int endTime, int varNo, std::ifstream & defFile)
Definition at line 801 of file TraCITestClient.cpp.
References answerLog, errorMsg(), reportResultState(), socket, and validateSubscription().
Referenced by run().
bool TraCITestClient::connect (int port, std::string host = "localhost")
Definition at line 105 of file TraCITestClient.cpp.
References errorMsg(), and socket.
Referenced by run().
void TraCITestClient::errorMsg (std::stringstream & msg) [private]
Definition at line 98 of file TraCITestClient.cpp.
References answerLog.
Referenced by commandClose(), commandDistanceRequest(), commandGetVariable(), commandGetVariablePlus(), commandPositionConversion(), commandSetValue(), commandSimulationStep2(), commandSubscribeVariable(), connect(), and run().
bool TraCITestClient::readAndReportTypeDependent (tcpip::Storage & inMsg, int valueDataType) [private]
Definition at line 1260 of file TraCITestClient.cpp.
References answerLog, testclient::BoundingBox::lowerLeft, POSITION_2D, POSITION_3D, POSITION_ROADMAP, SUMOReal, TLPHASE_GREEN, TLPHASE_RED, TLPHASE_YELLOW, TYPE_BOUNDINGBOX, TYPE_BYTE, TYPE_COLOR, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, TYPE_TLPHASELIST, TYPE_UBYTE, testclient::BoundingBox::upperRight, testclient::Position::x, and testclient::Position::y.
Referenced by commandGetVariable(), commandGetVariablePlus(), and validateSubscription().
bool TraCITestClient::reportResultState (tcpip::Storage & inMsg, int command, bool ignoreCommandId = false) [private]
Definition at line 305 of file TraCITestClient.cpp.
References answerLog, RTYPE_ERR, RTYPE_NOTIMPLEMENTED, and RTYPE_OK.
Referenced by commandClose(), commandDistanceRequest(), commandGetVariable(), commandGetVariablePlus(), commandPositionConversion(), commandSetValue(), commandSimulationStep2(), and commandSubscribeVariable().
bool TraCITestClient::run (std::string fileName, int port, std::string host = "localhost")
Definition at line 133 of file TraCITestClient.cpp.
References close(), commandClose(), commandDistanceRequest(), commandGetVariable(), commandGetVariablePlus(), commandPositionConversion(), commandSetValue(), commandSimulationStep2(), commandSubscribeVariable(), connect(), errorMsg(), flag, testclient::PositionRoadMap::laneId, testclient::PositionRoadMap::pos, testclient::PositionRoadMap::roadId, string2time(), testclient::Position3D::x, testclient::Position::x, testclient::Position3D::y, testclient::Position::y, and testclient::Position3D::z.
Referenced by main().
int TraCITestClient::setValueTypeDependant (tcpip::Storage & into, std::ifstream & defFile, std::stringstream & msg) [private]
Parses the next value type / value pair from the stream and inserts it into the storage.
Parameters:
[out] into The storage to add the value type and the value into
[in] defFile The file to read the values from
[out] msg If any error occurs, this should be filled
Returns:
The number of written bytes
Definition at line 866 of file TraCITestClient.cpp.
References POSITION_2D, POSITION_3D, POSITION_ROADMAP, REQUEST_AIRDIST, REQUEST_DRIVINGDIST, TYPE_BYTE, TYPE_COLOR, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, and TYPE_UBYTE.
Referenced by commandGetVariablePlus(), and commandSetValue().
bool TraCITestClient::validateDistanceRequest (tcpip::Storage & inMsg) [private]
Definition at line 1192 of file TraCITestClient.cpp.
References answerLog, CMD_DISTANCEREQUEST, flag, and SUMOReal.
Referenced by commandDistanceRequest().
bool TraCITestClient::validatePositionConversion (tcpip::Storage & inMsg) [private]
Definition at line 1124 of file TraCITestClient.cpp.
References answerLog, CMD_POSITIONCONVERSION, testclient::PositionRoadMap::laneId, testclient::PositionRoadMap::pos, POSITION_2D, POSITION_3D, POSITION_ROADMAP, testclient::PositionRoadMap::roadId, testclient::Position3D::x, testclient::Position::x, testclient::Position3D::y, testclient::Position::y, and testclient::Position3D::z.
Referenced by commandPositionConversion().
bool TraCITestClient::validateSimulationStep2 (tcpip::Storage & inMsg) [private]
Definition at line 1069 of file TraCITestClient.cpp.
References answerLog, and validateSubscription().
Referenced by commandSimulationStep2().
bool TraCITestClient::validateSubscription (tcpip::Storage & inMsg) [private]
Definition at line 1091 of file TraCITestClient.cpp.
References answerLog, readAndReportTypeDependent(), and RTYPE_OK.
Referenced by commandSubscribeVariable(), and validateSimulationStep2().
void TraCITestClient::writeResult () [private]
Definition at line 81 of file TraCITestClient.cpp.
References answerLog, and outputFileName.
Referenced by ~TraCITestClient().
Field Documentation
std::stringstream testclient::TraCITestClient::answerLog [private]
Definition at line 162 of file TraCITestClient.h.
Referenced by commandClose(), commandDistanceRequest(), commandGetVariable(), commandGetVariablePlus(), commandPositionConversion(), commandSetValue(), commandSimulationStep2(), commandSubscribeVariable(), errorMsg(), readAndReportTypeDependent(), reportResultState(), TraCITestClient(), validateDistanceRequest(), validatePositionConversion(), validateSimulationStep2(), validateSubscription(), and writeResult().
std::string testclient::TraCITestClient::outputFileName [private]
Definition at line 160 of file TraCITestClient.h.
Referenced by writeResult().
tcpip::Socket* testclient::TraCITestClient::socket [private]
Definition at line 158 of file TraCITestClient.h.
Referenced by close(), commandClose(), commandDistanceRequest(), commandGetVariable(), commandGetVariablePlus(), commandPositionConversion(), commandSetValue(), commandSimulationStep2(), commandSubscribeVariable(), connect(), and ~TraCITestClient().
The documentation for this class was generated from the following files:
TraCITestClient.h
TraCITestClient.cpp