SUMO - Simulation of Urban MObility: dfrouter_main.cpp File Reference
dfrouter_main.cpp File Reference
#include <config.h>
#include <xercesc/sax/SAXException.hpp>
#include <xercesc/sax/SAXParseException.hpp>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <limits.h>
#include <ctime>
#include <router/ROLoader.h>
#include <router/RONet.h>
#include "RODFEdgeBuilder.h"
#include <router/ROAbstractEdgeBuilder.h>
#include <router/ROFrame.h>
#include <utils/common/MsgHandler.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <map>
#include <vector>
#include <utils/common/SUMOTime.h>
#include <utils/common/RandomDistributor.h>
#include "RODFRouteDesc.h"
#include "RODFRouteCont.h"
#include <utils/common/StdDefs.h>
#include <router/ROEdge.h>
#include <utils/geom/Position.h>
#include "RODFDetector.h"
#include <utils/xml/SUMOSAXHandler.h>
#include "RODFDetectorFlow.h"
#include <utils/importio/NamedColumnsParser.h>
#include <utils/common/FileHelpers.h>
#include <utils/iodevices/OutputDevice.h>
Functions
int main (int argc, char **argv)
void readDetectorFlows (RODFDetectorFlows &flows, OptionsCont &oc, RODFDetectorCon &dc)
void readDetectors (RODFDetectorCon &detectors, OptionsCont &oc, RODFNet *optNet)
void startComputation (RODFNet *optNet, RODFDetectorFlows &flows, RODFDetectorCon &detectors, OptionsCont &oc)
Detailed Description
Author:
Daniel Krajzewicz
Eric Nicolay
Jakob Erdmann
Sascha Krieg
Michael Behrisch
Laura Bieker
Date:
Thu, 16.03.2006
Version:
Id
dfrouter_main.cpp 11671 2012-01-07 20:14:30Z behrisch
Definition in file dfrouter_main.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 253 of file dfrouter_main.cpp.
References RODFNet::buildApproachList(), RODFFrame::checkOptions(), SystemFrame::close(), OutputDevice::closeAll(), RODFFrame::fillOptions(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), ROLoader::loadNet(), OptionsCont::processMetaOptions(), readDetectorFlows(), readDetectors(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), startComputation(), string2time(), VERSION_STRING, and WRITE_ERROR.
void readDetectorFlows (RODFDetectorFlows & flows, OptionsCont & oc, RODFDetectorCon & dc)
Definition at line 106 of file dfrouter_main.cpp.
References FileHelpers::exists(), OptionsCont::getString(), OptionsCont::getStringVector(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, RODFDetFlowLoader::read(), and string2time().
Referenced by main().
void readDetectors (RODFDetectorCon & detectors, OptionsCont & oc, RODFNet * optNet)
Definition at line 83 of file dfrouter_main.cpp.
References FileHelpers::exists(), OptionsCont::getBool(), OptionsCont::getStringVector(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, and XMLSubSys::runParser().
Referenced by main().
void startComputation (RODFNet * optNet, RODFDetectorFlows & flows, RODFDetectorCon & detectors, OptionsCont & oc)
Definition at line 128 of file dfrouter_main.cpp.
References RODFNet::buildDetectorDependencies(), RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), RODFNet::computeTypes(), RODFDetectorCon::detectorsHaveCompleteTypes(), RODFDetectorCon::detectorsHaveRoutes(), OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getString(), RODFDetectorCon::guessEmptyFlows(), OptionsCont::isSet(), RODFDetectorFlows::printAbsolute(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, RODFNet::removeEmptyDetectors(), RODFNet::reportEmptyDetectors(), RODFNet::revalidateFlows(), RODFDetectorCon::save(), RODFDetectorCon::saveAsPOIs(), RODFDetectorCon::saveRoutes(), string2time(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), RODFDetectorCon::writeSpeedTrigger(), and RODFDetectorCon::writeValidationDetectors().
Referenced by main().