SUMO - Simulation of Urban MObility: AGActivityTripWriter Class Reference
AGActivityTripWriter Class Reference
#include <AGActivityTripWriter.h>
Public Member Functions
void addTrip (AGTrip trip)
AGActivityTripWriter (std::string file)
void initialize ()
void writeOutputFile ()
Private Member Functions
void vtypes ()
Private Attributes
std::map< std::string,
std::string > colors
std::string fileName
std::ofstream routes
Detailed Description
Definition at line 47 of file AGActivityTripWriter.h.
Constructor & Destructor Documentation
AGActivityTripWriter::AGActivityTripWriter (std::string file) [inline]
Definition at line 49 of file AGActivityTripWriter.h.
References initialize().
Member Function Documentation
void AGActivityTripWriter::addTrip (AGTrip trip)
Definition at line 61 of file AGActivityTripWriter.cpp.
References colors, AGTrip::getArr(), AGTrip::getDay(), AGTrip::getDep(), AGStreet::getName(), AGTrip::getPassed(), AGPosition::getPosition(), AGPosition::getStreet(), AGTrip::getTime(), AGTrip::getType(), AGTrip::getVehicleName(), and routes.
Referenced by AGActivityGen::generateOutputFile().
void AGActivityTripWriter::initialize ()
Definition at line 43 of file AGActivityTripWriter.cpp.
References routes, and vtypes().
Referenced by AGActivityTripWriter().
void AGActivityTripWriter::vtypes () [private]
Definition at line 50 of file AGActivityTripWriter.cpp.
References colors, and routes.
Referenced by initialize().
void AGActivityTripWriter::writeOutputFile ()
Definition at line 89 of file AGActivityTripWriter.cpp.
References routes.
Referenced by AGActivityGen::generateOutputFile().
Field Documentation
std::map<std::string, std::string> AGActivityTripWriter::colors [private]
Definition at line 62 of file AGActivityTripWriter.h.
Referenced by addTrip(), and vtypes().
std::string AGActivityTripWriter::fileName [private]
Definition at line 60 of file AGActivityTripWriter.h.
std::ofstream AGActivityTripWriter::routes [private]
Definition at line 61 of file AGActivityTripWriter.h.
Referenced by addTrip(), initialize(), vtypes(), and writeOutputFile().
The documentation for this class was generated from the following files:
AGActivityTripWriter.h
AGActivityTripWriter.cpp