SUMO - Simulation of Urban MObility: MSNoLogicJunction Class Reference
MSNoLogicJunction Class Reference
#include <MSNoLogicJunction.h>
Public Member Functions
virtual const std::vector
< MSLane * > & getFoeInternalLanes (const MSLink *const) const
virtual const std::vector
< MSLink * > & getFoeLinks (const MSLink *const) const
const std::string & getID () const
Returns the id of the junction.
const Position & getPosition () const
const PositionVector & getShape () const
Returns this junction's shape.
MSNoLogicJunction (const std::string &id, const Position &position, const PositionVector &shape, std::vector< MSLane * > incoming, std::vector< MSLane * > internal)
Constructor.
void postloadInit ()
virtual ~MSNoLogicJunction ()
Destructor.
Protected Attributes
std::vector< MSLane * > myEmptyLanes
std::vector< MSLink * > myEmptyLinks
std::string myID
The id of the junction.
Position myPosition
The position of the junction.
PositionVector myShape
The shape of the junction.
Private Member Functions
MSNoLogicJunction (const MSNoLogicJunction &)
Invalidated copy constructor.
MSNoLogicJunction & operator= (const MSNoLogicJunction &)
Invalidated assignment operator.
Private Attributes
std::vector< MSLane * > myIncomingLanes
std::vector< MSLane * > myInternalLanes
Static Private Attributes
static std::bitset< 64 > myDump
a dump container Request-setting vehicles may write into this container and responds are read from it. As responds are always true, this container is set to true for all links. This dump is also used as the mask for incoming non-first vehicles
Detailed Description
This junctions let all vehicles past through so they only should be used on junctions where incoming vehicles are no foes to each other (may drive simultaneously).
Definition at line 55 of file MSNoLogicJunction.h.
Constructor & Destructor Documentation
MSNoLogicJunction::~MSNoLogicJunction () [virtual]
Destructor.
Definition at line 71 of file MSNoLogicJunction.cpp.
MSNoLogicJunction::MSNoLogicJunction (const std::string & id, const Position & position, const PositionVector & shape, std::vector< MSLane * > incoming, std::vector< MSLane * > internal)
Constructor.
Parameters:
[in] id The id of the junction
[in] position The position of the junction
[in] shape The shape of the junction
[in] incoming The incoming lanes
[in] internal The internal lanes
Definition at line 54 of file MSNoLogicJunction.cpp.
MSNoLogicJunction::MSNoLogicJunction (const MSNoLogicJunction &) [private]
Invalidated copy constructor.
Member Function Documentation
virtual const std::vector<MSLane*>& MSJunction::getFoeInternalLanes (const MSLink * const) const [inline, virtual, inherited]
Reimplemented in MSInternalJunction, and MSRightOfWayJunction.
Definition at line 91 of file MSJunction.h.
References MSJunction::myEmptyLanes.
virtual const std::vector<MSLink*>& MSJunction::getFoeLinks (const MSLink * const) const [inline, virtual, inherited]
Reimplemented in MSInternalJunction, and MSRightOfWayJunction.
Definition at line 87 of file MSJunction.h.
References MSJunction::myEmptyLinks.
const std::string & MSJunction::getID () const [inherited]
Returns the id of the junction.
Definition at line 68 of file MSJunction.cpp.
References MSJunction::myID.
const Position & MSJunction::getPosition () const [inherited]
returns the junction's position
Definition at line 58 of file MSJunction.cpp.
References MSJunction::myPosition.
Referenced by GUIJunctionWrapper::drawGL(), GUINet::getJunctionPosition(), GUIJunctionWrapper::GUIJunctionWrapper(), and TraCIServerAPI_Junction::processGet().
const PositionVector& MSJunction::getShape () const [inline, inherited]
Returns this junction's shape.
Returns:
The shape of this junction
Definition at line 83 of file MSJunction.h.
References MSJunction::myShape.
Referenced by GUIJunctionWrapper::drawGL(), and GUIJunctionWrapper::GUIJunctionWrapper().
MSNoLogicJunction& MSNoLogicJunction::operator= (const MSNoLogicJunction &) [private]
Invalidated assignment operator.
void MSNoLogicJunction::postloadInit () [virtual]
Initialises the junction after the net was completely loaded
Reimplemented from MSJunction.
Definition at line 75 of file MSNoLogicJunction.cpp.
References myDump, myIncomingLanes, and myInternalLanes.
Field Documentation
std::bitset< 64 > MSNoLogicJunction::myDump [static, private]
a dump container Request-setting vehicles may write into this container and responds are read from it. As responds are always true, this container is set to true for all links. This dump is also used as the mask for incoming non-first vehicles
Definition at line 99 of file MSNoLogicJunction.h.
Referenced by postloadInit().
std::vector<MSLane*> MSJunction::myEmptyLanes [protected, inherited]
Definition at line 106 of file MSJunction.h.
Referenced by MSJunction::getFoeInternalLanes().
std::vector<MSLink*> MSJunction::myEmptyLinks [protected, inherited]
Definition at line 105 of file MSJunction.h.
Referenced by MSJunction::getFoeLinks().
std::string MSJunction::myID [protected, inherited]
The id of the junction.
Definition at line 97 of file MSJunction.h.
Referenced by MSJunction::getID().
std::vector<MSLane*> MSNoLogicJunction::myIncomingLanes [private]
Lanes incoming to the junction
Definition at line 80 of file MSNoLogicJunction.h.
Referenced by postloadInit().
std::vector<MSLane*> MSNoLogicJunction::myInternalLanes [private]
The junctions internal lanes
Definition at line 84 of file MSNoLogicJunction.h.
Referenced by postloadInit().
Position MSJunction::myPosition [protected, inherited]
The position of the junction.
Definition at line 100 of file MSJunction.h.
Referenced by MSJunction::getPosition().
PositionVector MSJunction::myShape [protected, inherited]
The shape of the junction.
Definition at line 103 of file MSJunction.h.
Referenced by MSJunction::getShape().
The documentation for this class was generated from the following files:
MSNoLogicJunction.h
MSNoLogicJunction.cpp