SUMO - Simulation of Urban MObility: MSInstantInductLoop Class Reference
MSInstantInductLoop Class Reference
An instantaneous induction loop.
#include <MSInstantInductLoop.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
MSInstantInductLoop (const std::string &id, OutputDevice &od, MSLane *const lane, SUMOReal positionInMeters)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void setID (const std::string &newID)
resets the id
void writeXMLDetectorProlog (OutputDevice &dev) const
Open the XML-output.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Write the generated output to the given device.
~MSInstantInductLoop ()
Destructor.
Virtual methods to implement by derived classes
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values).
virtual void reset ()
Resets collected values.
Methods inherited from MSMoveReminder
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Returns whether the detector may has to be concerned during the vehicle's further movement.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Dismisses the vehicle if it is on the detector due to a lane change.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
Protected Member Functions
void write (const char *state, SUMOReal t, SUMOVehicle &veh, SUMOReal speed, const char *add=0, SUMOReal addValue=-1)
Writes an event line.
Protected Attributes
std::map< SUMOVehicle *, SUMOReal > myEntryTimes
The last exit time.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myLastExitTime
The last exit time.
OutputDevice & myOutputDevice
The output device to use.
const SUMOReal myPosition
Detector's position on lane [m].
Private Member Functions
MSInstantInductLoop (const MSInstantInductLoop &)
Invalidated copy constructor.
MSInstantInductLoop & operator= (const MSInstantInductLoop &)
Invalidated assignment operator.
Detailed Description
An instantaneous induction loop.
See also:
MSMoveReminder
MSDetectorFileOutput
Definition at line 59 of file MSInstantInductLoop.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSInstantInductLoop::MSInstantInductLoop (const std::string & id, OutputDevice & od, MSLane *const lane, SUMOReal positionInMeters)
Constructor.
Parameters:
[in] id Unique id
[in] od The device to write to
[in] lane Lane where detector woks on.
[in] position Position of the detector within the lane.
Definition at line 52 of file MSInstantInductLoop.cpp.
References myPosition, and writeXMLDetectorProlog().
MSInstantInductLoop::~MSInstantInductLoop ()
Destructor.
Definition at line 61 of file MSInstantInductLoop.cpp.
MSInstantInductLoop::MSInstantInductLoop (const MSInstantInductLoop &) [private]
Invalidated copy constructor.
Member Function Documentation
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () [inline, virtual, inherited]
Builds the graphical representation.
Meant to be overridden by grahical versions of the detectors
Returns:
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUI_E2_ZS_CollectorOverLanes, GUIE3Collector, GUIInductLoop, and GUIInstantInductLoop.
Definition at line 121 of file MSDetectorFileOutput.h.
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) [inline, virtual, inherited]
Updates the detector (computes values).
Parameters:
[in] step The current time step
Reimplemented in MSE2Collector, MSE3Collector, MSMeanData, and MSMeanData_Harmonoise.
Definition at line 113 of file MSDetectorFileOutput.h.
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
bool MSInstantInductLoop::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) [virtual]
Returns whether the detector may has to be concerned during the vehicle's further movement.
If the detector is in front of the vehicle, true is returned. If the vehicle's front has passed the detector, false, because the vehicle is no longer relevant for the detector.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
True if vehicle is on or in front of the detector.
See also:
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 136 of file MSInstantInductLoop.cpp.
References MSVehicleType::getLengthWithGap(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), and myPosition.
bool MSInstantInductLoop::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) [virtual]
Dismisses the vehicle if it is on the detector due to a lane change.
If the vehicle is on the detector, it will be dismissed by incrementing myDismissedVehicleNumber and removing this vehicle's entering time from myVehiclesOnDet.
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also:
leaveDetectorByLaneChange
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 122 of file MSInstantInductLoop.cpp.
References MSNet::getInstance(), SUMOVehicle::getSpeed(), myEntryTimes, MSMoveReminder::NOTIFICATION_JUNCTION, STEPS2TIME, and write().
bool MSInstantInductLoop::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [virtual]
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
As soon a vehicle enters the detector, its entry time is computed and stored in myVehiclesOnDet via enterDetectorByMove. If it passes the detector, the according leaving time is computed and stored, too, using leaveDetectorByMove.
Parameters:
[in] veh Vehicle that asks this remider.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns:
True if vehicle hasn't passed the detector completely.
See also:
MSMoveReminder
MSMoveReminder::notifyMove
enterDetectorByMove
leaveDetectorByMove
Reimplemented from MSMoveReminder.
Definition at line 66 of file MSInstantInductLoop.cpp.
References MSNet::getInstance(), MSVehicleType::getLengthWithGap(), SUMOVehicle::getVehicleType(), myEntryTimes, myLastExitTime, myPosition, STEPS2TIME, SUMOReal, and write().
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
MSInstantInductLoop& MSInstantInductLoop::operator= (const MSInstantInductLoop &) [private]
Invalidated assignment operator.
virtual void MSDetectorFileOutput::reset () [inline, virtual, inherited]
Resets collected values.
Please note that this is only a "hack" for coupled-tls-outputs.
See also:
Command_SaveTLCoupledLaneDet
Todo:
Reckeck/refactor
Reimplemented in GUIInductLoop, MSE2Collector, MSE3Collector, and MSInductLoop.
Definition at line 106 of file MSDetectorFileOutput.h.
Referenced by Command_SaveTLCoupledLaneDet::execute().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSInstantInductLoop::write (const char * state, SUMOReal t, SUMOVehicle & veh, SUMOReal speed, const char * add = 0, SUMOReal addValue = -1) [protected]
Writes an event line.
Parameters:
[in] state The current state to report
[in] t The event time
[in] veh The vehicle responsible for the event
[in] speed The speed of the vehicle
[in] add An optional attribute to report
[in] addValue The value of the optional attribute
Definition at line 108 of file MSInstantInductLoop.cpp.
References OutputDevice::closeTag(), MSVehicleType::getID(), SUMOVehicle::getID(), Named::getID(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), myOutputDevice, OutputDevice::openTag(), toString(), and OutputDevice::writeAttr().
Referenced by notifyLeave(), and notifyMove().
void MSInstantInductLoop::writeXMLDetectorProlog (OutputDevice & dev) const [virtual]
Open the XML-output.
The implementing function should open an xml element using OutputDevice::writeXMLHeader.
Parameters:
[in] dev The output device to write the root into
Exceptions:
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 147 of file MSInstantInductLoop.cpp.
References OutputDevice::writeXMLHeader().
Referenced by MSInstantInductLoop().
void MSInstantInductLoop::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [inline, virtual]
Write the generated output to the given device.
This method is not used - output is written as soon as a vehicle visits the detector.
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions:
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 145 of file MSInstantInductLoop.h.
Field Documentation
std::map<SUMOVehicle*, SUMOReal> MSInstantInductLoop::myEntryTimes [protected]
The last exit time.
Definition at line 183 of file MSInstantInductLoop.h.
Referenced by notifyLeave(), and notifyMove().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSInstantInductLoop::myLastExitTime [protected]
The last exit time.
Definition at line 180 of file MSInstantInductLoop.h.
Referenced by notifyMove().
OutputDevice& MSInstantInductLoop::myOutputDevice [protected]
The output device to use.
Definition at line 174 of file MSInstantInductLoop.h.
Referenced by write().
const SUMOReal MSInstantInductLoop::myPosition [protected]
Detector's position on lane [m].
Definition at line 177 of file MSInstantInductLoop.h.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), MSInstantInductLoop(), notifyEnter(), and notifyMove().
The documentation for this class was generated from the following files:
MSInstantInductLoop.h
MSInstantInductLoop.cpp