SUMO - Simulation of Urban MObility: MSTLLogicControl::TLSLogicVariants Class Reference
MSTLLogicControl::TLSLogicVariants Class Reference
Storage for all programs of a single tls.
#include <MSTLLogicControl.h>
Public Member Functions
void addLink (MSLink *link, MSLane *lane, unsigned int pos)
bool addLogic (const std::string &programID, MSTrafficLightLogic *logic, bool netWasLoaded, bool isNewDefault=true)
Adds a logic (program).
void addSwitchCommand (OnSwitchAction *c)
bool checkOriginalTLS () const
Verifies traffic lights loaded from the network.
void executeOnSwitchActions () const
MSTrafficLightLogic * getActive () const
std::vector
< MSTrafficLightLogic * > getAllLogics () const
MSTrafficLightLogic * getLogic (const std::string &programID) const
MSTrafficLightLogic * getLogicInstantiatingOff (MSTLLogicControl &tlc, const std::string &programID)
bool isActive (const MSTrafficLightLogic *tl) const
void saveInitialStates ()
void switchTo (MSTLLogicControl &tlc, const std::string &programID)
TLSLogicVariants ()
Constructor.
~TLSLogicVariants ()
Destructor.
Private Member Functions
TLSLogicVariants & operator= (const TLSLogicVariants &)
Invalidated assignment operator.
TLSLogicVariants (const TLSLogicVariants &)
Invalidated copy constructor.
Private Attributes
MSTrafficLightLogic * myCurrentProgram
The currently used program.
std::map< MSLink *, LinkState > myOriginalLinkStates
Originally loaded link states.
std::vector< OnSwitchAction * > mySwitchActions
The list of actions/commands to execute on switch.
std::map< std::string,
MSTrafficLightLogic * > myVariants
A map of subkeys to programs.
Detailed Description
Storage for all programs of a single tls.
This class joins all programs of a single tls.
Definition at line 86 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
MSTLLogicControl::TLSLogicVariants::TLSLogicVariants ()
Constructor.
Definition at line 60 of file MSTLLogicControl.cpp.
MSTLLogicControl::TLSLogicVariants::~TLSLogicVariants ()
Destructor.
Definition at line 65 of file MSTLLogicControl.cpp.
References mySwitchActions, and myVariants.
MSTLLogicControl::TLSLogicVariants::TLSLogicVariants (const TLSLogicVariants &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSTLLogicControl::TLSLogicVariants::addLink (MSLink * link, MSLane * lane, unsigned int pos)
Definition at line 207 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by NLHandler::addConnection(), and NLSucceedingLaneBuilder::addSuccLane().
bool MSTLLogicControl::TLSLogicVariants::addLogic (const std::string & programID, MSTrafficLightLogic * logic, bool netWasLoaded, bool isNewDefault = true)
Adds a logic (program).
Parameters:
[in] programID The sub-id of this program
[in] logic The logic to add
[in] netWasLoaded Whether the network has already been loaded (the links have been assigned)
[in] isNewDefault Whether this logic shall be treated as the currently active logic
Definition at line 104 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::adaptLinkInformationFrom(), executeOnSwitchActions(), MSTrafficLightLogic::getID(), MSNet::getInstance(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getPhase(), MSPhaseDefinition::getState(), myCurrentProgram, myVariants, and MSTrafficLightLogic::setTrafficLightSignals().
Referenced by MSTLLogicControl::add(), getLogicInstantiatingOff(), and TraCIServerAPI_TLS::processSet().
void MSTLLogicControl::TLSLogicVariants::addSwitchCommand (OnSwitchAction * c)
Definition at line 163 of file MSTLLogicControl.cpp.
References mySwitchActions.
Referenced by Command_SaveTLCoupledDet::Command_SaveTLCoupledDet().
bool MSTLLogicControl::TLSLogicVariants::checkOriginalTLS () const
Verifies traffic lights loaded from the network.
Comparse the phase state sizes of each phase with the accoring tls' number of controlled links.
Returns:
Whether all tls programs are valid
Definition at line 77 of file MSTLLogicControl.cpp.
References myVariants, and WRITE_ERROR.
void MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions () const
Definition at line 199 of file MSTLLogicControl.cpp.
References mySwitchActions.
Referenced by addLogic(), MSTrafficLightLogic::SwitchCommand::execute(), and TraCIServerAPI_TLS::processSet().
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getActive () const
Definition at line 186 of file MSTLLogicControl.cpp.
References myCurrentProgram.
Referenced by NLHandler::addConnection(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), Command_SaveTLSState::execute(), MSTLLogicControl::initWautSwitch(), TraCIServerAPI_TLS::processGet(), and TraCIServerAPI_TLS::processSet().
std::vector< MSTrafficLightLogic * > MSTLLogicControl::TLSLogicVariants::getAllLogics () const
Definition at line 169 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by GUITrafficLightLogicWrapper::getPopUpMenu(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TLS::processGet(), and GUITrafficLightLogicWrapper::switchTLSLogic().
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getLogic (const std::string & programID) const
Definition at line 135 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by getLogicInstantiatingOff(), and TraCIServerAPI_TLS::processSet().
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff (MSTLLogicControl & tlc, const std::string & programID)
Definition at line 144 of file MSTLLogicControl.cpp.
References addLogic(), MSTrafficLightLogic::getID(), getLogic(), myCurrentProgram, and myVariants.
Referenced by MSTLLogicControl::initWautSwitch(), and switchTo().
bool MSTLLogicControl::TLSLogicVariants::isActive (const MSTrafficLightLogic * tl) const
Definition at line 180 of file MSTLLogicControl.cpp.
References myCurrentProgram.
Referenced by GUITrafficLightLogicWrapper::getPopUpMenu().
TLSLogicVariants& MSTLLogicControl::TLSLogicVariants::operator= (const TLSLogicVariants &) [private]
Invalidated assignment operator.
void MSTLLogicControl::TLSLogicVariants::saveInitialStates ()
Definition at line 98 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::collectLinkStates(), myCurrentProgram, and myOriginalLinkStates.
void MSTLLogicControl::TLSLogicVariants::switchTo (MSTLLogicControl & tlc, const std::string & programID)
Definition at line 192 of file MSTLLogicControl.cpp.
References getLogicInstantiatingOff(), and myCurrentProgram.
Referenced by TraCIServerAPI_TLS::processSet().
Field Documentation
MSTrafficLightLogic* MSTLLogicControl::TLSLogicVariants::myCurrentProgram [private]
The currently used program.
Definition at line 133 of file MSTLLogicControl.h.
Referenced by addLogic(), getActive(), getLogicInstantiatingOff(), isActive(), saveInitialStates(), and switchTo().
std::map<MSLink*, LinkState> MSTLLogicControl::TLSLogicVariants::myOriginalLinkStates [private]
Originally loaded link states.
Definition at line 139 of file MSTLLogicControl.h.
Referenced by saveInitialStates().
std::vector<OnSwitchAction*> MSTLLogicControl::TLSLogicVariants::mySwitchActions [private]
The list of actions/commands to execute on switch.
Definition at line 142 of file MSTLLogicControl.h.
Referenced by addSwitchCommand(), executeOnSwitchActions(), and ~TLSLogicVariants().
std::map<std::string, MSTrafficLightLogic*> MSTLLogicControl::TLSLogicVariants::myVariants [private]
A map of subkeys to programs.
Definition at line 136 of file MSTLLogicControl.h.
Referenced by addLink(), addLogic(), checkOriginalTLS(), getAllLogics(), getLogic(), getLogicInstantiatingOff(), and ~TLSLogicVariants().
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp