SUMO - Simulation of Urban MObility: OptionsParser Class Reference
OptionsParser Class Reference
Parses command line arguments.
#include <OptionsParser.h>
Static Public Member Functions
static bool parse (int argc, char **argv)
Parses the given command line arguments.
Static Private Member Functions
static int check (const char *arg1, const char *arg2, bool &ok)
parses the previous arguments
static bool checkParameter (const char *arg1)
Returns the whether the given token is an option.
static std::string convert (char abbr)
converts char to string
static std::string convert (const char *arg)
Converts char* to string.
static bool isAbbreviation (const char *arg1)
returns the whether the given token is an abbreviation
static bool processNonBooleanSingleSwitch (OptionsCont &oc, const char *arg)
Extracts the parameter directly attached to an option.
Detailed Description
Parses command line arguments.
The only public method parses the given list of arguments. It returns false when something failed. This may happen if the syntax of the arguments is invalid, a value is tried to be set several times or an unknown option is tried to be set.
The class assumes all options are unset or using default values only.
Definition at line 56 of file OptionsParser.h.
Member Function Documentation
int OptionsParser::check (const char * arg1, const char * arg2, bool & ok) [static, private]
parses the previous arguments
Parameters:
[in] arg1 The first token to parse
[in] arg2 The second token to parse, 0 if there is none
[in,out] ok Whether the parsing was successfull
Returns:
Number of read tokens (1 or 2)
Exceptions:
InvalidArgument If a performed setting of an option failed (see Option::set)
Definition at line 78 of file OptionsParser.cpp.
References checkParameter(), convert(), OptionsCont::getOptions(), isAbbreviation(), OptionsCont::isBool(), processNonBooleanSingleSwitch(), and OptionsCont::set().
Referenced by parse().
bool OptionsParser::checkParameter (const char * arg1) [static, private]
Returns the whether the given token is an option.
The given token is assumed to be an option if it starts with a '-'.
Parameters:
[in] arg1 The token to check
Returns:
Whether the token is an option
Definition at line 155 of file OptionsParser.cpp.
References WRITE_ERROR.
Referenced by check().
std::string OptionsParser::convert (char abbr) [static, private]
converts char to string
Parameters:
[in] abbr The char to convert
Returns:
The char converted into a std::string
Definition at line 178 of file OptionsParser.cpp.
std::string OptionsParser::convert (const char * arg) [static, private]
Converts char* to string.
Parameters:
[in] arg The c-string to convert
Returns:
The string converted into a std::string
Definition at line 171 of file OptionsParser.cpp.
Referenced by check(), and processNonBooleanSingleSwitch().
bool OptionsParser::isAbbreviation (const char * arg1) [static, private]
returns the whether the given token is an abbreviation
The given token is assumed to be an option if it starts with two '-'.
Parameters:
[in] arg1 The token to check
Returns:
Whether the token is an abbreviation
Definition at line 165 of file OptionsParser.cpp.
Referenced by check().
bool OptionsParser::parse (int argc, char ** argv) [static]
Parses the given command line arguments.
Parameters:
[in] oc The options container to fill
[in] argc The number of given command line arguments
[in] argv The command line arguments
Returns:
Whether the parsing was successfull
Exceptions:
InvalidArgument If a performed setting of an option failed (see Option::set)
Definition at line 50 of file OptionsParser.cpp.
References check(), and WRITE_ERROR.
Referenced by OptionsIO::getOptions().
bool OptionsParser::processNonBooleanSingleSwitch (OptionsCont & oc, const char * arg) [static, private]
Extracts the parameter directly attached to an option.
Parses single tokens which contain an option and the parameter (like -c=myconfig.cfg)
Parameters:
[in] oc The container to store the result into
[in] arg The token to parse
Exceptions:
InvalidArgument If a performed setting of an option failed (see Option::set)
Definition at line 135 of file OptionsParser.cpp.
References convert(), OptionsCont::set(), and WRITE_ERROR.
Referenced by check().
The documentation for this class was generated from the following files:
OptionsParser.h
OptionsParser.cpp