SUMO - Simulation of Urban MObility: RODUAEdgeBuilder Class Reference
RODUAEdgeBuilder Class Reference
Interface for building instances of duarouter-edges.
#include <RODUAEdgeBuilder.h>
Public Member Functions
RODUAEdgeBuilder (bool useBoundariesOnOverride, bool interpolate)
Constructor.
~RODUAEdgeBuilder ()
Destructor.
Methods to be implemented, inherited from ROAbstractEdgeBuilder
ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to)
Builds an edge with the given name.
Protected Member Functions
unsigned int getNextIndex ()
Returns the index of the edge to built.
Protected Attributes
bool myInterpolate
Information whether to interpolate at interval boundaries.
bool myUseBoundariesOnOverride
Information whether to use the first/last entry of the time in case it is too short.
Detailed Description
Interface for building instances of duarouter-edges.
This ROAbstractEdgeBuilder implementation builds edges for the duarouter (instances of ROEdge).
See also:
ROEdge
Definition at line 56 of file RODUAEdgeBuilder.h.
Constructor & Destructor Documentation
RODUAEdgeBuilder::RODUAEdgeBuilder (bool useBoundariesOnOverride, bool interpolate)
Constructor.
Parameters:
[in] useBoundariesOnOverride Whether edges shall use a boundary value if the requested is beyond known time scale
[in] interpolate Whether edges shall interpolate at interval boundaries
Todo:
useBoundariesOnOverride should not be a member of the edges
Definition at line 43 of file RODUAEdgeBuilder.cpp.
RODUAEdgeBuilder::~RODUAEdgeBuilder ()
Destructor.
Definition at line 47 of file RODUAEdgeBuilder.cpp.
Member Function Documentation
ROEdge * RODUAEdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to) [virtual]
Builds an edge with the given name.
This implementation builds a ROEdge.
Parameters:
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
Returns:
A proper instance of the named edge
See also:
ROEdge
Implements ROAbstractEdgeBuilder.
Definition at line 51 of file RODUAEdgeBuilder.cpp.
References ROAbstractEdgeBuilder::getNextIndex(), myInterpolate, and myUseBoundariesOnOverride.
unsigned int ROAbstractEdgeBuilder::getNextIndex () [inline, protected, inherited]
Returns the index of the edge to built.
Returns:
Next valid edge index
Definition at line 88 of file ROAbstractEdgeBuilder.h.
References ROAbstractEdgeBuilder::myCurrentIndex.
Referenced by ROJTREdgeBuilder::buildEdge(), buildEdge(), and RODFEdgeBuilder::buildEdge().
Field Documentation
bool RODUAEdgeBuilder::myInterpolate [protected]
Information whether to interpolate at interval boundaries.
Definition at line 93 of file RODUAEdgeBuilder.h.
Referenced by buildEdge().
bool RODUAEdgeBuilder::myUseBoundariesOnOverride [protected]
Information whether to use the first/last entry of the time in case it is too short.
Definition at line 90 of file RODUAEdgeBuilder.h.
Referenced by buildEdge().
The documentation for this class was generated from the following files:
RODUAEdgeBuilder.h
RODUAEdgeBuilder.cpp