SUMO - Simulation of Urban MObility: NIVissimNodeDef Class Reference
NIVissimNodeDef Class Reference
#include <NIVissimNodeDef.h>
Public Member Functions
int buildNodeCluster ()
virtual SUMOReal getEdgePosition (int edgeid) const =0
NIVissimNodeDef (int id, const std::string &name)
virtual void searchAndSetConnections ()=0
virtual ~NIVissimNodeDef ()
Static Public Member Functions
static void clearDict ()
static void dict_assignConnectionsToNodes ()
static NIVissimNodeDef * dictionary (int id)
static bool dictionary (int id, NIVissimNodeDef *o)
static size_t dictSize ()
static int getMaxID ()
Protected Attributes
int myID
std::string myName
Private Types
typedef std::map< int,
NIVissimNodeDef * > DictType
Static Private Attributes
static DictType myDict
static int myMaxID = 0
Detailed Description
Definition at line 41 of file NIVissimNodeDef.h.
Member Typedef Documentation
typedef std::map<int, NIVissimNodeDef*> NIVissimNodeDef::DictType [private]
Definition at line 62 of file NIVissimNodeDef.h.
Constructor & Destructor Documentation
NIVissimNodeDef::NIVissimNodeDef (int id, const std::string & name)
Definition at line 51 of file NIVissimNodeDef.cpp.
NIVissimNodeDef::~NIVissimNodeDef () [virtual]
Definition at line 55 of file NIVissimNodeDef.cpp.
Member Function Documentation
int NIVissimNodeDef::buildNodeCluster ()
void NIVissimNodeDef::clearDict () [static]
Definition at line 132 of file NIVissimNodeDef.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
void NIVissimNodeDef::dict_assignConnectionsToNodes () [static]
Definition at line 117 of file NIVissimNodeDef.cpp.
References myDict.
NIVissimNodeDef * NIVissimNodeDef::dictionary (int id) [static]
Definition at line 74 of file NIVissimNodeDef.cpp.
References myDict.
bool NIVissimNodeDef::dictionary (int id, NIVissimNodeDef * o) [static]
Definition at line 59 of file NIVissimNodeDef.cpp.
References myDict, and myMaxID.
Referenced by NIVissimNodeDef_Poly::dictionary(), NIVissimNodeDef_Edges::dictionary(), and NIVissimConnectionCluster::getPositionForEdge().
size_t NIVissimNodeDef::dictSize () [static]
Definition at line 125 of file NIVissimNodeDef.cpp.
References myDict.
virtual SUMOReal NIVissimNodeDef::getEdgePosition (int edgeid) const [pure virtual]
Implemented in NIVissimNodeDef_Edges.
Referenced by NIVissimConnectionCluster::getPositionForEdge().
int NIVissimNodeDef::getMaxID () [static]
Definition at line 141 of file NIVissimNodeDef.cpp.
References myMaxID.
Referenced by NIImporter_Vissim::postLoadBuild().
virtual void NIVissimNodeDef::searchAndSetConnections () [pure virtual]
Implemented in NIVissimNodeDef_Edges.
Field Documentation
NIVissimNodeDef::DictType NIVissimNodeDef::myDict [static, private]
Definition at line 63 of file NIVissimNodeDef.h.
Referenced by clearDict(), dict_assignConnectionsToNodes(), dictionary(), and dictSize().
int NIVissimNodeDef::myID [protected]
Definition at line 58 of file NIVissimNodeDef.h.
Referenced by NIVissimNodeDef_Poly::searchAndSetConnections(), and NIVissimNodeDef_Edges::searchAndSetConnections().
int NIVissimNodeDef::myMaxID = 0 [static, private]
Definition at line 64 of file NIVissimNodeDef.h.
Referenced by dictionary(), and getMaxID().
std::string NIVissimNodeDef::myName [protected]
Definition at line 59 of file NIVissimNodeDef.h.
The documentation for this class was generated from the following files:
NIVissimNodeDef.h
NIVissimNodeDef.cpp