SUMO - Simulation of Urban MObility: GUIE3Collector Class Reference
GUIE3Collector Class Reference
The gui-version of the MSE3Collector.
#include <GUIE3Collector.h>
Data Structures
class MyWrapper
Public Member Functions
GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Returns the wrapper for this detector.
void detectorUpdate (const SUMOTime step)
Computes the detector values in each time step.
void enter (SUMOVehicle &veh, SUMOReal entryTimestep)
Called if a vehicle touches an entry-cross-section.
const CrossSectionVector & getEntries () const
Returns the list of entry points.
const CrossSectionVector & getExits () const
Returns the list of exit points.
const std::string & getID () const
Returns the id.
GUIE3Collector (const std::string &id, const CrossSectionVector &entries, const CrossSectionVector &exits, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold)
Constructor.
void leave (SUMOVehicle &veh, SUMOReal leaveTimestep)
Called if a vehicle passes a leave-cross-section.
void reset ()
Resets all generated values to allow computation of next interval.
void setID (const std::string &newID)
resets the id
~GUIE3Collector ()
Destructor.
Methods returning current values
SUMOReal getCurrentHaltingNumber () const
Returns the number of current haltings within the area.
SUMOReal getCurrentMeanSpeed () const
Returns the mean speed within the area.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the number of vehicles within the area.
SUMOReal getVehiclesWithin () const
Returns the number of vehicles within the area.
Methods inherited from MSDetectorFileOutput.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "e3Detector" as root element.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
Protected Attributes
std::map< SUMOVehicle *, E3Values > myEnteredContainer
Container for vehicles that have entered the area.
CrossSectionVector myEntries
The detector's entries.
std::vector< MSE3EntryReminder * > myEntryReminders
The detector's built entry reminder.
CrossSectionVector myExits
The detector's exits.
SUMOReal myHaltingSpeedThreshold
Speed-threshold to determine if a vehicle is halting.
SUMOTime myHaltingTimeThreshold
std::string myID
The name of the object.
SUMOTime myLastResetTime
Information when the last reset has been done.
std::vector< MSE3LeaveReminder * > myLeaveReminders
The detector's built exit reminder.
std::map< SUMOVehicle *, E3Values > myLeftContainer
Container for vehicles that have left the area.
Storages for current values
SUMOReal myCurrentHaltingsNumber
The current number of haltings (inside).
SUMOReal myCurrentMeanSpeed
The current mean speed of known vehicles (inside).
SUMOReal myCurrentTouchedVehicles
The current number of vehicles inside;.
Detailed Description
The gui-version of the MSE3Collector.
Allows the building of a wrapper (also declared herein) which draws the detector on the gl-canvas.
Definition at line 53 of file GUIE3Collector.h.
Constructor & Destructor Documentation
GUIE3Collector::GUIE3Collector (const std::string & id, const CrossSectionVector & entries, const CrossSectionVector & exits, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold)
Constructor.
Definition at line 179 of file GUIE3Collector.cpp.
GUIE3Collector::~GUIE3Collector ()
Destructor.
Definition at line 186 of file GUIE3Collector.cpp.
Member Function Documentation
GUIDetectorWrapper * GUIE3Collector::buildDetectorGUIRepresentation () [virtual]
Returns the wrapper for this detector.
Returns:
The wrapper representing the detector
See also:
MyWrapper
Reimplemented from MSDetectorFileOutput.
Definition at line 203 of file GUIE3Collector.cpp.
void MSE3Collector::detectorUpdate (const SUMOTime step) [virtual, inherited]
Computes the detector values in each time step.
This method should be called at the end of a simulation step, when all vehicles have moved. The current values are computed and summed up with the previous.
Parameters:
[in] currentTime The current simulation time (unused)
Reimplemented from MSDetectorFileOutput.
Definition at line 285 of file MSE3Collector.cpp.
References MSE3Collector::E3Values::entryTime, SUMOVehicle::getSpeed(), MSE3Collector::E3Values::hadUpdate, MSE3Collector::E3Values::haltingBegin, MSE3Collector::E3Values::haltings, MSE3Collector::E3Values::intervalHaltings, MSE3Collector::E3Values::intervalSpeedSum, MSE3Collector::myCurrentHaltingsNumber, MSE3Collector::myCurrentMeanSpeed, MSE3Collector::myCurrentTouchedVehicles, MSE3Collector::myEnteredContainer, MSE3Collector::myHaltingSpeedThreshold, MSE3Collector::myHaltingTimeThreshold, MSE3Collector::E3Values::speedSum, SUMOReal, and TS.
void MSE3Collector::enter (SUMOVehicle & veh, SUMOReal entryTimestep) [inherited]
Called if a vehicle touches an entry-cross-section.
Inserts vehicle into internal containers.
Parameters:
[in] veh The vehicle that entered the area
[in] entryTimestep The time step the vehicle entered the area
Definition at line 157 of file MSE3Collector.cpp.
References DELTA_T, MSE3Collector::E3Values::entryTime, Named::getID(), SUMOVehicle::getID(), SUMOVehicle::getSpeed(), MSE3Collector::E3Values::hadUpdate, MSE3Collector::E3Values::haltingBegin, MSE3Collector::E3Values::haltings, MSE3Collector::E3Values::intervalHaltings, MSE3Collector::E3Values::intervalSpeedSum, MSE3Collector::E3Values::leaveTime, MSE3Collector::myEnteredContainer, MSE3Collector::myHaltingSpeedThreshold, MSE3Collector::myHaltingTimeThreshold, MSE3Collector::E3Values::speedSum, SUMO_TAG_E3DETECTOR, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSE3Collector::MSE3EntryReminder::notifyMove().
SUMOReal MSE3Collector::getCurrentHaltingNumber () const [inherited]
Returns the number of current haltings within the area.
If no vehicle is within the area, 0 is returned.
Returns:
The mean number of haltings within the area
Definition at line 338 of file MSE3Collector.cpp.
References MSE3Collector::myCurrentHaltingsNumber.
Referenced by GUIE3Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_MeMeDetector::processGet().
SUMOReal MSE3Collector::getCurrentMeanSpeed () const [inherited]
Returns the mean speed within the area.
If no vehicle is within the area, -1 is returned.
Returns:
The mean speed [m/s] of all vehicles within the area, -1 if there is none
Definition at line 325 of file MSE3Collector.cpp.
References MSE3Collector::myEnteredContainer, and SUMOReal.
Referenced by GUIE3Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_MeMeDetector::processGet().
std::vector< std::string > MSE3Collector::getCurrentVehicleIDs () const [inherited]
Returns the number of vehicles within the area.
Returns:
The number of vehicles that have passed the entry, but not yet an exit point
Definition at line 350 of file MSE3Collector.cpp.
References MSE3Collector::myEnteredContainer.
Referenced by TraCIServerAPI_MeMeDetector::processGet().
const CrossSectionVector & GUIE3Collector::getEntries () const
Returns the list of entry points.
Returns:
The list of entry points
Definition at line 190 of file GUIE3Collector.cpp.
References MSE3Collector::myEntries.
Referenced by GUIE3Collector::MyWrapper::MyWrapper().
const CrossSectionVector & GUIE3Collector::getExits () const
Returns the list of exit points.
Returns:
The list of exit points
Definition at line 196 of file GUIE3Collector.cpp.
References MSE3Collector::myExits.
Referenced by GUIE3Collector::MyWrapper::MyWrapper().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
SUMOReal MSE3Collector::getVehiclesWithin () const [inherited]
Returns the number of vehicles within the area.
Returns:
The number of vehicles that passed the entry collector
Definition at line 344 of file MSE3Collector.cpp.
References MSE3Collector::myEnteredContainer, and SUMOReal.
Referenced by GUIE3Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_MeMeDetector::processGet().
void MSE3Collector::leave (SUMOVehicle & veh, SUMOReal leaveTimestep) [inherited]
Called if a vehicle passes a leave-cross-section.
Removes vehicle from internal containers.
Parameters:
[in] veh The vehicle that left the area
[in] entryTimestep The time step the vehicle left the area
Definition at line 184 of file MSE3Collector.cpp.
References DELTA_T, Named::getID(), SUMOVehicle::getID(), SUMOVehicle::getSpeed(), MSE3Collector::E3Values::hadUpdate, MSE3Collector::E3Values::haltingBegin, MSE3Collector::E3Values::haltings, MSE3Collector::E3Values::intervalHaltings, MSE3Collector::E3Values::intervalSpeedSum, MSE3Collector::E3Values::leaveTime, MSE3Collector::myEnteredContainer, MSE3Collector::myHaltingSpeedThreshold, MSE3Collector::myHaltingTimeThreshold, MSE3Collector::myLeftContainer, MSE3Collector::E3Values::speedSum, SUMO_TAG_E3DETECTOR, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSE3Collector::MSE3LeaveReminder::notifyMove().
void MSE3Collector::reset () [virtual, inherited]
Resets all generated values to allow computation of next interval.
Reimplemented from MSDetectorFileOutput.
Definition at line 150 of file MSE3Collector.cpp.
References MSE3Collector::myLeftContainer.
Referenced by MSE3Collector::MSE3Collector().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSE3Collector::writeXMLDetectorProlog (OutputDevice & dev) const [virtual, inherited]
Opens the XML-output using "e3Detector" as root element.
The lists of entries/exists are written, too.
Parameters:
[in] dev The output device to write the root into
See also:
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 279 of file MSE3Collector.cpp.
References OutputDevice::writeXMLHeader().
void MSE3Collector::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [virtual, inherited]
Writes collected values into the given stream.
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also:
MSDetectorFileOutput::writeXMLOutput
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 212 of file MSE3Collector.cpp.
References MIN2(), MSE3Collector::myEnteredContainer, Named::myID, MSE3Collector::myLastResetTime, MSE3Collector::myLeftContainer, SUMOReal, and time2string().
Field Documentation
SUMOReal MSE3Collector::myCurrentHaltingsNumber [protected, inherited]
The current number of haltings (inside).
Definition at line 366 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate(), and MSE3Collector::getCurrentHaltingNumber().
SUMOReal MSE3Collector::myCurrentMeanSpeed [protected, inherited]
The current mean speed of known vehicles (inside).
Definition at line 363 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate().
SUMOReal MSE3Collector::myCurrentTouchedVehicles [protected, inherited]
The current number of vehicles inside;.
Please note, that vehicles that enter the area are given as a fraction
See also:
execute
Definition at line 373 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate().
std::map<SUMOVehicle*, E3Values> MSE3Collector::myEnteredContainer [protected, inherited]
Container for vehicles that have entered the area.
Definition at line 353 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate(), MSE3Collector::enter(), MSE3Collector::getCurrentMeanSpeed(), MSE3Collector::getCurrentVehicleIDs(), MSE3Collector::getVehiclesWithin(), MSE3Collector::leave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyMove(), and MSE3Collector::writeXMLOutput().
CrossSectionVector MSE3Collector::myEntries [protected, inherited]
The detector's entries.
Definition at line 307 of file MSE3Collector.h.
Referenced by getEntries().
std::vector<MSE3EntryReminder*> MSE3Collector::myEntryReminders [protected, inherited]
The detector's built entry reminder.
Definition at line 313 of file MSE3Collector.h.
Referenced by MSE3Collector::MSE3Collector(), and MSE3Collector::~MSE3Collector().
CrossSectionVector MSE3Collector::myExits [protected, inherited]
The detector's exits.
Definition at line 310 of file MSE3Collector.h.
Referenced by getExits().
SUMOReal MSE3Collector::myHaltingSpeedThreshold [protected, inherited]
Speed-threshold to determine if a vehicle is halting.
Definition at line 323 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate(), MSE3Collector::enter(), and MSE3Collector::leave().
SUMOTime MSE3Collector::myHaltingTimeThreshold [protected, inherited]
Definition at line 320 of file MSE3Collector.h.
Referenced by MSE3Collector::detectorUpdate(), MSE3Collector::enter(), and MSE3Collector::leave().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
SUMOTime MSE3Collector::myLastResetTime [protected, inherited]
Information when the last reset has been done.
Definition at line 378 of file MSE3Collector.h.
Referenced by MSE3Collector::writeXMLOutput().
std::vector<MSE3LeaveReminder*> MSE3Collector::myLeaveReminders [protected, inherited]
The detector's built exit reminder.
Definition at line 316 of file MSE3Collector.h.
Referenced by MSE3Collector::MSE3Collector(), and MSE3Collector::~MSE3Collector().
std::map<SUMOVehicle*, E3Values> MSE3Collector::myLeftContainer [protected, inherited]
Container for vehicles that have left the area.
Definition at line 356 of file MSE3Collector.h.
Referenced by MSE3Collector::leave(), MSE3Collector::reset(), and MSE3Collector::writeXMLOutput().
The documentation for this class was generated from the following files:
GUIE3Collector.h
GUIE3Collector.cpp