SUMO - Simulation of Urban MObility: RODFFrame Class Reference
RODFFrame Class Reference
Sets and checks options for df-routing.
#include <RODFFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid for usage within dfrouter.
static void fillOptions ()
Inserts options used by dfrouter into the OptionsCont-singleton.
Detailed Description
Sets and checks options for df-routing.
Definition at line 43 of file RODFFrame.h.
Member Function Documentation
bool RODFFrame::checkOptions () [static]
Checks set options from the OptionsCont-singleton for being valid for usage within dfrouter.
Returns:
Whether all needed options are set
Todo:
Unused currently; repair/fill
Definition at line 233 of file RODFFrame.cpp.
Referenced by main().
void RODFFrame::fillOptions () [static]
Inserts options used by dfrouter into the OptionsCont-singleton.
Definition at line 58 of file RODFFrame.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), OptionsCont::getOptions(), and RandHelper::insertRandOptions().
Referenced by main().
The documentation for this class was generated from the following files:
RODFFrame.h
RODFFrame.cpp