SUMO - Simulation of Urban MObility: GUIParameterTracker::GUIParameterTrackerPanel Class Reference
GUIParameterTracker::GUIParameterTrackerPanel Class Reference
#include <GUIParameterTracker.h>
Public Member Functions
GUIParameterTrackerPanel (FXComposite *c, GUIMainWindow &app, GUIParameterTracker &parent)
Constructor.
~GUIParameterTrackerPanel ()
Destructor.
FOX-callbacks
long onConfigure (FXObject *, FXSelector, void *)
Called on window resizing.
long onPaint (FXObject *, FXSelector, void *)
Called if the window shall be repainted.
long onSimStep (FXObject *sender, FXSelector, void *)
Called on a simulation step.
Protected Member Functions
GUIParameterTrackerPanel ()
FOX needs this.
Private Member Functions
void drawValue (TrackerValueDesc &desc, SUMOReal namePos)
Draws a single value.
void drawValues ()
Draws all values.
Private Attributes
GUIMainWindow * myApplication
The main application.
int myHeightInPixels
GUIParameterTracker * myParent
The parent window.
int myWidthInPixels
the sizes of the window
Friends
class GUIParameterTracker
needed to update
Detailed Description
This panel lies within the GUIParameterTracker being the main widget. It is the widget responsible for displaying the information while GUIParameterTracker only provides window-facilities.
Definition at line 114 of file GUIParameterTracker.h.
Constructor & Destructor Documentation
GUIParameterTracker::GUIParameterTrackerPanel::GUIParameterTrackerPanel (FXComposite * c, GUIMainWindow & app, GUIParameterTracker & parent)
Constructor.
Parameters:
[in] c The parent composite
[in] app The main window
[in] parent The parent tracker window this view belongs to
Definition at line 262 of file GUIParameterTracker.cpp.
GUIParameterTracker::GUIParameterTrackerPanel::~GUIParameterTrackerPanel ()
Destructor.
Definition at line 269 of file GUIParameterTracker.cpp.
GUIParameterTracker::GUIParameterTrackerPanel::GUIParameterTrackerPanel () [inline, protected]
FOX needs this.
Definition at line 170 of file GUIParameterTracker.h.
Member Function Documentation
void GUIParameterTracker::GUIParameterTrackerPanel::drawValue (TrackerValueDesc & desc, SUMOReal namePos) [private]
Draws a single value.
Parameters:
[in] desc The tracked values to draw
[in] namePos Position to display the name at (currently unused)
Definition at line 293 of file GUIParameterTracker.cpp.
References TrackerValueDesc::getAggregatedValues(), TrackerValueDesc::getAggregationSpan(), TrackerValueDesc::getColor(), TrackerValueDesc::getMax(), TrackerValueDesc::getMin(), TrackerValueDesc::getName(), TrackerValueDesc::getRange(), TrackerValueDesc::getRecordingBegin(), TrackerValueDesc::getYCenter(), pfdkGetStringWidth(), pfDrawString(), pfSetPosition(), SUMOReal, time2string(), toString(), and TrackerValueDesc::unlockValues().
Referenced by drawValues().
void GUIParameterTracker::GUIParameterTrackerPanel::drawValues () [private]
Draws all values.
Definition at line 273 of file GUIParameterTracker.cpp.
References drawValue(), myHeightInPixels, myParent, GUIParameterTracker::myTracked, myWidthInPixels, pfSetScale(), pfSetScaleXY(), and SUMOReal.
Referenced by onPaint().
long GUIParameterTracker::GUIParameterTrackerPanel::onConfigure (FXObject * , FXSelector , void *)
Called on window resizing.
Definition at line 416 of file GUIParameterTracker.cpp.
References myHeightInPixels, myParent, and myWidthInPixels.
Referenced by GUIParameterTracker::onConfigure().
long GUIParameterTracker::GUIParameterTrackerPanel::onPaint (FXObject * , FXSelector , void *)
Called if the window shall be repainted.
Definition at line 440 of file GUIParameterTracker.cpp.
References drawValues(), myHeightInPixels, and myWidthInPixels.
Referenced by GUIParameterTracker::onPaint().
long GUIParameterTracker::GUIParameterTrackerPanel::onSimStep (FXObject * sender, FXSelector , void *)
Called on a simulation step.
Friends And Related Function Documentation
friend class GUIParameterTracker [friend]
needed to update
Definition at line 129 of file GUIParameterTracker.h.
Field Documentation
GUIMainWindow* GUIParameterTracker::GUIParameterTrackerPanel::myApplication [private]
The main application.
Definition at line 166 of file GUIParameterTracker.h.
int GUIParameterTracker::GUIParameterTrackerPanel::myHeightInPixels [private]
Definition at line 163 of file GUIParameterTracker.h.
Referenced by drawValues(), onConfigure(), and onPaint().
GUIParameterTracker* GUIParameterTracker::GUIParameterTrackerPanel::myParent [private]
The parent window.
Definition at line 160 of file GUIParameterTracker.h.
Referenced by drawValues(), and onConfigure().
int GUIParameterTracker::GUIParameterTrackerPanel::myWidthInPixels [private]
the sizes of the window
Definition at line 163 of file GUIParameterTracker.h.
Referenced by drawValues(), onConfigure(), and onPaint().
The documentation for this class was generated from the following files:
GUIParameterTracker.h
GUIParameterTracker.cpp