SUMO - Simulation of Urban MObility: MSE3Collector::MSE3EntryReminder Class Reference
MSE3Collector::MSE3EntryReminder Class Reference
A place on the road net (at a certain lane and position on it) where the E3 area begins.
#include <MSE3Collector.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
const MSLane * getLane () const
Returns the lane the reminder works on.
MSE3EntryReminder (const MSCrossSection &crossSection, MSE3Collector &collector)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason)
Checks whether the reminder is activated by a vehicle entering the lane.
Methods inherited from MSMoveReminder.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Processes state changes of a vehicle.
bool notifyMove (SUMOVehicle &veh, SUMOReal, SUMOReal newPos, SUMOReal)
Checks whether the vehicle enters.
Protected Attributes
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
MSE3EntryReminder (const MSE3EntryReminder &)
Invalidated copy constructor.
MSE3EntryReminder & operator= (const MSE3EntryReminder &)
Invalidated assignment operator.
Private Attributes
MSE3Collector & myCollector
The parent collector.
SUMOReal myPosition
The position on the lane.
Detailed Description
A place on the road net (at a certain lane and position on it) where the E3 area begins.
Definition at line 71 of file MSE3Collector.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSE3Collector::MSE3EntryReminder::MSE3EntryReminder (const MSCrossSection & crossSection, MSE3Collector & collector)
Constructor.
Parameters:
[in] crossSection The position at which the entry lies
[in] collector The detector the entry belongs to
Definition at line 51 of file MSE3Collector.cpp.
MSE3Collector::MSE3EntryReminder::MSE3EntryReminder (const MSE3EntryReminder &) [private]
Invalidated copy constructor.
Member Function Documentation
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason) [inline, virtual, inherited]
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
True if vehicle enters the reminder.
See also:
Notification
Reimplemented in MSDevice_Person, MSDevice_Routing, MSDevice_Tripinfo, MSDevice_Vehroutes, MSE2Collector, MSInductLoop, MSInstantInductLoop, MSMeanData::MeanDataValues, MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Net::MSLaneMeanDataValues, MSRouteProbe, and MSTriggeredRerouter.
Definition at line 128 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
bool MSE3Collector::MSE3EntryReminder::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) [virtual]
Processes state changes of a vehicle.
If the reported vehicle is known, and the reason indicates a removal from the network (permanent or temporary), the vehicle is removed from the list of vehicles to regard.
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason The reason for the state change
See also:
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 77 of file MSE3Collector.cpp.
References myCollector, MSE3Collector::myEnteredContainer, and MSMoveReminder::NOTIFICATION_ARRIVED.
bool MSE3Collector::MSE3EntryReminder::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [virtual]
Checks whether the vehicle enters.
As soon as the reported vehicle enters the detector area (position>myPosition) the entering time is computed and both are added to the parent detector using "enter".
Parameters:
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep.
[in] newSpeed Unused here.
Returns:
False, if vehicle passed the detector entierly, else true.
See also:
MSMoveReminder
MSMoveReminder::notifyMove
MSE3Collector::enter
Reimplemented from MSMoveReminder.
Definition at line 58 of file MSE3Collector.cpp.
References MSE3Collector::enter(), MSNet::getInstance(), myCollector, MSE3Collector::myEnteredContainer, myPosition, STEPS2TIME, and SUMOReal.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
MSE3EntryReminder& MSE3Collector::MSE3EntryReminder::operator= (const MSE3EntryReminder &) [private]
Invalidated assignment operator.
Field Documentation
MSE3Collector& MSE3Collector::MSE3EntryReminder::myCollector [private]
The parent collector.
Definition at line 118 of file MSE3Collector.h.
Referenced by notifyLeave(), and notifyMove().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSE3Collector::MSE3EntryReminder::myPosition [private]
The position on the lane.
Definition at line 121 of file MSE3Collector.h.
Referenced by notifyMove().
The documentation for this class was generated from the following files:
MSE3Collector.h
MSE3Collector.cpp