SUMO - Simulation of Urban MObility: VehicleToTrack.cpp File Reference
VehicleToTrack.cpp File Reference
#include <config.h>
#include "VehicleToTrack.h"
#include <iostream>
Functions
std::ostream & operator<< (std::ostream &out, const VehicleToTrack &vehicle)
Function Documentation
std::ostream& operator<< (std::ostream & out, const VehicleToTrack & vehicle)
Definition at line 37 of file VehicleToTrack.cpp.
References VehicleToTrack::getBehaviour(), VehicleToTrack::getFinalPoint(), VehicleToTrack::getIdentifier(), VehicleToTrack::getInitialBattery(), VehicleToTrack::getInitialPoint(), VehicleToTrack::getOverlioad(), and VehicleToTrack::getVehicleType().