SUMO - Simulation of Urban MObility: MSVehicle::State Class Reference
MSVehicle::State Class Reference
Container that holds the vehicles driving state (position+speed).
#include <MSVehicle.h>
Public Member Functions
SUMOTime getEnterLane () const
double getMyEnterPosLane () const
double getMyLastChargeRemoved () const
MSEdge getMyLastEdge () const
double getMyPos () const
double getMyPosOnLane () const
double getMySpeed () const
bool operator!= (const State &state)
Operator !=.
State & operator= (const State &state)
Assignment operator.
double pos () const
Position of this state.
void setEnterLane (SUMOTime enterLane)
void setMyEnterPosLane (double myEnterPosLane)
void setMyLastChargeRemoved (double myLastChargeRemoved)
void setMyLastEdge (MSEdge myLastEdge)
void setMyPos (double myPos)
void setMyPosOnLane (double myPos)
void setMySpeed (double mySpeed)
double speed () const
Speed of this state.
State (const State &state)
Copy constructor.
State (double pos, double speed, SUMOTime lane)
Constructor.
Private Attributes
double myEnterPosLane
double myLastChargeRemoved
double myPos
the stored position
double myPosOnLane
double mySpeed
the stored speed
SUMOTime myTimeEnterLane
Friends
class MSLaneChanger
class MSVehicle
vehicle sets states directly
Detailed Description
Container that holds the vehicles driving state (position+speed).
Definition at line 101 of file MSVehicle.h.
Constructor & Destructor Documentation
MSVehicle::State::State (double pos, double speed, SUMOTime lane)
Constructor.
MSVehicle::State::State (const State & state)
Copy constructor.
Definition at line 110 of file MSVehicle.cpp.
References myPos, mySpeed, and myTimeEnterLane.
Member Function Documentation
SUMOTime MSVehicle::State::getEnterLane () const
Definition at line 2096 of file MSVehicle.cpp.
References myTimeEnterLane.
Referenced by MSVehicle::writeSyntheticData().
double MSVehicle::State::getMyEnterPosLane () const
Definition at line 2156 of file MSVehicle.cpp.
References myEnterPosLane.
Referenced by MSVehicle::writeSyntheticData().
double MSVehicle::State::getMyLastChargeRemoved () const
Definition at line 2164 of file MSVehicle.cpp.
References myLastChargeRemoved.
Referenced by MSVehicle::writeSyntheticData().
MSEdge MSVehicle::State::getMyLastEdge () const
double MSVehicle::State::getMyPos () const
Definition at line 2104 of file MSVehicle.cpp.
References myPos.
double MSVehicle::State::getMyPosOnLane () const
Definition at line 2100 of file MSVehicle.cpp.
References myPosOnLane.
Referenced by MSVehicle::writeSyntheticData().
double MSVehicle::State::getMySpeed () const
Definition at line 2108 of file MSVehicle.cpp.
References mySpeed.
bool MSVehicle::State::operator!= (const State & state)
Operator !=.
Definition at line 125 of file MSVehicle.cpp.
References myPos, mySpeed, and myTimeEnterLane.
MSVehicle::State & MSVehicle::State::operator= (const State & state)
Assignment operator.
Definition at line 118 of file MSVehicle.cpp.
References myPos, mySpeed, and myTimeEnterLane.
SUMOReal MSVehicle::State::pos () const
Position of this state.
Definition at line 130 of file MSVehicle.cpp.
References myPos.
Referenced by GUIVehicle::drawGL(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getAngle(), MSVehicle::getPosition(), and MSVehicle::moveChecked().
void MSVehicle::State::setEnterLane (SUMOTime enterLane)
Definition at line 2116 of file MSVehicle.cpp.
References myTimeEnterLane.
Referenced by MSVehicle::enterLaneAtLaneChange(), and MSVehicle::moveChecked().
void MSVehicle::State::setMyEnterPosLane (double myEnterPosLane)
Definition at line 2160 of file MSVehicle.cpp.
Referenced by MSVehicle::moveChecked().
void MSVehicle::State::setMyLastChargeRemoved (double myLastChargeRemoved)
Definition at line 2168 of file MSVehicle.cpp.
Referenced by MSVehicle::moveChecked().
void MSVehicle::State::setMyLastEdge (MSEdge myLastEdge)
void MSVehicle::State::setMyPos (double myPos)
Definition at line 2120 of file MSVehicle.cpp.
void MSVehicle::State::setMyPosOnLane (double myPos)
Definition at line 2112 of file MSVehicle.cpp.
References myPosOnLane.
Referenced by MSVehicle::enterLaneAtLaneChange(), and MSVehicle::moveChecked().
void MSVehicle::State::setMySpeed (double mySpeed)
Definition at line 2124 of file MSVehicle.cpp.
double MSVehicle::State::speed () const [inline]
Speed of this state.
Definition at line 132 of file MSVehicle.h.
References mySpeed.
Referenced by MSVehicle::enterLaneAtLaneChange(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHBEFA_CO2Emissions(), MSVehicle::getHBEFA_COEmissions(), MSVehicle::getHBEFA_FuelConsumption(), MSVehicle::getHBEFA_HCEmissions(), MSVehicle::getHBEFA_NOxEmissions(), MSVehicle::getHBEFA_PMxEmissions(), and MSVehicle::moveChecked().
Friends And Related Function Documentation
friend class MSLaneChanger [friend]
Definition at line 104 of file MSVehicle.h.
friend class MSVehicle [friend]
vehicle sets states directly
Definition at line 103 of file MSVehicle.h.
Field Documentation
double MSVehicle::State::myEnterPosLane [private]
Definition at line 146 of file MSVehicle.h.
Referenced by getMyEnterPosLane().
double MSVehicle::State::myLastChargeRemoved [private]
Definition at line 147 of file MSVehicle.h.
Referenced by getMyLastChargeRemoved().
double MSVehicle::State::myPos [private]
the stored position
Definition at line 137 of file MSVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::ends(), MSVehicle::enterLaneAtLaneChange(), getMyPos(), MSVehicle::getPositionOnLane(), MSVehicle::leaveLane(), MSVehicle::moveChecked(), MSVehicle::onRemovalFromNet(), operator!=(), operator=(), MSVehicle::overlap(), pos(), and State().
double MSVehicle::State::myPosOnLane [private]
Definition at line 144 of file MSVehicle.h.
Referenced by getMyPosOnLane(), and setMyPosOnLane().
double MSVehicle::State::mySpeed [private]
the stored speed
Definition at line 142 of file MSVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::congested(), getMySpeed(), MSVehicle::getSpeed(), MSVehicle::getSpeedWithoutTraciInfluence(), MSVehicle::moveChecked(), MSVehicle::onRemovalFromNet(), operator!=(), operator=(), speed(), and State().
SUMOTime MSVehicle::State::myTimeEnterLane [private]
Definition at line 145 of file MSVehicle.h.
Referenced by getEnterLane(), operator!=(), operator=(), setEnterLane(), and State().
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp