SUMO - Simulation of Urban MObility: NBJoinedEdgesMap Class Reference
NBJoinedEdgesMap Class Reference
A structure storing information about which edges were joined.
#include <NBJoinedEdgesMap.h>
Public Member Functions
void appended (const std::string &to, const std::string &what)
Informs the map that two edges have been joined.
void init (NBEdgeCont &ec)
Initialises the map using the list of edge names.
NBJoinedEdgesMap ()
Constructor.
~NBJoinedEdgesMap ()
Destructor.
Private Types
typedef std::map< std::string,
MappedEdgesVector > JoinedEdgesMap
def. of a map of edge names to lists of previous edges the current edge is made of
typedef std::vector< std::string > MappedEdgesVector
def. of a list of edges that make up an edge
Private Attributes
std::map< std::string, SUMOReal > myLengths
JoinedEdgesMap myMap
Map of edge names to lists of previous edges the current edge is made of.
Friends
std::ostream & operator<< (std::ostream &os, const NBJoinedEdgesMap &map)
Outputs the list of joined edges.
Detailed Description
A structure storing information about which edges were joined.
Definition at line 53 of file NBJoinedEdgesMap.h.
Member Typedef Documentation
typedef std::map<std::string, MappedEdgesVector> NBJoinedEdgesMap::JoinedEdgesMap [private]
def. of a map of edge names to lists of previous edges the current edge is made of
Definition at line 79 of file NBJoinedEdgesMap.h.
typedef std::vector<std::string> NBJoinedEdgesMap::MappedEdgesVector [private]
def. of a list of edges that make up an edge
Definition at line 76 of file NBJoinedEdgesMap.h.
Constructor & Destructor Documentation
NBJoinedEdgesMap::NBJoinedEdgesMap ()
Constructor.
Definition at line 47 of file NBJoinedEdgesMap.cpp.
NBJoinedEdgesMap::~NBJoinedEdgesMap ()
Destructor.
Definition at line 50 of file NBJoinedEdgesMap.cpp.
Member Function Documentation
void NBJoinedEdgesMap::appended (const std::string & to, const std::string & what)
Informs the map that two edges have been joined.
Definition at line 67 of file NBJoinedEdgesMap.cpp.
References myMap.
Referenced by NBNodeCont::removeUnwishedNodes().
void NBJoinedEdgesMap::init (NBEdgeCont & ec)
Initialises the map using the list of edge names.
Definition at line 54 of file NBJoinedEdgesMap.cpp.
References NBEdgeCont::getAllNames(), NBEdge::getLength(), myLengths, myMap, and NBEdgeCont::retrieve().
Referenced by NBNetBuilder::compute().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const NBJoinedEdgesMap & map) [friend]
Outputs the list of joined edges.
Definition at line 76 of file NBJoinedEdgesMap.cpp.
Field Documentation
std::map<std::string, SUMOReal> NBJoinedEdgesMap::myLengths [private]
Definition at line 84 of file NBJoinedEdgesMap.h.
Referenced by init(), and operator<<().
JoinedEdgesMap NBJoinedEdgesMap::myMap [private]
Map of edge names to lists of previous edges the current edge is made of.
Definition at line 82 of file NBJoinedEdgesMap.h.
Referenced by appended(), init(), and operator<<().
The documentation for this class was generated from the following files:
NBJoinedEdgesMap.h
NBJoinedEdgesMap.cpp