SUMO - Simulation of Urban MObility: NIVissimTL::NIVissimTLSignal Class Reference
NIVissimTL::NIVissimTLSignal Class Reference
#include <NIVissimTL.h>
Public Member Functions
bool addTo (NBEdgeCont &ec, NBLoadedTLDef *node) const
Position getPosition () const
bool isWithin (const PositionVector &poly) const
NIVissimTLSignal (int lsaid, int id, const std::string &name, const IntVector &groupids, int edgeid, int laneno, SUMOReal position, const IntVector &assignedVehicleTypes)
~NIVissimTLSignal ()
Static Public Member Functions
static void clearDict ()
static NIVissimTLSignal * dictionary (int lsaid, int id)
static bool dictionary (int lsaid, int id, NIVissimTLSignal *o)
static SSignalDictType getSignalsFor (int tlid)
Protected Attributes
int myEdgeID
IntVector myGroupIDs
int myID
int myLane
int myLSA
std::string myName
SUMOReal myPosition
IntVector myVehicleTypes
Static Protected Attributes
static SignalDictType myDict
Detailed Description
Definition at line 84 of file NIVissimTL.h.
Constructor & Destructor Documentation
NIVissimTL::NIVissimTLSignal::NIVissimTLSignal (int lsaid, int id, const std::string & name, const IntVector & groupids, int edgeid, int laneno, SUMOReal position, const IntVector & assignedVehicleTypes)
Definition at line 65 of file NIVissimTL.cpp.
NIVissimTL::NIVissimTLSignal::~NIVissimTLSignal ()
Definition at line 77 of file NIVissimTL.cpp.
Member Function Documentation
bool NIVissimTL::NIVissimTLSignal::addTo (NBEdgeCont & ec, NBLoadedTLDef * node) const
Definition at line 144 of file NIVissimTL.cpp.
References NBLoadedTLDef::addToSignalGroup(), dictionary(), NBEdge::getConnectionsFromLane(), NIVissimConnection::getFromEdgeID(), NBEdge::getNumLanes(), NIVissimConnection::getToEdgeID(), NBEdge::lanesWereAssigned(), myEdgeID, myGroupIDs, myLane, myPosition, NBEdgeCont::retrievePossiblySplitted(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), and WRITE_WARNING.
void NIVissimTL::NIVissimTLSignal::clearDict () [static]
Definition at line 123 of file NIVissimTL.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
NIVissimTL::NIVissimTLSignal * NIVissimTL::NIVissimTLSignal::dictionary (int lsaid, int id) [static]
Definition at line 109 of file NIVissimTL.cpp.
References myDict.
bool NIVissimTL::NIVissimTLSignal::dictionary (int lsaid, int id, NIVissimTL::NIVissimTLSignal * o) [static]
Definition at line 92 of file NIVissimTL.cpp.
References myDict.
Referenced by addTo(), getPosition(), and NIVissimSingleTypeParser_Signalgeberdefinition::parse().
Position NIVissimTL::NIVissimTLSignal::getPosition () const
Definition at line 86 of file NIVissimTL.cpp.
References dictionary(), myEdgeID, and myPosition.
Referenced by isWithin().
NIVissimTL::SSignalDictType NIVissimTL::NIVissimTLSignal::getSignalsFor (int tlid) [static]
Definition at line 134 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimTL::dict_SetSignals().
bool NIVissimTL::NIVissimTLSignal::isWithin (const PositionVector & poly) const
Definition at line 80 of file NIVissimTL.cpp.
References PositionVector::around(), and getPosition().
Field Documentation
NIVissimTL::SignalDictType NIVissimTL::NIVissimTLSignal::myDict [static, protected]
Definition at line 109 of file NIVissimTL.h.
Referenced by clearDict(), dictionary(), and getSignalsFor().
int NIVissimTL::NIVissimTLSignal::myEdgeID [protected]
Definition at line 105 of file NIVissimTL.h.
Referenced by addTo(), and getPosition().
IntVector NIVissimTL::NIVissimTLSignal::myGroupIDs [protected]
Definition at line 104 of file NIVissimTL.h.
Referenced by addTo().
int NIVissimTL::NIVissimTLSignal::myID [protected]
Definition at line 102 of file NIVissimTL.h.
int NIVissimTL::NIVissimTLSignal::myLane [protected]
Definition at line 106 of file NIVissimTL.h.
Referenced by addTo().
int NIVissimTL::NIVissimTLSignal::myLSA [protected]
Definition at line 101 of file NIVissimTL.h.
std::string NIVissimTL::NIVissimTLSignal::myName [protected]
Definition at line 103 of file NIVissimTL.h.
SUMOReal NIVissimTL::NIVissimTLSignal::myPosition [protected]
Definition at line 107 of file NIVissimTL.h.
Referenced by addTo(), and getPosition().
IntVector NIVissimTL::NIVissimTLSignal::myVehicleTypes [protected]
Definition at line 108 of file NIVissimTL.h.
The documentation for this class was generated from the following files:
NIVissimTL.h
NIVissimTL.cpp