SUMO - Simulation of Urban MObility: MSJunction Class Reference
MSJunction Class Reference
The base class for an intersection.
#include <MSJunction.h>
Public Member Functions
virtual const std::vector
< MSLane * > & getFoeInternalLanes (const MSLink *const) const
virtual const std::vector
< MSLink * > & getFoeLinks (const MSLink *const) const
const std::string & getID () const
Returns the id of the junction.
const Position & getPosition () const
const PositionVector & getShape () const
Returns this junction's shape.
MSJunction (const std::string &id, const Position &position, const PositionVector &shape)
Constructor.
virtual void postloadInit ()
virtual ~MSJunction ()
Destructor.
Protected Attributes
std::vector< MSLane * > myEmptyLanes
std::vector< MSLink * > myEmptyLinks
std::string myID
The id of the junction.
Position myPosition
The position of the junction.
PositionVector myShape
The shape of the junction.
Private Member Functions
MSJunction (const MSJunction &)
Invalidated copy constructor.
MSJunction & operator= (const MSJunction &)
Invalidated assignment operator.
Detailed Description
The base class for an intersection.
Definition at line 56 of file MSJunction.h.
Constructor & Destructor Documentation
MSJunction::~MSJunction () [virtual]
Destructor.
Definition at line 54 of file MSJunction.cpp.
MSJunction::MSJunction (const std::string & id, const Position & position, const PositionVector & shape)
Constructor.
Parameters:
[in] id The id of the junction
[in] position The position of the junction
[in] shape The shape of the junction
Definition at line 49 of file MSJunction.cpp.
MSJunction::MSJunction (const MSJunction &) [private]
Invalidated copy constructor.
Member Function Documentation
virtual const std::vector<MSLane*>& MSJunction::getFoeInternalLanes (const MSLink * const) const [inline, virtual]
Reimplemented in MSInternalJunction, and MSRightOfWayJunction.
Definition at line 91 of file MSJunction.h.
References myEmptyLanes.
virtual const std::vector<MSLink*>& MSJunction::getFoeLinks (const MSLink * const) const [inline, virtual]
Reimplemented in MSInternalJunction, and MSRightOfWayJunction.
Definition at line 87 of file MSJunction.h.
References myEmptyLinks.
const std::string & MSJunction::getID () const
Returns the id of the junction.
Definition at line 68 of file MSJunction.cpp.
References myID.
const Position & MSJunction::getPosition () const
returns the junction's position
Definition at line 58 of file MSJunction.cpp.
References myPosition.
Referenced by GUIJunctionWrapper::drawGL(), GUINet::getJunctionPosition(), GUIJunctionWrapper::GUIJunctionWrapper(), and TraCIServerAPI_Junction::processGet().
const PositionVector& MSJunction::getShape () const [inline]
Returns this junction's shape.
Returns:
The shape of this junction
Definition at line 83 of file MSJunction.h.
References myShape.
Referenced by GUIJunctionWrapper::drawGL(), and GUIJunctionWrapper::GUIJunctionWrapper().
MSJunction& MSJunction::operator= (const MSJunction &) [private]
Invalidated assignment operator.
void MSJunction::postloadInit () [virtual]
performs some initialisation after the loading (e.g., link map computation)
Reimplemented in MSInternalJunction, MSLogicJunction, MSNoLogicJunction, and MSRightOfWayJunction.
Definition at line 64 of file MSJunction.cpp.
Field Documentation
std::vector<MSLane*> MSJunction::myEmptyLanes [protected]
Definition at line 106 of file MSJunction.h.
Referenced by getFoeInternalLanes().
std::vector<MSLink*> MSJunction::myEmptyLinks [protected]
Definition at line 105 of file MSJunction.h.
Referenced by getFoeLinks().
std::string MSJunction::myID [protected]
The id of the junction.
Definition at line 97 of file MSJunction.h.
Referenced by getID().
Position MSJunction::myPosition [protected]
The position of the junction.
Definition at line 100 of file MSJunction.h.
Referenced by getPosition().
PositionVector MSJunction::myShape [protected]
The shape of the junction.
Definition at line 103 of file MSJunction.h.
Referenced by getShape().
The documentation for this class was generated from the following files:
MSJunction.h
MSJunction.cpp