SUMO - Simulation of Urban MObility: NBContHelper::same_connection_edge_sorter Class Reference
NBContHelper::same_connection_edge_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
std::pair< SUMOReal, SUMOReal > getMinMaxRelAngles (NBEdge *e) const
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
same_connection_edge_sorter ()
constructor
Detailed Description
same_connection_edge_sorter This class is used to sort edges which connect the same nodes. The edges are sorted in dependence to edges connecting them. The rightmost will be the first in the list; the leftmost the last one.
Definition at line 317 of file NBContHelper.h.
Constructor & Destructor Documentation
NBContHelper::same_connection_edge_sorter::same_connection_edge_sorter () [inline, explicit]
constructor
Definition at line 320 of file NBContHelper.h.
Member Function Documentation
std::pair<SUMOReal, SUMOReal> NBContHelper::same_connection_edge_sorter::getMinMaxRelAngles (NBEdge * e) const [inline]
Definition at line 341 of file NBContHelper.h.
References NBEdge::getAngle(), NBEdge::getConnectedEdges(), max, min, NBHelpers::normRelAngle(), and SUMOReal.
Referenced by operator()().
int NBContHelper::same_connection_edge_sorter::operator() (NBEdge * e1, NBEdge * e2) const [inline]
comparing operation
Definition at line 323 of file NBContHelper.h.
References Named::getID(), and getMinMaxRelAngles().
The documentation for this class was generated from the following file:
NBContHelper.h