SUMO - Simulation of Urban MObility: GUIDialog_ViewSettings::NamePanel Class Reference
GUIDialog_ViewSettings::NamePanel Class Reference
#include <GUIDialog_ViewSettings.h>
Public Member Functions
GUIVisualizationTextSettings getSettings ()
NamePanel (FXMatrix *parent, GUIDialog_ViewSettings *target, const std::string &title, const GUIVisualizationTextSettings &settings)
void update (const GUIVisualizationTextSettings &settings)
Data Fields
FXCheckButton * myCheck
FXColorWell * myColorWell
FXRealSpinDial * mySizeDial
Detailed Description
Definition at line 61 of file GUIDialog_ViewSettings.h.
Constructor & Destructor Documentation
GUIDialog_ViewSettings::NamePanel::NamePanel (FXMatrix * parent, GUIDialog_ViewSettings * target, const std::string & title, const GUIVisualizationTextSettings & settings)
Definition at line 1270 of file GUIDialog_ViewSettings.cpp.
References GUIVisualizationTextSettings::color, GUIDialog_ViewSettings::convert(), MID_SIMPLE_VIEW_COLORCHANGE, myCheck, myColorWell, mySizeDial, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Member Function Documentation
GUIVisualizationTextSettings GUIDialog_ViewSettings::NamePanel::getSettings ()
Definition at line 1295 of file GUIDialog_ViewSettings.cpp.
References GUIDialog_ViewSettings::convert(), myCheck, myColorWell, and mySizeDial.
Referenced by GUIDialog_ViewSettings::onCmdColorChange().
void GUIDialog_ViewSettings::NamePanel::update (const GUIVisualizationTextSettings & settings)
Definition at line 1302 of file GUIDialog_ViewSettings.cpp.
References GUIVisualizationTextSettings::color, GUIDialog_ViewSettings::convert(), myCheck, myColorWell, mySizeDial, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GUIDialog_ViewSettings::onCmdNameChange().
Field Documentation
FXCheckButton* GUIDialog_ViewSettings::NamePanel::myCheck
Definition at line 70 of file GUIDialog_ViewSettings.h.
Referenced by getSettings(), NamePanel(), and update().
FXColorWell* GUIDialog_ViewSettings::NamePanel::myColorWell
Definition at line 72 of file GUIDialog_ViewSettings.h.
Referenced by getSettings(), NamePanel(), and update().
FXRealSpinDial* GUIDialog_ViewSettings::NamePanel::mySizeDial
Definition at line 71 of file GUIDialog_ViewSettings.h.
Referenced by getSettings(), NamePanel(), and update().
The documentation for this class was generated from the following files:
GUIDialog_ViewSettings.h
GUIDialog_ViewSettings.cpp