SUMO - Simulation of Urban MObility: BiArc Class Reference
BiArc Class Reference
#include <BiArc.h>
Public Member Functions
BiArc (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle)
BiArc ()
double compute_arclength (double theta0, double theta2, double k)
void compute_biarc_params ()
double compute_join_theta (double k1, double k2)
void compute_other_stuff ()
void set_end_params (Point2D< double > end_pt, double end_angle)
void set_start_params (Point2D< double > start_pt, double start_angle)
~BiArc ()
Data Fields
BiArcParams params
Detailed Description
Definition at line 165 of file BiArc.h.
Constructor & Destructor Documentation
BiArc::BiArc () [inline]
Definition at line 170 of file BiArc.h.
BiArc::BiArc (Point2D< double > start_pt, double start_angle, Point2D< double > end_pt, double end_angle) [inline]
Definition at line 171 of file BiArc.h.
References angle0To2Pi(), compute_biarc_params(), BiArcParams::end_angle, BiArcParams::end_pt, params, BiArcParams::start_angle, and BiArcParams::start_pt.
BiArc::~BiArc () [inline]
Definition at line 183 of file BiArc.h.
Member Function Documentation
double BiArc::compute_arclength (double theta0, double theta2, double k)
Definition at line 190 of file BiArc.cpp.
References M_PI.
Referenced by compute_biarc_params().
void BiArc::compute_biarc_params (void)
Definition at line 4 of file BiArc.cpp.
References compute_arclength(), compute_join_theta(), compute_other_stuff(), BiArcParams::E, eA, eK, BiArcParams::end_angle, BiArcParams::end_pt, euc_distance(), BiArcParams::flag, BiArcParams::K1, BiArcParams::K2, BiArcParams::L1, BiArcParams::L2, M_PI, params, BiArcParams::start_angle, BiArcParams::start_pt, Point2D< coord_type >::x(), and Point2D< coord_type >::y().
Referenced by BiArc(), and EulerSpiral::compute_es_params().
double BiArc::compute_join_theta (double k1, double k2)
Definition at line 171 of file BiArc.cpp.
References BiArcParams::end_angle, BiArcParams::end_pt, M_PI, params, BiArcParams::start_angle, BiArcParams::start_pt, Point2D< coord_type >::x(), and Point2D< coord_type >::y().
Referenced by compute_biarc_params().
void BiArc::compute_other_stuff (void)
Definition at line 140 of file BiArc.cpp.
References BiArcParams::center1, BiArcParams::center2, BiArcParams::dir1, BiArcParams::dir2, BiArcParams::end_angle, BiArcParams::end_pt, BiArcParams::K1, BiArcParams::K2, BiArcParams::L1, M_PI, BiArcParams::mid_pt, params, BiArcParams::R1, BiArcParams::R2, Point2D< coord_type >::setX(), Point2D< coord_type >::setY(), BiArcParams::start_angle, BiArcParams::start_pt, Point2D< coord_type >::x(), and Point2D< coord_type >::y().
Referenced by compute_biarc_params().
void BiArc::set_end_params (Point2D< double > end_pt, double end_angle) [inline]
Definition at line 196 of file BiArc.h.
References angle0To2Pi(), BiArcParams::end_angle, BiArcParams::end_pt, and params.
Referenced by EulerSpiral::compute_es_params().
void BiArc::set_start_params (Point2D< double > start_pt, double start_angle) [inline]
Definition at line 190 of file BiArc.h.
References angle0To2Pi(), params, BiArcParams::start_angle, and BiArcParams::start_pt.
Referenced by EulerSpiral::compute_es_params().
Field Documentation
BiArcParams BiArc::params
Definition at line 168 of file BiArc.h.
Referenced by BiArc(), compute_biarc_params(), EulerSpiral::compute_es_params(), compute_join_theta(), compute_other_stuff(), set_end_params(), and set_start_params().
The documentation for this class was generated from the following files:
BiArc.h
BiArc.cpp