SUMO - Simulation of Urban MObility: MSTLLogicControl::WAUTSwitchProcedure_GSP Class Reference
MSTLLogicControl::WAUTSwitchProcedure_GSP Class Reference
This class switches using the GSP algorithm.
#include <MSTLLogicControl.h>
Public Member Functions
bool trySwitch (SUMOTime step)
Determines whether a switch is possible.
WAUTSwitchProcedure_GSP (MSTLLogicControl &control, WAUT &waut, MSTrafficLightLogic *from, MSTrafficLightLogic *to, bool synchron)
Constructor.
~WAUTSwitchProcedure_GSP ()
Destructor.
Protected Member Functions
void adaptLogic (SUMOTime step)
Stretches the destination program's phase to which the tls was switched.
SUMOTime getDiffToStartOfPhase (MSTrafficLightLogic &logic, SUMOTime toTime)
Returns the difference between a given time and the start of the phase.
unsigned int getGSPValue (const MSTrafficLightLogic &logic) const
Returns the GSP-value.
bool isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic &logic)
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt").
void switchToPos (SUMOTime simStep, MSTrafficLightLogic &logic, SUMOTime toTime)
switches the given logic directly to the given position
Protected Attributes
MSTLLogicControl & myControl
The control the logic belongs to.
MSTrafficLightLogic * myFrom
The current program of the tls to switch.
bool mySwitchSynchron
Information whether to switch synchron (?).
MSTrafficLightLogic * myTo
The program to switch the tls to.
WAUT & myWAUT
The WAUT responsible for switching.
Private Member Functions
WAUTSwitchProcedure_GSP & operator= (const WAUTSwitchProcedure_GSP &)
Invalidated assignment operator.
WAUTSwitchProcedure_GSP (const WAUTSwitchProcedure_GSP &)
Invalidated copy constructor.
Detailed Description
This class switches using the GSP algorithm.
Definition at line 641 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
MSTLLogicControl::WAUTSwitchProcedure_GSP::WAUTSwitchProcedure_GSP (MSTLLogicControl & control, WAUT & waut, MSTrafficLightLogic * from, MSTrafficLightLogic * to, bool synchron)
Constructor.
Parameters:
[in] control The responsible tls control
[in] waut The WAUT to switch
[in] from The original tls program
[in] to The destination tls program
[in] synchron Whether the switch shall be done in synchronuous mode
Definition at line 282 of file MSTLLogicControl.cpp.
MSTLLogicControl::WAUTSwitchProcedure_GSP::~WAUTSwitchProcedure_GSP ()
Destructor.
Definition at line 288 of file MSTLLogicControl.cpp.
MSTLLogicControl::WAUTSwitchProcedure_GSP::WAUTSwitchProcedure_GSP (const WAUTSwitchProcedure_GSP &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic (SUMOTime step) [protected]
Stretches the destination program's phase to which the tls was switched.
Definition at line 310 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSPhaseDefinition::duration, MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getDefaultCycleTime(), MSTLLogicControl::WAUTSwitchProcedure::getDiffToStartOfPhase(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), MSTrafficLightLogic::getPhase(), MSTLLogicControl::WAUTSwitchProcedure::myControl, MSTLLogicControl::WAUTSwitchProcedure::myTo, and TIME2STEPS.
Referenced by trySwitch().
SUMOTime MSTLLogicControl::WAUTSwitchProcedure::getDiffToStartOfPhase (MSTrafficLightLogic & logic, SUMOTime toTime) [protected, inherited]
Returns the difference between a given time and the start of the phase.
Parameters:
[in] logic The logic to consider
[in] toTime The time to ask for
Returns:
How much time elapsed between the last pahse start and the given time
Definition at line 241 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::getIndexFromOffset(), and MSTrafficLightLogic::getOffsetFromIndex().
Referenced by adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and MSTLLogicControl::WAUTSwitchProcedure::switchToPos().
unsigned int MSTLLogicControl::WAUTSwitchProcedure::getGSPValue (const MSTrafficLightLogic & logic) const [protected, inherited]
Returns the GSP-value.
The GSP must be given as a logic's parameter ("GSP").
Parameters:
[in] logic The logic to retrieve the GSP from
Returns:
The GSP value; 0 if not given.
See also:
MSTrafficLightLogic::getParameterValue
Definition at line 222 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::getParameterValue().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
bool MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic & logic) [protected, inherited]
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt").
The GSP must be given as a logic's parameter ("GSP"). Not the simulation second, but the phase the GSP lies within is used. If the phase the GSP lies within is the same as the logic's current phase, the result is true.
Parameters:
[in] currentTime The current time step
[in] logic The logic for which this should be examined
Returns:
Whether the current step is the GSP
See also:
getGSPValue
Definition at line 232 of file MSTLLogicControl.cpp.
References MSPhaseDefinition::duration, MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getDefaultCycleTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), and TIME2STEPS.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
WAUTSwitchProcedure_GSP& MSTLLogicControl::WAUTSwitchProcedure_GSP::operator= (const WAUTSwitchProcedure_GSP &) [private]
Invalidated assignment operator.
void MSTLLogicControl::WAUTSwitchProcedure::switchToPos (SUMOTime simStep, MSTrafficLightLogic & logic, SUMOTime toTime) [protected, inherited]
switches the given logic directly to the given position
Parameters:
[in] simStep The current simulation time
[in] logic The logic to switch
[in] toTime The time offset within the logic's phases to switch to
Definition at line 250 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSPhaseDefinition::duration, MSTLLogicControl::WAUTSwitchProcedure::getDiffToStartOfPhase(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getPhase(), and MSTLLogicControl::WAUTSwitchProcedure::myControl.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
bool MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch (SUMOTime step) [virtual]
Determines whether a switch is possible.
Parameters:
[in] step The current simulation step
Returns:
If a switch shall be done, this method should return true.
Implements MSTLLogicControl::WAUTSwitchProcedure.
Definition at line 292 of file MSTLLogicControl.cpp.
References adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), MSTLLogicControl::WAUTSwitchProcedure::myFrom, MSTLLogicControl::WAUTSwitchProcedure::mySwitchSynchron, MSTLLogicControl::WAUTSwitchProcedure::myTo, MSTLLogicControl::WAUTSwitchProcedure::switchToPos(), and TIME2STEPS.
Field Documentation
MSTLLogicControl& MSTLLogicControl::WAUTSwitchProcedure::myControl [protected, inherited]
The control the logic belongs to.
Definition at line 584 of file MSTLLogicControl.h.
Referenced by adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and MSTLLogicControl::WAUTSwitchProcedure::switchToPos().
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myFrom [protected, inherited]
The current program of the tls to switch.
Definition at line 572 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
bool MSTLLogicControl::WAUTSwitchProcedure::mySwitchSynchron [protected, inherited]
Information whether to switch synchron (?).
Definition at line 578 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myTo [protected, inherited]
The program to switch the tls to.
Definition at line 575 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch(), and trySwitch().
WAUT& MSTLLogicControl::WAUTSwitchProcedure::myWAUT [protected, inherited]
The WAUT responsible for switching.
Definition at line 581 of file MSTLLogicControl.h.
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp