SUMO - Simulation of Urban MObility: NBContHelper::edge_by_priority_sorter Class Reference
NBContHelper::edge_by_priority_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operator
Detailed Description
edge_by_priority_sorter Class to sort edges by their priority
Definition at line 138 of file NBContHelper.h.
Member Function Documentation
int NBContHelper::edge_by_priority_sorter::operator() (NBEdge * e1, NBEdge * e2) const [inline]
comparing operator
Definition at line 141 of file NBContHelper.h.
References NBEdge::getNumLanes(), NBEdge::getPriority(), and NBEdge::getSpeed().
The documentation for this class was generated from the following file:
NBContHelper.h