SUMO - Simulation of Urban MObility: MSXMLRawOut Class Reference
MSXMLRawOut Class Reference
Realises dumping the complete network state.
#include <MSXMLRawOut.h>
Static Public Member Functions
static void write (OutputDevice &of, const MSEdgeControl &ec, SUMOTime timestep)
Writes the complete network state of the given edges into the given device.
static void writeFev (OutputDevice &of, const MSEdgeControl &ec, SUMOTime timestep)
static void writeVehicle (OutputDevice &of, const MSVehicle &veh)
Writes the dump of the given vehicle into the given device.
static void writeVehicleFev (OutputDevice &of, SUMOTime timestep, const MSEdge &edge, const MSLane &lane, const MSVehicle &veh)
Private Member Functions
MSXMLRawOut (const MSXMLRawOut &)
Invalidated copy constructor.
MSXMLRawOut & operator= (const MSXMLRawOut &)
Invalidated assignment operator.
Static Private Member Functions
static void writeEdge (OutputDevice &of, const MSEdge &edge)
Writes the dump of the given edge into the given device.
static void writeLane (OutputDevice &of, const MSLane &lane)
Writes the dump of the given lane into the given device.
Detailed Description
Realises dumping the complete network state.
The class offers a static method, which writes the complete dump of the given network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 61 of file MSXMLRawOut.h.
Constructor & Destructor Documentation
MSXMLRawOut::MSXMLRawOut (const MSXMLRawOut &) [private]
Invalidated copy constructor.
Member Function Documentation
MSXMLRawOut& MSXMLRawOut::operator= (const MSXMLRawOut &) [private]
Invalidated assignment operator.
void MSXMLRawOut::write (OutputDevice & of, const MSEdgeControl & ec, SUMOTime timestep) [static]
Writes the complete network state of the given edges into the given device.
Opens the current time step, goes through the edges and writes each using writeEdge.
Parameters:
[in] of The output device to use
[in] ec The EdgeControl which holds the edges to write
[in] timestep The current time step
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 59 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSEdgeControl::getEdges(), OutputDevice::openTag(), time2string(), and writeEdge().
void MSXMLRawOut::writeEdge (OutputDevice & of, const MSEdge & edge) [static, private]
Writes the dump of the given edge into the given device.
If the edge is not empty or also empty edges shall be dumped, the edge description is opened and writeLane is called for each lane.
Parameters:
[in] of The output device to use
[in] edge The edge to dump
Todo:
MSGlobals::gOmitEmptyEdgesOnDump should not be used; rather the according option read in write
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 71 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSEdge::getID(), MSEdge::getLanes(), MSGlobals::gOmitEmptyEdgesOnDump, OutputDevice::openTag(), and writeLane().
Referenced by write().
static void MSXMLRawOut::writeFev (OutputDevice & of, const MSEdgeControl & ec, SUMOTime timestep) [static]
void MSXMLRawOut::writeLane (OutputDevice & of, const MSLane & lane) [static, private]
Writes the dump of the given lane into the given device.
Opens the lane description and goes through all vehicles, calling writeVehicle for each.
Parameters:
[in] of The output device to use
[in] lane The lane to dump
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 123 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSLane::getVehicleNumber(), Named::myID, MSLane::myVehBuffer, MSLane::myVehicles, OutputDevice::openTag(), and writeVehicle().
Referenced by writeEdge().
void MSXMLRawOut::writeVehicle (OutputDevice & of, const MSVehicle & veh) [static]
Writes the dump of the given vehicle into the given device.
Parameters:
[in] of The output device to use
[in] veh The vehicle to dump
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 141 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSNet::getCurrentTimeStep(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getMyState(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicle::isOnRoad(), OutputDevice::openTag(), and time2string().
Referenced by writeLane().
static void MSXMLRawOut::writeVehicleFev (OutputDevice & of, SUMOTime timestep, const MSEdge & edge, const MSLane & lane, const MSVehicle & veh) [static]
The documentation for this class was generated from the following files:
MSXMLRawOut.h
MSXMLRawOut.cpp