SUMO - Simulation of Urban MObility: NIVissimDisturbance Class Reference
NIVissimDisturbance Class Reference
#include <NIVissimDisturbance.h>
Public Member Functions
bool addToNode (NBNode *node, NBDistrictCont &dc, NBNodeCont &nc, NBEdgeCont &ec)
bool clustered () const
void computeBounding ()
bool crosses (const AbstractPoly &poly, SUMOReal offset=0) const
const Boundary & getBoundary () const
NBConnection getConnection (NBNode *node, int aedgeid)
int getDisturbanceID () const
int getEdgeID () const
void inCluster (int id)
NIVissimDisturbance (int id, const std::string &name, const NIVissimExtendedEdgePoint &edge, const NIVissimExtendedEdgePoint &by, SUMOReal timegap, SUMOReal waygap, SUMOReal vmax)
virtual ~NIVissimDisturbance ()
Static Public Member Functions
static void clearDict ()
static void closeLoading ()
static void dict_SetDisturbances ()
static NIVissimDisturbance * dictionary (int id)
static bool dictionary (int id, NIVissimDisturbance *o)
static bool dictionary (int id, const std::string &name, const NIVissimExtendedEdgePoint &edge, const NIVissimExtendedEdgePoint &by, SUMOReal timegap, SUMOReal waygap, SUMOReal vmax)
static IntVector getWithin (const AbstractPoly &poly)
static void reportRefused ()
Protected Types
typedef std::set
< NIVissimBoundedClusterObject * > ContType
Protected Attributes
Boundary * myBoundary
int myClusterID
Private Types
typedef std::map< int,
NIVissimDisturbance * > DictType
Private Attributes
NIVissimExtendedEdgePoint myDisturbance
NIVissimExtendedEdgePoint myEdge
int myID
std::string myName
int myNode
SUMOReal myTimeGap
SUMOReal myVMax
SUMOReal myWayGap
Static Private Attributes
static DictType myDict
static int myRunningID = 100000000
static int refusedProhibits = 0
Detailed Description
Definition at line 50 of file NIVissimDisturbance.h.
Member Typedef Documentation
typedef std::set<NIVissimBoundedClusterObject*> NIVissimBoundedClusterObject::ContType [protected, inherited]
Definition at line 60 of file NIVissimBoundedClusterObject.h.
typedef std::map<int, NIVissimDisturbance*> NIVissimDisturbance::DictType [private]
Definition at line 89 of file NIVissimDisturbance.h.
Constructor & Destructor Documentation
NIVissimDisturbance::NIVissimDisturbance (int id, const std::string & name, const NIVissimExtendedEdgePoint & edge, const NIVissimExtendedEdgePoint & by, SUMOReal timegap, SUMOReal waygap, SUMOReal vmax)
Definition at line 66 of file NIVissimDisturbance.cpp.
Referenced by dictionary().
NIVissimDisturbance::~NIVissimDisturbance () [virtual]
Definition at line 76 of file NIVissimDisturbance.cpp.
Member Function Documentation
bool NIVissimDisturbance::addToNode (NBNode * node, NBDistrictCont & dc, NBNodeCont & nc, NBEdgeCont & ec)
Definition at line 146 of file NIVissimDisturbance.cpp.
References NBNode::addSortedLinkFoes(), NBConnection::check(), NIVissimAbstractEdge::crossesEdgeAtPoint(), dictionary(), NBEdge::getConnectedEdges(), getConnection(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimConnection::getFromEdgeID(), NBEdge::getFromNode(), Named::getID(), NIVissimAbstractEdge::getID(), NIVissimExtendedEdgePoint::getPosition(), NIVissimConnection::getToEdgeID(), NBEdge::getToNode(), myDisturbance, myEdge, myNode, refusedProhibits, NBEdgeCont::retrieve(), NBNodeCont::retrieve(), NBEdgeCont::retrievePossiblySplitted(), NBEdgeCont::splitAt(), and WRITE_WARNING.
Referenced by NIVissimNodeCluster::dict_addDisturbances().
void NIVissimDisturbance::clearDict () [static]
Definition at line 347 of file NIVissimDisturbance.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
void NIVissimBoundedClusterObject::closeLoading () [static, inherited]
Definition at line 74 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
bool NIVissimBoundedClusterObject::clustered () const [inherited]
Definition at line 68 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
Referenced by NIVissimConnection::buildNodeClusters().
void NIVissimDisturbance::computeBounding () [virtual]
Implements NIVissimBoundedClusterObject.
Definition at line 130 of file NIVissimDisturbance.cpp.
References Boundary::add(), NIVissimAbstractEdge::dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimBoundedClusterObject::myBoundary, myDisturbance, myEdge, Boundary::xmax(), and Boundary::xmin().
bool NIVissimBoundedClusterObject::crosses (const AbstractPoly & poly, SUMOReal offset = 0) const [inherited]
Definition at line 54 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
void NIVissimDisturbance::dict_SetDisturbances () [static]
Definition at line 356 of file NIVissimDisturbance.cpp.
References dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), myDict, myDisturbance, and myEdge.
Referenced by NIImporter_Vissim::postLoadBuild().
NIVissimDisturbance * NIVissimDisturbance::dictionary (int id) [static]
Definition at line 109 of file NIVissimDisturbance.cpp.
References myDict.
bool NIVissimDisturbance::dictionary (int id, NIVissimDisturbance * o) [static]
Definition at line 98 of file NIVissimDisturbance.cpp.
References myDict.
bool NIVissimDisturbance::dictionary (int id, const std::string & name, const NIVissimExtendedEdgePoint & edge, const NIVissimExtendedEdgePoint & by, SUMOReal timegap, SUMOReal waygap, SUMOReal vmax) [static]
Definition at line 81 of file NIVissimDisturbance.cpp.
References myRunningID, NIVissimDisturbance(), and UNUSED_PARAMETER.
Referenced by addToNode(), dict_SetDisturbances(), getConnection(), NIVissimConnectionCluster::getDisturbanceParticipators(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), and NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed().
const Boundary & NIVissimBoundedClusterObject::getBoundary () const [inherited]
Definition at line 82 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary.
Referenced by NIVissimConnectionCluster::liesOnSameEdgesEnd().
NBConnection NIVissimDisturbance::getConnection (NBNode * node, int aedgeid)
Definition at line 327 of file NIVissimDisturbance.cpp.
References dictionary(), NIVissimEdge::dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimConnection::getFromEdgeID(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIVissimConnection::getToEdgeID(), myEdge, and WRITE_WARNING.
Referenced by addToNode().
int NIVissimDisturbance::getDisturbanceID () const [inline]
Definition at line 64 of file NIVissimDisturbance.h.
References NIVissimExtendedEdgePoint::getEdgeID(), and myDisturbance.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
int NIVissimDisturbance::getEdgeID () const [inline]
Definition at line 61 of file NIVissimDisturbance.h.
References NIVissimExtendedEdgePoint::getEdgeID(), and myEdge.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
IntVector NIVissimDisturbance::getWithin (const AbstractPoly & poly) [static]
Definition at line 118 of file NIVissimDisturbance.cpp.
References myDict.
Referenced by NIVissimConnectionCluster::buildNodeClusters().
void NIVissimBoundedClusterObject::inCluster (int id) [inherited]
Definition at line 62 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
void NIVissimDisturbance::reportRefused () [static]
Definition at line 370 of file NIVissimDisturbance.cpp.
References myDict, refusedProhibits, and WRITE_WARNING.
Referenced by NIVissimNodeCluster::dict_addDisturbances().
Field Documentation
Boundary* NIVissimBoundedClusterObject::myBoundary [protected, inherited]
Definition at line 62 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimConnection::buildNodeClusters(), computeBounding(), NIVissimConnection::computeBounding(), NIVissimBoundedClusterObject::crosses(), NIVissimBoundedClusterObject::getBoundary(), NIVissimConnection::getBoundingBox(), and NIVissimBoundedClusterObject::~NIVissimBoundedClusterObject().
int NIVissimBoundedClusterObject::myClusterID [protected, inherited]
Definition at line 63 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimBoundedClusterObject::clustered(), and NIVissimBoundedClusterObject::inCluster().
NIVissimDisturbance::DictType NIVissimDisturbance::myDict [static, private]
Reimplemented from NIVissimBoundedClusterObject.
Definition at line 90 of file NIVissimDisturbance.h.
Referenced by clearDict(), dict_SetDisturbances(), dictionary(), getWithin(), and reportRefused().
NIVissimExtendedEdgePoint NIVissimDisturbance::myDisturbance [private]
Definition at line 86 of file NIVissimDisturbance.h.
Referenced by addToNode(), computeBounding(), dict_SetDisturbances(), and getDisturbanceID().
NIVissimExtendedEdgePoint NIVissimDisturbance::myEdge [private]
Definition at line 85 of file NIVissimDisturbance.h.
Referenced by addToNode(), computeBounding(), dict_SetDisturbances(), getConnection(), and getEdgeID().
int NIVissimDisturbance::myID [private]
Definition at line 82 of file NIVissimDisturbance.h.
std::string NIVissimDisturbance::myName [private]
Definition at line 84 of file NIVissimDisturbance.h.
int NIVissimDisturbance::myNode [private]
Definition at line 83 of file NIVissimDisturbance.h.
Referenced by addToNode().
int NIVissimDisturbance::myRunningID = 100000000 [static, private]
Definition at line 91 of file NIVissimDisturbance.h.
Referenced by dictionary().
SUMOReal NIVissimDisturbance::myTimeGap [private]
Definition at line 87 of file NIVissimDisturbance.h.
SUMOReal NIVissimDisturbance::myVMax [private]
Definition at line 87 of file NIVissimDisturbance.h.
SUMOReal NIVissimDisturbance::myWayGap [private]
Definition at line 87 of file NIVissimDisturbance.h.
int NIVissimDisturbance::refusedProhibits = 0 [static, private]
Definition at line 92 of file NIVissimDisturbance.h.
Referenced by addToNode(), and reportRefused().
The documentation for this class was generated from the following files:
NIVissimDisturbance.h
NIVissimDisturbance.cpp