SUMO - Simulation of Urban MObility: MSTriggeredReader Class Reference
MSTriggeredReader Class Reference
#include <MSTriggeredReader.h>
Public Member Functions
void init ()
bool isInitialised () const
SUMOTime wrappedExecute (SUMOTime current)
virtual ~MSTriggeredReader ()
Destructor.
Protected Member Functions
virtual void inputEndReached ()=0
MSTriggeredReader (MSNet &net)
Constructor (for an abstract class).
virtual void myInit ()=0
virtual bool processNextEntryReaderTriggered ()=0
Processes the next event Returns true if the next element shall be read (a new timestemp is then available also) Returns false if the action could not be accomplished; this method is then called in the next step again.
virtual bool readNextTriggered ()=0
Reads from the file.
Protected Attributes
SUMOTime myOffset
The offset to the next event.
bool myWasInitialised
Private Member Functions
MSTriggeredReader (const MSTriggeredReader &)
Invalidated copy constructor.
MSTriggeredReader & operator= (const MSTriggeredReader &)
Invalidated assignment operator.
Detailed Description
Superclass for structures that read from a file where the times the next reading is performed are triggered by events,
Definition at line 46 of file MSTriggeredReader.h.
Constructor & Destructor Documentation
MSTriggeredReader::~MSTriggeredReader () [virtual]
Destructor.
Definition at line 47 of file MSTriggeredReader.cpp.
MSTriggeredReader::MSTriggeredReader (MSNet & net) [protected]
Constructor (for an abstract class).
Definition at line 43 of file MSTriggeredReader.cpp.
MSTriggeredReader::MSTriggeredReader (const MSTriggeredReader &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSTriggeredReader::init ()
Definition at line 51 of file MSTriggeredReader.cpp.
References myInit(), and myWasInitialised.
Referenced by wrappedExecute().
virtual void MSTriggeredReader::inputEndReached () [protected, pure virtual]
bool MSTriggeredReader::isInitialised () const
Definition at line 58 of file MSTriggeredReader.cpp.
References myWasInitialised.
Referenced by wrappedExecute().
virtual void MSTriggeredReader::myInit () [protected, pure virtual]
Implemented in MSTriggeredXMLReader.
Referenced by init().
MSTriggeredReader& MSTriggeredReader::operator= (const MSTriggeredReader &) [private]
Invalidated assignment operator.
virtual bool MSTriggeredReader::processNextEntryReaderTriggered () [protected, pure virtual]
Processes the next event Returns true if the next element shall be read (a new timestemp is then available also) Returns false if the action could not be accomplished; this method is then called in the next step again.
Referenced by wrappedExecute().
virtual bool MSTriggeredReader::readNextTriggered () [protected, pure virtual]
Reads from the file.
Implemented in MSTriggeredXMLReader.
Referenced by wrappedExecute().
SUMOTime MSTriggeredReader::wrappedExecute (SUMOTime current)
Definition at line 64 of file MSTriggeredReader.cpp.
References DELTA_T, init(), isInitialised(), myOffset, processNextEntryReaderTriggered(), and readNextTriggered().
Referenced by MSTriggeredXMLReader::MSTriggeredXMLReader().
Field Documentation
SUMOTime MSTriggeredReader::myOffset [protected]
The offset to the next event.
Definition at line 74 of file MSTriggeredReader.h.
Referenced by MSTriggeredXMLReader::myInit(), and wrappedExecute().
bool MSTriggeredReader::myWasInitialised [protected]
Definition at line 75 of file MSTriggeredReader.h.
Referenced by init(), and isInitialised().
The documentation for this class was generated from the following files:
MSTriggeredReader.h
MSTriggeredReader.cpp