SUMO - Simulation of Urban MObility: MSLane.cpp File Reference
MSLane.cpp File Reference
#include <config.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/StdDefs.h>
#include "MSVehicle.h"
#include "MSVehicleType.h"
#include "MSEdge.h"
#include "MSEdgeControl.h"
#include "MSJunction.h"
#include "MSLogicJunction.h"
#include "MSLink.h"
#include "MSLane.h"
#include "MSVehicleTransfer.h"
#include <string>
#include <vector>
#include "MSGlobals.h"
#include "MSVehicleControl.h"
#include <cmath>
#include <bitset>
#include <iostream>
#include <cassert>
#include <functional>
#include <algorithm>
#include <iterator>
#include <exception>
#include <climits>
#include <set>
#include <utils/common/MsgHandler.h>
#include <utils/common/ToString.h>
#include <utils/options/OptionsCont.h>
#include <utils/common/HelpersHarmonoise.h>
Data Structures
class by_second_sorter
Functions
SUMOReal getMaxSpeedRegardingNextLanes (MSVehicle &veh, SUMOReal speed, SUMOReal pos)
Detailed Description
Author:
Christian Roessel
Jakob Erdmann
Daniel Krajzewicz
Tino Morenz
Axel Wegener
Michael Behrisch
Christoph Sommer
Date:
Mon, 05 Mar 2001
Version:
Id
MSLane.cpp 11701 2012-01-10 22:23:40Z behrisch
Definition in file MSLane.cpp.
Function Documentation
SUMOReal getMaxSpeedRegardingNextLanes (MSVehicle & veh, SUMOReal speed, SUMOReal pos)
Definition at line 708 of file MSLane.cpp.
References MSRoute::begin(), MSCFModel::brakeGap(), MSRoute::end(), MSCFModel::freeSpeed(), MSVehicle::getCarFollowModel(), MSLane::getLength(), MSLane::getMaxSpeed(), MSBaseVehicle::getRoute(), MIN2(), SPEED2DIST, and SUMOReal.