SUMO - Simulation of Urban MObility: NIVissimVehTypeClass Class Reference
NIVissimVehTypeClass Class Reference
#include <NIVissimVehTypeClass.h>
Public Member Functions
SUMOReal meanSpeed () const
NIVissimVehTypeClass (int id, const std::string &name, const RGBColor &color, IntVector &types)
~NIVissimVehTypeClass ()
Static Public Member Functions
static void clearDict ()
static NIVissimVehTypeClass * dictionary (int name)
static bool dictionary (int id, NIVissimVehTypeClass *o)
static bool dictionary (int id, const std::string &name, const RGBColor &color, IntVector &types)
Private Types
typedef std::map< int,
NIVissimVehTypeClass * > DictType
Private Attributes
RGBColor myColor
int myID
std::string myName
IntVector myTypes
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 45 of file NIVissimVehTypeClass.h.
Member Typedef Documentation
typedef std::map<int, NIVissimVehTypeClass*> NIVissimVehTypeClass::DictType [private]
Definition at line 62 of file NIVissimVehTypeClass.h.
Constructor & Destructor Documentation
NIVissimVehTypeClass::NIVissimVehTypeClass (int id, const std::string & name, const RGBColor & color, IntVector & types)
Definition at line 43 of file NIVissimVehTypeClass.cpp.
Referenced by dictionary().
NIVissimVehTypeClass::~NIVissimVehTypeClass ()
Definition at line 49 of file NIVissimVehTypeClass.cpp.
Member Function Documentation
void NIVissimVehTypeClass::clearDict () [static]
Definition at line 89 of file NIVissimVehTypeClass.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
NIVissimVehTypeClass * NIVissimVehTypeClass::dictionary (int name) [static]
Definition at line 79 of file NIVissimVehTypeClass.cpp.
References myDict.
bool NIVissimVehTypeClass::dictionary (int id, NIVissimVehTypeClass * o) [static]
Definition at line 68 of file NIVissimVehTypeClass.cpp.
References myDict.
bool NIVissimVehTypeClass::dictionary (int id, const std::string & name, const RGBColor & color, IntVector & types) [static]
Definition at line 53 of file NIVissimVehTypeClass.cpp.
References NIVissimVehTypeClass().
Referenced by NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse().
SUMOReal NIVissimVehTypeClass::meanSpeed () const
Field Documentation
RGBColor NIVissimVehTypeClass::myColor [private]
Definition at line 59 of file NIVissimVehTypeClass.h.
NIVissimVehTypeClass::DictType NIVissimVehTypeClass::myDict [static, private]
Definition at line 63 of file NIVissimVehTypeClass.h.
Referenced by clearDict(), and dictionary().
int NIVissimVehTypeClass::myID [private]
Definition at line 57 of file NIVissimVehTypeClass.h.
std::string NIVissimVehTypeClass::myName [private]
Definition at line 58 of file NIVissimVehTypeClass.h.
IntVector NIVissimVehTypeClass::myTypes [private]
Definition at line 60 of file NIVissimVehTypeClass.h.
The documentation for this class was generated from the following files:
NIVissimVehTypeClass.h
NIVissimVehTypeClass.cpp