SUMO - Simulation of Urban MObility: NBLoadedSUMOTLDef Class Reference
NBLoadedSUMOTLDef Class Reference
A loaded (complete) traffic light logic.
#include <NBLoadedSUMOTLDef.h>
Data Structures
class connection_equal
class for identifying connections
Public Types
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addConnection (NBEdge *from, NBEdge *to, int fromLane, int toLane, int linkIndex)
Adds a connection and immediately informs the edges.
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of edges not controlled by the tls.
void addPhase (SUMOTime duration, const std::string &state)
Adds a phase to the logic the new phase is inserted at the end of the list of already added phases.
NBTrafficLightLogic * compute (const NBEdgeCont &ec, OptionsCont &oc)
Computes the traffic light logic.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
const std::vector< NBNode * > & getControlledNodes () const
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first).
NBTrafficLightLogic * getLogic ()
Returns the internal logic.
const std::string & getProgramID () const
Returns the ProgramID.
bool isLeftMover (const NBEdge *const from, const NBEdge *const to) const
returns the information whether the given link is a left-mover
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
NBLoadedSUMOTLDef (NBTrafficLightDefinition *def, NBTrafficLightLogic *logic)
Constructor that copies from an existing definition and its computed logic (used by NETEDIT).
NBLoadedSUMOTLDef (const std::string &id, const std::string &programID, SUMOTime offset)
Constructor.
void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
void removeConnection (const NBConnection &conn, bool reconstruct=true)
removes the given connection from the traffic light if recontruct=true, reconstructs the logic and informs the edges for immediate use in NETEDIT
void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)
Replaces a removed edge/lane.
void setID (const std::string &newID)
resets the id
virtual void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void setProgramID (const std::string &programID)
void setTLControllingInformation (const NBEdgeCont &ec) const
Informs edges about being controlled by a tls.
~NBLoadedSUMOTLDef ()
Destructor.
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
Static Public Attributes
static const std::string DefaultProgramID = "0"
Protected Member Functions
bool amInvalid () const
void collectEdges ()
Build the list of participating edges.
void collectLinks ()
Collects the links participating in this traffic light does nothing because the links are already loaded.
unsigned int computeBrakingTime (SUMOReal minDecel) const
Computes the time vehicles may need to brake.
NBTrafficLightLogic * myCompute (const NBEdgeCont &ec, unsigned int brakingTime)
Computes the traffic light logic finally in dependence to the type.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
std::string mySubID
The tls program's subid.
Private Member Functions
void setTLControllingInformation () const
Informs edges about being controlled by a tls.
Private Attributes
std::set< NBNode * > myOriginalNodes
The original nodes for which the loaded logic is valid.
NBTrafficLightLogic * myTLLogic
phases are added directly to myTLLogic which is then returned in myCompute()
Detailed Description
A loaded (complete) traffic light logic.
Definition at line 51 of file NBLoadedSUMOTLDef.h.
Member Enumeration Documentation
enum NBTrafficLightDefinition::TLColor [inherited]
An enumeration of possible tl-signal states.
Enumerator:
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused).
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 81 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBLoadedSUMOTLDef::NBLoadedSUMOTLDef (const std::string & id, const std::string & programID, SUMOTime offset)
Constructor.
Parameters:
[in] id The id of the tls
[in] programID The programID for the computed logic
[in] offset The offset for the computed logic
Definition at line 51 of file NBLoadedSUMOTLDef.cpp.
References myTLLogic, and NBTrafficLightLogic::setOffset().
NBLoadedSUMOTLDef::NBLoadedSUMOTLDef (NBTrafficLightDefinition * def, NBTrafficLightLogic * logic)
Constructor that copies from an existing definition and its computed logic (used by NETEDIT).
Parameters:
[in] def The definition to copy
[in] logic The computed logic of the given def
Definition at line 59 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightDefinition::getControlledLinks(), and NBTrafficLightDefinition::myControlledLinks.
NBLoadedSUMOTLDef::~NBLoadedSUMOTLDef ()
Destructor.
Definition at line 67 of file NBLoadedSUMOTLDef.cpp.
References myTLLogic.
Member Function Documentation
void NBLoadedSUMOTLDef::addConnection (NBEdge * from, NBEdge * to, int fromLane, int toLane, int linkIndex)
Adds a connection and immediately informs the edges.
Definition at line 83 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightDefinition::addNode(), NBEdge::getFromNode(), Named::getID(), NBTrafficLightLogic::getNumLinks(), NBEdge::getToNode(), NBTrafficLightDefinition::myControlledInnerEdges, NBTrafficLightDefinition::myControlledLinks, myOriginalNodes, myTLLogic, NBEdge::setControllingTLInformation(), toString(), and WRITE_ERROR.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIXMLTrafficLightsHandler::addTlConnection().
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges) [inherited]
Adds the given ids into the list of edges not controlled by the tls.
Parameters:
[in] edges The list of edge ids to add the inner edges to
Definition at line 345 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
void NBTrafficLightDefinition::addNode (NBNode * node) [virtual, inherited]
Adds a node to the traffic light logic.
Parameters:
[in] node A further node that shall be controlled by the tls
Definition at line 325 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by addConnection(), NBLoadedTLDef::addToSignalGroup(), and NBTrafficLightDefinition::NBTrafficLightDefinition().
void NBLoadedSUMOTLDef::addPhase (SUMOTime duration, const std::string & state)
Adds a phase to the logic the new phase is inserted at the end of the list of already added phases.
Parameters:
[in] duration The duration of the phase to add in SECONDS!
[in] state The state definition of a tls phase
Definition at line 138 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightLogic::addStep(), and myTLLogic.
Referenced by NIImporter_SUMO::addPhase().
bool NBLoadedSUMOTLDef::amInvalid () const [protected, virtual]
Reimplemented from NBTrafficLightDefinition.
Definition at line 144 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightDefinition::myControlledLinks, NBTrafficLightDefinition::myControlledNodes, and myOriginalNodes.
Referenced by setTLControllingInformation().
void NBTrafficLightDefinition::collectEdges () [protected, inherited]
Build the list of participating edges.
Definition at line 142 of file NBTrafficLightDefinition.cpp.
References Named::getID(), NBTrafficLightDefinition::myControlledInnerEdges, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myEdgesWithin, and NBTrafficLightDefinition::myIncomingEdges.
Referenced by NBTrafficLightDefinition::setParticipantsInformation(), and NBOwnTLDef::setParticipantsInformation().
void NBLoadedSUMOTLDef::collectLinks () [inline, protected, virtual]
Collects the links participating in this traffic light does nothing because the links are already loaded.
Implements NBTrafficLightDefinition.
Definition at line 124 of file NBLoadedSUMOTLDef.h.
NBTrafficLightLogic * NBTrafficLightDefinition::compute (const NBEdgeCont & ec, OptionsCont & oc) [inherited]
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters:
[in] ec The edge container in order to retrieve edge information
[in] oc The options container holding options needed during the building
Returns:
The built logic (may be 0)
Definition at line 98 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), OptionsCont::isSet(), NBTrafficLightDefinition::myCompute(), NBTrafficLightDefinition::myControlledNodes, and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic().
unsigned int NBTrafficLightDefinition::computeBrakingTime (SUMOReal minDecel) const [protected, inherited]
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 127 of file NBTrafficLightDefinition.cpp.
References NBContHelper::maxSpeed(), NBTrafficLightDefinition::myIncomingEdges, and SUMOReal.
Referenced by NBTrafficLightDefinition::compute().
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const [inherited]
Returns the information whether the given flows cross.
Parameters:
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns:
Whether both stream are foes (cross)
Definition at line 302 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBOwnTLDef::computeUnblockedWeightedStreamNumber().
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const [inherited]
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters:
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 225 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::mustBrake(), and NBOwnTLDef::myCompute().
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const [inline, inherited]
returns the controlled links (depends on previous call to collectLinks)
Definition at line 274 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by NBLoadedSUMOTLDef().
const std::vector<NBNode*>& NBTrafficLightDefinition::getControlledNodes () const [inline, inherited]
Definition at line 280 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const [inherited]
Returns the list of incoming edges (must be build first).
Returns:
The edges which are incoming into the tls
Definition at line 351 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myIncomingEdges.
Referenced by NBOwnTLDef::myCompute().
NBTrafficLightLogic* NBLoadedSUMOTLDef::getLogic () [inline]
Returns the internal logic.
Definition at line 115 of file NBLoadedSUMOTLDef.h.
References myTLLogic.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic(), and NIXMLTrafficLightsHandler::myStartElement().
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const [inline, inherited]
Returns the list of controlled nodes.
Returns:
Controlled nodes
Definition at line 154 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledNodes.
const std::string& NBTrafficLightDefinition::getProgramID () const [inline, inherited]
Returns the ProgramID.
Returns:
The ID of the program (subID)
Definition at line 288 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIImporter_SUMO::myEndElement(), and removeConnection().
bool NBTrafficLightDefinition::isLeftMover (const NBEdge *const from, const NBEdge *const to) const [inherited]
returns the information whether the given link is a left-mover
Parameters:
[in] from The connection's start edge
[in] to The connection's end edge
Returns:
Whether the connection is a left-mover
Definition at line 173 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBOwnTLDef::myCompute().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const [inherited]
Returns the information whether the described flow must let any other flow pass.
Parameters:
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 203 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids().
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const [inherited]
Returns the information whether the described flow must let the other flow pass.
Parameters:
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns:
Whether the second flow prohibits the first one
See also:
forbids
Definition at line 215 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids(), NBConnection::getFrom(), and NBConnection::getTo().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const [inherited]
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters:
[in] from The connection's start edge
[in] to The connection's end edge
Returns:
Whether the described connection must brake (has higher priorised foes)
Definition at line 189 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBLoadedTLDef::mustBrake().
NBTrafficLightLogic * NBLoadedSUMOTLDef::myCompute (const NBEdgeCont & ec, unsigned int brakingTime) [protected, virtual]
Computes the traffic light logic finally in dependence to the type.
Parameters:
[in] ec The edge container
[in] brakingTime Duration a vehicle needs for braking in front of the tls
Returns:
The computed logic
Implements NBTrafficLightDefinition.
Definition at line 73 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightLogic::closeBuilding(), myTLLogic, and UNUSED_PARAMETER.
void NBLoadedSUMOTLDef::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) [virtual]
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters:
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
Implements NBTrafficLightDefinition.
Definition at line 130 of file NBLoadedSUMOTLDef.cpp.
void NBLoadedSUMOTLDef::removeConnection (const NBConnection & conn, bool reconstruct = true)
removes the given connection from the traffic light if recontruct=true, reconstructs the logic and informs the edges for immediate use in NETEDIT
Note:
: tlIndex is not necessarily unique. we need the whole connection data here
Definition at line 162 of file NBLoadedSUMOTLDef.cpp.
References NBTrafficLightLogic::addStep(), NBConnection::getFrom(), Named::getID(), NBTrafficLightLogic::getOffset(), NBTrafficLightLogic::getPhases(), NBTrafficLightDefinition::getProgramID(), NBConnection::getTLIndex(), NBTrafficLightDefinition::myControlledLinks, myTLLogic, NBEdge::setControllingTLInformation(), NBTrafficLightLogic::setOffset(), setTLControllingInformation(), and NBConnection::setTLIndex().
Referenced by NIXMLTrafficLightsHandler::removeTlConnection().
void NBTrafficLightDefinition::removeNode (NBNode * node) [virtual, inherited]
Removes the given node from the list of controlled nodes.
Parameters:
[in] node The node that shall not be controlled by the tls any more
Definition at line 335 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBNode::removeTrafficLight().
void NBLoadedSUMOTLDef::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) [virtual]
Replaces a removed edge/lane.
Parameters:
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
Implements NBTrafficLightDefinition.
Definition at line 134 of file NBLoadedSUMOTLDef.cpp.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void NBTrafficLightDefinition::setParticipantsInformation () [virtual, inherited]
Builds the list of participating nodes/edges/links.
Reimplemented in NBOwnTLDef.
Definition at line 134 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::collectEdges(), and NBTrafficLightDefinition::collectLinks().
void NBTrafficLightDefinition::setProgramID (const std::string & programID) [inline, inherited]
Definition at line 293 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NBTrafficLightLogicCont::insert().
void NBLoadedSUMOTLDef::setTLControllingInformation () const [private]
Informs edges about being controlled by a tls.
Definition at line 112 of file NBLoadedSUMOTLDef.cpp.
References amInvalid(), NBConnection::getFrom(), Named::getID(), NBTrafficLightLogic::getNumLinks(), NBConnection::getTLIndex(), NBTrafficLightDefinition::myControlledLinks, myTLLogic, and NBEdge::setControllingTLInformation().
Referenced by removeConnection(), and setTLControllingInformation().
void NBLoadedSUMOTLDef::setTLControllingInformation (const NBEdgeCont & ec) const [virtual]
Informs edges about being controlled by a tls.
Parameters:
[in] ec The container of edges
Implements NBTrafficLightDefinition.
Definition at line 106 of file NBLoadedSUMOTLDef.cpp.
References setTLControllingInformation().
Field Documentation
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" [static, inherited]
Definition at line 75 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges [protected, inherited]
Set of inner edges that shall be controlled, though.
Definition at line 345 of file NBTrafficLightDefinition.h.
Referenced by addConnection(), NBTrafficLightDefinition::addControlledInnerEdges(), and NBTrafficLightDefinition::collectEdges().
NBConnectionVector NBTrafficLightDefinition::myControlledLinks [protected, inherited]
The list of controlled links.
Definition at line 342 of file NBTrafficLightDefinition.h.
Referenced by addConnection(), NBTrafficLightDefinition::amInvalid(), amInvalid(), NBOwnTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), NBTrafficLightDefinition::getControlledLinks(), NBLoadedSUMOTLDef(), removeConnection(), NBOwnTLDef::setTLControllingInformation(), and setTLControllingInformation().
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes [protected, inherited]
The container with participating nodes.
Definition at line 333 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addNode(), amInvalid(), NBTrafficLightDefinition::collectEdges(), NBLoadedTLDef::collectNodes(), NBTrafficLightDefinition::compute(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getControlledNodes(), NBTrafficLightDefinition::getNodes(), NBTrafficLightDefinition::isLeftMover(), NBTrafficLightDefinition::mustBrake(), NBTrafficLightDefinition::NBTrafficLightDefinition(), and NBTrafficLightDefinition::removeNode().
EdgeVector NBTrafficLightDefinition::myEdgesWithin [protected, inherited]
The list of edges within the area controlled by the tls.
Definition at line 339 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectEdges().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
EdgeVector NBTrafficLightDefinition::myIncomingEdges [protected, inherited]
The list of incoming edges.
Definition at line 336 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBLoadedTLDef::collectLinks(), NBTrafficLightDefinition::computeBrakingTime(), and NBTrafficLightDefinition::getIncomingEdges().
std::set<NBNode*> NBLoadedSUMOTLDef::myOriginalNodes [private]
The original nodes for which the loaded logic is valid.
Definition at line 143 of file NBLoadedSUMOTLDef.h.
Referenced by addConnection(), and amInvalid().
std::string NBTrafficLightDefinition::mySubID [protected, inherited]
The tls program's subid.
Definition at line 348 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getProgramID(), and NBTrafficLightDefinition::setProgramID().
NBTrafficLightLogic* NBLoadedSUMOTLDef::myTLLogic [private]
phases are added directly to myTLLogic which is then returned in myCompute()
Definition at line 140 of file NBLoadedSUMOTLDef.h.
Referenced by addConnection(), addPhase(), getLogic(), myCompute(), NBLoadedSUMOTLDef(), removeConnection(), setTLControllingInformation(), and ~NBLoadedSUMOTLDef().
The documentation for this class was generated from the following files:
NBLoadedSUMOTLDef.h
NBLoadedSUMOTLDef.cpp