SUMO - Simulation of Urban MObility: NIVissimNodeDef_Edges::lying_within_match Class Reference
NIVissimNodeDef_Edges::lying_within_match Class Reference
#include <NIVissimNodeDef_Edges.h>
Public Member Functions
lying_within_match (NIVissimNodeParticipatingEdge *e)
bool operator() (NIVissimExtendedEdgePoint *e)
Private Attributes
NIVissimNodeParticipatingEdge * myEdge
Detailed Description
Definition at line 65 of file NIVissimNodeDef_Edges.h.
Constructor & Destructor Documentation
NIVissimNodeDef_Edges::lying_within_match::lying_within_match (NIVissimNodeParticipatingEdge * e) [inline, explicit]
Definition at line 67 of file NIVissimNodeDef_Edges.h.
Member Function Documentation
bool NIVissimNodeDef_Edges::lying_within_match::operator() (NIVissimExtendedEdgePoint * e) [inline]
Definition at line 68 of file NIVissimNodeDef_Edges.h.
References NIVissimExtendedEdgePoint::getEdgeID(), NIVissimNodeParticipatingEdge::getID(), NIVissimExtendedEdgePoint::getPosition(), myEdge, and NIVissimNodeParticipatingEdge::positionLiesWithin().
Field Documentation
NIVissimNodeParticipatingEdge* NIVissimNodeDef_Edges::lying_within_match::myEdge [private]
Definition at line 73 of file NIVissimNodeDef_Edges.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
NIVissimNodeDef_Edges.h