SUMO - Simulation of Urban MObility: MSVehicle::Influencer Class Reference
MSVehicle::Influencer Class Reference
Changes the wished vehicle speed / lanes.
#include <MSVehicle.h>
Public Member Functions
ChangeRequest checkForLaneChanges (SUMOTime currentTime, const MSEdge &currentEdge, unsigned int currentLaneIndex)
double getOriginalSpeed () const
Returns the originally longitudianl speed to use.
Influencer ()
Constructor.
double influenceSpeed (SUMOTime currentTime, double speed, double vSafe, double vMin, double vMax)
Applies stored velocity information on the speed to use.
void setConsiderMaxAcceleration (bool value)
Sets whether the maximum acceleration shall be regarded.
void setConsiderMaxDeceleration (bool value)
Sets whether the maximum deceleration shall be regarded.
void setConsiderSafeVelocity (bool value)
Sets whether the safe velocity shall be regarded.
void setLaneTimeLine (const std::vector< std::pair< SUMOTime, unsigned int > > &laneTimeLine)
Sets a new lane timeline.
void setSpeedTimeLine (const std::vector< std::pair< SUMOTime, double > > &speedTimeLine)
Sets a new velocity timeline.
~Influencer ()
Destructor.
Private Attributes
bool myConsiderMaxAcceleration
Whether the maximum acceleration shall be regarded.
bool myConsiderMaxDeceleration
Whether the maximum deceleration shall be regarded.
bool myConsiderSafeVelocity
Whether the safe velocity shall be regarded.
std::vector< std::pair
< SUMOTime, unsigned int > > myLaneTimeLine
The lane usage time line to apply.
double myOriginalSpeed
The velocity before influence.
bool mySpeedAdaptationStarted
Whether influencing the speed has already started.
std::vector< std::pair
< SUMOTime, double > > mySpeedTimeLine
The velocity time line to apply.
Detailed Description
Changes the wished vehicle speed / lanes.
The class is used for passing velocities or velocity profiles obtained via TraCI to the vehicle.
The adaptation is controlled by the stored time line of speeds/lanes. Additionally, the variables myConsiderSafeVelocity, myConsiderMaxAcceleration, and myConsiderMaxDeceleration control whether the safe velocity, the maximum acceleration, and the maximum deceleration have to be regarded.
Definition at line 688 of file MSVehicle.h.
Constructor & Destructor Documentation
MSVehicle::Influencer::Influencer ()
Constructor.
Definition at line 142 of file MSVehicle.cpp.
MSVehicle::Influencer::~Influencer ()
Destructor.
Definition at line 147 of file MSVehicle.cpp.
Member Function Documentation
MSVehicle::ChangeRequest MSVehicle::Influencer::checkForLaneChanges (SUMOTime currentTime, const MSEdge & currentEdge, unsigned int currentLaneIndex)
Definition at line 198 of file MSVehicle.cpp.
References MSEdge::getLanes(), myLaneTimeLine, MSVehicle::REQUEST_HOLD, MSVehicle::REQUEST_LEFT, MSVehicle::REQUEST_NONE, and MSVehicle::REQUEST_RIGHT.
Referenced by MSVehicle::enterLaneAtLaneChange(), and MSVehicle::enterLaneAtMove().
double MSVehicle::Influencer::getOriginalSpeed () const [inline]
Returns the originally longitudianl speed to use.
Returns:
The speed given before influence
Definition at line 731 of file MSVehicle.h.
References myOriginalSpeed.
Referenced by MSVehicle::getSpeedWithoutTraciInfluence().
double MSVehicle::Influencer::influenceSpeed (SUMOTime currentTime, double speed, double vSafe, double vMin, double vMax)
Applies stored velocity information on the speed to use.
The given speed is assumed to be the non-influenced speed from longitudinal control. It is stored for further usage in "myOriginalSpeed".
Parameters:
[in] currentTime The current simulation time
[in] speed The undisturbed speed
[in] vSafe The safe velocity
[in] vMin The minimum velocity
[in] vMax The maximum simulation time
Returns:
The speed to use
Referenced by MSVehicle::moveChecked().
void MSVehicle::Influencer::setConsiderMaxAcceleration (bool value)
Sets whether the maximum acceleration shall be regarded.
Parameters:
[in] value Whether the maximum acceleration shall be regarded
Definition at line 228 of file MSVehicle.cpp.
References myConsiderMaxAcceleration.
void MSVehicle::Influencer::setConsiderMaxDeceleration (bool value)
Sets whether the maximum deceleration shall be regarded.
Parameters:
[in] value Whether the maximum deceleration shall be regarded
Definition at line 232 of file MSVehicle.cpp.
References myConsiderMaxDeceleration.
void MSVehicle::Influencer::setConsiderSafeVelocity (bool value)
Sets whether the safe velocity shall be regarded.
Parameters:
[in] value Whether the safe velocity shall be regarded
Definition at line 224 of file MSVehicle.cpp.
References myConsiderSafeVelocity.
void MSVehicle::Influencer::setLaneTimeLine (const std::vector< std::pair< SUMOTime, unsigned int > > & laneTimeLine)
Sets a new lane timeline.
Parameters:
[in] laneTimeLine The time line of lanes to use
Definition at line 156 of file MSVehicle.cpp.
References myLaneTimeLine.
void MSVehicle::Influencer::setSpeedTimeLine (const std::vector< std::pair< SUMOTime, double > > & speedTimeLine)
Sets a new velocity timeline.
Parameters:
[in] speedTimeLine The time line of speeds to use
Field Documentation
bool MSVehicle::Influencer::myConsiderMaxAcceleration [private]
Whether the maximum acceleration shall be regarded.
Definition at line 748 of file MSVehicle.h.
Referenced by setConsiderMaxAcceleration().
bool MSVehicle::Influencer::myConsiderMaxDeceleration [private]
Whether the maximum deceleration shall be regarded.
Definition at line 750 of file MSVehicle.h.
Referenced by setConsiderMaxDeceleration().
bool MSVehicle::Influencer::myConsiderSafeVelocity [private]
Whether the safe velocity shall be regarded.
Definition at line 746 of file MSVehicle.h.
Referenced by setConsiderSafeVelocity().
std::vector<std::pair<SUMOTime,unsigned int> > MSVehicle::Influencer::myLaneTimeLine [private]
The lane usage time line to apply.
Definition at line 740 of file MSVehicle.h.
Referenced by checkForLaneChanges(), and setLaneTimeLine().
double MSVehicle::Influencer::myOriginalSpeed [private]
The velocity before influence.
Definition at line 742 of file MSVehicle.h.
Referenced by getOriginalSpeed().
bool MSVehicle::Influencer::mySpeedAdaptationStarted [private]
Whether influencing the speed has already started.
Definition at line 744 of file MSVehicle.h.
std::vector<std::pair<SUMOTime,double> > MSVehicle::Influencer::mySpeedTimeLine [private]
The velocity time line to apply.
Definition at line 738 of file MSVehicle.h.
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp