SUMO - Simulation of Urban MObility: MSDevice_FEV Class Reference
MSDevice_FEV Class Reference
A device which collects Full electric vehicles consumptions.
#include <MSDevice_FEV.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
double computeMaxSpeed (double nextSpeed)
Called on writing tripinfo output.
void generateOutput () const
Called on writing tripinfo output.
SUMOVehicle & getHolder () const
Returns the vehicle that holds this device.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
double getMyCurrChargeRem () const
double getMyCurrDoD () const
double getMyCurrE () const
double getMyCurrSpeed () const
double getMyLastChargeRem () const
double getMyLastDoD () const
double getMyLastSpeed () const
double getMySoh () const
MSDevice_FEV ()
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void setID (const std::string &newID)
resets the id
void setMyCurrChargeRem (double my_curr_charge_rem)
void setMyCurrDoD (double my_curr_DoD)
void setMyCurrE (double my_curr_E)
void setMyCurrSpeed (double my_curr_speed)
void setMyLastChargeRem (double my_last_charge_rem)
void setMyLastDoD (double my_last_DoD)
void setMyLastSpeed (double my_last_speed)
void setMySoh (double my_SOH)
~MSDevice_FEV ()
Destructor.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason)
Checks whether the reminder is activated by a vehicle entering the lane.
virtual bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, Notification reason)
Called if the vehicle leaves the reminder's lane.
virtual bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
Methods called on vehicle movement / state change, overwriting MSDevice
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Computes current emission values and adds them to their sums.
Static Public Member Functions
static void buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice * > &into)
Build devices for the given vehicle, if needed.
static void insertOptions ()
Inserts MSDevice_FEV-options.
Protected Attributes
SUMOVehicle & myHolder
The vehicle that stores the device.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
double computeElectricAuxiliaries ()
MSDevice_FEV (const MSDevice_FEV &)
Invalidated copy constructor.
MSDevice_FEV (SUMOVehicle &holder, const std::string &id)
Constructor.
MSDevice_FEV & operator= (const MSDevice_FEV &)
Invalidated assignment operator.
Private Attributes
Internal storages for pollutant/fuel sum in mg or ml
double my_curr_charge_rem
double my_curr_DoD
double my_curr_E
double my_curr_speed
double my_last_charge_rem
double my_last_DoD
double my_last_speed
double my_SOH
Detailed Description
A device which collects Full electric vehicles consumptions.
Each device collects the vehicular consumption
See also:
MSDevice
Definition at line 61 of file MSDevice_FEV.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSDevice_FEV::~MSDevice_FEV ()
Destructor.
Definition at line 84 of file MSDevice_FEV.cpp.
MSDevice_FEV::MSDevice_FEV ()
Referenced by buildVehicleDevices().
MSDevice_FEV::MSDevice_FEV (SUMOVehicle & holder, const std::string & id) [private]
Constructor.
Parameters:
[in] holder The vehicle that holds this device
[in] id The ID of the device
Definition at line 77 of file MSDevice_FEV.cpp.
MSDevice_FEV::MSDevice_FEV (const MSDevice_FEV &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSDevice_FEV::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice * > & into) [static]
Build devices for the given vehicle, if needed.
The options are read and evaluated whether hbefa-devices shall be built for the given vehicle.
For each seen vehicle, the global vehicle index is increased.
The built device is stored in the given vector.
Parameters:
[in] v The vehicle for which a device may be built
in,filled] into The vector to store the built device in
Definition at line 66 of file MSDevice_FEV.cpp.
References SUMOVehicle::getID(), and MSDevice_FEV().
Referenced by MSBaseVehicle::MSBaseVehicle().
double MSDevice_FEV::computeElectricAuxiliaries () [private]
Added by the HI-Iberia. Calculates the electric power consumption of the vehicle auxiliaries such as: radio, heating, head lights, fog lights and cockpit lights.
Definition at line 306 of file MSDevice_FEV.cpp.
References MSVehicleType::getAuxMask(), MSVehicleType::getCockpitLigthsConsumption(), MSVehicleType::getFrontFogLigthsConsumption(), MSVehicleType::getHeatingAcConsumption(), MSDevice::getHolder(), MSVehicleType::getLightMask(), MSVehicleType::getRadioConsumption(), MSVehicleType::getVehicleHeadligthsConsumption(), and SUMOVehicle::getVehicleType().
Referenced by computeMaxSpeed().
double MSDevice_FEV::computeMaxSpeed (double nextSpeed)
Called on writing tripinfo output.
Parameters:
[in] os The stream to write the information into
Exceptions:
IOError not yet implemented
See also:
MSDevice::tripInfoOutput
Definition at line 215 of file MSDevice_FEV.cpp.
References computeElectricAuxiliaries(), DELTA_T, MSVehicleType::getAirDens(), MSVehicleType::getCapacity(), MSVehicleType::getConstantLosses(), MSVehicleType::getCooperLosses(), MSNet::getCurrentTimeStep(), MSVehicleType::getDragCoefficient(), MSVehicleType::getFrontalArea(), MSVehicleType::getGearRatio(), MSVehicleType::getGearSysEffc(), MSDevice::getHolder(), SUMOVehicle::getID(), MSNet::getInstance(), MSVehicleType::getIronLosses(), MSVehicleType::getMass(), MSVehicleType::getNumCells(), MSVehicleType::getRegenRatio(), MSVehicleType::getRollingRes(), SUMOVehicle::getVehicleType(), MSVehicleType::getWindageLosses(), my_curr_charge_rem, my_curr_DoD, my_curr_speed, my_last_charge_rem, my_last_DoD, my_last_speed, and SUMOReal.
Referenced by MSVehicle::moveChecked().
void MSDevice_FEV::generateOutput () const [virtual]
Called on writing tripinfo output.
The device may write some statistics into the tripinfo output. It is assumed that the written information is a valid xml-snipplet, which will be embedded within the vehicle's information.
The device should use the openTag / closeTag methods of the OutputDevice for correct indentation.
Parameters:
[in] os The stream to write the information into
Exceptions:
IOError not yet implemented
Reimplemented from MSDevice.
Definition at line 330 of file MSDevice_FEV.cpp.
SUMOVehicle& MSDevice::getHolder () const [inline, inherited]
Returns the vehicle that holds this device.
Returns:
The vehicle that holds this device
Definition at line 85 of file MSDevice.h.
References MSDevice::myHolder.
Referenced by computeElectricAuxiliaries(), and computeMaxSpeed().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
double MSDevice_FEV::getMyCurrChargeRem () const
Definition at line 347 of file MSDevice_FEV.cpp.
References my_curr_charge_rem.
Referenced by MSVehicle::writeSyntheticData().
double MSDevice_FEV::getMyCurrDoD () const
Definition at line 351 of file MSDevice_FEV.cpp.
References my_curr_DoD.
Referenced by MSVehicle::writeSyntheticData().
double MSDevice_FEV::getMyCurrE () const
Definition at line 403 of file MSDevice_FEV.cpp.
References my_curr_E.
Referenced by MSVehicle::writeSyntheticData().
double MSDevice_FEV::getMyCurrSpeed () const
Definition at line 355 of file MSDevice_FEV.cpp.
References my_curr_speed.
double MSDevice_FEV::getMyLastChargeRem () const
Definition at line 359 of file MSDevice_FEV.cpp.
References my_last_charge_rem.
Referenced by MSVehicle::moveChecked().
double MSDevice_FEV::getMyLastDoD () const
Definition at line 363 of file MSDevice_FEV.cpp.
References my_last_DoD.
double MSDevice_FEV::getMyLastSpeed () const
Definition at line 367 of file MSDevice_FEV.cpp.
References my_last_speed.
double MSDevice_FEV::getMySoh () const
Definition at line 395 of file MSDevice_FEV.cpp.
References my_SOH.
Referenced by MSVehicle::writeSyntheticData().
void MSDevice_FEV::insertOptions () [static]
Inserts MSDevice_FEV-options.
Definition at line 50 of file MSDevice_FEV.cpp.
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason) [inline, virtual, inherited]
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns:
True if vehicle enters the reminder.
See also:
Notification
Reimplemented in MSDevice_Person, MSDevice_Routing, MSDevice_Tripinfo, MSDevice_Vehroutes, MSE2Collector, MSInductLoop, MSInstantInductLoop, MSMeanData::MeanDataValues, MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Net::MSLaneMeanDataValues, MSRouteProbe, and MSTriggeredRerouter.
Definition at line 128 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual bool MSMoveReminder::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, Notification reason) [inline, virtual, inherited]
Called if the vehicle leaves the reminder's lane.
Informs if vehicle leaves reminder lane (due to lane change, removal from the network, or leaving to the next lane). The default is to do nothing.
Parameters:
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also:
Notification
Returns:
True if the reminder wants to receive further info.
Reimplemented in MSDevice_Person, MSDevice_Tripinfo, MSDevice_Vehroutes, MSE2Collector, MSE3Collector::MSE3EntryReminder, MSInductLoop, MSInstantInductLoop, MSMeanData::MeanDataValues, MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 173 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
virtual bool MSMoveReminder::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [inline, virtual, inherited]
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns:
True if vehicle hasn't passed the reminder completely.
Reimplemented in MSDevice_HBEFA, MSDevice_Person, MSDevice_Tripinfo, MSE2Collector, MSE3Collector::MSE3EntryReminder, MSE3Collector::MSE3LeaveReminder, MSInductLoop, MSInstantInductLoop, and MSMeanData::MeanDataValues.
Definition at line 148 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
bool MSDevice_FEV::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed)
Computes current emission values and adds them to their sums.
The vehicle's current emission values are computed using the current velocity and acceleration.
Parameters:
[in] veh The regarded vehicle
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep.
[in] newSpeed The vehicle's current speed
Returns:
false, if the vehicle is beyond the lane, true otherwise
See also:
MSMoveReminder
MSMoveReminder::notifyMove
HelpersHBEFA
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove().
MSDevice_FEV& MSDevice_FEV::operator= (const MSDevice_FEV &) [private]
Invalidated assignment operator.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void MSDevice_FEV::setMyCurrChargeRem (double my_curr_charge_rem)
Definition at line 371 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyCurrDoD (double my_curr_DoD)
Definition at line 375 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyCurrE (double my_curr_E)
Definition at line 407 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyCurrSpeed (double my_curr_speed)
Definition at line 379 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyLastChargeRem (double my_last_charge_rem)
Definition at line 383 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyLastDoD (double my_last_DoD)
Definition at line 387 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMyLastSpeed (double my_last_speed)
Definition at line 391 of file MSDevice_FEV.cpp.
void MSDevice_FEV::setMySoh (double my_SOH)
Definition at line 399 of file MSDevice_FEV.cpp.
Field Documentation
double MSDevice_FEV::my_curr_charge_rem [private]
Definition at line 144 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyCurrChargeRem().
double MSDevice_FEV::my_curr_DoD [private]
Definition at line 146 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyCurrDoD().
double MSDevice_FEV::my_curr_E [private]
Definition at line 140 of file MSDevice_FEV.h.
Referenced by getMyCurrE().
double MSDevice_FEV::my_curr_speed [private]
Definition at line 142 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyCurrSpeed().
double MSDevice_FEV::my_last_charge_rem [private]
Definition at line 143 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyLastChargeRem().
double MSDevice_FEV::my_last_DoD [private]
Definition at line 145 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyLastDoD().
double MSDevice_FEV::my_last_speed [private]
Definition at line 141 of file MSDevice_FEV.h.
Referenced by computeMaxSpeed(), and getMyLastSpeed().
double MSDevice_FEV::my_SOH [private]
Definition at line 147 of file MSDevice_FEV.h.
Referenced by getMySoh().
SUMOVehicle& MSDevice::myHolder [protected, inherited]
The vehicle that stores the device.
Definition at line 108 of file MSDevice.h.
Referenced by MSDevice_Vehroutes::addRoute(), MSDevice_Vehroutes::generateOutput(), MSDevice_Tripinfo::generateOutput(), MSDevice::getHolder(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Routing::preInsertionReroute(), MSDevice_Routing::wrappedRerouteCommandExecute(), MSDevice_Vehroutes::writeXMLRoute(), and MSDevice_Vehroutes::~MSDevice_Vehroutes().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
The documentation for this class was generated from the following files:
MSDevice_FEV.h
MSDevice_FEV.cpp