SUMO - Simulation of Urban MObility: NIImporter_Vissim::VissimSingleTypeParser Class Reference
NIImporter_Vissim::VissimSingleTypeParser Class Reference
#include <NIImporter_Vissim.h>
Public Member Functions
virtual bool parse (std::istream &from)=0
Parses a single data type. Returns whether no error occured.
VissimSingleTypeParser (NIImporter_Vissim &parent)
Constructor.
virtual ~VissimSingleTypeParser ()
Destructor.
Protected Member Functions
Position getPosition (std::istream &from)
returns the 2d-position saved as next within the stream
std::string myRead (std::istream &from)
reads from the stream and returns the lower case version of the read value
std::string overrideOptionalLabel (std::istream &from, const std::string &tag="")
overrides the optional label definition; returns the next tag as done by readEndSecure
IntVector parseAssignedVehicleTypes (std::istream &from, const std::string &next)
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
std::string readEndSecure (std::istream &from, const std::vector< std::string > &excl)
std::string readEndSecure (std::istream &from, const std::string &excl="")
as myRead, but returns "DATAEND" when the current field has ended
NIVissimExtendedEdgePoint readExtEdgePointDef (std::istream &from)
std::string readName (std::istream &from)
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
void readUntil (std::istream &from, const std::string &name)
Reads from the stream until the keywor occurs.
bool skipOverreading (std::istream &from, const std::string &name="")
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Private Attributes
NIImporter_Vissim & myVissimParent
Detailed Description
Definition at line 86 of file NIImporter_Vissim.h.
Constructor & Destructor Documentation
NIImporter_Vissim::VissimSingleTypeParser::VissimSingleTypeParser (NIImporter_Vissim & parent)
Constructor.
Definition at line 139 of file NIImporter_Vissim.cpp.
NIImporter_Vissim::VissimSingleTypeParser::~VissimSingleTypeParser () [virtual]
Destructor.
Definition at line 143 of file NIImporter_Vissim.cpp.
Member Function Documentation
Position NIImporter_Vissim::VissimSingleTypeParser::getPosition (std::istream & from) [protected]
returns the 2d-position saved as next within the stream
Definition at line 225 of file NIImporter_Vissim.cpp.
References SUMOReal.
Referenced by NIVissimSingleTypeParser_Streckendefinition::parse(), and NIVissimSingleTypeParser_Knotendefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::myRead (std::istream & from) [protected]
reads from the stream and returns the lower case version of the read value
Definition at line 147 of file NIImporter_Vissim.cpp.
References StringUtils::to_lower_case().
Referenced by overrideOptionalLabel(), NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Auswertungsdefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), NIVissimSingleTypeParser_Signalgruppendefinition::parseVAS(), readEndSecure(), readUntil(), and skipOverreading().
std::string NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel (std::istream & from, const std::string & tag = "") [protected]
overrides the optional label definition; returns the next tag as done by readEndSecure
Definition at line 204 of file NIImporter_Vissim.cpp.
References myRead().
Referenced by NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), and NIVissimSingleTypeParser_Knotendefinition::parse().
virtual bool NIImporter_Vissim::VissimSingleTypeParser::parse (std::istream & from) [pure virtual]
Parses a single data type. Returns whether no error occured.
Implemented in NIVissimSingleTypeParser__XKurvedefinition, NIVissimSingleTypeParser__XVerteilungsdefinition, NIVissimSingleTypeParser_Auswertungsdefinition, NIVissimSingleTypeParser_Detektordefinition, NIVissimSingleTypeParser_DynUml, NIVissimSingleTypeParser_Einheitendefinition, NIVissimSingleTypeParser_Emission, NIVissimSingleTypeParser_Fahrtverlaufdateien, NIVissimSingleTypeParser_Fahrverhaltendefinition, NIVissimSingleTypeParser_Fahrzeugklassendefinition, NIVissimSingleTypeParser_Fahrzeugtypdefinition, NIVissimSingleTypeParser_Fensterdefinition, NIVissimSingleTypeParser_Gefahrwarnungsdefinition, NIVissimSingleTypeParser_Gelbverhaltendefinition, NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition, NIVissimSingleTypeParser_Haltestellendefinition, NIVissimSingleTypeParser_Kantensperrung, NIVissimSingleTypeParser_Kennungszeile, NIVissimSingleTypeParser_Knotendefinition, NIVissimSingleTypeParser_Laengenverteilungsdefinition, NIVissimSingleTypeParser_Langsamfahrbereichdefinition, NIVissimSingleTypeParser_Lichtsignalanlagendefinition, NIVissimSingleTypeParser_Liniendefinition, NIVissimSingleTypeParser_Linksverkehr, NIVissimSingleTypeParser_LSAKopplungsdefinition, NIVissimSingleTypeParser_Messungsdefinition, NIVissimSingleTypeParser_Netzobjektdefinition, NIVissimSingleTypeParser_Parkplatzdefinition, NIVissimSingleTypeParser_Querschnittsmessungsdefinition, NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition, NIVissimSingleTypeParser_Rautedefinition, NIVissimSingleTypeParser_Reisezeitmessungsdefinition, NIVissimSingleTypeParser_Richtungsentscheidungsdefinition, NIVissimSingleTypeParser_Richtungspfeildefinition, NIVissimSingleTypeParser_Routenentscheidungsdefinition, NIVissimSingleTypeParser_Signalgeberdefinition, NIVissimSingleTypeParser_Signalgruppendefinition, NIVissimSingleTypeParser_Simdauer, NIVissimSingleTypeParser_SimRate, NIVissimSingleTypeParser_Startuhrzeit, NIVissimSingleTypeParser_Startzufallszahl, NIVissimSingleTypeParser_Stauparameterdefinition, NIVissimSingleTypeParser_Stauzaehlerdefinition, NIVissimSingleTypeParser_Stopschilddefinition, NIVissimSingleTypeParser_Streckendefinition, NIVissimSingleTypeParser_Streckentypdefinition, NIVissimSingleTypeParser_TEAPACDefinition, NIVissimSingleTypeParser_Verbindungsdefinition, NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition, NIVissimSingleTypeParser_Verlustzeitmessungsdefinition, NIVissimSingleTypeParser_VWunschentscheidungsdefinition, NIVissimSingleTypeParser_Zeitenverteilungsdefinition, NIVissimSingleTypeParser_Zeitschrittfaktor, NIVissimSingleTypeParser_Zuflussdefinition, and NIVissimSingleTypeParser_Zusammensetzungsdefinition.
Referenced by NIImporter_Vissim::readContents().
IntVector NIImporter_Vissim::VissimSingleTypeParser::parseAssignedVehicleTypes (std::istream & from, const std::string & next) [protected]
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
Definition at line 234 of file NIImporter_Vissim.cpp.
References readEndSecure().
Referenced by NIVissimSingleTypeParser_Signalgeberdefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::vector< std::string > & excl) [protected]
Definition at line 174 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), myRead(), myVissimParent, and StringUtils::to_lower_case().
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::string & excl = "") [protected]
as myRead, but returns "DATAEND" when the current field has ended
Definition at line 156 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), myRead(), myVissimParent, and StringUtils::to_lower_case().
Referenced by NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Zeitenverteilungsdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Laengenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Kantensperrung::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_DynUml::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Auswertungsdefinition::parse(), parseAssignedVehicleTypes(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePos(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseVAS(), readExtEdgePointDef(), and skipOverreading().
NIVissimExtendedEdgePoint NIImporter_Vissim::VissimSingleTypeParser::readExtEdgePointDef (std::istream & from) [protected]
Definition at line 251 of file NIImporter_Vissim.cpp.
References readEndSecure(), and SUMOReal.
Referenced by NIVissimSingleTypeParser_Verbindungsdefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::readName (std::istream & from) [protected]
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
Definition at line 274 of file NIImporter_Vissim.cpp.
References StringUtils::convertUmlaute().
Referenced by NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Kennungszeile::parse(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), and NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered().
void NIImporter_Vissim::VissimSingleTypeParser::readUntil (std::istream & from, const std::string & name) [protected]
Reads from the stream until the keywor occurs.
Definition at line 290 of file NIImporter_Vissim.cpp.
References myRead().
Referenced by NIVissimSingleTypeParser_Streckentypdefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Fahrverhaltendefinition::parse(), and NIVissimSingleTypeParser_DynUml::parse().
bool NIImporter_Vissim::VissimSingleTypeParser::skipOverreading (std::istream & from, const std::string & name = "") [protected]
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Definition at line 299 of file NIImporter_Vissim.cpp.
References myRead(), and readEndSecure().
Referenced by NIVissimSingleTypeParser_Stauzaehlerdefinition::parse(), NIVissimSingleTypeParser_Richtungsentscheidungsdefinition::parse(), and NIVissimSingleTypeParser_Messungsdefinition::parse().
Field Documentation
NIImporter_Vissim& NIImporter_Vissim::VissimSingleTypeParser::myVissimParent [private]
Definition at line 136 of file NIImporter_Vissim.h.
Referenced by readEndSecure().
The documentation for this class was generated from the following files:
NIImporter_Vissim.h
NIImporter_Vissim.cpp