SUMO - Simulation of Urban MObility: RORDLoader_TripDefs Class Reference
RORDLoader_TripDefs Class Reference
#include <RORDLoader_TripDefs.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endDocument ()
Called when the document has ended.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RORDLoader_TripDefs (RONet &net, SUMOTime begin, SUMOTime end, bool emptyDestinationsAllowed, bool withTaz, const std::string &file="")
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
~RORDLoader_TripDefs ()
Destructor.
inherited from ROAbstractRouteDefLoader
bool ended () const
Returns the information whether no routes are available from this loader anymore.
bool readRoutesAtLeastUntil (SUMOTime time, bool skipping)
Adds routes from the file until the given time is reached.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
inherited from ROAbstractRouteDefLoader
SUMOTime getLastReadTimeStep () const
Returns the time the current (last read) route starts at.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
ROEdge * getEdge (const SUMOSAXAttributes &attrs, const std::string &purpose, SumoXMLAttr which, const std::string &id, bool emptyAllowed)
Parses a named edge frm the attributes.
std::string getVehicleID (const SUMOSAXAttributes &attrs)
Parses the vehicle id.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from ROTypedXMLRoutesLoader
void beginNextRoute ()
Returns Initialises the reading of a further route.
bool nextRouteRead ()
inherited from GenericSAXHandler
void myEndElement (int element)
Called when a closing tag occurs.
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
SUMOTime myBegin
The time for which the first route shall be loaded.
ROEdge * myBeginEdge
The starting edge.
SUMOVTypeParameter * myCurrentVehicleType
The currently parsed vehicle type.
SUMOTime myDepartureTime
const bool myEmptyDestinationsAllowed
Information whether empty destinations are allowed This is a feature used for the handling of explicit routes within the jtrrouter where the destination is not necessary.
SUMOTime myEnd
The time for which the first route shall be loaded.
bool myEnded
Information whether the whole file has been parsed.
ROEdge * myEndEdge
The end edge.
bool myHaveWarnedAboutDeprecatedTripDef
IDSupplier myIdSupplier
generates numerical ids
RONet & myNet
The network to add routes to.
bool myNextRouteRead
The information whether the next route was read.
SUMOVehicleParameter * myParameter
SAX2XMLReader * myParser
The parser used.
XMLPScanToken myToken
Information about the current position within the file.
const bool myWithTaz
Information whether zones (districts) are used as origins / destinations.
Private Member Functions
RORDLoader_TripDefs & operator= (const RORDLoader_TripDefs &src)
Invalidated assignment operator.
RORDLoader_TripDefs (const RORDLoader_TripDefs &src)
Invalidated copy constructor.
Detailed Description
A handler for route definitions which consists of the origin and the destination edge only. Additionally, read vehicles may have information about a certain position to leave from and a certain speed to leave with.
Definition at line 53 of file RORDLoader_TripDefs.h.
Constructor & Destructor Documentation
RORDLoader_TripDefs::RORDLoader_TripDefs (RONet & net, SUMOTime begin, SUMOTime end, bool emptyDestinationsAllowed, bool withTaz, const std::string & file = "")
Constructor.
Definition at line 55 of file RORDLoader_TripDefs.cpp.
RORDLoader_TripDefs::~RORDLoader_TripDefs ()
Destructor.
Definition at line 66 of file RORDLoader_TripDefs.cpp.
RORDLoader_TripDefs::RORDLoader_TripDefs (const RORDLoader_TripDefs & src) [private]
Invalidated copy constructor.
Member Function Documentation
void RORDLoader_TripDefs::beginNextRoute () [protected, virtual]
Returns Initialises the reading of a further route.
Todo:
recheck/refactor
See also:
ROTypedXMLRoutesLoader::beginNextRoute
Implements ROTypedXMLRoutesLoader.
Definition at line 183 of file RORDLoader_TripDefs.cpp.
References myNextRouteRead.
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void ROTypedXMLRoutesLoader::endDocument () [inherited]
Called when the document has ended.
Todo:
Recheck usage of route loaders; it is not very fine to have one that use a parser and other that do not
Definition at line 86 of file ROTypedXMLRoutesLoader.cpp.
References ROTypedXMLRoutesLoader::myEnded.
bool ROTypedXMLRoutesLoader::ended () const [inline, virtual, inherited]
Returns the information whether no routes are available from this loader anymore.
Returns:
Whether the whole input has been processed
Implements ROAbstractRouteDefLoader.
Definition at line 99 of file ROTypedXMLRoutesLoader.h.
References ROTypedXMLRoutesLoader::myEnded.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
ROEdge * RORDLoader_TripDefs::getEdge (const SUMOSAXAttributes & attrs, const std::string & purpose, SumoXMLAttr which, const std::string & id, bool emptyAllowed) [protected]
Parses a named edge frm the attributes.
Definition at line 125 of file RORDLoader_TripDefs.cpp.
References RONet::getEdge(), SUMOSAXAttributes::getStringReporting(), ROAbstractRouteDefLoader::myNet, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_TO_TAZ, UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
SUMOTime RORDLoader_TripDefs::getLastReadTimeStep () const [inline, virtual]
Returns the time the current (last read) route starts at.
Returns:
The least time step that was read by this reader
Implements ROAbstractRouteDefLoader.
Definition at line 71 of file RORDLoader_TripDefs.h.
References myDepartureTime.
std::string RORDLoader_TripDefs::getVehicleID (const SUMOSAXAttributes & attrs) [protected]
Parses the vehicle id.
Definition at line 111 of file RORDLoader_TripDefs.cpp.
References IDSupplier::getNext(), SUMOSAXAttributes::getOptStringReporting(), myIdSupplier, and SUMO_ATTR_ID.
Referenced by myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void RORDLoader_TripDefs::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Reimplemented in RORDGenerator_ODAmounts.
Definition at line 147 of file RORDLoader_TripDefs.cpp.
References RONet::addRouteDef(), RONet::addVehicle(), RONet::addVehicleType(), SUMOVehicleParserHelper::closeVTypeParsing(), SUMOVehicleParameter::color, MsgHandler::getErrorInstance(), RONet::getVehicleTypeSecure(), SUMOVehicleParameter::id, myBeginEdge, myCurrentVehicleType, ROAbstractRouteDefLoader::myEnd, myEndEdge, ROAbstractRouteDefLoader::myNet, myNextRouteRead, myParameter, SUMO_TAG_TRIP, SUMO_TAG_TRIP__DEPRECATED, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE__DEPRECATED, VEHPARS_COLOR_SET, SUMOVehicleParameter::vtypeid, SUMOVehicleParameter::wasSet(), and WRITE_ERROR.
void RORDLoader_TripDefs::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Reimplemented in RORDGenerator_ODAmounts.
Definition at line 70 of file RORDLoader_TripDefs.cpp.
References SUMOVehicleParserHelper::beginVTypeParsing(), getEdge(), SUMOSAXAttributes::getSUMOTimeReporting(), getVehicleID(), SUMOVehicleParameter::id, myBeginEdge, myCurrentVehicleType, myDepartureTime, myEmptyDestinationsAllowed, myEndEdge, myHaveWarnedAboutDeprecatedTripDef, myParameter, myWithTaz, SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVTypeEmbedded(), SUMO_ATTR_DEPART, SUMO_ATTR_FROM, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_TO, SUMO_ATTR_TO_TAZ, SUMO_TAG_TRIP, SUMO_TAG_TRIP__DEPRECATED, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE__DEPRECATED, toString(), WRITE_ERROR, and WRITE_WARNING.
bool RORDLoader_TripDefs::nextRouteRead () [inline, protected, virtual]
Returns the information whether a route was read
Returns:
Whether a further route was read
See also:
ROTypedXMLRoutesLoader::nextRouteRead
Implements ROTypedXMLRoutesLoader.
Definition at line 111 of file RORDLoader_TripDefs.h.
References myNextRouteRead.
RORDLoader_TripDefs& RORDLoader_TripDefs::operator= (const RORDLoader_TripDefs & src) [private]
Invalidated assignment operator.
bool ROTypedXMLRoutesLoader::readRoutesAtLeastUntil (SUMOTime time, bool skipping) [virtual, inherited]
Adds routes from the file until the given time is reached.
Parameters:
[in] time The time until which route definitions shall be loaded
[in] skipping Whether routes shall not be added
Returns:
Whether any errors occured
Exceptions:
ProcessError If a major error occured
See also:
ROAbstractRouteDefLoader::readRoutesAtLeastUntil
Implements ROAbstractRouteDefLoader.
Reimplemented in RORDGenerator_ODAmounts.
Definition at line 73 of file ROTypedXMLRoutesLoader.cpp.
References ROTypedXMLRoutesLoader::beginNextRoute(), ROTypedXMLRoutesLoader::ended(), ROAbstractRouteDefLoader::getLastReadTimeStep(), ROTypedXMLRoutesLoader::myParser, ROTypedXMLRoutesLoader::myToken, ROTypedXMLRoutesLoader::nextRouteRead(), and UNUSED_PARAMETER.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
SUMOTime ROAbstractRouteDefLoader::myBegin [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 109 of file ROAbstractRouteDefLoader.h.
Referenced by RORDLoader_SUMOBase::closeVehicle(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), RORDGenerator_ODAmounts::readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts::RORDGenerator_ODAmounts().
ROEdge* RORDLoader_TripDefs::myBeginEdge [protected]
The starting edge.
Definition at line 138 of file RORDLoader_TripDefs.h.
Referenced by myEndElement(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
SUMOVTypeParameter* RORDLoader_TripDefs::myCurrentVehicleType [protected]
The currently parsed vehicle type.
Definition at line 155 of file RORDLoader_TripDefs.h.
Referenced by myEndElement(), and myStartElement().
SUMOTime RORDLoader_TripDefs::myDepartureTime [protected]
Definition at line 158 of file RORDLoader_TripDefs.h.
Referenced by RORDGenerator_ODAmounts::buildRoutes(), getLastReadTimeStep(), myStartElement(), RORDGenerator_ODAmounts::readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts::RORDGenerator_ODAmounts().
const bool RORDLoader_TripDefs::myEmptyDestinationsAllowed [protected]
Information whether empty destinations are allowed This is a feature used for the handling of explicit routes within the jtrrouter where the destination is not necessary.
Definition at line 146 of file RORDLoader_TripDefs.h.
Referenced by myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
SUMOTime ROAbstractRouteDefLoader::myEnd [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 112 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), and myEndElement().
bool ROTypedXMLRoutesLoader::myEnded [protected, inherited]
Information whether the whole file has been parsed.
Definition at line 141 of file ROTypedXMLRoutesLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), ROTypedXMLRoutesLoader::endDocument(), and ROTypedXMLRoutesLoader::ended().
ROEdge* RORDLoader_TripDefs::myEndEdge [protected]
The end edge.
Definition at line 141 of file RORDLoader_TripDefs.h.
Referenced by myEndElement(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
bool RORDLoader_TripDefs::myHaveWarnedAboutDeprecatedTripDef [protected]
Definition at line 160 of file RORDLoader_TripDefs.h.
Referenced by myStartElement().
IDSupplier RORDLoader_TripDefs::myIdSupplier [protected]
generates numerical ids
Definition at line 135 of file RORDLoader_TripDefs.h.
Referenced by getVehicleID().
RONet& ROAbstractRouteDefLoader::myNet [protected, inherited]
The network to add routes to.
Definition at line 106 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), getEdge(), RORDLoader_SUMOBase::myCharacters(), myEndElement(), RORDLoader_SUMOBase::myEndElement(), and RORDGenerator_ODAmounts::myEndFlowAmountDef().
bool RORDLoader_TripDefs::myNextRouteRead [protected]
The information whether the next route was read.
Definition at line 152 of file RORDLoader_TripDefs.h.
Referenced by beginNextRoute(), myEndElement(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), and nextRouteRead().
SUMOVehicleParameter* RORDLoader_TripDefs::myParameter [protected]
Definition at line 157 of file RORDLoader_TripDefs.h.
Referenced by myEndElement(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), myStartElement(), and RORDGenerator_ODAmounts::parseFlowAmountDef().
SAX2XMLReader* ROTypedXMLRoutesLoader::myParser [protected, inherited]
The parser used.
Definition at line 135 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), and ROTypedXMLRoutesLoader::~ROTypedXMLRoutesLoader().
XMLPScanToken ROTypedXMLRoutesLoader::myToken [protected, inherited]
Information about the current position within the file.
Definition at line 138 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), and ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader().
const bool RORDLoader_TripDefs::myWithTaz [protected]
Information whether zones (districts) are used as origins / destinations.
Definition at line 149 of file RORDLoader_TripDefs.h.
Referenced by myStartElement().
The documentation for this class was generated from the following files:
RORDLoader_TripDefs.h
RORDLoader_TripDefs.cpp