SUMO - Simulation of Urban MObility: NIVissimTL::NIVissimTLSignalGroup Class Reference
NIVissimTL::NIVissimTLSignalGroup Class Reference
#include <NIVissimTL.h>
Public Member Functions
bool addTo (NBLoadedTLDef *node) const
NIVissimTLSignalGroup (int lsaid, int id, const std::string &name, bool isGreenBegin, const DoubleVector &times, SUMOTime tredyellow, SUMOTime tyellow)
~NIVissimTLSignalGroup ()
Static Public Member Functions
static void clearDict ()
static NIVissimTLSignalGroup * dictionary (int lsaid, int id)
static bool dictionary (int lsaid, int id, NIVissimTLSignalGroup *o)
static SGroupDictType getGroupsFor (int tlid)
Private Attributes
bool myFirstIsRed
int myID
int myLSA
std::string myName
DoubleVector myTimes
SUMOTime myTRedYellow
SUMOTime myTYellow
Static Private Attributes
static GroupDictType myDict
Detailed Description
Definition at line 112 of file NIVissimTL.h.
Constructor & Destructor Documentation
NIVissimTL::NIVissimTLSignalGroup::NIVissimTLSignalGroup (int lsaid, int id, const std::string & name, bool isGreenBegin, const DoubleVector & times, SUMOTime tredyellow, SUMOTime tyellow)
Definition at line 215 of file NIVissimTL.cpp.
NIVissimTL::NIVissimTLSignalGroup::~NIVissimTLSignalGroup ()
Definition at line 225 of file NIVissimTL.cpp.
Member Function Documentation
bool NIVissimTL::NIVissimTLSignalGroup::addTo (NBLoadedTLDef * node) const
Definition at line 288 of file NIVissimTL.cpp.
References NBLoadedTLDef::addSignalGroup(), NBLoadedTLDef::addSignalGroupPhaseBegin(), myFirstIsRed, myID, myTimes, myTRedYellow, myTYellow, NBLoadedTLDef::setSignalYellowTimes(), NBTrafficLightDefinition::TLCOLOR_GREEN, and NBTrafficLightDefinition::TLCOLOR_RED.
void NIVissimTL::NIVissimTLSignalGroup::clearDict () [static]
Definition at line 267 of file NIVissimTL.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
NIVissimTL::NIVissimTLSignalGroup * NIVissimTL::NIVissimTLSignalGroup::dictionary (int lsaid, int id) [static]
Definition at line 254 of file NIVissimTL.cpp.
References myDict.
bool NIVissimTL::NIVissimTLSignalGroup::dictionary (int lsaid, int id, NIVissimTL::NIVissimTLSignalGroup * o) [static]
Definition at line 229 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimSingleTypeParser_Signalgruppendefinition::parseFixedTime().
NIVissimTL::SGroupDictType NIVissimTL::NIVissimTLSignalGroup::getGroupsFor (int tlid) [static]
Definition at line 278 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimTL::dict_SetSignals().
Field Documentation
NIVissimTL::GroupDictType NIVissimTL::NIVissimTLSignalGroup::myDict [static, private]
Definition at line 132 of file NIVissimTL.h.
Referenced by clearDict(), dictionary(), and getGroupsFor().
bool NIVissimTL::NIVissimTLSignalGroup::myFirstIsRed [private]
Definition at line 130 of file NIVissimTL.h.
Referenced by addTo().
int NIVissimTL::NIVissimTLSignalGroup::myID [private]
Definition at line 127 of file NIVissimTL.h.
Referenced by addTo().
int NIVissimTL::NIVissimTLSignalGroup::myLSA [private]
Definition at line 126 of file NIVissimTL.h.
std::string NIVissimTL::NIVissimTLSignalGroup::myName [private]
Definition at line 128 of file NIVissimTL.h.
DoubleVector NIVissimTL::NIVissimTLSignalGroup::myTimes [private]
Definition at line 129 of file NIVissimTL.h.
Referenced by addTo().
SUMOTime NIVissimTL::NIVissimTLSignalGroup::myTRedYellow [private]
Definition at line 131 of file NIVissimTL.h.
Referenced by addTo().
SUMOTime NIVissimTL::NIVissimTLSignalGroup::myTYellow [private]
Definition at line 131 of file NIVissimTL.h.
Referenced by addTo().
The documentation for this class was generated from the following files:
NIVissimTL.h
NIVissimTL.cpp