SUMO - Simulation of Urban MObility: NIVissimAbstractEdge Class Reference
NIVissimAbstractEdge Class Reference
#include <NIVissimAbstractEdge.h>
Public Member Functions
void addDisturbance (int disturbance)
virtual void buildGeom ()=0
SUMOReal crossesAtPoint (const Position &p1, const Position &p2) const
bool crossesEdge (NIVissimAbstractEdge *c) const
Position crossesEdgeAtPoint (NIVissimAbstractEdge *c) const
const IntVector & getDisturbances () const
const PositionVector & getGeometry () const
Position getGeomPosition (SUMOReal pos) const
int getID () const
bool hasNodeCluster () const
NIVissimAbstractEdge (int id, const PositionVector &geom)
bool overlapsWith (const AbstractPoly &p, SUMOReal offset=0.0) const
virtual void setNodeCluster (int nodeid)=0
void splitAssigning ()
virtual ~NIVissimAbstractEdge ()
Static Public Member Functions
static void clearDict ()
static NIVissimAbstractEdge * dictionary (int id)
static bool dictionary (int id, NIVissimAbstractEdge *e)
static IntVector getWithin (const AbstractPoly &p, SUMOReal offset=0.0)
static void splitAndAssignToNodes ()
Protected Attributes
IntVector myDisturbances
PositionVector myGeom
int myID
int myNode
Private Types
typedef std::map< int,
NIVissimAbstractEdge * > DictType
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 45 of file NIVissimAbstractEdge.h.
Member Typedef Documentation
typedef std::map<int, NIVissimAbstractEdge*> NIVissimAbstractEdge::DictType [private]
Reimplemented in NIVissimConnection, and NIVissimEdge.
Definition at line 82 of file NIVissimAbstractEdge.h.
Constructor & Destructor Documentation
NIVissimAbstractEdge::NIVissimAbstractEdge (int id, const PositionVector & geom)
Definition at line 51 of file NIVissimAbstractEdge.cpp.
References dictionary(), PositionVector::getCont(), myGeom, PositionVector::push_back_noDoublePos(), toString(), NILoader::transformCoordinates(), and WRITE_WARNING.
NIVissimAbstractEdge::~NIVissimAbstractEdge () [virtual]
Definition at line 69 of file NIVissimAbstractEdge.cpp.
Member Function Documentation
void NIVissimAbstractEdge::addDisturbance (int disturbance)
Definition at line 196 of file NIVissimAbstractEdge.cpp.
References myDisturbances.
virtual void NIVissimAbstractEdge::buildGeom () [pure virtual]
Implemented in NIVissimConnection, and NIVissimEdge.
Referenced by NIVissimNodeCluster::buildNBNode().
void NIVissimAbstractEdge::clearDict () [static]
Definition at line 181 of file NIVissimAbstractEdge.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
SUMOReal NIVissimAbstractEdge::crossesAtPoint (const Position & p1, const Position & p2) const
Definition at line 139 of file NIVissimAbstractEdge.cpp.
References PositionVector::getBegin(), PositionVector::getEnd(), GeomHelper::intersection_position(), myGeom, and GeomHelper::nearest_position_on_line_to_point2D().
bool NIVissimAbstractEdge::crossesEdge (NIVissimAbstractEdge * c) const
Definition at line 127 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersects(), and myGeom.
Referenced by NIVissimNodeCluster::buildNBNode().
Position NIVissimAbstractEdge::crossesEdgeAtPoint (NIVissimAbstractEdge * c) const
Definition at line 133 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersectsAtPoint(), and myGeom.
Referenced by NIVissimDisturbance::addToNode(), and NIVissimNodeCluster::buildNBNode().
NIVissimAbstractEdge * NIVissimAbstractEdge::dictionary (int id) [static]
Reimplemented in NIVissimConnection, and NIVissimEdge.
Definition at line 84 of file NIVissimAbstractEdge.cpp.
References myDict.
bool NIVissimAbstractEdge::dictionary (int id, NIVissimAbstractEdge * e) [static]
Definition at line 73 of file NIVissimAbstractEdge.cpp.
References myDict.
Referenced by NIVissimDisturbance::computeBounding(), NIVissimExtendedEdgePoint::getGeomPosition(), and NIVissimAbstractEdge().
const IntVector & NIVissimAbstractEdge::getDisturbances () const
Definition at line 202 of file NIVissimAbstractEdge.cpp.
References myDisturbances.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
const PositionVector & NIVissimAbstractEdge::getGeometry () const
Definition at line 190 of file NIVissimAbstractEdge.cpp.
References myGeom.
Referenced by NIVissimEdge::dict_checkEdges2Join(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::same_direction_sorter::operator()(), and NIVissimConnectionCluster::recomputeBoundary().
Position NIVissimAbstractEdge::getGeomPosition (SUMOReal pos) const
Definition at line 95 of file NIVissimAbstractEdge.cpp.
References GeomHelper::extrapolate_second(), PositionVector::length(), myGeom, PositionVector::pop_back(), PositionVector::positionAtLengthPosition(), PositionVector::push_back(), and SUMOReal.
Referenced by NIVissimDistrictConnection::geomPosition().
int NIVissimAbstractEdge::getID () const
Definition at line 176 of file NIVissimAbstractEdge.cpp.
References myID.
Referenced by NIVissimDisturbance::addToNode(), NIVissimConnection::buildEdgeConnections(), NIVissimEdge::dict_checkEdges2Join(), NIVissimEdge::getConnectionTo(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), and NIVissimConnectionCluster::removeConnections().
IntVector NIVissimAbstractEdge::getWithin (const AbstractPoly & p, SUMOReal offset = 0.0) [static]
Definition at line 151 of file NIVissimAbstractEdge.cpp.
References myDict, myID, and overlapsWith().
Referenced by NIVissimNodeDef_Poly::searchAndSetConnections().
bool NIVissimAbstractEdge::hasNodeCluster () const
Definition at line 170 of file NIVissimAbstractEdge.cpp.
References myNode.
bool NIVissimAbstractEdge::overlapsWith (const AbstractPoly & p, SUMOReal offset = 0.0) const
Definition at line 164 of file NIVissimAbstractEdge.cpp.
References myGeom, and PositionVector::overlapsWith().
Referenced by getWithin().
virtual void NIVissimAbstractEdge::setNodeCluster (int nodeid) [pure virtual]
Implemented in NIVissimConnection, and NIVissimEdge.
void NIVissimAbstractEdge::splitAndAssignToNodes () [static]
Definition at line 112 of file NIVissimAbstractEdge.cpp.
References myDict, and splitAssigning().
void NIVissimAbstractEdge::splitAssigning ()
Definition at line 120 of file NIVissimAbstractEdge.cpp.
Referenced by splitAndAssignToNodes().
Field Documentation
NIVissimAbstractEdge::DictType NIVissimAbstractEdge::myDict [static, private]
Reimplemented in NIVissimConnection, and NIVissimEdge.
Definition at line 83 of file NIVissimAbstractEdge.h.
Referenced by clearDict(), dictionary(), getWithin(), and splitAndAssignToNodes().
IntVector NIVissimAbstractEdge::myDisturbances [protected]
Definition at line 78 of file NIVissimAbstractEdge.h.
Referenced by addDisturbance(), and getDisturbances().
PositionVector NIVissimAbstractEdge::myGeom [protected]
Definition at line 77 of file NIVissimAbstractEdge.h.
Referenced by NIVissimConnection::buildGeom(), NIVissimEdge::buildNBEdge(), crossesAtPoint(), crossesEdge(), crossesEdgeAtPoint(), NIVissimEdge::getBegin2D(), NIVissimEdge::getEnd2D(), NIVissimEdge::getFromNode(), getGeometry(), getGeomPosition(), NIVissimEdge::getLength(), NIVissimEdge::getToNode(), NIVissimAbstractEdge(), overlapsWith(), and NIVissimEdge::resolveSameNode().
int NIVissimAbstractEdge::myID [protected]
Definition at line 76 of file NIVissimAbstractEdge.h.
Referenced by NIVissimEdge::buildNBEdge(), NIVissimEdge::getFromNode(), getID(), NIVissimEdge::getToNode(), getWithin(), NIVissimEdge::NIVissimEdge(), NIVissimEdge::resolveSameNode(), and NIVissimEdge::setDistrictSpeed().
int NIVissimAbstractEdge::myNode [protected]
Definition at line 79 of file NIVissimAbstractEdge.h.
Referenced by hasNodeCluster(), NIVissimEdge::setNodeCluster(), and NIVissimConnection::setNodeCluster().
The documentation for this class was generated from the following files:
NIVissimAbstractEdge.h
NIVissimAbstractEdge.cpp