SUMO - Simulation of Urban MObility: RORouteDef_Complete Class Reference
RORouteDef_Complete Class Reference
A complete route description containing all edges the driver will pass.
#include <RORouteDef_Complete.h>
Public Member Functions
void addAlternative (SUMOAbstractRouter< ROEdge, ROVehicle > &router, const ROVehicle *const, RORoute *current, SUMOTime begin)
Adds an route alternative (see further comments).
RORoute * buildCurrentRoute (SUMOAbstractRouter< ROEdge, ROVehicle > &router, SUMOTime begin, const ROVehicle &veh) const
Builds the route.
RORouteDef * copy (const std::string &id) const
Returns a copy of the route definition.
const RGBColor * getColor () const
Returns the color of the route.
const std::string & getID () const
Returns the id.
bool isSaved () const
Returns the information whether this item was already saved.
void markSaved ()
Marks the item as saved.
RORouteDef_Complete (const std::string &id, const RGBColor *const color, const std::vector< const ROEdge * > &edges, bool tryRepair)
Constructor.
void setID (const std::string &newID)
resets the id
virtual OutputDevice & writeXMLDefinition (SUMOAbstractRouter< ROEdge, ROVehicle > &router, OutputDevice &dev, const ROVehicle *const veh, bool asAlternatives, bool withExitTimes) const
Saves the built route / route alternatives.
virtual ~RORouteDef_Complete ()
Destructor.
Protected Member Functions
const RGBColor * copyColorIfGiven () const
Protected Attributes
const RGBColor *const myColor
The color the route shall have.
std::vector< const ROEdge * > myEdges
The list of edges the driver passes.
std::string myID
The name of the object.
SUMOTime myStartTime
The begin of the route.
bool myTryRepair
Private Member Functions
RORouteDef_Complete & operator= (const RORouteDef_Complete &src)
Invalidated assignment operator.
RORouteDef_Complete (const RORouteDef_Complete &src)
Invalidated copy constructor.
Detailed Description
A complete route description containing all edges the driver will pass.
Definition at line 55 of file RORouteDef_Complete.h.
Constructor & Destructor Documentation
RORouteDef_Complete::RORouteDef_Complete (const std::string & id, const RGBColor *const color, const std::vector< const ROEdge * > & edges, bool tryRepair)
Constructor.
Definition at line 55 of file RORouteDef_Complete.cpp.
Referenced by copy().
RORouteDef_Complete::~RORouteDef_Complete () [virtual]
Destructor.
Definition at line 63 of file RORouteDef_Complete.cpp.
RORouteDef_Complete::RORouteDef_Complete (const RORouteDef_Complete & src) [private]
Invalidated copy constructor.
Member Function Documentation
void RORouteDef_Complete::addAlternative (SUMOAbstractRouter< ROEdge, ROVehicle > & router, const ROVehicle * const , RORoute * current, SUMOTime begin) [virtual]
Adds an route alternative (see further comments).
Here, as in most cases, the alternative is the route that was build as last and will stay the only route known
Implements RORouteDef.
Definition at line 104 of file RORouteDef_Complete.cpp.
References RORoute::getEdgeVector(), myEdges, and myStartTime.
RORoute * RORouteDef_Complete::buildCurrentRoute (SUMOAbstractRouter< ROEdge, ROVehicle > & router, SUMOTime begin, const ROVehicle & veh) const [virtual]
Builds the route.
Implements RORouteDef.
Definition at line 67 of file RORouteDef_Complete.cpp.
References SUMOAbstractRouter< E, V >::compute(), copy(), RORouteDef::copyColorIfGiven(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), Named::getID(), ROVehicle::getID(), OptionsCont::getOptions(), MsgHandler::getWarningInstance(), MsgHandler::inform(), myEdges, Named::myID, myTryRepair, SUMOAbstractRouter< E, V >::recomputeCosts(), SUMOReal, and WRITE_WARNING.
RORouteDef * RORouteDef_Complete::copy (const std::string & id) const [virtual]
Returns a copy of the route definition.
Implements RORouteDef.
Definition at line 113 of file RORouteDef_Complete.cpp.
References RORouteDef::copyColorIfGiven(), myEdges, myTryRepair, and RORouteDef_Complete().
Referenced by buildCurrentRoute().
const RGBColor * RORouteDef::copyColorIfGiven () const [protected, inherited]
Definition at line 65 of file RORouteDef.cpp.
References RORouteDef::myColor.
Referenced by RORouteDef_OrigDest::buildCurrentRoute(), buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), RORouteDef_OrigDest::copy(), and copy().
const RGBColor* RORouteDef::getColor () const [inline, inherited]
Returns the color of the route.
Definition at line 94 of file RORouteDef.h.
References RORouteDef::myColor.
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
bool ReferencedItem::isSaved () const [inline, inherited]
Returns the information whether this item was already saved.
Returns:
Whether this item was saved
Definition at line 59 of file ReferencedItem.h.
References ReferencedItem::myWasSaved.
Referenced by RONet::computeRoute(), and ROVehicle::saveAllAsXML().
void ReferencedItem::markSaved () [inline, inherited]
Marks the item as saved.
Definition at line 66 of file ReferencedItem.h.
References ReferencedItem::myWasSaved.
RORouteDef_Complete& RORouteDef_Complete::operator= (const RORouteDef_Complete & src) [private]
Invalidated assignment operator.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
OutputDevice & RORouteDef_Complete::writeXMLDefinition (SUMOAbstractRouter< ROEdge, ROVehicle > & router, OutputDevice & dev, const ROVehicle *const veh, bool asAlternatives, bool withExitTimes) const [virtual]
Saves the built route / route alternatives.
Writes the route into the given stream.
Parameters:
[in] dev The device to write the route into
[in] asAlternatives Whether the route shall be saved as route alternatives
Returns:
The same device for further usage
Implements RORouteDef.
Definition at line 119 of file RORouteDef_Complete.cpp.
References OutputDevice::closeTag(), ROVehicle::getDepartureTime(), RORouteDef::myColor, myEdges, OutputDevice::openTag(), SUMOAbstractRouter< E, V >::recomputeCosts(), STEPS2TIME, and SUMOReal.
Field Documentation
const RGBColor* const RORouteDef::myColor [protected, inherited]
The color the route shall have.
Definition at line 116 of file RORouteDef.h.
Referenced by RORouteDef::copyColorIfGiven(), RORouteDef::getColor(), writeXMLDefinition(), RORouteDef_Alternatives::writeXMLDefinition(), and RORouteDef::~RORouteDef().
std::vector<const ROEdge*> RORouteDef_Complete::myEdges [mutable, protected]
The list of edges the driver passes.
Definition at line 85 of file RORouteDef_Complete.h.
Referenced by addAlternative(), buildCurrentRoute(), copy(), and writeXMLDefinition().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
SUMOTime RORouteDef_Complete::myStartTime [protected]
The begin of the route.
Definition at line 88 of file RORouteDef_Complete.h.
Referenced by addAlternative().
bool RORouteDef_Complete::myTryRepair [protected]
Definition at line 90 of file RORouteDef_Complete.h.
Referenced by buildCurrentRoute(), and copy().
The documentation for this class was generated from the following files:
RORouteDef_Complete.h
RORouteDef_Complete.cpp