SUMO - Simulation of Urban MObility: MSNet::EdgeWeightsProxi Class Reference
MSNet::EdgeWeightsProxi Class Reference
A proxi for edge weights known by a vehicle/known globally.
#include <MSNet.h>
Public Member Functions
EdgeWeightsProxi (const MSEdgeWeightsStorage &vehKnowledge, const MSEdgeWeightsStorage &netKnowledge)
Constructor.
SUMOReal getEffort (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) const
Returns the effort to pass an edge.
SUMOReal getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) const
Returns the travel time to pass an edge.
~EdgeWeightsProxi ()
Destructor.
Private Member Functions
EdgeWeightsProxi & operator= (const EdgeWeightsProxi &)
Private Attributes
const MSEdgeWeightsStorage & myNetKnowledge
The global knownledge.
const MSEdgeWeightsStorage & myVehicleKnowledge
The vehicle's knownledge.
Detailed Description
A proxi for edge weights known by a vehicle/known globally.
Both getter methods try to return the vehicle's knowledge about the edge/time, first. If not existing,they try to retrieve it from the global knowledge. If not existing, the travel time retrieval method returns the edges' length divided by the maximum speed (information from the first lane is used). The default value for the effort is 0.
See also:
MSEdgeWeightsStorage
Definition at line 488 of file MSNet.h.
Constructor & Destructor Documentation
MSNet::EdgeWeightsProxi::EdgeWeightsProxi (const MSEdgeWeightsStorage & vehKnowledge, const MSEdgeWeightsStorage & netKnowledge) [inline]
Constructor.
Parameters:
[in] vehKnowledge The vehicle's edge weights knowledge
[in] netKnowledge The global edge weights knowledge
Definition at line 494 of file MSNet.h.
MSNet::EdgeWeightsProxi::~EdgeWeightsProxi () [inline]
Destructor.
Definition at line 500 of file MSNet.h.
Member Function Documentation
SUMOReal MSNet::EdgeWeightsProxi::getEffort (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) const
Returns the effort to pass an edge.
Parameters:
[in] e The edge for which the effort to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the effort shall be returned [s]
Returns:
The effort (abstract) for an edge
See also:
DijkstraRouterTT_ByProxi
Definition at line 113 of file MSNet.cpp.
References myNetKnowledge, myVehicleKnowledge, MSEdgeWeightsStorage::retrieveExistingEffort(), and SUMOReal.
Referenced by TraCIServerAPI_Vehicle::processSet().
SUMOReal MSNet::EdgeWeightsProxi::getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, SUMOReal t) const
Returns the travel time to pass an edge.
Parameters:
[in] e The edge for which the travel time to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the travel time shall be returned [s]
Returns:
The travel time for an edge
See also:
DijkstraRouterTT_ByProxi
Definition at line 128 of file MSNet.cpp.
References MSEdge::getLanes(), MSLane::getLength(), MSLane::getMaxSpeed(), myNetKnowledge, myVehicleKnowledge, MSEdgeWeightsStorage::retrieveExistingTravelTime(), and SUMOReal.
Referenced by MSTriggeredRerouter::notifyEnter(), and TraCIServerAPI_Vehicle::processSet().
EdgeWeightsProxi& MSNet::EdgeWeightsProxi::operator= (const EdgeWeightsProxi &) [private]
Field Documentation
const MSEdgeWeightsStorage& MSNet::EdgeWeightsProxi::myNetKnowledge [private]
The global knownledge.
Definition at line 530 of file MSNet.h.
Referenced by getEffort(), and getTravelTime().
const MSEdgeWeightsStorage& MSNet::EdgeWeightsProxi::myVehicleKnowledge [private]
The vehicle's knownledge.
Definition at line 527 of file MSNet.h.
Referenced by getEffort(), and getTravelTime().
The documentation for this class was generated from the following files:
MSNet.h
MSNet.cpp