SUMO - Simulation of Urban MObility: MSDetectorControl Class Reference
MSDetectorControl Class Reference
Detectors container; responsible for string and output generation.
#include <MSDetectorControl.h>
Data Structures
struct detectorEquals
Returns true if detectors are equal.
Public Member Functions
void add (MSMeanData *mn, OutputDevice &device, SUMOTime frequency, SUMOTime begin)
Adds a mean data object.
void add (SumoXMLTag type, MSDetectorFileOutput *d)
Adds only the detector into the containers.
void add (SumoXMLTag type, MSDetectorFileOutput *d, OutputDevice &device, int splInterval, SUMOTime begin=-1)
Adds a detector/output combination into the containers.
void addDetectorAndInterval (MSDetectorFileOutput *det, OutputDevice *device, SUMOTime interval, SUMOTime begin=-1)
Adds one of the detectors as a new MSDetectorFileOutput.
void close (SUMOTime step)
Closes the detector outputs.
const NamedObjectCont
< MSDetectorFileOutput * > & getTypedDetectors (SumoXMLTag type) const
Returns the list of detectors of the given type.
MSDetectorControl ()
Constructor.
void updateDetectors (const SUMOTime step)
Computes detector values.
void writeOutput (SUMOTime step, bool closing)
Writes the output to be generated within the given time step.
~MSDetectorControl ()
Destructor.
Protected Types
Structures needed for assigning detectors to intervals
typedef std::pair
< MSDetectorFileOutput
*, OutputDevice * > DetectorFilePair
A pair of a Detector with it's associated file-stream.
typedef std::vector
< DetectorFilePair > DetectorFileVec
Container holding DetectorFilePair (with the same interval).
typedef std::map< IntervalsKey,
DetectorFileVec > Intervals
Association of intervals to DetectorFilePair containers.
typedef std::pair< SUMOTime,
SUMOTime > IntervalsKey
Definition of the interval key.
Protected Attributes
std::map< SumoXMLTag,
NamedObjectCont
< MSDetectorFileOutput * > > myDetectors
The detectors map, first by detector type, then using NamedObjectCont (.
NamedObjectCont
< MSDetectorFileOutput * > myEmptyContainer
An empty container to return in getTypedDetectors() if no detectors of the asked type exist.
Intervals myIntervals
Map that hold DetectorFileVec for given intervals.
std::map< IntervalsKey, SUMOTime > myLastCalls
The map that holds the last call for each sample interval.
std::vector< MSMeanData * > myMeanData
List of harmonoise detectors.
Private Member Functions
MSDetectorControl (const MSDetectorControl &)
Invalidated copy constructor.
MSDetectorControl & operator= (const MSDetectorControl &)
Invalidated assignment operator.
Friends
class GUINet
Detailed Description
Detectors container; responsible for string and output generation.
Definition at line 65 of file MSDetectorControl.h.
Member Typedef Documentation
typedef std::pair< MSDetectorFileOutput*, OutputDevice* > MSDetectorControl::DetectorFilePair [protected]
A pair of a Detector with it's associated file-stream.
Definition at line 196 of file MSDetectorControl.h.
typedef std::vector< DetectorFilePair > MSDetectorControl::DetectorFileVec [protected]
Container holding DetectorFilePair (with the same interval).
Definition at line 199 of file MSDetectorControl.h.
typedef std::map< IntervalsKey, DetectorFileVec > MSDetectorControl::Intervals [protected]
Association of intervals to DetectorFilePair containers.
Definition at line 205 of file MSDetectorControl.h.
typedef std::pair<SUMOTime, SUMOTime> MSDetectorControl::IntervalsKey [protected]
Definition of the interval key.
Definition at line 202 of file MSDetectorControl.h.
Constructor & Destructor Documentation
MSDetectorControl::MSDetectorControl ()
Constructor.
Definition at line 55 of file MSDetectorControl.cpp.
MSDetectorControl::~MSDetectorControl ()
Destructor.
Deletes all stored detectors.
Definition at line 59 of file MSDetectorControl.cpp.
References myDetectors, and myMeanData.
MSDetectorControl::MSDetectorControl (const MSDetectorControl &) [private]
Invalidated copy constructor.
Member Function Documentation
void MSDetectorControl::add (MSMeanData * mn, OutputDevice & device, SUMOTime frequency, SUMOTime begin)
Adds a mean data object.
The detector is pushed into the internal list.
Please note, that the detector control gets responsible for the detector.
Parameters:
[in] mn The mean data to add
[in] device The output device to use
[in] frequency The frequency for output generation
[in] begin The begin of the first interval
Definition at line 108 of file MSDetectorControl.cpp.
References addDetectorAndInterval(), OptionsCont::getOptions(), MSMeanData::init(), myMeanData, and string2time().
void MSDetectorControl::add (SumoXMLTag type, MSDetectorFileOutput * d)
Adds only the detector into the containers.
The detector is tried to be added into "myDetectors". If the detector is already known (the id was already used for a similar detector), a ProcessError is thrown.
Please note, that the detector control gets responsible for the detector.
Parameters:
[in] type The type of the detector
[in] d The detector to add
Exceptions:
ProcessError If the detector is already known
Definition at line 94 of file MSDetectorControl.cpp.
References NamedObjectCont< T >::add(), Named::getID(), myDetectors, and toString().
void MSDetectorControl::add (SumoXMLTag type, MSDetectorFileOutput * d, OutputDevice & device, int splInterval, SUMOTime begin = -1)
Adds a detector/output combination into the containers.
The detector is tried to be added into "myDetectors". If the detector is already known (the id was already used for a similar detector), a ProcessError is thrown.
Otherwise, the Detector2File-mechanism is instantiated for the detector.
Please note, that the detector control gets responsible for the detector.
Parameters:
[in] type The type of the detector
[in] d The detector to add
[in] device The device the detector uses
[in] splInterval The sample interval of the detector
Exceptions:
ProcessError If the detector is already known
Definition at line 79 of file MSDetectorControl.cpp.
References NamedObjectCont< T >::add(), addDetectorAndInterval(), Named::getID(), myDetectors, and toString().
Referenced by NLDetectorBuilder::createEdgeLaneMeanData(), and NLDetectorBuilder::endE3Detector().
void MSDetectorControl::addDetectorAndInterval (MSDetectorFileOutput * det, OutputDevice * device, SUMOTime interval, SUMOTime begin = -1)
Adds one of the detectors as a new MSDetectorFileOutput.
Parameters:
[in] det The generator to add
[in] device The device to use
[in] interval The sample interval to use
[in] begin The start of the first sample interval to use
Definition at line 160 of file MSDetectorControl.cpp.
References OptionsCont::getOptions(), myIntervals, myLastCalls, string2time(), WRITE_WARNING, and MSDetectorFileOutput::writeXMLDetectorProlog().
Referenced by add().
void MSDetectorControl::close (SUMOTime step)
Closes the detector outputs.
Goes through the intervals to write and writes the last step using the current simulation time as end.
Parameters:
[in] step The time step (the simulation has ended at)
Definition at line 70 of file MSDetectorControl.cpp.
References myIntervals, and writeOutput().
Referenced by MSNet::closeSimulation().
const NamedObjectCont< MSDetectorFileOutput * > & MSDetectorControl::getTypedDetectors (SumoXMLTag type) const
Returns the list of detectors of the given type.
Parameters:
[in] type The type of detectors to be retrieved
Returns:
The container of detectors
Definition at line 119 of file MSDetectorControl.cpp.
References myDetectors, and myEmptyContainer.
Referenced by GUINet::initGUIStructures(), TraCIServerAPI_MeMeDetector::processGet(), TraCIServerAPI_InductionLoop::processGet(), and updateDetectors().
MSDetectorControl& MSDetectorControl::operator= (const MSDetectorControl &) [private]
Invalidated assignment operator.
void MSDetectorControl::updateDetectors (const SUMOTime step)
Computes detector values.
Some detectors need to be touched each time step in order to compute values from the vehicles stored in their containers. This method goes through all of these detectors and forces a recomputation of the values.
Parameters:
[in] step The current time step
Definition at line 128 of file MSDetectorControl.cpp.
References NamedObjectCont< T >::getMyMap(), getTypedDetectors(), myDetectors, and myMeanData.
Referenced by MSNet::writeOutput().
void MSDetectorControl::writeOutput (SUMOTime step, bool closing)
Writes the output to be generated within the given time step.
Goes through the list of intervals. If one interval has ended within the given step or if the closing-flag is set and the output was not written in this step already, the writeXMLOutput method is called for all MSDetectorFileOutputs within this interval.
Parameters:
[in] step The current time step
[in] closing Whether the device is closed
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 142 of file MSDetectorControl.cpp.
References myIntervals, myLastCalls, and MSDetectorFileOutput::writeXMLOutput().
Referenced by close(), and MSNet::writeOutput().
Friends And Related Function Documentation
friend class GUINet [friend]
Definition at line 68 of file MSDetectorControl.h.
Field Documentation
std::map<SumoXMLTag, NamedObjectCont< MSDetectorFileOutput*> > MSDetectorControl::myDetectors [protected]
The detectors map, first by detector type, then using NamedObjectCont (.
See also:
NamedObjectCont)
Definition at line 228 of file MSDetectorControl.h.
Referenced by add(), getTypedDetectors(), GUINet::initGUIStructures(), updateDetectors(), and ~MSDetectorControl().
NamedObjectCont< MSDetectorFileOutput*> MSDetectorControl::myEmptyContainer [protected]
An empty container to return in getTypedDetectors() if no detectors of the asked type exist.
Definition at line 241 of file MSDetectorControl.h.
Referenced by getTypedDetectors().
Intervals MSDetectorControl::myIntervals [protected]
Map that hold DetectorFileVec for given intervals.
Definition at line 232 of file MSDetectorControl.h.
Referenced by addDetectorAndInterval(), close(), and writeOutput().
std::map<IntervalsKey, SUMOTime> MSDetectorControl::myLastCalls [protected]
The map that holds the last call for each sample interval.
Definition at line 235 of file MSDetectorControl.h.
Referenced by addDetectorAndInterval(), and writeOutput().
std::vector<MSMeanData*> MSDetectorControl::myMeanData [protected]
List of harmonoise detectors.
Definition at line 238 of file MSDetectorControl.h.
Referenced by add(), updateDetectors(), and ~MSDetectorControl().
The documentation for this class was generated from the following files:
MSDetectorControl.h
MSDetectorControl.cpp