SUMO - Simulation of Urban MObility: TraCIDijkstraRouter< E >::EdgeInfoCont Class Reference
TraCIDijkstraRouter< E >::EdgeInfoCont Class Reference
#include <TraCIDijkstraRouter.h>
Public Member Functions
EdgeInfo * add (const E *edgeArg, SUMOReal effortArg, EdgeInfo *prevArg, SUMOReal distArg)
Adds the information about the effort to get to an edge and its predeccessing edge.
EdgeInfo * add (const E *edgeArg, SUMOReal effortArg, EdgeInfo *prevArg)
Adds the information about the effort to get to an edge and its predeccessing edge.
EdgeInfoCont (size_t toAlloc)
Constructor.
SUMOReal getEffort (const E *to) const
Returns the effort to get to the specify edge The value is valid if the edge was already visited.
void reset ()
Resets all effort-information.
~EdgeInfoCont ()
Destructor.
Private Attributes
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
Detailed Description
template<class E>
class TraCIDijkstraRouter< E >::EdgeInfoCont
A class holding the instances of effort-to-reach and predeccessor information for every edge within the network. This class is used instead of the former saving of these values within the edges to allow parallel route computation in multithreading mode.
Definition at line 239 of file TraCIDijkstraRouter.h.
Constructor & Destructor Documentation
template<class E> TraCIDijkstraRouter< E >::EdgeInfoCont::EdgeInfoCont (size_t toAlloc) [inline]
Constructor.
Definition at line 242 of file TraCIDijkstraRouter.h.
template<class E> TraCIDijkstraRouter< E >::EdgeInfoCont::~EdgeInfoCont () [inline]
Destructor.
Definition at line 246 of file TraCIDijkstraRouter.h.
Member Function Documentation
template<class E> EdgeInfo* TraCIDijkstraRouter< E >::EdgeInfoCont::add (const E * edgeArg, SUMOReal effortArg, EdgeInfo * prevArg, SUMOReal distArg) [inline]
Adds the information about the effort to get to an edge and its predeccessing edge.
Definition at line 259 of file TraCIDijkstraRouter.h.
References TraCIDijkstraRouter< E >::EdgeInfo::dist, TraCIDijkstraRouter< E >::EdgeInfo::edge, TraCIDijkstraRouter< E >::EdgeInfo::effort, TraCIDijkstraRouter< E >::EdgeInfoCont::myEdgeInfos, and TraCIDijkstraRouter< E >::EdgeInfo::prev.
template<class E> EdgeInfo* TraCIDijkstraRouter< E >::EdgeInfoCont::add (const E * edgeArg, SUMOReal effortArg, EdgeInfo * prevArg) [inline]
Adds the information about the effort to get to an edge and its predeccessing edge.
Definition at line 249 of file TraCIDijkstraRouter.h.
References TraCIDijkstraRouter< E >::EdgeInfo::dist, TraCIDijkstraRouter< E >::EdgeInfo::edge, TraCIDijkstraRouter< E >::EdgeInfo::effort, TraCIDijkstraRouter< E >::EdgeInfoCont::myEdgeInfos, and TraCIDijkstraRouter< E >::EdgeInfo::prev.
Referenced by TraCIDijkstraRouter< E >::compute().
template<class E> SUMOReal TraCIDijkstraRouter< E >::EdgeInfoCont::getEffort (const E * to) const [inline]
Returns the effort to get to the specify edge The value is valid if the edge was already visited.
Definition at line 279 of file TraCIDijkstraRouter.h.
References TraCIDijkstraRouter< E >::EdgeInfoCont::myEdgeInfos.
Referenced by TraCIDijkstraRouter< E >::compute().
template<class E> void TraCIDijkstraRouter< E >::EdgeInfoCont::reset () [inline]
Resets all effort-information.
Definition at line 270 of file TraCIDijkstraRouter.h.
References max, and TraCIDijkstraRouter< E >::EdgeInfoCont::myEdgeInfos.
Referenced by TraCIDijkstraRouter< E >::compute().
Field Documentation
template<class E> std::vector<EdgeInfo> TraCIDijkstraRouter< E >::EdgeInfoCont::myEdgeInfos [private]
The container of edge information.
Definition at line 285 of file TraCIDijkstraRouter.h.
Referenced by TraCIDijkstraRouter< E >::EdgeInfoCont::add(), TraCIDijkstraRouter< E >::EdgeInfoCont::getEffort(), and TraCIDijkstraRouter< E >::EdgeInfoCont::reset().
The documentation for this class was generated from the following file:
TraCIDijkstraRouter.h