SUMO - Simulation of Urban MObility: MSMeanData::MeanDataValues Class Reference
MSMeanData::MeanDataValues Class Reference
Data structure for mean (aggregated) edge/lane values.
#include <MSMeanData.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
virtual void addTo (MeanDataValues &val) const =0
Add the values of this to the given one and store them there.
const MSLane * getLane () const
Returns the lane the reminder works on.
virtual SUMOReal getSamples () const
Returns the number of collected sample seconds.
virtual bool isEmpty () const
Returns whether any data was collected.
MeanDataValues (MSLane *const lane, const SUMOReal length, const bool doAdd, const std::set< std::string > *const vTypes=0)
Constructor.
virtual bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Called if the vehicle enters the reminder's lane.
virtual bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Called if the vehicle leaves the reminder's lane.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
virtual void reset (bool afterWrite=false)=0
Resets values so they may be used for the next interval.
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
bool vehicleApplies (const SUMOVehicle &veh) const
Tests whether the vehicles type is to be regarded.
virtual void write (OutputDevice &dev, const SUMOTime period, const SUMOReal numLanes, const int numVehicles=-1) const =0
Writes output values into the given stream.
virtual ~MeanDataValues ()
Destructor.
Protected Attributes
MSLane *const myLane
Lane on which the reminder works.
const SUMOReal myLaneLength
The length of the lane / edge the data collector is on.
Private Attributes
const std::set< std::string >
*const myVehicleTypes
The vehicle types to look for (0 or empty means all).
Collected values
The number of sampled vehicle movements (in s)
SUMOReal sampleSeconds
SUMOReal travelledDistance
The sum of the distances the vehicles travelled.
Detailed Description
Data structure for mean (aggregated) edge/lane values.
Structure holding values that describe the emissions aggregated over some seconds.
Definition at line 76 of file MSMeanData.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification [inherited]
Definition of a vehicle state.
Enumerator:
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network).
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only).
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only).
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted).
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 93 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSMeanData::MeanDataValues::MeanDataValues (MSLane *const lane, const SUMOReal length, const bool doAdd, const std::set< std::string > *const vTypes = 0)
Constructor.
Definition at line 61 of file MSMeanData.cpp.
MSMeanData::MeanDataValues::~MeanDataValues () [virtual]
Destructor.
Definition at line 71 of file MSMeanData.cpp.
Member Function Documentation
virtual void MSMeanData::MeanDataValues::addTo (MeanDataValues & val) const [pure virtual]
Add the values of this to the given one and store them there.
Parameters:
[in] val The meandata to add to
Implemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Referenced by MSMeanData::writeEdge().
const MSLane* MSMoveReminder::getLane () const [inline, inherited]
Returns the lane the reminder works on.
Returns:
The lane the reminder works on.
Definition at line 87 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by GUIInstantInductLoop::buildDetectorGUIRepresentation(), GUIInductLoop::buildDetectorGUIRepresentation(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), notifyMove(), TraCIServerAPI_InductionLoop::processGet(), and MSMeanData::writeEdge().
SUMOReal MSMeanData::MeanDataValues::getSamples () const [virtual]
Returns the number of collected sample seconds.
Returns:
the number of collected sample seconds
Reimplemented in MSMeanData::MeanDataValueTracker.
Definition at line 133 of file MSMeanData.cpp.
References sampleSeconds.
Referenced by MSMeanData::writePrefix().
bool MSMeanData::MeanDataValues::isEmpty () const [virtual]
Returns whether any data was collected.
Returns:
whether no data was collected
Reimplemented in MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 122 of file MSMeanData.cpp.
References sampleSeconds.
Referenced by MSMeanData::writePrefix().
bool MSMeanData::MeanDataValues::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) [virtual]
Called if the vehicle enters the reminder's lane.
Parameters:
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
See also:
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 76 of file MSMeanData.cpp.
References UNUSED_PARAMETER, and vehicleApplies().
bool MSMeanData::MeanDataValues::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) [virtual]
Called if the vehicle leaves the reminder's lane.
Parameters:
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also:
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Reimplemented in MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 109 of file MSMeanData.cpp.
References MSMoveReminder::NOTIFICATION_JUNCTION.
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) [virtual]
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns:
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 83 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), myLaneLength, MSMoveReminder::notifyMoveInternal(), SUMOReal, TS, and WRITE_ERROR.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) [inline, virtual, inherited]
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters:
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 200 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by notifyMove().
virtual void MSMeanData::MeanDataValues::reset (bool afterWrite = false) [pure virtual]
Resets values so they may be used for the next interval.
Implemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Referenced by MSMeanData::init(), MSMeanData::resetOnly(), and MSMeanData::writeEdge().
void MSMeanData::MeanDataValues::update () [virtual]
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 128 of file MSMeanData.cpp.
bool MSMeanData::MeanDataValues::vehicleApplies (const SUMOVehicle & veh) const
Tests whether the vehicles type is to be regarded.
Parameters:
[in] veh The regarded vehicle
Returns:
whether the type of the vehicle is in the set of regarded types
Definition at line 115 of file MSMeanData.cpp.
References MSVehicleType::getID(), SUMOVehicle::getVehicleType(), and myVehicleTypes.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), notifyEnter(), and MSMeanData_Net::MSLaneMeanDataValues::notifyLeave().
virtual void MSMeanData::MeanDataValues::write (OutputDevice & dev, const SUMOTime period, const SUMOReal numLanes, const int numVehicles = -1) const [pure virtual]
Writes output values into the given stream.
Parameters:
[in] dev The output device to write the data into
[in] period Length of the period the data were gathered
[in] numLanes The total number of lanes for which the data was collected
Exceptions:
IOError If an error on writing occurs (!!! not yet implemented)
Implemented in MSMeanData::MeanDataValueTracker, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_HBEFA::MSLaneMeanDataValues, and MSMeanData_Net::MSLaneMeanDataValues.
Referenced by MSMeanData::writeEdge().
Field Documentation
MSLane* const MSMoveReminder::myLane [protected, inherited]
Lane on which the reminder works.
Definition at line 215 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), and MSMeanData::MeanDataValueTracker::reset().
const SUMOReal MSMeanData::MeanDataValues::myLaneLength [protected]
The length of the lane / edge the data collector is on.
Definition at line 173 of file MSMeanData.h.
Referenced by notifyMove(), MSMeanData::MeanDataValueTracker::reset(), MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::write().
const std::set<std::string>* const MSMeanData::MeanDataValues::myVehicleTypes [private]
The vehicle types to look for (0 or empty means all).
Definition at line 186 of file MSMeanData.h.
Referenced by vehicleApplies().
SUMOReal MSMeanData::MeanDataValues::sampleSeconds [protected]
Definition at line 178 of file MSMeanData.h.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData_HBEFA::MSLaneMeanDataValues::addTo(), MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), getSamples(), MSMeanData_Net::MSLaneMeanDataValues::isEmpty(), isEmpty(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_HBEFA::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_HBEFA::MSLaneMeanDataValues::reset(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::write().
SUMOReal MSMeanData::MeanDataValues::travelledDistance
The sum of the distances the vehicles travelled.
Definition at line 181 of file MSMeanData.h.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData_HBEFA::MSLaneMeanDataValues::addTo(), MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_HBEFA::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_HBEFA::MSLaneMeanDataValues::reset(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::write(), MSMeanData_HBEFA::MSLaneMeanDataValues::write(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::write().
The documentation for this class was generated from the following files:
MSMeanData.h
MSMeanData.cpp