SUMO - Simulation of Urban MObility: AGHousehold Class Reference
AGHousehold Class Reference
#include <AGHousehold.h>
Public Member Functions
void addACar ()
AGHousehold (AGStreet *str, AGCity *city, int idHouseholds)
AGHousehold (AGPosition pos, AGCity *city, int idHouseholds)
bool allocateAdultsWork ()
bool allocateChildrenSchool ()
void generateCars (SUMOReal rate)
void generatePeople ()
int getAdultNbr ()
int getCarNbr ()
int getPeopleNbr ()
AGPosition getPosition ()
AGCity * getTheCity ()
bool isCloseFromPubTransport (std::map< int, AGPosition > *pubTransport)
bool isCloseFromPubTransport (std::list< AGPosition > *pubTransport)
void regenerate ()
bool retiredHouseholders ()
Data Fields
std::list< AGAdult > adults
std::list< AGCar > cars
std::list< AGChild > children
Private Member Functions
bool decisionProba (SUMOReal p)
Private Attributes
int idHH
AGPosition location
AGCity * myCity
int numberOfCars
int numberOfPeople
Detailed Description
Definition at line 58 of file AGHousehold.h.
Constructor & Destructor Documentation
AGHousehold::AGHousehold (AGPosition pos, AGCity * city, int idHouseholds) [inline]
Definition at line 60 of file AGHousehold.h.
AGHousehold::AGHousehold (AGStreet * str, AGCity * city, int idHouseholds) [inline]
Definition at line 64 of file AGHousehold.h.
Member Function Documentation
void AGHousehold::addACar ()
generates one (more) car in this household
Definition at line 86 of file AGHousehold.cpp.
References cars, and idHH.
Referenced by generateCars().
bool AGHousehold::allocateAdultsWork ()
associates a work position to every working adult is taken in account the unemployment and the number of work positions
Definition at line 166 of file AGHousehold.cpp.
References adults, myCity, AGCity::statData, AGDataAndStatistics::unemployement, AGCity::workPositions, and AGDataAndStatistics::workPositions.
bool AGHousehold::allocateChildrenSchool ()
associates a school to each children. return false if not done (not enough place at school in the city...
Definition at line 153 of file AGHousehold.cpp.
References children, location, myCity, and AGCity::schools.
bool AGHousehold::decisionProba (SUMOReal p) [private]
Definition at line 181 of file AGHousehold.cpp.
References RandHelper::rand().
Referenced by generateCars(), and generatePeople().
void AGHousehold::generateCars (SUMOReal rate)
function allocating cars to this household in relation to the given rate for each adult
Definition at line 75 of file AGHousehold.cpp.
References addACar(), adults, cars, and decisionProba().
void AGHousehold::generatePeople ()
function generating one first Adult.
a second person is created depending on the mean number of adults per Households (and depending on the age of the first person)
and children are created for households of one or two people in age to work. Children are created in relation to the mean number of children and they are distributed with the POISSON's lay of probability.
Definition at line 46 of file AGHousehold.cpp.
References adults, children, decisionProba(), AGDataAndStatistics::getPoissonsNumberOfChildren(), AGDataAndStatistics::getRandomPopDistributed(), AGDataAndStatistics::limitAgeChildren, AGDataAndStatistics::limitAgeRetirement, AGDataAndStatistics::limitEndAge, AGDataAndStatistics::meanNbrChildren, myCity, AGDataAndStatistics::secondPersProb, and AGCity::statData.
int AGHousehold::getAdultNbr ()
Definition at line 102 of file AGHousehold.cpp.
References adults.
Referenced by AGWorkAndSchool::carAllocation(), AGWorkAndSchool::makePossibleDriversDrive(), and AGFreeTime::possibleTypeOfTrip().
int AGHousehold::getCarNbr ()
Definition at line 92 of file AGHousehold.cpp.
References cars.
Referenced by AGWorkAndSchool::buildWorkDestinations(), AGWorkAndSchool::generateTrips(), AGWorkAndSchool::isThereUnusedCar(), and AGActivity::possibleTranspMean().
int AGHousehold::getPeopleNbr ()
Definition at line 97 of file AGHousehold.cpp.
References adults, and children.
Referenced by AGFreeTime::possibleTypeOfTrip().
AGPosition AGHousehold::getPosition ()
returns the position of the household and other private entities
Definition at line 186 of file AGHousehold.cpp.
References location.
Referenced by AGWorkAndSchool::buildChildrenAccompaniment(), AGWorkAndSchool::carsToTrips(), AGWorkAndSchool::generateListTrips(), AGActivity::possibleTranspMean(), regenerate(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
AGCity * AGHousehold::getTheCity ()
returns the city pointer in which the household is.
Definition at line 191 of file AGHousehold.cpp.
References myCity.
Referenced by AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
bool AGHousehold::isCloseFromPubTransport (std::map< int, AGPosition > * pubTransport)
Definition at line 116 of file AGHousehold.cpp.
References location, AGDataAndStatistics::maxFootDistance, AGPosition::minDistanceTo(), myCity, AGCity::statData, and SUMOReal.
bool AGHousehold::isCloseFromPubTransport (std::list< AGPosition > * pubTransport)
function returning true if the household is close to the given stations stations
Definition at line 107 of file AGHousehold.cpp.
References location, AGDataAndStatistics::maxFootDistance, AGPosition::minDistanceTo(), myCity, AGCity::statData, and SUMOReal.
void AGHousehold::regenerate ()
function regenerating the household: --> work positions and schools are resigned --> cars and people are deleted --> number of people are MAINTAINED --> work positions, schools and cars are reallocated
Definition at line 125 of file AGHousehold.cpp.
References adults, children, getPosition(), myCity, AGCity::schools, AGCity::statData, AGDataAndStatistics::unemployement, AGCity::workPositions, and AGDataAndStatistics::workPositions.
Referenced by AGActivities::generateTrips().
bool AGHousehold::retiredHouseholders ()
returns if adults are retired or in working age
Definition at line 196 of file AGHousehold.cpp.
References adults, AGDataAndStatistics::limitAgeRetirement, myCity, and AGCity::statData.
Field Documentation
std::list<AGAdult> AGHousehold::adults
Definition at line 123 of file AGHousehold.h.
Referenced by allocateAdultsWork(), AGWorkAndSchool::buildWorkDestinations(), AGWorkAndSchool::carAllocation(), AGFreeTime::decideTypeOfTrip(), generateCars(), generatePeople(), getAdultNbr(), getPeopleNbr(), AGWorkAndSchool::makePossibleDriversDrive(), AGFreeTime::possibleTypeOfTrip(), regenerate(), and retiredHouseholders().
std::list<AGCar> AGHousehold::cars
Definition at line 125 of file AGHousehold.h.
Referenced by addACar(), AGWorkAndSchool::carsToTrips(), generateCars(), getCarNbr(), AGWorkAndSchool::getUnusedCar(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
std::list<AGChild> AGHousehold::children
Definition at line 124 of file AGHousehold.h.
Referenced by allocateChildrenSchool(), AGWorkAndSchool::buildChildrenAccompaniment(), generatePeople(), getPeopleNbr(), and regenerate().
int AGHousehold::idHH [private]
Definition at line 135 of file AGHousehold.h.
Referenced by addACar().
AGPosition AGHousehold::location [private]
Definition at line 132 of file AGHousehold.h.
Referenced by allocateChildrenSchool(), getPosition(), and isCloseFromPubTransport().
AGCity* AGHousehold::myCity [private]
Definition at line 131 of file AGHousehold.h.
Referenced by allocateAdultsWork(), allocateChildrenSchool(), generatePeople(), getTheCity(), isCloseFromPubTransport(), regenerate(), and retiredHouseholders().
int AGHousehold::numberOfCars [private]
Definition at line 134 of file AGHousehold.h.
int AGHousehold::numberOfPeople [private]
Definition at line 133 of file AGHousehold.h.
The documentation for this class was generated from the following files:
AGHousehold.h
AGHousehold.cpp