SUMO - Simulation of Urban MObility: SUMOSAXAttributesImpl_Xerces Class Reference
SUMOSAXAttributesImpl_Xerces Class Reference
Encapsulated Xerces-SAX-attributes.
#include <SUMOSAXAttributesImpl_Xerces.h>
Public Member Functions
bool getBoolReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is a boolean.
int getIntReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is an int.
bool getOptBoolReporting (int attr, const char *objectid, bool &ok, bool defaultValue, bool report=true) const
Tries to read given attribute assuming it is a boolean.
int getOptIntReporting (int attr, const char *objectid, bool &ok, int defaultValue, bool report=true) const
Tries to read given attribute assuming it is an int.
std::string getOptStringReporting (int attr, const char *objectid, bool &ok, const std::string &defaultValue, bool report=true) const
Tries to read given attribute assuming it is a string.
SUMOReal getOptSUMORealReporting (int attr, const char *objectid, bool &ok, SUMOReal defaultValue, bool report=true) const
Tries to read given attribute assuming it is a SUMOReal.
SUMOTime getOptSUMOTimeReporting (int attr, const char *objectid, bool &ok, SUMOTime defaultValue, bool report=true) const
Tries to read given attribute assuming it is a SUMOTime.
std::string getStringReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is a string.
SUMOReal getSUMORealReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is a SUMOReal.
SUMOTime getSUMOTimeReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is a SUMOTime.
SUMOSAXAttributesImpl_Xerces (const Attributes &attrs, const std::map< int, XMLCh * > &predefinedTags, const std::map< int, std::string > &predefinedTagsMML, const std::string &objectType)
Constructor.
virtual ~SUMOSAXAttributesImpl_Xerces ()
Destructor.
methods for retrieving attribute values
typedef std::map< int, XMLCh * > AttrMap
Definition of a map of attribute ids to their xerces-representation.
const Attributes & myAttrs
The encapsulated attributes.
const AttrMap & myPredefinedTags
Map of attribute ids to their xerces-representation.
const std::map< int,
std::string > & myPredefinedTagsMML
Map of attribute ids to their (readable) string-representation.
bool getBool (int id) const throw (EmptyData, BoolFormatException)
Returns the bool-value of the named (by its enum-value) attribute.
bool getBoolSecure (int id, bool def) const throw (EmptyData)
Returns the bool-value of the named (by its enum-value) attribute or the given value if the attribute is not known.
SUMOReal getFloat (const std::string &id) const throw (EmptyData, NumberFormatException)
Returns the SUMOReal-value of the named attribute.
SUMOReal getFloat (int id) const throw (EmptyData, NumberFormatException)
Returns the SUMOReal-value of the named (by its enum-value) attribute.
SUMOReal getFloatSecure (int id, SUMOReal def) const throw (EmptyData, NumberFormatException)
Returns the SUMOReal-value of the named (by its enum-value) attribute.
int getInt (int id) const throw (EmptyData, NumberFormatException)
Returns the int-value of the named (by its enum-value) attribute.
int getIntSecure (int id, int def) const throw (EmptyData, NumberFormatException)
Returns the int-value of the named (by its enum-value) attribute.
std::string getName (int attr) const
Converts the given attribute id into a man readable string.
std::string getString (int id) const throw (EmptyData)
Returns the string-value of the named (by its enum-value) attribute.
std::string getStringSecure (const std::string &id, const std::string &def) const
Returns the string-value of the named (by its enum-value) attribute.
std::string getStringSecure (int id, const std::string &def) const throw (EmptyData)
Returns the string-value of the named (by its enum-value) attribute.
bool hasAttribute (const std::string &id) const
Returns the information whether the named attribute is within the current list.
bool hasAttribute (int id) const
Returns the information whether the named (by its enum-value) attribute is within the current list.
const XMLCh * getAttributeValueSecure (int id) const
Returns Xerces-value of the named attribute.
SUMOSAXAttributesImpl_Xerces & operator= (const SUMOSAXAttributesImpl_Xerces &src)
Invalidated assignment operator.
SUMOSAXAttributesImpl_Xerces (const SUMOSAXAttributesImpl_Xerces &src)
Invalidated copy constructor.
virtual methods for retrieving attribute values
const std::string & getObjectType () const
return the objecttype to which these attributes belong
static const std::string ENCODING = " encoding=\"UTF-8\""
The encoding of parsed strings.
static void parseStringVector (const std::string &def, std::vector< std::string > &into)
Splits the given string.
void emitEmptyError (const std::string &attrname, const char *objectid) const
void emitFormatError (const std::string &attrname, const std::string &type, const char *objectid) const
void emitUngivenError (const std::string &attrname, const char *objectid) const
Detailed Description
Encapsulated Xerces-SAX-attributes.
See also:
SUMOSAXAttributes
Definition at line 59 of file SUMOSAXAttributesImpl_Xerces.h.
Member Typedef Documentation
typedef std::map<int, XMLCh*> SUMOSAXAttributesImpl_Xerces::AttrMap [private]
Definition of a map of attribute ids to their xerces-representation.
Definition at line 291 of file SUMOSAXAttributesImpl_Xerces.h.
Constructor & Destructor Documentation
SUMOSAXAttributesImpl_Xerces::SUMOSAXAttributesImpl_Xerces (const Attributes & attrs, const std::map< int, XMLCh * > & predefinedTags, const std::map< int, std::string > & predefinedTagsMML, const std::string & objectType)
Constructor.
Parameters:
[in] attrs The encapsulated xerces-attributes
[in] predefinedTags Map of attribute ids to their xerces-representation
[in] predefinedTagsMML Map of attribute ids to their (readable) string-representation
Definition at line 50 of file SUMOSAXAttributesImpl_Xerces.cpp.
SUMOSAXAttributesImpl_Xerces::~SUMOSAXAttributesImpl_Xerces () [virtual]
Destructor.
Definition at line 60 of file SUMOSAXAttributesImpl_Xerces.cpp.
SUMOSAXAttributesImpl_Xerces::SUMOSAXAttributesImpl_Xerces (const SUMOSAXAttributesImpl_Xerces & src) [private]
Invalidated copy constructor.
Member Function Documentation
void SUMOSAXAttributes::emitEmptyError (const std::string & attrname, const char * objectid) const [protected, inherited]
Definition at line 323 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::getBoolReporting(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptIntReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), and SUMOSAXAttributes::getSUMOTimeReporting().
void SUMOSAXAttributes::emitFormatError (const std::string & attrname, const std::string & type, const char * objectid) const [protected, inherited]
Definition at line 339 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::getBoolReporting(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptIntReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMORealReporting(), and SUMOSAXAttributes::getSUMOTimeReporting().
void SUMOSAXAttributes::emitUngivenError (const std::string & attrname, const char * objectid) const [protected, inherited]
Definition at line 307 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::getBoolReporting(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), and SUMOSAXAttributes::getSUMOTimeReporting().
const XMLCh * SUMOSAXAttributesImpl_Xerces::getAttributeValueSecure (int id) const [private]
Returns Xerces-value of the named attribute.
It is assumed that this attribute is within the stored attributes.
Parameters:
[in] id The id of the attribute to retrieve the vale of
Returns:
The xerces-value of the attribute
Definition at line 148 of file SUMOSAXAttributesImpl_Xerces.cpp.
References myAttrs, and myPredefinedTags.
bool SUMOSAXAttributesImpl_Xerces::getBool (int id) const throw (EmptyData, BoolFormatException) [virtual]
Returns the bool-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2bool. If the attribute is empty or ==0, TplConvert<XMLCh>::_2bool throws an EmptyData-exception which is passed. If the value can not be parsed to a bool, TplConvert<XMLCh>::_2bool throws a BoolFormatException-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
Returns:
The attribute's value as a bool, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
BoolFormatException If the attribute value can not be parsed to a bool
Implements SUMOSAXAttributes.
Definition at line 75 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvert< E >::_2bool().
bool SUMOSAXAttributes::getBoolReporting (int attr, const char * objectid, bool & ok, bool report = true) const [inherited]
Tries to read given attribute assuming it is a boolean.
If an error occurs (the attribute is not there, it is not a boolean), "ok" is set to false and an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; false if an error occured
Definition at line 156 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getBool(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
bool SUMOSAXAttributesImpl_Xerces::getBoolSecure (int id, bool def) const throw (EmptyData) [virtual]
Returns the bool-value of the named (by its enum-value) attribute or the given value if the attribute is not known.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2boolSec. If the attribute is empty, TplConvert<XMLCh>::_2boolSec throws an EmptyData-exception which is passed. If the attribute==0, TplConvert<XMLCh>::_2boolSec returns the default value.
Parameters:
[in] id The id of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns:
The attribute's value as a bool, if it could be read and parsed
Exceptions:
EmptyData If the attribute value is an empty string
Implements SUMOSAXAttributes.
Definition at line 81 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvertSec< E >::_2boolSec().
SUMOReal SUMOSAXAttributesImpl_Xerces::getFloat (const std::string & id) const throw (EmptyData, NumberFormatException) [virtual]
Returns the SUMOReal-value of the named attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2SUMOReal. If the attribute is empty or ==0, TplConvert<XMLCh>::_2SUMOReal throws an EmptyData-exception which is passed. If the value can not be parsed to a SUMOReal, TplConvert<XMLCh>::_2SUMOReal throws a NumberFormatException-exception which is passed.
Parameters:
[in] id The name of the attribute to return the value of
Returns:
The attribute's value as a float, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an SUMOReal
Implements SUMOSAXAttributes.
Definition at line 156 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvert< E >::_2SUMOReal(), and SUMOReal.
SUMOReal SUMOSAXAttributesImpl_Xerces::getFloat (int id) const throw (EmptyData, NumberFormatException) [virtual]
Returns the SUMOReal-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2SUMOReal. If the attribute is empty or ==0, TplConvert<XMLCh>::_2SUMOReal throws an EmptyData-exception which is passed. If the value can not be parsed to a SUMOReal, TplConvert<XMLCh>::_2SUMOReal throws a NumberFormatException-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
Returns:
The attribute's value as a float, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an SUMOReal
Implements SUMOSAXAttributes.
Definition at line 135 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvert< E >::_2SUMOReal().
SUMOReal SUMOSAXAttributesImpl_Xerces::getFloatSecure (int id, SUMOReal def) const throw (EmptyData, NumberFormatException) [virtual]
Returns the SUMOReal-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2SUMORealSec. If the attribute is empty, TplConvert<XMLCh>::_2SUMORealSec throws an EmptyData-exception which is passed. If the attribute==0, TplConvert<XMLCh>::_2SUMORealSec returns the default value. If the value can not be parsed to a SUMOReal, TplConvert<XMLCh>::_2SUMORealSec throws a NumberFormatException-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns:
The attribute's value as a float, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an SUMOReal
Implements SUMOSAXAttributes.
Definition at line 141 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvertSec< E >::_2SUMORealSec().
int SUMOSAXAttributesImpl_Xerces::getInt (int id) const throw (EmptyData, NumberFormatException) [virtual]
Returns the int-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2int. If the attribute is empty or ==0, TplConvert<XMLCh>::_2int throws an EmptyData-exception which is passed. If the value can not be parsed to an int, TplConvert<XMLCh>::_2int throws a NumberFormatException-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
Returns:
The attribute's value as an int, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an int
Implements SUMOSAXAttributes.
Definition at line 87 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvert< E >::_2int().
int SUMOSAXAttributes::getIntReporting (int attr, const char * objectid, bool & ok, bool report = true) const [inherited]
Tries to read given attribute assuming it is an int.
If an error occurs (the attribute is not there, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
If the value could be read, "ok" is not changed, and the value is returned.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; -1 if an error occured
Definition at line 60 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getInt(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addConnection(), NIImporter_SUMO::addConnection(), NIXMLEdgesHandler::addEdge(), NIXMLEdgesHandler::addLane(), NLHandler::addLogicItem(), NLHandler::addRequest(), MSRouteHandler::addStop(), NLHandler::addSuccLane(), NIImporter_SUMO::addSuccLane(), SUMOSAXAttributes::getSUMOTimeReporting(), PCLoaderOSM::EdgesHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), RORDGenerator_ODAmounts::parseFlowAmountDef(), SUMOVehicleParserHelper::parseFlowAttributes(), NIXMLConnectionsHandler::parseLaneDefinition(), AGActivityGenHandler::parseStation(), SUMOVehicleParserHelper::parseVehicleAttributes(), NIXMLTrafficLightsHandler::removeTlConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), and RORDLoader_SUMOBase::startAlternative().
int SUMOSAXAttributesImpl_Xerces::getIntSecure (int id, int def) const throw (EmptyData, NumberFormatException) [virtual]
Returns the int-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2intSec. If the attribute is empty, TplConvert<XMLCh>::_2intSec throws an EmptyData-exception which is passed. If the attribute==0, TplConvert<XMLCh>::_2intSec returns the default value. If the value can not be parsed to an int, TplConvert<XMLCh>::_2intSec throws a NumberFormatException-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns:
The attribute's value as an int, if it could be read and parsed
Exceptions:
EmptyData If the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an int
Implements SUMOSAXAttributes.
Definition at line 93 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvertSec< E >::_2intSec().
std::string SUMOSAXAttributesImpl_Xerces::getName (int attr) const [virtual]
Converts the given attribute id into a man readable string.
Returns a "?" if the attribute is not known.
Parameters:
[in] attr The id of the attribute to return the name of
Returns:
The name of the described attribute
Implements SUMOSAXAttributes.
Definition at line 184 of file SUMOSAXAttributesImpl_Xerces.cpp.
References myPredefinedTagsMML.
const std::string& SUMOSAXAttributes::getObjectType () const [inline, inherited]
return the objecttype to which these attributes belong
Definition at line 475 of file SUMOSAXAttributes.h.
References SUMOSAXAttributes::myObjectType.
Referenced by NIImporter_SUMO::addEdge(), NIImporter_SUMO::addJunction(), NIImporter_SUMO::addLane(), NLHandler::addPOI(), NLHandler::addPoly(), SUMOVehicleParserHelper::beginVTypeParsing(), NIImporter_SUMO::loadLocation(), PCNetProjectionLoader::myStartElement(), GUISettingsHandler::myStartElement(), NLHandler::openJunction(), MSRouteHandler::openRoute(), ODDistrictHandler::parseConnection(), SUMOVehicleParserHelper::parseEmissionClass(), SUMOVehicleParserHelper::parseGuiShape(), SUMOVehicleParserHelper::parseVehicleClass(), NLHandler::setLocation(), RORDLoader_SUMOBase::startRoute(), and NIXMLEdgesHandler::tryGetShape().
bool SUMOSAXAttributes::getOptBoolReporting (int attr, const char * objectid, bool & ok, bool defaultValue, bool report = true) const [inherited]
Tries to read given attribute assuming it is a boolean.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not a boolean), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; the default value if the attribute does not exist; false if an error occured
Definition at line 182 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getBool(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIXMLEdgesHandler::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addLogicItem(), NLHandler::addPoly(), NLHandler::addRequest(), MSRouteHandler::addStop(), NLHandler::addWAUTJunction(), PCTypeDefHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), and NIXMLConnectionsHandler::parseLaneBound().
int SUMOSAXAttributes::getOptIntReporting (int attr, const char * objectid, bool & ok, int defaultValue, bool report = true) const [inherited]
Tries to read given attribute assuming it is an int.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
If the value could be read, "ok" is not changed, and the value is returned.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; the default value if the attribute does not exist; -1 if an error occured
Definition at line 86 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getInt(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NIImporter_SUMO::addEdge(), NLHandler::addLane(), NLHandler::addPOI(), NLHandler::addPoly(), NIXMLTrafficLightsHandler::addTlConnection(), SUMOSAXAttributes::getOptSUMOTimeReporting(), PCTypeDefHandler::myStartElement(), and NIXMLTypesHandler::myStartElement().
std::string SUMOSAXAttributes::getOptStringReporting (int attr, const char * objectid, bool & ok, const std::string & defaultValue, bool report = true) const [inherited]
Tries to read given attribute assuming it is a string.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and not empty; the default value if the attribute does not exist; "" if an error occured
Definition at line 230 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::getString(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLDiscreteEventBuilder::addAction(), NLHandler::addConnection(), NIImporter_SUMO::addConnection(), NLHandler::addE2Detector(), NIXMLEdgesHandler::addEdge(), NIImporter_SUMO::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addLane(), NIXMLEdgesHandler::addLane(), NIImporter_SUMO::addLane(), NIXMLNodesHandler::addNode(), NLHandler::addPOI(), NLHandler::addPoly(), NIImporter_SUMO::addProhibition(), NIXMLEdgesHandler::addSplit(), MSRouteHandler::addStop(), NLHandler::addSuccLane(), NIImporter_SUMO::addSuccLane(), NIXMLTrafficLightsHandler::addTlConnection(), NLHandler::addWAUTJunction(), NLHandler::beginEdgeParsing(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), RORDLoader_TripDefs::getVehicleID(), NLHandler::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), SAXWeightsHandler::myStartElement(), RODFDetectorHandler::myStartElement(), PCTypeDefHandler::myStartElement(), PCNetProjectionLoader::myStartElement(), PCLoaderXML::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), GUISettingsHandler::myStartElement(), NLHandler::openJunction(), MSRouteHandler::openRoute(), SUMOVehicleParserHelper::parseEmissionClass(), SUMOVehicleParserHelper::parseGuiShape(), RONetHandler::parseLane(), SUMOVehicleParserHelper::parseVehicleClass(), NIXMLNodesHandler::processTrafficLightDefinitions(), NIXMLEdgesHandler::tryGetLaneSpread(), and NIXMLEdgesHandler::tryGetShape().
SUMOReal SUMOSAXAttributes::getOptSUMORealReporting (int attr, const char * objectid, bool & ok, SUMOReal defaultValue, bool report = true) const [inherited]
Tries to read given attribute assuming it is a SUMOReal.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; the default value if the attribute does not exist; -1 if an error occured
Definition at line 134 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::hasAttribute(), and SUMOReal.
Referenced by NLHandler::addConnection(), NLHandler::addE2Detector(), NIXMLEdgesHandler::addEdge(), NIImporter_SUMO::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addLane(), NIImporter_SUMO::addLane(), NLHandler::addPOI(), MSRouteHandler::addStop(), NLHandler::addSuccLane(), NLHandler::beginE3Detector(), NIXMLTypesHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), GUISettingsHandler::myStartElement(), MSRouteHandler::openRoute(), RORDLoader_SUMOBase::startRoute(), and NIXMLEdgesHandler::tryGetPosition().
SUMOTime SUMOSAXAttributes::getOptSUMOTimeReporting (int attr, const char * objectid, bool & ok, SUMOTime defaultValue, bool report = true) const [inherited]
Tries to read given attribute assuming it is a SUMOTime.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
In dependence to the used time representation, either getIntReporting or getSUMORealReporting is used.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; the default value if the attribute does not exist; -1 if an error occured
Definition at line 278 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::getOptIntReporting(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addPhase(), NLHandler::addRouteProbeDetector(), MSRouteHandler::addStop(), NLHandler::beginE3Detector(), NLHandler::initTrafficLightLogic(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::myStartElement(), GUISettingsHandler::myStartElement(), NLHandler::openWAUT(), RORDGenerator_ODAmounts::parseFlowAmountDef(), and RORDGenerator_ODAmounts::parseInterval().
std::string SUMOSAXAttributesImpl_Xerces::getString (int id) const throw (EmptyData) [virtual]
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2str. If the attribute is ==0, TplConvert<XMLCh>::_2str throws an EmptyData-exception which is passed.
Parameters:
[in] id The id of the attribute to return the value of
Returns:
The attribute's value as a string, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
Implements SUMOSAXAttributes.
Definition at line 100 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvert< E >::_2str().
Referenced by GenericSAXHandler::startElement().
std::string SUMOSAXAttributes::getStringReporting (int attr, const char * objectid, bool & ok, bool report = true) const [inherited]
Tries to read given attribute assuming it is a string.
If an error occurs (the attribute is not there, it's empty), "ok" is set to false and an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and not empty; "" if an error occured
Definition at line 204 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::getString(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addConnection(), NIImporter_SUMO::addConnection(), NLHandler::addDistrict(), NLHandler::addDistrictEdge(), NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIXMLEdgesHandler::addEdge(), NIImporter_SUMO::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NIXMLNodesHandler::addJoinCluster(), NIXMLNodesHandler::addJoinExclusion(), NIImporter_SUMO::addJunction(), NLHandler::addLane(), NIImporter_SUMO::addLane(), NLHandler::addLogicItem(), NIXMLNodesHandler::addNode(), NLHandler::addParam(), NLHandler::addPhase(), NIImporter_SUMO::addPhase(), NLHandler::addPOI(), NLHandler::addPoly(), NLHandler::addRequest(), NLHandler::addRouteProbeDetector(), MSRouteHandler::addStop(), NIImporter_SUMO::addSuccEdge(), NLHandler::addSuccLane(), NIImporter_SUMO::addSuccLane(), ROJTRTurnDefLoader::addToEdge(), NLHandler::addVTypeProbeDetector(), NLHandler::addWAUTJunction(), NLHandler::addWAUTSwitch(), NLHandler::beginE3Detector(), NLHandler::beginEdgeParsing(), ROJTRTurnDefLoader::beginFromEdge(), SUMOVehicleParserHelper::beginVTypeParsing(), NLTriggerBuilder::buildVaporizer(), NIXMLEdgesHandler::deleteEdge(), NIXMLNodesHandler::deleteNode(), RORDLoader_TripDefs::getEdge(), NLHandler::initJunctionLogic(), NLHandler::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NIImporter_SUMO::loadLocation(), ROJTRTurnDefLoader::myStartElement(), RODFDetectorHandler::myStartElement(), PCTypeDefHandler::myStartElement(), PCLoaderXML::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_MATSim::NodesHandler::myStartElement(), MSRouteHandler::myStartElement(), GUISettingsHandler::myStartElement(), ODDistrictHandler::openDistrict(), NLHandler::openJunction(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), NLHandler::openSucc(), MSRouteHandler::openVehicleTypeDistribution(), NLHandler::openWAUT(), SUMOVehicleParserHelper::parseCommonAttributes(), RONetHandler::parseConnectedEdge(), RONetHandler::parseConnectingEdge(), RONetHandler::parseConnection(), ODDistrictHandler::parseConnection(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), RONetHandler::parseDistrict(), RONetHandler::parseDistrictEdge(), RONetHandler::parseEdge(), SUMOVehicleParserHelper::parseFlowAttributes(), RONetHandler::parseJunction(), RONetHandler::parseLane(), SUMOVehicleParserHelper::parseVehicleAttributes(), NIXMLNodesHandler::processTrafficLightDefinitions(), NIXMLTrafficLightsHandler::removeTlConnection(), NIXMLTrafficLightsHandler::retrieveEdge(), NLHandler::setLocation(), NIXMLEdgesHandler::setNodes(), RORDLoader_SUMOBase::startAlternative(), RORDLoader_SUMOBase::startRoute(), and NIXMLEdgesHandler::tryGetLaneSpread().
std::string SUMOSAXAttributesImpl_Xerces::getStringSecure (const std::string & id, const std::string & def) const [virtual]
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. If the attribute is ==0, TplConvert<XMLCh>::_2strSec returns the default value.
Parameters:
[in] id The name of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns:
The attribute's value as a string, if it could be read and parsed
Implements SUMOSAXAttributes.
Definition at line 174 of file SUMOSAXAttributesImpl_Xerces.cpp.
References myAttrs.
std::string SUMOSAXAttributesImpl_Xerces::getStringSecure (int id, const std::string & def) const throw (EmptyData) [virtual]
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2strSec. If the attribute is ==0, TplConvert<XMLCh>::_2strSec returns the default value.
Parameters:
[in] id The id of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns:
The attribute's value as a string, if it could be read and parsed
Exceptions:
EmptyData If the attribute is not known or the attribute value is an empty string
Implements SUMOSAXAttributes.
Definition at line 117 of file SUMOSAXAttributesImpl_Xerces.cpp.
References TplConvertSec< E >::_2strSec().
SUMOReal SUMOSAXAttributes::getSUMORealReporting (int attr, const char * objectid, bool & ok, bool report = true) const [inherited]
Tries to read given attribute assuming it is a SUMOReal.
If an error occurs (the attribute is not there, it is not numeric), "ok" is set to false and an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; -1 if an error occured
Definition at line 108 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::hasAttribute(), and SUMOReal.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIXMLEdgesHandler::addEdge(), NLHandler::addInstantE1Detector(), NLHandler::addLane(), NIXMLEdgesHandler::addLane(), NIImporter_SUMO::addLane(), NIXMLNodesHandler::addNode(), NIImporter_SUMO::addPhase(), NIXMLEdgesHandler::addSplit(), ROJTRTurnDefLoader::addToEdge(), SUMOVehicleParserHelper::beginVTypeParsing(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), SAXWeightsHandler::myStartElement(), RODFDetectorHandler::myStartElement(), PCLoaderXML::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_MATSim::NodesHandler::myStartElement(), GUISettingsHandler::myStartElement(), NLHandler::openJunction(), ODDistrictHandler::parseConnection(), SUMOVehicleParserHelper::parseFlowAttributes(), RONetHandler::parseJunction(), RONetHandler::parseLane(), SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVTypeEmbedded(), NIImporter_SUMO::readPosition(), and RORDLoader_SUMOBase::startRoute().
SUMOTime SUMOSAXAttributes::getSUMOTimeReporting (int attr, const char * objectid, bool & ok, bool report = true) const [inherited]
Tries to read given attribute assuming it is a SUMOTime.
If an error occurs (the attribute is not there, it is not numeric), "ok" is set to false and an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
In dependence to the used time representation, either getIntReporting or getSUMORealReporting is used.
Parameters:
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns:
The read value if given and correct; -1 if an error occured
Definition at line 248 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addPhase(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::addWAUTSwitch(), NLHandler::beginE3Detector(), NLTriggerBuilder::buildVaporizer(), RORDLoader_TripDefs::myStartElement(), ROJTRTurnDefLoader::myStartElement(), MSLaneSpeedTrigger::myStartElement(), SUMOVehicleParserHelper::parseFlowAttributes(), and SUMOVehicleParserHelper::parseVehicleAttributes().
bool SUMOSAXAttributesImpl_Xerces::hasAttribute (const std::string & id) const [virtual]
Returns the information whether the named attribute is within the current list.
Implements SUMOSAXAttributes.
Definition at line 165 of file SUMOSAXAttributesImpl_Xerces.cpp.
References myAttrs.
bool SUMOSAXAttributesImpl_Xerces::hasAttribute (int id) const [virtual]
Returns the information whether the named (by its enum-value) attribute is within the current list.
Parameters:
[in] id The id of the searched attribute
Returns:
Whether the attribute is within the attributes
Implements SUMOSAXAttributes.
Definition at line 65 of file SUMOSAXAttributesImpl_Xerces.cpp.
References myAttrs, and myPredefinedTags.
SUMOSAXAttributesImpl_Xerces& SUMOSAXAttributesImpl_Xerces::operator= (const SUMOSAXAttributesImpl_Xerces & src) [private]
Invalidated assignment operator.
void SUMOSAXAttributes::parseStringVector (const std::string & def, std::vector< std::string > & into) [static, inherited]
Splits the given string.
Spaces, ",", and ";" are assumed to be separator characters. Though, in the case a "," or a ";" occurs, a warning is generated (once).
Parameters:
[in] def The string to split
[out] into The vector to fill
Definition at line 355 of file SUMOSAXAttributes.cpp.
References StringTokenizer::hasNext(), SUMOSAXAttributes::myHaveInformedAboutDeprecatedDivider, StringTokenizer::next(), and WRITE_WARNING.
Referenced by NIXMLEdgesHandler::addLane(), NIXMLEdgesHandler::addSplit(), NLTriggerBuilder::parseAndBuildBusStop(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), and NIXMLNodesHandler::processTrafficLightDefinitions().
Field Documentation
const std::string SUMOSAXAttributes::ENCODING = " encoding=\"UTF-8\"" [static, inherited]
The encoding of parsed strings.
Definition at line 481 of file SUMOSAXAttributes.h.
Referenced by PCPolyContainer::save(), OptionsCont::writeConfiguration(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), OptionsCont::writeSchema(), and NWWriter_XML::writeTrafficLights().
const Attributes& SUMOSAXAttributesImpl_Xerces::myAttrs [private]
The encapsulated attributes.
Definition at line 288 of file SUMOSAXAttributesImpl_Xerces.h.
Referenced by getAttributeValueSecure(), getStringSecure(), and hasAttribute().
const AttrMap& SUMOSAXAttributesImpl_Xerces::myPredefinedTags [private]
Map of attribute ids to their xerces-representation.
Definition at line 293 of file SUMOSAXAttributesImpl_Xerces.h.
Referenced by getAttributeValueSecure(), and hasAttribute().
const std::map<int, std::string>& SUMOSAXAttributesImpl_Xerces::myPredefinedTagsMML [private]
Map of attribute ids to their (readable) string-representation.
Definition at line 296 of file SUMOSAXAttributesImpl_Xerces.h.
Referenced by getName().
The documentation for this class was generated from the following files:
SUMOSAXAttributesImpl_Xerces.h
SUMOSAXAttributesImpl_Xerces.cpp