SUMO - Simulation of Urban MObility: MSVTypeProbe Class Reference
MSVTypeProbe Class Reference
Writes positions of vehicles that have a certain (named) type.
#include <MSVTypeProbe.h>
Public Member Functions
const std::string & getID () const
Returns the id.
MSVTypeProbe (const std::string &id, const std::string &vType, OutputDevice &od, SUMOTime frequency)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MSVTypeProbe ()
Destructor.
Derived from Command
SUMOTime execute (SUMOTime currentTime)
Writes values into the given stream.
Protected Attributes
std::string myID
The name of the object.
Private Member Functions
MSVTypeProbe (const MSVTypeProbe &)
Invalidated copy constructor.
MSVTypeProbe & operator= (const MSVTypeProbe &)
Invalidated assignment operator.
Private Attributes
SUMOTime myFrequency
The frequency of reporting.
OutputDevice & myOutputDevice
The device to write into.
std::string myVType
The id of the vehicle type vehicles must have to be reported.
Detailed Description
Writes positions of vehicles that have a certain (named) type.
This device allows to log the data of all running vehicles of the specified vehicle type, i.e. vehicle id, edge, lane=, position on lane, x/y coordinates and speed.
A frequency can be specified to generate the output in certain intervals, (e.g. every 10 seconds).
See also:
Command
Named
Definition at line 60 of file MSVTypeProbe.h.
Constructor & Destructor Documentation
MSVTypeProbe::MSVTypeProbe (const std::string & id, const std::string & vType, OutputDevice & od, SUMOTime frequency)
Constructor.
Parameters:
[in] id The id of the vehicle type probe
[in] vType The vtype of which vehicles to report must be ("" for all vehicles)
[in] od The output device to write into
[in] frequency The output frequency [ms]
Definition at line 50 of file MSVTypeProbe.cpp.
References MSEventControl::ADAPT_AFTER_EXECUTION, MSEventControl::addEvent(), MSNet::getEndOfTimestepEvents(), MSNet::getInstance(), myOutputDevice, and OutputDevice::writeXMLHeader().
MSVTypeProbe::~MSVTypeProbe () [virtual]
Destructor.
Definition at line 59 of file MSVTypeProbe.cpp.
MSVTypeProbe::MSVTypeProbe (const MSVTypeProbe &) [private]
Invalidated copy constructor.
Member Function Documentation
SUMOTime MSVTypeProbe::execute (SUMOTime currentTime) [virtual]
Writes values into the given stream.
This method goes through all runing vehicles; if a vehicle has a type with the same id as the wished one, it is reported. When the type "" is wished, all vehicles are reported
Parameters:
[in] currentTime The current simulation time (unused)
Returns:
Always myFrequency (time till next output)
See also:
Command
Implements Command.
Definition at line 64 of file MSVTypeProbe.cpp.
References GeoConvHelper::cartesian2geo(), GEO_OUTPUT_ACCURACY, GeoConvHelper::getFinal(), MSBaseVehicle::getID(), MSVehicleType::getID(), Named::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSLane::getShape(), MSVehicle::getSpeed(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSVehicle::isOnRoad(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), myFrequency, myOutputDevice, myVType, PositionVector::positionAtLengthPosition(), OutputDevice::setPrecision(), time2string(), Position::x(), and Position::y().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
MSVTypeProbe& MSVTypeProbe::operator= (const MSVTypeProbe &) [private]
Invalidated assignment operator.
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
Field Documentation
SUMOTime MSVTypeProbe::myFrequency [private]
The frequency of reporting.
Definition at line 103 of file MSVTypeProbe.h.
Referenced by execute().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
OutputDevice& MSVTypeProbe::myOutputDevice [private]
The device to write into.
Definition at line 100 of file MSVTypeProbe.h.
Referenced by execute(), and MSVTypeProbe().
std::string MSVTypeProbe::myVType [private]
The id of the vehicle type vehicles must have to be reported.
Definition at line 97 of file MSVTypeProbe.h.
Referenced by execute().
The documentation for this class was generated from the following files:
MSVTypeProbe.h
MSVTypeProbe.cpp