SUMO - Simulation of Urban MObility: FXEX::FXSevenSegment Class Reference
FXEX::FXSevenSegment Class Reference
#include <FXSevenSegment.h>
Public Member Functions
FXSevenSegment (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=FRAME_NONE, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
create a seven segment display
FXColor getBgColor () const
virtual FXint getDefaultHeight ()
Return minimum height.
virtual FXint getDefaultWidth ()
Return minimum width.
FXColor getFgColor () const
FXint getGroove () const
FXint getHorizontal () const
FXchar getText () const
get the text on the display
FXint getThickness () const
FXint getVertical () const
virtual void load (FXStream &store)
load resources
long onCmdGetIntValue (FXObject *, FXSelector, void *)
long onCmdGetStringValue (FXObject *, FXSelector, void *)
long onCmdSetIntValue (FXObject *, FXSelector, void *)
long onCmdSetStringValue (FXObject *, FXSelector, void *)
long onCmdSetValue (FXObject *, FXSelector, void *)
long onPaint (FXObject *, FXSelector, void *)
long onQueryHelp (FXObject *, FXSelector, void *)
long onQueryTip (FXObject *, FXSelector, void *)
virtual void save (FXStream &store) const
save resources
void setBgColor (const FXColor clr)
get/set background color
void setFgColor (const FXColor clr)
get/set foreground color
void setGroove (const FXint width)
get/set groove thickness
void setHorizontal (const FXint len)
get/set horizontal segment length
void setText (const FXchar val)
set the text on the display
void setThickness (const FXint width)
get/set segment thickness
void setVertical (const FXint len)
get/set vertical segment length
virtual ~FXSevenSegment ()
dtor
Protected Member Functions
void drawBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
virtual void drawFigure (FXDCWindow &dc, FXchar figure)
void drawLeftBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawLeftTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawMiddleSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawRightBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawRightTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawSegments (FXDCWindow &dc, FXbool s1, FXbool s2, FXbool s3, FXbool s4, FXbool s5, FXbool s6, FXbool s7)
void drawTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
FXSevenSegment ()
Private Member Functions
void checkSize ()
Private Attributes
FXColor bgcolor
FXColor fgcolor
FXint groove
FXint hsl
FXint st
FXchar value
FXint vsl
Detailed Description
Seven-segment (eg LCD/watch style) widget
Definition at line 45 of file FXSevenSegment.h.
Constructor & Destructor Documentation
FXEX::FXSevenSegment::FXSevenSegment () [inline, protected]
Definition at line 62 of file FXSevenSegment.h.
FXEX::FXSevenSegment::FXSevenSegment (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = FRAME_NONE, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD)
create a seven segment display
Definition at line 72 of file FXSevenSegment.cpp.
virtual FXEX::FXSevenSegment::~FXSevenSegment () [inline, virtual]
dtor
Definition at line 150 of file FXSevenSegment.h.
Member Function Documentation
void FXEX::FXSevenSegment::checkSize () [private]
Definition at line 377 of file FXSevenSegment.cpp.
References groove, hsl, st, and vsl.
Referenced by setGroove(), setHorizontal(), setThickness(), and setVertical().
void FXEX::FXSevenSegment::drawBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 558 of file FXSevenSegment.cpp.
References hsl, and st.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawFigure (FXDCWindow & dc, FXchar figure) [protected, virtual]
Definition at line 219 of file FXSevenSegment.cpp.
References drawSegments().
Referenced by onPaint().
void FXEX::FXSevenSegment::drawLeftBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 532 of file FXSevenSegment.cpp.
References st, and vsl.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawLeftTopSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 489 of file FXSevenSegment.cpp.
References st, and vsl.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawMiddleSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 515 of file FXSevenSegment.cpp.
References hsl, and st.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawRightBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 545 of file FXSevenSegment.cpp.
References st, and vsl.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawRightTopSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 502 of file FXSevenSegment.cpp.
References st, and vsl.
Referenced by drawSegments().
void FXEX::FXSevenSegment::drawSegments (FXDCWindow & dc, FXbool s1, FXbool s2, FXbool s3, FXbool s4, FXbool s5, FXbool s6, FXbool s7) [protected]
Definition at line 408 of file FXSevenSegment.cpp.
References drawBottomSegment(), drawLeftBottomSegment(), drawLeftTopSegment(), drawMiddleSegment(), drawRightBottomSegment(), drawRightTopSegment(), drawTopSegment(), groove, hsl, st, and vsl.
Referenced by drawFigure().
void FXEX::FXSevenSegment::drawTopSegment (FXDCWindow & dc, FXshort x, FXshort y) [protected]
Definition at line 476 of file FXSevenSegment.cpp.
References hsl, and st.
Referenced by drawSegments().
FXColor FXEX::FXSevenSegment::getBgColor () const [inline]
Definition at line 109 of file FXSevenSegment.h.
References bgcolor.
Referenced by FXEX::FXLCDLabel::getBgColor(), FXEX::FXLCDLabel::onPaint(), and FXEX::FXLCDLabel::setBgColor().
FXint FXEX::FXSevenSegment::getDefaultHeight () [virtual]
Return minimum height.
Definition at line 84 of file FXSevenSegment.cpp.
References groove, and vsl.
FXint FXEX::FXSevenSegment::getDefaultWidth () [virtual]
Return minimum width.
Definition at line 79 of file FXSevenSegment.cpp.
References groove, and hsl.
FXColor FXEX::FXSevenSegment::getFgColor () const [inline]
Definition at line 103 of file FXSevenSegment.h.
References fgcolor.
Referenced by FXEX::FXLCDLabel::getFgColor(), FXEX::FXLCDLabel::onPaint(), and FXEX::FXLCDLabel::setFgColor().
FXint FXEX::FXSevenSegment::getGroove () const [inline]
Definition at line 133 of file FXSevenSegment.h.
References groove.
Referenced by FXEX::FXLCDLabel::getGroove(), and FXEX::FXLCDLabel::setGroove().
FXint FXEX::FXSevenSegment::getHorizontal () const [inline]
Definition at line 115 of file FXSevenSegment.h.
References hsl.
Referenced by FXEX::FXLCDLabel::getHorizontal(), and FXEX::FXLCDLabel::setHorizontal().
FXchar FXEX::FXSevenSegment::getText () const [inline]
get the text on the display
Definition at line 97 of file FXSevenSegment.h.
References value.
FXint FXEX::FXSevenSegment::getThickness () const [inline]
Definition at line 127 of file FXSevenSegment.h.
References st.
Referenced by FXEX::FXLCDLabel::getThickness(), and FXEX::FXLCDLabel::setThickness().
FXint FXEX::FXSevenSegment::getVertical () const [inline]
Definition at line 121 of file FXSevenSegment.h.
References vsl.
Referenced by FXEX::FXLCDLabel::getVertical(), and FXEX::FXLCDLabel::setVertical().
void FXEX::FXSevenSegment::load (FXStream & store) [virtual]
load resources
Definition at line 582 of file FXSevenSegment.cpp.
References bgcolor, fgcolor, groove, hsl, st, value, and vsl.
long FXEX::FXSevenSegment::onCmdGetIntValue (FXObject * sender, FXSelector , void *)
Definition at line 177 of file FXSevenSegment.cpp.
References ASCII_ZERO, and value.
long FXEX::FXSevenSegment::onCmdGetStringValue (FXObject * sender, FXSelector , void *)
Definition at line 203 of file FXSevenSegment.cpp.
References value.
long FXEX::FXSevenSegment::onCmdSetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 190 of file FXSevenSegment.cpp.
References ASCII_ZERO, and setText().
long FXEX::FXSevenSegment::onCmdSetStringValue (FXObject * , FXSelector , void * ptr)
Definition at line 210 of file FXSevenSegment.cpp.
References setText().
long FXEX::FXSevenSegment::onCmdSetValue (FXObject * , FXSelector , void * ptr)
Definition at line 168 of file FXSevenSegment.cpp.
References setText().
long FXEX::FXSevenSegment::onPaint (FXObject * , FXSelector , void * ptr)
Definition at line 156 of file FXSevenSegment.cpp.
References bgcolor, drawFigure(), fgcolor, and value.
long FXEX::FXSevenSegment::onQueryHelp (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 602 of file FXSevenSegment.cpp.
long FXEX::FXSevenSegment::onQueryTip (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 594 of file FXSevenSegment.cpp.
void FXEX::FXSevenSegment::save (FXStream & store) const [virtual]
save resources
Definition at line 571 of file FXSevenSegment.cpp.
References bgcolor, fgcolor, groove, hsl, st, value, and vsl.
void FXEX::FXSevenSegment::setBgColor (const FXColor clr)
get/set background color
Definition at line 107 of file FXSevenSegment.cpp.
References bgcolor.
Referenced by FXEX::FXLCDLabel::setBgColor().
void FXEX::FXSevenSegment::setFgColor (const FXColor clr)
get/set foreground color
Definition at line 98 of file FXSevenSegment.cpp.
References fgcolor.
Referenced by FXEX::FXLCDLabel::setFgColor().
void FXEX::FXSevenSegment::setGroove (const FXint width)
get/set groove thickness
Definition at line 146 of file FXSevenSegment.cpp.
References checkSize(), and groove.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setGroove().
void FXEX::FXSevenSegment::setHorizontal (const FXint len)
get/set horizontal segment length
Definition at line 116 of file FXSevenSegment.cpp.
References checkSize(), and hsl.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setHorizontal().
void FXEX::FXSevenSegment::setText (const FXchar val)
set the text on the display
Definition at line 89 of file FXSevenSegment.cpp.
References value.
Referenced by FXEX::FXLCDLabel::drawString(), onCmdSetIntValue(), onCmdSetStringValue(), and onCmdSetValue().
void FXEX::FXSevenSegment::setThickness (const FXint width)
get/set segment thickness
Definition at line 136 of file FXSevenSegment.cpp.
References checkSize(), and st.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setThickness().
void FXEX::FXSevenSegment::setVertical (const FXint len)
get/set vertical segment length
Definition at line 126 of file FXSevenSegment.cpp.
References checkSize(), and vsl.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setVertical().
Field Documentation
FXColor FXEX::FXSevenSegment::bgcolor [private]
Definition at line 52 of file FXSevenSegment.h.
Referenced by getBgColor(), load(), onPaint(), save(), and setBgColor().
FXColor FXEX::FXSevenSegment::fgcolor [private]
Definition at line 51 of file FXSevenSegment.h.
Referenced by getFgColor(), load(), onPaint(), save(), and setFgColor().
FXint FXEX::FXSevenSegment::groove [private]
Definition at line 56 of file FXSevenSegment.h.
Referenced by checkSize(), drawSegments(), getDefaultHeight(), getDefaultWidth(), getGroove(), load(), save(), and setGroove().
FXint FXEX::FXSevenSegment::hsl [private]
Definition at line 53 of file FXSevenSegment.h.
Referenced by checkSize(), drawBottomSegment(), drawMiddleSegment(), drawSegments(), drawTopSegment(), getDefaultWidth(), getHorizontal(), load(), save(), and setHorizontal().
FXint FXEX::FXSevenSegment::st [private]
Definition at line 55 of file FXSevenSegment.h.
Referenced by checkSize(), drawBottomSegment(), drawLeftBottomSegment(), drawLeftTopSegment(), drawMiddleSegment(), drawRightBottomSegment(), drawRightTopSegment(), drawSegments(), drawTopSegment(), getThickness(), load(), save(), and setThickness().
FXchar FXEX::FXSevenSegment::value [private]
Definition at line 50 of file FXSevenSegment.h.
Referenced by getText(), load(), onCmdGetIntValue(), onCmdGetStringValue(), onPaint(), save(), and setText().
FXint FXEX::FXSevenSegment::vsl [private]
Definition at line 54 of file FXSevenSegment.h.
Referenced by checkSize(), drawLeftBottomSegment(), drawLeftTopSegment(), drawRightBottomSegment(), drawRightTopSegment(), drawSegments(), getDefaultHeight(), getVertical(), load(), save(), and setVertical().
The documentation for this class was generated from the following files:
FXSevenSegment.h
FXSevenSegment.cpp