SUMO - Simulation of Urban MObility: MSInternalJunction Class Reference
MSInternalJunction Class Reference
#include <MSInternalJunction.h>
Public Types
typedef std::bitset< 64 > InnerState
Container for junction-internal lane occupation Each element of this container represents one particular junction-internal lane.
typedef std::bitset< 64 > LinkFoes
Container for link foes.
Public Member Functions
const std::vector< MSLane * > & getFoeInternalLanes (const MSLink *const srcLink) const
const std::vector< MSLink * > & getFoeLinks (const MSLink *const srcLink) const
const std::string & getID () const
Returns the id of the junction.
const Position & getPosition () const
const PositionVector & getShape () const
Returns this junction's shape.
MSInternalJunction (const std::string &id, const Position &position, const PositionVector &shape, std::vector< MSLane * > incoming, std::vector< MSLane * > internal)
Constructor.
void postloadInit ()
initialises the junction after the whole net has been loaded
virtual ~MSInternalJunction ()
Destructor.
Protected Attributes
std::vector< MSLane * > myEmptyLanes
std::vector< MSLink * > myEmptyLinks
std::string myID
The id of the junction.
std::vector< MSLane * > myIncomingLanes
list of incoming lanes
InnerState myInnerState
std::vector< MSLane * > myInternalLanes
list of incoming lanes
Position myPosition
The position of the junction.
PositionVector myShape
The shape of the junction.
Private Member Functions
MSInternalJunction (const MSInternalJunction &)
Invalidated copy constructor.
MSInternalJunction & operator= (const MSInternalJunction &)
Invalidated assignment operator.
Private Attributes
std::vector< MSLane * > myInternalLaneFoes
std::vector< MSLink * > myInternalLinkFoes
Detailed Description
A class which realises junctions that do regard any kind of a right-of-way. The rules for the right-of-way themselves are stored within the associated "MSJunctionLogic" - structure.
Definition at line 60 of file MSInternalJunction.h.
Member Typedef Documentation
typedef std::bitset<64> MSLogicJunction::InnerState [inherited]
Container for junction-internal lane occupation Each element of this container represents one particular junction-internal lane.
Definition at line 69 of file MSLogicJunction.h.
typedef std::bitset<64> MSLogicJunction::LinkFoes [inherited]
Container for link foes.
Definition at line 64 of file MSLogicJunction.h.
Constructor & Destructor Documentation
MSInternalJunction::MSInternalJunction (const std::string & id, const Position & position, const PositionVector & shape, std::vector< MSLane * > incoming, std::vector< MSLane * > internal)
Constructor.
Parameters:
[in] id The id of the junction
[in] position The position of the junction
[in] shape The shape of the junction
[in] incoming The incoming lanes
[in] internal The internal lanes
Definition at line 50 of file MSInternalJunction.cpp.
MSInternalJunction::~MSInternalJunction () [virtual]
Destructor.
Definition at line 59 of file MSInternalJunction.cpp.
MSInternalJunction::MSInternalJunction (const MSInternalJunction &) [private]
Invalidated copy constructor.
Member Function Documentation
const std::vector<MSLane*>& MSInternalJunction::getFoeInternalLanes (const MSLink *const srcLink) const [inline, virtual]
Reimplemented from MSJunction.
Definition at line 84 of file MSInternalJunction.h.
References myInternalLaneFoes, and UNUSED_PARAMETER.
const std::vector<MSLink*>& MSInternalJunction::getFoeLinks (const MSLink *const srcLink) const [inline, virtual]
Reimplemented from MSJunction.
Definition at line 79 of file MSInternalJunction.h.
References myInternalLinkFoes, and UNUSED_PARAMETER.
const std::string & MSJunction::getID () const [inherited]
Returns the id of the junction.
Definition at line 68 of file MSJunction.cpp.
References MSJunction::myID.
const Position & MSJunction::getPosition () const [inherited]
returns the junction's position
Definition at line 58 of file MSJunction.cpp.
References MSJunction::myPosition.
Referenced by GUIJunctionWrapper::drawGL(), GUINet::getJunctionPosition(), GUIJunctionWrapper::GUIJunctionWrapper(), and TraCIServerAPI_Junction::processGet().
const PositionVector& MSJunction::getShape () const [inline, inherited]
Returns this junction's shape.
Returns:
The shape of this junction
Definition at line 83 of file MSJunction.h.
References MSJunction::myShape.
Referenced by GUIJunctionWrapper::drawGL(), and GUIJunctionWrapper::GUIJunctionWrapper().
MSInternalJunction& MSInternalJunction::operator= (const MSInternalJunction &) [private]
Invalidated assignment operator.
void MSInternalJunction::postloadInit () [virtual]
initialises the junction after the whole net has been loaded
Reimplemented from MSLogicJunction.
Definition at line 63 of file MSInternalJunction.cpp.
References MSLane::getLinkCont(), MSLogicJunction::myIncomingLanes, myInternalLaneFoes, MSLogicJunction::myInternalLanes, and myInternalLinkFoes.
Field Documentation
std::vector<MSLane*> MSJunction::myEmptyLanes [protected, inherited]
Definition at line 106 of file MSJunction.h.
Referenced by MSJunction::getFoeInternalLanes().
std::vector<MSLink*> MSJunction::myEmptyLinks [protected, inherited]
Definition at line 105 of file MSJunction.h.
Referenced by MSJunction::getFoeLinks().
std::string MSJunction::myID [protected, inherited]
The id of the junction.
Definition at line 97 of file MSJunction.h.
Referenced by MSJunction::getID().
std::vector<MSLane*> MSLogicJunction::myIncomingLanes [protected, inherited]
list of incoming lanes
Definition at line 92 of file MSLogicJunction.h.
Referenced by MSRightOfWayJunction::postloadInit(), and postloadInit().
InnerState MSLogicJunction::myInnerState [protected, inherited]
Current inner state
Definition at line 100 of file MSLogicJunction.h.
Referenced by MSRightOfWayJunction::postloadInit().
std::vector<MSLane*> MSInternalJunction::myInternalLaneFoes [private]
Definition at line 92 of file MSInternalJunction.h.
Referenced by getFoeInternalLanes(), and postloadInit().
std::vector<MSLane*> MSLogicJunction::myInternalLanes [protected, inherited]
list of incoming lanes
Definition at line 96 of file MSLogicJunction.h.
Referenced by MSRightOfWayJunction::postloadInit(), and postloadInit().
std::vector<MSLink*> MSInternalJunction::myInternalLinkFoes [private]
Definition at line 91 of file MSInternalJunction.h.
Referenced by getFoeLinks(), and postloadInit().
Position MSJunction::myPosition [protected, inherited]
The position of the junction.
Definition at line 100 of file MSJunction.h.
Referenced by MSJunction::getPosition().
PositionVector MSJunction::myShape [protected, inherited]
The shape of the junction.
Definition at line 103 of file MSJunction.h.
Referenced by MSJunction::getShape().
The documentation for this class was generated from the following files:
MSInternalJunction.h
MSInternalJunction.cpp