SUMO - Simulation of Urban MObility: NIVisumTL Class Reference
NIVisumTL Class Reference
Intermediate class for storing visum traffic lights during their import.
#include <NIVisumTL.h>
Data Structures
class Phase
class SignalGroup
class TimePeriod
Timeperiod with starttime and endtime.
Public Types
typedef std::vector< NBNode * > NodeVector
typedef std::map< std::string,
Phase * > PhaseMap
typedef std::map< std::string,
SignalGroup * > SignalGroupMap
Public Member Functions
void AddPhase (const std::string Name, SUMOTime StartTime, SUMOTime EndTime)
void AddSignalGroup (const std::string Name, SUMOTime StartTime, SUMOTime EndTime)
void build (NBTrafficLightLogicCont &tlc)
SUMOTime GetCycleTime ()
SUMOTime GetIntermediateTime ()
SUMOTime GetName ()
NodeVector * GetNodes ()
bool GetPhaseDefined ()
PhaseMap * GetPhases ()
SignalGroup * GetSignalGroup (const std::string Name)
SignalGroupMap * GetSignalGroups ()
NIVisumTL (const std::string &Name, SUMOTime CycleTime, SUMOTime IntermediateTime, bool PhaseDefined)
NIVisumTL ()
void SetCycleTime (SUMOTime CylcleTime)
void SetIntermediateTime (SUMOTime IntermediateTime)
void SetPhaseDefined (bool PhaseDefined)
~NIVisumTL ()
Private Attributes
SUMOTime myCycleTime
SUMOTime myIntermediateTime
std::string myName
NodeVector myNodes
bool myPhaseDefined
PhaseMap myPhases
SignalGroupMap mySignalGroups
Detailed Description
Intermediate class for storing visum traffic lights during their import.
Definition at line 50 of file NIVisumTL.h.
Member Typedef Documentation
typedef std::vector<NBNode*> NIVisumTL::NodeVector
Definition at line 78 of file NIVisumTL.h.
typedef std::map<std::string, Phase*> NIVisumTL::PhaseMap
Definition at line 79 of file NIVisumTL.h.
typedef std::map<std::string, SignalGroup*> NIVisumTL::SignalGroupMap
Definition at line 100 of file NIVisumTL.h.
Constructor & Destructor Documentation
NIVisumTL::NIVisumTL ()
Definition at line 125 of file NIVisumTL.cpp.
NIVisumTL::NIVisumTL (const std::string & Name, SUMOTime CycleTime, SUMOTime IntermediateTime, bool PhaseDefined)
Definition at line 128 of file NIVisumTL.cpp.
NIVisumTL::~NIVisumTL ()
Definition at line 133 of file NIVisumTL.cpp.
References myPhases, and mySignalGroups.
Member Function Documentation
void NIVisumTL::AddPhase (const std::string Name, SUMOTime StartTime, SUMOTime EndTime)
Definition at line 190 of file NIVisumTL.cpp.
References myPhases.
void NIVisumTL::AddSignalGroup (const std::string Name, SUMOTime StartTime, SUMOTime EndTime)
Definition at line 186 of file NIVisumTL.cpp.
References mySignalGroups.
void NIVisumTL::build (NBTrafficLightLogicCont & tlc)
Definition at line 199 of file NIVisumTL.cpp.
References NBLoadedTLDef::addSignalGroup(), NBLoadedTLDef::addSignalGroupPhaseBegin(), NBLoadedTLDef::addToSignalGroup(), NIVisumTL::SignalGroup::GetConnections(), NIVisumTL::TimePeriod::GetEndTime(), Named::getID(), NIVisumTL::SignalGroup::GetPhases(), NIVisumTL::TimePeriod::GetStartTime(), NBTrafficLightLogicCont::insert(), myCycleTime, myIntermediateTime, myNodes, myPhaseDefined, mySignalGroups, NBLoadedTLDef::setCycleDuration(), NBLoadedTLDef::setSignalYellowTimes(), NBTrafficLightDefinition::TLCOLOR_GREEN, and NBTrafficLightDefinition::TLCOLOR_RED.
SUMOTime NIVisumTL::GetCycleTime ()
Definition at line 145 of file NIVisumTL.cpp.
References myCycleTime.
SUMOTime NIVisumTL::GetIntermediateTime ()
Definition at line 150 of file NIVisumTL.cpp.
References myIntermediateTime.
SUMOTime NIVisumTL::GetName ()
NIVisumTL::NodeVector * NIVisumTL::GetNodes ()
Definition at line 160 of file NIVisumTL.cpp.
References myNodes.
bool NIVisumTL::GetPhaseDefined ()
Definition at line 155 of file NIVisumTL.cpp.
References myPhaseDefined.
NIVisumTL::PhaseMap * NIVisumTL::GetPhases ()
Definition at line 166 of file NIVisumTL.cpp.
References myPhases.
Referenced by NIImporter_VISUM::parse_SignalGroupsToPhases().
NIVisumTL::SignalGroup * NIVisumTL::GetSignalGroup (const std::string Name)
Definition at line 194 of file NIVisumTL.cpp.
References mySignalGroups.
Referenced by NIImporter_VISUM::parse_SignalGroupsToPhases().
NIVisumTL::SignalGroupMap * NIVisumTL::GetSignalGroups ()
Definition at line 170 of file NIVisumTL.cpp.
References mySignalGroups.
void NIVisumTL::SetCycleTime (SUMOTime CylcleTime)
Definition at line 174 of file NIVisumTL.cpp.
References myCycleTime.
void NIVisumTL::SetIntermediateTime (SUMOTime IntermediateTime)
Definition at line 178 of file NIVisumTL.cpp.
References myIntermediateTime.
void NIVisumTL::SetPhaseDefined (bool PhaseDefined)
Definition at line 182 of file NIVisumTL.cpp.
References myPhaseDefined.
Field Documentation
SUMOTime NIVisumTL::myCycleTime [private]
Definition at line 132 of file NIVisumTL.h.
Referenced by build(), GetCycleTime(), and SetCycleTime().
SUMOTime NIVisumTL::myIntermediateTime [private]
Definition at line 135 of file NIVisumTL.h.
Referenced by build(), GetIntermediateTime(), and SetIntermediateTime().
std::string NIVisumTL::myName [private]
Definition at line 129 of file NIVisumTL.h.
NodeVector NIVisumTL::myNodes [private]
Definition at line 141 of file NIVisumTL.h.
Referenced by build(), and GetNodes().
bool NIVisumTL::myPhaseDefined [private]
Definition at line 138 of file NIVisumTL.h.
Referenced by build(), GetPhaseDefined(), and SetPhaseDefined().
PhaseMap NIVisumTL::myPhases [private]
Definition at line 144 of file NIVisumTL.h.
Referenced by AddPhase(), GetPhases(), and ~NIVisumTL().
SignalGroupMap NIVisumTL::mySignalGroups [private]
Definition at line 147 of file NIVisumTL.h.
Referenced by AddSignalGroup(), build(), GetSignalGroup(), GetSignalGroups(), and ~NIVisumTL().
The documentation for this class was generated from the following files:
NIVisumTL.h
NIVisumTL.cpp