SUMO - Simulation of Urban MObility: GUIParameterTableItem< T > Class Template Reference
GUIParameterTableItem< T > Class Template Reference
Instance of a single line in a parameter window.
#include <GUIParameterTableItem.h>
Public Member Functions
bool dynamic () const
Returns the information whether this item may change.
const std::string & getName () const
Returns the name of this value.
ValueSource< T > * getSourceCopy () const
Returns a copy of the source if the value is dynamic.
ValueSource< SUMOReal > * getSUMORealSourceCopy () const
Returns a SUMOReal-typed copy of the source if the value is dynamic.
GUIParameterTableItem (FXTable *table, unsigned pos, const std::string &name, bool dynamic, std::string value)
Constructor for string-typed, non-changing (static) values.
GUIParameterTableItem (FXTable *table, unsigned pos, const std::string &name, bool dynamic, T value)
Constructor for non-changing (static) values.
GUIParameterTableItem (FXTable *table, unsigned pos, const std::string &name, bool dynamic, ValueSource< T > *src)
Constructor for changing (dynamic) values.
void init (bool dynamic, std::string value)
Initialises the line.
void update ()
Resets the value if it's dynamic.
~GUIParameterTableItem ()
Destructor.
Private Attributes
bool myAmDynamic
Information whether the value may change.
std::string myName
The name of this value.
ValueSource< T > * mySource
The source to gain new values from; this source is==0 if the values are not dynamic.
FXTable * myTable
The table this entry belongs to.
FXint myTablePosition
The position within the table.
T myValue
A backup of the value to avoid the redrawing when nothing has changed.
Detailed Description
template<class T>
class GUIParameterTableItem< T >
Instance of a single line in a parameter window.
This class represents a single item of a parameter table and is an implementation of the GUIParameterTableItemInterface that allows different value-types.
As some values may change over the simulation, this class holds the information whether they change and how to ask for new values if they do.
See also:
GUIParameterTracker
GUIParameterTableItemInterface
Definition at line 120 of file GUIParameterTableItem.h.
Constructor & Destructor Documentation
template<class T> GUIParameterTableItem< T >::GUIParameterTableItem (FXTable * table, unsigned pos, const std::string & name, bool dynamic, ValueSource< T > * src) [inline]
Constructor for changing (dynamic) values.
Parameters:
[in] table The table this item belongs to
[in] pos The row of the table this item fills
[in] name The name of the represented value
[in] dynamic Information whether this value changes over time
[in] src The value source
Todo:
Consider using a reference to the table
Check whether the name should be stored in GUIParameterTableItemInterface
Definition at line 132 of file GUIParameterTableItem.h.
References ValueSource< T >::getValue(), and GUIParameterTableItem< T >::init().
template<class T> GUIParameterTableItem< T >::GUIParameterTableItem (FXTable * table, unsigned pos, const std::string & name, bool dynamic, T value) [inline]
Constructor for non-changing (static) values.
Parameters:
[in] table The table this item belongs to
[in] pos The row of the table this item fills
[in] name The name of the represented value
[in] dynamic Information whether this value changes over time
[in] value The value
Todo:
Consider using a reference to the table
Check whether the name should be stored in GUIParameterTableItemInterface
Should never be dynamic!?
Definition at line 152 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::init().
template<class T> GUIParameterTableItem< T >::GUIParameterTableItem (FXTable * table, unsigned pos, const std::string & name, bool dynamic, std::string value) [inline]
Constructor for string-typed, non-changing (static) values.
Parameters:
[in] table The table this item belongs to
[in] pos The row of the table this item fills
[in] name The name of the represented value
[in] dynamic Information whether this value changes over time
[in] value The value
Todo:
Consider using a reference to the table
Check whether the name should be stored in GUIParameterTableItemInterface
Should never be dynamic!?
Definition at line 172 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::init().
template<class T> GUIParameterTableItem< T >::~GUIParameterTableItem () [inline]
Destructor.
Definition at line 182 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::mySource.
Member Function Documentation
template<class T> bool GUIParameterTableItem< T >::dynamic () const [inline, virtual]
Returns the information whether this item may change.
Returns:
Whether this item changes over time
Implements GUIParameterTableItemInterface.
Definition at line 212 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::myAmDynamic.
Referenced by GUIParameterTableItem< T >::update().
template<class T> const std::string& GUIParameterTableItem< T >::getName () const [inline, virtual]
Returns the name of this value.
Returns:
The name of this value
Implements GUIParameterTableItemInterface.
Definition at line 221 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::myName.
template<class T> ValueSource<T>* GUIParameterTableItem< T >::getSourceCopy () const [inline]
Returns a copy of the source if the value is dynamic.
Returns:
A copy of the value source
Definition at line 249 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::mySource.
template<class T> ValueSource<SUMOReal>* GUIParameterTableItem< T >::getSUMORealSourceCopy () const [inline, virtual]
Returns a SUMOReal-typed copy of the source if the value is dynamic.
Returns:
A SUMOReal-typed copy of the value source
Implements GUIParameterTableItemInterface.
Definition at line 261 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::mySource.
template<class T> void GUIParameterTableItem< T >::init (bool dynamic, std::string value) [inline]
Initialises the line.
Fills the line using the name, the current value, and the information whether the value changes over time.
Parameters:
[in] dynamic Information whether this value changes over time
[in] value The current (initial) value
Definition at line 195 of file GUIParameterTableItem.h.
References GUIIconSubSys::getIcon(), ICON_NO, ICON_YES, GUIParameterTableItem< T >::myName, GUIParameterTableItem< T >::myTable, and GUIParameterTableItem< T >::myTablePosition.
Referenced by GUIParameterTableItem< T >::GUIParameterTableItem().
template<class T> void GUIParameterTableItem< T >::update () [inline, virtual]
Resets the value if it's dynamic.
If the value is dynamic, the current value is retrieved from the value source. If it is different from the previous one (stored in myValue), it is stored in myValue and set as the current value text within the according table cell.
Implements GUIParameterTableItemInterface.
Definition at line 233 of file GUIParameterTableItem.h.
References GUIParameterTableItem< T >::dynamic(), GUIParameterTableItem< T >::mySource, GUIParameterTableItem< T >::myTable, GUIParameterTableItem< T >::myTablePosition, and GUIParameterTableItem< T >::myValue.
Field Documentation
template<class T> bool GUIParameterTableItem< T >::myAmDynamic [private]
Information whether the value may change.
Definition at line 271 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::dynamic().
template<class T> std::string GUIParameterTableItem< T >::myName [private]
The name of this value.
Definition at line 274 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::getName(), and GUIParameterTableItem< T >::init().
template<class T> ValueSource<T>* GUIParameterTableItem< T >::mySource [private]
The source to gain new values from; this source is==0 if the values are not dynamic.
Definition at line 280 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::getSourceCopy(), GUIParameterTableItem< T >::getSUMORealSourceCopy(), GUIParameterTableItem< T >::update(), and GUIParameterTableItem< T >::~GUIParameterTableItem().
template<class T> FXTable* GUIParameterTableItem< T >::myTable [private]
The table this entry belongs to.
Definition at line 286 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::init(), and GUIParameterTableItem< T >::update().
template<class T> FXint GUIParameterTableItem< T >::myTablePosition [private]
The position within the table.
Definition at line 277 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::init(), and GUIParameterTableItem< T >::update().
template<class T> T GUIParameterTableItem< T >::myValue [private]
A backup of the value to avoid the redrawing when nothing has changed.
Definition at line 283 of file GUIParameterTableItem.h.
Referenced by GUIParameterTableItem< T >::update().
The documentation for this class was generated from the following file:
GUIParameterTableItem.h