SUMO - Simulation of Urban MObility: angles.h File Reference
angles.h File Reference
#include <cmath>
Functions
double angle0To2Pi (double angle)
double CCW (double reference, double angle1)
Function Documentation
double angle0To2Pi (double angle) [inline]
Definition at line 40 of file angles.h.
References M_PI.
Referenced by BiArc::BiArc(), CCW(), EulerSpiral::compute_es_params(), EulerSpiral::EulerSpiral(), EulerSpiral::set_end_params(), BiArc::set_end_params(), EulerSpiral::set_params(), EulerSpiral::set_start_params(), and BiArc::set_start_params().
double CCW (double reference, double angle1) [inline]
Definition at line 57 of file angles.h.
References angle0To2Pi(), and M_PI.
Referenced by EulerSpiral::compute_end_pt().