SUMO - Simulation of Urban MObility: NWWriter_OpenDrive Class Reference
NWWriter_OpenDrive Class Reference
Exporter writing networks using the openDRIVE format.
#include <NWWriter_OpenDrive.h>
Static Public Member Functions
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a openDRIVE-file.
Static Protected Member Functions
static int getID (const std::string &origID, StringBijection< int > &map, int &lastID)
static void writeEmptyCenterLane (OutputDevice &device)
static void writePlanView (const PositionVector &shape, OutputDevice &device)
Detailed Description
Exporter writing networks using the openDRIVE format.
Definition at line 53 of file NWWriter_OpenDrive.h.
Member Function Documentation
int NWWriter_OpenDrive::getID (const std::string & origID, StringBijection< int > & map, int & lastID) [static, protected]
Definition at line 210 of file NWWriter_OpenDrive.cpp.
References StringBijection< T >::get(), StringBijection< T >::hasString(), and StringBijection< T >::insert().
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeEmptyCenterLane (OutputDevice & device) [static, protected]
Definition at line 198 of file NWWriter_OpenDrive.cpp.
Referenced by writeNetwork().
void NWWriter_OpenDrive::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) [static]
Writes the network into a openDRIVE-file.
Parameters:
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 54 of file NWWriter_OpenDrive.cpp.
References PositionVector::appendWithCrossingPoint(), NBNodeCont::begin(), NBEdgeCont::begin(), NBNodeCont::end(), NBEdgeCont::end(), OutputDevice::getDevice(), NBNetBuilder::getEdgeCont(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), getID(), NBNode::getIncomingEdges(), NBEdge::getLanes(), NBEdge::getLength(), NBNetBuilder::getNodeCont(), NBEdge::getNumLanes(), NBEdge::getStreetName(), OptionsCont::getString(), NBEdge::getToNode(), NBEdge::hasLaneSpecificWidth(), NBEdge::Connection::haveVia, NBEdge::Connection::id, OptionsCont::isSet(), PositionVector::length(), NBEdge::Connection::shape, SUMO_const_laneWidth, SUMOReal, NBEdge::Connection::viaShape, writeEmptyCenterLane(), and writePlanView().
void NWWriter_OpenDrive::writePlanView (const PositionVector & shape, OutputDevice & device) [static, protected]
Definition at line 183 of file NWWriter_OpenDrive.cpp.
References Line::length(), PositionVector::lineAt(), Line::p1(), Line::p2(), PositionVector::size(), SUMOReal, Position::x(), and Position::y().
Referenced by writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_OpenDrive.h
NWWriter_OpenDrive.cpp