SUMO - Simulation of Urban MObility: NLHandler Class Reference
NLHandler Class Reference
#include <NLHandler.h>
Public Types
typedef std::vector< MSLane * > LaneVector
Definition of a lane vector.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getLastDepart () const
Returns the last loaded depart time.
NLHandler (const std::string &file, MSNet &net, NLDetectorBuilder &detBuilder, NLTriggerBuilder &triggerBuilder, NLEdgeControlBuilder &edgeBuilder, NLJunctionControlBuilder &junctionBuilder)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~NLHandler ()
Destructor.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Protected Member Functions
virtual void addE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
virtual void addE2Detector (const SUMOSAXAttributes &attrs)
Builds an e2 detector using the given specification.
void addE3Entry (const SUMOSAXAttributes &attrs)
Adds an entry to the currently processed e3 detector.
void addE3Exit (const SUMOSAXAttributes &attrs)
Adds an exit to the currently processed e3 detector.
virtual void addEdgeLaneMeanData (const SUMOSAXAttributes &attrs, int objecttype)
Builds edge or lane base mean data collector using the given specification.
virtual void addInstantE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
void addParam (const SUMOSAXAttributes &attrs)
virtual void addRouteProbeDetector (const SUMOSAXAttributes &attrs)
Builds a routeprobe-detector using the given specification.
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
virtual void addVTypeProbeDetector (const SUMOSAXAttributes &attrs)
Builds a vtype-detector using the given specification.
void beginE3Detector (const SUMOSAXAttributes &attrs)
Starts building of an e3 detector using the given specification.
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
virtual void closeEdge ()
Closes the process of building an edge.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute ()
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void endE3Detector ()
Builds of an e3 detector using collected values.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
inherited from GenericSAXHandler
virtual void myEndElement (int element)
Called when a closing tag occurs.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
NLDiscreteEventBuilder myActionBuilder
A builder for object actions.
MSPerson::MSPersonPlan * myActivePlan
The plan of the current person.
MSEdgeVector myActiveRoute
The current route.
RGBColor myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The id of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector
< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmInTLLogicMode
internal information whether a tls-logic is currently read
Boundary myConvBoundary
std::string myCurrentDistrictID
The id of the current district.
bool myCurrentIsBroken
bool myCurrentIsInternalToSkip
Information whether the currently parsed edge is internal and not wished, here.
RandomDistributor< const
MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route).
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor
< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type).
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
std::string myCurrentWAUTID
The id of the currently processed WAUT.
NLDetectorBuilder & myDetectorBuilder
The detector builder to use.
NLEdgeControlBuilder & myEdgeControlBuilder
The edge builder to use.
bool myHaveWarnedAboutDeprecatedBusStop
bool myHaveWarnedAboutDeprecatedDetEntry
bool myHaveWarnedAboutDeprecatedDetExit
bool myHaveWarnedAboutDeprecatedDistrict
bool myHaveWarnedAboutDeprecatedDSink
bool myHaveWarnedAboutDeprecatedDSource
bool myHaveWarnedAboutDeprecatedE1
bool myHaveWarnedAboutDeprecatedE2
bool myHaveWarnedAboutDeprecatedE3
bool myHaveWarnedAboutDeprecatedEdgeMean
bool myHaveWarnedAboutDeprecatedFriendlyPos
bool myHaveWarnedAboutDeprecatedJamDistThreshold
bool myHaveWarnedAboutDeprecatedLaneMean
bool myHaveWarnedAboutDeprecatedLanes
bool myHaveWarnedAboutDeprecatedRefID
bool myHaveWarnedAboutDeprecatedRouteProbe
bool myHaveWarnedAboutDeprecatedRowLogic
bool myHaveWarnedAboutDeprecatedSpeedThreshold
bool myHaveWarnedAboutDeprecatedTimedEvent
bool myHaveWarnedAboutDeprecatedTimeThreshold
bool myHaveWarnedAboutDeprecatedTLLogic
bool myHaveWarnedAboutDeprecatedTLSTiming
bool myHaveWarnedAboutDeprecatedVType
bool myHaveWarnedAboutDeprecatedVTypeDistribution
bool myHaveWarnedAboutDeprecatedVTypeProbe
bool myHaveWarnedAboutDeprecatedVTypes
NLJunctionControlBuilder & myJunctionControlBuilder
The junction builder to use.
SUMOTime myLastDepart
The insertion time of the vehicle read last.
MSNet & myNet
The net to fill (preinitialised).
Position myNetworkOffset
The network offset.
Boundary myOrigBoundary
The network's boundaries.
SUMOReal myScale
The scaling factor (especially for inc-dua).
NLSucceedingLaneBuilder mySucceedingLaneBuilder
The lane-to-lane connections builder to use.
NLTriggerBuilder & myTriggerBuilder
The trigger builder to use.
SUMOVehicleParameter * myVehicleParameter
Private Member Functions
void addConnection (const SUMOSAXAttributes &attrs)
adds a connection
void addDistrict (const SUMOSAXAttributes &attrs)
void addDistrictEdge (const SUMOSAXAttributes &attrs, bool isSource)
void addLane (const SUMOSAXAttributes &attrs)
adds a lane to the previously opened edge
void addLogicItem (const SUMOSAXAttributes &attrs)
(deprecated) adds a logic item to the current logic
void addPhase (const SUMOSAXAttributes &attrs)
adds a phase to the traffic lights logic currently build
void addPOI (const SUMOSAXAttributes &attrs)
adds a polygon
void addPoly (const SUMOSAXAttributes &attrs)
adds a polygon
void addRequest (const SUMOSAXAttributes &attrs)
adds a request item to the current junction logic
void addSuccLane (const SUMOSAXAttributes &attrs)
adds a succeeding lane (deprecated, see addConnection)
void addWAUTJunction (const SUMOSAXAttributes &attrs)
void addWAUTSwitch (const SUMOSAXAttributes &attrs)
void beginEdgeParsing (const SUMOSAXAttributes &attrs)
begins the processing of an edge
void closeSuccLane ()
closes the processing of a lane
void closeWAUT ()
std::pair< MSLane *, MSLane * > getLanesFromIndices (MSEdge *from, MSEdge *to, const std::string &laneIndices, bool &ok)
retrieves <fromLane, toLane> based on the edges and an index specifier (i.e. '0:1')
void initJunctionLogic (const SUMOSAXAttributes &attrs)
begins the reading of a junction row logic
void initTrafficLightLogic (const SUMOSAXAttributes &attrs)
begins the reading of a traffic lights logic
NLHandler (const NLHandler &s)
virtual void openJunction (const SUMOSAXAttributes &attrs)
opens a junction for processing
void openSucc (const SUMOSAXAttributes &attrs)
opens the container of succeeding lanes for processing (deprecated, see addConnection))
virtual void openWAUT (const SUMOSAXAttributes &attrs)
NLHandler & operator= (const NLHandler &s)
void parseLanes (const std::string &junctionID, const std::string &def, std::vector< MSLane * > &into, bool &ok)
LinkDirection parseLinkDir (const std::string &dir)
Parses the given character into an enumeration typed link direction.
LinkState parseLinkState (const std::string &state)
Parses the given character into an enumeration typed link state.
void setLocation (const SUMOSAXAttributes &attrs)
Parses network location description.
Detailed Description
Definition at line 71 of file NLHandler.h.
Member Typedef Documentation
typedef std::vector<MSLane*> NLHandler::LaneVector
Definition of a lane vector.
Definition at line 74 of file NLHandler.h.
Constructor & Destructor Documentation
NLHandler::NLHandler (const std::string & file, MSNet & net, NLDetectorBuilder & detBuilder, NLTriggerBuilder & triggerBuilder, NLEdgeControlBuilder & edgeBuilder, NLJunctionControlBuilder & junctionBuilder)
Constructor.
Parameters:
[in] file Name of the parsed file
[in,out] net The network to fill
[in] detBuilder The detector builder to use
[in] triggerBuilder The trigger builder to use
[in] edgeBuilder The builder of edges to use
[in] junctionBuilder The builder of junctions to use
Definition at line 69 of file NLHandler.cpp.
NLHandler::~NLHandler () [virtual]
Destructor.
Definition at line 91 of file NLHandler.cpp.
NLHandler::NLHandler (const NLHandler & s) [private]
invalid copy constructor
Member Function Documentation
void NLHandler::addConnection (const SUMOSAXAttributes & attrs) [private]
adds a connection
Definition at line 1329 of file NLHandler.cpp.
References MSLane::addApproachingLane(), MSLane::addIncomingLane(), MSLane::addLink(), MSTLLogicControl::TLSLogicVariants::addLink(), MSLane::dictionary(), MSEdge::dictionary(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseDef(), Named::getID(), SUMOSAXAttributes::getIntReporting(), getLanesFromIndices(), MSLane::getLength(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), MSLane::getShape(), MSPhaseDefinition::getState(), SUMOSAXAttributes::getStringReporting(), NLJunctionControlBuilder::getTLLogic(), MSGlobals::gUsingInternalLanes, SUMOSAXAttributes::hasAttribute(), myHaveWarnedAboutDeprecatedLanes, myJunctionControlBuilder, parseLinkDir(), parseLinkState(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_LANE, SUMO_ATTR_PASS, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLLINKNO__DEPRECATED, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addDistrict (const SUMOSAXAttributes & attrs) [private]
Parses a district and creates a pseudo edge for it
Called on the occurence of a "district" element, this method retrieves the id of the district and creates a district type edge with this id.
Parameters:
[in] attrs The attributes (of the "district"-element) to parse
Exceptions:
ProcessError If an edge given in district is not known
Definition at line 1525 of file NLHandler.cpp.
References MSEdge::addFollower(), NLEdgeControlBuilder::buildEdge(), MSEdge::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, SUMOSAXAttributes::getString(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), MSEdge::initialize(), myCurrentDistrictID, myCurrentIsBroken, myEdgeControlBuilder, SUMO_ATTR_EDGES, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addDistrictEdge (const SUMOSAXAttributes & attrs, bool isSource) [private]
Parses a district edge and connects it to the district
Called on the occurence of a "dsource" or "dsink" element, this method retrieves the id of the approachable edge. If this edge is known and valid, the approaching edge is informed about it.
Parameters:
[in] attrs The attributes to parse
[in] isSource whether a "dsource or a "dsink" was given
Todo:
No exception?
Definition at line 1575 of file NLHandler.cpp.
References MSEdge::addFollower(), MSEdge::dictionary(), SUMOSAXAttributes::getStringReporting(), myCurrentDistrictID, myCurrentIsBroken, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addE1Detector (const SUMOSAXAttributes & attrs) [protected, virtual]
Builds an e1 detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 882 of file NLHandler.cpp.
References NLDetectorBuilder::buildInductLoop(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addE2Detector (const SUMOSAXAttributes & attrs) [protected, virtual]
Builds an e2 detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 1005 of file NLHandler.cpp.
References NLDetectorBuilder::buildE2Detector(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogic(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, myHaveWarnedAboutDeprecatedJamDistThreshold, myHaveWarnedAboutDeprecatedSpeedThreshold, myHaveWarnedAboutDeprecatedTimeThreshold, myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_SPEED_THRESHOLD__DEPRECATED, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD__DEPRECATED, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_JAM_DIST_THRESHOLD__DEPRECATED, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMOReal, TIME2STEPS, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addE3Entry (const SUMOSAXAttributes & attrs) [protected]
Adds an entry to the currently processed e3 detector.
Parameters:
[in] attrs The attributes that define the entry
Definition at line 1162 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMOReal, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addE3Exit (const SUMOSAXAttributes & attrs) [protected]
Adds an exit to the currently processed e3 detector.
Parameters:
[in] attrs The attributes that define the exit
Definition at line 1189 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Exit(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMOReal, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addEdgeLaneMeanData (const SUMOSAXAttributes & attrs, int objecttype) [protected, virtual]
Builds edge or lane base mean data collector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
[in] objecttype The type (lane/edge) of the parsed mean data definition
Definition at line 1216 of file NLHandler.cpp.
References NLDetectorBuilder::createEdgeLaneMeanData(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptBoolReporting(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, myHaveWarnedAboutDeprecatedVTypes, POSITION_EPS, string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_EXCLUDE_EMPTY, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_MAX_TRAVELTIME, SUMO_ATTR_MIN_SAMPLES, SUMO_ATTR_TRACK_VEHICLES, SUMO_ATTR_TYPE, SUMO_ATTR_VTYPES, SUMO_ATTR_VTYPES__DEPRECATED, SUMO_ATTR_WITH_INTERNAL, SUMO_TAG_MEANDATA_LANE, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addInstantE1Detector (const SUMOSAXAttributes & attrs) [protected, virtual]
Builds an e1 detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 925 of file NLHandler.cpp.
References NLDetectorBuilder::buildInstantInductLoop(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, SUMO_ATTR_FILE, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addLane (const SUMOSAXAttributes & attrs) [private]
adds a lane to the previously opened edge
Definition at line 442 of file NLHandler.cpp.
References NLEdgeControlBuilder::addLane(), MSLane::dictionary(), SUMOSAXAttributes::getOptIntReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMORealReporting(), SUMOSAXAttributes::hasAttribute(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, GeomConvHelper::parseShapeReporting(), parseVehicleClasses(), MSLane::setMySlope(), PositionVector::size(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED__DEPRECATED, SUMO_ATTR_SHAPE, SUMO_ATTR_SLOPE, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, SUMO_const_laneWidth, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addLogicItem (const SUMOSAXAttributes & attrs) [private]
(deprecated) adds a logic item to the current logic
Definition at line 726 of file NLHandler.cpp.
References NLJunctionControlBuilder::addLogicItem(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_REQUEST, SUMO_ATTR_RESPONSE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addParam (const SUMOSAXAttributes & attrs) [protected]
Definition at line 575 of file NLHandler.cpp.
References NLJunctionControlBuilder::addParam(), SUMOSAXAttributes::getStringReporting(), myAmInTLLogicMode, myJunctionControlBuilder, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by myStartElement().
void NLHandler::addPhase (const SUMOSAXAttributes & attrs) [private]
adds a phase to the traffic lights logic currently build
Definition at line 811 of file NLHandler.cpp.
References NLJunctionControlBuilder::addPhase(), NLJunctionControlBuilder::getActiveKey(), NLJunctionControlBuilder::getActiveSubKey(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), myHaveWarnedAboutDeprecatedTLSTiming, myJunctionControlBuilder, SUMO_ATTR_DURATION, SUMO_ATTR_MAXDURATION, SUMO_ATTR_MAXDURATION__DEPRECATED, SUMO_ATTR_MINDURATION, SUMO_ATTR_MINDURATION__DEPRECATED, SUMO_ATTR_STATE, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addPOI (const SUMOSAXAttributes & attrs) [private]
adds a polygon
Definition at line 657 of file NLHandler.cpp.
References ShapeContainer::addPoI(), MSLane::dictionary(), MSLane::getLength(), SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptIntReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), MSLane::getShape(), MSNet::getShapeContainer(), SUMOSAXAttributes::getStringReporting(), GLO_SHAPE, myNet, RGBColor::parseColorReporting(), PositionVector::positionAtLengthPosition(), SUMO_ATTR_COLOR, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addPoly (const SUMOSAXAttributes & attrs) [private]
adds a polygon
Definition at line 698 of file NLHandler.cpp.
References ShapeContainer::addPolygon(), SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptIntReporting(), SUMOSAXAttributes::getOptStringReporting(), MSNet::getShapeContainer(), SUMOSAXAttributes::getStringReporting(), GLO_SHAPE, myNet, RGBColor::parseColorReporting(), GeomConvHelper::parseShapeReporting(), SUMO_ATTR_COLOR, SUMO_ATTR_FILL, SUMO_ATTR_ID, SUMO_ATTR_LAYER, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addRequest (const SUMOSAXAttributes & attrs) [private]
adds a request item to the current junction logic
Definition at line 749 of file NLHandler.cpp.
References NLJunctionControlBuilder::addLogicItem(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getStringReporting(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_INDEX, SUMO_ATTR_RESPONSE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addRouteProbeDetector (const SUMOSAXAttributes & attrs) [protected, virtual]
Builds a routeprobe-detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 983 of file NLHandler.cpp.
References NLDetectorBuilder::buildRouteProbe(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) [protected, inherited]
Processing of a stop.
Definition at line 665 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, MSRouteHandler::checkStopPos(), MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSBusStop::getBeginLanePosition(), MSNet::getBusStop(), MSBusStop::getEndLanePosition(), Named::getID(), MSNet::getInstance(), SUMOSAXAttributes::getIntReporting(), MSBusStop::getLane(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRouteID, MSRouteHandler::myActiveRouteStops, MSRouteHandler::myHaveWarnedAboutDeprecatedBusStop, MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos, MSRouteHandler::myVehicleParameter, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, SUMOVehicleParameter::stops, SUMO_ATTR_BUS_STOP, SUMO_ATTR_BUS_STOP__DEPRECATED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_INDEX, SUMO_ATTR_LANE, SUMO_ATTR_PARKING, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, toString(), SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::myStartElement().
void NLHandler::addSuccLane (const SUMOSAXAttributes & attrs) [private]
adds a succeeding lane (deprecated, see addConnection)
Definition at line 1282 of file NLHandler.cpp.
References NLSucceedingLaneBuilder::addSuccLane(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), HAVE_INTERNAL_LANES, myCurrentIsInternalToSkip, mySucceedingLaneBuilder, parseLinkDir(), parseLinkState(), SUMO_ATTR_DIR, SUMO_ATTR_LANE, SUMO_ATTR_PASS, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLLINKNO__DEPRECATED, SUMO_ATTR_VIA, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addVTypeProbeDetector (const SUMOSAXAttributes & attrs) [protected, virtual]
Builds a vtype-detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 963 of file NLHandler.cpp.
References NLDetectorBuilder::buildVTypeProbe(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addWAUTJunction (const SUMOSAXAttributes & attrs) [private]
Definition at line 635 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTJunction(), SUMOSAXAttributes::getOptBoolReporting(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getStringReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_JUNCTION_ID, SUMO_ATTR_PROCEDURE, SUMO_ATTR_SYNCHRON, SUMO_ATTR_WAUT_ID, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addWAUTSwitch (const SUMOSAXAttributes & attrs) [private]
Definition at line 615 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTSwitch(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_TIME, SUMO_ATTR_TO, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::beginE3Detector (const SUMOSAXAttributes & attrs) [protected]
Starts building of an e3 detector using the given specification.
Parameters:
[in] attrs The attributes that define the detector
Definition at line 1113 of file NLHandler.cpp.
References NLDetectorBuilder::beginE3Detector(), OutputDevice::getDevice(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptSUMORealReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), myDetectorBuilder, myHaveWarnedAboutDeprecatedSpeedThreshold, myHaveWarnedAboutDeprecatedTimeThreshold, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_SPEED_THRESHOLD__DEPRECATED, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD__DEPRECATED, SUMO_ATTR_ID, SUMOReal, TIME2STEPS, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::beginEdgeParsing (const SUMOSAXAttributes & attrs) [private]
begins the processing of an edge
Definition at line 366 of file NLHandler.cpp.
References NLEdgeControlBuilder::beginEdgeParsing(), EDGEFUNC_CONNECTOR, EDGEFUNC_INTERNAL, EDGEFUNC_NORMAL, EDGEFUNC_SINK, EDGEFUNC_SOURCE, MSEdge::EDGEFUNCTION_CONNECTOR, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_NORMAL, MSEdge::EDGEFUNCTION_UNKNOWN, SUMOXMLDefinitions::EdgeFunctions, StringBijection< T >::get(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getStringReporting(), MSGlobals::gUsingInternalLanes, myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, SUMO_ATTR_FUNCTION, SUMO_ATTR_ID, SUMO_ATTR_NAME, toString(), and WRITE_ERROR.
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
bool MSRouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) [inherited]
check start and end position of a stop
Definition at line 627 of file MSRouteHandler.cpp.
Referenced by MSRouteHandler::addStop().
void NLHandler::closeEdge () [protected, virtual]
Closes the process of building an edge.
Definition at line 428 of file NLHandler.cpp.
References NLEdgeControlBuilder::closeEdge(), MSEdge::dictionary(), MSEdge::getID(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void MSRouteHandler::closeFlow () [protected, inherited]
Ends the processing of a flow.
Definition at line 591 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRouteHandler::checkLastDepart(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRouteID, MSRouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::myEndElement().
void MSRouteHandler::closePerson () [protected, inherited]
Ends the processing of a person.
Definition at line 575 of file MSRouteHandler.cpp.
References MSRouteHandler::checkLastDepart(), SUMOVehicleParameter::depart, MSNet::getInstance(), MSNet::getPersonControl(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myVehicleParameter, and MSPersonControl::setArrival().
Referenced by MSRouteHandler::myEndElement().
void MSRouteHandler::closeRoute () [protected, inherited]
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Definition at line 401 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::dictionary(), MSNet::getInstance(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, MSRouteHandler::myActiveRouteColor, MSRouteHandler::myActiveRouteID, MSRouteHandler::myActiveRouteProbability, MSRouteHandler::myActiveRouteRefID, MSRouteHandler::myActiveRouteStops, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myVehicleParameter, and SUMOVehicleParameter::repetitionNumber.
Referenced by MSRouteHandler::myEndElement(), and MSRouteHandler::myStartElement().
void MSRouteHandler::closeRouteDistribution () [protected, inherited]
closes (ends) the building of a distribution
Definition at line 477 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, and WRITE_ERROR.
Referenced by MSRouteHandler::myEndElement().
void NLHandler::closeSuccLane () [private]
closes the processing of a lane
Definition at line 1601 of file NLHandler.cpp.
References NLSucceedingLaneBuilder::closeSuccLane(), myCurrentIsInternalToSkip, mySucceedingLaneBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void MSRouteHandler::closeVehicle () [protected, inherited]
Ends the processing of a vehicle.
Definition at line 492 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addWaiting(), MSRoute::begin(), MSVehicleControl::buildVehicle(), MSRouteHandler::checkLastDepart(), MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSVehicleControl::isInQuota(), MSRouteHandler::myActiveRouteID, MSRouteHandler::myScale, MSRouteHandler::myVehicleParameter, MSVehicleControl::registerOneWaitingForPerson(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::myEndElement(), and MSRouteHandler::myStartElement().
void MSRouteHandler::closeVehicleTypeDistribution () [protected, inherited]
closes (ends) the building of a distribution
Definition at line 281 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, and WRITE_ERROR.
Referenced by MSRouteHandler::myEndElement().
void NLHandler::closeWAUT () [private]
Definition at line 1621 of file NLHandler.cpp.
References MSTLLogicControl::closeWAUT(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void NLHandler::endE3Detector () [protected, virtual]
Builds of an e3 detector using collected values.
Definition at line 1613 of file NLHandler.cpp.
References NLDetectorBuilder::endE3Detector(), myDetectorBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by addE1Detector(), addE2Detector(), addEdgeLaneMeanData(), addInstantE1Detector(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
std::pair< MSLane *, MSLane * > NLHandler::getLanesFromIndices (MSEdge * from, MSEdge * to, const std::string & laneIndices, bool & ok) [private]
retrieves <fromLane, toLane> based on the edges and an index specifier (i.e. '0:1')
Definition at line 1472 of file NLHandler.cpp.
References GenericSAXHandler::error(), MSEdge::getID(), MSEdge::getLanes(), StringTokenizer::next(), StringTokenizer::size(), and WRITE_ERROR.
Referenced by addConnection().
SUMOTime MSRouteHandler::getLastDepart () const [inherited]
Returns the last loaded depart time.
Definition at line 100 of file MSRouteHandler.cpp.
References MSRouteHandler::myLastDepart.
void NLHandler::initJunctionLogic (const SUMOSAXAttributes & attrs) [private]
begins the reading of a junction row logic
Definition at line 775 of file NLHandler.cpp.
References SUMOSAXAttributes::getStringReporting(), NLJunctionControlBuilder::initJunctionLogic(), myCurrentIsBroken, myJunctionControlBuilder, and SUMO_ATTR_ID.
Referenced by myStartElement().
void NLHandler::initTrafficLightLogic (const SUMOSAXAttributes & attrs) [private]
begins the reading of a traffic lights logic
Definition at line 787 of file NLHandler.cpp.
References StringBijection< T >::get(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), NLJunctionControlBuilder::initTrafficLightLogic(), myAmInTLLogicMode, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_OFFSET, SUMO_ATTR_PROGRAMID, SUMO_ATTR_TYPE, SUMOXMLDefinitions::TrafficLightTypes, and WRITE_ERROR.
Referenced by myStartElement().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void NLHandler::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 317 of file NLHandler.cpp.
References closeEdge(), NLJunctionControlBuilder::closeJunction(), NLJunctionControlBuilder::closeJunctionLogic(), closeSuccLane(), NLJunctionControlBuilder::closeTrafficLightLogic(), closeWAUT(), endE3Detector(), myAmInTLLogicMode, myCurrentIsBroken, myJunctionControlBuilder, SUMO_TAG_E3DETECTOR, SUMO_TAG_E3DETECTOR__DEPRECATED, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_JUNCTION, SUMO_TAG_ROWLOGIC__DEPRECATED, SUMO_TAG_SUCC, SUMO_TAG_TLLOGIC, SUMO_TAG_TLLOGIC__DEPRECATED, SUMO_TAG_WAUT, and WRITE_ERROR.
void NLHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 94 of file NLHandler.cpp.
References NLDiscreteEventBuilder::addAction(), addConnection(), addDistrict(), addDistrictEdge(), addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addLane(), addLogicItem(), addParam(), addPhase(), addPOI(), addPoly(), addRequest(), addRouteProbeDetector(), addSuccLane(), addVTypeProbeDetector(), addWAUTJunction(), addWAUTSwitch(), beginE3Detector(), beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), GenericSAXHandler::getFileName(), initJunctionLogic(), initTrafficLightLogic(), myActionBuilder, myHaveWarnedAboutDeprecatedDetEntry, myHaveWarnedAboutDeprecatedDetExit, myHaveWarnedAboutDeprecatedDistrict, myHaveWarnedAboutDeprecatedDSink, myHaveWarnedAboutDeprecatedDSource, myHaveWarnedAboutDeprecatedE1, myHaveWarnedAboutDeprecatedE2, myHaveWarnedAboutDeprecatedE3, myHaveWarnedAboutDeprecatedEdgeMean, myHaveWarnedAboutDeprecatedLaneMean, myHaveWarnedAboutDeprecatedRouteProbe, myHaveWarnedAboutDeprecatedRowLogic, myHaveWarnedAboutDeprecatedTimedEvent, myHaveWarnedAboutDeprecatedTLLogic, myHaveWarnedAboutDeprecatedVTypeProbe, myNet, myTriggerBuilder, openJunction(), openSucc(), openWAUT(), NLTriggerBuilder::parseAndBuildBusStop(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), setLocation(), SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CONNECTION, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_ENTRY__DEPRECATED, SUMO_TAG_DET_EXIT, SUMO_TAG_DET_EXIT__DEPRECATED, SUMO_TAG_DISTRICT__DEPRECATED, SUMO_TAG_DSINK__DEPRECATED, SUMO_TAG_DSOURCE__DEPRECATED, SUMO_TAG_E1DETECTOR, SUMO_TAG_E1DETECTOR__DEPRECATED, SUMO_TAG_E2DETECTOR, SUMO_TAG_E2DETECTOR__DEPRECATED, SUMO_TAG_E3DETECTOR, SUMO_TAG_E3DETECTOR__DEPRECATED, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_INDUCTION_LOOP, SUMO_TAG_INSTANT_INDUCTION_LOOP, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANE_AREA_DETECTOR, SUMO_TAG_LOCATION, SUMO_TAG_LOGICITEM, SUMO_TAG_MEANDATA_EDGE, SUMO_TAG_MEANDATA_EDGE__DEPRECATED, SUMO_TAG_MEANDATA_LANE, SUMO_TAG_MEANDATA_LANE__DEPRECATED, SUMO_TAG_PARAM, SUMO_TAG_PHASE, SUMO_TAG_POI, SUMO_TAG_POLY, SUMO_TAG_REQUEST, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_ROUTEPROBE__DEPRECATED, SUMO_TAG_ROWLOGIC__DEPRECATED, SUMO_TAG_SUCC, SUMO_TAG_SUCCLANE, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, SUMO_TAG_TIMEDEVENT, SUMO_TAG_TIMEDEVENT__DEPRECATED, SUMO_TAG_TLLOGIC, SUMO_TAG_TLLOGIC__DEPRECATED, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPEPROBE, SUMO_TAG_VTYPEPROBE__DEPRECATED, SUMO_TAG_WAUT, SUMO_TAG_WAUT_JUNCTION, SUMO_TAG_WAUT_SWITCH, toString(), WRITE_ERROR, and WRITE_WARNING.
void NLHandler::openJunction (const SUMOSAXAttributes & attrs) [private, virtual]
opens a junction for processing
Definition at line 508 of file NLHandler.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMORealReporting(), MSGlobals::gUsingInternalLanes, SUMOSAXAttributes::hasAttribute(), myCurrentIsBroken, myJunctionControlBuilder, NLJunctionControlBuilder::openJunction(), parseLanes(), GeomConvHelper::parseShapeReporting(), SUMO_ATTR_ID, SUMO_ATTR_INCLANES, SUMO_ATTR_INTLANES, SUMO_ATTR_KEY, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) [protected, inherited]
opens a route for reading
Definition at line 296 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), RGBColor::getDefaultColor(), SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), SUMOSAXAttributes::getOptSUMORealReporting(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, MSRouteHandler::myActiveRouteColor, MSRouteHandler::myActiveRouteID, MSRouteHandler::myActiveRouteProbability, MSRouteHandler::myActiveRouteRefID, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myHaveWarnedAboutDeprecatedRefID, MSRouteHandler::myVehicleParameter, RGBColor::parseColorReporting(), MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMO_ATTR_REFID__DEPRECATED, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::myStartElement().
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) [protected, inherited]
opens a route distribution for reading
Definition at line 447 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::dictionary(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, and SUMO_ATTR_ROUTES.
Referenced by MSRouteHandler::myStartElement().
void NLHandler::openSucc (const SUMOSAXAttributes & attrs) [private]
opens the container of succeeding lanes for processing (deprecated, see addConnection))
Definition at line 1271 of file NLHandler.cpp.
References SUMOSAXAttributes::getStringReporting(), MSGlobals::gUsingInternalLanes, myCurrentIsInternalToSkip, mySucceedingLaneBuilder, NLSucceedingLaneBuilder::openSuccLane(), and SUMO_ATTR_LANE.
Referenced by myStartElement().
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) [protected, inherited]
opens a type distribution for reading
Definition at line 252 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), SUMOSAXAttributes::getStringReporting(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myHaveWarnedAboutDeprecatedVTypes, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_VTYPES, SUMO_ATTR_VTYPES__DEPRECATED, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::myStartElement().
void NLHandler::openWAUT (const SUMOSAXAttributes & attrs) [private, virtual]
Definition at line 587 of file NLHandler.cpp.
References MSTLLogicControl::addWAUT(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_REF_TIME, SUMO_ATTR_START_PROG, and WRITE_ERROR.
Referenced by myStartElement().
NLHandler& NLHandler::operator= (const NLHandler & s) [private]
invalid assignment operator
void NLHandler::parseLanes (const std::string & junctionID, const std::string & def, std::vector< MSLane * > & into, bool & ok) [private]
Definition at line 555 of file NLHandler.cpp.
References MSLane::dictionary(), MSGlobals::gUsingInternalLanes, StringTokenizer::hasNext(), StringTokenizer::next(), and WRITE_ERROR.
Referenced by openJunction().
LinkDirection NLHandler::parseLinkDir (const std::string & dir) [private]
Parses the given character into an enumeration typed link direction.
Definition at line 1451 of file NLHandler.cpp.
References StringBijection< T >::get(), and SUMOXMLDefinitions::LinkDirections.
Referenced by addConnection(), and addSuccLane().
LinkState NLHandler::parseLinkState (const std::string & state) [private]
Parses the given character into an enumeration typed link state.
Definition at line 1459 of file NLHandler.cpp.
References StringBijection< T >::get(), LINKSTATE_TL_OFF_BLINKING, and SUMOXMLDefinitions::LinkStates.
Referenced by addConnection(), and addSuccLane().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void NLHandler::setLocation (const SUMOSAXAttributes & attrs) [private]
Parses network location description.
Definition at line 1507 of file NLHandler.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getStringReporting(), GeoConvHelper::init(), GeomConvHelper::parseBoundaryReporting(), GeomConvHelper::parseShapeReporting(), SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, and SUMO_ATTR_ORIG_PROJ.
Referenced by myStartElement().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
NLDiscreteEventBuilder NLHandler::myActionBuilder [protected]
A builder for object actions.
Definition at line 281 of file NLHandler.h.
Referenced by myStartElement().
MSPerson::MSPersonPlan* MSRouteHandler::myActivePlan [protected, inherited]
The plan of the current person.
Definition at line 160 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closePerson(), and MSRouteHandler::myStartElement().
MSEdgeVector MSRouteHandler::myActiveRoute [protected, inherited]
The current route.
Definition at line 142 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), and MSRouteHandler::openRoute().
RGBColor MSRouteHandler::myActiveRouteColor [protected, inherited]
The currently parsed route's color.
Definition at line 154 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), and MSRouteHandler::openRoute().
std::string MSRouteHandler::myActiveRouteID [protected, inherited]
The id of the current route.
Definition at line 145 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeFlow(), MSRouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), and MSRouteHandler::openRoute().
SUMOReal MSRouteHandler::myActiveRouteProbability [protected, inherited]
The id of the current route.
Definition at line 151 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), and MSRouteHandler::openRoute().
std::string MSRouteHandler::myActiveRouteRefID [protected, inherited]
The id of the route the current route references to.
Definition at line 148 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), and MSRouteHandler::openRoute().
std::vector<SUMOVehicleParameter::Stop> MSRouteHandler::myActiveRouteStops [protected, inherited]
List of the stops on the parsed route.
Definition at line 157 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), and MSRouteHandler::closeRoute().
bool MSRouteHandler::myAddVehiclesDirectly [protected, inherited]
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 163 of file MSRouteHandler.h.
Referenced by MSRouteHandler::checkLastDepart().
bool NLHandler::myAmInTLLogicMode [protected]
internal information whether a tls-logic is currently read
Definition at line 308 of file NLHandler.h.
Referenced by addParam(), initTrafficLightLogic(), and myEndElement().
Boundary NLHandler::myConvBoundary [protected]
Definition at line 317 of file NLHandler.h.
std::string NLHandler::myCurrentDistrictID [protected]
The id of the current district.
Definition at line 305 of file NLHandler.h.
Referenced by addDistrict(), and addDistrictEdge().
bool NLHandler::myCurrentIsBroken [protected]
Definition at line 319 of file NLHandler.h.
Referenced by addDistrict(), addDistrictEdge(), addLane(), addRequest(), addWAUTJunction(), addWAUTSwitch(), beginEdgeParsing(), closeEdge(), closeWAUT(), initJunctionLogic(), myEndElement(), openJunction(), and openWAUT().
bool NLHandler::myCurrentIsInternalToSkip [protected]
Information whether the currently parsed edge is internal and not wished, here.
Definition at line 284 of file NLHandler.h.
Referenced by addLane(), addSuccLane(), beginEdgeParsing(), closeEdge(), closeSuccLane(), and openSucc().
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution [protected, inherited]
The currently parsed distribution of routes (probability->route).
Definition at line 172 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
std::string MSRouteHandler::myCurrentRouteDistributionID [protected, inherited]
The id of the currently parsed route distribution.
Definition at line 175 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
SUMOVTypeParameter* MSRouteHandler::myCurrentVType [protected, inherited]
The currently parsed vehicle type.
Definition at line 181 of file MSRouteHandler.h.
Referenced by MSRouteHandler::myEndElement(), and MSRouteHandler::myStartElement().
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution [protected, inherited]
The currently parsed distribution of vehicle types (probability->vehicle type).
Definition at line 166 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
std::string MSRouteHandler::myCurrentVTypeDistributionID [protected, inherited]
The id of the currently parsed vehicle type distribution.
Definition at line 169 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
std::string NLHandler::myCurrentWAUTID [protected]
The id of the currently processed WAUT.
Definition at line 311 of file NLHandler.h.
Referenced by addWAUTSwitch(), closeWAUT(), and openWAUT().
NLDetectorBuilder& NLHandler::myDetectorBuilder [protected]
The detector builder to use.
Definition at line 288 of file NLHandler.h.
Referenced by addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), and endE3Detector().
NLEdgeControlBuilder& NLHandler::myEdgeControlBuilder [protected]
The edge builder to use.
Definition at line 294 of file NLHandler.h.
Referenced by addDistrict(), addLane(), beginEdgeParsing(), and closeEdge().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedBusStop [protected, inherited]
Definition at line 183 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop().
bool NLHandler::myHaveWarnedAboutDeprecatedDetEntry [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedDetExit [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedDistrict [protected]
Definition at line 332 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedDSink [protected]
Definition at line 332 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedDSource [protected]
Definition at line 332 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedE1 [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedE2 [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedE3 [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedEdgeMean [protected]
Definition at line 329 of file NLHandler.h.
Referenced by myStartElement().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedFriendlyPos [protected, inherited]
Definition at line 183 of file MSRouteHandler.h.
Referenced by addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addInstantE1Detector(), and MSRouteHandler::addStop().
bool NLHandler::myHaveWarnedAboutDeprecatedJamDistThreshold [protected]
Definition at line 326 of file NLHandler.h.
Referenced by addE2Detector().
bool NLHandler::myHaveWarnedAboutDeprecatedLaneMean [protected]
Definition at line 329 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedLanes [protected]
Definition at line 331 of file NLHandler.h.
Referenced by addConnection().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedRefID [protected, inherited]
Definition at line 185 of file MSRouteHandler.h.
Referenced by MSRouteHandler::openRoute().
bool NLHandler::myHaveWarnedAboutDeprecatedRouteProbe [protected]
Definition at line 329 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedRowLogic [protected]
Definition at line 324 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedSpeedThreshold [protected]
Definition at line 326 of file NLHandler.h.
Referenced by addE2Detector(), and beginE3Detector().
bool NLHandler::myHaveWarnedAboutDeprecatedTimedEvent [protected]
Definition at line 321 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedTimeThreshold [protected]
Definition at line 326 of file NLHandler.h.
Referenced by addE2Detector(), and beginE3Detector().
bool NLHandler::myHaveWarnedAboutDeprecatedTLLogic [protected]
Definition at line 324 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedTLSTiming [protected]
Definition at line 325 of file NLHandler.h.
Referenced by addPhase().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedVType [protected, inherited]
Definition at line 184 of file MSRouteHandler.h.
Referenced by MSRouteHandler::myStartElement().
bool MSRouteHandler::myHaveWarnedAboutDeprecatedVTypeDistribution [protected, inherited]
Definition at line 184 of file MSRouteHandler.h.
Referenced by MSRouteHandler::myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedVTypeProbe [protected]
Definition at line 329 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedVTypes [protected]
Reimplemented from MSRouteHandler.
Definition at line 331 of file NLHandler.h.
Referenced by addEdgeLaneMeanData().
NLJunctionControlBuilder& NLHandler::myJunctionControlBuilder [protected]
The junction builder to use.
Definition at line 297 of file NLHandler.h.
Referenced by addConnection(), addE2Detector(), addLogicItem(), addParam(), addPhase(), addRequest(), addWAUTJunction(), addWAUTSwitch(), closeWAUT(), initJunctionLogic(), initTrafficLightLogic(), myEndElement(), openJunction(), and openWAUT().
SUMOTime MSRouteHandler::myLastDepart [protected, inherited]
The insertion time of the vehicle read last.
Definition at line 139 of file MSRouteHandler.h.
Referenced by MSRouteHandler::checkLastDepart(), and MSRouteHandler::getLastDepart().
MSNet& NLHandler::myNet [protected]
The net to fill (preinitialised).
Definition at line 181 of file NLHandler.h.
Referenced by addPOI(), addPoly(), and myStartElement().
Position NLHandler::myNetworkOffset [protected]
The network offset.
Definition at line 314 of file NLHandler.h.
Boundary NLHandler::myOrigBoundary [protected]
The network's boundaries.
Definition at line 317 of file NLHandler.h.
SUMOReal MSRouteHandler::myScale [protected, inherited]
The scaling factor (especially for inc-dua).
Definition at line 178 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicle(), and MSRouteHandler::MSRouteHandler().
NLSucceedingLaneBuilder NLHandler::mySucceedingLaneBuilder [protected]
The lane-to-lane connections builder to use.
Definition at line 300 of file NLHandler.h.
Referenced by addSuccLane(), closeSuccLane(), and openSucc().
NLTriggerBuilder& NLHandler::myTriggerBuilder [protected]
The trigger builder to use.
Definition at line 291 of file NLHandler.h.
Referenced by myStartElement().
SUMOVehicleParameter* MSRouteHandler::myVehicleParameter [protected, inherited]
Definition at line 136 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::checkLastDepart(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myEndElement(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
The documentation for this class was generated from the following files:
NLHandler.h
NLHandler.cpp