SUMO - Simulation of Urban MObility: SysUtils Class Reference
SysUtils Class Reference
#include <SysUtils.h>
Static Public Member Functions
static long getCurrentMillis ()
Detailed Description
Definition at line 37 of file SysUtils.h.
Member Function Documentation
long SysUtils::getCurrentMillis () [static]
Definition at line 46 of file SysUtils.cpp.
Referenced by NLBuilder::build(), MSNet::closeBuilding(), MSNet::closeSimulation(), NLBuilder::load(), GUIRunThread::run(), and MSNet::simulationStep().
The documentation for this class was generated from the following files:
SysUtils.h
SysUtils.cpp