SUMO - Simulation of Urban MObility: MSCFModel_PWag2009 Class Reference
MSCFModel_PWag2009 Class Reference
Scalable model based on Krauﬂ by Peter Wagner.
#include <MSCFModel_PWag2009.h>
Data Structures
class VehicleVariables
Public Member Functions
virtual
MSCFModel::VehicleVariables * createVehicleVariables () const
Returns model specific values which are stored inside a vehicle and must be used with casting.
MSCFModel * duplicate (const MSVehicleType *vtype) const
Duplicates the car-following model.
MSCFModel_PWag2009 (const MSVehicleType *vtype, SUMOReal accel, SUMOReal decel, SUMOReal dawdle, SUMOReal headwayTime, SUMOReal tauLast, SUMOReal apProb)
Constructor.
~MSCFModel_PWag2009 ()
Destructor.
Currently fixed methods
SUMOReal brakeGap (SUMOReal speed) const
Returns the distance the vehicle needs to halt including driver's reaction time.
SUMOReal getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const
Returns the minimum gap to reserve if the leader is braking at maximum.
SUMOReal getSpeedAfterMaxDecel (SUMOReal v) const
Returns the velocity after maximum deceleration.
void leftVehicleVsafe (const MSVehicle *const ego, const MSVehicle *const neigh, SUMOReal &vSafe) const
Incorporates the influence of the vehicle on the left lane.
SUMOReal maxNextSpeed (SUMOReal speed) const
Returns the maximum speed given the current speed.
Implementations of the MSCFModel interface
SUMOReal followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Computes the vehicle's safe speed (no dawdling).
SUMOReal getImperfection () const
Get the driver's imperfection.
int getModelID () const
Returns the model's name.
SUMOReal moveHelper (MSVehicle *const veh, SUMOReal vPos) const
Applies interaction with stops and lane changing model influences.
SUMOReal stopSpeed (const MSVehicle *const veh, SUMOReal gap2pred) const
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling).
Methods to override by model implementation
virtual SUMOReal freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed) const
Computes the vehicle's safe speed without a leader.
virtual SUMOReal interactionGap (const MSVehicle *const veh, SUMOReal vL) const
Returns the maximum gap at which an interaction between both vehicles occurs.
virtual void saveState (std::ostream &os)
Saves the model's definition into the state.
Virtual methods with default implementation
virtual SUMOReal getHeadwayTime () const
Get the driver's reaction time [s].
virtual SUMOReal getMaxAccel () const
Get the vehicle type's maximum acceleration [m/s^2].
virtual SUMOReal getMaxDecel () const
Get the vehicle type's maximum deceleration [m/s^2].
Setter methods
virtual void setHeadwayTime (SUMOReal headwayTime)
Sets a new value for driver reaction time [s].
virtual void setImperfection (SUMOReal imperfection)
Sets a new value for driver imperfection.
virtual void setMaxAccel (SUMOReal accel)
Sets a new value for maximum acceleration [m/s^2].
virtual void setMaxDecel (SUMOReal decel)
Sets a new value for maximum deceleration [m/s^2].
Protected Attributes
SUMOReal myAccel
The vehicle's maximum acceleration [m/s^2].
SUMOReal myDecel
The vehicle's maximum deceleration [m/s^2].
SUMOReal myHeadwayTime
The driver's desired time headway (aka reaction time tau) [s].
const MSVehicleType * myType
The type to which this model definition belongs to.
Private Member Functions
SUMOReal _v (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap, SUMOReal predSpeed) const
Returns the next velocity.
SUMOReal dawdle (SUMOReal speed) const
Applies driver imperfection (dawdling / sigma).
Private Attributes
model parameter
The vehicle's dawdle-parameter. 0 for no dawdling, 1 for max.
SUMOReal myActionPointProbability
The probability for any action.
SUMOReal myDawdle
SUMOReal myDecelDivTau
The precomputed value for myDecel/myTau.
SUMOReal myTauDecel
The precomputed value for myDecel*myTau.
SUMOReal myTauLastDecel
The precomputed value for (minimum headway time)*myDecel.
Detailed Description
Scalable model based on Krauﬂ by Peter Wagner.
See also:
MSCFModel
Definition at line 44 of file MSCFModel_PWag2009.h.
Constructor & Destructor Documentation
MSCFModel_PWag2009::MSCFModel_PWag2009 (const MSVehicleType * vtype, SUMOReal accel, SUMOReal decel, SUMOReal dawdle, SUMOReal headwayTime, SUMOReal tauLast, SUMOReal apProb)
Constructor.
Parameters:
[in] accel The maximum acceleration
[in] decel The maximum deceleration
[in] dawdle The driver imperfection
[in] tau The driver's reaction time
Definition at line 42 of file MSCFModel_PWag2009.cpp.
Referenced by duplicate().
MSCFModel_PWag2009::~MSCFModel_PWag2009 ()
Destructor.
Definition at line 50 of file MSCFModel_PWag2009.cpp.
Member Function Documentation
SUMOReal MSCFModel_PWag2009::_v (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap, SUMOReal predSpeed) const [private]
Returns the next velocity.
Parameters:
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The LEADER's speed
Returns:
the safe velocity
Definition at line 98 of file MSCFModel_PWag2009.cpp.
References MAX2(), MSCFModel::myDecel, myTauLastDecel, and SUMOReal.
Referenced by followSpeed(), and stopSpeed().
SUMOReal MSCFModel::brakeGap (SUMOReal speed) const [inherited]
Returns the distance the vehicle needs to halt including driver's reaction time.
Parameters:
[in] speed The vehicle's current speed
Returns:
The distance needed to halt
Definition at line 104 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxDecel(), MSCFModel::myHeadwayTime, SPEED2DIST, and SUMOReal.
Referenced by MSVehicle::addStop(), MSLane::getLeaderOnConsecutive(), getMaxSpeedRegardingNextLanes(), MSLaneChanger::getRealLeader(), MSCFModel::getSecureGap(), MSLane::isInsertionSuccess(), MSLane::pWagGenericInsertion(), and MSLane::pWagSimpleInsertion().
virtual MSCFModel::VehicleVariables* MSCFModel_PWag2009::createVehicleVariables () const [inline, virtual]
Returns model specific values which are stored inside a vehicle and must be used with casting.
Reimplemented from MSCFModel.
Definition at line 118 of file MSCFModel_PWag2009.h.
SUMOReal MSCFModel_PWag2009::dawdle (SUMOReal speed) const [private]
Applies driver imperfection (dawdling / sigma).
Parameters:
[in] speed The speed with no dawdling
Returns:
The speed after dawdling
Definition at line 89 of file MSCFModel_PWag2009.cpp.
References ACCEL2SPEED, MAX2(), MSCFModel::myAccel, myDawdle, RandHelper::rand(), and SUMOReal.
MSCFModel * MSCFModel_PWag2009::duplicate (const MSVehicleType * vtype) const [virtual]
Duplicates the car-following model.
Parameters:
[in] vtype The vehicle type this model belongs to (1:1)
Returns:
A duplicate of this car-following model
Implements MSCFModel.
Definition at line 108 of file MSCFModel_PWag2009.cpp.
References MSCFModel_PWag2009(), MSCFModel::myAccel, myActionPointProbability, myDawdle, MSCFModel::myDecel, MSCFModel::myHeadwayTime, and myTauLastDecel.
SUMOReal MSCFModel_PWag2009::followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const [virtual]
Computes the vehicle's safe speed (no dawdling).
Parameters:
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns:
EGO's safe speed
See also:
MSCFModel::ffeV
Implements MSCFModel.
Definition at line 77 of file MSCFModel_PWag2009.cpp.
References _v().
virtual SUMOReal MSCFModel::freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed) const [inline, virtual, inherited]
Computes the vehicle's safe speed without a leader.
Returns the velocity of the vehicle in dependence to the length of the free street and the target velocity at the end of the free range.
Parameters:
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] seen The look ahead distance
[in] maxSpeed The maximum allowed speed
Returns:
EGO's safe speed
Definition at line 96 of file MSCFModel.h.
References MSCFModel::followSpeed().
Referenced by getMaxSpeedRegardingNextLanes(), and MSLane::isInsertionSuccess().
virtual SUMOReal MSCFModel::getHeadwayTime () const [inline, virtual, inherited]
Get the driver's reaction time [s].
Returns:
The reaction time of this class' drivers in s
Definition at line 193 of file MSCFModel.h.
References MSCFModel::myHeadwayTime.
Referenced by TraCIServerAPI_VehicleType::getVariable(), MSLane::maxSpeedGapInsertion(), and MSLane::pWagSimpleInsertion().
SUMOReal MSCFModel_PWag2009::getImperfection () const [inline, virtual]
Get the driver's imperfection.
Returns:
The imperfection of drivers of this class
Reimplemented from MSCFModel.
Definition at line 104 of file MSCFModel_PWag2009.h.
References myDawdle.
virtual SUMOReal MSCFModel::getMaxAccel () const [inline, virtual, inherited]
Get the vehicle type's maximum acceleration [m/s^2].
Returns:
The maximum acceleration (in m/s^2) of vehicles of this class
Definition at line 169 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and MSCFModel::maxNextSpeed().
virtual SUMOReal MSCFModel::getMaxDecel () const [inline, virtual, inherited]
Get the vehicle type's maximum deceleration [m/s^2].
Returns:
The maximum deceleration (in m/s^2) of vehicles of this class
Definition at line 177 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by MSCFModel::brakeGap(), MSLaneChanger::change2left(), MSLaneChanger::change2right(), MSLane::freeInsertion(), TraCIServerAPI_VehicleType::getVariable(), MSLCM_DK2004::informBlocker(), MSLane::isInsertionSuccess(), MSCFModel::leftVehicleVsafe(), MSLane::maxSpeedGapInsertion(), MSVehicle::moveChecked(), MSLane::pWagGenericInsertion(), MSLCM_DK2004::wantsChangeToLeft(), and MSLCM_DK2004::wantsChangeToRight().
int MSCFModel_PWag2009::getModelID () const [inline, virtual]
Returns the model's name.
Returns:
The model's name
See also:
MSCFModel::getModelName
Implements MSCFModel.
Definition at line 96 of file MSCFModel_PWag2009.h.
References SUMO_TAG_CF_PWAGNER2009.
SUMOReal MSCFModel::getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const [inline, inherited]
Returns the minimum gap to reserve if the leader is braking at maximum.
Parameters:
[in] speed EGO's speed
[in] leaderSpeed LEADER's speed
[in] leaderMaxDecel LEADER's max. deceleration rate
Definition at line 239 of file MSCFModel.h.
References ACCEL2SPEED, MSCFModel::brakeGap(), MAX2(), SPEED2DIST, and SUMOReal.
Referenced by MSLaneChanger::change2left(), MSLaneChanger::change2right(), MSLane::freeInsertion(), MSLCM_DK2004::informBlocker(), and MSLane::isInsertionSuccess().
SUMOReal MSCFModel::getSpeedAfterMaxDecel (SUMOReal v) const [inline, inherited]
Returns the velocity after maximum deceleration.
Parameters:
[in] v The velocity
Returns:
The velocity after maximum deceleration
Definition at line 250 of file MSCFModel.h.
References ACCEL2SPEED, MAX2(), MSCFModel::myDecel, and SUMOReal.
Referenced by MSCFModel_Krauss::followSpeed(), MSCFModel_Wiedemann::stopSpeed(), and MSCFModel_Krauss::stopSpeed().
SUMOReal MSCFModel::interactionGap (const MSVehicle *const veh, SUMOReal vL) const [virtual, inherited]
Returns the maximum gap at which an interaction between both vehicles occurs.
"interaction" means that the LEADER influences EGO's speed.
Parameters:
[in] veh The EGO vehicle
[in] vL LEADER's speed
Returns:
The interaction gap
Todo:
evaluate signature
Reimplemented in MSCFModel_IDM, and MSCFModel_Wiedemann.
Definition at line 71 of file MSCFModel.cpp.
References MSVehicle::getLane(), MSLane::getMaxSpeed(), MSVehicle::getSpeed(), MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, SPEED2DIST, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::predInteraction().
void MSCFModel::leftVehicleVsafe (const MSVehicle *const ego, const MSVehicle *const neigh, SUMOReal & vSafe) const [inherited]
Incorporates the influence of the vehicle on the left lane.
In Germany, vehicles on the right lane must not pass a vehicle on the lane left to the if the allowed velocity>60km/h
Parameters:
[in] ego The ego vehicle
[in] neigh The neighbor vehicle on the left lane
[in,out] vSafe Current vSafe; may be adapted due to the left neighbor
Definition at line 86 of file MSCFModel.cpp.
References MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), MIN2(), and SUMOReal.
SUMOReal MSCFModel::maxNextSpeed (SUMOReal speed) const [inherited]
Returns the maximum speed given the current speed.
The implementation of this method must take into account the time step duration.
Justification: Due to air brake or other influences, the vehicle's next maximum speed may depend on the vehicle's current speed (given).
Parameters:
[in] speed The vehicle's current speed
Returns:
The maximum possible speed for the next step
Definition at line 98 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxAccel(), MSVehicleType::getMaxSpeed(), MIN2(), MSCFModel::myType, and SUMOReal.
Referenced by MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_Kerner::followSpeed(), MSLane::getFollowerOnConsecutive(), MSCFModel::interactionGap(), MSVehicle::moveChecked(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2004::patchSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_Krauss::stopSpeed(), and MSCFModel_Kerner::stopSpeed().
SUMOReal MSCFModel_PWag2009::moveHelper (MSVehicle *const veh, SUMOReal vPos) const [virtual]
Applies interaction with stops and lane changing model influences.
Parameters:
[in] veh The ego vehicle
[in] vPos The possible velocity
Returns:
The velocity after applying interactions with stops and lane change model influences
Reimplemented from MSCFModel.
Definition at line 54 of file MSCFModel_PWag2009.cpp.
References ACCEL2SPEED, MSCFModel_PWag2009::VehicleVariables::aOld, MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowVariables(), MSVehicle::getLane(), MSLane::getLeaderOnConsecutive(), MSVehicle::getSpeed(), MAX2(), myActionPointProbability, myDawdle, myDecelDivTau, MSCFModel::myHeadwayTime, myTauDecel, RandHelper::rand(), SPEED2ACCEL, SUMOReal, and TS.
void MSCFModel::saveState (std::ostream & os) [virtual, inherited]
Saves the model's definition into the state.
Parameters:
[in] os The output to write the definition into
Definition at line 113 of file MSCFModel.cpp.
virtual void MSCFModel::setHeadwayTime (SUMOReal headwayTime) [inline, virtual, inherited]
Sets a new value for driver reaction time [s].
Parameters:
[in] headwayTime The new driver reaction time (in s)
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 286 of file MSCFModel.h.
References MSCFModel::myHeadwayTime.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setImperfection (SUMOReal imperfection) [inline, virtual, inherited]
Sets a new value for driver imperfection.
Parameters:
[in] accel The new driver imperfection
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 278 of file MSCFModel.h.
References UNUSED_PARAMETER.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setMaxAccel (SUMOReal accel) [inline, virtual, inherited]
Sets a new value for maximum acceleration [m/s^2].
Parameters:
[in] accel The new acceleration in m/s^2
Definition at line 262 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setMaxDecel (SUMOReal decel) [inline, virtual, inherited]
Sets a new value for maximum deceleration [m/s^2].
Parameters:
[in] accel The new deceleration in m/s^2
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 270 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by TraCIServerAPI_VehicleType::setVariable().
SUMOReal MSCFModel_PWag2009::stopSpeed (const MSVehicle *const veh, SUMOReal gap2pred) const [virtual]
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling).
Parameters:
[in] veh The vehicle (EGO)
[in] gap2pred The (netto) distance to the the obstacle
Returns:
EGO's safe speed for approaching a non-moving obstacle
See also:
MSCFModel::ffeS
Todo:
generic Interface, models can call for the values they need
Implements MSCFModel.
Definition at line 83 of file MSCFModel_PWag2009.cpp.
References _v(), and MSVehicle::getSpeed().
Field Documentation
SUMOReal MSCFModel::myAccel [protected, inherited]
The vehicle's maximum acceleration [m/s^2].
Definition at line 297 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_Kerner::_v(), MSCFModel_IDM::_v(), dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_Krauss::dawdle(), MSCFModel_Wiedemann::duplicate(), duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Wiedemann::fullspeed(), MSCFModel::getMaxAccel(), MSCFModel_IDM::interactionGap(), and MSCFModel::setMaxAccel().
SUMOReal MSCFModel_PWag2009::myActionPointProbability [private]
The probability for any action.
Definition at line 159 of file MSCFModel_PWag2009.h.
Referenced by duplicate(), and moveHelper().
SUMOReal MSCFModel_PWag2009::myDawdle [private]
Definition at line 147 of file MSCFModel_PWag2009.h.
Referenced by dawdle(), duplicate(), getImperfection(), and moveHelper().
SUMOReal MSCFModel::myDecel [protected, inherited]
The vehicle's maximum deceleration [m/s^2].
Definition at line 300 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), _v(), MSCFModel_Kerner::_v(), MSCFModel_KraussOrig1::_vsafe(), MSCFModel_Krauss::_vsafe(), MSCFModel_Wiedemann::duplicate(), duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Wiedemann::emergency(), MSCFModel::getMaxDecel(), MSCFModel::getSpeedAfterMaxDecel(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel_KraussOrig1::setMaxDecel(), and MSCFModel::setMaxDecel().
SUMOReal MSCFModel_PWag2009::myDecelDivTau [private]
The precomputed value for myDecel/myTau.
Definition at line 153 of file MSCFModel_PWag2009.h.
Referenced by moveHelper().
SUMOReal MSCFModel::myHeadwayTime [protected, inherited]
The driver's desired time headway (aka reaction time tau) [s].
Definition at line 303 of file MSCFModel.h.
Referenced by MSCFModel_IDM::_v(), MSCFModel::brakeGap(), duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel::getHeadwayTime(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), moveHelper(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel::setHeadwayTime(), and MSCFModel_KraussOrig1::setMaxDecel().
SUMOReal MSCFModel_PWag2009::myTauDecel [private]
The precomputed value for myDecel*myTau.
Definition at line 150 of file MSCFModel_PWag2009.h.
Referenced by moveHelper().
SUMOReal MSCFModel_PWag2009::myTauLastDecel [private]
The precomputed value for (minimum headway time)*myDecel.
Definition at line 156 of file MSCFModel_PWag2009.h.
Referenced by _v(), and duplicate().
const MSVehicleType* MSCFModel::myType [protected, inherited]
The type to which this model definition belongs to.
Definition at line 294 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_IDM::desiredSpeed(), and MSCFModel::maxNextSpeed().
The documentation for this class was generated from the following files:
MSCFModel_PWag2009.h
MSCFModel_PWag2009.cpp