SUMO - Simulation of Urban MObility: PCNetProjectionLoader Class Reference
PCNetProjectionLoader Class Reference
A reader for a SUMO network's projection description.
#include <PCNetProjectionLoader.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Static Public Member Functions
static void loadIfSet (OptionsCont &oc, Position &netOffset, Boundary &origNetBoundary, Boundary &convNetBoundary, std::string &projParameter)
Loads network projection if wished.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
bool hasReadAll () const
Returns whether all needed values were read.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
PCNetProjectionLoader (Position &netOffset, Boundary &origNetBoundary, Boundary &convNetBoundary, std::string &projParameter)
Constructor.
~PCNetProjectionLoader ()
Destructor.
inherited from GenericSAXHandler
void myCharacters (int element, const std::string &chars)
Called when characters occure.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Private Attributes
Boundary & myConvNetBoundary
The converted network boundary to fill from values read from the network.
bool myFoundConvNetBoundary
bool myFoundOffset
Information whether the parameter was read.
bool myFoundOrigNetBoundary
bool myFoundProj
Position & myNetOffset
The network offset to fill from values read from the network.
Boundary & myOrigNetBoundary
The original network boundary to fill from values read from the network.
std::string & myProjParameter
The projection parameter to fill from values read from the network.
Detailed Description
A reader for a SUMO network's projection description.
Definition at line 54 of file PCNetProjectionLoader.h.
Constructor & Destructor Documentation
PCNetProjectionLoader::PCNetProjectionLoader (Position & netOffset, Boundary & origNetBoundary, Boundary & convNetBoundary, std::string & projParameter) [protected]
Constructor.
Parameters:
[out] netOffset The network offset to fill from values read from the network
[out] origNetBoundary The original network boundary to fill from values read from the network
[out] convNetBoundary The converted network boundary to fill from values read from the network
[out] projParameter The projection parameter to fill from values read from the network
Definition at line 101 of file PCNetProjectionLoader.cpp.
PCNetProjectionLoader::~PCNetProjectionLoader () [protected]
Destructor.
Definition at line 111 of file PCNetProjectionLoader.cpp.
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
bool PCNetProjectionLoader::hasReadAll () const [protected]
Returns whether all needed values were read.
Returns:
Whether all needed values were read
Definition at line 147 of file PCNetProjectionLoader.cpp.
References myFoundConvNetBoundary, myFoundOffset, myFoundOrigNetBoundary, and myFoundProj.
Referenced by loadIfSet().
void PCNetProjectionLoader::loadIfSet (OptionsCont & oc, Position & netOffset, Boundary & origNetBoundary, Boundary & convNetBoundary, std::string & projParameter) [static]
Loads network projection if wished.
If the option "net" is set within the given options container, an instance of PCNetProjectionLoader is built and used as a handler for the file given in this option.
Parameters:
[in] oc The options container to get further options from
[out] netOffset The network offset to fill from values read from the network
[out] origNetBoundary The original network boundary to fill from values read from the network
[out] convNetBoundary The converted network boundary to fill from values read from the network
[out] projParameter The projection parameter to fill from values read from the network
Exceptions:
ProcessError if something fails
Definition at line 64 of file PCNetProjectionLoader.cpp.
References FileHelpers::exists(), GenericSAXHandler::getFileName(), XMLSubSys::getSAXReader(), OptionsCont::getString(), hasReadAll(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, and GenericSAXHandler::setFileName().
Referenced by main().
void PCNetProjectionLoader::myCharacters (int element, const std::string & chars) [protected, virtual]
Called when characters occure.
Parameters:
[in] element ID of the last opened element
[in] chars The read characters (complete)
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myCharacters
Reimplemented from GenericSAXHandler.
Definition at line 139 of file PCNetProjectionLoader.cpp.
References UNUSED_PARAMETER.
void GenericSAXHandler::myEndElement (int element) [protected, virtual, inherited]
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in MSRouteHandler, MSLaneSpeedTrigger, MSTriggeredRerouter, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_OpenStreetMap::NodesHandler, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_SUMO, NIXMLEdgesHandler, NIXMLTrafficLightsHandler, NLHandler, ODDistrictHandler, PCLoaderOSM::NodesHandler, PCLoaderOSM::EdgesHandler, RORDGenerator_ODAmounts, RORDLoader_SUMOBase, RORDLoader_TripDefs, and SAXWeightsHandler.
Definition at line 232 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void PCNetProjectionLoader::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 115 of file PCNetProjectionLoader.cpp.
References SUMOSAXAttributes::getObjectType(), SUMOSAXAttributes::getOptStringReporting(), myConvNetBoundary, myFoundConvNetBoundary, myFoundOffset, myFoundOrigNetBoundary, myFoundProj, myNetOffset, myOrigNetBoundary, myProjParameter, GeomConvHelper::parseBoundaryReporting(), GeomConvHelper::parseShapeReporting(), SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, SUMO_ATTR_ORIG_PROJ, and SUMO_TAG_LOCATION.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
Boundary& PCNetProjectionLoader::myConvNetBoundary [private]
The converted network boundary to fill from values read from the network.
Definition at line 129 of file PCNetProjectionLoader.h.
Referenced by myStartElement().
bool PCNetProjectionLoader::myFoundConvNetBoundary [private]
Definition at line 135 of file PCNetProjectionLoader.h.
Referenced by hasReadAll(), and myStartElement().
bool PCNetProjectionLoader::myFoundOffset [private]
Information whether the parameter was read.
Definition at line 135 of file PCNetProjectionLoader.h.
Referenced by hasReadAll(), and myStartElement().
bool PCNetProjectionLoader::myFoundOrigNetBoundary [private]
Definition at line 135 of file PCNetProjectionLoader.h.
Referenced by hasReadAll(), and myStartElement().
bool PCNetProjectionLoader::myFoundProj [private]
Definition at line 135 of file PCNetProjectionLoader.h.
Referenced by hasReadAll(), and myStartElement().
Position& PCNetProjectionLoader::myNetOffset [private]
The network offset to fill from values read from the network.
Definition at line 123 of file PCNetProjectionLoader.h.
Referenced by myStartElement().
Boundary& PCNetProjectionLoader::myOrigNetBoundary [private]
The original network boundary to fill from values read from the network.
Definition at line 126 of file PCNetProjectionLoader.h.
Referenced by myStartElement().
std::string& PCNetProjectionLoader::myProjParameter [private]
The projection parameter to fill from values read from the network.
Definition at line 132 of file PCNetProjectionLoader.h.
Referenced by myStartElement().
The documentation for this class was generated from the following files:
PCNetProjectionLoader.h
PCNetProjectionLoader.cpp