SUMO - Simulation of Urban MObility: NIImporter_ArcView Class Reference
NIImporter_ArcView Class Reference
Importer for networks stored in ArcView-shape format.
#include <NIImporter_ArcView.h>
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given ArcView Shape files.
Protected Member Functions
void load ()
Loads the shape files.
NIImporter_ArcView (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec, NBTypeCont &tc, const std::string &dbf_name, const std::string &shp_name, bool speedInKMH)
Constructor.
~NIImporter_ArcView ()
Destructor.
Private Member Functions
void checkSpread (NBEdge *e)
Checks whether the lane spread shall be changed.
unsigned int getLaneNo (OGRFeature &f, const std::string &edgeid, SUMOReal speed)
Parses the number of lanes of the edge currently processed.
int getPriority (OGRFeature &f, const std::string &edgeid)
Parses the priority of the edge currently processed.
SUMOReal getSpeed (OGRFeature &f, const std::string &edgeid)
Parses the maximum speed allowed on the edge currently processed.
NIImporter_ArcView (const NIImporter_ArcView &)
Invalidated copy constructor.
NIImporter_ArcView & operator= (const NIImporter_ArcView &)
Invalidated assignment operator.
Private Attributes
NBEdgeCont & myEdgeCont
The container to add edges to.
int myNameAddition
A running number to assure unique edge ids.
NBNodeCont & myNodeCont
The container to add nodes to.
const OptionsCont & myOptions
The options to use.
int myRunningNodeID
A running number to assure unique node ids.
std::string mySHPName
The name of the shape file.
bool mySpeedInKMH
Whether the speed is given in km/h.
NBTypeCont & myTypeCont
The container to get the types from.
Detailed Description
Importer for networks stored in ArcView-shape format.
The current importer works only if SUMO was compiled with GDAL-support. If not, an error message is generated.
Todo:
reinsert import via shapelib
Definition at line 56 of file NIImporter_ArcView.h.
Constructor & Destructor Documentation
NIImporter_ArcView::NIImporter_ArcView (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec, NBTypeCont & tc, const std::string & dbf_name, const std::string & shp_name, bool speedInKMH) [protected]
Constructor.
Parameters:
[in] oc Options container to read options from
[in] nc The node container to store nodes into
[in] ec The edge container to store edges into
[in] tc The type container to get edge types from
[in] dbf_name The name of the according database file
[in] shp_name The name of the according shape file
[in] speedInKMH Whether the speed shall be assumed to be given in km/h
Definition at line 105 of file NIImporter_ArcView.cpp.
References UNUSED_PARAMETER.
NIImporter_ArcView::~NIImporter_ArcView () [protected]
Destructor.
Definition at line 121 of file NIImporter_ArcView.cpp.
NIImporter_ArcView::NIImporter_ArcView (const NIImporter_ArcView &) [private]
Invalidated copy constructor.
Member Function Documentation
void NIImporter_ArcView::checkSpread (NBEdge * e) [private]
Checks whether the lane spread shall be changed.
If for the given edge an edge into the vice direction is already stored, both edges' lane spread functions are set to LANESPREAD_RIGHT.
Parameters:
[in] e The edge to check
Definition at line 381 of file NIImporter_ArcView.cpp.
References NBNode::getConnectionTo(), NBEdge::getFromNode(), NBEdge::getToNode(), LANESPREAD_RIGHT, and NBEdge::setLaneSpreadFunction().
Referenced by load().
unsigned int NIImporter_ArcView::getLaneNo (OGRFeature & f, const std::string & edgeid, SUMOReal speed) [private]
Parses the number of lanes of the edge currently processed.
Parameters:
[in] f The entry to read the lane number from
[in] edgeid The id of the edge for error output
[in] speed The edge's speed used to help determinig the edge's lane number
Definition at line 329 of file NIImporter_ArcView.cpp.
References NINavTeqHelper::getLaneNumber(), NBTypeCont::getNumLanes(), OptionsCont::getString(), OptionsCont::isSet(), myOptions, and myTypeCont.
Referenced by load().
int NIImporter_ArcView::getPriority (OGRFeature & f, const std::string & edgeid) [private]
Parses the priority of the edge currently processed.
Parameters:
[in] f The entry to read the priority from
[in] edgeid The id of the edge for error output
Definition at line 358 of file NIImporter_ArcView.cpp.
References NBTypeCont::getPriority(), OptionsCont::getString(), OptionsCont::isSet(), myOptions, and myTypeCont.
Referenced by load().
SUMOReal NIImporter_ArcView::getSpeed (OGRFeature & f, const std::string & edgeid) [private]
Parses the maximum speed allowed on the edge currently processed.
Parameters:
[in] f The entry to read the speed from
[in] edgeid The id of the edge for error output
Definition at line 304 of file NIImporter_ArcView.cpp.
References NBTypeCont::getSpeed(), OptionsCont::getString(), OptionsCont::isSet(), myOptions, myTypeCont, and SUMOReal.
Referenced by load().
void NIImporter_ArcView::load () [protected]
Loads the shape files.
Definition at line 125 of file NIImporter_ArcView.cpp.
References checkSpread(), OptionsCont::getBool(), getLaneNo(), NBTypeCont::getNumLanes(), getPriority(), NBTypeCont::getSpeed(), getSpeed(), OptionsCont::getString(), NBTypeCont::getWidth(), NBEdgeCont::insert(), NBNodeCont::insert(), OptionsCont::isSet(), LANESPREAD_CENTER, LANESPREAD_RIGHT, myEdgeCont, myNodeCont, myOptions, myRunningNodeID, mySHPName, mySpeedInKMH, myTypeCont, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, StringUtils::prune(), PositionVector::push_back_noDoublePos(), StringUtils::replace(), NBEdgeCont::retrieve(), NBNodeCont::retrieve(), PositionVector::reverse(), SUMOReal, toString(), NILoader::transformCoordinates(), WRITE_ERROR, and WRITE_WARNING.
void NIImporter_ArcView::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) [static]
Loads content of the optionally given ArcView Shape files.
If the option "shapefile-prefix" is set, the file stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "shapefile-prefix" is not set, this method simply returns.
Parameters:
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 71 of file NIImporter_ArcView.cpp.
References FileHelpers::exists(), OptionsCont::getBool(), NBNetBuilder::getEdgeCont(), MsgHandler::getErrorInstance(), NBNetBuilder::getNodeCont(), OptionsCont::getString(), NBNetBuilder::getTypeCont(), OptionsCont::isSet(), and WRITE_ERROR.
Referenced by NILoader::load().
NIImporter_ArcView& NIImporter_ArcView::operator= (const NIImporter_ArcView &) [private]
Invalidated assignment operator.
Field Documentation
NBEdgeCont& NIImporter_ArcView::myEdgeCont [private]
The container to add edges to.
Definition at line 144 of file NIImporter_ArcView.h.
Referenced by load().
int NIImporter_ArcView::myNameAddition [private]
A running number to assure unique edge ids.
Definition at line 138 of file NIImporter_ArcView.h.
NBNodeCont& NIImporter_ArcView::myNodeCont [private]
The container to add nodes to.
Definition at line 141 of file NIImporter_ArcView.h.
Referenced by load().
const OptionsCont& NIImporter_ArcView::myOptions [private]
The options to use.
Definition at line 132 of file NIImporter_ArcView.h.
Referenced by getLaneNo(), getPriority(), getSpeed(), and load().
int NIImporter_ArcView::myRunningNodeID [private]
A running number to assure unique node ids.
Definition at line 153 of file NIImporter_ArcView.h.
Referenced by load().
std::string NIImporter_ArcView::mySHPName [private]
The name of the shape file.
Definition at line 135 of file NIImporter_ArcView.h.
Referenced by load().
bool NIImporter_ArcView::mySpeedInKMH [private]
Whether the speed is given in km/h.
Definition at line 150 of file NIImporter_ArcView.h.
Referenced by load().
NBTypeCont& NIImporter_ArcView::myTypeCont [private]
The container to get the types from.
Definition at line 147 of file NIImporter_ArcView.h.
Referenced by getLaneNo(), getPriority(), getSpeed(), and load().
The documentation for this class was generated from the following files:
NIImporter_ArcView.h
NIImporter_ArcView.cpp