SUMO - Simulation of Urban MObility: NIVissimNodeDef_Edges Class Reference
NIVissimNodeDef_Edges Class Reference
#include <NIVissimNodeDef_Edges.h>
Data Structures
class id_matches
class lying_within_match
Public Member Functions
int buildNodeCluster ()
virtual SUMOReal getEdgePosition (int edgeid) const
NIVissimNodeDef_Edges (int id, const std::string &name, const NIVissimNodeParticipatingEdgeVector &edges)
virtual void searchAndSetConnections ()
virtual ~NIVissimNodeDef_Edges ()
Static Public Member Functions
static void clearDict ()
static void dict_assignConnectionsToNodes ()
static NIVissimNodeDef * dictionary (int id)
static bool dictionary (int id, NIVissimNodeDef *o)
static bool dictionary (int id, const std::string &name, const NIVissimNodeParticipatingEdgeVector &edges)
static size_t dictSize ()
static int getMaxID ()
Protected Attributes
NIVissimNodeParticipatingEdgeVector myEdges
int myID
std::string myName
Detailed Description
Definition at line 40 of file NIVissimNodeDef_Edges.h.
Constructor & Destructor Documentation
NIVissimNodeDef_Edges::NIVissimNodeDef_Edges (int id, const std::string & name, const NIVissimNodeParticipatingEdgeVector & edges)
Definition at line 54 of file NIVissimNodeDef_Edges.cpp.
Referenced by dictionary().
NIVissimNodeDef_Edges::~NIVissimNodeDef_Edges () [virtual]
Definition at line 59 of file NIVissimNodeDef_Edges.cpp.
References myEdges.
Member Function Documentation
int NIVissimNodeDef::buildNodeCluster () [inherited]
void NIVissimNodeDef::clearDict () [static, inherited]
Definition at line 132 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
void NIVissimNodeDef::dict_assignConnectionsToNodes () [static, inherited]
Definition at line 117 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
NIVissimNodeDef * NIVissimNodeDef::dictionary (int id) [static, inherited]
Definition at line 74 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
bool NIVissimNodeDef::dictionary (int id, NIVissimNodeDef * o) [static, inherited]
Definition at line 59 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict, and NIVissimNodeDef::myMaxID.
Referenced by NIVissimNodeDef_Poly::dictionary(), dictionary(), and NIVissimConnectionCluster::getPositionForEdge().
bool NIVissimNodeDef_Edges::dictionary (int id, const std::string & name, const NIVissimNodeParticipatingEdgeVector & edges) [static]
Definition at line 68 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeDef::dictionary(), and NIVissimNodeDef_Edges().
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse(), and searchAndSetConnections().
size_t NIVissimNodeDef::dictSize () [static, inherited]
Definition at line 125 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
SUMOReal NIVissimNodeDef_Edges::getEdgePosition (int edgeid) const [virtual]
Implements NIVissimNodeDef.
Definition at line 113 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeParticipatingEdge::getFromPos(), NIVissimNodeParticipatingEdge::getID(), NIVissimNodeParticipatingEdge::getToPos(), myEdges, and SUMOReal.
int NIVissimNodeDef::getMaxID () [static, inherited]
Definition at line 141 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myMaxID.
Referenced by NIImporter_Vissim::postLoadBuild().
void NIVissimNodeDef_Edges::searchAndSetConnections () [virtual]
Implements NIVissimNodeDef.
Definition at line 80 of file NIVissimNodeDef_Edges.cpp.
References Boundary::add(), dictionary(), NIVissimConnection::getFromGeomPosition(), NIVissimNodeParticipatingEdge::getFromPos(), NIVissimNodeParticipatingEdge::getID(), NIVissimConnection::getToGeomPosition(), NIVissimNodeParticipatingEdge::getToPos(), NIVissimEdge::myConnectionClusters, myEdges, NIVissimNodeDef::myID, and NIVissimConnection::setNodeCluster().
Field Documentation
NIVissimNodeParticipatingEdgeVector NIVissimNodeDef_Edges::myEdges [protected]
Definition at line 77 of file NIVissimNodeDef_Edges.h.
Referenced by getEdgePosition(), searchAndSetConnections(), and ~NIVissimNodeDef_Edges().
int NIVissimNodeDef::myID [protected, inherited]
Definition at line 58 of file NIVissimNodeDef.h.
Referenced by NIVissimNodeDef_Poly::searchAndSetConnections(), and searchAndSetConnections().
std::string NIVissimNodeDef::myName [protected, inherited]
Definition at line 59 of file NIVissimNodeDef.h.
The documentation for this class was generated from the following files:
NIVissimNodeDef_Edges.h
NIVissimNodeDef_Edges.cpp