SUMO - Simulation of Urban MObility: NIVissimVehicleType Class Reference
NIVissimVehicleType Class Reference
#include <NIVissimVehicleType.h>
Public Member Functions
NIVissimVehicleType (int id, const std::string &name, const std::string &category, SUMOReal length, const RGBColor &color, SUMOReal amax, SUMOReal dmax)
~NIVissimVehicleType ()
Static Public Member Functions
static void clearDict ()
static NIVissimVehicleType * dictionary (int id)
static bool dictionary (int id, NIVissimVehicleType *o)
static bool dictionary (int id, const std::string &name, const std::string &category, SUMOReal length, const RGBColor &color, SUMOReal amax, SUMOReal dmax)
Private Types
typedef std::map< int,
NIVissimVehicleType * > DictType
Private Attributes
SUMOReal myAMax
std::string myCategory
RGBColor myColor
SUMOReal myDMax
int myID
SUMOReal myLength
std::string myName
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 44 of file NIVissimVehicleType.h.
Member Typedef Documentation
typedef std::map<int, NIVissimVehicleType*> NIVissimVehicleType::DictType [private]
Definition at line 65 of file NIVissimVehicleType.h.
Constructor & Destructor Documentation
NIVissimVehicleType::NIVissimVehicleType (int id, const std::string & name, const std::string & category, SUMOReal length, const RGBColor & color, SUMOReal amax, SUMOReal dmax)
Definition at line 40 of file NIVissimVehicleType.cpp.
Referenced by dictionary().
NIVissimVehicleType::~NIVissimVehicleType ()
Definition at line 47 of file NIVissimVehicleType.cpp.
Member Function Documentation
void NIVissimVehicleType::clearDict () [static]
Definition at line 86 of file NIVissimVehicleType.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
NIVissimVehicleType * NIVissimVehicleType::dictionary (int id) [static]
Definition at line 77 of file NIVissimVehicleType.cpp.
References myDict.
bool NIVissimVehicleType::dictionary (int id, NIVissimVehicleType * o) [static]
Definition at line 66 of file NIVissimVehicleType.cpp.
References myDict.
bool NIVissimVehicleType::dictionary (int id, const std::string & name, const std::string & category, SUMOReal length, const RGBColor & color, SUMOReal amax, SUMOReal dmax) [static]
Definition at line 52 of file NIVissimVehicleType.cpp.
References NIVissimVehicleType().
Referenced by NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse().
Field Documentation
SUMOReal NIVissimVehicleType::myAMax [private]
Definition at line 63 of file NIVissimVehicleType.h.
std::string NIVissimVehicleType::myCategory [private]
Definition at line 60 of file NIVissimVehicleType.h.
RGBColor NIVissimVehicleType::myColor [private]
Definition at line 62 of file NIVissimVehicleType.h.
NIVissimVehicleType::DictType NIVissimVehicleType::myDict [static, private]
Definition at line 66 of file NIVissimVehicleType.h.
Referenced by clearDict(), and dictionary().
SUMOReal NIVissimVehicleType::myDMax [private]
Definition at line 63 of file NIVissimVehicleType.h.
int NIVissimVehicleType::myID [private]
Definition at line 58 of file NIVissimVehicleType.h.
SUMOReal NIVissimVehicleType::myLength [private]
Definition at line 61 of file NIVissimVehicleType.h.
std::string NIVissimVehicleType::myName [private]
Definition at line 59 of file NIVissimVehicleType.h.
The documentation for this class was generated from the following files:
NIVissimVehicleType.h
NIVissimVehicleType.cpp