SUMO - Simulation of Urban MObility: NIImporter_ITSUMO Class Reference
NIImporter_ITSUMO Class Reference
Importer for networks stored in ITSUMO format.
#include <NIImporter_ITSUMO.h>
Data Structures
class Handler
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given ITSUMO network files.
Private Types
enum ItsumoXMLAttr { ITSUMO_ATTR_NOTHING = 0 }
Numbers representing MATSIM-XML - attributes.
enum ItsumoXMLTag {
ITSUMO_TAG_NOTHING = 0, ITSUMO_TAG_SIMULATION, ITSUMO_TAG_NETWORK_ID, ITSUMO_TAG_NETWORK_NAME,
ITSUMO_TAG_NODES, ITSUMO_TAG_NODE, ITSUMO_TAG_NODE_ID, ITSUMO_TAG_NODE_NAME,
ITSUMO_TAG_X_COORD, ITSUMO_TAG_Y_COORD, ITSUMO_TAG_SOURCES, ITSUMO_TAG_SINKS,
ITSUMO_TAG_TRAFFIC_LIGHTS, ITSUMO_TAG_STREETS, ITSUMO_TAG_STREET, ITSUMO_TAG_STREET_ID,
ITSUMO_TAG_STREET_NAME, ITSUMO_TAG_SECTIONS, ITSUMO_TAG_SECTION, ITSUMO_TAG_SECTION_ID,
ITSUMO_TAG_SECTION_NAME, ITSUMO_TAG_IS_PREFERENCIAL, ITSUMO_TAG_DELIMITING_NODE, ITSUMO_TAG_LANESETS,
ITSUMO_TAG_LANESET, ITSUMO_TAG_LANESET_ID, ITSUMO_TAG_LANESET_POSITION, ITSUMO_TAG_START_NODE,
ITSUMO_TAG_END_NODE, ITSUMO_TAG_TURNING_PROBABILITIES, ITSUMO_TAG_DIRECTION, ITSUMO_TAG_DESTINATION_LANESET,
ITSUMO_TAG_PROBABILITY, ITSUMO_TAG_LANES, ITSUMO_TAG_LANE, ITSUMO_TAG_LANE_ID,
ITSUMO_TAG_LANE_POSITION, ITSUMO_TAG_MAXIMUM_SPEED, ITSUMO_TAG_DECELERATION_PROB
}
Numbers representing ITSUMO-XML - element names.
Static Private Attributes
static StringBijection< int >
::Entry itsumoAttrs []
The names of MATSIM-XML attributes (for passing to GenericSAXHandler).
static StringBijection< int >
::Entry itsumoTags []
The names of MATSIM-XML elements (for passing to GenericSAXHandler).
Detailed Description
Importer for networks stored in ITSUMO format.
Definition at line 61 of file NIImporter_ITSUMO.h.
Member Enumeration Documentation
enum NIImporter_ITSUMO::ItsumoXMLAttr [private]
Numbers representing MATSIM-XML - attributes.
See also:
GenericSAXHandler
Enumerator:
ITSUMO_ATTR_NOTHING
Definition at line 238 of file NIImporter_ITSUMO.h.
enum NIImporter_ITSUMO::ItsumoXMLTag [private]
Numbers representing ITSUMO-XML - element names.
See also:
GenericSAXHandler
Enumerator:
ITSUMO_TAG_NOTHING
ITSUMO_TAG_SIMULATION
ITSUMO_TAG_NETWORK_ID
ITSUMO_TAG_NETWORK_NAME
ITSUMO_TAG_NODES
ITSUMO_TAG_NODE
ITSUMO_TAG_NODE_ID
ITSUMO_TAG_NODE_NAME
ITSUMO_TAG_X_COORD
ITSUMO_TAG_Y_COORD
ITSUMO_TAG_SOURCES
ITSUMO_TAG_SINKS
ITSUMO_TAG_TRAFFIC_LIGHTS
ITSUMO_TAG_STREETS
ITSUMO_TAG_STREET
ITSUMO_TAG_STREET_ID
ITSUMO_TAG_STREET_NAME
ITSUMO_TAG_SECTIONS
ITSUMO_TAG_SECTION
ITSUMO_TAG_SECTION_ID
ITSUMO_TAG_SECTION_NAME
ITSUMO_TAG_IS_PREFERENCIAL
ITSUMO_TAG_DELIMITING_NODE
ITSUMO_TAG_LANESETS
ITSUMO_TAG_LANESET
ITSUMO_TAG_LANESET_ID
ITSUMO_TAG_LANESET_POSITION
ITSUMO_TAG_START_NODE
ITSUMO_TAG_END_NODE
ITSUMO_TAG_TURNING_PROBABILITIES
ITSUMO_TAG_DIRECTION
ITSUMO_TAG_DESTINATION_LANESET
ITSUMO_TAG_PROBABILITY
ITSUMO_TAG_LANES
ITSUMO_TAG_LANE
ITSUMO_TAG_LANE_ID
ITSUMO_TAG_LANE_POSITION
ITSUMO_TAG_MAXIMUM_SPEED
ITSUMO_TAG_DECELERATION_PROB
Definition at line 190 of file NIImporter_ITSUMO.h.
Member Function Documentation
void NIImporter_ITSUMO::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) [static]
Loads content of the optionally given ITSUMO network files.
If the option "itsumo-files" is set, the file(s) stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "itsumo-files" is not set, this method simply returns.
Parameters:
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 115 of file NIImporter_ITSUMO.cpp.
References FileHelpers::exists(), OptionsCont::getStringVector(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, XMLSubSys::runParser(), GenericSAXHandler::setFileName(), and WRITE_ERROR.
Referenced by NILoader::load().
Field Documentation
StringBijection< int >::Entry NIImporter_ITSUMO::itsumoAttrs [static, private]
Initial value:
 {
    { "",               NIImporter_ITSUMO::ITSUMO_ATTR_NOTHING }
}
The names of MATSIM-XML attributes (for passing to GenericSAXHandler).
Definition at line 246 of file NIImporter_ITSUMO.h.
StringBijection< int >::Entry NIImporter_ITSUMO::itsumoTags [static, private]
The names of MATSIM-XML elements (for passing to GenericSAXHandler).
Definition at line 243 of file NIImporter_ITSUMO.h.
The documentation for this class was generated from the following files:
NIImporter_ITSUMO.h
NIImporter_ITSUMO.cpp