SUMO - Simulation of Urban MObility: NBEdge::MainDirections Class Reference
NBEdge::MainDirections Class Reference
Public Types
enum Direction { DIR_RIGHTMOST, DIR_LEFTMOST, DIR_FORWARD }
enum of possible directions
Public Member Functions
bool empty () const
bool includes (Direction d) const
MainDirections (const EdgeVector &outgoing, NBEdge *parent, NBNode *to)
constructor
~MainDirections ()
destructor
Data Fields
std::vector< Direction > myDirs
Private Member Functions
MainDirections (const MainDirections &)
Invalidated copy constructor.
MainDirections & operator= (const MainDirections &)
Invalidated assignment operator.
Detailed Description
MainDirections Holds (- relative to the edge it is build from -!!!) the list of main directions a vehicle that drives on this street may take on the junction the edge ends in The back direction is not regarded
Definition at line 1010 of file NBEdge.h.
Member Enumeration Documentation
enum NBEdge::MainDirections::Direction
enum of possible directions
Enumerator:
DIR_RIGHTMOST
DIR_LEFTMOST
DIR_FORWARD
Definition at line 1013 of file NBEdge.h.
Constructor & Destructor Documentation
NBEdge::MainDirections::MainDirections (const EdgeVector & outgoing, NBEdge * parent, NBNode * to)
constructor
Definition at line 106 of file NBEdge.cpp.
References DIR_FORWARD, DIR_LEFTMOST, DIR_RIGHTMOST, NBNode::getDirection(), NBEdge::getJunctionPriority(), LINKDIR_STRAIGHT, and myDirs.
NBEdge::MainDirections::~MainDirections ()
destructor
Definition at line 143 of file NBEdge.cpp.
NBEdge::MainDirections::MainDirections (const MainDirections &) [private]
Invalidated copy constructor.
Member Function Documentation
bool NBEdge::MainDirections::empty () const
returns the information whether no following street has a higher priority
Definition at line 147 of file NBEdge.cpp.
References myDirs.
Referenced by NBEdge::preparePriorities().
bool NBEdge::MainDirections::includes (Direction d) const
returns the information whether the street in the given direction has a higher priority
Definition at line 153 of file NBEdge.cpp.
References myDirs.
Referenced by NBEdge::preparePriorities().
MainDirections& NBEdge::MainDirections::operator= (const MainDirections &) [private]
Invalidated assignment operator.
Field Documentation
std::vector<Direction> NBEdge::MainDirections::myDirs
list of the main direction within the following junction relative to the edge
Definition at line 1017 of file NBEdge.h.
Referenced by empty(), includes(), and MainDirections().
The documentation for this class was generated from the following files:
NBEdge.h
NBEdge.cpp