SUMO - Simulation of Urban MObility: MSActuatedTrafficLightLogic Class Reference
MSActuatedTrafficLightLogic Class Reference
An actuated (adaptive) traffic light logic.
#include <MSActuatedTrafficLightLogic.h>
Public Types
typedef std::map< MSLane
*, MSInductLoop * > InductLoopMap
Definition of a map from lanes to induct loops lying on them.
Structure definitions
typedef std::vector< MSLane * > LaneVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector< MSLink * > LinkVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LinkVector > LinkVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector
< MSPhaseDefinition * > Phases
Definition of a list of phases, being the junction logic.
Public Member Functions
void init (NLDetectorBuilder &nb)
Initialises the tls with information about incoming lanes.
MSActuatedTrafficLightLogic (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &programID, const MSSimpleTrafficLightLogic::Phases &phases, unsigned int step, SUMOTime delay, const std::map< std::string, std::string > &parameter)
Constructor.
~MSActuatedTrafficLightLogic ()
Destructor.
Handling of controlled links
virtual void adaptLinkInformationFrom (const MSTrafficLightLogic &logic)
Applies information about controlled links and lanes from the given logic.
void addLink (MSLink *link, MSLane *lane, unsigned int pos)
Adds a link on building.
std::map< MSLink *, LinkState > collectLinkStates () const
Returns the (uncontrolled) states of the controlled links.
void resetLinkStates (const std::map< MSLink *, LinkState > &vals) const
Resets the states of controlled links.
Changing phases and phase durations
void addOverridingDuration (SUMOTime duration)
Changes the duration of the next phase.
void setCurrentDurationIncrement (SUMOTime delay)
Delays current phase by the given delay.
Changing phases and phase durations
void changeStepAndDuration (MSTLLogicControl &tlcontrol, SUMOTime simStep, unsigned int step, SUMOTime stepDuration)
Changes the current phase and her duration.
void setPhases (const Phases &phases)
Replaces the phases.
Dynamic Information Retrieval
const MSPhaseDefinition & getCurrentPhaseDef () const
Returns the definition of the current phase.
unsigned int getCurrentPhaseIndex () const
Returns the current index within the program.
Dynamic Information Retrieval
SUMOTime getDefaultCycleTime () const
Returns the cycle time (in ms).
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
Static Information Retrieval
const std::string & getID () const
Returns this tl-logic's id.
const LaneVectorVector & getLanes () const
Returns the list of lists of all lanes controlled by this tls.
const LaneVector & getLanesAt (unsigned int i) const
Returns the list of lanes that are controlled by the signals at the given position.
int getLinkIndex (const MSLink *const link) const
Returns the index of the given link.
const LinkVectorVector & getLinks () const
Returns the list of lists of all affected links.
const LinkVector & getLinksAt (unsigned int i) const
Returns the list of links that are controlled by the signals at the given position.
const std::string & getProgramID () const
Returns this tl-logic's id.
Conversion between time and phase
unsigned int getIndexFromOffset (SUMOTime offset) const
Returns the step (the phasenumber) of a given position of the cycle.
SUMOTime getOffsetFromIndex (unsigned int index) const
Returns the position (start of a phase during a cycle) from of a given step.
SUMOTime getPhaseIndexAtTime (SUMOTime simStep) const
Returns the index of the logic at the given simulation step.
Algorithm parameter handling
std::string getParameterValue (const std::string &key) const
Returns a named parameter.
void setParameter (const std::map< std::string, std::string > &params)
Inserts read parameter.
Static Information Retrieval
const MSPhaseDefinition & getPhase (unsigned int givenstep) const
Returns the definition of the phase from the given position within the plan.
unsigned int getPhaseNumber () const
Returns the number of phases.
Phases & getPhases ()
Returns the phases of this tls program.
const Phases & getPhases () const
Returns the phases of this tls program.
Switching and setting current rows
bool setTrafficLightSignals (SUMOTime t) const
Applies the current signal states to controlled links.
Switching and setting current rows
SUMOTime trySwitch (bool isActive)
Switches to the next phase.
Protected Member Functions
"actuated" algorithm methods
SUMOTime duration () const
Returns the duration of the given step.
void gapControl ()
Decides, whether a phase should be continued by checking the gaps of vehicles having green.
Protected Attributes
bool myContinue
information whether the current phase should be lenghtend
SUMOTime myCurrentDurationIncrement
A value for enlarge the current duration.
SUMOTime myDefaultCycleTime
The cycle time (without changes).
SUMOReal myDetectorGap
The detector distance.
std::string myID
The id of the logic.
InductLoopMap myInductLoops
A map from lanes to induct loops lying on them.
LaneVectorVector myLanes
The list of links which do participate in this traffic light.
LinkVectorVector myLinks
The list of links which do participate in this traffic light.
SUMOReal myMaxGap
The maximum gap to check.
std::vector< SUMOTime > myOverridingTimes
A list of duration overrides.
std::map< std::string,
std::string > myParameter
Given parameter.
SUMOReal myPassingTime
The passing time used.
Phases myPhases
The list of phases this logic uses.
std::string myProgramID
unsigned int myStep
The current step.
SwitchCommand * mySwitchCommand
The current switch command.
Detailed Description
An actuated (adaptive) traffic light logic.
Definition at line 57 of file MSActuatedTrafficLightLogic.h.
Member Typedef Documentation
typedef std::map<MSLane*, MSInductLoop*> MSActuatedTrafficLightLogic::InductLoopMap
Definition of a map from lanes to induct loops lying on them.
Definition at line 61 of file MSActuatedTrafficLightLogic.h.
typedef std::vector<MSLane*> MSTrafficLightLogic::LaneVector [inherited]
Definition of the list of links that participate in this tl-light.
Definition at line 77 of file MSTrafficLightLogic.h.
typedef std::vector<LaneVector> MSTrafficLightLogic::LaneVectorVector [inherited]
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 80 of file MSTrafficLightLogic.h.
typedef std::vector<MSLink*> MSTrafficLightLogic::LinkVector [inherited]
Definition of the list of links that participate in this tl-light.
Definition at line 71 of file MSTrafficLightLogic.h.
typedef std::vector<LinkVector> MSTrafficLightLogic::LinkVectorVector [inherited]
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 74 of file MSTrafficLightLogic.h.
typedef std::vector<MSPhaseDefinition*> MSTrafficLightLogic::Phases [inherited]
Definition of a list of phases, being the junction logic.
Definition at line 68 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & programID, const MSSimpleTrafficLightLogic::Phases & phases, unsigned int step, SUMOTime delay, const std::map< std::string, std::string > & parameter)
Constructor.
Parameters:
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] programID This tls' sub-id (program id)
[in] phases Definitions of the phases
[in] step The initial phase index
[in] delay The time to wait before the first switch
[in] parameter The parameter to use for tls set-up
Definition at line 55 of file MSActuatedTrafficLightLogic.cpp.
References myDetectorGap, myMaxGap, myPassingTime, and SUMOReal.
MSActuatedTrafficLightLogic::~MSActuatedTrafficLightLogic ()
Destructor.
Definition at line 116 of file MSActuatedTrafficLightLogic.cpp.
References myInductLoops.
Member Function Documentation
void MSTrafficLightLogic::adaptLinkInformationFrom (const MSTrafficLightLogic & logic) [virtual, inherited]
Applies information about controlled links and lanes from the given logic.
If we load a logic after the network has been loaded, we do not get the information about controlled links afterwards. We have to copy them from a previously loaded logic.
Parameters:
[in] logic The logic to use the information about controlled links/lanes from
Reimplemented in MSOffTrafficLightLogic.
Definition at line 143 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLanes, and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic().
void MSTrafficLightLogic::addLink (MSLink * link, MSLane * lane, unsigned int pos) [inherited]
Adds a link on building.
Parameters:
[in] link The controlled link
[in] lane The lane this link starts at
[in] pos The link's index (signal group) within this program
Definition at line 125 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, and MSLink::setTLState().
void MSTrafficLightLogic::addOverridingDuration (SUMOTime duration) [inherited]
Changes the duration of the next phase.
Parameters:
[in] duration The new duration
Definition at line 216 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myOverridingTimes.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
void MSSimpleTrafficLightLogic::changeStepAndDuration (MSTLLogicControl & tlcontrol, SUMOTime simStep, unsigned int step, SUMOTime stepDuration) [virtual, inherited]
Changes the current phase and her duration.
Parameters:
[in] tlcontrol The responsible traffic lights control
[in] simStep The current simulation step
[in] step Index of the phase to use
[in] stepDuration The left duration of the phase
See also:
MSTrafficLightLogic::changeStepAndDuration
Implements MSTrafficLightLogic.
Definition at line 191 of file MSSimpleTrafficLightLogic.cpp.
References MSEventControl::ADAPT_AFTER_EXECUTION, MSEventControl::addEvent(), MSTrafficLightLogic::SwitchCommand::deschedule(), MSNet::getBeginOfTimestepEvents(), MSNet::getInstance(), MSSimpleTrafficLightLogic::myStep, and MSTrafficLightLogic::mySwitchCommand.
Referenced by GUIViewTraffic::onGamingClick().
std::map< MSLink *, LinkState > MSTrafficLightLogic::collectLinkStates () const [inherited]
Returns the (uncontrolled) states of the controlled links.
Returns:
The controlled link's states
Definition at line 150 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::saveInitialStates().
SUMOTime MSActuatedTrafficLightLogic::duration () const [protected]
Returns the duration of the given step.
Returns:
The wanted duration of the current step
Definition at line 146 of file MSActuatedTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getLanesAt(), MSPhaseDefinition::getState(), MSPhaseDefinition::isGreenPhase(), LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, MSPhaseDefinition::maxDuration, MSPhaseDefinition::minDuration, myContinue, myInductLoops, myPassingTime, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, and SUMOReal.
Referenced by trySwitch().
void MSActuatedTrafficLightLogic::gapControl () [protected]
Decides, whether a phase should be continued by checking the gaps of vehicles having green.
Definition at line 182 of file MSActuatedTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTrafficLightLogic::getLanesAt(), MSPhaseDefinition::getState(), MSPhaseDefinition::isGreenPhase(), LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, myContinue, myInductLoops, myMaxGap, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, and SUMOReal.
Referenced by trySwitch().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getCurrentPhaseDef () const [virtual, inherited]
Returns the definition of the current phase.
Returns:
The current phase
See also:
MSTrafficLightLogic::getCurrentPhaseDef
Implements MSTrafficLightLogic.
Definition at line 133 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSAgentbasedTrafficLightLogic::collectData(), duration(), gapControl(), and MSAgentbasedTrafficLightLogic::trySwitch().
unsigned int MSSimpleTrafficLightLogic::getCurrentPhaseIndex () const [virtual, inherited]
Returns the current index within the program.
Returns:
The index of the current phase within the tls
See also:
MSTrafficLightLogic::getCurrentPhaseIndex
Implements MSTrafficLightLogic.
Definition at line 127 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myStep.
SUMOTime MSTrafficLightLogic::getDefaultCycleTime () const [inline, inherited]
Returns the cycle time (in ms).
Returns:
The (maybe changing) cycle time of this tls
Definition at line 263 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myDefaultCycleTime.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), and MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
const std::string& MSTrafficLightLogic::getID () const [inline, inherited]
Returns this tl-logic's id.
Returns:
This tls' id
Definition at line 170 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myID.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUITrafficLightLogicWrapper::begin2TrackPhases(), GUINet::createTLWrapper(), MSTrafficLightLogic::SwitchCommand::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), Command_SaveTLSState::execute(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSTLLogicControl::isActive(), GUIViewTraffic::onGamingClick(), and GUITrafficLightLogicWrapper::switchTLSLogic().
unsigned int MSSimpleTrafficLightLogic::getIndexFromOffset (SUMOTime offset) const [virtual, inherited]
Returns the step (the phasenumber) of a given position of the cycle.
Parameters:
[in] offset The offset (time) for which the according phase shall be returned
Returns:
The according phase
See also:
MSTrafficLightLogic::getIndexFromOffset
Implements MSTrafficLightLogic.
Definition at line 169 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, and MSSimpleTrafficLightLogic::myPhases.
const LaneVectorVector& MSTrafficLightLogic::getLanes () const [inline, inherited]
Returns the list of lists of all lanes controlled by this tls.
Returns:
All lanes controlled by this tls, sorted by the signal index
Definition at line 186 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::getCenteringBoundary(), and TraCIServerAPI_TLS::processGet().
const LaneVector& MSTrafficLightLogic::getLanesAt (unsigned int i) const [inline, inherited]
Returns the list of lanes that are controlled by the signals at the given position.
Parameters:
[in] i The index of the signal
Returns:
The lanes controlled by the signal at the given index
Definition at line 195 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by MSAgentbasedTrafficLightLogic::collectData(), GUITrafficLightLogicWrapper::drawGL(), duration(), Command_SaveTLSSwitches::execute(), gapControl(), and GUIViewTraffic::onGamingClick().
int MSTrafficLightLogic::getLinkIndex (const MSLink *const link) const [inherited]
Returns the index of the given link.
Parameters:
[in] link The link to retrieve the index for
Returns:
The index of the given link (-1 if it is not controlled by this tls)
Definition at line 192 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by GUITrafficLightLogicWrapper::getLinkIndex().
const LinkVectorVector& MSTrafficLightLogic::getLinks () const [inline, inherited]
Returns the list of lists of all affected links.
Returns:
All links controlled by this tls, sorted by the signal index
Definition at line 203 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUINet::createTLWrapper(), GUITLLogicPhasesTrackerWindow::drawValues(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), TraCIServerAPI_TLS::processGet(), and MSOffTrafficLightLogic::rebuildPhase().
const LinkVector& MSTrafficLightLogic::getLinksAt (unsigned int i) const [inline, inherited]
Returns the list of links that are controlled by the signals at the given position.
Parameters:
[in] i The index of the signal
Returns:
The links controlled by the signal at the given index
Definition at line 212 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
SUMOTime MSTrafficLightLogic::getNextSwitchTime () const [inherited]
Returns the assumed next switch time.
The time may change in case of adaptive/actuated traffic lights.
Returns:
The assumed next switch time (simulation time)
Definition at line 209 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::SwitchCommand::getNextSwitchTime(), and MSTrafficLightLogic::mySwitchCommand.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), and TraCIServerAPI_TLS::processGet().
SUMOTime MSSimpleTrafficLightLogic::getOffsetFromIndex (unsigned int index) const [virtual, inherited]
Returns the position (start of a phase during a cycle) from of a given step.
Parameters:
[in] index The index of the phase to return the begin of
Returns:
The begin time of the phase
See also:
MSTrafficLightLogic::getOffsetFromIndex
Implements MSTrafficLightLogic.
Definition at line 155 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), and MSSimpleTrafficLightLogic::myPhases.
std::string MSTrafficLightLogic::getParameterValue (const std::string & key) const [inherited]
Returns a named parameter.
Parameters:
[in] key The name of the parameter
Returns:
The value of the parameter, "" if the parameter is not known
Definition at line 237 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myParameter.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getPhase (unsigned int givenstep) const [virtual, inherited]
Returns the definition of the phase from the given position within the plan.
Parameters:
[in] givenstep The index of the phase within the plan
Returns:
The definition of the phase at the given position
See also:
MSTrafficLightLogic::getPhase
Implements MSTrafficLightLogic.
Definition at line 119 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), and GUIViewTraffic::onGamingClick().
SUMOTime MSSimpleTrafficLightLogic::getPhaseIndexAtTime (SUMOTime simStep) const [virtual, inherited]
Returns the index of the logic at the given simulation step.
Returns:
The (estimated) index of the tls at the given simulation time step
See also:
MSTrafficLightLogic::getPhaseIndexAtTime
Implements MSTrafficLightLogic.
Definition at line 140 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, MSPhaseDefinition::myLastSwitch, and MSSimpleTrafficLightLogic::myStep.
unsigned int MSSimpleTrafficLightLogic::getPhaseNumber () const [virtual, inherited]
Returns the number of phases.
Returns:
The number of this tls program's phases
See also:
MSTrafficLightLogic::getPhaseNumber
Implements MSTrafficLightLogic.
Definition at line 101 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () [inherited]
Returns the phases of this tls program.
Returns:
The phases of this tls program
Todo:
Recheck!
Definition at line 113 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () const [virtual, inherited]
Returns the phases of this tls program.
Returns:
The phases of this tls program
See also:
MSTrafficLightLogic::getPhases
Implements MSTrafficLightLogic.
Definition at line 107 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const std::string& MSTrafficLightLogic::getProgramID () const [inline, inherited]
Returns this tl-logic's id.
Returns:
This program's id
Definition at line 178 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myProgramID.
Referenced by Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), Command_SaveTLSState::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), GUIViewTraffic::onGamingClick(), and TraCIServerAPI_TLS::processGet().
void MSActuatedTrafficLightLogic::init (NLDetectorBuilder & nb) [virtual]
Initialises the tls with information about incoming lanes.
Parameters:
[in] nb The detector builder
Exceptions:
ProcessError If something fails on initialisation
Reimplemented from MSTrafficLightLogic.
Definition at line 77 of file MSActuatedTrafficLightLogic.cpp.
References NLDetectorBuilder::createInductLoop(), Named::getID(), MSLane::getLength(), MSLane::getMaxSpeed(), myDetectorGap, MSTrafficLightLogic::myID, myInductLoops, MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myParameter, MSTrafficLightLogic::myProgramID, and SUMOReal.
void MSTrafficLightLogic::resetLinkStates (const std::map< MSLink *, LinkState > & vals) const [inherited]
Resets the states of controlled links.
Parameters:
[in] vals The state of controlled links to use
Definition at line 179 of file MSTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::myLinks.
void MSTrafficLightLogic::setCurrentDurationIncrement (SUMOTime delay) [inherited]
Delays current phase by the given delay.
Parameters:
[in] delay The time by which the current phase shall be delayed
Definition at line 222 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myCurrentDurationIncrement.
void MSTrafficLightLogic::setParameter (const std::map< std::string, std::string > & params) [inherited]
Inserts read parameter.
Parameters:
[in] params The parameter to use
Definition at line 231 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myParameter.
Referenced by NLJunctionControlBuilder::closeTrafficLightLogic().
void MSSimpleTrafficLightLogic::setPhases (const Phases & phases) [inherited]
Replaces the phases.
Definition at line 203 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::deletePhases(), and MSSimpleTrafficLightLogic::myPhases.
bool MSTrafficLightLogic::setTrafficLightSignals (SUMOTime t) const [inherited]
Applies the current signal states to controlled links.
Parameters:
[in] t The current time
Returns:
Always true
See also:
LinkState
MSLink::setTLState
Definition at line 163 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSTrafficLightLogic::SwitchCommand::execute(), and TraCIServerAPI_TLS::processSet().
SUMOTime MSActuatedTrafficLightLogic::trySwitch (bool isActive) [virtual]
Switches to the next phase.
Parameters:
[in] isActive Whether this program is the currently used one
Returns:
The time of the next switch
See also:
MSTrafficLightLogic::trySwitch
Reimplemented from MSSimpleTrafficLightLogic.
Definition at line 125 of file MSActuatedTrafficLightLogic.cpp.
References duration(), gapControl(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), myContinue, MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Field Documentation
bool MSActuatedTrafficLightLogic::myContinue [protected]
information whether the current phase should be lenghtend
Definition at line 125 of file MSActuatedTrafficLightLogic.h.
Referenced by duration(), gapControl(), and trySwitch().
SUMOTime MSTrafficLightLogic::myCurrentDurationIncrement [protected, inherited]
A value for enlarge the current duration.
Definition at line 427 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::setCurrentDurationIncrement(), and MSSimpleTrafficLightLogic::trySwitch().
SUMOTime MSTrafficLightLogic::myDefaultCycleTime [protected, inherited]
The cycle time (without changes).
Definition at line 433 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getDefaultCycleTime(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSOffTrafficLightLogic::MSOffTrafficLightLogic(), and MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic().
SUMOReal MSActuatedTrafficLightLogic::myDetectorGap [protected]
The detector distance.
Definition at line 134 of file MSActuatedTrafficLightLogic.h.
Referenced by init(), and MSActuatedTrafficLightLogic().
std::string MSTrafficLightLogic::myID [protected, inherited]
The id of the logic.
Definition at line 415 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getID(), MSAgentbasedTrafficLightLogic::init(), and init().
InductLoopMap MSActuatedTrafficLightLogic::myInductLoops [protected]
A map from lanes to induct loops lying on them.
Definition at line 122 of file MSActuatedTrafficLightLogic.h.
Referenced by duration(), gapControl(), init(), and ~MSActuatedTrafficLightLogic().
LaneVectorVector MSTrafficLightLogic::myLanes [protected, inherited]
The list of links which do participate in this traffic light.
Definition at line 421 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSTrafficLightLogic::getLanes(), MSTrafficLightLogic::getLanesAt(), MSAgentbasedTrafficLightLogic::init(), and init().
LinkVectorVector MSTrafficLightLogic::myLinks [protected, inherited]
The list of links which do participate in this traffic light.
Definition at line 418 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSTrafficLightLogic::collectLinkStates(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), MSTrafficLightLogic::resetLinkStates(), and MSTrafficLightLogic::setTrafficLightSignals().
SUMOReal MSActuatedTrafficLightLogic::myMaxGap [protected]
The maximum gap to check.
Definition at line 128 of file MSActuatedTrafficLightLogic.h.
Referenced by gapControl(), and MSActuatedTrafficLightLogic().
std::vector<SUMOTime> MSTrafficLightLogic::myOverridingTimes [protected, inherited]
A list of duration overrides.
Definition at line 424 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::addOverridingDuration(), and MSSimpleTrafficLightLogic::trySwitch().
std::map<std::string, std::string> MSTrafficLightLogic::myParameter [protected, inherited]
Given parameter.
Definition at line 412 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getParameterValue(), MSAgentbasedTrafficLightLogic::init(), init(), and MSTrafficLightLogic::setParameter().
SUMOReal MSActuatedTrafficLightLogic::myPassingTime [protected]
The passing time used.
Definition at line 131 of file MSActuatedTrafficLightLogic.h.
Referenced by duration(), and MSActuatedTrafficLightLogic().
Phases MSSimpleTrafficLightLogic::myPhases [protected, inherited]
The list of phases this logic uses.
Definition at line 194 of file MSSimpleTrafficLightLogic.h.
Referenced by MSAgentbasedTrafficLightLogic::calculateDuration(), MSAgentbasedTrafficLightLogic::cutCycleTime(), MSSimpleTrafficLightLogic::deletePhases(), duration(), MSAgentbasedTrafficLightLogic::findStepOfMaxValue(), MSAgentbasedTrafficLightLogic::findStepOfMinValue(), gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhase(), MSSimpleTrafficLightLogic::getPhaseNumber(), MSSimpleTrafficLightLogic::getPhases(), MSAgentbasedTrafficLightLogic::init(), MSAgentbasedTrafficLightLogic::lengthenCycleTime(), MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic(), MSAgentbasedTrafficLightLogic::nextStep(), MSSimpleTrafficLightLogic::setPhases(), MSSimpleTrafficLightLogic::trySwitch(), MSAgentbasedTrafficLightLogic::trySwitch(), and trySwitch().
std::string MSTrafficLightLogic::myProgramID [protected, inherited]
Definition at line 415 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getProgramID(), MSAgentbasedTrafficLightLogic::init(), and init().
unsigned int MSSimpleTrafficLightLogic::myStep [protected, inherited]
The current step.
Definition at line 197 of file MSSimpleTrafficLightLogic.h.
Referenced by MSAgentbasedTrafficLightLogic::calculateDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSAgentbasedTrafficLightLogic::collectData(), duration(), gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getCurrentPhaseIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSAgentbasedTrafficLightLogic::nextStep(), MSSimpleTrafficLightLogic::trySwitch(), MSAgentbasedTrafficLightLogic::trySwitch(), and trySwitch().
SwitchCommand* MSTrafficLightLogic::mySwitchCommand [protected, inherited]
The current switch command.
Definition at line 430 of file MSTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::MSTrafficLightLogic(), and MSTrafficLightLogic::~MSTrafficLightLogic().
The documentation for this class was generated from the following files:
MSActuatedTrafficLightLogic.h
MSActuatedTrafficLightLogic.cpp