SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::EdgesHandler Class Reference
NIImporter_DlrNavteq::EdgesHandler Class Reference
Importer of edges stored in unsplit elmar format.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
EdgesHandler (NBNodeCont &nc, NBEdgeCont &ec, const std::string &file, std::map< std::string, PositionVector > &geoms)
Constructor.
bool report (const std::string &result)
Parsing method.
~EdgesHandler ()
Destructor.
Protected Attributes
NBEdgeCont & myEdgeCont
The edge container to store loaded edges into.
std::map< std::string,
PositionVector > & myGeoms
Previously read edge geometries.
NBNodeCont & myNodeCont
The node container to get the referenced nodes from.
bool myTryIgnoreNodePositions
Whether node positions shall not be added to the edge's geometry.
Private Member Functions
EdgesHandler (const EdgesHandler &)
Invalidated copy constructor.
EdgesHandler & operator= (const EdgesHandler &)
Invalidated assignment operator.
Detailed Description
Importer of edges stored in unsplit elmar format.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain edge definitions in DLRNavteq's unsplit format.
Definition at line 140 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
NIImporter_DlrNavteq::EdgesHandler::EdgesHandler (NBNodeCont & nc, NBEdgeCont & ec, const std::string & file, std::map< std::string, PositionVector > & geoms)
Constructor.
Parameters:
[in] nc The node control to retrieve nodes from
in,filled] ec The edge control to insert loaded edges into
[in] file The name of the parsed file
[in] geoms The previously read edge geometries
Definition at line 184 of file NIImporter_DlrNavteq.cpp.
References UNUSED_PARAMETER.
NIImporter_DlrNavteq::EdgesHandler::~EdgesHandler ()
Destructor.
Definition at line 193 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::EdgesHandler::EdgesHandler (const EdgesHandler &) [private]
Invalidated copy constructor.
Member Function Documentation
EdgesHandler& NIImporter_DlrNavteq::EdgesHandler::operator= (const EdgesHandler &) [private]
Invalidated assignment operator.
bool NIImporter_DlrNavteq::EdgesHandler::report (const std::string & result) [virtual]
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores it into "myEdgeCont".
Parameters:
[in] result The read line
Returns:
Whether the parsing shall continue
Exceptions:
ProcessError if something fails
See also:
LineHandler::report
Implements LineHandler.
Definition at line 197 of file NIImporter_DlrNavteq.cpp.
References NINavTeqHelper::addVehicleClasses(), NINavTeqHelper::getLaneNumber(), NBNode::getPosition(), NINavTeqHelper::getSpeed(), StringTokenizer::getVector(), NBEdgeCont::insert(), LANESPREAD_CENTER, myEdgeCont, myGeoms, myNodeCont, StringTokenizer::next(), PositionVector::push_back(), PositionVector::push_front(), NBNodeCont::retrieve(), PositionVector::reverse(), SUMOReal, and StringTokenizer::WHITECHARS.
Field Documentation
NBEdgeCont& NIImporter_DlrNavteq::EdgesHandler::myEdgeCont [protected]
The edge container to store loaded edges into.
Definition at line 173 of file NIImporter_DlrNavteq.h.
Referenced by report().
std::map<std::string, PositionVector>& NIImporter_DlrNavteq::EdgesHandler::myGeoms [protected]
Previously read edge geometries.
Definition at line 176 of file NIImporter_DlrNavteq.h.
Referenced by report().
NBNodeCont& NIImporter_DlrNavteq::EdgesHandler::myNodeCont [protected]
The node container to get the referenced nodes from.
Definition at line 170 of file NIImporter_DlrNavteq.h.
Referenced by report().
bool NIImporter_DlrNavteq::EdgesHandler::myTryIgnoreNodePositions [protected]
Whether node positions shall not be added to the edge's geometry.
Definition at line 179 of file NIImporter_DlrNavteq.h.
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp