SUMO - Simulation of Urban MObility: NBLoadedTLDef::SignalGroup Class Reference
NBLoadedTLDef::SignalGroup Class Reference
A single signal group, may control several connections.
#include <NBLoadedTLDef.h>
Data Structures
class phase_by_time_sorter
Sorts phases by their begin time.
class PhaseDef
Definition of a single, loaded phase.
Public Member Functions
void addConnection (const NBConnection &c)
Inserts a controlled connection.
void addPhaseBegin (SUMOTime time, TLColor color)
Sets the begin of a phase.
bool containsConnection (NBEdge *from, NBEdge *to) const
Returns whether the given connection is controlled by this signal.
bool containsIncoming (NBEdge *from) const
Returns whether this signal controls the given edge.
bool containsOutgoing (NBEdge *to) const
Returns whether this signal controls a connection where the given edge is the destination.
const NBConnection & getConnection (unsigned int pos) const
Returns the connection at the given index.
const std::string & getID () const
Returns the id.
unsigned int getLinkNo () const
Returns the number of links (connection) controlled by this signal.
DoubleVector getTimes (SUMOTime cycleDuration) const
Returns the times at which the signal switches.
bool hasYellow (SUMOTime time) const
Returns whether controlled links have yellow at the given time.
bool mayDrive (SUMOTime time) const
Returns whether vehicles on controlled links may drive at the given time.
void patchTYellow (SUMOTime tyellow)
Sets the yellow time.
void remap (NBEdge *removed, int removedLane, NBEdge *by, int byLane)
Replaces a removed edge/lane.
void remapIncoming (NBEdge *which, const EdgeVector &by)
Replaces the given incoming edge by the others given.
void remapOutgoing (NBEdge *which, const EdgeVector &by)
Replaces the given outgoing edge by the others given.
void setID (const std::string &newID)
resets the id
void setYellowTimes (SUMOTime tRedYellowe, SUMOTime tYellow)
Sets the times for redyellow and yellow.
SignalGroup (const std::string &id)
Constructor.
void sortPhases ()
Sorts the phases.
~SignalGroup ()
Destructor.
Protected Attributes
std::string myID
The name of the object.
Private Attributes
NBConnectionVector myConnections
Connections controlled by this signal.
std::vector< PhaseDef > myPhases
The phases of this signal.
SUMOTime myTRedYellow
The times of redyellow and yellow.
SUMOTime myTYellow
Detailed Description
A single signal group, may control several connections.
Definition at line 54 of file NBLoadedTLDef.h.
Constructor & Destructor Documentation
NBLoadedTLDef::SignalGroup::SignalGroup (const std::string & id)
Constructor.
Parameters:
[in] id The id of the signal group
Definition at line 56 of file NBLoadedTLDef.cpp.
NBLoadedTLDef::SignalGroup::~SignalGroup ()
Destructor.
Definition at line 59 of file NBLoadedTLDef.cpp.
Member Function Documentation
void NBLoadedTLDef::SignalGroup::addConnection (const NBConnection & c)
Inserts a controlled connection.
Parameters:
[in] c The connection to be controlled by this signal group
Definition at line 62 of file NBLoadedTLDef.cpp.
References NBConnection::getFrom(), NBConnection::getFromLane(), NBEdge::getNumLanes(), and myConnections.
void NBLoadedTLDef::SignalGroup::addPhaseBegin (SUMOTime time, TLColor color)
Sets the begin of a phase.
Parameters:
[in] time The time at which the phase starts
[in] color The color of this signal starting at the given time
Definition at line 69 of file NBLoadedTLDef.cpp.
References myPhases.
bool NBLoadedTLDef::SignalGroup::containsConnection (NBEdge * from, NBEdge * to) const
Returns whether the given connection is controlled by this signal.
Parameters:
[in] from The connection's start edge
[in] from The connection's end edge
Returns:
Whether the connection is controlled by this signal
Definition at line 150 of file NBLoadedTLDef.cpp.
References myConnections.
bool NBLoadedTLDef::SignalGroup::containsIncoming (NBEdge * from) const
Returns whether this signal controls the given edge.
Parameters:
[in] from The incoming edge
Returns:
Whether this edge is controlled by this signal
Definition at line 169 of file NBLoadedTLDef.cpp.
References myConnections.
Referenced by NBLoadedTLDef::remapRemoved(), and NBLoadedTLDef::replaceRemoved().
bool NBLoadedTLDef::SignalGroup::containsOutgoing (NBEdge * to) const
Returns whether this signal controls a connection where the given edge is the destination.
Parameters:
[in] from The outgoing edge
Returns:
Whether this edge's predecessing edge is controlled by this signal
Definition at line 203 of file NBLoadedTLDef.cpp.
References myConnections.
Referenced by NBLoadedTLDef::remapRemoved(), and NBLoadedTLDef::replaceRemoved().
const NBConnection & NBLoadedTLDef::SignalGroup::getConnection (unsigned int pos) const
Returns the connection at the given index.
Parameters:
[in] pos The position within this signal
Returns:
The connection at the given index
Definition at line 162 of file NBLoadedTLDef.cpp.
References myConnections.
Referenced by NBLoadedTLDef::buildPhaseState(), NBLoadedTLDef::collectNodes(), NBLoadedTLDef::mustBrake(), and NBLoadedTLDef::setTLControllingInformation().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), remapIncoming(), remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
unsigned int NBLoadedTLDef::SignalGroup::getLinkNo () const
Returns the number of links (connection) controlled by this signal.
Returns:
The number of links controlled by this signal
Definition at line 123 of file NBLoadedTLDef.cpp.
References myConnections.
Referenced by NBLoadedTLDef::buildPhaseState(), NBLoadedTLDef::collectNodes(), NBLoadedTLDef::mustBrake(), and NBLoadedTLDef::setTLControllingInformation().
DoubleVector NBLoadedTLDef::SignalGroup::getTimes (SUMOTime cycleDuration) const
Returns the times at which the signal switches.
Parameters:
[in] cycleDuration The duration of the complete cycle
Returns:
The switch times of this signal
Definition at line 99 of file NBLoadedTLDef.cpp.
References myPhases, myTYellow, SUMOReal, and NBTrafficLightDefinition::TLCOLOR_RED.
Referenced by NBLoadedTLDef::myCompute().
bool NBLoadedTLDef::SignalGroup::hasYellow (SUMOTime time) const
Returns whether controlled links have yellow at the given time.
Parameters:
[in] time The regarded time
Returns:
Whether controlled links are yellow at this time
Definition at line 142 of file NBLoadedTLDef.cpp.
References mayDrive(), and myTYellow.
Referenced by NBLoadedTLDef::buildPhaseState().
bool NBLoadedTLDef::SignalGroup::mayDrive (SUMOTime time) const
Returns whether vehicles on controlled links may drive at the given time.
Parameters:
[in] time The regarded time
Returns:
Whether vehicles may drive at this time
Definition at line 129 of file NBLoadedTLDef.cpp.
References myPhases, and NBTrafficLightDefinition::TLCOLOR_GREEN.
Referenced by NBLoadedTLDef::buildPhaseState(), and hasYellow().
void NBLoadedTLDef::SignalGroup::patchTYellow (SUMOTime tyellow)
Sets the yellow time.
Parameters:
[in] tyellow The yellow time to set
Definition at line 90 of file NBLoadedTLDef.cpp.
References Named::getID(), myTYellow, and WRITE_WARNING.
Referenced by NBLoadedTLDef::myCompute().
void NBLoadedTLDef::SignalGroup::remap (NBEdge * removed, int removedLane, NBEdge * by, int byLane)
Replaces a removed edge/lane.
Parameters:
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
Definition at line 237 of file NBLoadedTLDef.cpp.
References myConnections.
Referenced by NBLoadedTLDef::replaceRemoved().
void NBLoadedTLDef::SignalGroup::remapIncoming (NBEdge * which, const EdgeVector & by)
Replaces the given incoming edge by the others given.
Parameters:
[in] which The edge to replace
[in] by The replacements
Definition at line 180 of file NBLoadedTLDef.cpp.
References Named::getID(), myConnections, and NBConnection::replaceFrom().
Referenced by NBLoadedTLDef::remapRemoved().
void NBLoadedTLDef::SignalGroup::remapOutgoing (NBEdge * which, const EdgeVector & by)
Replaces the given outgoing edge by the others given.
Parameters:
[in] which The edge to replace
[in] by The replacements
Definition at line 214 of file NBLoadedTLDef.cpp.
References Named::getID(), myConnections, and NBConnection::replaceTo().
Referenced by NBLoadedTLDef::remapRemoved().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void NBLoadedTLDef::SignalGroup::setYellowTimes (SUMOTime tRedYellowe, SUMOTime tYellow)
Sets the times for redyellow and yellow.
Parameters:
[in] tRedYellowe The duration of the redyellow phase
[in] tYellow The duration of the yellow phase
Definition at line 75 of file NBLoadedTLDef.cpp.
References myTRedYellow, and myTYellow.
void NBLoadedTLDef::SignalGroup::sortPhases ()
Sorts the phases.
Definition at line 83 of file NBLoadedTLDef.cpp.
References myPhases.
Referenced by NBLoadedTLDef::myCompute().
Field Documentation
NBConnectionVector NBLoadedTLDef::SignalGroup::myConnections [private]
Connections controlled by this signal.
Definition at line 194 of file NBLoadedTLDef.h.
Referenced by addConnection(), containsConnection(), containsIncoming(), containsOutgoing(), getConnection(), getLinkNo(), remap(), remapIncoming(), and remapOutgoing().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::vector<PhaseDef> NBLoadedTLDef::SignalGroup::myPhases [private]
The phases of this signal.
Definition at line 196 of file NBLoadedTLDef.h.
Referenced by addPhaseBegin(), getTimes(), mayDrive(), and sortPhases().
SUMOTime NBLoadedTLDef::SignalGroup::myTRedYellow [private]
The times of redyellow and yellow.
Definition at line 198 of file NBLoadedTLDef.h.
Referenced by setYellowTimes().
SUMOTime NBLoadedTLDef::SignalGroup::myTYellow [private]
Definition at line 198 of file NBLoadedTLDef.h.
Referenced by getTimes(), hasYellow(), patchTYellow(), and setYellowTimes().
The documentation for this class was generated from the following files:
NBLoadedTLDef.h
NBLoadedTLDef.cpp