SUMO - Simulation of Urban MObility: RODFDetectorCon Class Reference
RODFDetectorCon Class Reference
A container for RODFDetectors.
#include <RODFDetector.h>
Public Member Functions
bool addDetector (RODFDetector *dfd)
bool detectorsHaveCompleteTypes () const
bool detectorsHaveRoutes () const
int getAggFlowFor (const ROEdge *edge, SUMOTime time, SUMOTime period, const RODFDetectorFlows &flows) const
const RODFDetector & getAnyDetectorForEdge (const RODFEdge *const edge) const
const RODFDetector & getDetector (const std::string &id) const
const std::vector
< RODFDetector * > & getDetectors () const
void guessEmptyFlows (RODFDetectorFlows &flows)
bool knows (const std::string &id) const
void mesoJoin (const std::string &nid, const std::vector< std::string > &oldids)
void removeDetector (const std::string &id)
RODFDetectorCon ()
void save (const std::string &file) const
void saveAsPOIs (const std::string &file) const
void saveRoutes (const std::string &file) const
void writeEmitterPOIs (const std::string &file, const RODFDetectorFlows &flows)
void writeEmitters (const std::string &file, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet &net, bool writeCalibrators, bool includeUnusedRoutes, SUMOReal scale, int maxFollower, bool insertionsOnly)
void writeEndRerouterDetectors (const std::string &file)
void writeSpeedTrigger (const RODFNet *const net, const std::string &file, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void writeValidationDetectors (const std::string &file, bool includeSources, bool singleFile, bool friendly)
~RODFDetectorCon ()
Protected Member Functions
void clearDists (std::map< size_t, RandomDistributor< size_t > * > &dists) const
Clears the given distributions map, deleting the timed distributions.
Protected Attributes
std::map< std::string,
std::vector< RODFDetector * > > myDetectorEdgeMap
std::map< std::string,
RODFDetector * > myDetectorMap
std::vector< RODFDetector * > myDetectors
Private Member Functions
RODFDetectorCon & operator= (const RODFDetectorCon &src)
Invalidated assignment operator.
RODFDetectorCon (const RODFDetectorCon &src)
Invalidated copy constructor.
Detailed Description
A container for RODFDetectors.
Definition at line 237 of file RODFDetector.h.
Constructor & Destructor Documentation
RODFDetectorCon::RODFDetectorCon ()
Definition at line 400 of file RODFDetector.cpp.
RODFDetectorCon::~RODFDetectorCon ()
Definition at line 403 of file RODFDetector.cpp.
References myDetectors.
RODFDetectorCon::RODFDetectorCon (const RODFDetectorCon & src) [private]
Invalidated copy constructor.
Member Function Documentation
bool RODFDetectorCon::addDetector (RODFDetector * dfd)
Definition at line 411 of file RODFDetector.cpp.
References RODFDetector::getID(), RODFDetector::getLaneID(), myDetectorEdgeMap, myDetectorMap, and myDetectors.
Referenced by mesoJoin(), and RODFDetectorHandler::myStartElement().
void RODFDetectorCon::clearDists (std::map< size_t, RandomDistributor< size_t > * > & dists) const [protected]
Clears the given distributions map, deleting the timed distributions.
Parameters:
[in] dists The distribution map to clear
Definition at line 840 of file RODFDetector.cpp.
Referenced by writeEmitters().
bool RODFDetectorCon::detectorsHaveCompleteTypes () const
Definition at line 427 of file RODFDetector.cpp.
References myDetectors, and TYPE_NOT_DEFINED.
Referenced by startComputation().
bool RODFDetectorCon::detectorsHaveRoutes () const
Definition at line 438 of file RODFDetector.cpp.
References myDetectors.
Referenced by startComputation().
int RODFDetectorCon::getAggFlowFor (const ROEdge * edge, SUMOTime time, SUMOTime period, const RODFDetectorFlows & flows) const
Definition at line 640 of file RODFDetector.cpp.
References ROEdge::getID(), myDetectorEdgeMap, FlowDef::qLKW, FlowDef::qPKW, SUMOReal, and UNUSED_PARAMETER.
Referenced by RODFDetector::computeSplitProbabilities().
const RODFDetector & RODFDetectorCon::getAnyDetectorForEdge (const RODFEdge *const edge) const
Definition at line 829 of file RODFDetector.cpp.
References ROEdge::getID(), and myDetectors.
Referenced by RODFDetector::buildDestinationDistribution().
const RODFDetector & RODFDetectorCon::getDetector (const std::string & id) const
Definition at line 536 of file RODFDetector.cpp.
References myDetectorMap.
Referenced by RODFNet::buildDetectorDependencies(), RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), RODFNet::hasInBetweenDetectorsOnly(), RODFNet::hasSourceDetector(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), RODFNet::mesoJoin(), and mesoJoin().
const std::vector< RODFDetector * > & RODFDetectorCon::getDetectors () const
Definition at line 449 of file RODFDetector.cpp.
References myDetectors.
Referenced by RODFNet::buildDetectorEdgeDependencies(), RODFNet::buildRoutes(), RODFNet::computeTypes(), RODFNet::removeEmptyDetectors(), RODFNet::reportEmptyDetectors(), and RODFNet::revalidateFlows().
void RODFDetectorCon::guessEmptyFlows (RODFDetectorFlows & flows)
Definition at line 785 of file RODFDetector.cpp.
References RODFDetector::getFollowerDetectors(), RODFDetector::getID(), RODFDetector::getPriorDetectors(), RODFDetectorFlows::knows(), and myDetectors.
Referenced by startComputation().
bool RODFDetectorCon::knows (const std::string & id) const
Definition at line 542 of file RODFDetector.cpp.
References myDetectorMap.
void RODFDetectorCon::mesoJoin (const std::string & nid, const std::vector< std::string > & oldids)
Definition at line 848 of file RODFDetector.cpp.
References addDetector(), getDetector(), and removeDetector().
Referenced by RODFNet::mesoJoin().
RODFDetectorCon& RODFDetectorCon::operator= (const RODFDetectorCon & src) [private]
Invalidated assignment operator.
void RODFDetectorCon::removeDetector (const std::string & id)
Definition at line 758 of file RODFDetector.cpp.
References myDetectorEdgeMap, myDetectorMap, and myDetectors.
Referenced by mesoJoin(), and RODFNet::removeEmptyDetectors().
void RODFDetectorCon::save (const std::string & file) const
Definition at line 455 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, OutputDevice::close(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), myDetectors, SINK_DETECTOR, SOURCE_DETECTOR, SUMO_TAG_DETECTOR_DEFINITION, toString(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::saveAsPOIs (const std::string & file) const
Definition at line 485 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, OutputDevice::close(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), myDetectors, SINK_DETECTOR, SOURCE_DETECTOR, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::saveRoutes (const std::string & file) const
Definition at line 514 of file RODFDetector.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), myDetectors, SOURCE_DETECTOR, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::writeEmitterPOIs (const std::string & file, const RODFDetectorFlows & flows)
Definition at line 605 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, OutputDevice::close(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), RODFDetectorFlows::getFlowSumSecure(), RODFDetector::getID(), RODFDetectorFlows::getMaxDetectorFlow(), myDetectors, SINK_DETECTOR, SOURCE_DETECTOR, SUMOReal, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::writeEmitters (const std::string & file, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet & net, bool writeCalibrators, bool includeUnusedRoutes, SUMOReal scale, int maxFollower, bool insertionsOnly)
Definition at line 548 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, RODFDetector::buildDestinationDistribution(), clearDists(), OutputDevice::close(), StringUtils::escapeXML(), OutputDevice::getDevice(), RONet::getEdge(), RODFDetector::getEdgeID(), FileHelpers::getFilePath(), RODFDetector::getID(), RODFDetector::getLaneID(), RODFDetector::getPos(), RODFDetector::getType(), RODFDetectorFlows::knows(), myDetectors, SOURCE_DETECTOR, SUMOReal, RODFDetector::writeEmitterDefinition(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::writeEndRerouterDetectors (const std::string & file)
Definition at line 708 of file RODFDetector.cpp.
References OutputDevice::close(), StringUtils::escapeXML(), OutputDevice::getDevice(), RODFDetector::getID(), RODFDetector::getLaneID(), RODFDetector::getType(), myDetectors, SINK_DETECTOR, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::writeSpeedTrigger (const RODFNet *const net, const std::string & file, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 684 of file RODFDetector.cpp.
References OutputDevice::close(), StringUtils::escapeXML(), OutputDevice::getDevice(), RONet::getEdge(), RODFDetector::getEdgeID(), FileHelpers::getFilePath(), RODFDetector::getID(), RODFDetector::getLaneID(), RODFDetector::getType(), RODFDetectorFlows::knows(), myDetectors, SINK_DETECTOR, SUMOReal, RODFDetector::writeSingleSpeedTrigger(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
void RODFDetectorCon::writeValidationDetectors (const std::string & file, bool includeSources, bool singleFile, bool friendly)
!!
Definition at line 726 of file RODFDetector.cpp.
References OutputDevice::close(), StringUtils::escapeXML(), OutputDevice::getDevice(), RODFDetector::getID(), RODFDetector::getLaneID(), RODFDetector::getPos(), RODFDetector::getType(), myDetectors, SOURCE_DETECTOR, SUMOReal, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
Field Documentation
std::map<std::string, std::vector<RODFDetector*> > RODFDetectorCon::myDetectorEdgeMap [protected]
Definition at line 291 of file RODFDetector.h.
Referenced by addDetector(), getAggFlowFor(), and removeDetector().
std::map<std::string, RODFDetector*> RODFDetectorCon::myDetectorMap [protected]
Definition at line 290 of file RODFDetector.h.
Referenced by addDetector(), getDetector(), knows(), and removeDetector().
std::vector<RODFDetector*> RODFDetectorCon::myDetectors [protected]
Definition at line 289 of file RODFDetector.h.
Referenced by addDetector(), detectorsHaveCompleteTypes(), detectorsHaveRoutes(), getAnyDetectorForEdge(), getDetectors(), guessEmptyFlows(), removeDetector(), save(), saveAsPOIs(), saveRoutes(), writeEmitterPOIs(), writeEmitters(), writeEndRerouterDetectors(), writeSpeedTrigger(), writeValidationDetectors(), and ~RODFDetectorCon().
The documentation for this class was generated from the following files:
RODFDetector.h
RODFDetector.cpp