SUMO - Simulation of Urban MObility: GUITriggerBuilder Class Reference
GUITriggerBuilder Class Reference
Builds trigger objects for guisim.
#include <GUITriggerBuilder.h>
Public Member Functions
void buildVaporizer (const SUMOSAXAttributes &attrs)
Builds a vaporization.
GUITriggerBuilder ()
Constructor.
void setHandler (NLHandler *handler)
Sets the parent handler to use for nested parsing.
~GUITriggerBuilder ()
Destructor.
parsing methods
These methods parse the attributes for each of the described trigger and call the according methods to build the trigger
void parseAndBuildBusStop (MSNet &net, const SUMOSAXAttributes &attrs) throw (InvalidArgument)
Parses his values and builds a bus stop.
void parseAndBuildLaneSpeedTrigger (MSNet &net, const SUMOSAXAttributes &attrs, const std::string &base) throw (InvalidArgument)
Parses his values and builds a lane speed trigger.
void parseAndBuildRerouter (MSNet &net, const SUMOSAXAttributes &attrs, const std::string &base) throw (InvalidArgument)
Parses his values and builds a rerouter.
Protected Member Functions
building methods
Override NLTriggerBuilder-methods for building guisim-objects
See also:
NLTriggerBuilder
virtual void buildBusStop (MSNet &net, const std::string &id, const std::vector< std::string > &lines, MSLane *lane, SUMOReal frompos, SUMOReal topos) throw (InvalidArgument)
Builds a bus stop.
virtual MSLaneSpeedTrigger * buildLaneSpeedTrigger (MSNet &net, const std::string &id, const std::vector< MSLane * > &destLanes, const std::string &file)
Builds a lane speed trigger.
virtual void buildRerouter (MSNet &net, const std::string &id, std::vector< MSEdge * > &edges, SUMOReal prob, const std::string &file, bool off)
builds an rerouter
helper method for obtaining and checking values
std::string getFileName (const SUMOSAXAttributes &attrs, const std::string &base, const bool allowEmpty=false) throw (InvalidArgument)
Helper method to obtain the filename.
MSLane * getLane (const SUMOSAXAttributes &attrs, const std::string &tt, const std::string &tid) throw (InvalidArgument)
Returns the lane defined by attribute "lane".
SUMOReal getPosition (const SUMOSAXAttributes &attrs, MSLane *lane, const std::string &tt, const std::string &tid) throw (InvalidArgument)
returns the position on the lane checking it
Protected Attributes
NLHandler * myHandler
The parent handler to set for subhandlers.
bool myHaveWarnedAboutDeprecatedFriendlyPos
Detailed Description
Builds trigger objects for guisim.
Definition at line 55 of file GUITriggerBuilder.h.
Constructor & Destructor Documentation
GUITriggerBuilder::GUITriggerBuilder ()
Constructor.
Definition at line 49 of file GUITriggerBuilder.cpp.
GUITriggerBuilder::~GUITriggerBuilder ()
Destructor.
Definition at line 52 of file GUITriggerBuilder.cpp.
Member Function Documentation
void GUITriggerBuilder::buildBusStop (MSNet & net, const std::string & id, const std::vector< std::string > & lines, MSLane * lane, SUMOReal frompos, SUMOReal topos) throw (InvalidArgument) [protected, virtual]
Builds a bus stop.
Simply calls the GUIBusStop constructor.
Parameters:
[in] net The net the bus stop belongs to
[in] id The id of the bus stop
[in] lines Names of the bus lines that halt on this bus stop
[in] lane The lane the bus stop is placed on
[in] frompos Begin position of the bus stop on the lane
[in] topos End position of the bus stop on the lane
Exceptions:
InvalidArgument If the bus stop can not be added to the net (is duplicate)
Reimplemented from NLTriggerBuilder.
Definition at line 74 of file GUITriggerBuilder.cpp.
MSLaneSpeedTrigger * GUITriggerBuilder::buildLaneSpeedTrigger (MSNet & net, const std::string & id, const std::vector< MSLane * > & destLanes, const std::string & file) [protected, virtual]
Builds a lane speed trigger.
Simply calls the GUILaneSpeedTrigger constructor.
Parameters:
[in] net The net the lane speed trigger belongs to
[in] id The id of the lane speed trigger
[in] destLanes List of lanes affected by this speed trigger
[in] file Name of the file to read the speeds to set from
See also:
MSLaneSpeedTrigger
Exceptions:
ProcessError If the XML definition file is errornous
Reimplemented from NLTriggerBuilder.
Definition at line 56 of file GUITriggerBuilder.cpp.
void GUITriggerBuilder::buildRerouter (MSNet & net, const std::string & id, std::vector< MSEdge * > & edges, SUMOReal prob, const std::string & file, bool off) [protected, virtual]
builds an rerouter
Simply calls the GUITriggeredRerouter constructor.
Parameters:
[in] net The net the rerouter belongs to
[in] id The id of the rerouter
[in] edges The edges the rerouter is placed at
[in] prob The probability the rerouter reoutes vehicles with
[in] file The file to read the reroute definitions from
Reimplemented from NLTriggerBuilder.
Definition at line 66 of file GUITriggerBuilder.cpp.
void NLTriggerBuilder::buildVaporizer (const SUMOSAXAttributes & attrs) [inherited]
Builds a vaporization.
Parses the attributes, reporting errors if the time values are false or the edge is not known. Instatiates events for enabling and disabling the vaporization otherwise.
Parameters:
[in] attrs SAX-attributes which define the vaporizer
Note:
recheck throwing the exception
Definition at line 77 of file NLTriggerBuilder.cpp.
References MSEventControl::ADAPT_AFTER_EXECUTION, MSEventControl::addEvent(), MSEdge::decVaporization(), MSEdge::dictionary(), MSNet::getBeginOfTimestepEvents(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOSAXAttributes::getStringReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), MSEdge::incVaporization(), string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by NLHandler::myStartElement().
std::string NLTriggerBuilder::getFileName (const SUMOSAXAttributes & attrs, const std::string & base, const bool allowEmpty = false) throw (InvalidArgument) [protected, inherited]
Helper method to obtain the filename.
Retrieves "file" from attributes, checks whether it is absolute and extends it by the given base path if not. Returns this information.
Parameters:
[in] attrs The attributes to obtain the file name from
[in] base The base path (the path the loaded additional file lies in)
Returns:
The (expanded) path to the named file
Todo:
Recheck usage of the helper class
Definition at line 298 of file NLTriggerBuilder.cpp.
References FileHelpers::getConfigurationRelative(), FileHelpers::isAbsolute(), and SUMO_ATTR_FILE.
MSLane * NLTriggerBuilder::getLane (const SUMOSAXAttributes & attrs, const std::string & tt, const std::string & tid) throw (InvalidArgument) [protected, inherited]
Returns the lane defined by attribute "lane".
Retrieves the lane id from the given attrs. Tries to retrieve the lane, throws an InvalidArgument if it does not exist.
Parameters:
[in] attrs The attributes to obtain the lane id from
[in] tt The trigger type (for user output)
[in] tid The trigger id (for user output)
Returns:
The named lane if it is known
Exceptions:
InvalidArgument If the named lane does not exist or a lane is not named
Definition at line 319 of file NLTriggerBuilder.cpp.
References MSLane::dictionary(), and SUMO_ATTR_LANE.
SUMOReal NLTriggerBuilder::getPosition (const SUMOSAXAttributes & attrs, MSLane * lane, const std::string & tt, const std::string & tid) throw (InvalidArgument) [protected, inherited]
returns the position on the lane checking it
This method extracts the position, checks whether it shall be mirrored and checks whether it is within the lane. If not, an error is reported and a InvalidArgument is thrown.
Parameters:
[in] attrs The attributes to obtain the position from
[in] lane The lane the position shall be valid for
[in] tt The trigger type (for user output)
[in] tid The trigger id (for user output)
Returns:
The position on the lane
Exceptions:
InvalidArgument If the position is beyond the lane
Definition at line 333 of file NLTriggerBuilder.cpp.
References Named::getID(), MSLane::getLength(), SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_POSITION, SUMOReal, toString(), and WRITE_WARNING.
void NLTriggerBuilder::parseAndBuildBusStop (MSNet & net, const SUMOSAXAttributes & attrs) throw (InvalidArgument) [inherited]
Parses his values and builds a bus stop.
Parameters:
[in] net The network the bus stop belongs to
[in] attrs SAX-attributes which define the trigger
Exceptions:
InvalidArgument If a parameter (lane/position) is not valid
Definition at line 153 of file NLTriggerBuilder.cpp.
References MSLane::getLength(), SUMOSAXAttributes::parseStringVector(), SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FRIENDLY_POS__DEPRECATED, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_LINES, SUMO_ATTR_STARTPOS, SUMO_ATTR_TO, SUMOReal, toString(), and WRITE_WARNING.
Referenced by NLHandler::myStartElement().
void NLTriggerBuilder::parseAndBuildLaneSpeedTrigger (MSNet & net, const SUMOSAXAttributes & attrs, const std::string & base) throw (InvalidArgument) [inherited]
Parses his values and builds a lane speed trigger.
If one of the declaration values is errornous, an InvalidArgument is thrown.
If the XML-file parsed during initialisation is errornous, and the MSLaneSpeedTrigger-constructor throws a ProcessError due to this, this exception is catched and an InvalidArgument with the message given in the ProcessError is thrown.
Parameters:
[in] net The network the lane speed trigger belongs to
[in] attrs SAX-attributes which define the trigger
[in] base The base path
Exceptions:
InvalidArgument If a parameter (lane/position) is not valid or the read definition is errornous
See also:
buildLaneSpeedTrigger
Definition at line 113 of file NLTriggerBuilder.cpp.
References MSLane::dictionary(), SUMOSAXAttributes::parseStringVector(), GenericSAXHandler::registerParent(), SUMO_ATTR_ID, SUMO_ATTR_LANES, and SUMO_TAG_VSS.
Referenced by NLHandler::myStartElement().
void NLTriggerBuilder::parseAndBuildRerouter (MSNet & net, const SUMOSAXAttributes & attrs, const std::string & base) throw (InvalidArgument) [inherited]
Parses his values and builds a rerouter.
Parameters:
[in] net The network the rerouter belongs to
[in] attrs SAX-attributes which define the trigger
[in] base The base path
Exceptions:
InvalidArgument If a parameter (edge) is not valid
Definition at line 216 of file NLTriggerBuilder.cpp.
References MSEdge::dictionary(), SUMOSAXAttributes::parseStringVector(), SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_OFF, SUMO_ATTR_PROB, and SUMOReal.
Referenced by NLHandler::myStartElement().
void NLTriggerBuilder::setHandler (NLHandler * handler) [inherited]
Sets the parent handler to use for nested parsing.
Parameters:
[in] handler The netload handler to set
Definition at line 71 of file NLTriggerBuilder.cpp.
References NLTriggerBuilder::myHandler.
Referenced by load(), and GUILoadThread::run().
Field Documentation
NLHandler* NLTriggerBuilder::myHandler [protected, inherited]
The parent handler to set for subhandlers.
Definition at line 289 of file NLTriggerBuilder.h.
Referenced by NLTriggerBuilder::setHandler().
bool NLTriggerBuilder::myHaveWarnedAboutDeprecatedFriendlyPos [protected, inherited]
Definition at line 291 of file NLTriggerBuilder.h.
The documentation for this class was generated from the following files:
GUITriggerBuilder.h
GUITriggerBuilder.cpp