SUMO - Simulation of Urban MObility: NBLoadedSUMOTLDef::connection_equal Class Reference
NBLoadedSUMOTLDef::connection_equal Class Reference
class for identifying connections
Public Member Functions
connection_equal (const NBConnection &c)
constructor
bool operator() (const NBConnection &c) const
Private Member Functions
connection_equal & operator= (const connection_equal &s)
invalidated assignment operator
Private Attributes
const NBConnection & myC
Detailed Description
class for identifying connections
Definition at line 150 of file NBLoadedSUMOTLDef.h.
Constructor & Destructor Documentation
NBLoadedSUMOTLDef::connection_equal::connection_equal (const NBConnection & c) [inline]
constructor
Definition at line 153 of file NBLoadedSUMOTLDef.h.
Member Function Documentation
bool NBLoadedSUMOTLDef::connection_equal::operator() (const NBConnection & c) const [inline]
Definition at line 155 of file NBLoadedSUMOTLDef.h.
References NBConnection::getFrom(), NBConnection::getFromLane(), NBConnection::getTo(), NBConnection::getToLane(), and myC.
connection_equal& NBLoadedSUMOTLDef::connection_equal::operator= (const connection_equal & s) [private]
invalidated assignment operator
Field Documentation
const NBConnection& NBLoadedSUMOTLDef::connection_equal::myC [private]
Definition at line 160 of file NBLoadedSUMOTLDef.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
NBLoadedSUMOTLDef.h