SUMO - Simulation of Urban MObility: ROTypedXMLRoutesLoader Class Reference
ROTypedXMLRoutesLoader Class Reference
Base class for loading routes from XML-files.
#include <ROTypedXMLRoutesLoader.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endDocument ()
Called when the document has ended.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
ROTypedXMLRoutesLoader (RONet &net, SUMOTime begin, SUMOTime end, const std::string &file="")
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~ROTypedXMLRoutesLoader ()
Destructor.
inherited from ROAbstractRouteDefLoader
bool ended () const
Returns the information whether no routes are available from this loader anymore.
bool readRoutesAtLeastUntil (SUMOTime time, bool skipping)
Adds routes from the file until the given time is reached.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
Methods to be implemented
virtual SUMOTime getLastReadTimeStep () const =0
Returns the time the current (last read) route starts at.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Callback method for an opening tag to implement by derived classes.
Virtual methods to implement by derived classes
virtual void beginNextRoute ()=0
Returns Initialises the reading of a further route.
virtual bool nextRouteRead ()=0
Protected Attributes
SUMOTime myBegin
The time for which the first route shall be loaded.
SUMOTime myEnd
The time for which the first route shall be loaded.
bool myEnded
Information whether the whole file has been parsed.
RONet & myNet
The network to add routes to.
SAX2XMLReader * myParser
The parser used.
XMLPScanToken myToken
Information about the current position within the file.
Private Member Functions
ROTypedXMLRoutesLoader & operator= (const ROTypedXMLRoutesLoader &src)
Invalidated assignment operator.
ROTypedXMLRoutesLoader (const ROTypedXMLRoutesLoader &src)
Invalidated copy constructor.
Detailed Description
Base class for loading routes from XML-files.
Base class for loaders which load route definitions which use XML-derived formats. Some methods as the initialisation and the file processing, together with the need for a parser are common to all such loaders.
Todo:
recheck/refactor
Definition at line 61 of file ROTypedXMLRoutesLoader.h.
Constructor & Destructor Documentation
ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader (RONet & net, SUMOTime begin, SUMOTime end, const std::string & file = "")
Constructor.
Parameters:
[in] vb The vehicle builder to use
[in] net The network to add vehicles to
[in] begin The time step import shall start at
[in] end The time step import shall stop at
[in] file Name of the used input file
Exceptions:
ProcessError If an error occured during initialisation of parsing the xml-file
Definition at line 51 of file ROTypedXMLRoutesLoader.cpp.
References GenericSAXHandler::getFileName(), XMLSubSys::getSAXReader(), myParser, and myToken.
ROTypedXMLRoutesLoader::~ROTypedXMLRoutesLoader () [virtual]
Destructor.
Definition at line 67 of file ROTypedXMLRoutesLoader.cpp.
References myParser.
ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader (const ROTypedXMLRoutesLoader & src) [private]
Invalidated copy constructor.
Member Function Documentation
virtual void ROTypedXMLRoutesLoader::beginNextRoute () [protected, pure virtual]
Returns Initialises the reading of a further route.
Todo:
recheck/refactor
Implemented in RORDLoader_SUMOBase, and RORDLoader_TripDefs.
Referenced by readRoutesAtLeastUntil().
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void ROTypedXMLRoutesLoader::endDocument ()
Called when the document has ended.
Todo:
Recheck usage of route loaders; it is not very fine to have one that use a parser and other that do not
Definition at line 86 of file ROTypedXMLRoutesLoader.cpp.
References myEnded.
bool ROTypedXMLRoutesLoader::ended () const [inline, virtual]
Returns the information whether no routes are available from this loader anymore.
Returns:
Whether the whole input has been processed
Implements ROAbstractRouteDefLoader.
Definition at line 99 of file ROTypedXMLRoutesLoader.h.
References myEnded.
Referenced by readRoutesAtLeastUntil().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
virtual SUMOTime ROAbstractRouteDefLoader::getLastReadTimeStep () const [pure virtual, inherited]
Returns the time the current (last read) route starts at.
Returns:
The least time step that was read by this reader
Implemented in RORDLoader_SUMOBase, and RORDLoader_TripDefs.
Referenced by readRoutesAtLeastUntil().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) [protected, virtual, inherited]
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in MSRouteHandler, MSLaneSpeedTrigger, MSTriggeredRerouter, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_OpenStreetMap::NodesHandler, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_SUMO, NIXMLEdgesHandler, NIXMLTrafficLightsHandler, NLHandler, ODDistrictHandler, PCLoaderOSM::NodesHandler, PCLoaderOSM::EdgesHandler, RORDGenerator_ODAmounts, RORDLoader_SUMOBase, RORDLoader_TripDefs, and SAXWeightsHandler.
Definition at line 232 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual, inherited]
Callback method for an opening tag to implement by derived classes.
Called by "startElement" (see there).
Parameters:
[in] element The element that contains the characters, given as a int
[in] attrs The SAX-attributes, wrapped as SUMOSAXAttributes ProcessError These method may throw a ProcessError if something fails
Reimplemented in AGActivityGenHandler, RODFDetectorHandler, ROJTRTurnDefLoader, MSRouteHandler, MSLaneSpeedTrigger, MSTriggeredRerouter, NIImporter_ITSUMO::Handler, NIImporter_MATSim::NodesHandler, NIImporter_MATSim::EdgesHandler, NIImporter_OpenDrive, NIImporter_OpenStreetMap::NodesHandler, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_SUMO, NIXMLConnectionsHandler, NIXMLEdgesHandler, NIXMLNodesHandler, NIXMLTrafficLightsHandler, NIXMLTypesHandler, NLHandler, ODDistrictHandler, PCLoaderOSM::NodesHandler, PCLoaderOSM::EdgesHandler, PCLoaderXML, PCNetProjectionLoader, PCTypeDefHandler, RONetHandler, RORDGenerator_ODAmounts, RORDLoader_SUMOBase, RORDLoader_TripDefs, GUISettingsHandler, and SAXWeightsHandler.
Definition at line 224 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::startElement().
virtual bool ROTypedXMLRoutesLoader::nextRouteRead () [protected, pure virtual]
Returns the information whether a route was read
Returns:
Whether a further route was read
Todo:
recheck/refactor
Implemented in RORDLoader_SUMOBase, and RORDLoader_TripDefs.
Referenced by readRoutesAtLeastUntil().
ROTypedXMLRoutesLoader& ROTypedXMLRoutesLoader::operator= (const ROTypedXMLRoutesLoader & src) [private]
Invalidated assignment operator.
bool ROTypedXMLRoutesLoader::readRoutesAtLeastUntil (SUMOTime time, bool skipping) [virtual]
Adds routes from the file until the given time is reached.
Parameters:
[in] time The time until which route definitions shall be loaded
[in] skipping Whether routes shall not be added
Returns:
Whether any errors occured
Exceptions:
ProcessError If a major error occured
See also:
ROAbstractRouteDefLoader::readRoutesAtLeastUntil
Implements ROAbstractRouteDefLoader.
Reimplemented in RORDGenerator_ODAmounts.
Definition at line 73 of file ROTypedXMLRoutesLoader.cpp.
References beginNextRoute(), ended(), ROAbstractRouteDefLoader::getLastReadTimeStep(), myParser, myToken, nextRouteRead(), and UNUSED_PARAMETER.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
SUMOTime ROAbstractRouteDefLoader::myBegin [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 109 of file ROAbstractRouteDefLoader.h.
Referenced by RORDLoader_SUMOBase::closeVehicle(), RORDGenerator_ODAmounts::myEndFlowAmountDef(), RORDGenerator_ODAmounts::readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts::RORDGenerator_ODAmounts().
SUMOTime ROAbstractRouteDefLoader::myEnd [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 112 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), and RORDLoader_TripDefs::myEndElement().
bool ROTypedXMLRoutesLoader::myEnded [protected]
Information whether the whole file has been parsed.
Definition at line 141 of file ROTypedXMLRoutesLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), endDocument(), and ended().
RONet& ROAbstractRouteDefLoader::myNet [protected, inherited]
The network to add routes to.
Definition at line 106 of file ROAbstractRouteDefLoader.h.
Referenced by RORDGenerator_ODAmounts::buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), RORDLoader_TripDefs::getEdge(), RORDLoader_SUMOBase::myCharacters(), RORDLoader_TripDefs::myEndElement(), RORDLoader_SUMOBase::myEndElement(), and RORDGenerator_ODAmounts::myEndFlowAmountDef().
SAX2XMLReader* ROTypedXMLRoutesLoader::myParser [protected]
The parser used.
Definition at line 135 of file ROTypedXMLRoutesLoader.h.
Referenced by readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader(), and ~ROTypedXMLRoutesLoader().
XMLPScanToken ROTypedXMLRoutesLoader::myToken [protected]
Information about the current position within the file.
Definition at line 138 of file ROTypedXMLRoutesLoader.h.
Referenced by readRoutesAtLeastUntil(), RORDGenerator_ODAmounts::RORDGenerator_ODAmounts(), and ROTypedXMLRoutesLoader().
The documentation for this class was generated from the following files:
ROTypedXMLRoutesLoader.h
ROTypedXMLRoutesLoader.cpp