SUMO - Simulation of Urban MObility: jtrrouter_main.cpp File Reference
jtrrouter_main.cpp File Reference
#include <config.h>
#include <xercesc/sax/SAXException.hpp>
#include <xercesc/sax/SAXParseException.hpp>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <limits.h>
#include <ctime>
#include <set>
#include <router/ROFrame.h>
#include <router/ROLoader.h>
#include <router/RONet.h>
#include <utils/common/MsgHandler.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/ToString.h>
#include <utils/common/RandHelper.h>
#include <utils/common/StringTokenizer.h>
#include <utils/xml/XMLSubSys.h>
#include "ROJTREdgeBuilder.h"
#include <router/ROAbstractEdgeBuilder.h>
#include <utils/common/SUMOAbstractRouter.h>
#include <map>
#include <vector>
#include <utils/common/ValueTimeLine.h>
#include <router/ROEdge.h>
#include <utils/xml/SUMOSAXHandler.h>
#include <utils/importio/NamedColumnsParser.h>
#include <utils/importio/LineHandler.h>
#include <utils/iodevices/OutputDevice.h>
Functions
void computeRoutes (RONet &net, ROLoader &loader, OptionsCont &oc)
std::vector< SUMOReal > getTurningDefaults (OptionsCont &oc)
void initNet (RONet &net, ROLoader &loader, OptionsCont &oc, const std::vector< SUMOReal > &turnDefs)
void loadJTRDefinitions (RONet &net, OptionsCont &oc)
int main (int argc, char **argv)
Detailed Description
Author:
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date:
Tue, 20 Jan 2004
Version:
Id
jtrrouter_main.cpp 11671 2012-01-07 20:14:30Z behrisch
Definition in file jtrrouter_main.cpp.
Function Documentation
void computeRoutes (RONet & net, ROLoader & loader, OptionsCont & oc)
Computes the routes saving them
Definition at line 146 of file jtrrouter_main.cpp.
References RONet::closeOutput(), OptionsCont::getBool(), RONet::getEdgeNo(), OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), RONet::openOutput(), ROLoader::openRoutes(), ROLoader::processAllRoutes(), ROLoader::processRoutesStepWise(), string2time(), and SUMOReal.
std::vector<SUMOReal> getTurningDefaults (OptionsCont & oc)
Definition at line 95 of file jtrrouter_main.cpp.
References TplConvert< E >::_2SUMOReal(), OptionsCont::getStringVector(), and SUMOReal.
Referenced by main().
void initNet (RONet & net, ROLoader & loader, OptionsCont & oc, const std::vector< SUMOReal > & turnDefs)
loads the net The net is in this meaning made up by the net itself and the dynamic weights which may be supplied in a separate file
Definition at line 82 of file jtrrouter_main.cpp.
References RONet::getEdgeMap(), and ROLoader::loadNet().
void loadJTRDefinitions (RONet & net, OptionsCont & oc)
Definition at line 114 of file jtrrouter_main.cpp.
References MsgHandler::clear(), ROEdge::ET_SINK, OptionsCont::getBool(), RONet::getEdge(), MsgHandler::getErrorInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), XMLSubSys::runParser(), and ROEdge::setType().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 171 of file jtrrouter_main.cpp.
References ROJTRFrame::checkOptions(), SystemFrame::close(), OutputDevice::closeAll(), computeRoutes(), ROJTRFrame::fillOptions(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), getTurningDefaults(), MsgHandler::inform(), XMLSubSys::init(), initNet(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), loadJTRDefinitions(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), toString(), VERSION_STRING, and WRITE_ERROR.