SUMO - Simulation of Urban MObility: ROVehicle Class Reference
ROVehicle Class Reference
A vehicle as used by router.
#include <ROVehicle.h>
Public Member Functions
virtual ROVehicle * copy (const std::string &id, unsigned int depTime, RORouteDef *newRoute)
Returns a copy of the vehicle using a new id, departure time and route.
SUMOTime getDepartureTime () const
Returns the time the vehicle starts at.
const std::string & getID () const
Returns the id of the vehicle.
RORouteDef * getRouteDefinition () const
Returns the definition of the route the vehicle takes.
const SUMOVTypeParameter * getType () const
Returns the type of the vehicle.
ROVehicle (const SUMOVehicleParameter &pars, RORouteDef *route, SUMOVTypeParameter *type)
Constructor.
void saveAllAsXML (SUMOAbstractRouter< ROEdge, ROVehicle > &router, OutputDevice &os, OutputDevice *const altos, bool withExitTimes) const
Saves the complete vehicle description.
virtual ~ROVehicle ()
Destructor.
Protected Attributes
SUMOVehicleParameter myParameter
The vehicle's parameter.
RORouteDef * myRoute
The route the vehicle takes.
SUMOVTypeParameter * myType
The type of the vehicle.
Private Member Functions
ROVehicle & operator= (const ROVehicle &src)
Invalidated assignment operator.
ROVehicle (const ROVehicle &src)
Invalidated copy constructor.
Detailed Description
A vehicle as used by router.
Definition at line 59 of file ROVehicle.h.
Constructor & Destructor Documentation
ROVehicle::ROVehicle (const SUMOVehicleParameter & pars, RORouteDef * route, SUMOVTypeParameter * type)
Constructor.
Parameters:
[in] pars Parameter of this vehicle
[in] route The definition of the route the vehicle shall use
[in] type The type of the vehicle
Todo:
Why is the vehicle builder given?
Definition at line 55 of file ROVehicle.cpp.
Referenced by copy().
ROVehicle::~ROVehicle () [virtual]
Destructor.
Definition at line 60 of file ROVehicle.cpp.
ROVehicle::ROVehicle (const ROVehicle & src) [private]
Invalidated copy constructor.
Member Function Documentation
ROVehicle * ROVehicle::copy (const std::string & id, unsigned int depTime, RORouteDef * newRoute) [virtual]
Returns a copy of the vehicle using a new id, departure time and route.
Parameters:
[in] id the new id to use
[in] depTime The new vehicle's departure time
[in] newRoute The new vehicle's route
Returns:
The new vehicle
Todo:
Is this used? What for if everything is replaced?
Definition at line 97 of file ROVehicle.cpp.
References SUMOVehicleParameter::depart, SUMOVehicleParameter::id, myParameter, myType, and ROVehicle().
Referenced by RORDGenerator_ODAmounts::FlowDef::addSingleRoute().
SUMOTime ROVehicle::getDepartureTime () const [inline]
Returns the time the vehicle starts at.
Returns:
The vehicle's depart time
Definition at line 112 of file ROVehicle.h.
References SUMOVehicleParameter::depart, and myParameter.
Referenced by RONet::computeRoute(), ROVehicleByDepartureComperator::operator()(), RONet::saveAndRemoveRoutesUntil(), RORouteDef_Complete::writeXMLDefinition(), RORouteDef_Alternatives::writeXMLDefinition(), and RORoute::writeXMLDefinition().
const std::string& ROVehicle::getID () const [inline]
Returns the id of the vehicle.
Returns:
The id of the vehicle
Definition at line 103 of file ROVehicle.h.
References SUMOVehicleParameter::id, and myParameter.
Referenced by RORouteDef_Alternatives::addAlternative(), RORDGenerator_ODAmounts::FlowDef::addSingleRoute(), RORouteDef_Complete::buildCurrentRoute(), RONet::computeRoute(), ROVehicleCont::erase(), ROVehicleByDepartureComperator::operator()(), and RONet::saveAndRemoveRoutesUntil().
RORouteDef* ROVehicle::getRouteDefinition () const [inline]
Returns the definition of the route the vehicle takes.
Returns:
The vehicle's route definition
Todo:
Why not return a reference?
Definition at line 83 of file ROVehicle.h.
References myRoute.
Referenced by RONet::computeRoute().
const SUMOVTypeParameter* ROVehicle::getType () const [inline]
Returns the type of the vehicle.
Returns:
The vehicle's type
Todo:
Why not return a reference?
Definition at line 94 of file ROVehicle.h.
References myType.
Referenced by ROEdge::getCO2Effort(), ROEdge::getCOEffort(), ROEdge::getFuelEffort(), ROEdge::getHCEffort(), ROEdge::getNoiseEffort(), ROEdge::getNOxEffort(), ROEdge::getPMxEffort(), and ROEdge::prohibits().
ROVehicle& ROVehicle::operator= (const ROVehicle & src) [private]
Invalidated assignment operator.
void ROVehicle::saveAllAsXML (SUMOAbstractRouter< ROEdge, ROVehicle > & router, OutputDevice & os, OutputDevice *const altos, bool withExitTimes) const
Saves the complete vehicle description.
Saves the vehicle type if it was not saved before. Saves the vehicle route if it was not saved before. Saves the vehicle itself.
Parameters:
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] route !!!describe
Exceptions:
IOError If something fails (not yet implemented)
Todo:
What is the given route definition?
Definition at line 64 of file ROVehicle.cpp.
References OutputDevice::closeTag(), OptionsCont::getOptions(), ReferencedItem::isSaved(), myParameter, myRoute, myType, SUMOVTypeParameter::saved, SUMOVTypeParameter::write(), SUMOVehicleParameter::writeAs(), and RORouteDef::writeXMLDefinition().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
SUMOVehicleParameter ROVehicle::myParameter [protected]
The vehicle's parameter.
Definition at line 147 of file ROVehicle.h.
Referenced by copy(), getDepartureTime(), getID(), and saveAllAsXML().
RORouteDef* ROVehicle::myRoute [protected]
The route the vehicle takes.
Definition at line 153 of file ROVehicle.h.
Referenced by getRouteDefinition(), and saveAllAsXML().
SUMOVTypeParameter* ROVehicle::myType [protected]
The type of the vehicle.
Definition at line 150 of file ROVehicle.h.
Referenced by copy(), getType(), and saveAllAsXML().
The documentation for this class was generated from the following files:
ROVehicle.h
ROVehicle.cpp