SUMO - Simulation of Urban MObility: MSDetectorFileOutput Class Reference
MSDetectorFileOutput Class Reference
Base of value-generating classes (detectors).
#include <MSDetectorFileOutput.h>
Public Member Functions
const std::string & getID () const
Returns the id.
MSDetectorFileOutput (const std::string &id)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MSDetectorFileOutput ()
(virtual) destructor
Protected Attributes
std::string myID
The name of the object.
Virtual methods to implement by derived classes
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values).
virtual void reset ()
Resets collected values.
virtual void writeXMLDetectorProlog (OutputDevice &dev) const =0
Open the XML-output.
virtual void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)=0
Write the generated output to the given device.
MSDetectorFileOutput (const MSDetectorFileOutput &)
Invalidated copy constructor.
MSDetectorFileOutput & operator= (const MSDetectorFileOutput &)
Invalidated assignment operator.
Detailed Description
Base of value-generating classes (detectors).
Pure virtual base class for classes (e.g. MSInductLoop) that should produce XML-output.
Definition at line 65 of file MSDetectorFileOutput.h.
Constructor & Destructor Documentation
MSDetectorFileOutput::MSDetectorFileOutput (const std::string & id) [inline]
Constructor.
Definition at line 68 of file MSDetectorFileOutput.h.
virtual MSDetectorFileOutput::~MSDetectorFileOutput () [inline, virtual]
(virtual) destructor
Definition at line 72 of file MSDetectorFileOutput.h.
MSDetectorFileOutput::MSDetectorFileOutput (const MSDetectorFileOutput &) [private]
Invalidated copy constructor.
Member Function Documentation
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () [inline, virtual]
Builds the graphical representation.
Meant to be overridden by grahical versions of the detectors
Returns:
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUI_E2_ZS_CollectorOverLanes, GUIE3Collector, GUIInductLoop, and GUIInstantInductLoop.
Definition at line 121 of file MSDetectorFileOutput.h.
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) [inline, virtual]
Updates the detector (computes values).
Parameters:
[in] step The current time step
Reimplemented in MSE2Collector, MSE3Collector, MSMeanData, and MSMeanData_Harmonoise.
Definition at line 113 of file MSDetectorFileOutput.h.
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
MSDetectorFileOutput& MSDetectorFileOutput::operator= (const MSDetectorFileOutput &) [private]
Invalidated assignment operator.
virtual void MSDetectorFileOutput::reset () [inline, virtual]
Resets collected values.
Please note that this is only a "hack" for coupled-tls-outputs.
See also:
Command_SaveTLCoupledLaneDet
Todo:
Reckeck/refactor
Reimplemented in GUIInductLoop, MSE2Collector, MSE3Collector, and MSInductLoop.
Definition at line 106 of file MSDetectorFileOutput.h.
Referenced by Command_SaveTLCoupledLaneDet::execute().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
virtual void MSDetectorFileOutput::writeXMLDetectorProlog (OutputDevice & dev) const [pure virtual]
Open the XML-output.
The implementing function should open an xml element using OutputDevice::writeXMLHeader.
Parameters:
[in] dev The output device to write the root into
Exceptions:
IOError If an error on writing occurs
Implemented in MS_E2_ZS_CollectorOverLanes, MSE2Collector, MSE3Collector, MSInductLoop, MSInstantInductLoop, MSMeanData, and MSRouteProbe.
Referenced by MSDetectorControl::addDetectorAndInterval(), and Command_SaveTLCoupledDet::Command_SaveTLCoupledDet().
virtual void MSDetectorFileOutput::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) [pure virtual]
Write the generated output to the given device.
Parameters:
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions:
IOError If an error on writing occurs
Implemented in MS_E2_ZS_CollectorOverLanes, MSE2Collector, MSE3Collector, MSInductLoop, MSInstantInductLoop, MSMeanData, and MSRouteProbe.
Referenced by Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), and MSDetectorControl::writeOutput().
Field Documentation
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
The documentation for this class was generated from the following file:
MSDetectorFileOutput.h