SUMO - Simulation of Urban MObility: MyHandler2 Class Reference
MyHandler2 Class Reference
#include <MyHandler2.h>
Public Member Functions
void fatalError (const SAXParseException &)
MyHandler2 ()
void showVehiclesToTrack (std::vector< VehicleToTrack > &vehicles)
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
Data Fields
std::vector< VehicleToTrack > vehicles
Private Member Functions
bool exists (std::vector< VehicleToTrack > &vec, const std::string &vehicle)
void processAttribute (VehicleToTrack &vehicle, const Attributes &attr)
!!!Here you need to add another argument (vehicle) to set information to vehicle.
Detailed Description
Definition at line 24 of file MyHandler2.h.
Constructor & Destructor Documentation
MyHandler2::MyHandler2 ()
Definition at line 25 of file MyHandler2.cpp.
Member Function Documentation
bool MyHandler2::exists (std::vector< VehicleToTrack > & vec, const std::string & vehicle) [private]
Definition at line 30 of file MyHandler2.cpp.
Referenced by startElement().
void MyHandler2::fatalError (const SAXParseException & exception)
Definition at line 255 of file MyHandler2.cpp.
void MyHandler2::processAttribute (VehicleToTrack & vehicle, const Attributes & attr) [private]
!!!Here you need to add another argument (vehicle) to set information to vehicle.
Definition at line 107 of file MyHandler2.cpp.
References VehicleToTrack::setAsConsumption(), VehicleToTrack::setBehaviour(), VehicleToTrack::setCoefDrag(), VehicleToTrack::setCoefRollingResistance(), VehicleToTrack::setConstantLoss(), VehicleToTrack::setCooperLossCoef(), VehicleToTrack::setFinalPoint(), VehicleToTrack::setFrontalArea(), VehicleToTrack::setGearRatio(), VehicleToTrack::setGearSystemEff(), VehicleToTrack::setHeatingConsumption(), VehicleToTrack::setIdentifier(), VehicleToTrack::setInitialBattery(), VehicleToTrack::setInitialPoint(), VehicleToTrack::setIronLossCoef(), VehicleToTrack::setLights(), VehicleToTrack::setMass(), VehicleToTrack::setMaxPower(), VehicleToTrack::setMotorEff(), VehicleToTrack::setNominalCapacity(), VehicleToTrack::setNumberCells(), VehicleToTrack::setOverlioad(), VehicleToTrack::setPeukertCoeff(), VehicleToTrack::setRadioConsumption(), VehicleToTrack::setRegenRatio(), VehicleToTrack::setTimeCharge(), VehicleToTrack::setVehicleType(), VehicleToTrack::setWidescreenCons(), VehicleToTrack::setWindageLossCoef(), and vehicles.
Referenced by startElement().
void MyHandler2::showVehiclesToTrack (std::vector< VehicleToTrack > & vehicles)
Definition at line 262 of file MyHandler2.cpp.
void MyHandler2::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs)
Definition at line 41 of file MyHandler2.cpp.
References exists(), processAttribute(), VehicleToTrack::setIdentifier(), and vehicles.
Field Documentation
std::vector<VehicleToTrack> MyHandler2::vehicles
Definition at line 33 of file MyHandler2.h.
Referenced by processAttribute(), and startElement().
The documentation for this class was generated from the following files:
MyHandler2.h
MyHandler2.cpp