SUMO - Simulation of Urban MObility: PointOfInterest Class Reference
PointOfInterest Class Reference
A point-of-interest.
#include <PointOfInterest.h>
Public Member Functions
void add (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Adds the given position to this one.
void add (SUMOReal dx, SUMOReal dy)
Adds the given position to this one.
void add (const Position &pos)
Adds the given position to this one.
bool almostSame (const Position &p2, SUMOReal maxDiv=POSITION_EPS) const
SUMOReal blue () const
Returns the blue-amount of the color.
RGBColor changedBrightness (SUMOReal change)
Returns a new color with altered brightness.
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
SUMOReal distanceSquaredTo (const Position &p2) const
SUMOReal distanceSquaredTo2D (const Position &p2) const
SUMOReal distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
SUMOReal distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
SUMOReal dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
const std::string & getID () const
Returns the id.
const std::string & getType () const
Returns the (abstract) type of the poi.
SUMOReal green () const
Returns the green-amount of the color.
void mul (SUMOReal mx, SUMOReal my, SUMOReal mz)
Multiplies position with the given values.
void mul (SUMOReal mx, SUMOReal my)
Multiplies position with the given values.
void mul (SUMOReal val)
Multiplies both positions with the given value.
void norm2d ()
bool operator!= (const Position &p2) const
bool operator!= (const RGBColor &c) const
Position operator* (SUMOReal scalar) const
Position operator+ (const Position &p2) const
Position operator- (const Position &p2) const
bool operator== (const Position &p2) const
bool operator== (const RGBColor &c) const
PointOfInterest (const std::string &id, const std::string &type, const Position &p, const RGBColor &c)
Constrcutor.
SUMOReal red () const
Returns the red-amount of the color.
void reshiftRotate (SUMOReal xoff, SUMOReal yoff, SUMOReal rot)
void set (const Position &pos)
void set (SUMOReal x, SUMOReal y, SUMOReal z)
void set (SUMOReal x, SUMOReal y)
void set (SUMOReal r, SUMOReal g, SUMOReal b)
assigns new values
void setID (const std::string &newID)
resets the id
void setType (const std::string &type)
Sets a new type.
void sub (const Position &pos)
Substracts the given position from this one.
void sub (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Substracts the given position from this one.
void sub (SUMOReal dx, SUMOReal dy)
Substracts the given position from this one.
SUMOReal x () const
Returns the x-position.
SUMOReal y () const
Returns the y-position.
SUMOReal z () const
Returns the z-position.
virtual ~PointOfInterest ()
Destructor.
Static Public Member Functions
static RGBColor fromHSV (SUMOReal h, SUMOReal s, SUMOReal v)
Converts the given hsv-triplet to rgb.
static RGBColor getDefaultColor ()
Returns the default color by parsing DEFAULT_COLOR_STRING.
static RGBColor interpolate (const RGBColor &minColor, const RGBColor &maxColor, SUMOReal weight)
Interpolates between two colors.
static RGBColor parseColor (const std::string &coldef) throw (EmptyData, NumberFormatException)
Parses a color information.
static RGBColor parseColorReporting (const std::string &coldef, const std::string &objecttype, const char *objectid, bool report, bool &ok)
Parses a color information.
Static Public Attributes
static const RGBColor DEFAULT_COLOR = RGBColor::parseColor(RGBColor::DEFAULT_COLOR_STRING)
The default color (for vehicle types and vehicles).
static const std::string DEFAULT_COLOR_STRING = "1,1,0"
The string description of the default color.
Protected Attributes
std::string myID
The name of the object.
std::string myType
the type of the poi
Friends
std::ostream & operator<< (std::ostream &os, const Position &p)
Prints to the output.
std::ostream & operator<< (std::ostream &os, const RGBColor &col)
Writes the color to the given stream.
Detailed Description
A point-of-interest.
Definition at line 48 of file PointOfInterest.h.
Constructor & Destructor Documentation
PointOfInterest::PointOfInterest (const std::string & id, const std::string & type, const Position & p, const RGBColor & c) [inline]
Constrcutor.
Parameters:
[in] id The id of the POI
[in] type The (abstract) type of the poi
[in] p The position of the poi
[in] c The color of the poi
Definition at line 56 of file PointOfInterest.h.
virtual PointOfInterest::~PointOfInterest () [inline, virtual]
Destructor.
Definition at line 62 of file PointOfInterest.h.
Member Function Documentation
void Position::add (SUMOReal dx, SUMOReal dy, SUMOReal dz) [inline, inherited]
Adds the given position to this one.
Definition at line 132 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::add (SUMOReal dx, SUMOReal dy) [inline, inherited]
Adds the given position to this one.
Definition at line 126 of file Position.h.
References Position::myX, and Position::myY.
void Position::add (const Position & pos) [inline, inherited]
Adds the given position to this one.
Definition at line 119 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by Line::add(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeContinuationNodeShape(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GUIEdge::drawGL(), GLHelper::drawTextBox(), Line::extrapolateBy(), NBNode::getEmptyDir(), Line::move2side(), GeoConvHelper::moveConvertedBy(), Line::rotateAround(), Line::rotateAtP1(), GUISUMOAbstractView::showToolTipFor(), GeomHelper::transfer_to_side(), and GeoConvHelper::x2cartesian_const().
bool Position::almostSame (const Position & p2, SUMOReal maxDiv = POSITION_EPS) const [inline, inherited]
Definition at line 202 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBNode::computeInternalLaneShape(), AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
SUMOReal RGBColor::blue () const [inline, inherited]
Returns the blue-amount of the color.
Returns:
The red component's value
Definition at line 91 of file RGBColor.h.
References RGBColor::myBlue.
Referenced by RGBColor::changedBrightness(), GUIDialog_ViewSettings::convert(), GUIPointOfInterest::drawGL(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), MSVehicleType::saveState(), and GLHelper::setColor().
RGBColor RGBColor::changedBrightness (SUMOReal change) [inherited]
Returns a new color with altered brightness.
Parameters:
[in] change The absolute change applied to all channels (within bounds)
Returns:
The new color
Definition at line 107 of file RGBColor.cpp.
References RGBColor::blue(), RGBColor::green(), MAX2(), MIN2(), RGBColor::myBlue, RGBColor::myGreen, RGBColor::myRed, RGBColor::red(), RGBColor::RGBColor(), and SUMOReal.
Referenced by drawAction_drawVehicleAsPoly().
Position Position::crossProduct (const Position & pos) [inline, inherited]
returns the cross product between this point and the second one
Definition at line 229 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
SUMOReal Position::distanceSquaredTo (const Position & p2) const [inline, inherited]
Definition at line 213 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by GeomHelper::distancePointLine(), and Position::distanceTo().
SUMOReal Position::distanceSquaredTo2D (const Position & p2) const [inline, inherited]
Definition at line 224 of file Position.h.
References Position::myX, and Position::myY.
Referenced by Position::distanceTo2D().
SUMOReal Position::distanceTo (const Position & p2) const [inline, inherited]
returns the euclidean distance in 3 dimension
Definition at line 208 of file Position.h.
References Position::distanceSquaredTo().
Referenced by NBEdge::buildInnerEdges(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBNode::computeInternalLaneShape(), NIVissimEdge::dict_checkEdges2Join(), NBHelpers::distance(), GeomHelper::distancePointLine(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GeomHelper::extrapolate_first(), GeomHelper::extrapolate_second(), Line::extrapolateBy(), NBNodeCont::generateNodeClusters(), Line::getPositionAtDistance(), GUIBusStop::GUIBusStop(), GUILaneWrapper::GUILaneWrapper(), PositionVector::indexOfClosest(), NBEdge::init(), GeomHelper::interpolate(), Line::length(), PositionVector::move2side(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), PositionVector::nearest_position_on_line_to_point(), GUIViewTraffic::onGamingClick(), PositionVector::positionAtLengthPosition(), NIVissimEdge::remapOneOfNodes(), GUIVehicle::setFunctionalColor(), and PositionVector::splitAt().
SUMOReal Position::distanceTo2D (const Position & p2) const [inline, inherited]
returns the euclidean distance in the x-y-plane
Definition at line 219 of file Position.h.
References Position::distanceSquaredTo2D().
Referenced by GeomHelper::closestDistancePointLine(), GeomHelper::getNormal90D_CW(), PositionVector::intersectsAtLengths2D(), Line::intersectsAtLengths2D(), Line::length2D(), and GeomHelper::nearest_position_on_line_to_point2D().
SUMOReal Position::dotProduct (const Position & pos) [inline, inherited]
returns the dot product (scalar product) between this point and the second one
Definition at line 237 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
RGBColor RGBColor::fromHSV (SUMOReal h, SUMOReal s, SUMOReal v) [static, inherited]
Converts the given hsv-triplet to rgb.
Parameters:
[in] h Hue (0-360)
[in] s Saturation (0-1)
[in] v Value (0-1)
Returns:
The color as RGB
Author:
Alvy Ray Smith (http://www.alvyray.com/default.htm)
Definition at line 176 of file RGBColor.cpp.
References RGBColor::RGBColor().
Referenced by GUIVehicle::setFunctionalColor().
RGBColor RGBColor::getDefaultColor () [static, inherited]
Returns the default color by parsing DEFAULT_COLOR_STRING.
Returns:
The default color
Definition at line 155 of file RGBColor.cpp.
References RGBColor::DEFAULT_COLOR_STRING, and RGBColor::parseColor().
Referenced by MSRouteHandler::openRoute().
const std::string& Named::getID () const [inline, inherited]
Returns the id.
Returns:
The stored id
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 61 of file Named.h.
References Named::myID.
Referenced by ShapeContainer::add(), MSDetectorControl::add(), RORouteDef_Alternatives::addAlternative(), MSNet::addBusStop(), NLHandler::addConnection(), NBLoadedSUMOTLDef::addConnection(), NIImporter_OpenDrive::addE2EConnectionsSecure(), RONet::addNode(), NIImporter_SUMO::addPhase(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), MSRouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), NIVisumTL::build(), MS_E2_ZS_CollectorOverLanes::buildCollector(), RORouteDef_Complete::buildCurrentRoute(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), NBNodeCont::buildOffRamp(), NBNodeCont::buildOnRamp(), ODDistrictHandler::closeDistrict(), NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::collectLinks(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBNode::computeNodeShape(), NBTrafficLightLogicCont::computeSingleLogic(), NBEdge::connections_sorter(), MSLane::detectCollisions(), NIVissimDistrictConnection::dict_BuildDistricts(), MSE3Collector::enter(), MSVTypeProbe::execute(), Command_SaveTLSSwitches::execute(), NBTrafficLightLogicCont::extract(), NBNodeCont::extract(), NBEdgeCont::extract(), MSNet::getBusStopID(), NIImporter_VISUM::getNamedEdgeContinuating(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), NLTriggerBuilder::getPosition(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBEdgeCont::ignoreFilterMatch(), MSAgentbasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NIImporter_SUMO::initTrafficLightLogic(), NBTrafficLightLogicCont::insert(), NBNodeCont::insert(), NBEdgeCont::insert(), NBDistrictCont::insert(), NBNodeCont::joinJunctions(), MSE3Collector::leave(), NIImporter_OpenDrive::loadNetwork(), MSLane::moveCritical(), MSVehicle::MSVehicle(), RORDLoader_SUMOBase::myCharacters(), NBOwnTLDef::myCompute(), NBLoadedTLDef::myCompute(), NIXMLTrafficLightsHandler::myEndElement(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_Tripinfo::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), Named::ComparatorIdLess::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), NBLoadedTLDef::SignalGroup::patchTYellow(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_InductionLoop::processGet(), NWWriter_SUMO::prohibitionConnection(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::removeUnwishedNodes(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NBNodeCont::setAsTLControlled(), NBEdge::setControllingTLInformation(), MSLane::setCritical(), NIXMLEdgesHandler::setNodes(), NBOwnTLDef::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBEdgeCont::splitAt(), RORDLoader_SUMOBase::startRoute(), NBEdge::startShapeAt(), NIXMLConnectionsHandler::validateLaneInfo(), MSInstantInductLoop::write(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), MSVehicle::writeSyntheticData(), MSInductLoop::writeTypedXMLOutput(), MSRouteProbe::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
const std::string& PointOfInterest::getType () const [inline]
Returns the (abstract) type of the poi.
Returns:
The polygon's (abstract) type
Definition at line 69 of file PointOfInterest.h.
References myType.
Referenced by TraCIServerAPI_POI::processGet().
SUMOReal RGBColor::green () const [inline, inherited]
Returns the green-amount of the color.
Returns:
The red component's value
Definition at line 83 of file RGBColor.h.
References RGBColor::myGreen.
Referenced by RGBColor::changedBrightness(), GUIDialog_ViewSettings::convert(), GUIPointOfInterest::drawGL(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), MSVehicleType::saveState(), and GLHelper::setColor().
RGBColor RGBColor::interpolate (const RGBColor & minColor, const RGBColor & maxColor, SUMOReal weight) [static, inherited]
Interpolates between two colors.
The interpolated color is calculated as a weighted average of the RGB values of minColor and maxColor, giving weight to maxColor and 1-weight to minColor.
Parameters:
[in] minColor The color to interpolate from
[in] maxColor The color to interpolate to
[in] weight The weight of the first color
Returns:
The interpolated color
Definition at line 161 of file RGBColor.cpp.
References RGBColor::myBlue, RGBColor::myGreen, RGBColor::myRed, RGBColor::RGBColor(), and SUMOReal.
Referenced by GUIColorScheme::getColor().
void Position::mul (SUMOReal mx, SUMOReal my, SUMOReal mz) [inline, inherited]
Multiplies position with the given values.
Definition at line 112 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::mul (SUMOReal mx, SUMOReal my) [inline, inherited]
Multiplies position with the given values.
Definition at line 106 of file Position.h.
References Position::myX, and Position::myY.
void Position::mul (SUMOReal val) [inline, inherited]
Multiplies both positions with the given value.
Definition at line 99 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeContinuationNodeShape(), GUIEdge::drawGL(), and NBNode::getEmptyDir().
void Position::norm2d () [inline, inherited]
Definition at line 158 of file Position.h.
References Position::myX, Position::myY, and SUMOReal.
Referenced by NBNode::getEmptyDir().
bool Position::operator!= (const Position & p2) const [inline, inherited]
Definition at line 197 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
bool RGBColor::operator!= (const RGBColor & c) const [inherited]
Definition at line 100 of file RGBColor.cpp.
References RGBColor::myBlue, RGBColor::myGreen, and RGBColor::myRed.
Position Position::operator* (SUMOReal scalar) const [inline, inherited]
Definition at line 189 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator+ (const Position & p2) const [inline, inherited]
Definition at line 181 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator- (const Position & p2) const [inline, inherited]
Definition at line 185 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
bool Position::operator== (const Position & p2) const [inline, inherited]
Definition at line 193 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
bool RGBColor::operator== (const RGBColor & c) const [inherited]
Definition at line 93 of file RGBColor.cpp.
References RGBColor::myBlue, RGBColor::myGreen, and RGBColor::myRed.
RGBColor RGBColor::parseColor (const std::string & coldef) throw (EmptyData, NumberFormatException) [static, inherited]
Parses a color information.
It is assumed that the color is stored as "<RED>,<GREEN>,<BLUE>" And each color is represented as a SUMOReal.
Parameters:
[in] coldef The color definition to parse
Returns:
The parsed color
Exceptions:
EmptyData If the definition has less than three entries
NumberFormatException If one of the components is not numeric
Definition at line 116 of file RGBColor.cpp.
References TplConvert< E >::_2SUMOReal(), StringTokenizer::next(), StringTokenizer::size(), and SUMOReal.
Referenced by RGBColor::getDefaultColor(), PCLoaderVisum::load(), PCLoaderArcView::load(), PCLoaderOSM::loadIfSet(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), PCLoaderXML::myStartElement(), RGBColor::parseColorReporting(), and SUMOVehicleParserHelper::parseCommonAttributes().
RGBColor RGBColor::parseColorReporting (const std::string & coldef, const std::string & objecttype, const char * objectid, bool report, bool & ok) [static, inherited]
Parses a color information.
It is assumed that the color is stored as "<RED>,<GREEN>,<BLUE>" And each color is represented as a SUMOReal.
Parameters:
[in] coldef The color definition to parse
[in] objecttype The type of the currently parsed object
[in] objectid The id of the currently parsed object
[in] report Whether errors shall be reported
[in,out] ok Whether parsing was successful
Returns:
The parsed color
Exceptions:
EmptyData If the definition has less than three entries
NumberFormatException If one of the components is not numeric
Definition at line 129 of file RGBColor.cpp.
References RGBColor::parseColor(), RGBColor::RGBColor(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by NLHandler::addPOI(), NLHandler::addPoly(), SUMOVehicleParserHelper::beginVTypeParsing(), GUISettingsHandler::myStartElement(), MSRouteHandler::openRoute(), GUISettingsHandler::parseTextSettings(), and RORDLoader_SUMOBase::startRoute().
SUMOReal RGBColor::red () const [inline, inherited]
Returns the red-amount of the color.
Returns:
The red component's value
Definition at line 75 of file RGBColor.h.
References RGBColor::myRed.
Referenced by RGBColor::changedBrightness(), GUIDialog_ViewSettings::convert(), GUIPointOfInterest::drawGL(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), MSVehicleType::saveState(), and GLHelper::setColor().
void Position::reshiftRotate (SUMOReal xoff, SUMOReal yoff, SUMOReal rot) [inline, inherited]
Definition at line 164 of file Position.h.
References Position::myX, Position::myY, SUMOReal, Position::x(), and Position::y().
Referenced by NBNode::reshiftPosition(), NBDistrict::reshiftPosition(), and Line::rotateAtP1().
void Position::set (const Position & pos) [inline, inherited]
Definition at line 91 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::set (SUMOReal x, SUMOReal y, SUMOReal z) [inline, inherited]
Definition at line 84 of file Position.h.
References Position::myX, Position::myY, Position::myZ, Position::x(), Position::y(), and Position::z().
void Position::set (SUMOReal x, SUMOReal y) [inline, inherited]
Definition at line 78 of file Position.h.
References Position::myX, Position::myY, Position::x(), and Position::y().
Referenced by NIXMLNodesHandler::addNode(), GeoConvHelper::cartesian2geo(), GeomHelper::closestDistancePointLine(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
void RGBColor::set (SUMOReal r, SUMOReal g, SUMOReal b) [inherited]
assigns new values
Parameters:
[in] r The red component's value
[in] g The green component's value
[in] b The blue component's value
Definition at line 74 of file RGBColor.cpp.
References RGBColor::myBlue, RGBColor::myGreen, and RGBColor::myRed.
Referenced by TraCIServerAPI_Vehicle::processSet().
void Named::setID (const std::string & newID) [inline, inherited]
resets the id
Definition at line 67 of file Named.h.
References Named::myID.
void PointOfInterest::setType (const std::string & type) [inline]
Sets a new type.
Parameters:
[in] type The new type to use
Definition at line 77 of file PointOfInterest.h.
References myType.
Referenced by TraCIServerAPI_POI::processSet().
void Position::sub (const Position & pos) [inline, inherited]
Substracts the given position from this one.
Definition at line 152 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::sub (SUMOReal dx, SUMOReal dy, SUMOReal dz) [inline, inherited]
Substracts the given position from this one.
Definition at line 145 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::sub (SUMOReal dx, SUMOReal dy) [inline, inherited]
Substracts the given position from this one.
Definition at line 139 of file Position.h.
References Position::myX, and Position::myY.
Referenced by GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), NBNode::computeInternalLaneShape(), GLHelper::drawTextBox(), Line::extrapolateBy(), NBNode::getEmptyDir(), Line::rotateAtP1(), and Line::sub().
SUMOReal Position::x () const [inline, inherited]
Returns the x-position.
Definition at line 63 of file Position.h.
References Position::myX.
Referenced by Line::add(), Boundary::add(), NIXMLNodesHandler::addNode(), PositionVector::around(), Boundary::around(), Line::atan2Angle(), Line::atan2DegreeAngle(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShape(), NBNodeShapeComputer::computeNodeShapeByCrosses(), NGRandomNetBuilder::createNewNode(), GeomHelper::distancePointLine(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GLHelper::drawFilledPoly(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIPointOfInterest::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIEdge::drawGL(), GUIBusStop::drawGL(), GLHelper::drawLine(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextBox(), MSVehicle::enterLaneAtLaneChange(), MSVTypeProbe::execute(), GeomHelper::extrapolate_first(), GeomHelper::extrapolate_second(), MSVehicle::getAngle(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), GeomHelper::getNormal90D_CW(), GeoConvHelper::getOffsetBase(), GUIDanielPerspectiveChanger::getXPos(), GUIBusStop::GUIBusStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILaneWrapper::GUILaneWrapper(), NBEdge::init(), NIXMLEdgesHandler::insertNodeChecking(), GeomHelper::interpolate(), GeomHelper::intersection_position(), GeomHelper::intersects(), PositionVector::isLeft(), isLeft(), main(), PositionVector::move2side(), MSVehicle::moveChecked(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GeomHelper::nearest_position_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PositionVector::increasing_x_y_sorter::operator()(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::positionAtLengthPosition(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Junction::processGet(), NIImporter_SUMO::reconstructEdgeShape(), Position::reshiftRotate(), NBNodeCont::retrieve(), Line::rotateAround(), GUILaneWrapper::ROWdrawAction_drawArrows(), GUILaneWrapper::ROWdrawAction_drawLane2LaneConnections(), GUILaneWrapper::ROWdrawAction_drawLinkNo(), GUILaneWrapper::ROWdrawAction_drawLinkRules(), GUILaneWrapper::ROWdrawAction_drawTLSLinkNo(), Position::set(), GUIVehicle::setFunctionalColor(), NIXMLEdgesHandler::setNodes(), NGNode::setY(), GeomHelper::transfer_to_side(), NILoader::transformCoordinates(), GUISUMOAbstractView::updatePositionInformation(), NWWriter_OpenDrive::writePlanView(), NWFrame::writePositionLong(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::y () const [inline, inherited]
Returns the y-position.
Definition at line 68 of file Position.h.
References Position::myY.
Referenced by Line::add(), Boundary::add(), NIXMLNodesHandler::addNode(), PositionVector::around(), Boundary::around(), Line::atan2Angle(), Line::atan2DegreeAngle(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShape(), NBNodeShapeComputer::computeNodeShapeByCrosses(), NGRandomNetBuilder::createNewNode(), GeomHelper::distancePointLine(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GLHelper::drawFilledPoly(), GUIVehicle::drawGL(), GUITriggeredRerouter::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIPointOfInterest::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUIEdge::drawGL(), GUIBusStop::drawGL(), GLHelper::drawLine(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextBox(), MSVehicle::enterLaneAtLaneChange(), MSVTypeProbe::execute(), GeomHelper::extrapolate_first(), GeomHelper::extrapolate_second(), MSVehicle::getAngle(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), GeomHelper::getNormal90D_CW(), GeoConvHelper::getOffsetBase(), GUIDanielPerspectiveChanger::getYPos(), GUIBusStop::GUIBusStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILaneWrapper::GUILaneWrapper(), NBEdge::init(), NIXMLEdgesHandler::insertNodeChecking(), GeomHelper::interpolate(), GeomHelper::intersection_position(), GeomHelper::intersects(), PositionVector::isLeft(), isLeft(), main(), PositionVector::move2side(), MSVehicle::moveChecked(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GeomHelper::nearest_position_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PositionVector::increasing_x_y_sorter::operator()(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::positionAtLengthPosition(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Junction::processGet(), NIImporter_SUMO::reconstructEdgeShape(), Position::reshiftRotate(), NBNodeCont::retrieve(), Line::rotateAround(), GUILaneWrapper::ROWdrawAction_drawArrows(), GUILaneWrapper::ROWdrawAction_drawLane2LaneConnections(), GUILaneWrapper::ROWdrawAction_drawLinkNo(), GUILaneWrapper::ROWdrawAction_drawLinkRules(), GUILaneWrapper::ROWdrawAction_drawTLSLinkNo(), Position::set(), GUIVehicle::setFunctionalColor(), NIXMLEdgesHandler::setNodes(), NGNode::setX(), GeomHelper::transfer_to_side(), NILoader::transformCoordinates(), GUISUMOAbstractView::updatePositionInformation(), NWWriter_OpenDrive::writePlanView(), NWFrame::writePositionLong(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::z () const [inline, inherited]
Returns the z-position.
Definition at line 73 of file Position.h.
References Position::myZ.
Referenced by NBEdge::computeLaneShape(), Position::set(), and NWFrame::writePositionLong().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Position & p) [friend, inherited]
Prints to the output.
Definition at line 173 of file Position.h.
std::ostream& operator<< (std::ostream & os, const RGBColor & col) [friend, inherited]
Writes the color to the given stream.
Parameters:
[out] os The stream to write to
[in] col The color to write
Returns:
The stream
Definition at line 83 of file RGBColor.cpp.
Field Documentation
const RGBColor RGBColor::DEFAULT_COLOR = RGBColor::parseColor(RGBColor::DEFAULT_COLOR_STRING) [static, inherited]
The default color (for vehicle types and vehicles).
Definition at line 186 of file RGBColor.h.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), SUMOVehicleParserHelper::parseCommonAttributes(), and TraCIServerAPI_Route::processSet().
const std::string RGBColor::DEFAULT_COLOR_STRING = "1,1,0" [static, inherited]
The string description of the default color.
Definition at line 182 of file RGBColor.h.
Referenced by RGBColor::getDefaultColor().
std::string Named::myID [protected, inherited]
The name of the object.
Reimplemented in MS_E2_ZS_CollectorOverLanes.
Definition at line 83 of file Named.h.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), RORouteDef_OrigDest::buildCurrentRoute(), RORouteDef_Complete::buildCurrentRoute(), RORouteDef_Alternatives::buildCurrentRoute(), NBEdge::computeEdgeShape(), Named::getID(), NBEdge::getLaneID(), NBEdge::init(), MSRoute::release(), Named::setID(), NBEdge::splitGeometry(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), MSMeanData::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string PointOfInterest::myType [protected]
the type of the poi
Definition at line 84 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::getPopUpMenu(), getType(), and setType().
The documentation for this class was generated from the following file:
PointOfInterest.h