SUMO - Simulation of Urban MObility: NILoader Class Reference
NILoader Class Reference
Perfoms network import.
#include <NILoader.h>
Public Member Functions
void load (OptionsCont &oc)
NILoader (NBNetBuilder &nb)
Constructor.
~NILoader ()
Destructor.
Static Public Member Functions
static bool transformCoordinates (PositionVector &from, bool includeInBoundary=true, GeoConvHelper *from_srs=0)
static bool transformCoordinates (Position &from, bool includeInBoundary=true, GeoConvHelper *from_srs=0)
transforms loaded coordinates handles projections, offsets (using GeoConvHelper) and import of height data (using Heightmapper if available)
Private Member Functions
void loadXML (OptionsCont &oc)
void loadXMLType (SUMOSAXHandler *handler, const std::vector< std::string > &files, const std::string &type)
NILoader (const NILoader &)
Invalidated copy constructor.
NILoader & operator= (const NILoader &)
Invalidated assignment operator.
Private Attributes
NBNetBuilder & myNetBuilder
The network builder to fill with loaded data.
Detailed Description
Perfoms network import.
A plain loader which encapsulates calls to the import modules.
Definition at line 60 of file NILoader.h.
Constructor & Destructor Documentation
NILoader::NILoader (NBNetBuilder & nb)
Constructor.
Parameters:
[in] nb The network builder to fill with loaded data
Definition at line 79 of file NILoader.cpp.
NILoader::~NILoader ()
Destructor.
Definition at line 83 of file NILoader.cpp.
NILoader::NILoader (const NILoader &) [private]
Invalidated copy constructor.
Member Function Documentation
void NILoader::load (OptionsCont & oc)
loads data from the files specified in the given option container
Definition at line 87 of file NILoader.cpp.
References NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NBEdgeCont::getNoEdgeSplits(), GeoConvHelper::getProcessing(), OptionsCont::getStringVector(), NBNetBuilder::getTypeCont(), GeoConvHelper::init(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_Vissim::loadNetwork(), NIImporter_ArcView::loadNetwork(), NIImporter_VISUM::loadNetwork(), NIImporter_OpenStreetMap::loadNetwork(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_SUMO::loadNetwork(), loadXML(), loadXMLType(), myNetBuilder, NBTypeCont::size(), NBDistrictCont::size(), NBEdgeCont::size(), NBNodeCont::size(), toString(), and WRITE_MESSAGE.
Referenced by main().
void NILoader::loadXML (OptionsCont & oc) [private]
loads data from sumo-files loads data from XML-files
Definition at line 142 of file NILoader.cpp.
References NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::getStringVector(), NBNetBuilder::getTLLogicCont(), NBNetBuilder::getTypeCont(), loadXMLType(), and myNetBuilder.
Referenced by load().
void NILoader::loadXMLType (SUMOSAXHandler * handler, const std::vector< std::string > & files, const std::string & type) [private]
loads data from the list of xml-files of certain type
Definition at line 164 of file NILoader.cpp.
References FileHelpers::exists(), GenericSAXHandler::getFileName(), XMLSubSys::getSAXReader(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, GenericSAXHandler::setFileName(), and WRITE_ERROR.
Referenced by load(), and loadXML().
NILoader& NILoader::operator= (const NILoader &) [private]
Invalidated assignment operator.
bool NILoader::transformCoordinates (PositionVector & from, bool includeInBoundary = true, GeoConvHelper * from_srs = 0) [static]
Definition at line 219 of file NILoader.cpp.
References OptionsCont::getFloat(), OptionsCont::getOptions(), PositionVector::insertAt(), PositionVector::size(), SUMOReal, and transformCoordinates().
bool NILoader::transformCoordinates (Position & from, bool includeInBoundary = true, GeoConvHelper * from_srs = 0) [static]
transforms loaded coordinates handles projections, offsets (using GeoConvHelper) and import of height data (using Heightmapper if available)
Parameters:
[in,out] from The coordinate to be transformed
[in] includeInBoundary Whether to patch the convex boundary of the GeoConvHelper default instance
[in] from_srs The spatial reference system of the input coordinate
Definition at line 199 of file NILoader.cpp.
References GeoConvHelper::cartesian2geo(), GeoConvHelper::getProcessing(), SUMOReal, GeoConvHelper::usingGeoProjection(), Position::x(), GeoConvHelper::x2cartesian(), and Position::y().
Referenced by NIImporter_SUMO::addEdge(), NIImporter_SUMO::addJunction(), NIImporter_SUMO::addLane(), NIXMLNodesHandler::addNode(), NIImporter_OpenDrive::computeShapes(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::insertNodeChecking(), NIImporter_ArcView::load(), NIImporter_RobocupRescue::loadNodes(), NIImporter_ITSUMO::Handler::myEndElement(), NIImporter_MATSim::NodesHandler::myStartElement(), NIVissimAbstractEdge::NIVissimAbstractEdge(), NIImporter_VISUM::parse_Districts(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Nodes(), NIImporter_VISUM::parse_Point(), NIImporter_DlrNavteq::NodesHandler::report(), NIXMLEdgesHandler::setNodes(), transformCoordinates(), and NIXMLEdgesHandler::tryGetShape().
Field Documentation
NBNetBuilder& NILoader::myNetBuilder [private]
The network builder to fill with loaded data.
Definition at line 98 of file NILoader.h.
Referenced by load(), and loadXML().
The documentation for this class was generated from the following files:
NILoader.h
NILoader.cpp