SUMO - Simulation of Urban MObility: GUIPolygon.cpp File Reference
GUIPolygon.cpp File Reference
#include <config.h>
#include <string>
#include "GUIPolygon.h"
#include <utils/shapes/Polygon.h>
#include <utils/gui/globjects/GUIGlObject_AbstractAdd.h>
#include <utils/gui/globjects/GUIGlObject.h>
#include <utils/gui/div/GUIParameterTableWindow.h>
#include <utils/gui/globjects/GUIGLObjectPopupMenu.h>
#include <utils/gui/settings/GUIVisualizationSettings.h>
#include <utils/gui/div/GLHelper.h>
#include <foreign/polyfonts/polyfonts.h>
#include <GL/gl.h>
#include <GL/glu.h>
Functions
void APIENTRY beginCallback (GLenum which)
void APIENTRY combineCallback (GLdouble coords[3], GLdouble *vertex_data[4], GLfloat weight[4], GLdouble **dataOut)
void APIENTRY endCallback (void)
void APIENTRY errorCallback (GLenum errorCode)
void APIENTRY vertexCallback (GLvoid *vertex)
Variables
double glvert [6]
Detailed Description
Author:
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Laura Bieker
Date:
June 2006
Version:
Id
GUIPolygon.cpp 11671 2012-01-07 20:14:30Z behrisch
Definition in file GUIPolygon.cpp.
Function Documentation
void APIENTRY beginCallback (GLenum which)
Definition at line 102 of file GUIPolygon.cpp.
Referenced by GUIPolygon::drawGL().
void APIENTRY combineCallback (GLdouble coords[3], GLdouble * vertex_data[4], GLfloat weight[4], GLdouble ** dataOut)
Definition at line 125 of file GUIPolygon.cpp.
References UNUSED_PARAMETER.
Referenced by GUIPolygon::drawGL().
void APIENTRY endCallback (void)
Definition at line 114 of file GUIPolygon.cpp.
Referenced by GUIPolygon::drawGL().
void APIENTRY errorCallback (GLenum errorCode)
Definition at line 106 of file GUIPolygon.cpp.
void APIENTRY vertexCallback (GLvoid * vertex)
Definition at line 118 of file GUIPolygon.cpp.
Variable Documentation
double glvert[6]
Definition at line 140 of file GUIPolygon.cpp.
Referenced by GUIPolygon::drawGL().