SUMO - Simulation of Urban MObility: NGNode Class Reference
NGNode Class Reference
A netgen-representation of a node.
#include <NGNode.h>
Public Member Functions
void addLink (NGEdge *link)
Adds the given link to the internal list.
NBNode * buildNBNode (NBNetBuilder &nb) const
Builds and returns this node's netbuild-representation.
bool connected (NGNode *node) const
Returns whether the other node is connected.
const std::string & getID () const
Returns this node's id.
SUMOReal getMaxNeighbours ()
Returns this node's maximum neighbour number.
const Position & getPosition () const
Returns this node's position.
NGNode (const std::string &id, int xID, int yID, bool amCenter)
Constructor.
NGNode (const std::string &id, int xPos, int yPos)
Constructor.
NGNode (const std::string &id)
Constructor.
NGNode ()
Constructor.
void removeLink (NGEdge *link)
Removes the given link.
bool samePos (int xPos, int yPos) const
Returns whether the node has the given position.
void setMaxNeighbours (SUMOReal value)
Sets this node's maximum neighbour number.
void setX (SUMOReal x)
Sets a new value for x-position.
void setY (SUMOReal y)
Sets a new value for y-position.
~NGNode ()
Destructor.
Private Attributes
NGEdgeList LinkList
List of connected links.
bool myAmCenter
Information whether this is the center of a cpider-net.
std::string myID
The id of the node.
SUMOReal myMaxNeighbours
The maximum number of neighbours.
Position myPosition
The position of the node.
int xID
Integer x-position (x-id).
int yID
Integer y-position (y-id).
Friends
class NGRandomNetBuilder
Detailed Description
A netgen-representation of a node.
Definition at line 57 of file NGNode.h.
Constructor & Destructor Documentation
NGNode::NGNode ()
Constructor.
Definition at line 57 of file NGNode.cpp.
NGNode::NGNode (const std::string & id)
Constructor.
Parameters:
[in] id The id of the node
Definition at line 61 of file NGNode.cpp.
NGNode::NGNode (const std::string & id, int xPos, int yPos)
Constructor.
Parameters:
[in] id The id of the node
[in] xPos The x-position of the node
[in] yPos The y-position of the node
Definition at line 65 of file NGNode.cpp.
NGNode::NGNode (const std::string & id, int xID, int yID, bool amCenter)
Constructor.
Parameters:
[in] id The id of the node
[in] xPos The x-position of the node
[in] yPos The y-position of the node
[in] amCenter Information whether this is the center-node of a spider-net
Definition at line 69 of file NGNode.cpp.
NGNode::~NGNode ()
Destructor.
Definition at line 73 of file NGNode.cpp.
References LinkList.
Member Function Documentation
void NGNode::addLink (NGEdge * link)
Adds the given link to the internal list.
Parameters:
[in] link The link to add
Definition at line 117 of file NGNode.cpp.
References LinkList.
Referenced by NGEdge::NGEdge().
NBNode * NGNode::buildNBNode (NBNetBuilder & nb) const
Builds and returns this node's netbuild-representation.
The position of the node is transformed to cartesian using GeoConvHelper::x2cartesian, first. If this node is the center node of a spider net, a node of the type NBNode::NODETYPE_NOJUNCTION is returned. Otherwise, a plain node is built and it is checked whether the options indicate building one of the tls node-types. In this case, a logic is built and stored. A ProcessError is thrown if this fails (should never happen, in fact).
Parameters:
[in] nb The netbuilder to retrieve the tls-container from
Returns:
The built node
Exceptions:
ProcessError If the built tls logic could not be added (should never happen)
Todo:
There is no interaction with explicit node setting options? Where is this done?
Check whether throwing an exception is really necessary, here
Definition at line 83 of file NGNode.cpp.
References StringBijection< T >::get(), OptionsCont::getOptions(), GeoConvHelper::getProcessing(), OptionsCont::getString(), NBNetBuilder::getTLLogicCont(), NBTrafficLightLogicCont::insert(), OptionsCont::isSet(), myAmCenter, myID, myPosition, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY_JUNCTION, NODETYPE_TRAFFIC_LIGHT, SUMOXMLDefinitions::NodeTypes, and GeoConvHelper::x2cartesian().
bool NGNode::connected (NGNode * node) const
Returns whether the other node is connected.
Parameters:
[in] node The link to check whether it is connected
Returns:
Whether the given node is connected
Definition at line 129 of file NGNode.cpp.
References LinkList.
Referenced by NGRandomNetBuilder::findPossibleOuterNodes().
const std::string& NGNode::getID () const [inline]
Returns this node's id.
Returns:
The id of the node
Definition at line 97 of file NGNode.h.
References myID.
Referenced by NGEdge::buildNBEdge(), and NGNet::connect().
SUMOReal NGNode::getMaxNeighbours () [inline]
Returns this node's maximum neighbour number.
Returns:
The maximum neighbour number of the node
Definition at line 115 of file NGNode.h.
References myMaxNeighbours.
Referenced by NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), and NGRandomNetBuilder::findPossibleOuterNodes().
const Position& NGNode::getPosition () const [inline]
Returns this node's position.
Returns:
The position of the node
Definition at line 106 of file NGNode.h.
References myPosition.
Referenced by NGRandomNetBuilder::canConnect(), NGRandomNetBuilder::checkAngles(), and NGRandomNetBuilder::createNewNode().
void NGNode::removeLink (NGEdge * link)
Removes the given link.
The given pointer is compared to those in the list. A matching pointer is removed, not other same connections.
Parameters:
[in] link The link to remove
Definition at line 123 of file NGNode.cpp.
References LinkList.
Referenced by NGEdge::~NGEdge().
bool NGNode::samePos (int xPos, int yPos) const [inline]
Returns whether the node has the given position.
Parameters:
[in] node The link to check whether it is connected
Returns:
Whether the given node is connected
Definition at line 195 of file NGNode.h.
void NGNode::setMaxNeighbours (SUMOReal value) [inline]
Sets this node's maximum neighbour number.
Parameters:
[in] value The new maximum neighbour number of the node
Definition at line 124 of file NGNode.h.
References myMaxNeighbours.
Referenced by NGRandomNetBuilder::createNet(), and NGRandomNetBuilder::createNewNode().
void NGNode::setX (SUMOReal x) [inline]
Sets a new value for x-position.
Parameters:
[in] value The new x-position of this node
Definition at line 133 of file NGNode.h.
References myPosition, Position::set(), and Position::y().
Referenced by NGNet::createChequerBoard(), NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), and NGNet::createSpiderWeb().
void NGNode::setY (SUMOReal y) [inline]
Sets a new value for y-position.
Parameters:
[in] value The new y-position of this node
Definition at line 142 of file NGNode.h.
References myPosition, Position::set(), and Position::x().
Referenced by NGNet::createChequerBoard(), NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), and NGNet::createSpiderWeb().
Friends And Related Function Documentation
friend class NGRandomNetBuilder [friend]
Definition at line 200 of file NGNode.h.
Field Documentation
NGEdgeList NGNode::LinkList [private]
List of connected links.
Definition at line 210 of file NGNode.h.
Referenced by addLink(), NGRandomNetBuilder::checkAngles(), connected(), NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), NGRandomNetBuilder::findPossibleOuterNodes(), removeLink(), and ~NGNode().
bool NGNode::myAmCenter [private]
Information whether this is the center of a cpider-net.
Definition at line 222 of file NGNode.h.
Referenced by buildNBNode().
std::string NGNode::myID [private]
The id of the node.
Definition at line 213 of file NGNode.h.
Referenced by buildNBNode(), and getID().
SUMOReal NGNode::myMaxNeighbours [private]
The maximum number of neighbours.
Definition at line 219 of file NGNode.h.
Referenced by getMaxNeighbours(), and setMaxNeighbours().
Position NGNode::myPosition [private]
The position of the node.
Definition at line 216 of file NGNode.h.
Referenced by buildNBNode(), getPosition(), setX(), and setY().
int NGNode::xID [private]
Integer x-position (x-id).
Definition at line 204 of file NGNode.h.
int NGNode::yID [private]
Integer y-position (y-id).
Definition at line 207 of file NGNode.h.
The documentation for this class was generated from the following files:
NGNode.h
NGNode.cpp