SUMO - Simulation of Urban MObility: RORDGenerator_ODAmounts Class Reference
RORDGenerator_ODAmounts Class Reference
#include <RORDGenerator_ODAmounts.h>
Data Structures
class FlowDef
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endDocument ()
Called when the document has ended.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RORDGenerator_ODAmounts (RONet &net, SUMOTime begin, SUMOTime end, bool emptyDestinationsAllowed, bool randomize, const std::string &file="")
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs)
The inherited method called when a new tag opens.
~RORDGenerator_ODAmounts ()
Destructor.
inherited from ROAbstractRouteDefLoader
bool ended () const
Returns the information whether no routes are available from this loader anymore.
SAX ErrorHandler callbacks
void error (const SAXParseException &exception)
Handler for XML-errors.
void fatalError (const SAXParseException &exception)
Handler for XML-errors.
void warning (const SAXParseException &exception)
Handler for XML-warnings.
inherited from ROAbstractRouteDefLoader
SUMOTime getLastReadTimeStep () const
Returns the time the current (last read) route starts at.
inherited from ROAbstractRouteDefLoader
bool readRoutesAtLeastUntil (SUMOTime until, bool skipping)
Adds routes from the file until the given time is reached.
Protected Member Functions
std::string buildErrorMessage (const SAXParseException &exception)
Builds an error message.
ROEdge * getEdge (const SUMOSAXAttributes &attrs, const std::string &purpose, SumoXMLAttr which, const std::string &id, bool emptyAllowed)
Parses a named edge frm the attributes.
std::string getVehicleID (const SUMOSAXAttributes &attrs)
Parses the vehicle id.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void myEndFlowAmountDef ()
Closes the trip amount parsing.
void myEndInterval ()
Closes the current embedding interval.
void parseFlowAmountDef (const SUMOSAXAttributes &attrs)
Parses the trip amount definition.
void parseInterval (const SUMOSAXAttributes &attrs)
Parses the interval information.
inherited from ROTypedXMLRoutesLoader
void beginNextRoute ()
Returns Initialises the reading of a further route.
bool nextRouteRead ()
inherited from GenericSAXHandler
void myEndElement (int element)
Called when a closing tag occurs.
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
SUMOTime myBegin
The time for which the first route shall be loaded.
ROEdge * myBeginEdge
The starting edge.
SUMOVTypeParameter * myCurrentVehicleType
The currently parsed vehicle type.
SUMOTime myDepartureTime
const bool myEmptyDestinationsAllowed
Information whether empty destinations are allowed This is a feature used for the handling of explicit routes within the jtrrouter where the destination is not necessary.
SUMOTime myEnd
The time for which the first route shall be loaded.
bool myEnded
Information whether the whole file has been parsed.
ROEdge * myEndEdge
The end edge.
bool myHaveWarnedAboutDeprecatedTripDef
IDSupplier myIdSupplier
generates numerical ids
RONet & myNet
The network to add routes to.
bool myNextRouteRead
The information whether the next route was read.
SUMOVehicleParameter * myParameter
SAX2XMLReader * myParser
The parser used.
XMLPScanToken myToken
Information about the current position within the file.
const bool myWithTaz
Information whether zones (districts) are used as origins / destinations.
Private Types
typedef std::vector< FlowDef * > FlowDefV
Definition of a container for flo definitions (vector).
Private Member Functions
void buildForTimeStep (SUMOTime time)
Builds the routes for the given time step.
void buildRoutes (SUMOTime until)
Builds the routes between the current time step and the one given.
RORDGenerator_ODAmounts & operator= (const RORDGenerator_ODAmounts &src)
Invalidated assignment operator.
RORDGenerator_ODAmounts (const RORDGenerator_ODAmounts &src)
Invalidated copy constructor.
Private Attributes
SUMOTime myCurrentTimeStep
The current time step read.
FlowDefV myFlows
The definitions of the read flows.
bool myHaveWarnedAboutDeprecatedNumber
SUMOTime myIntervalBegin
The begin of the interval current read.
SUMOTime myIntervalEnd
The end of the interval current read.
std::set< std::string > myKnownIDs
A storage for ids (!!! this should be done router-wide).
bool myRandom
Information whether randomized departures are used.
SUMOTime myUpperIntervalBegin
The begin of the embedding interval (if given).
SUMOTime myUpperIntervalEnd
The end of the embedding interval (if given).
unsigned int myVehicle2InsertNumber
The number of vehicles to insert.
Detailed Description
This class is a file-based generator. Within the first step, all route definitions are parsed into the memory from a file and then consecutively build on demand.
Definition at line 54 of file RORDGenerator_ODAmounts.h.
Member Typedef Documentation
typedef std::vector<FlowDef*> RORDGenerator_ODAmounts::FlowDefV [private]
Definition of a container for flo definitions (vector).
Definition at line 199 of file RORDGenerator_ODAmounts.h.
Constructor & Destructor Documentation
RORDGenerator_ODAmounts::RORDGenerator_ODAmounts (RONet & net, SUMOTime begin, SUMOTime end, bool emptyDestinationsAllowed, bool randomize, const std::string & file = "")
Constructor.
Definition at line 140 of file RORDGenerator_ODAmounts.cpp.
References GenericSAXHandler::getFileName(), ROAbstractRouteDefLoader::myBegin, RORDLoader_TripDefs::myDepartureTime, ROTypedXMLRoutesLoader::myParser, and ROTypedXMLRoutesLoader::myToken.
RORDGenerator_ODAmounts::~RORDGenerator_ODAmounts ()
Destructor.
Definition at line 156 of file RORDGenerator_ODAmounts.cpp.
References myFlows.
RORDGenerator_ODAmounts::RORDGenerator_ODAmounts (const RORDGenerator_ODAmounts & src) [private]
Invalidated copy constructor.
Member Function Documentation
void RORDLoader_TripDefs::beginNextRoute () [protected, virtual, inherited]
Returns Initialises the reading of a further route.
Todo:
recheck/refactor
See also:
ROTypedXMLRoutesLoader::beginNextRoute
Implements ROTypedXMLRoutesLoader.
Definition at line 183 of file RORDLoader_TripDefs.cpp.
References RORDLoader_TripDefs::myNextRouteRead.
std::string GenericSAXHandler::buildErrorMessage (const SAXParseException & exception) [protected, inherited]
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters:
[in] exception The name of the currently processed file
Returns:
A string describing the given exception
Definition at line 193 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void RORDGenerator_ODAmounts::buildForTimeStep (SUMOTime time) [private]
Builds the routes for the given time step.
Definition at line 188 of file RORDGenerator_ODAmounts.cpp.
References RORDGenerator_ODAmounts::FlowDef::addRoutes(), RORDGenerator_ODAmounts::FlowDef::applicableForTime(), RORDGenerator_ODAmounts::FlowDef::getIntervalEnd(), ROAbstractRouteDefLoader::myEnd, ROTypedXMLRoutesLoader::myEnded, myFlows, and ROAbstractRouteDefLoader::myNet.
Referenced by buildRoutes().
void RORDGenerator_ODAmounts::buildRoutes (SUMOTime until) [private]
Builds the routes between the current time step and the one given.
Definition at line 178 of file RORDGenerator_ODAmounts.cpp.
References buildForTimeStep(), DELTA_T, and RORDLoader_TripDefs::myDepartureTime.
Referenced by readRoutesAtLeastUntil().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) [inherited]
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 176 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myCharactersVector.
void ROTypedXMLRoutesLoader::endDocument () [inherited]
Called when the document has ended.
Todo:
Recheck usage of route loaders; it is not very fine to have one that use a parser and other that do not
Definition at line 86 of file ROTypedXMLRoutesLoader.cpp.
References ROTypedXMLRoutesLoader::myEnded.
bool ROTypedXMLRoutesLoader::ended () const [inline, virtual, inherited]
Returns the information whether no routes are available from this loader anymore.
Returns:
Whether the whole input has been processed
Implements ROAbstractRouteDefLoader.
Definition at line 99 of file ROTypedXMLRoutesLoader.h.
References ROTypedXMLRoutesLoader::myEnded.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) [inherited]
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters:
[in] exception The occured exception to process
Exceptions:
ProcessError On any call
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by NLHandler::getLanesFromIndices().
void GenericSAXHandler::fatalError (const SAXParseException & exception) [inherited]
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions:
ProcessError On any call
Parameters:
[in] exception The occured exception to process
Definition at line 218 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
ROEdge * RORDLoader_TripDefs::getEdge (const SUMOSAXAttributes & attrs, const std::string & purpose, SumoXMLAttr which, const std::string & id, bool emptyAllowed) [protected, inherited]
Parses a named edge frm the attributes.
Definition at line 125 of file RORDLoader_TripDefs.cpp.
References RONet::getEdge(), SUMOSAXAttributes::getStringReporting(), ROAbstractRouteDefLoader::myNet, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_TO_TAZ, UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
const std::string & GenericSAXHandler::getFileName () const [inherited]
returns the current file name
Returns:
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), MSRouteLoader::init(), PCNetProjectionLoader::loadIfSet(), NILoader::loadXMLType(), MSTriggeredXMLReader::myInit(), RODFDetectorHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GUISettingsHandler::myStartElement(), RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), XMLSubSys::runParser(), and GenericSAXHandler::startElement().
SUMOTime RORDLoader_TripDefs::getLastReadTimeStep () const [inline, virtual, inherited]
Returns the time the current (last read) route starts at.
Returns:
The least time step that was read by this reader
Implements ROAbstractRouteDefLoader.
Definition at line 71 of file RORDLoader_TripDefs.h.
References RORDLoader_TripDefs::myDepartureTime.
std::string RORDLoader_TripDefs::getVehicleID (const SUMOSAXAttributes & attrs) [protected, inherited]
Parses the vehicle id.
Definition at line 111 of file RORDLoader_TripDefs.cpp.
References IDSupplier::getNext(), SUMOSAXAttributes::getOptStringReporting(), RORDLoader_TripDefs::myIdSupplier, and SUMO_ATTR_ID.
Referenced by RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) [protected, virtual, inherited]
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters:
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in ROJTRTurnDefLoader, NIImporter_ITSUMO::Handler, NIImporter_OpenDrive, NIImporter_SUMO, PCLoaderXML, PCNetProjectionLoader, and RORDLoader_SUMOBase.
Definition at line 228 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void RORDGenerator_ODAmounts::myEndElement (int element) [protected, virtual]
Called when a closing tag occurs.
Parameters:
[in] element ID of the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myEndElement
Reimplemented from RORDLoader_TripDefs.
Definition at line 269 of file RORDGenerator_ODAmounts.cpp.
References myEndFlowAmountDef(), myEndInterval(), SUMO_TAG_FLOW, and SUMO_TAG_INTERVAL.
void RORDGenerator_ODAmounts::myEndFlowAmountDef () [protected]
Closes the trip amount parsing.
!! set double in route def and flowdef?
Definition at line 287 of file RORDGenerator_ODAmounts.cpp.
References RONet::addRouteDef(), SUMOVehicleParameter::color, MsgHandler::getErrorInstance(), RONet::getVehicleTypeSecure(), SUMOVehicleParameter::id, ROAbstractRouteDefLoader::myBegin, RORDLoader_TripDefs::myBeginEdge, RORDLoader_TripDefs::myEndEdge, myFlows, myIntervalBegin, myIntervalEnd, ROAbstractRouteDefLoader::myNet, RORDLoader_TripDefs::myNextRouteRead, RORDLoader_TripDefs::myParameter, myRandom, myVehicle2InsertNumber, VEHPARS_COLOR_SET, SUMOVehicleParameter::vtypeid, SUMOVehicleParameter::wasSet(), and WRITE_ERROR.
Referenced by myEndElement().
void RORDGenerator_ODAmounts::myEndInterval () [protected]
Closes the current embedding interval.
Definition at line 280 of file RORDGenerator_ODAmounts.cpp.
References myUpperIntervalBegin, and myUpperIntervalEnd.
Referenced by myEndElement().
void RORDGenerator_ODAmounts::myStartElement (int element, const SUMOSAXAttributes & attrs) [protected, virtual]
Called on the opening of a tag;.
Parameters:
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions:
ProcessError If something fails
See also:
GenericSAXHandler::myStartElement
Reimplemented from RORDLoader_TripDefs.
Definition at line 208 of file RORDGenerator_ODAmounts.cpp.
References parseFlowAmountDef(), parseInterval(), SUMO_TAG_FLOW, and SUMO_TAG_INTERVAL.
bool RORDLoader_TripDefs::nextRouteRead () [inline, protected, virtual, inherited]
Returns the information whether a route was read
Returns:
Whether a further route was read
See also:
ROTypedXMLRoutesLoader::nextRouteRead
Implements ROTypedXMLRoutesLoader.
Definition at line 111 of file RORDLoader_TripDefs.h.
References RORDLoader_TripDefs::myNextRouteRead.
RORDGenerator_ODAmounts& RORDGenerator_ODAmounts::operator= (const RORDGenerator_ODAmounts & src) [private]
Invalidated assignment operator.
void RORDGenerator_ODAmounts::parseFlowAmountDef (const SUMOSAXAttributes & attrs) [protected]
Parses the trip amount definition.
Definition at line 220 of file RORDGenerator_ODAmounts.cpp.
References RORDLoader_TripDefs::getEdge(), SUMOSAXAttributes::getIntReporting(), SUMOSAXAttributes::getOptSUMOTimeReporting(), RORDLoader_TripDefs::getVehicleID(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, RORDLoader_TripDefs::myBeginEdge, RORDLoader_TripDefs::myEmptyDestinationsAllowed, RORDLoader_TripDefs::myEndEdge, myHaveWarnedAboutDeprecatedNumber, myIntervalBegin, myIntervalEnd, myKnownIDs, RORDLoader_TripDefs::myParameter, myUpperIntervalBegin, myUpperIntervalEnd, myVehicle2InsertNumber, SUMOVehicleParserHelper::parseVehicleAttributes(), StringUtils::replace(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_FROM, SUMO_ATTR_NO__DEPRECATED, SUMO_ATTR_NUMBER, SUMO_ATTR_TO, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void RORDGenerator_ODAmounts::parseInterval (const SUMOSAXAttributes & attrs) [protected]
Parses the interval information.
Definition at line 261 of file RORDGenerator_ODAmounts.cpp.
References SUMOSAXAttributes::getOptSUMOTimeReporting(), myUpperIntervalBegin, myUpperIntervalEnd, SUMO_ATTR_BEGIN, and SUMO_ATTR_END.
Referenced by myStartElement().
bool RORDGenerator_ODAmounts::readRoutesAtLeastUntil (SUMOTime until, bool skipping) [virtual]
Adds routes from the file until the given time is reached.
Parameters:
[in] time The time until which route definitions shall be loaded
[in] skipping Whether routes shall not be added
Returns:
Whether any errors occured
Exceptions:
ProcessError If a major error occured
See also:
ROAbstractRouteDefLoader::readRoutesAtLeastUntil
Reimplemented from ROTypedXMLRoutesLoader.
Definition at line 164 of file RORDGenerator_ODAmounts.cpp.
References buildRoutes(), ROAbstractRouteDefLoader::myBegin, RORDLoader_TripDefs::myDepartureTime, and UNUSED_PARAMETER.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) [inherited]
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 168 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildLaneSpeedTrigger().
void GenericSAXHandler::setFileName (const std::string & name) [inherited]
Sets the current file name.
Parameters:
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_OpenStreetMap::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), PCNetProjectionLoader::loadIfSet(), ROLoader::loadNet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NILoader::loadXMLType(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) [inherited]
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const SAXParseException & exception) [inherited]
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters:
[in] exception The occured exception to process
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
SUMOTime ROAbstractRouteDefLoader::myBegin [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 109 of file ROAbstractRouteDefLoader.h.
Referenced by RORDLoader_SUMOBase::closeVehicle(), myEndFlowAmountDef(), readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts().
ROEdge* RORDLoader_TripDefs::myBeginEdge [protected, inherited]
The starting edge.
Definition at line 138 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myEndElement(), myEndFlowAmountDef(), RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
SUMOTime RORDGenerator_ODAmounts::myCurrentTimeStep [private]
The current time step read.
Definition at line 196 of file RORDGenerator_ODAmounts.h.
SUMOVTypeParameter* RORDLoader_TripDefs::myCurrentVehicleType [protected, inherited]
The currently parsed vehicle type.
Definition at line 155 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myEndElement(), and RORDLoader_TripDefs::myStartElement().
SUMOTime RORDLoader_TripDefs::myDepartureTime [protected, inherited]
Definition at line 158 of file RORDLoader_TripDefs.h.
Referenced by buildRoutes(), RORDLoader_TripDefs::getLastReadTimeStep(), RORDLoader_TripDefs::myStartElement(), readRoutesAtLeastUntil(), and RORDGenerator_ODAmounts().
const bool RORDLoader_TripDefs::myEmptyDestinationsAllowed [protected, inherited]
Information whether empty destinations are allowed This is a feature used for the handling of explicit routes within the jtrrouter where the destination is not necessary.
Definition at line 146 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
SUMOTime ROAbstractRouteDefLoader::myEnd [protected, inherited]
The time for which the first route shall be loaded.
Definition at line 112 of file ROAbstractRouteDefLoader.h.
Referenced by buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), and RORDLoader_TripDefs::myEndElement().
bool ROTypedXMLRoutesLoader::myEnded [protected, inherited]
Information whether the whole file has been parsed.
Definition at line 141 of file ROTypedXMLRoutesLoader.h.
Referenced by buildForTimeStep(), ROTypedXMLRoutesLoader::endDocument(), and ROTypedXMLRoutesLoader::ended().
ROEdge* RORDLoader_TripDefs::myEndEdge [protected, inherited]
The end edge.
Definition at line 141 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myEndElement(), myEndFlowAmountDef(), RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
FlowDefV RORDGenerator_ODAmounts::myFlows [private]
The definitions of the read flows.
Definition at line 202 of file RORDGenerator_ODAmounts.h.
Referenced by buildForTimeStep(), myEndFlowAmountDef(), and ~RORDGenerator_ODAmounts().
bool RORDGenerator_ODAmounts::myHaveWarnedAboutDeprecatedNumber [private]
Definition at line 211 of file RORDGenerator_ODAmounts.h.
Referenced by parseFlowAmountDef().
bool RORDLoader_TripDefs::myHaveWarnedAboutDeprecatedTripDef [protected, inherited]
Definition at line 160 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myStartElement().
IDSupplier RORDLoader_TripDefs::myIdSupplier [protected, inherited]
generates numerical ids
Definition at line 135 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::getVehicleID().
SUMOTime RORDGenerator_ODAmounts::myIntervalBegin [private]
The begin of the interval current read.
Definition at line 181 of file RORDGenerator_ODAmounts.h.
Referenced by myEndFlowAmountDef(), and parseFlowAmountDef().
SUMOTime RORDGenerator_ODAmounts::myIntervalEnd [private]
The end of the interval current read.
Definition at line 184 of file RORDGenerator_ODAmounts.h.
Referenced by myEndFlowAmountDef(), and parseFlowAmountDef().
std::set<std::string> RORDGenerator_ODAmounts::myKnownIDs [private]
A storage for ids (!!! this should be done router-wide).
Definition at line 205 of file RORDGenerator_ODAmounts.h.
Referenced by parseFlowAmountDef().
RONet& ROAbstractRouteDefLoader::myNet [protected, inherited]
The network to add routes to.
Definition at line 106 of file ROAbstractRouteDefLoader.h.
Referenced by buildForTimeStep(), RORDLoader_SUMOBase::closeVehicle(), RORDLoader_TripDefs::getEdge(), RORDLoader_SUMOBase::myCharacters(), RORDLoader_TripDefs::myEndElement(), RORDLoader_SUMOBase::myEndElement(), and myEndFlowAmountDef().
bool RORDLoader_TripDefs::myNextRouteRead [protected, inherited]
The information whether the next route was read.
Definition at line 152 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::beginNextRoute(), RORDLoader_TripDefs::myEndElement(), myEndFlowAmountDef(), and RORDLoader_TripDefs::nextRouteRead().
SUMOVehicleParameter* RORDLoader_TripDefs::myParameter [protected, inherited]
Definition at line 157 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myEndElement(), myEndFlowAmountDef(), RORDLoader_TripDefs::myStartElement(), and parseFlowAmountDef().
SAX2XMLReader* ROTypedXMLRoutesLoader::myParser [protected, inherited]
The parser used.
Definition at line 135 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts(), ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader(), and ROTypedXMLRoutesLoader::~ROTypedXMLRoutesLoader().
bool RORDGenerator_ODAmounts::myRandom [private]
Information whether randomized departures are used.
Definition at line 208 of file RORDGenerator_ODAmounts.h.
Referenced by myEndFlowAmountDef().
XMLPScanToken ROTypedXMLRoutesLoader::myToken [protected, inherited]
Information about the current position within the file.
Definition at line 138 of file ROTypedXMLRoutesLoader.h.
Referenced by ROTypedXMLRoutesLoader::readRoutesAtLeastUntil(), RORDGenerator_ODAmounts(), and ROTypedXMLRoutesLoader::ROTypedXMLRoutesLoader().
SUMOTime RORDGenerator_ODAmounts::myUpperIntervalBegin [private]
The begin of the embedding interval (if given).
Definition at line 187 of file RORDGenerator_ODAmounts.h.
Referenced by myEndInterval(), parseFlowAmountDef(), and parseInterval().
SUMOTime RORDGenerator_ODAmounts::myUpperIntervalEnd [private]
The end of the embedding interval (if given).
Definition at line 190 of file RORDGenerator_ODAmounts.h.
Referenced by myEndInterval(), parseFlowAmountDef(), and parseInterval().
unsigned int RORDGenerator_ODAmounts::myVehicle2InsertNumber [private]
The number of vehicles to insert.
Definition at line 193 of file RORDGenerator_ODAmounts.h.
Referenced by myEndFlowAmountDef(), and parseFlowAmountDef().
const bool RORDLoader_TripDefs::myWithTaz [protected, inherited]
Information whether zones (districts) are used as origins / destinations.
Definition at line 149 of file RORDLoader_TripDefs.h.
Referenced by RORDLoader_TripDefs::myStartElement().
The documentation for this class was generated from the following files:
RORDGenerator_ODAmounts.h
RORDGenerator_ODAmounts.cpp